# -*- coding: utf-8 -*-
"""DE M19 — Data modeling and warehousing."""

M19 = ("Data Modeling and Warehousing", 189, 202, """| | |
|---|---|
| **Objective cấp module** | Thiết kế một lược đồ kho dữ liệu từ mô tả nghiệp vụ, phát biểu và kiểm chứng được hạt của mọi bảng, và bàn giao nó cho người dựng mart mà không phải giải thích thêm |
| **Tiền đề** | M18 |
| **Exit criterion** | Lược đồ sao cài đặt được, có chiều thay đổi chậm và bảng lịch, và đạt rà soát chéo về khả năng bàn giao |
| **Kỹ năng SFIA** | `DTAN` mức 4 · `DBAD` mức 3 |
| **Chế độ hỏng** | Thiết kế đẹp trên giấy mà không khai báo được hạt bằng một câu, nên mọi bảng phía sau kế thừa sự mơ hồ đó |""",
"""Ranh giới với chương trình Analytics Engineer: Data Engineer thiết kế và bàn giao tập dữ liệu có hợp đồng; mart theo miền nghiệp vụ, semantic layer và định nghĩa chỉ số thuộc về Analytics Engineer. Module này dạy mô hình chiều đủ sâu để bàn giao đúng, không dạy để sở hữu mart. Bảy bài đầu là mô hình hoá, bốn bài giữa là kiến trúc phân lớp và bàn giao, hai bài cuối là thiết kế vật lý và dự án.""")

L19 = [
(189,"Normalization and where denormalization is deliberate","LT","Module 19: M18",
"Ba dị thường thao tác và cách dạy đi từ dị thường quan sát được tới quy tắc, không theo chiều ngược lại: gặp một bảng phẳng rồi thử thêm, sửa, xoá và thấy nó hỏng ở đâu. Phụ thuộc hàm và cách phát hiện từ chính dữ liệu bằng truy vấn đếm. Dạng chuẩn một và giá trị nguyên tử: một cột chứa danh sách ngăn bởi dấu phẩy làm mọi phép lọc và gộp theo phần tử trở nên không tin được. Dạng chuẩn hai và phụ thuộc đầy đủ vào khoá. Dạng chuẩn ba và phụ thuộc bắc cầu. Dạng chuẩn Boyce Codd ở mức nhận biết. Phi chuẩn hoá có chủ đích: điều kiện áp dụng, chi phí đi kèm, và điều kiện bắt buộc là phải có cơ chế giữ cho bản sao nhất quán. Phân biệt phi chuẩn hoá có chủ đích với thiếu chuẩn hoá do không biết: cái đầu có tài liệu nêu lý do, cái sau thì không.",
"Chuẩn hoá một bảng phẳng tới dạng chuẩn ba và chỉ ra dị thường nào được loại bỏ ở bước nào.",
"Tầng *áp dụng*. Objective là một thủ tục có tiêu chí đúng sai rõ. Đạt khi lược đồ kết quả không còn phụ thuộc bắc cầu nào, kiểm bằng truy vấn phát hiện phụ thuộc hàm, và khi ba dị thường được gán đúng bước loại bỏ chúng.",
"Nhận bảng phẳng 40 cột chứa đơn hàng, khách, sản phẩm và địa chỉ. Thử ba thao tác gây dị thường và ghi lại hỏng thế nào. Chuẩn hoá từng bước tới dạng chuẩn ba, sau mỗi bước chạy truy vấn phát hiện phụ thuộc hàm còn lại. Tìm một cột chứa danh sách và tách nó ra.",
"Chuẩn hoá theo quy tắc mà không kiểm phụ thuộc hàm trên dữ liệu thật · phi chuẩn hoá mà không ghi lý do · để cột chứa danh sách ngăn bởi dấu phẩy.",
"Lược đồ kết quả không còn phụ thuộc bắc cầu kiểm bằng truy vấn, và ba dị thường gán đúng bước loại bỏ."),

(190,"OLTP against OLAP - access patterns decide structure","LT","Lesson 189",
"Sáu chiều khác biệt giữa hệ thống giao dịch và hệ thống phân tích: mẫu truy cập, mức chuẩn hoá, hạt dữ liệu, tần suất ghi, nhóm người dùng, và chỉ số hiệu năng mục tiêu. Mỗi chiều dẫn ra một quyết định thiết kế khác nhau, nên cùng một dữ liệu có hai lược đồ hợp lý khác nhau ở hai nơi, và đây là lý do sao chép nguyên lược đồ giao dịch sang kho phân tích luôn cho kết quả tệ. Lưu theo dòng so với lưu theo cột và hệ quả lên phép gộp, nối lại lesson 41 và 169. Hậu quả vận hành của việc chạy báo cáo nặng trên hệ thống sản xuất: tranh chấp khoá ở lesson 116, ô nhiễm bộ đệm ở lesson 110, và độ trễ tăng cho giao dịch. Kho dữ liệu, hồ dữ liệu và lakehouse ở mức thuật ngữ đủ để trao đổi, chi tiết ở M34. Bốn mức độ trễ dữ liệu và chi phí tương ứng, cùng nguyên tắc chọn mức thấp nhất mà nghiệp vụ thật sự cần.",
"Chọn loại hệ thống cho một tình huống cho trước và biện minh bằng ít nhất ba trong sáu chiều khác biệt.",
"Tầng *đánh giá*. Objective đòi chọn có biện minh nhiều chiều. Kiểm bằng bốn tình huống; đạt khi chọn đúng cả bốn và mỗi lần nêu ít nhất ba chiều, không chấp nhận lý do chung như phân tích thì dùng kho.",
"Nhận bốn tình huống có yêu cầu độ trễ và mẫu truy cập khác nhau. Chọn loại hệ thống và nêu ba chiều cho từng cái. Sau đó chạy một báo cáo gộp nặng trên PostgreSQL đang có tải giao dịch, đo độ trễ giao dịch trước và trong lúc chạy báo cáo.",
"Sao chép nguyên lược đồ giao dịch sang kho phân tích · chọn độ trễ thấp nhất có thể thay vì mức nghiệp vụ cần · chạy báo cáo trên bản chính vì tiện.",
"Chọn đúng cả bốn tình huống, mỗi lần nêu ít nhất ba chiều, và có số đo tác động lên độ trễ giao dịch."),

(191,"Dimensional modeling - the four Kimball steps","LT","Lesson 190",
"Bốn bước theo thứ tự cố định: chọn quy trình nghiệp vụ, khai báo hạt, xác định chiều, xác định độ đo. Thứ tự này không đảo được, và bước hai là bước chặn: chọn sai hạt thì ba bước sau đều phải làm lại. Chọn quy trình nghiệp vụ nghĩa là chọn một sự kiện nghiệp vụ có thật, không chọn một phòng ban hay một báo cáo; chọn theo báo cáo là sai lầm phổ biến vì báo cáo đổi còn quy trình thì không. Bảng sự kiện chứa khoá ngoại và độ đo, không chứa thuộc tính mô tả. Bảng chiều rộng, phi chuẩn, giàu thuộc tính, và cố ý lặp dữ liệu vì mục tiêu là đọc nhanh và đọc dễ chứ không phải tiết kiệm dung lượng. Vì sao mô hình chiều vẫn sống sau ba mươi năm dù phần cứng đã đổi hoàn toàn: nó tối ưu cho khả năng hiểu của con người, và đó là ràng buộc không đổi theo phần cứng. Ranh giới trong chương trình: Data Engineer dựng lớp này để bàn giao, Analytics Engineer dựng mart lên trên.",
"Áp bốn bước lên một mô tả nghiệp vụ và phát biểu hạt của bảng sự kiện bằng một câu không mơ hồ.",
"Tầng *áp dụng*. Objective có sản phẩm kiểm được bằng rà soát. Đạt khi phát biểu hạt là một câu có dạng một dòng là một sự kiện gì, và khi một học viên khác đọc câu đó rồi suy ra đúng bảng sự kiện có bao nhiêu dòng cho một tập dữ liệu mẫu.",
"Nhận mô tả nghiệp vụ giao hàng. Áp bốn bước theo thứ tự. Viết phát biểu hạt bằng một câu. Đổi bài chéo: người khác đọc câu đó và dự đoán số dòng bảng sự kiện cho tập mẫu 1.000 sự kiện. So dự đoán với số thật. Thử chọn quy trình theo một báo cáo và chỉ ra nó hỏng ở đâu khi báo cáo đổi.",
"Chọn quy trình nghiệp vụ theo một báo cáo có sẵn · nhảy sang xác định chiều trước khi khai báo hạt · đặt thuộc tính mô tả vào bảng sự kiện.",
"Phát biểu hạt là một câu, và người khác suy ra đúng số dòng bảng sự kiện từ câu đó."),

(192,"Declaring the grain and verifying it","TH","Lesson 191",
"Hạt là phát biểu về ý nghĩa của một dòng, và nó phải kiểm chứng được chứ không chỉ phát biểu được. Ba cách kiểm chứng và cái mỗi cách bắt: đếm số dòng phân biệt theo tập cột định danh hạt phải bằng tổng số dòng, phép đếm theo nhóm không được ra nhóm nào lớn hơn một, và tổng một độ đo cộng được phải khớp tổng ở nguồn. Phát biểu hạt sai theo hai hướng: mịn hơn thực tế làm bảng có dòng trùng, thô hơn thực tế làm mất chi tiết không lấy lại được. Hướng thứ hai không có cách sửa ngoài làm lại từ nguồn, nên nó tốn kém hơn. Hạt thay đổi khi nghiệp vụ thay đổi và quy trình xử lý: tạo bảng mới thay vì sửa hạt bảng cũ. Trộn hai hạt trong một bảng và cách phát hiện: một cột độ đo có giá trị lặp lại theo nhóm là dấu hiệu. Hạt của bảng chiều cũng phải khai báo và hay bị bỏ qua.",
"Kiểm chứng phát biểu hạt bằng ba phép kiểm, và phát hiện một bảng bị trộn hai hạt trong một tập dữ liệu cho trước.",
"Tầng *phân tích*. Objective đòi phát hiện lỗi hạt chứ không chỉ khai báo. Đạt khi ba phép kiểm chạy được trên năm bảng, và khi phát hiện đúng bảng bị trộn hạt cùng chỉ ra cột nào lặp lại theo nhóm làm bằng chứng.",
"Nhận năm bảng, trong đó một bảng trộn hai hạt và một bảng có phát biểu hạt mịn hơn thực tế. Chạy ba phép kiểm cho từng bảng. Định vị hai bảng có vấn đề. Với bảng trộn hạt, chỉ cột lặp lại và đề xuất tách. Viết ba phép kiểm thành truy vấn dùng lại được cho bảng bất kỳ.",
"Phát biểu hạt rồi không kiểm · sửa hạt của bảng đang có người dùng thay vì tạo bảng mới · bỏ qua hạt của bảng chiều.",
"Ba phép kiểm chạy trên năm bảng, và bảng trộn hạt được phát hiện kèm cột lặp làm bằng chứng."),

(193,"Fact tables - three types and additivity","TH","Lesson 192",
"Ba loại bảng sự kiện và điều kiện dùng từng loại: giao dịch ghi một dòng cho mỗi sự kiện, ảnh chụp định kỳ ghi trạng thái theo chu kỳ cố định, và ảnh chụp tích luỹ ghi một dòng cho mỗi thực thể rồi cập nhật khi nó qua các mốc. Loại thứ ba là loại duy nhất trong ba loại có cập nhật, nên nó phá vỡ giả định chỉ chèn thêm của phần lớn kiến trúc và phải xử lý riêng. Ba loại độ đo theo tính cộng được: cộng được theo mọi chiều, bán cộng được không cộng theo thời gian như số dư và tồn kho, và không cộng được như tỉ lệ và phần trăm. Hậu quả khi cộng nhầm: cộng số dư theo thời gian ra con số vô nghĩa nhưng trông hợp lý, và đây là lỗi báo cáo hay gặp. Độ đo phái sinh và nơi nên tính chúng: tính ở tầng bàn giao hay để Analytics Engineer tính, cùng tiêu chí chọn. Bảng sự kiện không có độ đo cho sự kiện chỉ cần đếm.",
"Phân loại độ đo theo tính cộng được và chọn đúng loại bảng sự kiện cho ba bài toán, nêu hậu quả khi chọn sai.",
"Tầng *áp dụng*. Objective gồm hai phép phân loại có đáp án. Đạt khi phân loại đúng ít nhất 10 trên 12 độ đo, chọn đúng loại bảng cho cả ba bài toán, và khi tính được con số sai sinh ra từ việc cộng nhầm một độ đo bán cộng được.",
"Nhận 12 độ đo và phân loại theo tính cộng được. Nhận ba bài toán: đơn hàng, số dư tài khoản cuối ngày, và đơn hàng qua năm mốc trạng thái. Chọn loại bảng cho từng cái. Cộng số dư theo thời gian trên tập thật và so với cách tính đúng, ghi lại chênh lệch.",
"Cộng độ đo bán cộng được theo thời gian · dùng bảng giao dịch cho bài toán theo dõi qua các mốc · lưu tỉ lệ vào bảng sự kiện rồi cộng chúng.",
"Phân loại đúng ít nhất 10 trên 12 độ đo, chọn đúng ba loại bảng, và tính được chênh lệch do cộng nhầm."),

(194,"Dimension tables and surrogate keys","TH","Lesson 193",
"Bảng chiều rộng và giàu thuộc tính, và lý do thêm thuộc tính rẻ hơn nhiều so với thêm bảng: mỗi thuộc tính là một cách cắt lát dữ liệu mà người dùng không phải kết thêm. Khoá thay thế là khoá do kho sinh ra, tách khỏi khoá nghiệp vụ của hệ nguồn, và ba lý do cần nó: hệ nguồn có thể tái dùng khoá, hợp nhất nhiều nguồn có khoá trùng, và chiều thay đổi chậm cần nhiều dòng cho cùng một thực thể, nối tới lesson 195. Khoá băm từ khoá nghiệp vụ và đánh đổi: tính được ở nhiều nơi nên không cần tra cứu, nhưng cạm bẫy khi băm từ cột có thể rỗng vì hai bản ghi khác nhau ra cùng băm. Chuẩn hoá giá trị rỗng trước khi băm là bắt buộc. Chiều dùng chung giữa nhiều bảng sự kiện và vì sao nó là điều kiện để so sánh chéo. Chiều rác gom các cờ bản số thấp. Chiều suy biến là khoá nghiệp vụ giữ lại trong bảng sự kiện. Chiều vai trò dùng một bảng cho nhiều vai trò.",
"Thiết kế bảng chiều dùng chung được cho nhiều bảng sự kiện, và chứng minh khoá băm xử lý đúng trường hợp có giá trị rỗng.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm. Đạt khi chiều dùng được cho hai bảng sự kiện khác nhau mà không phải đổi, và khi thực nghiệm cho thấy khoá băm không chuẩn hoá giá trị rỗng sinh ra va chạm còn bản chuẩn hoá thì không.",
"Thiết kế chiều khách hàng dùng chung cho bảng sự kiện đơn hàng và bảng sự kiện hỗ trợ. Sinh khoá băm từ ba cột trong đó một cột có giá trị rỗng. Chạy trên 1 triệu bản ghi và đếm va chạm. Chuẩn hoá giá trị rỗng rồi chạy lại. Tạo một chiều rác từ năm cờ bản số thấp.",
"Băm từ cột có thể rỗng mà không chuẩn hoá · dùng khoá nghiệp vụ làm khoá chiều · tạo bảng chiều riêng cho mỗi bảng sự kiện.",
"Chiều dùng được cho hai bảng sự kiện không phải đổi, và thực nghiệm cho thấy khác biệt va chạm trước sau chuẩn hoá."),

(195,"Slowly changing dimensions - types and implementation","TH","Lesson 194",
"Bài toán phát biểu bằng một ví dụ định lượng được: khách chuyển từ vùng A sang vùng B, và nếu bảng chiều ghi đè thì toàn bộ doanh thu lịch sử của khách đó nhảy sang vùng B, làm báo cáo theo vùng của mọi kỳ trước đổi. Bốn loại xử lý và hậu quả báo cáo cụ thể của từng loại: loại không cho đổi, loại ghi đè mất lịch sử, loại thêm dòng mới giữ lịch sử, và loại thêm cột giữ một giá trị trước đó. Cài đặt loại thêm dòng mới bằng khoá thay thế cộng ba cột hiệu lực từ, hiệu lực đến, và cờ bản ghi hiện hành. Mẫu tải: phát hiện thay đổi bằng so sánh cột hoặc bằng dấu thời gian, đóng dòng cũ, mở dòng mới, và cả ba bước phải trong một giao dịch. Truy vấn trạng thái hiện hành so với truy vấn tại một thời điểm trong quá khứ. Chọn loại nào là quyết định nghiệp vụ chứ không kỹ thuật, và phải hỏi người dùng dữ liệu.",
"Cài đặt chiều thay đổi chậm loại thêm dòng mới, và chứng minh báo cáo lịch sử không đổi sau khi thuộc tính chiều thay đổi.",
"Tầng *áp dụng*. Objective có tiêu chí đối chứng tuyệt đối. Đạt khi báo cáo doanh thu theo vùng cho ba kỳ quá khứ cho kết quả y hệt trước và sau khi 10% khách đổi vùng, và khi truy vấn tại một thời điểm trong quá khứ trả về đúng trạng thái của thời điểm đó.",
"Dựng chiều khách hàng loại thêm dòng mới. Chạy báo cáo doanh thu theo vùng ba kỳ, ghi kết quả. Cho 10% khách đổi vùng và chạy tải chiều. Chạy lại báo cáo và so từng dòng. Truy vấn trạng thái khách tại một ngày trong quá khứ. Thử cài bằng loại ghi đè và ghi lại chênh lệch.",
"Dùng loại ghi đè cho thuộc tính mà báo cáo lịch sử phụ thuộc · quên cờ bản ghi hiện hành nên truy vấn hiện tại phải lọc theo ngày · đóng dòng cũ và mở dòng mới ngoài giao dịch.",
"Báo cáo ba kỳ quá khứ không đổi sau khi 10% khách đổi vùng, và truy vấn tại thời điểm quá khứ trả đúng trạng thái."),

(196,"The calendar dimension and Vietnamese fiscal reality","TH","Lesson 195",
"Bảng lịch thường là bảng chiều đầu tiên được dựng trong một kho dữ liệu, vì gần như mọi bảng sự kiện đều kết với nó. Cách sinh bằng script có hạt giống cố định thay vì nhập tay. Tập thuộc tính tối thiểu: ngày, tuần, tháng, quý, năm theo lịch dương; ngày làm việc và ngày nghỉ; tuần theo chuẩn quốc tế; và các thuộc tính theo năm tài chính khi nó lệch năm dương lịch. Đặc thù Việt Nam mà bảng lịch mẫu nước ngoài không có: Tết âm lịch dịch chuyển giữa tháng dương lịch nên phép so cùng kỳ năm trước theo tháng dương bị lệch nặng ở quý một, và cách xử lý là thêm thuộc tính đánh dấu kỳ Tết cùng ngày tương ứng năm trước theo âm lịch. Ngày nghỉ bù và tuần làm việc sáu ngày ở một số ngành. Chiều vai trò: cùng bảng lịch dùng cho ngày đặt, ngày giao và ngày thanh toán, nối lại lesson 194. Chiều thời gian trong ngày tách riêng khi cần phân tích theo giờ.",
"Dựng bảng lịch đầy đủ cho doanh nghiệp Việt Nam, và chứng minh phép so cùng kỳ năm trước không bị Tết âm lịch làm lệch.",
"Tầng *áp dụng*. Objective có tiêu chí đối chứng trên một ca khó và đặc thù. Đạt khi phép so cùng kỳ cho quý một của ba năm liên tiếp khớp bản đối chứng tính theo kỳ Tết, và khi bảng lịch dùng được làm chiều vai trò cho ba cột ngày khác nhau.",
"Sinh bảng lịch 10 năm bằng script. Thêm thuộc tính Tết âm lịch cho ba năm. Chạy báo cáo so cùng kỳ quý một theo tháng dương và theo kỳ Tết, so hai kết quả với bản đối chứng. Dùng bảng lịch làm chiều vai trò cho ngày đặt, ngày giao, ngày thanh toán trong cùng một truy vấn.",
"Dùng bảng lịch mẫu nước ngoài không có Tết · so cùng kỳ theo tháng dương cho quý một · tạo ba bảng lịch riêng cho ba vai trò ngày.",
"So cùng kỳ quý một ba năm khớp bản đối chứng, và bảng lịch dùng được cho ba vai trò ngày."),

(197,"Star schema against snowflake and the bus matrix","TH","Lesson 196",
"Lược đồ sao đặt bảng sự kiện ở giữa và các chiều phi chuẩn xung quanh; lược đồ bông tuyết chuẩn hoá tiếp các chiều thành nhiều bảng. Bông tuyết sạch hơn về lý thuyết nhưng thực hành thiên về sao, và ba lý do: ít phép kết hơn nên truy vấn nhanh và dễ viết, người dùng hiểu được cấu trúc mà không cần sơ đồ, và dung lượng tiết kiệm được từ chuẩn hoá chiều là không đáng kể so với bảng sự kiện. Điều kiện bị ép dùng bông tuyết: chiều rất lớn có thuộc tính lặp nhiều, hoặc công cụ hạ nguồn yêu cầu. Ma trận xe buýt là bảng quy trình nghiệp vụ nhân chiều dùng chung, và nó là công cụ lập kế hoạch: mỗi ô đánh dấu cho biết hai quy trình nào so sánh chéo được với nhau. Nhiều bảng sự kiện ở hạt khác nhau và cách so sánh chúng: không kết trực tiếp mà gộp từng bảng về hạt chung rồi mới kết, vì kết trực tiếp gây nhân dòng, nối lại lesson 100.",
"Chuyển một lược đồ chuẩn hoá thành lược đồ sao, lập ma trận xe buýt, và so sánh hai bảng sự kiện khác hạt mà không nhân dòng.",
"Tầng *áp dụng*. Objective gồm ba sản phẩm, trong đó cái thứ ba có tiêu chí đúng sai tuyệt đối. Đạt khi lược đồ sao cài đặt được và trả lời được năm câu hỏi phân tích, khi ma trận xe buýt chỉ ra đúng chiều dùng chung, và khi phép so hai bảng sự kiện cho kết quả khớp bản đối chứng.",
"Chuyển lược đồ chuẩn hoá 12 bảng thành lược đồ sao. Trả lời năm câu hỏi phân tích trên nó. Lập ma trận xe buýt cho ba quy trình nghiệp vụ. So sánh bảng sự kiện đơn hàng với bảng sự kiện trả hàng ở hai hạt khác nhau, đối chiếu bản đối chứng. Thử kết trực tiếp và ghi lại số dòng bị nhân.",
"Kết trực tiếp hai bảng sự kiện khác hạt · chuẩn hoá chiều vì thấy dữ liệu lặp · lập ma trận xe buýt sau khi đã xây xong thay vì trước.",
"Lược đồ sao trả lời được năm câu hỏi, ma trận xe buýt đúng chiều dùng chung, và phép so hai bảng khớp đối chứng."),

(198,"Medallion layers - raw, cleaned, curated","LT","Lesson 197",
"Ba lớp và trách nhiệm tách bạch của từng lớp. Lớp thô giữ nguyên như nguồn, không sửa gì, và mục đích duy nhất là tái tạo được mọi thứ phía sau từ nó; hệ quả là nó chỉ chèn thêm và không bao giờ ghi đè, nối tới lesson 206. Lớp sạch làm chuẩn hoá kiểu, chuẩn hoá giá trị rỗng, khử trùng, và áp quy tắc chất lượng; nó vẫn giữ hạt của nguồn và chưa có logic nghiệp vụ. Lớp phục vụ là nơi mô hình chiều ở bảy bài trước sống, và nó hướng người dùng dữ liệu. Ranh giới hay bị vi phạm nhất là đưa logic nghiệp vụ vào lớp sạch, làm lớp đó không dùng lại được cho mục đích khác. Ba câu hỏi để kiểm một phép biến đổi thuộc lớp nào. Quy ước đặt tên cho từng lớp. Ranh giới bàn giao với Analytics Engineer thường đặt ở cuối lớp sạch hoặc đầu lớp phục vụ, và đặt ở đâu là thoả thuận giữa hai vai trò chứ không có đáp án chung.",
"Phân loại 15 phép biến đổi vào đúng lớp, và nêu ranh giới bàn giao phù hợp cho hai kiểu tổ chức khác nhau.",
"Tầng *hiểu*. Objective là phân loại theo tiêu chí và một phán đoán về ranh giới tổ chức. Đạt khi phân loại đúng ít nhất 12 trên 15, và khi hai ranh giới bàn giao đề xuất đều nêu được hậu quả cho cả hai vai trò.",
"Nhận 15 phép biến đổi: ép kiểu ngày, khử trùng theo khoá nghiệp vụ, tính doanh thu thuần sau chiết khấu, chuẩn hoá tên tỉnh, gán phân khúc khách, và các phép khác. Phân loại vào ba lớp. Với hai kiểu tổ chức khác nhau, đề xuất ranh giới bàn giao và nêu hậu quả.",
"Đưa logic nghiệp vụ vào lớp sạch · ghi đè lớp thô khi nguồn sửa dữ liệu · đặt ranh giới bàn giao mà không thoả thuận với vai trò bên kia.",
"Phân loại đúng ít nhất 12 trên 15, và hai ranh giới bàn giao đều nêu hậu quả cho cả hai vai trò."),

(199,"Data Vault at a level sufficient to recognise it","LT","Lesson 198",
"Ba loại bảng và việc của từng cái: bảng trung tâm giữ khoá nghiệp vụ, bảng liên kết giữ quan hệ giữa các khoá, và bảng vệ tinh giữ thuộc tính kèm dấu thời gian. Mục tiêu thiết kế khác hẳn mô hình chiều: nó tối ưu cho khả năng nạp song song, khả năng kiểm toán, và khả năng thêm nguồn mới mà không sửa cấu trúc cũ, đổi lấy việc truy vấn phức tạp hơn nhiều. Hệ quả: nó không phải lớp phục vụ, nó là lớp trung gian, và vẫn cần dựng mô hình chiều lên trên để người dùng đọc được. Điều kiện một tổ chức nên cân nhắc: nhiều nguồn có khoá nghiệp vụ chồng lấn, yêu cầu kiểm toán chặt, và đội đủ lớn để chịu chi phí phức tạp. Điều kiện không nên: đội nhỏ, ít nguồn, hoặc chưa có mô hình chiều chạy được. Mức yêu cầu của bài là nhận ra một lược đồ dạng này khi gặp và nêu được ba loại bảng, không phải thiết kế một cái.",
"Nhận ra một lược đồ dạng này khi gặp và nêu điều kiện tổ chức nào nên cân nhắc nó, cùng cái nó đánh đổi.",
"Tầng *hiểu*. Objective ở mức nhận biết, vì thiết kế một lược đồ dạng này vượt phạm vi Data Engineer bàn giao dữ liệu. Đạt khi phân loại đúng ba loại bảng trong một lược đồ mẫu, và khi nêu được ba điều kiện nên và hai điều kiện không nên, mỗi cái kèm lý do.",
"Đọc một lược đồ mẫu 15 bảng và phân loại từng bảng vào ba loại. Viết một truy vấn lấy trạng thái hiện tại của một thực thể từ lược đồ đó và so độ phức tạp với truy vấn tương đương trên lược đồ sao. Viết nửa trang nêu điều kiện nên và không nên.",
"Kết luận nó tốt hơn mô hình chiều · coi nó là lớp phục vụ cho người dùng cuối · đề xuất nó cho đội bốn người chưa có kho chạy được.",
"Phân loại đúng ba loại bảng trong lược đồ mẫu, và nêu ba điều kiện nên cùng hai điều kiện không nên kèm lý do."),

(200,"Modelling for handover - what the Analytics Engineer needs","TH","Lesson 199",
"Sản phẩm bàn giao của Data Engineer là tập dữ liệu có hợp đồng, và bài này định nghĩa hợp đồng đó ở phần mô hình. Mười một khai báo mà người nhận cần, nối tới lesson 216 nơi chúng thành hợp đồng đầy đủ: hạt, khoá nghiệp vụ, lược đồ và kiểu, múi giờ, ngữ nghĩa của cập nhật và xoá, độ tươi, mức đầy đủ, mức chính xác, lineage, chủ sở hữu, và thời gian lưu giữ. Ba khai báo hay bị bỏ nhất và hậu quả: ngữ nghĩa cập nhật và xoá không rõ làm người nhận không biết dữ liệu có thay đổi hồi tố không; múi giờ không khai báo làm mọi phép gộp theo ngày lệch; và mức chính xác không nêu làm người nhận tưởng số đã đối soát. Cung cấp dữ liệu mẫu cố định cho người nhận viết kiểm thử, nối lại lesson 84. Tài liệu cột viết cho người không có ngữ cảnh. Thông báo trước khi đổi lược đồ và thời gian chuyển tiếp. Vì sao bàn giao tốt rẻ hơn nhiều so với trả lời câu hỏi lặp lại.",
"Bàn giao một tập dữ liệu kèm mười một khai báo, và chứng minh người nhận dựng được mart lên trên mà không đặt câu hỏi nào.",
"Tầng *đánh giá*. Objective đo bằng người nhận thật chứ không bằng danh sách đã điền. Kiểm bằng quan sát: một học viên khác nhận tập dữ liệu và tài liệu, dựng một mart nhỏ, ghi lại mọi câu phải hỏi. Đạt khi không quá một câu hỏi và khi mart dựng ra cho số khớp bản đối chứng.",
"Bàn giao ba bảng của lược đồ sao ở lesson 197 kèm mười một khai báo và dữ liệu mẫu cố định. Người nhận dựng một mart doanh thu theo vùng và ghi lại mọi câu hỏi. So số của mart với bản đối chứng. Sửa tài liệu theo câu hỏi rồi bàn giao lại cho người thứ hai.",
"Bỏ khai báo ngữ nghĩa cập nhật và xoá · viết tài liệu cột bằng cách chép lại tên cột · bàn giao mà không kèm dữ liệu mẫu cố định.",
"Người nhận đặt không quá một câu hỏi và mart dựng ra khớp bản đối chứng."),

(201,"Warehouse physical design - partitioning, clustering, sort keys","TH","Lesson 200",
"Thiết kế logic ở chín bài trước quyết định đúng đắn; thiết kế vật lý quyết định chi phí và tốc độ, và hai thứ này tách bạch được. Ba đòn bẩy và ánh xạ sang từng hệ đã học: phân vùng ở lesson 115 và 130, phân cụm hoặc khoá sắp xếp ở lesson 161 và 168, và chọn kiểu dữ liệu hẹp ở lesson 169. Chọn khoá phân vùng cho bảng sự kiện: cột ngày của sự kiện nghiệp vụ chứ không phải ngày nạp, và lý do là truy vấn lọc theo ngày nghiệp vụ. Ngoại lệ khi hai ngày lệch nhau nhiều do dữ liệu tới muộn, nối tới lesson 205. Bảng chiều thường nhỏ nên không cần phân vùng, và phát tán chúng tới mọi nút trong hệ phân tán. Nén và ảnh hưởng của thứ tự sắp xếp lên tỉ lệ nén. Đo trước khi tối ưu và đo lại sau, nối lại lesson 17. Thiết kế vật lý phụ thuộc hệ đích nên phải làm sau khi chọn hệ ở M18, không làm trước.",
"Thiết kế vật lý cho một lược đồ sao trên hai hệ đích khác nhau, và chứng minh cải thiện bằng số đo riêng cho từng đòn bẩy.",
"Tầng *đánh giá*. Objective đòi chọn có đánh đổi và đo riêng từng thay đổi. Đạt khi ba đòn bẩy đều có số đo riêng trên cả hai hệ, và khi lựa chọn khoá phân vùng được biện minh bằng mẫu truy vấn chứ bằng thói quen.",
"Nạp lược đồ sao 100 triệu dòng vào hai hệ đích. Áp ba đòn bẩy từng cái một, đo sau mỗi bước trên cả hai hệ. So khoá phân vùng theo ngày nghiệp vụ với theo ngày nạp trên bộ sáu truy vấn. Đo ảnh hưởng của thứ tự sắp xếp lên tỉ lệ nén.",
"Phân vùng theo ngày nạp · làm thiết kế vật lý trước khi chọn hệ đích · gộp ba đòn bẩy rồi đo một lần.",
"Ba đòn bẩy có số đo riêng trên cả hai hệ, và lựa chọn khoá phân vùng biện minh bằng mẫu truy vấn."),

(202,"Modeling and loading project","DA","Lesson 201",
"Không có nội dung mới. Dự án gộp M19: nhận một cơ sở dữ liệu nguồn chuẩn hoá, thiết kế và cài đặt lược đồ sao đầy đủ, dựng ba lớp theo lesson 198, và bàn giao theo lesson 200. Yêu cầu đầu ra: phát biểu hạt kiểm chứng được cho mọi bảng, ít nhất một chiều thay đổi chậm loại thêm dòng mới, bảng lịch có xử lý Tết âm lịch, pipeline nạp gia tăng chạy lại được, và bộ kiểm chứng ba phép kiểm hạt ở lesson 192 chạy tự động. Tiêu chí đối soát: tổng độ đo cộng được trong bảng sự kiện khớp tổng ở nguồn cho cả ba kỳ, và chạy lại pipeline hai lần cho kết quả bằng chạy một lần.",
"Thiết kế và cài đặt một kho dữ liệu ba lớp từ một nguồn chuẩn hoá, và chứng minh đối soát khớp cùng tính bất biến khi chạy lại.",
"Tầng *sáng tạo*. Objective là thiết kế một hệ dưới nhiều ràng buộc. Chấm theo năm mục: phát biểu và kiểm chứng hạt 25đ, mô hình chiều và chiều thay đổi chậm 25đ, pipeline nạp bất biến 20đ, đối soát khớp 20đ, tài liệu bàn giao 10đ. Đạt khi ≥ 70/100 và mục đối soát ≥ 70% của nó.",
"Nhận cơ sở dữ liệu nguồn 15 bảng, 50 triệu dòng. Thiết kế lược đồ sao, cài ba lớp, viết pipeline nạp gia tăng. Chạy hai lần và đối soát. Nộp bộ kiểm chứng hạt chạy tự động và tài liệu bàn giao mười một khai báo.",
"Bỏ lớp thô để tiết kiệm dung lượng · phát biểu hạt mà không viết phép kiểm tự động · đối soát một kỳ rồi kết luận.",
"Đạt ≥ 70/100, mục đối soát ≥ 70%, và chạy hai lần cho kết quả bằng chạy một lần."),
]
