# -*- coding: utf-8 -*-
"""DE M23 Dagster + M24 Prefect."""

M23 = ("Dagster", 237, 248, """| | |
|---|---|
| **Objective cấp module** | Mô hình hoá pipeline tham chiếu bằng đồ thị tài sản, và chỉ ra thao tác vận hành nào rẻ đi so với đồ thị tác vụ cùng lý do nằm ở mô hình |
| **Tiền đề** | M22 |
| **Exit criterion** | Pipeline tham chiếu chạy bằng đồ thị tài sản có phân mảnh và kiểm tra tài sản, vật chất hoá lại một phân mảnh, và đo được số bước phải chạy so với Airflow |
| **Kỹ năng SFIA** | `PROG` mức 4 · `DATM` mức 3 |
| **Chế độ hỏng** | Khai báo tài sản theo thói quen tác vụ, nên mất hết lợi thế của mô hình tài sản mà vẫn chịu chi phí học công cụ mới |""",
"""Dagster ở mức `A`, dựng lại đúng pipeline tham chiếu của M22. Khác biệt cần bám suốt module là đơn vị mô hình hoá: Airflow mô hình hoá việc phải làm, Dagster mô hình hoá thứ được tạo ra. Ba bài đầu là mô hình, sáu bài giữa là tính năng suy ra từ mô hình đó, ba bài cuối là tích hợp và vận hành.""")

L23 = [
(237,"The asset as the unit of modelling, against the task","LT","Module 23: M22",
"Một tài sản là một đối tượng dữ liệu bền vững có tên: một bảng, một tệp, một phân mảnh. Khai báo gồm tên, phụ thuộc vào tài sản nào, và hàm tính ra nó. Ba hệ quả suy ra từ lựa chọn này. Thứ nhất, đồ thị phụ thuộc phát biểu bằng bảng nào sinh ra bảng nào, nên nó trùng với lineage dữ liệu thay vì nằm song song với nó và phải giữ cho khớp bằng tay, nối lại lesson 206. Thứ hai, câu hỏi vận hành đổi dạng: ở Airflow hỏi đỉnh nào chạy lúc nào, ở đây hỏi bảng nào cũ, bảng nào sai, bảng nào cần dựng lại; ba câu sau gần với câu hỏi người dùng dữ liệu hỏi hơn. Thứ ba, dựng lại chọn lọc thành thao tác cơ bản chứ không phải mẹo, vì hệ thống biết bảng nào phụ thuộc bảng nào. Chỗ mô hình tài sản không hợp: việc không tạo ra dữ liệu bền vững, ví dụ gửi thông báo hay gọi dịch vụ ngoài; hai khái niệm cho loại đó ở lesson 239. Vật chất hoá là hành động tính lại một tài sản và ghi kết quả xuống.",
"Đối chiếu đồ thị tác vụ của M22 với đồ thị tài sản cho cùng pipeline, và chỉ ra ba câu hỏi vận hành mà mô hình tài sản trả lời trực tiếp còn mô hình tác vụ phải suy ra.",
"Tầng *phân tích*. Bài lý thuyết nhưng objective là phân rã khác biệt giữa hai mô hình, không phải nhắc lại định nghĩa. Kiểm bằng bản đối chiếu viết: ba câu hỏi phải là câu hỏi vận hành thật, và với mỗi câu phải nêu ở Airflow phải làm gì để trả lời. Liệt kê tính năng của Dagster không phải phép kiểm hợp lệ cho objective này.",
"Lấy đồ thị Airflow ở lesson 226. Vẽ đồ thị tài sản tương ứng cho cùng pipeline tham chiếu. Đặt ba câu hỏi vận hành thật: bảng nào cũ hơn 24 giờ, đổi lược đồ nguồn thì hỏng bảng nào, dựng lại một bảng giữa đồ thị thì phải dựng lại thêm gì. Với mỗi câu, nêu cách trả lời ở hai mô hình.",
"Vẽ đồ thị tài sản y hệt đồ thị tác vụ rồi kết luận hai cái như nhau · coi mọi việc là tài sản kể cả việc không sinh dữ liệu · so sánh hai công cụ bằng tính năng thay vì bằng câu hỏi vận hành.",
"Bản đối chiếu nêu đủ ba câu hỏi vận hành, mỗi câu có cách trả lời ở cả hai mô hình."),

(238,"Software-defined assets and the asset graph","TH","Lesson 237",
"Khai báo tài sản bằng hàm có trang trí, và phụ thuộc suy ra từ tham số của hàm chứ từ khai báo riêng, nên đồ thị không lệch khỏi mã. Khoá tài sản và nhóm tài sản, cùng quy ước đặt tên theo hạt của kết quả thay vì theo thao tác, nối lại lesson 192. Tài sản ngoài là tài sản hệ thống biết có nhưng không tự tạo ra, dùng để nối đồ thị tới tận bảng nguồn; đây là chỗ lineage bắt đầu từ nguồn thật chứ từ bước đầu tiên của mình. Siêu dữ liệu gắn vào mỗi lần vật chất hoá: số dòng, dung lượng, và bất kỳ số nào đáng theo dõi, và chúng hiện thành đồ thị theo thời gian trong giao diện. Chọn tập tài sản để chạy bằng cú pháp chọn lọc theo tên, theo nhóm, theo thượng nguồn hoặc hạ nguồn. Mã ở tầng ngoài tệp cũng chạy lúc nạp định nghĩa, nên bẫy ở lesson 226 vẫn còn, chỉ khác tên gọi. Đồ thị nhiều tài sản và ngưỡng cần chia nhóm.",
"Dựng lại pipeline tham chiếu thành đồ thị tài sản có tài sản ngoài cho nguồn, và chạy một nhánh bằng cú pháp chọn lọc.",
"Tầng *áp dụng*. Sản phẩm chạy được với tiêu chí đếm được. Đạt khi đồ thị có đủ tài sản cho mọi bước cộng tài sản ngoài cho hai nguồn, và khi chạy một nhánh thì số tài sản vật chất hoá khớp số tài sản trong nhánh đó, đọc từ bản ghi chạy. Chạy được cả đồ thị không chứng minh được objective.",
"Dựng lại pipeline tham chiếu thành đồ thị tài sản. Khai báo hai nguồn thành tài sản ngoài. Gắn siêu dữ liệu số dòng cho mỗi tài sản. Chọn một nhánh giữa đồ thị và chạy nó, đọc bản ghi chạy xác nhận số tài sản. Đặt một lệnh gọi mạng ở tầng ngoài tệp và đo thời gian nạp định nghĩa.",
"Khai báo phụ thuộc bằng chuỗi tên gõ tay rồi sai chính tả · bỏ tài sản ngoài nên đồ thị đứt ở tầng nguồn · đặt mã nặng ở tầng ngoài tệp.",
"Đồ thị đủ tài sản cộng hai tài sản ngoài, và chạy một nhánh vật chất hoá đúng số tài sản của nhánh đó."),

(239,"Ops, jobs and graphs - when you still need them","TH","Lesson 238",
"Không phải việc nào cũng sinh ra dữ liệu bền vững: gửi thông báo, gọi dịch vụ ngoài, dọn tệp tạm, kích hoạt hệ thống khác. Đơn vị tác vụ và công việc tồn tại cho đúng nhóm đó. Tiêu chí phân biệt dựa trên tác dụng phụ: nếu chạy lại hai lần và kết quả quan sát được là như nhau thì nhiều khả năng đó là tài sản; nếu chạy lại gây tác dụng phụ lặp lại thì đó là tác vụ. Tiêu chí này chính là tính bất biến ở lesson 222 nhìn từ góc mô hình hoá. Cách trộn hai thứ trong một hệ thống mà không rối: tài sản cho đường dữ liệu chính, tác vụ cho phần rìa. Đồ thị tác vụ khi một chuỗi việc cần chạy theo thứ tự nhưng không sinh bảng nào. Công việc vật chất hoá một tập tài sản, và đây là cầu nối: lịch chạy gắn vào công việc chứ gắn vào tài sản. Sai lầm theo chiều ngược: biến mọi thứ thành tác vụ vì quen Airflow, rồi mất toàn bộ lợi thế đã học ở lesson 237.",
"Phân loại một danh sách việc thành tài sản và tác vụ theo tiêu chí tác dụng phụ, và cài đặt phần rìa bằng tác vụ trong khi giữ đường dữ liệu chính là tài sản.",
"Tầng *áp dụng*. Objective gồm một phép phân loại có tiêu chí xác định cộng một sản phẩm. Kiểm hai phần: bảng phân loại 12 việc chấm theo tiêu chí tác dụng phụ, đạt khi đúng ít nhất 10; và hệ thống chạy được trong đó đường dữ liệu chính vẫn là tài sản. Phân loại đúng mà cài đặt biến hết thành tác vụ thì không đạt.",
"Nhận 12 việc trong pipeline tham chiếu: chạy bước biến đổi, gửi thông báo thành công, dọn bảng tạm, tải tệp lên kho đối tượng, kích hoạt làm mới bảng điều khiển, gọi giao diện lập trình web bên thứ ba, và các việc khác. Phân loại theo tiêu chí. Cài ba việc phần rìa bằng tác vụ, giữ đường dữ liệu chính là tài sản.",
"Biến việc gửi thông báo thành tài sản vì tiện đặt vào đồ thị · biến mọi bước thành tác vụ vì quen Airflow · gắn lịch vào tài sản thay vì vào công việc.",
"Bảng phân loại đúng ít nhất 10 trên 12, và hệ thống chạy được với đường dữ liệu chính là tài sản."),

(240,"Partitions - time, static and multi-dimensional","TH","Lesson 239",
"Phân mảnh chia một tài sản thành các lát độc lập, mỗi lát vật chất hoá riêng và có trạng thái riêng, nên hệ thống biết lát nào đã có lát nào chưa. Đây là chỗ mô hình tài sản trả lại lợi ích rõ nhất: chạy bù trở thành vật chất hoá các lát còn thiếu, không phải một chế độ chạy riêng như ở lesson 233. Định nghĩa phân mảnh theo thời gian và ràng buộc phân mảnh phải khớp hạt của bảng, nối lại lesson 192; khai báo theo ngày trong khi bảng gộp theo tuần sẽ ghi đè lẫn nhau, một lỗi âm thầm. Ánh xạ phân mảnh giữa các tài sản khi hạt đổi dọc đồ thị, ví dụ bảng ngày nuôi bảng tháng. Truyền cửa sổ thời gian của lát vào mã, nối thẳng ngày logic ở lesson 221. Bảng trạng thái phân mảnh trong giao diện và cách đọc để biết thiếu ngày nào. Phân mảnh tĩnh theo danh sách giá trị. Phân mảnh nhiều chiều và chi phí: số lát nhân lên rất nhanh nên phải cân nhắc trước khi khai báo.",
"Khai báo phân mảnh theo ngày cho các tài sản của pipeline, và vật chất hoá lại đúng một ngày trong quá khứ mà không đụng tới ngày khác.",
"Tầng *áp dụng*. Objective kiểm được bằng thực nghiệm có tiêu chí tuyệt đối. Đạt khi vật chất hoá lại ngày `T-5` làm đổi đúng các dòng của ngày đó, xác nhận bằng so dấu thời gian cập nhật của các ngày còn lại trước và sau. Một ngày khác bị đụng là không đạt.",
"Khai báo phân mảnh ngày cho các tài sản. Vật chất hoá 30 ngày. Ghi dấu thời gian cập nhật từng ngày. Vật chất hoá lại riêng ngày `T-5`. So dấu thời gian. Đo số bước phải chạy so với cách chạy bù ở lesson 233. Khai báo phân mảnh nhiều chiều theo ngày và vùng, đếm số lát sinh ra.",
"Khai báo phân mảnh theo ngày cho bảng có hạt tuần · quên truyền cửa sổ phân mảnh vào mã nên vẫn lọc theo đồng hồ hệ thống · khai báo phân mảnh nhiều chiều rồi sinh hàng chục nghìn lát.",
"Vật chất hoá lại một ngày chỉ đổi dòng của ngày đó, xác nhận bằng dấu thời gian các ngày còn lại."),

(241,"Schedules and sensors","TH","Lesson 240",
"Lịch chạy gắn vào công việc và sinh lần chạy theo chu kỳ, tương ứng lập lịch theo thời gian ở lesson 221. Cảm biến chạy một hàm kiểm tra theo chu kỳ ngắn và quyết định có kích hoạt hay không, tương ứng lập lịch theo sự kiện; khác cảm biến của Airflow ở lesson 230 ở chỗ nó không chiếm chỗ tiến trình thực thi vì nó chạy trong tiến trình nền riêng, nên bài toán bế tắc tài nguyên ở đó không tồn tại ở đây. Con trỏ của cảm biến để nhớ đã xử lý tới đâu giữa các lần kiểm, và lưu nó đúng cách là điều kiện để cảm biến không kích hoạt trùng. Cảm biến tài sản kích hoạt khi một tài sản thượng nguồn được vật chất hoá, cho phép nối hai đồ thị mà không cần lịch. Chính sách độ tươi khai báo yêu cầu bằng ngưỡng thời gian và tự thành cảnh báo khi vượt, chuyển khả năng quan sát từ việc đã chạy chưa sang việc dữ liệu có mới không. Cảm biến chạy lỗi và cách phát hiện, vì cảm biến hỏng thì không có gì kích hoạt và hệ thống im lặng.",
"Cấu hình mẫu lai gồm lịch theo giờ và cảm biến chờ nguồn, và chứng minh cảm biến không kích hoạt trùng khi kiểm lại nhiều lần.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng hai kịch bản đối lập cộng một tiêu chí về trùng lặp. Đạt khi nguồn tới sớm thì chạy ngay và nguồn không tới thì vẫn chạy đúng giờ chốt, và khi chạy cảm biến 200 vòng kiểm trên cùng một tệp chỉ sinh đúng một lần chạy.",
"Cấu hình lịch theo giờ cộng cảm biến chờ tệp. Kịch bản một: đặt tệp sớm 20 phút, xác nhận chạy ngay. Kịch bản hai: không đặt tệp, xác nhận vẫn chạy đúng giờ chốt. Chạy cảm biến 200 vòng trên cùng tệp và đếm số lần chạy sinh ra. Khai báo chính sách độ tươi và để một tài sản quá hạn.",
"Không lưu con trỏ cảm biến nên kích hoạt trùng mỗi vòng kiểm · gắn lịch vào tài sản thay vì vào công việc · không theo dõi cảm biến lỗi nên hệ thống im lặng.",
"Hai kịch bản đối lập cho đúng hành vi, và 200 vòng kiểm trên cùng tệp chỉ sinh một lần chạy."),

(242,"Resources, configuration and separating IO from logic","TH","Lesson 241",
"Tài nguyên là đối tượng dùng chung khai báo một lần rồi tiêm vào tài sản cần nó: kết nối cơ sở dữ liệu, ứng dụng khách kho đối tượng, ứng dụng khách giao diện lập trình web. Hai lợi ích: mã tài sản không tự khởi tạo kết nối nên kiểm thử được bằng cách tiêm bản giả, nối lại lesson 84; và đổi cấu hình giữa các môi trường không phải sửa mã, nối lại lesson 75. Cấu hình có lược đồ và kiểm lúc nạp định nghĩa chứ lúc chạy, nên thiếu một trường bị bắt sớm. Ba tầng cấu hình và thứ tự ưu tiên. Tách phần vào ra khỏi phần logic: hàm tài sản nhận dữ liệu đã đọc và trả dữ liệu cần ghi, còn việc đọc ghi do bộ quản lý vào ra làm, chi tiết ở lesson 243. Hệ quả là phần logic thành hàm thuần và kiểm thử được không cần hạ tầng, đúng nguyên tắc ở lesson 68. Định nghĩa khác nhau cho môi trường phát triển và sản xuất bằng cách chọn tập tài nguyên.",
"Tách một tài sản đang tự mở kết nối thành phần logic thuần cộng tài nguyên tiêm vào, và chứng minh phần logic kiểm thử được với mạng bị chặn.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm rõ ràng. Đạt khi bộ kiểm thử cho phần logic chạy xanh khi chặn mạng và không có cơ sở dữ liệu, và khi cùng mã chạy được ở hai môi trường chỉ bằng đổi tập tài nguyên, không sửa dòng nào.",
"Nhận ba tài sản tự mở kết nối. Tách thành logic thuần cộng tài nguyên. Viết kiểm thử cho phần logic, chạy với mạng bị chặn. Định nghĩa hai tập tài nguyên cho hai môi trường và chạy cùng mã ở cả hai. Bỏ một trường cấu hình bắt buộc và xác nhận nó bị bắt lúc nạp định nghĩa.",
"Khởi tạo kết nối trong hàm tài sản · rẽ nhánh theo tên môi trường bên trong mã · trộn phần đọc ghi với phần biến đổi nên không kiểm thử được.",
"Kiểm thử phần logic xanh khi chặn mạng, và cùng mã chạy ở hai môi trường chỉ bằng đổi tập tài nguyên."),

(243,"IO managers and where data actually lands","TH","Lesson 242",
"Bộ quản lý vào ra là lớp quyết định giá trị trả về của một tài sản được ghi ở đâu và đọc lại thế nào, và nó là khái niệm dễ gây nhầm nhất của công cụ. Mặc định ghi vào hệ tệp cục bộ dạng tuần tự hoá, tiện cho thử nghiệm nhưng không phải thứ dùng cho sản xuất. Ba lựa chọn thật và điều kiện: ghi vào kho đối tượng theo định dạng cột, ghi vào bảng của kho dữ liệu, hoặc không dùng bộ quản lý vào ra và để hàm tài sản tự ghi rồi chỉ trả về siêu dữ liệu. Lựa chọn thứ ba là lựa chọn hay dùng nhất trong pipeline dữ liệu lớn, vì dữ liệu không nên đi qua tiến trình điều phối, đúng nguyên tắc ở lesson 224 và 229. Bộ quản lý vào ra theo phân mảnh và cách nó ánh xạ lát sang đường dẫn. Viết bộ quản lý vào ra riêng. Khi nào nên dùng và khi nào không: dùng cho tài sản nhỏ và trung bình, không dùng cho tài sản lớn hơn bộ nhớ tiến trình.",
"Chọn cách ghi cho ba tài sản có kích thước khác nhau và chứng minh bằng đo bộ nhớ tiến trình rằng tài sản lớn không đi qua tiến trình điều phối.",
"Tầng *đánh giá*. Objective đòi chọn giữa ba phương án theo ràng buộc kích thước. Đạt khi ba lựa chọn đều có lý do dẫn về kích thước và bộ nhớ, và khi đo được bộ nhớ tiến trình điều phối gần như không tăng với tài sản 20 ghi ga byte trong khi tăng vọt nếu dùng bộ quản lý vào ra mặc định.",
"Ba tài sản kích thước 10 mê ga byte, 500 mê ga byte, và 20 ghi ga byte. Thử cả ba cách ghi cho từng tài sản, đo bộ nhớ đỉnh của tiến trình điều phối. Cài bộ quản lý vào ra riêng ghi vào kho đối tượng theo định dạng cột cho tài sản thứ hai. Với tài sản thứ ba, để hàm tự ghi và chỉ trả siêu dữ liệu.",
"Dùng bộ quản lý vào ra mặc định cho tài sản lớn · trả về cả khung dữ liệu từ hàm tài sản khi dữ liệu lớn hơn bộ nhớ · viết bộ quản lý vào ra riêng khi ba cách có sẵn đã đủ.",
"Ba lựa chọn có lý do dẫn về kích thước, và bộ nhớ tiến trình điều phối gần như không tăng với tài sản 20 ghi ga byte."),

(244,"Asset checks and data quality inside the graph","TH","Lesson 243",
"Kiểm tra tài sản gắn phép kiểm chất lượng vào chính đồ thị thay vì để nó thành một bước riêng, nên kết quả kiểm hiện cạnh tài sản và người dùng hạ nguồn thấy bảng nào đang nghi ngờ mà không phải đọc nhật ký. Áp trực tiếp sáu chiều chất lượng ở lesson 211: mỗi chiều thành một kiểm tra gắn vào tài sản tương ứng. Kiểm tra chặn và kiểm tra không chặn, cùng tiêu chí chọn, nối lại lesson 213: chặn khi dữ liệu sai gây hại hơn dữ liệu trễ. Kiểm tra chạy cùng lúc vật chất hoá hay chạy riêng sau đó, cùng đánh đổi. Kiểm tra trên tài sản ngoài để bắt lỗi nguồn trước khi nó vào hệ, đúng vị trí thứ nhất trong ba vị trí ở lesson 213. Siêu dữ liệu kèm kết quả kiểm để người đọc biết lệch bao nhiêu chứ chỉ biết đạt hay không. Lịch sử kết quả kiểm theo thời gian, và đây là nơi phát hiện trôi phân bố ở lesson 215 mà không phải dựng hệ riêng.",
"Gắn sáu chiều chất lượng thành kiểm tra tài sản, và chứng minh kiểm tra chặn dừng được đồ thị còn kiểm tra không chặn thì không.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm đối lập. Đạt khi sáu chiều đều có kiểm tra gắn đúng tài sản, và khi bơm cùng một lỗi vào hai tài sản có mức nghiêm trọng khác nhau thì một cái dừng đồ thị còn cái kia chạy tiếp và ghi nhận.",
"Gắn sáu kiểm tra cho các tài sản của pipeline, mỗi kiểm tra một chiều. Đặt ba chặn và ba không chặn theo tiêu chí. Bơm lỗi tương ứng từng cái và ghi hành vi. Gắn siêu dữ liệu lệch bao nhiêu vào kết quả. Xem lịch sử kết quả kiểm 30 ngày và tìm một xu hướng trôi.",
"Đặt mọi kiểm tra là chặn rồi đồ thị dừng vì một cảnh báo nhỏ · chỉ báo đạt hay không mà không báo lệch bao nhiêu · gắn kiểm tra vào tài sản hạ nguồn trong khi lỗi ở nguồn.",
"Sáu chiều có kiểm tra gắn đúng tài sản, và hai mức nghiêm trọng cho hành vi khác nhau khi bơm cùng lỗi."),

(245,"Backfilling partitions and selective materialization","TH","Lesson 244",
"Chạy bù ở đây là vật chất hoá một tập lát, nên nó dùng chung cơ chế với chạy thường chứ không phải chế độ riêng, khác hẳn lesson 233. Ba cách chọn tập lát: theo dải thời gian, theo trạng thái thiếu, và theo chọn lọc thượng nguồn hạ nguồn. Cách thứ hai đáng chú ý: hệ thống biết lát nào chưa có nên chạy bù trở thành lấp chỗ trống, và người vận hành không phải tự tính dải ngày. Chạy bù theo chiều dọc so với theo chiều ngang: chạy hết một tài sản cho mọi ngày rồi sang tài sản sau, hay chạy hết mọi tài sản cho một ngày rồi sang ngày sau; hai thứ tự cho hai đặc tính khác nhau về khả năng phục hồi giữa chừng và về áp lực lên hệ đích. Giới hạn số lát chạy đồng thời, cùng bài toán lesson 234. Dựng lại hạ nguồn tự động khi một tài sản thượng nguồn thay đổi, và điều kiện nên bật. Theo dõi tiến độ một lần chạy bù lớn và dừng sạch sẽ.",
"Chạy bù 90 ngày bằng cách lấp lát còn thiếu, và so số bước phải chạy với cách chạy bù ở Airflow trên cùng pipeline.",
"Tầng *áp dụng*. Objective có tiêu chí đối chứng tuyệt đối cộng một phép so định lượng. Đạt khi kết quả 90 ngày khớp bản đối chứng từng dòng, và khi có bảng so số bước phải chạy giữa hai công cụ cho ba kịch bản chạy bù khác nhau. Đây là số đo dùng lại ở M25.",
"Xoá ngẫu nhiên 30 trong 90 lát. Chạy bù bằng cách lấp lát thiếu. Đối chiếu từng dòng với bản đối chứng. So số bước phải chạy với Airflow cho ba kịch bản: thiếu một ngày giữa, thiếu 30 ngày rải rác, và sửa logic một tài sản giữa đồ thị. Thử hai thứ tự chạy bù và đo thời gian.",
"Tự tính dải ngày thay vì dùng trạng thái lát thiếu · chạy bù không giới hạn số lát đồng thời · bật dựng lại hạ nguồn tự động cho tài sản đổi liên tục.",
"Kết quả 90 ngày khớp từng dòng, và bảng so số bước với Airflow cho ba kịch bản."),

(246,"Lineage, the asset catalog and observability","TH","Lesson 245",
"Đồ thị tài sản đã chứa sẵn thông tin mà ở nơi khác phải dựng công cụ riêng mới có: bảng nào sinh ra bảng nào, lần vật chất hoá cuối, kiểm tra nào đang hỏng, ai sở hữu, số dòng theo thời gian. Bảng danh mục là mặt tiền đọc được của những thứ đó. Ba câu hỏi người dùng hạ nguồn hay hỏi và cách danh mục trả lời trực tiếp: số này lấy từ đâu, bảng này cập nhật lần cuối lúc nào, và tôi đổi cột này thì hỏng cái gì. Câu thứ ba là phân tích tác động và nó đọc ngược đồ thị. Siêu dữ liệu gắn vào tài sản và vào mỗi lần vật chất hoá, cùng cách chúng hiện thành đồ thị theo thời gian. Mô tả cột và liên kết tới mã nguồn. Giới hạn: danh mục chỉ biết những gì đi qua nó, nên bảng ai đó tạo tay trong kho sẽ không xuất hiện, và đây là lý do phải có quy ước mọi bảng phục vụ đều đi qua đồ thị. Phân biệt với danh mục dữ liệu cấp tổ chức.",
"Gắn đủ siêu dữ liệu để một người ngoài đội trả lời được ba câu hỏi hạ nguồn chỉ bằng danh mục, không hỏi ai.",
"Tầng *đánh giá*. Objective đo bằng người dùng thật chứ bằng danh sách trường đã điền. Kiểm bằng quan sát: ba người chưa từng thấy hệ thống, mỗi người ba câu hỏi, ghi lại chỗ họ vướng thay vì hỏi họ thấy thế nào. Đạt khi ít nhất hai trên ba người trả lời được cả ba câu mà không cần hướng dẫn.",
"Gắn mô tả, chủ sở hữu, nhóm và số dòng cho mọi tài sản. Nối mô tả cột. Đưa danh mục cho ba người chưa từng thấy, giao ba câu hỏi, quan sát và ghi điểm vướng. Sửa theo điểm vướng rồi thử với người thứ tư. Tạo một bảng ngoài đồ thị và chỉ ra nó không có trong danh mục.",
"Điền mô tả bằng cách chép lại tên tài sản · bỏ trường chủ sở hữu vì cả đội đều biết · tạo bảng phục vụ ngoài đồ thị.",
"Ít nhất hai trên ba người ngoài đội trả lời được cả ba câu hỏi, có ghi chép điểm vướng."),

(247,"Integrating an external transformation tool - one graph instead of two","TH","Lesson 246",
"Khi tầng biến đổi do đội khác sở hữu bằng công cụ riêng, có hai đồ thị: đồ thị điều phối và đồ thị bên trong công cụ đó. Ba cách nối và đánh đổi. Gọi nó như một bước đơn: đơn giản nhất, nhưng đồ thị điều phối chỉ thấy một đỉnh nên hỏng một mô hình phải mở nhật ký mới biết là mô hình nào. Đọc bản kê của công cụ và sinh một tài sản cho mỗi mô hình: hai đồ thị nhập làm một, thấy ngay mô hình nào hỏng và dựng lại đúng nhánh, nhưng phải giải bài toán bản kê có trước lúc nạp định nghĩa. Nối qua ranh giới dữ liệu: đội kia đọc tài sản mình bàn giao và mình không nhìn vào trong. Cách thứ ba là cách khớp với ranh giới trách nhiệm ở lesson 200: Data Engineer bàn giao tập dữ liệu có hợp đồng, đội phân tích sở hữu phần biến đổi phía sau. Chọn cách nào là quyết định tổ chức nhiều hơn kỹ thuật, và phải thoả thuận với đội kia chứ không tự quyết.",
"Nối một công cụ biến đổi ngoài vào đồ thị bằng hai trong ba cách, và so thời gian từ lúc hỏng tới lúc biết bước nào hỏng.",
"Tầng *đánh giá*. Objective đòi chọn giữa các cách có đánh đổi cả kỹ thuật lẫn tổ chức. Đạt khi hai cách đều chạy và có số đo thời gian phát hiện lỗi, và khi lựa chọn cuối nêu được nó phù hợp với ranh giới trách nhiệm nào giữa hai đội.",
"Dựng một dự án biến đổi ngoài 20 bước. Nối vào đồ thị bằng cách gọi một bước đơn, đo thời gian từ lúc một bước hỏng tới lúc biết bước nào. Nối lại bằng cách sinh một tài sản cho mỗi bước, đo lại. Viết nửa trang nêu cách nào phù hợp với ranh giới trách nhiệm nào.",
"Sinh tài sản từ bản kê bằng cách chạy công cụ lúc nạp định nghĩa · tự quyết cách nối mà không thoả thuận với đội sở hữu tầng biến đổi · gọi một bước đơn rồi than không quan sát được.",
"Hai cách đều chạy có số đo thời gian phát hiện lỗi, và lựa chọn cuối nêu được ranh giới trách nhiệm tương ứng."),

(248,"Operating Dagster - the daemon, code locations, deployment","TH","Lesson 247",
"Không có cơ chế mới. Bài gộp module, đo năng lực vận hành. Tiến trình nền chạy lịch, cảm biến, và hàng đợi lần chạy; nó chết thì không có gì kích hoạt và hệ thống im lặng chứ không báo lỗi, nên theo dõi nó là chỉ số vận hành bắt buộc, cùng loại vấn đề với cảm biến lỗi ở lesson 241. Vị trí mã là đơn vị nạp định nghĩa, chạy trong tiến trình riêng; hệ quả là một vị trí mã lỗi không làm chết vị trí khác, và mỗi vị trí có phụ thuộc riêng, giải bài toán xung đột thư viện mà bộ thực thi phân tán của Airflow gặp ở lesson 235. Kho lưu trữ giữ trạng thái lần chạy, sự kiện và siêu dữ liệu tài sản; nó tương ứng cơ sở dữ liệu siêu dữ liệu ở lesson 225 và cần bảo trì tương tự. Triển khai mã mới và cửa sổ hai phiên bản cùng tồn tại. Ba sự cố vận hành và quy trình chẩn đoán: tiến trình nền chết, vị trí mã nạp lỗi, và kho lưu trữ phình.",
"Chẩn đoán ba sự cố vận hành chưa từng thấy về đúng nguyên nhân, và triển khai một phiên bản mã mới không gián đoạn lịch chạy.",
"Tầng *đánh giá*. Objective đòi chẩn đoán dưới thời gian cộng một thao tác vận hành. Chấm theo bốn mục: chẩn đoán ba sự cố 45đ, triển khai không gián đoạn 20đ, sổ tay xử lý 20đ, và theo dõi tiến trình nền 15đ. Đạt khi ≥ 70/100 và mục chẩn đoán ≥ 60%.",
"Cụm Dagster có tải. Giám khảo gây ba sự cố không báo trước: giết tiến trình nền, đẩy mã lỗi vào một vị trí, và làm kho lưu trữ phình. Chẩn đoán theo quy trình, ghi số đo trước khi sửa. Triển khai phiên bản mã mới trong lúc lịch đang chạy. Nộp sổ tay xử lý và truy vấn theo dõi tiến trình nền.",
"Không theo dõi tiến trình nền nên hệ thống im lặng · gộp mọi định nghĩa vào một vị trí mã · quên bảo trì kho lưu trữ như một cơ sở dữ liệu thật.",
"Đạt ≥ 70/100 và mục chẩn đoán ≥ 60%, với sổ tay xử lý và truy vấn theo dõi tiến trình nền."),
]

M24 = ("Prefect", 249, 260, """| | |
|---|---|
| **Objective cấp module** | Điều phối pipeline tham chiếu bằng Prefect, xử lý thất bại bằng trạng thái trả về, và tách định nghĩa luồng khỏi hạ tầng chạy nó |
| **Tiền đề** | M22 |
| **Exit criterion** | Pipeline tham chiếu chạy bằng Prefect có bản triển khai và nhóm công việc, xử lý đúng ba loại thất bại, và ghi được thời gian từ lúc bắt đầu tới lúc chạy được |
| **Kỹ năng SFIA** | `PROG` mức 4 |
| **Chế độ hỏng** | Viết luồng như một script Python rồi bỏ qua trạng thái trả về, nên thất bại đi qua mà hệ thống báo thành công |""",
"""Prefect ở mức `A`, dựng lại đúng pipeline tham chiếu. Khác biệt nền tảng với hai công cụ trước: luồng và tác vụ là hàm Python bình thường, không có lớp khai báo trung gian. Hệ quả là rào vào thấp nhất trong ba công cụ, và giá phải trả là kỷ luật xử lý trạng thái nằm ở người viết chứ ở hệ thống.

Tên đúng của công cụ là Prefect.""")

L24 = [
(249,"Flows and tasks as plain Python functions","LT","Module 24: M22",
"Một luồng là một hàm Python có trang trí, một tác vụ cũng vậy. Không có lớp khai báo riêng, không có tệp cấu hình bắt buộc, nên mã chạy được bằng trình thông dịch bình thường lẫn chạy được dưới sự quản lý của công cụ. Hệ quả thứ nhất: kiểm thử luồng bằng công cụ kiểm thử Python thông thường, không cần dựng hạ tầng, nối lại lesson 84. Hệ quả thứ hai và đáng chú ý hơn: trạng thái là giá trị trả về chứ không phải thứ hệ thống giữ hộ. Một tác vụ trả về đối tượng trạng thái, và mã gọi nó quyết định làm gì với trạng thái đó. Bốn trạng thái kết thúc và ý nghĩa của từng cái, gồm cả trạng thái báo bỏ qua có chủ đích khác với thất bại. Cơ chế khiến một tác vụ thất bại đi lọt: mã gọi không kiểm tra trạng thái trả về, luồng vẫn chạy tiếp và kết thúc xanh. Đây là chế độ hỏng đặc trưng của công cụ này và nó không tồn tại ở Airflow vì ở đó hệ thống tự quyết định. Đánh đổi tổng quát: tự do hơn thì kỷ luật phải tự mang.",
"Chỉ ra trong một luồng cho trước chỗ một tác vụ thất bại đi lọt, và phát biểu cơ chế khiến luồng vẫn kết thúc xanh.",
"Tầng *phân tích*. Objective là định vị một lỗi trong mã, không phải nhắc lại định nghĩa. Kiểm bằng ba đoạn luồng, mỗi đoạn có một chỗ thất bại đi lọt theo một cơ chế khác nhau. Đạt khi chỉ đúng dòng và phát biểu đúng cơ chế cho cả ba, và dự đoán phải đưa ra trước khi chạy.",
"Đọc ba đoạn luồng. Với mỗi đoạn, chỉ dòng mà thất bại đi lọt và phát biểu cơ chế, ghi lại trước khi chạy. Chạy cả ba xác nhận dự đoán. Mọi chênh lệch phải giải thích được. Viết một luồng nhỏ và chạy nó bằng trình thông dịch thường, không qua công cụ.",
"Coi tác vụ như hàm thường rồi bỏ qua giá trị trả về · nhầm trạng thái bỏ qua có chủ đích với thất bại · gọi công cụ là Perfect.",
"Chỉ đúng dòng và cơ chế cho cả ba đoạn, dự đoán trước khi chạy khớp kết quả."),

(250,"State as a first-class object, and handling it","TH","Lesson 249",
"Trạng thái là đối tượng có kiểu, mang cả kết quả lẫn thông tin về cách tác vụ kết thúc. Lấy trạng thái thay vì lấy kết quả khi cần xử lý thất bại trong mã thay vì để luồng đổ. Ba mẫu xử lý và điều kiện dùng: để đổ và dựa vào thử lại cho lỗi tạm thời, bắt trạng thái và rẽ nhánh cho lỗi có phương án thay thế, và trả về trạng thái bỏ qua có chủ đích khi không có gì để làm. Mẫu thứ ba hay bị bỏ và nó là cách phân biệt không có dữ liệu với có lỗi, hai thứ khác nhau mà nhiều pipeline gộp làm một. Trạng thái của luồng gộp từ trạng thái các tác vụ theo quy tắc khai báo được, tương ứng bốn quy tắc gộp ở lesson 220. Nâng lỗi có kiểu để mã gọi phân biệt được, nối lại lesson 65. Ghi nhật ký có cấu trúc gắn với trạng thái, nối lại lesson 74. Móc nối chạy khi chuyển trạng thái, dùng cho cảnh báo có ngữ cảnh.",
"Bọc ba bước của pipeline sao cho ba loại kết thúc cho ba trạng thái khác nhau, và chứng minh bằng ba lần chạy bơm lỗi.",
"Tầng *áp dụng*. Objective có tiêu chí đúng sai tuyệt đối, kiểm bằng thực nghiệm. Đạt khi ba kịch bản bơm lỗi cho đúng ba trạng thái khác nhau, và khi kịch bản không có dữ liệu cho trạng thái bỏ qua chứ trạng thái thất bại. Hai kịch bản cho cùng một trạng thái là không đạt vì đó chính là lỗi bài này dạy cách tránh.",
"Bọc ba bước của pipeline tham chiếu. Bơm ba tình huống: lỗi kết nối tạm thời, lỗi dữ liệu xác định, và nguồn không có bản ghi mới. Xác nhận ba trạng thái khác nhau. Viết móc nối chuyển trạng thái để gửi cảnh báo có ngữ cảnh. Khai báo quy tắc gộp trạng thái luồng và kiểm bằng một tác vụ không bắt buộc thất bại.",
"Gộp không có dữ liệu vào thất bại · bắt ngoại lệ quá rộng rồi nuốt mất lỗi lập trình · dựa vào trạng thái mặc định mà không khai báo quy tắc gộp.",
"Ba kịch bản cho ba trạng thái khác nhau, và kịch bản không có dữ liệu cho trạng thái bỏ qua."),

(251,"Deployments - separating the flow from where it runs","TH","Lesson 250",
"Bản triển khai là cầu nối giữa mã luồng và hạ tầng chạy nó. Cùng một luồng triển khai được nhiều lần với tham số, lịch và hạ tầng khác nhau, và đây là cách chạy cùng mã ở môi trường thử nghiệm lẫn sản xuất mà không rẽ nhánh trong mã, nối lại lesson 242. Phân biệt ba thứ hay bị gộp: định nghĩa luồng, bản triển khai, và một lần chạy. Nơi lưu mã luồng và cách tiến trình thực thi lấy được nó: từ kho mã, từ ảnh vùng chứa, hoặc từ kho đối tượng, cùng đánh đổi về tốc độ khởi động và khả năng tái lập. Tham số hoá bản triển khai để chạy bù nhận dải ngày từ ngoài thay vì sửa mã, nối lại lesson 221. Lịch gắn vào bản triển khai chứ gắn vào luồng, nên cùng luồng có hai lịch khác nhau ở hai môi trường. Phiên bản bản triển khai và cách quay lui. Bản triển khai là thứ tương ứng với đồ thị ở Airflow và với công việc ở Dagster, nên đây là điểm neo khi so ba công cụ ở M25.",
"Triển khai cùng một luồng thành hai bản chạy trên hai hạ tầng khác nhau, và chạy bù một dải ngày bằng tham số truyền từ ngoài.",
"Tầng *áp dụng*. Sản phẩm chạy được với tiêu chí đếm được. Đạt khi hai bản triển khai cùng trỏ về một định nghĩa luồng, chạy trên hai hạ tầng khác nhau, và một lần chạy bù nhận dải ngày qua tham số cho ra đúng số lần chạy tương ứng. Sửa mã để chạy bù là không đạt.",
"Triển khai luồng ở lesson 250 thành hai bản: một chạy bằng tiến trình, một chạy trong vùng chứa. Dựng hai nhóm công việc. Chạy bù 7 ngày bằng tham số. Xác nhận không dòng mã nào bị sửa giữa hai môi trường. Thử ba cách lưu mã luồng và đo thời gian khởi động từng cách.",
"Rẽ nhánh theo tên môi trường bên trong mã luồng · gộp định nghĩa luồng với bản triển khai nên mỗi môi trường một bản mã · viết cứng dải ngày chạy bù vào luồng.",
"Hai bản triển khai cùng một mã chạy trên hai hạ tầng, và chạy bù 7 ngày qua tham số sinh đúng 7 lần chạy."),

(252,"Work pools, workers and infrastructure","TH","Lesson 251",
"Nhóm công việc là hàng đợi kèm khai báo hạ tầng; tiến trình thực thi kéo việc từ nhóm về chạy. Mô hình kéo thay vì đẩy, và hệ quả về mạng: tiến trình thực thi chủ động gọi ra nên chạy được sau tường lửa mà không cần mở cổng vào, khác mô hình của Airflow ở lesson 235. Ba kiểu hạ tầng và tiêu chí chọn: tiến trình trên máy có sẵn, vùng chứa riêng cho mỗi lần chạy, và công việc trên cụm điều phối vùng chứa; cùng ba lựa chọn với bộ thực thi ở lesson 235 nên so sánh được trực tiếp. Chi phí khởi động của từng kiểu và ảnh hưởng lên luồng nhiều tác vụ ngắn. Tiến trình thực thi có thẻ để định tuyến luồng cần tài nguyên đặc biệt. Giới hạn số lần chạy đồng thời đặt ở nhóm công việc, tương ứng nhóm tài nguyên ở lesson 234. Tiến trình thực thi chết và cơ chế phát hiện lần chạy mồ côi. Triển khai tiến trình thực thi và quy mô theo tải.",
"Dựng hai nhóm công việc với hai kiểu hạ tầng, và đo chi phí khởi động cùng thông lượng của từng kiểu trên pipeline tham chiếu.",
"Tầng *đánh giá*. Objective đòi chọn hạ tầng có đánh đổi, và số đo dùng lại ở M25. Đạt khi có số đo chi phí khởi động và thông lượng cho ít nhất hai kiểu hạ tầng, và khi lựa chọn dẫn được về số đo cộng năng lực vận hành chứ bằng danh tiếng công cụ.",
"Dựng hai nhóm công việc: một chạy tiến trình, một chạy vùng chứa. Chạy pipeline tham chiếu trên cả hai, đo chi phí khởi động một tác vụ và tổng thông lượng. Đặt giới hạn số lần chạy đồng thời ở nhóm và kiểm. Giết một tiến trình thực thi giữa chừng và quan sát cơ chế phát hiện lần chạy mồ côi.",
"Dùng hạ tầng vùng chứa cho luồng nhiều tác vụ ngắn · không đặt giới hạn đồng thời ở nhóm công việc · để tiến trình thực thi chạy mà không theo dõi lần chạy mồ côi.",
"Số đo chi phí khởi động và thông lượng cho ít nhất hai kiểu hạ tầng, và lựa chọn dẫn được về số đo."),

(253,"Schedules, event triggers and automations","TH","Lesson 252",
"Lịch gắn vào bản triển khai, nên cùng luồng có hai lịch khác nhau ở hai môi trường. Ba kiểu lịch và tiêu chí chọn: biểu thức cron cho chu kỳ theo lịch dương, khoảng lặp cho chu kỳ đều, và lịch khai báo theo múi giờ có xử lý giờ mùa hè. Nối lại lesson 221: lịch quyết định khi nào chạy, tham số quyết định chạy cho khoảng dữ liệu nào, và hai thứ đó phải khớp nếu không sẽ lệch một chu kỳ. Kích hoạt theo sự kiện: luồng chạy khi một luồng khác kết thúc, khi một trạng thái xuất hiện, hoặc khi có tín hiệu từ ngoài. Tự động hoá là quy tắc dạng nếu thấy điều kiện này thì làm việc kia, và nó xử lý nhóm việc mà lịch không làm được: chạy lại khi thất bại, báo khi một lần chạy vượt thời lượng thường lệ, huỷ lần chạy treo. Mẫu lai cho pipeline dữ liệu: lịch theo giờ cộng kích hoạt khi nguồn báo đã nạp xong, lấy cái nào tới trước và chặn chạy trùng.",
"Cấu hình mẫu lai gồm lịch theo giờ và kích hoạt theo sự kiện, sao cho nguồn tới sớm thì chạy sớm còn nguồn không tới thì vẫn chạy đúng giờ chốt.",
"Tầng *áp dụng*. Objective là cấu hình có hành vi kiểm được bằng hai kịch bản đối lập. Đạt khi kịch bản nguồn tới sớm làm luồng chạy ngay, kịch bản nguồn không tới làm luồng vẫn chạy đúng giờ chốt, và không kịch bản nào sinh hai lần chạy chồng nhau.",
"Cấu hình lịch theo giờ cộng kích hoạt sự kiện. Kịch bản một: phát tín hiệu nguồn sẵn sàng sớm 20 phút, xác nhận chạy ngay. Kịch bản hai: không phát tín hiệu, xác nhận vẫn chạy đúng giờ chốt. Thêm tự động hoá huỷ lần chạy vượt gấp đôi thời lượng thường lệ và kiểm nó.",
"Gắn lịch vào luồng thay vì vào bản triển khai · để lịch và tham số lệch nhau một chu kỳ · quên chặn chạy trùng nên cả sự kiện lẫn lịch cùng kích hoạt.",
"Hai kịch bản đối lập cho đúng hành vi, và không kịch bản nào sinh hai lần chạy chồng nhau."),

(254,"Retries, caching and result persistence","TH","Lesson 253",
"Thử lại đặt ở mức tác vụ bằng tham số của hàm, và điều kiện để bật vẫn là tính bất biến ở lesson 222. Khoảng chờ tăng dần và nhiễu ngẫu nhiên. Điều kiện thử lại tuỳ biến để chỉ thử lại đúng loại lỗi tạm thời, giải trực tiếp vấn đề phân loại ở lesson 222 mà không phải bọc thủ công. Bộ nhớ đệm kết quả tác vụ: nếu đầu vào không đổi thì trả kết quả cũ thay vì chạy lại, và khoá đệm tính từ tham số theo hàm khai báo được. Đây là công cụ mạnh cho chạy bù và cho phát triển lặp, nhưng có hai bẫy: khoá đệm không tính tới dữ liệu nguồn đã đổi, và thời gian sống của đệm quá dài làm dữ liệu cũ đi. Lưu kết quả để lần chạy sau đọc lại và để tác vụ hạ nguồn nhận đầu vào mà không chạy lại thượng nguồn, cùng ràng buộc như lesson 243: kết quả lớn không nên đi qua tiến trình điều phối. Nơi lưu kết quả và cấu hình tuần tự hoá.",
"Cấu hình thử lại có điều kiện và bộ nhớ đệm kết quả, và chứng minh đệm không trả kết quả cũ khi dữ liệu nguồn đã đổi.",
"Tầng *áp dụng*. Objective có bẫy đúng đắn cụ thể là đệm quá tay. Đạt khi thử lại chỉ kích hoạt cho lỗi tạm thời và không kích hoạt cho lỗi xác định, và khi đổi dữ liệu nguồn mà không đổi tham số thì tác vụ vẫn chạy lại chứ không trả kết quả đệm.",
"Cấu hình thử lại có điều kiện cho ba loại lỗi. Bật đệm kết quả cho bước biến đổi. Chạy hai lần cùng tham số, xác nhận lần hai dùng đệm. Đổi dữ liệu nguồn mà giữ nguyên tham số, xác nhận nó vẫn chạy lại. Đo chênh lệch thời gian chạy bù có và không có đệm.",
"Bật thử lại cho mọi loại lỗi · tính khoá đệm chỉ từ tham số mà bỏ trạng thái nguồn · lưu kết quả lớn qua tiến trình điều phối.",
"Thử lại chỉ kích hoạt cho lỗi tạm thời, và đổi dữ liệu nguồn làm tác vụ chạy lại chứ không dùng đệm."),

(255,"Subflows, task runners and concurrency","TH","Lesson 254",
"Luồng con là một luồng gọi từ luồng khác, và nó có trạng thái riêng nên thử lại được cả cụm mà không chạy lại toàn bộ. Dùng luồng con để nhóm các bước thành đơn vị phục hồi, và đây là quyết định kích thước đỉnh ở lesson 220 nhìn từ góc Prefect. Bộ chạy tác vụ quyết định tác vụ chạy đồng thời thế nào: tuần tự, nhiều luồng, hay nhiều tiến trình; áp trực tiếp phân loại tải ở lesson 50 và 59, tải nghẽn vào ra hợp nhiều luồng, tải nghẽn tính toán cần nhiều tiến trình. Gửi tác vụ và chờ kết quả, cùng mẫu thu kết quả từ nhiều tác vụ song song. Giới hạn đồng thời ở ba mức: trong một luồng, trong một nhóm công việc, và toàn cục theo thẻ; mức thứ ba tương ứng nhóm tài nguyên ở lesson 234 và là chỗ khai báo ràng buộc dùng chung với hệ đích. Bộ chạy tác vụ trên cụm phân tán cho tải lớn. Chọn bộ chạy theo loại tải chứ theo mặc định.",
"Chọn bộ chạy tác vụ cho hai loại tải khác nhau bằng số đo, và đặt giới hạn đồng thời toàn cục theo thẻ để bảo vệ hệ đích.",
"Tầng *đánh giá*. Objective đòi chọn theo loại tải với số đo, nối lại phương pháp lesson 12. Đạt khi có bảng thông lượng cho hai bộ chạy nhân hai loại tải, khi lựa chọn khớp loại tải, và khi giới hạn theo thẻ chặn được số kết nối tới hệ đích ở ngưỡng đặt ra.",
"Chạy pipeline có một phần nghẽn vào ra và một phần nghẽn tính toán. Thử ba bộ chạy tác vụ, đo thông lượng từng phần. Lập bảng. Tách phần nạp thành luồng con và thử lại riêng nó. Đặt giới hạn đồng thời theo thẻ cho các tác vụ chạm cơ sở dữ liệu và kiểm số kết nối cao nhất.",
"Dùng bộ chạy nhiều luồng cho tải nghẽn tính toán · đặt giới hạn đồng thời trong luồng rồi tưởng đã chặn ràng buộc dùng chung · gộp mọi bước vào một luồng nên thử lại là chạy lại tất cả.",
"Bảng hai bộ chạy nhân hai loại tải, và giới hạn theo thẻ chặn được số kết nối ở ngưỡng đặt ra."),

(256,"Blocks, variables and secret management","TH","Lesson 255",
"Khối là cấu hình có kiểu, đặt tên, lưu ngoài mã và nạp vào lúc chạy. Khác biệt với biến thường: khối có lược đồ nên sai kiểu bị bắt sớm, và khối bí mật được mã hoá khi lưu. Ba nhóm cấu hình và chỗ đặt tương ứng, nối lại lesson 75: tham số đổi theo lần chạy truyền qua tham số bản triển khai; tham số đổi theo môi trường đặt trong biến hoặc khối; thông tin xác thực đặt trong khối bí mật. Ba nơi thông tin xác thực vẫn rò ra dù đã dùng khối bí mật: in đối tượng khối ra nhật ký, truyền qua biến môi trường mà tiến trình con ghi lại, và lưu giá trị đã giải mã vào hiện vật; cách bịt từng nơi. Tích hợp với kho bí mật ngoài và điều kiện đáng chuyển. Khối hạ tầng mô tả nơi luồng chạy, nối lại lesson 252. Quyền trên khối và ai trong đội đọc được cái gì. Xoay vòng bí mật và yêu cầu mã phải đọc lại được thay vì đọc một lần lúc khởi động.",
"Chuyển toàn bộ thông tin xác thực sang khối bí mật, và chứng minh bằng quét rằng không giá trị nào trong kho mã, nhật ký hay hiện vật.",
"Tầng *áp dụng*. Sản phẩm là cấu hình chạy được cộng bằng chứng quét. Kiểm hai lớp: luồng chạy xanh, và quét kho mã, nhật ký lẫn hiện vật bằng công cụ tìm bí mật, đạt khi không kết quả nào. Lỗi rò rỉ chỉ lộ ra khi quét thật nên không kiểm bằng câu hỏi.",
"Chuyển thông tin xác thực của pipeline tham chiếu sang khối bí mật. Bật ghi nhật ký chi tiết và chạy lại. Quét nhật ký, hiện vật và toàn bộ lịch sử kho mã. Sửa mọi chỗ rò rồi quét lại. Xoay vòng một bí mật và xác nhận lần chạy sau dùng giá trị mới không cần khởi động lại.",
"In đối tượng khối ra nhật ký khi gỡ lỗi · lưu giá trị giải mã vào hiện vật · đọc bí mật một lần lúc khởi động nên xoay vòng không có hiệu lực.",
"Luồng chạy xanh, và quét kho mã, nhật ký lẫn hiện vật không ra thông tin xác thực nào."),

(257,"Artifacts, logging and observability","TH","Lesson 256",
"Hiện vật là đầu ra có cấu trúc gắn vào một lần chạy và xem được sau khi lần chạy kết thúc: bảng, đánh dấu, đường dẫn. Đây là chỗ đặt báo cáo chất lượng dữ liệu, số dòng theo bước, và chênh lệch so với lần chạy trước, thay vì để chúng trong nhật ký rồi phải đọc bằng mắt. Nhật ký có cấu trúc và lý do ghi khoá giá trị thay vì ghi câu, nối lại lesson 74; khi có 30 lần chạy một ngày thì lọc quan trọng hơn đọc. Ba mức nhật ký và tiêu chí dùng từng mức. Đưa nhật ký của luồng và nhật ký của tiến trình con về cùng một chỗ. Đo thời lượng từng tác vụ để biết chỗ nào chậm dần theo thời gian. Bốn chỉ số dùng chung với hai công cụ trước để M25 so được: tổng thời gian chạy, thời gian từ lúc hỏng tới lúc biết bước nào hỏng, thời gian chạy lại sau khi sửa một bước ở giữa, và số đỉnh hoặc tác vụ trong định nghĩa. Giới hạn khả năng quan sát ở tầng điều phối: nó biết luồng chạy bao lâu và hỏng ở đâu, không biết số trong bảng có đúng không.",
"Ghi báo cáo chất lượng mỗi lần chạy thành hiện vật đọc được sau khi lần chạy kết thúc, và đo bốn chỉ số dùng chung với hai công cụ trước.",
"Tầng *áp dụng*. Objective có sản phẩm và số đo cụ thể dùng lại ở M25. Đạt khi hiện vật xem được sau khi vùng chứa đã xoá và nội dung gồm số dòng theo bước cùng chênh lệch so lần trước, và khi bảng bốn chỉ số dùng đúng định nghĩa của lesson 226 và 245.",
"Ghi báo cáo chất lượng thành hiện vật dạng bảng. Xoá vùng chứa rồi mở lại hiện vật. Đo bốn chỉ số dùng chung. Ghi lại thời gian từ lúc bắt đầu module tới lúc luồng chạy được lần đầu, số đo này dùng ở M25. Gộp nhật ký luồng và nhật ký tiến trình con.",
"Ghi báo cáo vào nhật ký rồi mất khi xoay vòng nhật ký · ghi câu văn thay vì khoá giá trị nên không lọc được · đo bốn chỉ số bằng định nghĩa khác với hai module trước.",
"Hiện vật xem được sau khi xoá vùng chứa, và bảng bốn chỉ số dùng đúng định nghĩa của hai module trước."),

(258,"Failure handling, notifications and crash hooks","TH","Lesson 257",
"Ba tầng xử lý thất bại và cái mỗi tầng bắt: thử lại ở mức tác vụ cho lỗi tạm thời, xử lý trạng thái trong mã cho lỗi có phương án thay thế, và móc nối chuyển trạng thái cho việc thông báo. Móc nối chạy khi luồng hoặc tác vụ đổi trạng thái, nên nó là chỗ đặt cảnh báo có ngữ cảnh đầy đủ thay vì thông báo mặc định; nội dung phải nói ba thứ như lesson 232. Móc nối khi sập xử lý trường hợp tiến trình chết đột ngột, khác móc nối khi thất bại ở chỗ nó chạy trong điều kiện khắc nghiệt hơn, và nó không chạy được nếu máy bị giết cưỡng bức, nối lại lesson 21 và 66; nên vẫn cần dọn dẹp lúc khởi động. Tự động hoá gửi thông báo theo quy tắc, tách việc thông báo khỏi mã luồng. Gom cảnh báo cùng nguyên nhân. Lần chạy treo và phát hiện bằng tự động hoá theo thời lượng. Phân biệt luồng thất bại với luồng bị huỷ và với tiến trình thực thi chết, ba tình huống cần ba phản ứng khác nhau.",
"Cấu hình ba tầng xử lý thất bại và chứng minh mỗi tầng bắt đúng loại tình huống của nó, gồm cả trường hợp tiến trình bị giết cưỡng bức.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng bốn kịch bản khác nhau. Đạt khi bốn kịch bản cho bốn phản ứng đúng như thiết kế: lỗi tạm thời tự phục hồi không cảnh báo, lỗi xác định cảnh báo đủ ba thứ, tiến trình bị giết để lại dấu vết cho lần khởi động sau dọn, và lần chạy treo bị huỷ tự động.",
"Cấu hình ba tầng cho pipeline tham chiếu. Bơm bốn tình huống: lỗi mạng tự khỏi, lỗi dữ liệu xác định, giết cưỡng bức tiến trình, và một tác vụ treo vô hạn. Ghi phản ứng của hệ thống cho từng cái. Thêm bước dọn dẹp lúc khởi động và xác nhận nó xử lý dấu vết còn sót.",
"Dựa vào móc nối khi sập cho trường hợp giết cưỡng bức · gộp luồng bị huỷ với luồng thất bại · đặt việc thông báo trong mã luồng thay vì trong móc nối.",
"Bốn kịch bản cho bốn phản ứng đúng như thiết kế, gồm cả trường hợp giết cưỡng bức."),

(259,"Dynamic workflows and mapping","TH","Lesson 258",
"Sinh số tác vụ phụ thuộc dữ liệu lúc chạy, tương ứng sinh đỉnh động ở lesson 231 nhưng tự nhiên hơn vì luồng là mã Python nên vòng lặp và điều kiện dùng được trực tiếp. Ánh xạ một tác vụ lên một danh sách để chạy song song, và cách thu kết quả. Giới hạn số tác vụ sinh ra và lý do phải đặt: một lỗi ở nguồn trả về 100.000 phần tử sẽ sinh 100.000 tác vụ. Xử lý khi một phần trong tập ánh xạ thất bại: để cả luồng đổ, bỏ qua phần hỏng và ghi nhận, hoặc thử lại riêng phần đó; ba lựa chọn và tiêu chí. Ánh xạ lồng nhau và chi phí của nó. Đánh đổi với việc để một tác vụ xử lý cả danh sách trong vòng lặp, cùng bài toán ở lesson 231: nhiều tác vụ cho khả năng quan sát và thử lại riêng, một tác vụ cho chi phí điều phối thấp. Ngưỡng chọn theo thời gian xử lý mỗi phần tử và tỉ lệ hỏng. Luồng con động khi mỗi phần tử cần một chuỗi bước chứ một bước.",
"Chuyển một tác vụ xử lý danh sách trong vòng lặp sang ánh xạ động, và xác định ngưỡng mà cách nào rẻ hơn bằng thực nghiệm.",
"Tầng *đánh giá*. Objective đòi chọn giữa hai cách có đánh đổi hai chiều, và số đo so được với lesson 231. Đạt khi có bảng thực nghiệm ít nhất bốn kích thước danh sách kèm tổng thời gian và thời gian phát hiện lỗi, và khi ngưỡng chọn ra biện minh bằng cả hai chỉ số.",
"Tác vụ nạp N tệp, chạy ở N bằng 5, 50, 500, 5.000. Cài cả hai cách. Đo tổng thời gian và thời gian từ lúc một tệp hỏng tới lúc biết tệp nào. So bảng với kết quả lesson 231. Đặt giới hạn số tác vụ sinh ra và thử vượt. Cho một phần tử hỏng và thử ba cách xử lý.",
"Không đặt giới hạn số tác vụ sinh ra · để cả luồng đổ khi một phần tử trong 5.000 hỏng · chọn cách theo tổng thời gian mà bỏ thời gian phát hiện lỗi.",
"Bảng bốn kích thước danh sách có cả hai chỉ số, và ngưỡng chọn ra biện minh bằng cả hai."),

(260,"Operating Prefect - self-hosted against Cloud","TH","Lesson 259",
"Không có cơ chế mới. Bài gộp module. Hai cách vận hành và đánh đổi: máy chủ tự dựng cho toàn quyền kiểm soát và dữ liệu không ra ngoài, nhưng phải vận hành máy chủ, cơ sở dữ liệu và bản sao lưu; dịch vụ đám mây bỏ được phần đó nhưng siêu dữ liệu lần chạy nằm ngoài và có chi phí theo mức dùng. Điều cần rõ ở cả hai cách: dữ liệu của mình không đi qua đó, chỉ siêu dữ liệu đi, nên câu hỏi tuân thủ là về siêu dữ liệu chứ về dữ liệu. Cơ sở dữ liệu của máy chủ tự dựng cần bảo trì như một cơ sở dữ liệu thật, áp kiến thức M11: phình, sao lưu, di trú khi nâng cấp. Ba sự cố vận hành và quy trình chẩn đoán: tiến trình thực thi không nhận việc, lần chạy mồ côi sau khi tiến trình thực thi chết, và cơ sở dữ liệu máy chủ phình. Triển khai phiên bản mã mới và cửa sổ hai phiên bản cùng tồn tại. Sao lưu và thứ mất khi mất cơ sở dữ liệu máy chủ.",
"Chẩn đoán ba sự cố vận hành chưa từng thấy, và nêu tiêu chí chọn giữa máy chủ tự dựng với dịch vụ đám mây cho một đội cho trước.",
"Tầng *đánh giá*. Objective đòi chẩn đoán cộng một quyết định kiến trúc. Chấm theo bốn mục: chẩn đoán ba sự cố 45đ, tiêu chí chọn cách vận hành 25đ, sổ tay xử lý 20đ, và sao lưu 10đ. Đạt khi ≥ 70/100 và mục chẩn đoán ≥ 60%. Phần tiêu chí chọn phải nêu rõ cái gì đi ra ngoài và cái gì không.",
"Cụm Prefect tự dựng có tải. Giám khảo gây ba sự cố không báo trước. Chẩn đoán theo quy trình, ghi số đo trước khi sửa. Viết tiêu chí chọn cho hai đội khác nhau về quy mô và ràng buộc tuân thủ. Nộp sổ tay xử lý và quy trình sao lưu cơ sở dữ liệu máy chủ.",
"Chọn dịch vụ đám mây mà không xác định siêu dữ liệu nào ra ngoài · bỏ bảo trì cơ sở dữ liệu máy chủ tự dựng · khởi động lại tiến trình thực thi khi gặp sự cố thay vì chẩn đoán.",
"Đạt ≥ 70/100 và mục chẩn đoán ≥ 60%, với tiêu chí chọn nêu rõ cái gì ra ngoài."),
]
