# -*- coding: utf-8 -*-
"""DE M21 Orchestration foundations + M22 Apache Airflow."""

M21 = ("Orchestration Foundations", 219, 224, """| | |
|---|---|
| **Objective cấp module** | Phát biểu một bài toán điều phối bằng từ vựng đồ thị, máy trạng thái và ngày logic, trước khi mở bất kỳ công cụ nào |
| **Tiền đề** | M20 |
| **Exit criterion** | Nhận sáu tình huống hỏng của một hệ chạy bằng cron, định vị đúng cơ chế cho cả sáu và nêu công cụ điều phối giải nó bằng cách nào |
| **Kỹ năng SFIA** | `PROG` mức 3 · `SYSP` mức 3 |
| **Chế độ hỏng** | Học thẳng vào công cụ, rồi coi mọi vấn đề điều phối là vấn đề cấu hình, nên đổi công cụ mà lỗi vẫn còn |""",
"""Module không mở công cụ nào. Nó dựng từ vựng để ba module công cụ sau có cái mà so sánh, và để M25 chấm được bằng tiêu chí thay vì bằng cảm nhận. Không có module này thì M25 tụt xuống thành bài liệt kê tính năng.

**Pipeline tham chiếu.** M22, M23 và M24 dựng lại cùng một pipeline: nạp từ PostgreSQL và một giao diện lập trình web có phân trang, ghi vào kho đối tượng, biến đổi, nạp lớp phục vụ, có phép kiểm chất lượng. Đó chính là nền tảng theo lô đã xây ở lesson 217. Cùng dữ liệu, cùng lỗi cài sẵn, cùng kịch bản giết tiến trình. Không cùng bài toán thì M25 không đo được gì.""")

L21 = [
(219,"Why an orchestrator exists - cron and the failures it cannot handle","LT","Module 21: M20",
"Cron biểu diễn được đúng một thứ: chạy lệnh này vào thời điểm này. Sáu tình huống nó không biểu diễn được, mỗi tình huống kèm hậu quả quan sát được trên pipeline ở lesson 217. Một là phụ thuộc: bước biến đổi phải chờ bước nạp xong, mà cron không biết bước nạp đã xong chưa nên chỉ đoán bằng cách đặt giờ muộn hơn, và cách đoán đó hỏng ngay khi nguồn chậm một lần. Hai là chồng lần chạy: lần chạy hai giờ chưa xong thì lần ba giờ đã khởi động, hai tiến trình cùng ghi một bảng, nối lại lesson 207. Ba là thử lại: cron không có khái niệm thất bại tạm thời. Bốn là chạy bù: mất ba ngày dữ liệu thì không có cách nào bảo cron chạy lại đúng ba ngày đó theo thứ tự, nối lại lesson 210. Năm là khả năng quan sát. Sáu là trạng thái: cron không biết lần chạy trước dừng ở đâu. Phân biệt lập lịch với điều phối: lập lịch trả lời khi nào, điều phối trả lời theo thứ tự nào và nếu hỏng thì sao.",
"Định vị trong sáu tình huống cái nào gây ra một sự cố cho trước, dựa vào nhật ký và bảng kết quả chứ vào phỏng đoán.",
"Tầng *phân tích*. Bài mở module, người học đã vận hành pipeline từ M20 nên có kinh nghiệm để soi lại, nhưng chưa có công cụ điều phối nào. Objective dừng ở phân rã một sự cố về đúng cơ chế. Kiểm bằng sáu hồ sơ sự cố có nhật ký và ảnh chụp bảng; đạt khi định vị đúng ít nhất năm và mỗi lần dẫn được bằng chứng, không chấp nhận đoán đúng mà không dẫn.",
"Chạy nền tảng lesson 217 bằng cron trong môi trường mô phỏng 30 ngày có sự cố. Nhận sáu hồ sơ sự cố. Với mỗi hồ sơ, chỉ ra tình huống nào trong sáu, dẫn dòng nhật ký hoặc số liệu làm bằng chứng, và nêu cron thiếu khả năng gì.",
"Quy mọi sự cố về mã pipeline sai thay vì về cách nó được gọi · nhầm hai tiến trình chồng nhau với lỗi khoá của kho · cho rằng đặt giờ muộn hơn là cách giải quyết phụ thuộc.",
"Định vị đúng ít nhất năm trên sáu hồ sơ, mỗi lần dẫn được nhật ký hoặc số liệu làm bằng chứng."),

(220,"DAG, task dependency and the state machine of a run","LT","Lesson 219",
"Đồ thị có hướng không chu trình làm mô hình cho công việc: đỉnh là một đơn vị chạy được, cạnh là quan hệ phải xong trước. Điều kiện phi chu trình và chuyện gì xảy ra khi đồ thị có chu trình lọt vào công cụ. Sắp xếp tô pô và lý do có nhiều thứ tự chạy hợp lệ cho cùng một đồ thị, từ đó suy ra chỗ chạy song song được. Đường găng: chuỗi dài nhất quyết định thời gian chạy tối thiểu, nên tối ưu một đỉnh không nằm trên đường găng không rút ngắn được gì, nối lại định luật Amdahl ở lesson 50. Máy trạng thái của một lần chạy: chờ lịch, đã xếp hàng, đang chạy, thành công, thất bại, chờ thử lại, bỏ qua, hết hạn; chuyển trạng thái nào hợp lệ và chuyển nào thì không. Phân biệt trạng thái một đỉnh với trạng thái cả lần chạy, và bốn quy tắc gộp thường gặp. Kích thước một đỉnh là quyết định thiết kế: đỉnh quá nhỏ thì chi phí điều phối lấn át, quá lớn thì hỏng phải chạy lại nhiều.",
"Vẽ đồ thị phụ thuộc của nền tảng ở lesson 217, chỉ ra đường găng, và liệt kê các nhóm chạy song song được.",
"Tầng *áp dụng*. Objective là thực hiện một thủ tục xác định trên hệ thống của chính mình. Đạt khi đồ thị phi chu trình, đường găng chỉ ra đúng với đồ thị đó, và nhóm song song khớp sắp xếp tô pô. Chấm bằng đối chiếu với đồ thị sinh tự động từ danh sách phụ thuộc khai báo.",
"Lấy nền tảng lesson 217. Vẽ đồ thị phụ thuộc bằng tay từ mã. Chỉ đường găng và các nhóm song song. Đo thời gian chạy tuần tự và ước lượng thời gian tối thiểu từ đường găng. Chạy song song theo nhóm đã xác định và so với ước lượng.",
"Nhầm thứ tự viết mã với thứ tự phụ thuộc · tối ưu một bước không nằm trên đường găng · chia đỉnh quá nhỏ nên chi phí điều phối lấn át.",
"Đồ thị phi chu trình khớp danh sách phụ thuộc khai báo, và thời gian chạy song song gần ước lượng từ đường găng."),

(221,"Logical date against wall-clock date; schedule against event trigger","LT","Lesson 220",
"Ngày logic là khoảng dữ liệu mà lần chạy chịu trách nhiệm, còn ngày chạy thật là lúc tiến trình khởi động. Hai cái này gần như không bao giờ trùng, và đây là nguồn sai sót phổ biến nhất khi chạy bù, nối lại lesson 210. Hệ quả trực tiếp lên pipeline: mọi bước lọc theo thời gian phải lọc theo ngày logic, không theo đồng hồ hệ thống, nếu không thì chạy bù ngày hôm kia sẽ nạp dữ liệu hôm nay. Cách truyền ngày logic vào công việc qua tham số dòng lệnh, nối lại lesson 76. Lập lịch theo thời gian: biểu thức cron, múi giờ, và hai bất thường mà giờ mùa hè tạo ra, nối lại lesson 9. Lập lịch theo sự kiện: kích hoạt khi tệp xuất hiện, khi bảng nguồn cập nhật, khi một lần chạy khác kết thúc. Đánh đổi: lịch theo thời gian dễ suy luận và dễ chạy bù nhưng phải đoán độ trễ nguồn; theo sự kiện bám nguồn sát hơn nhưng khó trả lời câu hỏi lần chạy cho ngày mùng ba ở đâu. Mẫu lai có thời gian chờ tối đa.",
"Chuyển một bước pipeline đang đọc đồng hồ hệ thống sang nhận ngày logic từ ngoài, và chứng minh bằng chạy bù rằng kết quả khớp bản chạy đúng ngày.",
"Tầng *áp dụng*. Objective là phép biến đổi mã có tiêu chí đúng sai rõ, kiểm bằng chạy thật. Đạt khi chạy bù ba ngày quá khứ cho kết quả khớp từng dòng với bản đối chứng sinh khi chạy đúng vào ngày đó. Không kiểm bằng câu hỏi vì lỗi này chỉ lộ ra khi chạy.",
"Tìm mọi chỗ trong nền tảng lesson 217 đọc đồng hồ hệ thống. Chuyển sang nhận ngày logic qua tham số. Chạy bù ba ngày liên tiếp trong quá khứ. So từng dòng với bảng đối chứng. Thiết kế mẫu lai lịch theo giờ cộng cảm biến chờ nguồn có thời gian chờ tối đa.",
"Đọc đồng hồ hệ thống trong bước biến đổi · đặt lịch theo giờ máy chủ rồi lệch một ngày với người dùng khác múi giờ · bỏ thời gian chờ tối đa cho cảm biến.",
"Ba ngày chạy bù khớp từng dòng với bảng đối chứng."),

(222,"Idempotency, retries, timeouts and what may be retried safely","LT","Lesson 221",
"Bất biến khi chạy lại đã gặp ở lesson 106, 205 và 217; bài này phát biểu nó thành điều kiện của điều phối. Quy tắc: một đỉnh chỉ được phép thử lại khi nó bất biến, nên tính bất biến không phải tính chất tốt mà là điều kiện để bật thử lại. Phân biệt thất bại tạm thời với thất bại xác định, nối lại lesson 65: lỗi mạng, hết thời gian chờ, kho bận là tạm thời và thử lại có nghĩa; lỗi cú pháp, thiếu cột, phép kiểm chất lượng không đạt là xác định, thử lại chỉ tốn thời gian và che mất tín hiệu. Khoảng chờ tăng dần và nhiễu ngẫu nhiên, nối lại lesson 34. Số lần thử lại theo loại đỉnh: đỉnh chờ nguồn thử nhiều, đỉnh biến đổi thử ít. Thời gian chờ ở hai mức, đỉnh và cả lần chạy, cùng lý do thiếu cái thứ hai làm một lần chạy treo chiếm chỗ mãi. Chạy tiếp từ chỗ hỏng so với chạy lại từ đầu, và điều kiện để chạy tiếp cho kết quả đúng.",
"Phân loại các đỉnh trong pipeline thành bất biến và không bất biến, và đặt chính sách thử lại phù hợp cho từng loại.",
"Tầng *phân tích*. Objective đòi phán đoán về tính chất của từng đỉnh rồi suy ra cấu hình. Đạt khi phân loại đúng cả tám đỉnh của nền tảng lesson 217, kiểm bằng chạy lại từng đỉnh và đối chiếu, và khi 12 thông báo lỗi được phân loại tạm thời hay xác định đúng ít nhất 10.",
"Với tám đỉnh của nền tảng, chạy lại từng đỉnh hai lần và đối chiếu để xác định tính bất biến. Sửa đỉnh nào chưa bất biến. Phân loại 12 thông báo lỗi. Đặt chính sách thử lại theo loại đỉnh. Bật thử lại cho một đỉnh chưa bất biến và quan sát nhân bản dữ liệu.",
"Bật thử lại cho mọi đỉnh mà không kiểm tính bất biến · đặt cùng số lần thử lại cho mọi đỉnh · thử lại một phép kiểm chất lượng không đạt.",
"Tám đỉnh phân loại đúng kiểm bằng chạy lại, và 12 thông báo lỗi phân loại đúng ít nhất 10."),

(223,"Backfill, catchup and concurrency limits","TH","Lesson 222",
"Chạy bù là chạy lại một dải ngày logic trong quá khứ, đã gặp ở lesson 210; bài này thêm chiều điều phối. Bắt kịp là cơ chế tự động sinh các lần chạy còn thiếu kể từ ngày bắt đầu, và nó bật theo mặc định ở nhiều công cụ; hệ quả là bật một đồ thị có ngày bắt đầu sáu tháng trước sẽ sinh hàng trăm lần chạy cùng lúc và làm sập hệ đích. Ba câu hỏi trước mỗi lần chạy bù: các ngày độc lập hay phải theo thứ tự, chạy được mấy ngày cùng lúc mà hệ đích chịu được, và mọi đỉnh liên quan đã bất biến chưa. Giới hạn song song ở ba tầng: toàn hệ thống, một đồ thị, và một nhóm tài nguyên dùng chung; chỉ tầng thứ ba biểu diễn được ràng buộc chia sẻ giữa nhiều đồ thị, nên đây là chỗ khai báo số kết nối mà cơ sở dữ liệu chịu được, nối lại lesson 134. Theo dõi tiến độ một lần chạy bù dài và cách dừng giữa chừng mà không để lại trạng thái dở.",
"Chạy bù 30 ngày cho nền tảng dưới giới hạn ba lần chạy đồng thời, và chứng minh kết quả khớp bản chạy tuần tự từng ngày.",
"Tầng *áp dụng*. Objective có tiêu chí đúng sai tuyệt đối và chỉ kiểm được bằng chạy thật quy mô. Đạt khi bảng sau chạy bù khớp từng dòng với bản đối chứng sinh bằng chạy tuần tự 30 ngày. Lệch một dòng là không đạt, vì sai sót chạy bù đúng là thứ chỉ lộ ra ở quy mô này.",
"Sinh bản đối chứng bằng chạy tuần tự 30 ngày. Xoá bảng đích. Chạy bù 30 ngày với giới hạn ba lần chạy đồng thời. Giết một tiến trình giữa chừng và để hệ thống tự phục hồi. So từng dòng. Đo mức dùng kết nối cơ sở dữ liệu ở hai mức giới hạn song song.",
"Bật bắt kịp mà không đặt giới hạn song song · chạy bù song song các ngày khi có chiều thay đổi chậm, nối lại lesson 210 · đặt giới hạn ở mức đồ thị rồi tưởng đã chặn ràng buộc chia sẻ.",
"Bảng sau chạy bù khớp từng dòng với bản đối chứng, kể cả sau khi một tiến trình bị giết."),

(224,"What an orchestrator is not - processing engine and message broker","LT","Lesson 223",
"Ba loại hệ thống hay bị gộp và ranh giới giữa chúng. Công cụ điều phối quyết định cái gì chạy khi nào và theo thứ tự nào; nó không xử lý dữ liệu. Bộ máy xử lý biến đổi dữ liệu; Spark ở M35 là ví dụ. Hàng đợi bản tin chuyển bản tin giữa các dịch vụ; Kafka ở M29 là ví dụ. Ba dấu hiệu dùng sai công cụ điều phối và hậu quả: đẩy dữ liệu qua cơ chế truyền tham số giữa các đỉnh làm cơ sở dữ liệu siêu dữ liệu phình và chậm; xử lý từng bản ghi bằng một đỉnh mỗi bản ghi làm đồ thị hàng nghìn đỉnh; và dùng nó làm hàng đợi công việc thời gian thực trong khi nó lập lịch theo chu kỳ. Nguyên tắc phân công: công cụ điều phối gọi bộ máy xử lý và chờ kết quả, dữ liệu đi qua kho lưu trữ chứ không đi qua công cụ điều phối. Trường hợp không cần công cụ điều phối: một công việc duy nhất chạy theo lịch không phụ thuộc gì, cron là đủ và thêm công cụ chỉ thêm thứ phải vận hành.",
"Phân loại 12 nhu cầu vào ba loại hệ thống, và nêu điều kiện một đội chưa cần công cụ điều phối riêng.",
"Tầng *đánh giá*. Objective đòi phán đoán ranh giới, gồm cả phán đoán không dùng gì cả. Đạt khi phân loại đúng ít nhất 10 trên 12 nhu cầu kèm lý do, và khi điều kiện chưa cần công cụ điều phối nêu được bằng đặc tính cụ thể của công việc chứ bằng quy mô đội.",
"Nhận 12 nhu cầu thật và phân loại vào ba loại hệ thống. Với ba nhu cầu mơ hồ, nêu thêm câu hỏi cần hỏi để phân loại. Dựng một đồ thị đẩy 50 mê ga byte qua cơ chế truyền tham số giữa hai đỉnh và đo tác động lên cơ sở dữ liệu siêu dữ liệu.",
"Đẩy dữ liệu qua cơ chế truyền tham số giữa các đỉnh · tạo một đỉnh cho mỗi bản ghi · dựng công cụ điều phối cho một công việc duy nhất không phụ thuộc gì.",
"Phân loại đúng ít nhất 10 trên 12 nhu cầu kèm lý do, và điều kiện chưa cần công cụ nêu bằng đặc tính công việc."),
]

M22 = ("Apache Airflow", 225, 236, """| | |
|---|---|
| **Objective cấp module** | Vận hành Airflow ở mức sản xuất: chẩn đoán bộ lập lịch đứng, chọn bộ thực thi có căn cứ, và chạy bù quy mô lớn dưới giới hạn tài nguyên |
| **Tiền đề** | M21 |
| **Exit criterion** | Pipeline tham chiếu chạy trên Airflow, chạy bù 90 ngày dưới giới hạn tài nguyên khớp bản đối chứng, và chẩn đoán được ba sự cố vận hành |
| **Kỹ năng SFIA** | `PROG` mức 4 · `SYSP` mức 4 |
| **Chế độ hỏng** | Dựng được đồ thị chạy xanh trên máy cá nhân rồi dừng ở đó, nên gặp cụm thật là không chẩn đoán được gì |""",
"""Airflow ở mức `A`, góc nhìn vận hành nền tảng. Chương trình Analytics Engineer cũng có module Airflow nhưng ở góc điều phối một dự án dbt; hai module không trùng bài nào. Hai bài đầu là cơ chế, tám bài giữa là tính năng và vận hành dưới ràng buộc, hai bài cuối là bộ thực thi và chẩn đoán cụm.

Mọi tham số cấu hình phụ thuộc phiên bản, nên phải đối chiếu tài liệu chính thức của đúng phiên bản đang cài chứ không theo bài hướng dẫn tìm được.""")

L22 = [
(225,"Architecture - scheduler, metadata database, executor, worker","LT","Module 22: M21",
"Bốn thành phần và trách nhiệm tách bạch. Bộ lập lịch đọc tệp định nghĩa, dựng đồ thị, quyết định đỉnh nào đủ điều kiện chạy, và ghi quyết định xuống cơ sở dữ liệu siêu dữ liệu. Cơ sở dữ liệu siêu dữ liệu giữ toàn bộ trạng thái, nên nó vừa là nguồn sự thật duy nhất vừa là điểm hỏng chung và chỗ nghẽn khi đồ thị lớn; mọi kiến thức ở M11 áp dụng trực tiếp vào việc vận hành nó. Bộ thực thi quyết định đỉnh chạy ở đâu, chi tiết ở lesson 235. Tiến trình thực thi chạy đỉnh thật. Đường đi của một đỉnh qua bốn thành phần theo thứ tự, kèm chỗ nó kẹt được ở mỗi chặng. Giao diện web đọc từ cơ sở dữ liệu siêu dữ liệu chứ không hỏi tiến trình thực thi, nên nó hiển thị trạng thái đã ghi chứ không hiển thị tiến trình đang chạy thật. Ba triệu chứng vận hành và chặng tương ứng: đỉnh nằm mãi ở đã xếp hàng, đồ thị không xuất hiện, và giao diện chậm.",
"Truy một đỉnh đang kẹt về đúng thành phần gây kẹt, dựa vào trạng thái trong cơ sở dữ liệu siêu dữ liệu và nhật ký của thành phần đó.",
"Tầng *phân tích*. Bài lý thuyết nhưng objective là chẩn đoán, nên kiểm bằng ca bệnh chứ bằng định nghĩa. Ba ca dựng sẵn, mỗi ca kẹt ở một thành phần khác nhau; đạt khi chỉ đúng cả ba và dẫn được bằng chứng từ trạng thái hoặc nhật ký. Hỏi lại định nghĩa bốn thành phần không phải phép kiểm hợp lệ cho objective này.",
"Dựng Airflow bằng Docker Compose. Mở cơ sở dữ liệu siêu dữ liệu bằng ứng dụng khách SQL và đọc trực tiếp bảng trạng thái đỉnh. Nhận ba ca: đỉnh kẹt ở đã xếp hàng, đồ thị không hiện trong giao diện, giao diện chậm. Với mỗi ca, chỉ thành phần gây ra và dẫn bằng chứng.",
"Đọc trạng thái từ giao diện rồi tưởng đó là tiến trình thật · khởi động lại cả cụm thay vì đọc nhật ký của đúng thành phần · sửa cấu hình theo hướng dẫn của phiên bản khác.",
"Chỉ đúng thành phần cho cả ba ca, mỗi ca dẫn được trạng thái hoặc dòng nhật ký làm bằng chứng."),

(226,"DAG parsing, the top-level code trap and import time","TH","Lesson 225",
"Tệp định nghĩa đồ thị được bộ lập lịch đọc lại theo chu kỳ, thường vài chục giây một lần. Hệ quả phản trực giác: mã ở tầng ngoài cùng của tệp chạy lại mỗi lần đọc, còn mã trong thân đỉnh chỉ chạy khi đỉnh chạy. Một lệnh gọi cơ sở dữ liệu hoặc lệnh gọi mạng đặt ở tầng ngoài sẽ được thực hiện hàng nghìn lần mỗi ngày, làm chậm bộ lập lịch cho mọi đồ thị trong cụm chứ không riêng đồ thị đó, nối thẳng bẫy ở lesson 68. Cách đo thời gian phân tích tệp và ngưỡng đáng lo. Ba mẫu sai thường gặp và cách sửa từng cái: đọc cấu hình từ kho dữ liệu ở tầng ngoài, sinh danh sách đỉnh bằng cách truy vấn bảng, và khởi tạo ứng dụng khách ở phạm vi mô đun. Biến và kết nối lưu trong cơ sở dữ liệu siêu dữ liệu, nên đọc chúng ở tầng ngoài cũng là một dạng của cùng cái bẫy. Số lượng tệp đồ thị và thời gian phân tích tổng, cùng ngưỡng cần chia cụm.",
"Dựng đồ thị chạy pipeline tham chiếu và hạ thời gian phân tích tệp xuống dưới ngưỡng đo được sau khi sửa mã ở tầng ngoài.",
"Tầng *áp dụng*. Có sản phẩm chạy được và một phép đo trước sau, nên kiểm bằng số. Đạt khi đồ thị chạy xanh và thời gian phân tích giảm xuống dưới một giây, có ảnh chụp số đo trước và sau. Giải thích được cái bẫy mà không hạ được số thì chưa đạt.",
"Nhận tệp đồ thị cố ý đặt ba lệnh gọi ở tầng ngoài. Đo thời gian phân tích. Sửa cả ba. Đo lại. Dựng đồ thị chạy pipeline tham chiếu, chạy xanh một lần. Sinh 200 tệp đồ thị và đo thời gian phân tích tổng của bộ lập lịch.",
"Khởi tạo ứng dụng khách kho dữ liệu ở phạm vi mô đun · sinh đỉnh bằng truy vấn bảng trong lúc phân tích tệp · đặt lệnh nhập nặng ở đầu tệp rồi kết luận bộ lập lịch yếu.",
"Đồ thị chạy xanh, và thời gian phân tích tệp sau khi sửa dưới một giây có số đo trước sau."),

(227,"Task lifecycle and state transitions in the metadata database","TH","Lesson 226",
"Vòng đời một lần chạy đỉnh đi qua các trạng thái ở lesson 220, và bài này đọc chúng trực tiếp từ bảng trong cơ sở dữ liệu siêu dữ liệu thay vì qua giao diện. Lần thử là đơn vị lưu nhật ký, nên một đỉnh thử lại ba lần có ba tệp nhật ký riêng, và đọc nhầm lần thử là lý do phổ biến khiến kết luận sai nguyên nhân. Cấu trúc thư mục nhật ký và cách tìm nhật ký khi giao diện không mở được. Ba lớp thông báo lỗi chồng lên nhau khi pipeline chạy trong Airflow: lỗi của hệ đích ở trong cùng, lỗi của mã pipeline ở giữa, lỗi của Airflow ở ngoài; quy tắc đọc từ trong ra ngoài vì lớp ngoài thường chỉ nói tiến trình con trả về mã khác không. Phân biệt đỉnh thất bại với đỉnh bị đánh dấu bỏ qua vì cha thất bại, và vì sao đếm đỉnh thất bại trong một lần chạy hỏng thường ra con số gây hiểu nhầm. Đánh dấu lại trạng thái bằng tay và khi nào việc đó chính đáng.",
"Nhận một lần chạy hỏng và truy về đúng bước gây lỗi cùng dòng thông báo gốc, không dừng ở thông báo mã trả về khác không.",
"Tầng *phân tích*. Objective là truy nguyên qua ba lớp trừu tượng. Kiểm bằng ba lần chạy hỏng dựng sẵn, mỗi lần hỏng vì một lớp khác nhau; đạt khi chỉ đúng bước và dẫn đúng dòng thông báo gốc cho cả ba. Nêu đúng bước mà dẫn thông báo của lớp ngoài thì tính là chưa đạt.",
"Nhận ba lần chạy hỏng: một do SQL sai, một do phép kiểm chất lượng không đạt, một do hết thời gian chờ hệ đích. Với mỗi lần, truy về bước và dòng thông báo gốc. Đọc trực tiếp bảng trạng thái đỉnh trong cơ sở dữ liệu siêu dữ liệu. Đẩy nhật ký ra kho lưu trữ ngoài và đọc lại sau khi xoá vùng chứa.",
"Đọc nhật ký của lần thử đầu trong khi lỗi thật ở lần thử cuối · dừng ở thông báo mã trả về khác không · đếm cả đỉnh bị bỏ qua vào số đỉnh thất bại.",
"Truy đúng bước và dòng thông báo gốc cho cả ba lần chạy, và đọc lại được nhật ký sau khi xoá vùng chứa."),

(228,"Operators, hooks and connections","TH","Lesson 227",
"Toán tử là khuôn cho một loại công việc, móc nối là lớp mã nói chuyện với một hệ ngoài, và kết nối là bản ghi cấu hình trong cơ sở dữ liệu siêu dữ liệu. Ba lớp này tách bạch để mã đỉnh không bao giờ chạm tới thông tin xác thực. Kết nối được mã hoá bằng một khoá đối xứng, nên mất khoá là mất toàn bộ kết nối và đổi khoá phải mã hoá lại. Ba nơi thông tin xác thực rò ra ngoài dù đã dùng kết nối: in ra nhật ký khi gỡ lỗi, truyền qua biến môi trường mà tiến trình con ghi lại, và nằm trong tệp cấu hình nộp vào kho mã; cách bịt từng nơi, nối lại lesson 75. Kho bí mật ngoài và điều kiện đáng chuyển sang. Phân biệt biến với kết nối: biến cho tham số cấu hình, kết nối cho thông tin xác thực. Viết toán tử riêng khi không có sẵn, và tiêu chí chọn giữa viết toán tử riêng với gọi lệnh trong toán tử chung. Quyền trên kết nối và ai trong đội xem được cái gì.",
"Cấu hình pipeline lấy mọi thông tin xác thực từ kết nối lúc chạy, và chứng minh bằng quét rằng không thông tin xác thực nào trong kho mã hay nhật ký.",
"Tầng *áp dụng*. Sản phẩm là cấu hình chạy được cộng bằng chứng quét. Kiểm hai lớp: chạy được, và quét toàn bộ kho mã cùng nhật ký bằng công cụ tìm bí mật, đạt khi không có kết quả nào. Không kiểm bằng câu hỏi vì lỗi rò rỉ chỉ lộ ra khi quét thật.",
"Chuyển pipeline tham chiếu sang lấy thông tin xác thực từ kết nối. Bật chế độ gỡ lỗi chi tiết, chạy lại, quét nhật ký. Quét toàn bộ lịch sử kho mã. Viết một toán tử riêng cho bước nạp từ giao diện lập trình web và so với cách gọi lệnh trong toán tử chung.",
"Nộp tệp cấu hình có mật khẩu rồi xoá ở lần nộp sau mà quên lịch sử · in toàn bộ biến môi trường khi gỡ lỗi · nhét mật khẩu vào biến vì nhanh hơn.",
"Pipeline chạy xanh với kết nối, và quét kho mã cùng nhật ký không ra thông tin xác thực nào."),

(229,"XCom, its size limit, and why data does not travel through it","TH","Lesson 228",
"Cơ chế truyền giá trị giữa các đỉnh lưu trong cơ sở dữ liệu siêu dữ liệu, nên mọi giá trị truyền qua nó là một dòng trong bảng. Hệ quả và giới hạn: kích thước tối đa phụ thuộc kiểu cột của cơ sở dữ liệu nền, và vượt quá thì lỗi hoặc cắt cụt tuỳ phiên bản. Vấn đề thật không phải giới hạn mà là hiệu năng: đẩy dữ liệu qua đây làm bảng phình, làm giao diện chậm, và làm cơ sở dữ liệu siêu dữ liệu thành nút cổ chai cho cả cụm, đúng thứ đã cảnh báo ở lesson 224. Cái nên truyền qua nó: đường dẫn tệp, mã định danh lô, số bản ghi, cờ trạng thái. Cái không nên: bảng dữ liệu, nội dung tệp, danh sách dài. Mẫu đúng: dữ liệu đi qua kho lưu trữ, chỉ đường dẫn đi qua cơ chế truyền giá trị. Dọn dẹp bảng này định kỳ và hậu quả khi quên. Phụ thuộc ngầm giữa hai đỉnh qua cơ chế này mà không có cạnh trong đồ thị, một lỗi thiết kế làm thứ tự chạy không bảo đảm.",
"Chuyển một đồ thị đang đẩy dữ liệu qua cơ chế truyền giá trị sang mẫu truyền đường dẫn, và đo tác động lên cơ sở dữ liệu siêu dữ liệu.",
"Tầng *áp dụng*. Objective có một phép biến đổi và một phép đo tác động. Đạt khi kích thước bảng liên quan giảm ít nhất 95% sau khi chuyển, và khi thời gian tải giao diện danh sách lần chạy giảm đo được.",
"Dựng đồ thị đẩy 50 mê ga byte qua cơ chế truyền giá trị, chạy 100 lần. Đo kích thước bảng và thời gian tải giao diện. Chuyển sang truyền đường dẫn tới kho đối tượng, chạy lại 100 lần, đo lại. Tìm một phụ thuộc ngầm giữa hai đỉnh và thêm cạnh tường minh cho nó.",
"Đẩy khung dữ liệu qua cơ chế truyền giá trị · dựa vào phụ thuộc ngầm thay vì khai báo cạnh · quên dọn bảng này nên nó phình theo thời gian.",
"Kích thước bảng giảm ít nhất 95%, và thời gian tải giao diện danh sách lần chạy giảm đo được."),

(230,"Sensors - poke against reschedule - and deferrable tasks","TH","Lesson 229",
"Cảm biến là đỉnh chờ một điều kiện thành đúng, và nó là cách cài lập lịch theo sự kiện ở lesson 221. Hai chế độ và khác biệt quyết định: chế độ thăm dò giữ chỗ tiến trình thực thi suốt thời gian chờ, chế độ lên lịch lại nhả chỗ giữa hai lần kiểm. Hệ quả vận hành: 20 cảm biến chế độ thăm dò trên cụm có 16 chỗ làm mọi đỉnh khác không chạy được, một tình trạng bế tắc tài nguyên trông như hệ thống treo. Đây là sự cố phổ biến và nó không hiện ra như lỗi. Đỉnh hoãn lại đẩy việc chờ sang một tiến trình riêng nên không chiếm chỗ nào, giải quyết triệt để hơn chế độ lên lịch lại, nhưng đòi mã viết theo kiểu bất đồng bộ, nối lại lesson 58. Thời gian chờ tối đa cho cảm biến là bắt buộc, nếu không thì nó chờ vô hạn. Phân biệt cảm biến với thử lại: cảm biến chờ điều kiện ngoài, thử lại xử lý lỗi tạm thời. Mẫu thay thế: để hệ nguồn kích hoạt thay vì mình chờ.",
"Tái hiện bế tắc tài nguyên do cảm biến chế độ thăm dò, và sửa bằng hai cách, đo số chỗ tiến trình thực thi bị chiếm ở mỗi cách.",
"Tầng *phân tích*. Objective đòi tái hiện một sự cố không hiện ra như lỗi rồi sửa có đo. Đạt khi tái hiện được tình trạng không đỉnh nào chạy được dù cụm rỗi, và khi hai bản sửa đều hạ số chỗ bị chiếm xuống dưới hai, có số đo cho cả ba trạng thái.",
"Cụm 8 chỗ tiến trình thực thi. Dựng 10 cảm biến chế độ thăm dò chờ tệp chưa tới. Quan sát không đỉnh nào khác chạy được. Đo số chỗ bị chiếm. Chuyển sang chế độ lên lịch lại, đo lại. Chuyển sang đỉnh hoãn lại, đo lại. Bỏ thời gian chờ tối đa và quan sát.",
"Dùng chế độ thăm dò cho cảm biến chờ lâu · bỏ thời gian chờ tối đa · dùng cảm biến khi hệ nguồn có thể kích hoạt trực tiếp.",
"Tái hiện được bế tắc tài nguyên, và hai bản sửa hạ số chỗ bị chiếm xuống dưới hai có số đo."),

(231,"Dynamic task mapping","TH","Lesson 230",
"Sinh số đỉnh phụ thuộc dữ liệu lúc chạy thay vì cố định lúc viết, giải bài toán nạp N tệp mà N chỉ biết khi chạy. Khác biệt then chốt với việc sinh đỉnh ở tầng ngoài tệp: cách đó chạy lúc phân tích nên dính bẫy ở lesson 226 và số đỉnh cố định cho tới lần phân tích sau; cách này chạy lúc thực thi nên số đỉnh phản ánh dữ liệu thật. Cách khai báo và giới hạn số đỉnh sinh ra, cùng lý do phải đặt giới hạn: một lỗi ở nguồn trả về 100.000 phần tử sẽ sinh 100.000 đỉnh và làm sập bộ lập lịch. Kết quả gộp từ các đỉnh sinh ra và cách xử lý khi một phần thất bại. Đánh đổi với việc để một đỉnh xử lý cả danh sách trong vòng lặp: nhiều đỉnh cho khả năng quan sát và thử lại riêng từng phần, một đỉnh cho chi phí điều phối thấp; ngưỡng chọn theo thời gian xử lý mỗi phần tử và tỉ lệ hỏng. Đây là cùng bài toán kích thước đỉnh ở lesson 220.",
"Chuyển một đỉnh xử lý danh sách trong vòng lặp sang sinh đỉnh động, và xác định ngưỡng mà cách nào rẻ hơn bằng thực nghiệm.",
"Tầng *đánh giá*. Objective đòi chọn giữa hai cách có đánh đổi hai chiều. Đạt khi có bảng thực nghiệm ít nhất bốn kích thước danh sách kèm tổng thời gian và thời gian phát hiện lỗi, và khi ngưỡng chọn ra được biện minh bằng cả hai chỉ số chứ bằng một.",
"Đỉnh nạp N tệp, chạy ở N bằng 5, 50, 500, 5.000. Cài cả hai cách. Đo tổng thời gian chạy và thời gian từ lúc một tệp hỏng tới lúc biết tệp nào. Đặt giới hạn số đỉnh sinh ra và thử vượt giới hạn. Cho một tệp hỏng và so cách chạy lại ở hai cách.",
"Sinh đỉnh ở tầng ngoài tệp bằng truy vấn · không đặt giới hạn số đỉnh sinh ra · chọn cách theo tổng thời gian mà bỏ thời gian phát hiện lỗi.",
"Bảng bốn kích thước danh sách có cả hai chỉ số, và ngưỡng chọn ra biện minh bằng cả hai."),

(232,"Retries, timeouts, SLA and alerting","TH","Lesson 231",
"Áp phân loại ở lesson 222 vào cấu hình thật. Thử lại đặt ở mức đỉnh với số lần khác nhau theo loại đỉnh. Khoảng chờ tăng dần và giới hạn trên. Thời gian chờ ở hai mức và lý do thiếu mức lần chạy làm một đồ thị treo chiếm chỗ mãi. Cam kết thời gian hoàn thành khác thời gian chờ tối đa ở chỗ nó không giết đỉnh mà chỉ báo trễ, một phân biệt hay bị nhầm. Cảnh báo phải nói ba thứ: cái gì hỏng, ảnh hưởng tới ai, bước đầu tiên nên làm, nối lại lesson 214. Mệt mỏi vì cảnh báo và hai cách chống: gom cảnh báo cùng nguyên nhân, và chỉ cảnh báo thứ người trực làm được gì đó. Hàm gọi khi thất bại và khi thử lại, dùng để gửi cảnh báo có ngữ cảnh thay vì thông báo mặc định. Phân biệt cảnh báo cho người trực với ghi nhận cho báo cáo. Đỉnh dọn dẹp chạy kể cả khi đỉnh trước thất bại, và quy tắc kích hoạt để làm việc đó.",
"Cấu hình thử lại, thời gian chờ và cảnh báo cho pipeline tham chiếu sao cho lỗi tạm thời tự phục hồi không sinh cảnh báo, còn lỗi xác định sinh cảnh báo đủ ba thứ.",
"Tầng *áp dụng*. Objective là cấu hình có tiêu chí đúng sai kiểm được bằng thực nghiệm. Kiểm bằng hai kịch bản bơm lỗi đối lập. Đạt khi kịch bản một chạy qua không cảnh báo, kịch bản hai sinh đúng một cảnh báo, và nội dung cảnh báo nêu được cả ba thứ.",
"Cấu hình đồ thị tham chiếu. Bơm lỗi mạng tự khỏi sau 20 giây, xác nhận tự phục hồi không cảnh báo. Bơm lỗi phép kiểm chất lượng không đạt, xác nhận đúng một cảnh báo. Viết hàm gọi khi thất bại để cảnh báo đủ ba thứ. Thêm đỉnh dọn dẹp chạy kể cả khi thất bại.",
"Đặt cùng số lần thử lại cho mọi đỉnh · nhầm cam kết thời gian với thời gian chờ tối đa · cảnh báo mọi thất bại kể cả thứ tự khỏi.",
"Lỗi tạm thời không sinh cảnh báo, lỗi xác định sinh đúng một cảnh báo nêu đủ ba thứ."),

(233,"Backfill and catchup at scale","TH","Lesson 232",
"Áp lesson 223 vào quy mô lớn hơn và vào đặc thù công cụ. Hai cách chạy bù: lệnh dòng lệnh và kích hoạt từ giao diện, cùng khác biệt về khả năng kiểm soát. Bắt kịp và ngày bắt đầu: đổi ngày bắt đầu của một đồ thị đang chạy gây hành vi khó đoán, nên quy tắc là tạo đồ thị mới thay vì đổi ngày bắt đầu. Chạy bù 90 ngày trên đồ thị 20 đỉnh sinh 1.800 lần chạy đỉnh, nên giới hạn song song và thứ tự ưu tiên quyết định nó mất bao lâu và có ảnh hưởng tải hằng ngày không. Tách nhóm tài nguyên cho chạy bù khỏi nhóm của sản xuất, nếu không thì chạy bù chiếm hết chỗ và công việc hằng ngày trễ. Theo dõi tiến độ và dừng giữa chừng sạch sẽ. Chạy bù một phần đồ thị bằng cách chọn tập đỉnh. Xoá trạng thái lần chạy cũ trước khi chạy lại và hậu quả nếu quên. Chạy bù khi logic đã đổi: quyết định có muốn kết quả theo logic mới không, nối lại lesson 210.",
"Chạy bù 90 ngày cho đồ thị tham chiếu dưới giới hạn tài nguyên tách khỏi sản xuất, và chứng minh công việc hằng ngày không bị trễ.",
"Tầng *áp dụng*. Objective có hai tiêu chí đồng thời, một về đúng đắn một về ảnh hưởng. Đạt khi kết quả 90 ngày khớp bản đối chứng, và khi thời gian hoàn thành công việc hằng ngày trong lúc chạy bù không vượt quá 20% so với mức nền.",
"Sinh bản đối chứng 90 ngày. Chạy bù với nhóm tài nguyên chung với sản xuất, đo độ trễ công việc hằng ngày. Tách nhóm tài nguyên riêng, chạy lại, đo lại. Đối chiếu kết quả. Dừng giữa chừng một lần và tiếp tục, xác nhận không trùng lặp.",
"Chạy bù dùng chung nhóm tài nguyên với sản xuất · đổi ngày bắt đầu của đồ thị đang chạy · quên xoá trạng thái lần chạy cũ trước khi chạy lại.",
"Kết quả 90 ngày khớp bản đối chứng, và công việc hằng ngày không trễ quá 20% so với mức nền."),

(234,"Pools, priority weight and concurrency at three levels","TH","Lesson 233",
"Ba tầng giới hạn song song và phạm vi của từng tầng, nối lại lesson 223. Nhóm tài nguyên là cơ chế duy nhất trong ba cái biểu diễn được ràng buộc dùng chung giữa nhiều đồ thị, nên đây là chỗ khai báo số kết nối mà cơ sở dữ liệu chịu được, lấy từ số đo ở lesson 134. Trọng số ưu tiên quyết định đỉnh nào lấy chỗ trước khi nhóm đầy, và cách dùng nó để đồ thị quan trọng không bị đồ thị chạy bù chặn. Hai triệu chứng của thiếu giới hạn: hệ đích báo hết kết nối, và truy vấn xếp hàng làm mọi thứ chậm đều chứ không hỏng hẳn, cái sau khó chẩn đoán hơn. Tìm số song song phù hợp bằng thực nghiệm thay vì đoán, cùng phương pháp lesson 134. Giới hạn ở mức đỉnh để một đỉnh không chạy quá nhiều lần chạy đồng thời. Cô lập tài nguyên giữa môi trường. Chi phí ở hệ đích tính tiền theo lượng quét: tăng song song không phải lúc nào cũng giảm tổng thời gian nhưng gần như luôn tăng tiền, nối lại lesson 160.",
"Tìm mức song song phù hợp bằng thực nghiệm và chứng minh cấu hình chọn ra không làm hệ đích hết kết nối khi chạy bù đồng thời với lần chạy hằng ngày.",
"Tầng *đánh giá*. Objective đòi chọn một giá trị và biện minh bằng đánh đổi giữa thời gian với chi phí. Đạt khi có bảng thực nghiệm ít nhất bốn mức song song kèm ba số đo mỗi mức, và khi kịch bản kiểm chứng chạy đồng thời không sinh lỗi hết kết nối.",
"Chạy đồ thị tham chiếu ở bốn mức song song. Mỗi mức đo tổng thời gian, số kết nối cao nhất tới hệ đích, và chi phí hoặc lượng dữ liệu quét. Chọn một mức, khai báo nhóm tài nguyên. Chạy bù đồng thời với lần chạy hằng ngày và xác nhận không lỗi. Đặt trọng số ưu tiên và kiểm thứ tự lấy chỗ.",
"Đặt giới hạn ở mức đồ thị rồi tưởng đã chặn ràng buộc dùng chung · tăng song song tới khi nhanh nhất mà không nhìn chi phí · để chạy bù dùng chung nhóm với sản xuất.",
"Bảng bốn mức song song có đủ ba số đo, và chạy bù đồng thời với hằng ngày không sinh lỗi hết kết nối."),

(235,"Executors - Local, Celery, Kubernetes - and choosing between them","TH","Lesson 234",
"Bộ thực thi quyết định đỉnh chạy ở đâu, và ba lựa chọn có đặc tính vận hành khác hẳn nhau. Bộ thực thi cục bộ chạy đỉnh trên cùng máy với bộ lập lịch: đơn giản nhất, không có thành phần thêm, nhưng không mở rộng và một đỉnh nặng làm chậm bộ lập lịch. Bộ thực thi phân tán qua hàng đợi chạy đỉnh trên nhiều tiến trình thực thi thường trực: mở rộng được, chi phí khởi động thấp, nhưng thêm hàng đợi và các tiến trình thực thi phải vận hành, và mọi tiến trình thực thi phải có cùng phụ thuộc. Bộ thực thi trên cụm vùng chứa tạo một vùng chứa cho mỗi đỉnh: cô lập phụ thuộc hoàn toàn và tự co giãn, nhưng chi phí khởi động mỗi đỉnh vài giây tới vài chục giây nên đồ thị nhiều đỉnh ngắn trở nên rất chậm. Bốn tiêu chí chọn: số đỉnh mỗi ngày, thời gian chạy trung bình một đỉnh, mức độ khác nhau về phụ thuộc giữa các đỉnh, và năng lực vận hành của đội. Chi phí khởi động là yếu tố bị bỏ qua nhiều nhất.",
"Chọn bộ thực thi cho ba tình huống khác nhau và chứng minh bằng số đo chi phí khởi động cùng thông lượng.",
"Tầng *đánh giá*. Objective đòi chọn giữa ba phương án theo bốn tiêu chí. Đạt khi có số đo chi phí khởi động và thông lượng cho ít nhất hai bộ thực thi, và khi ba lựa chọn đều dẫn được về số đo cộng năng lực vận hành chứ bằng danh tiếng công cụ.",
"Chạy cùng đồ thị tham chiếu trên bộ thực thi cục bộ và bộ thực thi phân tán. Đo chi phí khởi động một đỉnh và tổng thông lượng. Nếu có cụm vùng chứa thì đo thêm, nếu không thì ước lượng từ tài liệu và ghi rõ chưa đo. Ba tình huống: 50 đỉnh mỗi ngày mỗi đỉnh 10 giây, 5.000 đỉnh mỗi ngày mỗi đỉnh 30 phút, và các đỉnh cần thư viện xung đột nhau.",
"Chọn bộ thực thi trên cụm vùng chứa cho đồ thị nhiều đỉnh ngắn · dùng bộ thực thi cục bộ cho sản xuất · bỏ qua yêu cầu mọi tiến trình thực thi có cùng phụ thuộc.",
"Có số đo chi phí khởi động và thông lượng cho ít nhất hai bộ thực thi, và ba lựa chọn dẫn được về số đo."),

(236,"Operating Airflow - deployment, upgrade, diagnosing a stuck scheduler","TH","Lesson 235",
"Không có cơ chế mới. Bài gộp module, và nó đo đúng thứ phân biệt mức `A` với mức `B`: chẩn đoán được khi cụm hỏng. Bốn sự cố vận hành thường gặp và quy trình chẩn đoán cho từng cái. Bộ lập lịch đứng: kiểm thời gian phân tích tệp ở lesson 226, kiểm cơ sở dữ liệu siêu dữ liệu chậm, kiểm bế tắc cảm biến ở lesson 230, theo thứ tự đó. Đỉnh kẹt ở đã xếp hàng: kiểm chỗ tiến trình thực thi, nhóm tài nguyên, và trạng thái tiến trình thực thi. Cơ sở dữ liệu siêu dữ liệu phình: dọn bảng lịch sử và bảng truyền giá trị, áp kiến thức M11 về phình bảng. Giao diện chậm: thường là hệ quả của cái thứ ba. Nâng cấp phiên bản: di trú lược đồ cơ sở dữ liệu siêu dữ liệu, kiểm tương thích của mã đồ thị, và quy trình quay lui. Triển khai mã đồ thị: đồng bộ tệp tới mọi thành phần và cửa sổ không nhất quán giữa chúng. Sao lưu cơ sở dữ liệu siêu dữ liệu và thứ mất khi mất nó.",
"Chẩn đoán ba sự cố cụm chưa từng thấy về đúng nguyên nhân theo quy trình, và thực hiện một lần nâng cấp phiên bản có quay lui được.",
"Tầng *đánh giá*. Objective đòi chẩn đoán dưới thời gian và một thao tác vận hành rủi ro. Chấm theo năm mục: chẩn đoán ba sự cố 45đ, nâng cấp thành công 20đ, quay lui được 15đ, sổ tay xử lý 10đ, và sao lưu cơ sở dữ liệu siêu dữ liệu 10đ. Đạt khi ≥ 70/100 và mục chẩn đoán ≥ 60%.",
"Cụm Airflow có tải. Giám khảo gây ba sự cố không báo trước. Chẩn đoán theo quy trình, ghi số đo trước khi sửa. Nâng cấp một phiên bản phụ, có di trú lược đồ. Quay lui về phiên bản cũ. Nộp sổ tay xử lý cho bốn sự cố theo khuôn lesson 90.",
"Khởi động lại cụm khi gặp sự cố thay vì chẩn đoán · nâng cấp mà không sao lưu cơ sở dữ liệu siêu dữ liệu · triển khai mã đồ thị tới bộ lập lịch mà quên các tiến trình thực thi.",
"Đạt ≥ 70/100 và mục chẩn đoán ≥ 60%, với sổ tay xử lý đủ bốn sự cố."),
]
