# -*- coding: utf-8 -*-
"""DE M31 Change data capture with Debezium + M32 Stream processing."""

M31 = ("Change Data Capture with Debezium", 309, 316, """| | |
|---|---|
| **Objective cấp module** | Thay một tuyến nạp gia tăng theo lô bằng CDC đọc nhật ký, và chứng minh tuyến mới bắt được cả ba thứ mà bản cũ bỏ sót |
| **Tiền đề** | M29 |
| **Exit criterion** | Tuyến CDC chạy qua một lần chụp đầu, một đợt thay đổi lược đồ nguồn và một lần khởi động lại, đối soát khớp tuyệt đối với bảng nguồn |
| **Kỹ năng SFIA** | `DBAD` mức 3 · `DTAN` mức 3 |
| **Chế độ hỏng** | Bật trình nối rồi coi là xong, không theo dõi khe sao chép, tới khi đĩa cơ sở dữ liệu nguồn đầy thì cả hệ sản xuất dừng |""",
"""Mức `B` theo quy ước ở mục 2. Module đứng sau M29 vì Debezium ghi ra Kafka và dùng trực tiếp chủ đề nén theo khoá ở lesson 296 làm bảng thay đổi.

Đây là lần thứ hai chương trình quay lại bài toán nạp gia tăng. Lần đầu ở lesson 204 và 205 giải bằng cột mốc và truy vấn định kỳ; module này giải bằng nhật ký giao dịch, và phần lớn giá trị nằm ở chỗ so hai cách trên cùng một nguồn chứ ở chỗ cài đặt công cụ.""")

L31 = [
(309,"Why CDC exists - the cost of polling and the rows it misses","LT","Module 31: M29",
"Truy vấn định kỳ theo cột mốc ở lesson 205 bỏ sót ba thứ, và cả ba đều im lặng. Một là bản ghi bị xoá: không còn dòng nào để truy vấn thấy, nên đích giữ lại bản ghi đã chết mãi mãi trừ khi có cờ xoá mềm. Hai là thay đổi trung gian: một đơn đổi trạng thái ba lần giữa hai lần quét thì đích chỉ thấy trạng thái cuối, và mọi phân tích về thời gian ở mỗi trạng thái đều sai. Ba là bản ghi cập nhật mà không đụng cột mốc, thường do sửa tay hoặc do một đường ghi khác quên cập nhật trường thời gian. Chi phí của truy vấn định kỳ cũng đáng kể: mỗi lần quét là một lần đọc trên cơ sở dữ liệu đang phục vụ sản xuất, và quét càng dày thì tải càng nặng, nên có một trần thực tế cho độ tươi. CDC đọc nhật ký giao dịch thay vì đọc bảng, nên thấy đủ ba thứ trên và gần như không thêm tải đọc. Cái giá: phụ thuộc vào cấu hình nội bộ của cơ sở dữ liệu nguồn, cần quyền cao, và thêm một hệ phải trực.",
"Chỉ ra trong một tuyến nạp theo cột mốc cho trước những bản ghi nào bị bỏ sót, và định lượng mức sai lệch bằng số đếm trên dữ liệu thật.",
"Tầng *phân tích*. Người học đã tự xây tuyến gia tăng ở M20 nên có hệ để soi lại; objective là tìm ra chỗ hỏng của chính công trình cũ chứ tiếp nhận một khẳng định. Kiểm bằng phép đếm đối chứng; đạt khi định lượng đúng cả ba loại bỏ sót.",
"Trên tuyến gia tăng đã dựng ở lesson 217, chạy một kịch bản gồm xoá 50 bản ghi, đổi trạng thái 200 đơn ba lần trong một chu kỳ quét, và cập nhật 30 bản ghi mà không đụng cột mốc. Sau một chu kỳ, đối soát đích với nguồn và đếm chính xác từng loại sai lệch.",
"Kết luận truy vấn định kỳ luôn tệ hơn mà không xét tải và độ phức tạp · dùng xoá mềm rồi tưởng đã giải xong bài toán xoá · quét dày hơn để chữa mà không đo tải lên nguồn.",
"Đếm đúng cả ba loại bỏ sót với số khớp kịch bản đã tiêm, và nêu được mức tải thêm khi tăng tần suất quét."),

(310,"Reading the database log - logical decoding and the replication slot","LT","Lesson 309",
"CDC đọc chính cái nhật ký mà cơ sở dữ liệu vốn đã ghi để phục hồi sau sự cố ở lesson 118 và để sao chép sang bản sao ở lesson 120. Giải mã logic biến các bản ghi nhật ký ở dạng vật lý thành sự kiện có nghĩa: bảng nào, thao tác gì, giá trị trước và sau. Khe sao chép là con trỏ phía máy chủ ghi nhớ bên đọc đã tiêu thụ tới đâu, và **đây là chi tiết nguy hiểm nhất của cả module**: máy chủ không được xoá nhật ký mà khe chưa đọc tới, nên bên đọc dừng mà khe còn đó thì nhật ký dồn lại cho tới khi đầy đĩa và cơ sở dữ liệu sản xuất ngừng nhận ghi. Hai loại khe và khác biệt khi khởi động lại. Danh tính bản ghi quyết định sự kiện xoá và cập nhật mang theo bao nhiêu thông tin: mặc định chỉ có khoá chính, đặt đầy đủ thì có toàn bộ giá trị trước nhưng nhật ký phình. Mỗi hệ một cơ chế: MySQL dùng nhật ký nhị phân theo dòng, MongoDB dùng luồng thay đổi, và cả ba đã gặp ở M11 tới M13.",
"Giải thích đường đi từ một lệnh cập nhật tới một sự kiện thay đổi, gọi đúng tên nhật ký, giải mã logic và khe, và nêu điều gì xảy ra khi bên đọc dừng.",
"Tầng *hiểu*. Bài lý thuyết nối kiến thức nội bộ cơ sở dữ liệu đã có với một cơ chế mới, chưa đòi vận hành. Kiểm bằng bài giải thích cộng một thí nghiệm quan sát; đạt khi mô tả đúng đường đi và dự đoán đúng hậu quả của việc dừng bên đọc.",
"Bật giải mã logic trên PostgreSQL, tạo một khe, dùng công cụ dòng lệnh đọc trực tiếp sự kiện thô. Chạy chèn, cập nhật, xoá và đọc ra ba loại sự kiện. Đổi danh tính bản ghi và quan sát sự kiện xoá đổi nội dung ra sao. Dừng bên đọc 10 phút trong lúc có tải ghi và đo kích thước nhật ký dồn lại.",
"Tạo khe rồi quên, để nó giữ nhật ký vô hạn · tưởng CDC không đụng gì tới nguồn · dùng danh tính bản ghi mặc định rồi không có giá trị trước để đối soát.",
"Mô tả đúng ba thành phần trên đường đi, và số đo kích thước nhật ký dồn lại sau 10 phút dừng khớp với dự đoán về hướng tăng."),

(311,"Debezium architecture - connector, offset and the change event envelope","TH","Lesson 310",
"Debezium là một trình nối nguồn chạy trên Kafka Connect ở lesson 302, nên mọi thứ đã học về chế độ phân tán, cấu hình và thư chết áp dụng nguyên vẹn. Nó giữ hai loại vị trí và trộn lẫn hai loại này là nguồn lỗi hay gặp: offset của trình nối ghi vị trí đã đọc tới trong nhật ký nguồn, còn offset của bên tiêu thụ ở lesson 295 là chuyện phía sau, hoàn toàn độc lập. Phong bì sự kiện thay đổi có cấu trúc cố định gồm trạng thái trước, trạng thái sau, siêu dữ liệu nguồn và loại thao tác. Bốn loại thao tác và ý nghĩa của trường trước trong từng loại: chèn thì trước rỗng, cập nhật thì có cả hai, xoá thì sau rỗng, đọc là loại riêng chỉ xuất hiện trong lần chụp đầu. Siêu dữ liệu nguồn mang số thứ tự trong nhật ký và dấu thời gian giao dịch, và đây là thứ dùng để sắp lại đúng thứ tự khi cần. Quy ước đặt tên chủ đề: mỗi bảng một chủ đề, khoá chính làm khoá bản ghi, nên thứ tự trong một hàng được bảo đảm theo đúng lập luận ở lesson 279.",
"Đọc được một sự kiện thay đổi thô và nói đúng thao tác gì xảy ra trên hàng nào, dùng trường trước và sau để chứng minh.",
"Tầng *áp dụng*. Bài thực hành đầu của module, đòi dùng đúng cấu trúc dữ liệu chứ thiết kế mới. Kiểm bằng bài đọc sự kiện có đáp án; đạt khi giải mã đúng ít nhất 9/10 sự kiện và giải thích được vì sao khoá chủ đề là khoá chính.",
"Dựng Debezium trên Kafka Connect đọc bảng đơn hàng. Sinh 10 thao tác hỗn hợp trên nguồn, bắt 10 sự kiện tương ứng, và với mỗi sự kiện viết ra thao tác gì trên hàng nào, dẫn bằng trường trước và sau. Đổi khoá chủ đề sang ngẫu nhiên và chứng minh thứ tự trong một hàng không còn được bảo đảm.",
"Nhầm offset trình nối với offset bên tiêu thụ · bỏ qua trường thao tác nên xử lý sự kiện xoá như cập nhật · đặt khoá bản ghi khác khoá chính rồi mất thứ tự trong hàng.",
"Giải mã đúng ≥ 9/10 sự kiện, và chứng minh được bằng thực nghiệm rằng đổi khoá làm mất thứ tự trong hàng."),

(312,"Snapshot and the handover to streaming","TH","Lesson 311",
"Nhật ký giao dịch chỉ giữ một khoảng gần đây, nên CDC không thể dựng lại lịch sử từ đầu; phải chụp trạng thái hiện tại trước rồi mới chuyển sang đọc liên tục. Chỗ khó nằm ở mối nối giữa hai giai đoạn: chụp mất nhiều giờ trên bảng lớn, và trong lúc đó nguồn vẫn đang thay đổi, nên nếu mối nối sai thì hoặc mất thay đổi xảy ra giữa chừng hoặc nhân đôi chúng. Bốn chế độ chụp và tình huống dùng: chụp rồi chuyển sang luồng, chỉ chụp, chỉ luồng khi đích đã có sẵn dữ liệu, và chụp gia tăng theo lô nhỏ để không khoá bảng lâu. Tác động lên nguồn khi chụp: đọc nặng, và ở một số cấu hình có khoá đọc, nên phải chọn cửa sổ thời gian. Chụp gia tăng giải quyết bằng cách chia bảng thành cửa sổ khoá chính và xen kẽ với luồng, đổi lại logic phức tạp hơn. Vì sao khử trùng theo khoá nghiệp vụ ở lesson 208 vẫn cần: mối nối có thể phát lại một đoạn, và đích phải chịu được điều đó.",
"Chạy được một lần chụp trên bảng đang có ghi và chứng minh bằng đối soát rằng không thay đổi nào bị mất hay nhân đôi ở mối nối.",
"Tầng *áp dụng*. Objective là một thao tác vận hành có kết quả kiểm được bằng đối soát, đúng phương pháp của lesson 212. Kiểm bằng đối soát số dòng và tổng tiền sau khi chụp xong; đạt khi khớp tuyệt đối trong khi nguồn vẫn có ghi.",
"Chạy chụp trên bảng 2 triệu dòng trong lúc một tiến trình khác liên tục chèn và cập nhật. Sau khi chuyển sang luồng, đối soát đích với nguồn theo số dòng và tổng tiền. Đo thời gian chụp và tải thêm trên nguồn. Chạy lại bằng chế độ chụp gia tăng và so hai cột số.",
"Chụp trong giờ cao điểm rồi làm chậm hệ sản xuất · dừng ghi ở nguồn để chụp cho an toàn · đối soát bằng số dòng mà quên tổng tiền · tin rằng mối nối luôn đúng nên không đối soát.",
"Đối soát khớp tuyệt đối cả số dòng lẫn tổng tiền khi nguồn vẫn đang ghi, và có bảng so thời gian cùng tải giữa hai chế độ chụp."),

(313,"Schema change at the source and what reaches the consumer","TH","Lesson 312",
"Thay đổi lược đồ ở nguồn đi thẳng vào sự kiện thay đổi, nên CDC là đường truyền rủi ro lược đồ nhanh nhất trong cả hệ: đội nguồn thêm cột lúc 10 giờ thì 10 giờ 01 đích đã nhận cấu trúc mới. Ba loại thay đổi và hành vi tương ứng: thêm cột thì sự kiện có thêm trường và bên tiêu thụ cũ bỏ qua được nếu lược đồ tương thích ngược ở lesson 299; đổi kiểu thì có thể phá vỡ và sổ đăng ký chặn; xoá cột thì bên tiêu thụ còn dùng cột đó sẽ hỏng. Debezium phát sự kiện thay đổi lược đồ vào một chủ đề riêng, và đây là chỗ nối CDC với hợp đồng dữ liệu ở M26: hợp đồng nói đội nguồn phải báo trước, sổ đăng ký cưỡng chế bằng máy, còn chủ đề lược đồ cho đích biết chuyện đã xảy ra. Ba cách xử lý khi nguồn đổi kiểu, theo đúng ba chiến lược đã đặt ở lesson 209 cho biên nạp theo lô: bỏ qua, tự thêm, hoặc dừng và báo.",
"Thực hiện được ba loại thay đổi lược đồ ở nguồn và mô tả chính xác cái gì tới được bên tiêu thụ trong từng loại.",
"Tầng *phân tích*. Bài đòi truy hậu quả từ một thay đổi ở đầu này sang biểu hiện ở đầu kia, xuyên qua ba thành phần. Kiểm bằng ba thí nghiệm có dự đoán viết trước; đạt khi cả ba dự đoán khớp quan sát, hoặc chênh thì giải thích được nguyên nhân.",
"Với tuyến CDC đang chạy và bên tiêu thụ đang ghi mart, viết dự đoán trước rồi thực hiện lần lượt: thêm một cột có mặc định, đổi kiểu một cột, xoá một cột đang được mart dùng. Với mỗi lần, ghi lại sự kiện lược đồ, hành vi của sổ đăng ký, và trạng thái bên tiêu thụ. Cấu hình lại theo chiến lược dừng và báo rồi lặp lại thí nghiệm xoá cột.",
"Không bật sổ đăng ký nên thay đổi phá vỡ đi thẳng tới đích · bỏ qua chủ đề lược đồ · coi CDC là lý do không cần hợp đồng dữ liệu nữa.",
"Ba dự đoán khớp quan sát hoặc chênh có giải thích, và sau khi đổi chiến lược thì xoá cột làm tuyến dừng có cảnh báo thay vì ghi dữ liệu sai."),

(314,"Compacted topics as a changelog and rebuilding current state","TH","Lesson 313",
"Chủ đề nén theo khoá ở lesson 296 và luồng CDC khớp nhau đúng một cách: khoá là khoá chính, giá trị là trạng thái sau, nên chủ đề nén trở thành ảnh chụp trạng thái hiện hành dựng lại được bất cứ lúc nào. Sự kiện xoá phát ra bản ghi giá trị rỗng để nén loại bỏ hẳn khoá đó. Hai cách dùng luồng thay đổi ở đích, và chọn sai là sai kiến trúc chứ sai cấu hình: dựng bảng trạng thái hiện hành bằng cách gộp theo khoá lấy bản mới nhất, hoặc giữ toàn bộ lịch sử thay đổi để dựng bảng chiều biến đổi chậm loại 2 đúng như cơ chế ở lesson 195. Luồng CDC là nguồn tự nhiên nhất cho loại 2 vì nó có đủ mốc thời gian của từng lần đổi, thứ mà nạp theo lô hằng ngày không bao giờ có. Điều kiện để dựng lại được: bên ghi phải bất biến theo lesson 106, và thứ tự trong một khoá phải được giữ theo lesson 279.",
"Dựng được cả bảng trạng thái hiện hành lẫn bảng lịch sử loại 2 từ cùng một luồng CDC, và dựng lại được trạng thái sau khi xoá sạch đích.",
"Tầng *sáng tạo*. Bài đòi ghép nén theo khoá, mô hình chiều và tính bất biến thành một thiết kế, chứ chạy một tính năng. Kiểm bằng việc xoá sạch bảng đích rồi dựng lại từ chủ đề; đạt khi bảng dựng lại khớp tuyệt đối với bản trước khi xoá.",
"Cấu hình chủ đề CDC nén theo khoá. Dựng hai đích từ cùng luồng: bảng trạng thái hiện hành và bảng loại 2 có cột hiệu lực từ và đến. Sinh một chuỗi thay đổi có cả xoá. Xoá sạch cả hai bảng đích rồi dựng lại hoàn toàn từ chủ đề và đối soát với bản đã lưu trước đó.",
"Nén theo khoá trên chủ đề cần giữ lịch sử nên mất các bước trung gian · quên bản ghi rỗng nên bản ghi đã xoá sống lại khi dựng lại · dựng loại 2 mà không bất biến nên chạy lại sinh trùng dòng.",
"Cả hai bảng dựng lại từ chủ đề khớp tuyệt đối với bản trước khi xoá, kể cả các khoá đã bị xoá ở nguồn."),

(315,"Operating CDC - slot growth, lag and the failure that fills the disk","TH","Lesson 314",
"Chế độ hỏng nguy hiểm nhất của module, và nó đánh vào cơ sở dữ liệu sản xuất chứ vào hệ phân tích: bên đọc dừng, khe sao chép giữ nhật ký, nhật ký dồn, đĩa đầy, nguồn ngừng nhận ghi. Ba chỉ số phải theo dõi liên tục, và chỉ số đầu là chỉ số cảnh báo sớm duy nhất: dung lượng nhật ký mà khe đang giữ, độ trễ của trình nối tính bằng thời gian, và độ trễ tiêu thụ phía sau theo lesson 300. Ngưỡng nên đặt theo tốc độ tăng chứ theo giá trị tuyệt đối, cùng lập luận đã dùng ở lesson 300. Bốn nguyên nhân làm khe phình và cách phân biệt: trình nối chết, trình nối chạy nhưng chậm hơn tốc độ ghi, Kafka không nhận được nên trình nối chặn, và một giao dịch dài ở nguồn giữ nhật ký. Quy trình xử lý khẩn khi đĩa sắp đầy, và câu hỏi khó phải quyết trong vài phút: xoá khe để cứu nguồn và chấp nhận phải chụp lại từ đầu, hay cố cứu trình nối. Sổ tay xử lý viết theo chuẩn M26, có ngưỡng và có người chịu trách nhiệm.",
"Chẩn đoán một khe đang phình về đúng một trong bốn nguyên nhân bằng số đo, và thực hiện đúng quy trình khẩn khi đĩa nguồn sắp đầy.",
"Tầng *phân tích*. Bài vận hành có rủi ro thật lên hệ sản xuất, nên objective là chẩn đoán dưới áp lực thời gian. Kiểm bằng ba sự cố tiêm sẵn tính giờ; đạt khi chẩn đoán đúng ít nhất hai và quyết định khẩn có lập luận về đánh đổi.",
"Dựng theo dõi ba chỉ số với cảnh báo theo tốc độ tăng. Giảng viên tiêm ba tình huống làm khe phình, mỗi lần 10 phút. Với mỗi lần, ghi ba chỉ số, nêu nguyên nhân, xử lý. Ở tình huống cuối, đĩa mô phỏng còn 5%: viết quyết định và lập luận đánh đổi trong 3 phút.",
"Chỉ theo dõi độ trễ mà bỏ dung lượng khe · đặt ngưỡng tuyệt đối · xoá khe theo phản xạ mà không tính chi phí chụp lại · để khe của môi trường thử trỏ vào nguồn sản xuất rồi quên.",
"Chẩn đoán đúng ≥ 2/3 tình huống kèm số đo, và quyết định khẩn nêu được cả hai phía của đánh đổi kèm chi phí ước lượng."),

(316,"CDC into the reference pipeline - replacing an incremental batch load","TH","Lesson 315",
"Bài khép module: thay tuyến nạp gia tăng theo cột mốc đã dựng ở lesson 217 bằng tuyến CDC, rồi chạy song song hai tuyến trên cùng nguồn để so. Bốn đại lượng phải đo trên cả hai tuyến: độ tươi tính từ lúc thay đổi xảy ra ở nguồn tới lúc thấy ở mart, tải thêm trên cơ sở dữ liệu nguồn, số bản ghi sai lệch theo ba loại ở lesson 309, và công sức vận hành tính bằng số thành phần cùng số chỉ số phải theo dõi. Chạy song song là bắt buộc chứ tuỳ chọn: chuyển thẳng rồi mới so là cách mất khả năng đối chứng. Kết luận phải nêu cả chiều ngược: CDC không phải lựa chọn đúng cho mọi nguồn, và ba tình huống nên giữ nạp theo lô gồm nguồn không cho bật giải mã logic, khối lượng thay đổi rất nhỏ, và đội không đủ người trực. Bằng chứng ghi lại theo chuẩn đã dùng ở lesson 290 và 304 để về sau đưa vào hồ sơ quyết định kiến trúc.",
"Chạy song song hai tuyến trên cùng nguồn, đo bốn đại lượng, và đưa ra khuyến nghị kèm điều kiện làm khuyến nghị đó sai.",
"Tầng *đánh giá*. Bài tổng hợp module thành một quyết định có bằng chứng, chuẩn bị cho hồ sơ kiến trúc ở M39. Kiểm bằng bảng bốn đại lượng hai cột cộng phần điều kiện đảo ngược; đạt khi mỗi ô có số và nêu được ít nhất hai điều kiện đảo ngược cụ thể.",
"Chạy song song tuyến CDC và tuyến theo cột mốc trên cùng nguồn trong 24 giờ có tải mô phỏng. Đo bốn đại lượng. Lập bảng hai cột. Viết khuyến nghị cho một đội cho trước kèm hai điều kiện làm khuyến nghị sai, và nêu tuyến nào trong ba tình huống ở phần Learn nên giữ nạp theo lô.",
"Chuyển thẳng sang CDC rồi bỏ tuyến cũ nên không còn đối chứng · đo độ tươi mà quên tải lên nguồn · khuyến nghị CDC cho mọi trường hợp · ghi số mà không ghi cách đo.",
"Bảng bốn đại lượng hai cột đủ số kèm cách đo, và khuyến nghị có ít nhất hai điều kiện đảo ngược cụ thể."),
]

M32 = ("Stream Processing", 317, 328, """| | |
|---|---|
| **Objective cấp module** | Viết một công việc xử lý luồng có trạng thái, đúng theo thời gian sự kiện, phục hồi được sau sự cố, và chứng minh tính đúng bằng thí nghiệm hỏng |
| **Tiền đề** | M29 · M31 |
| **Exit criterion** | Công việc chạy đúng dưới dữ liệu tới muộn, tới sai thứ tự và một lần giết tiến trình, kết quả khớp với bản tính theo lô trên cùng dữ liệu |
| **Kỹ năng SFIA** | `PROG` mức 4 · `HPCC` mức 3 |
| **Chế độ hỏng** | Viết công việc theo thời gian xử lý vì nó chạy được ngay, rồi kết quả đổi mỗi lần chạy lại và không ai đối soát được |""",
"""Module dạy **ngữ nghĩa xử lý luồng trước, engine sau**. Bốn khái niệm quyết định tính đúng là thời gian sự kiện, dấu nước, trạng thái và điểm kiểm tra; chúng giống nhau giữa các engine, còn cú pháp thì không. Flink là phương tiện cụ thể ở mức `B` vì nó là engine luồng thuần nên mọi khái niệm lộ ra trực tiếp.

**Ghi chú về thứ tự trong bản đồ.** Bản đồ đặt Spark Structured Streaming ở module này, nhưng Spark chỉ được dạy ở M34, tức sau đây 15 bài. Nên lesson 327 chỉ đối chiếu mô hình lô vi mô ở mức khái niệm và trỏ tới M34 cho phần nội bộ Spark. Nếu muốn dạy Structured Streaming đầy đủ ở đây thì phải đảo M34 lên trước M32.

Ràng buộc kế thừa từ lesson 282: broker vận chuyển, module này biến đổi. Mọi logic nghiệp vụ nhét vào bên tiêu thụ ở M29 lẽ ra thuộc về đây.""")

L32 = [
(317,"Event time against processing time, and why order is not guaranteed","LT","Module 32: M29 · M31",
"Ba mốc thời gian gắn với một sự kiện và ba mốc này gần như không bao giờ trùng: thời điểm việc xảy ra ngoài đời, thời điểm sự kiện được ghi, và thời điểm engine xử lý nó. Vấn đề đã được báo trước ở lesson 279: thứ tự trong hàng đợi là thứ tự tới, không phải thứ tự xảy ra. Bốn nguyên nhân làm sự kiện tới muộn hoặc sai thứ tự, và cả bốn đều bình thường chứ bất thường: thiết bị di động mất mạng rồi gửi bù, phân vùng khác nhau xử lý với tốc độ khác nhau, thử lại theo lesson 278 đẩy một sự kiện ra sau, và đồng hồ giữa các máy lệch nhau. Hệ quả: một công việc tính doanh thu theo giờ mà dùng thời gian xử lý sẽ cho kết quả **khác nhau mỗi lần chạy lại**, nên không đối soát được và không chạy bù được, mất luôn hai tính chất đã đặt làm bắt buộc ở lesson 222. Dùng thời gian sự kiện thì kết quả tái lập được, đổi lại phải quyết định chờ bao lâu, và đó là nội dung lesson 318.",
"Chỉ ra trong một công việc cho trước chỗ nào dùng thời gian xử lý, và dự đoán kết quả sai lệch ra sao khi chạy lại trên cùng dữ liệu.",
"Tầng *phân tích*. Bài mở module, người học đã có kinh nghiệm chạy bù và tính bất biến từ M21, nên đủ nền để thấy vì sao thời gian xử lý phá cả hai. Kiểm bằng ba công việc mẫu; đạt khi định vị đúng cả ba và dự đoán đúng hướng sai lệch.",
"Chạy một công việc gộp theo cửa sổ giờ dùng thời gian xử lý, trên một tập dữ liệu có 5% sự kiện tới muộn. Chạy ba lần với tốc độ nạp khác nhau và so ba kết quả. Sau đó chạy bản dùng thời gian sự kiện và so lại. Lập bảng chênh lệch theo từng cửa sổ giờ.",
"Cho rằng dữ liệu của mình không tới muộn vì chưa từng đo · dùng thời gian xử lý vì nó chạy được ngay · so hai kết quả bằng tổng mà không so theo từng cửa sổ.",
"Ba lần chạy theo thời gian xử lý cho ba kết quả khác nhau có số chứng minh, bản theo thời gian sự kiện cho cùng kết quả qua ba lần."),

(318,"Watermarks - bounding lateness and choosing the delay","LT","Lesson 317",
"Dùng thời gian sự kiện đặt ra một câu hỏi không có lời giải hoàn hảo: đóng cửa sổ 9 giờ lúc nào, khi luôn có khả năng một sự kiện 9 giờ còn chưa tới. Dấu nước là lời hứa của engine rằng sẽ không còn sự kiện nào cũ hơn mốc này, và nó chỉ là một **ước lượng có chủ ý sai lệch về phía an toàn**. Chọn độ trễ cho phép là chọn một điểm trên đường đánh đổi giữa độ tươi và độ đầy đủ: chờ ngắn thì kết quả ra sớm nhưng thiếu, chờ dài thì đầy đủ nhưng chậm, và không có giá trị đúng phổ quát. Cách chọn có căn cứ thay vì đoán: đo phân bố độ trễ thật của luồng, lấy một phân vị cao làm độ trễ cho phép, rồi định lượng phần trăm sự kiện bị bỏ lại ở mức đó. Dấu nước trong hệ có nhiều phân vùng lấy theo phân vùng chậm nhất, nên một phân vùng không có dữ liệu làm dấu nước đứng yên và cửa sổ không bao giờ đóng, đây là chế độ hỏng tĩnh lặng phổ biến nhất của xử lý luồng.",
"Chọn độ trễ cho phép từ phân bố độ trễ đo được của chính luồng, và định lượng phần trăm sự kiện bị bỏ lại ở mức đã chọn.",
"Tầng *đánh giá*. Objective là chọn một điểm trên đường đánh đổi dựa trên dữ liệu tự đo, cùng phương pháp đã dùng cho prefetch ở lesson 285. Kiểm bằng biểu đồ phân bố cộng bảng ba mức; đạt khi có phân bố thật, có điểm chọn và có con số bị bỏ lại.",
"Đo phân bố độ trễ trên luồng CDC ở lesson 316 và vẽ biểu đồ. Chạy cùng công việc ở ba mức độ trễ cho phép, với mỗi mức ghi độ tươi kết quả và phần trăm sự kiện bị bỏ. Tạo một phân vùng không có dữ liệu và quan sát dấu nước đứng yên, ghi lại triệu chứng.",
"Đặt độ trễ cho phép bằng một con số tròn · lấy phân vị 99 rồi mất hết tính kịp thời · không xử lý phân vùng rỗng nên cửa sổ treo vô hạn · kết luận về độ trễ mà chưa đo phân bố.",
"Biểu đồ phân bố dựng từ dữ liệu thật, bảng ba mức có cả độ tươi lẫn phần trăm bị bỏ, và mô tả đúng triệu chứng khi một phân vùng rỗng."),

(319,"Windows - tumbling, sliding and session","TH","Lesson 318",
"Ba loại cửa sổ trả lời ba câu hỏi nghiệp vụ khác nhau, và chọn sai loại là sai câu hỏi chứ sai cài đặt. Cửa sổ cuốn chiếu chia thời gian thành các khoảng rời nhau, dùng cho báo cáo theo kỳ, mỗi sự kiện thuộc đúng một cửa sổ. Cửa sổ trượt chồng lấn nhau, dùng khi cần trung bình trượt hoặc phát hiện ngưỡng liên tục, và mỗi sự kiện thuộc nhiều cửa sổ nên chi phí trạng thái nhân lên theo tỉ lệ chồng lấn. Cửa sổ phiên gom theo khoảng lặng chứ theo mốc thời gian cố định, dùng cho hành vi người dùng, và độ dài mỗi phiên do dữ liệu quyết định nên không đoán trước được chi phí. Ba loại đều đóng theo dấu nước ở lesson 318. Chi phí trạng thái là thứ phải tính trước: số khoá nhân số cửa sổ đang mở nhân kích thước trạng thái mỗi cửa sổ, và cửa sổ trượt với phiên dài là hai cách làm tràn bộ nhớ nhanh nhất.",
"Chọn đúng loại cửa sổ cho ba câu hỏi nghiệp vụ và ước lượng trước chi phí trạng thái, rồi đối chiếu ước lượng với số đo thật.",
"Tầng *áp dụng*. Objective là quyết định thiết kế kèm ước lượng kiểm được bằng đo đạc. Kiểm bằng ba cài đặt cộng bảng so ước lượng với thực đo; đạt khi cả ba chọn đúng loại và ước lượng cùng bậc độ lớn với số đo.",
"Cài đặt ba công việc: doanh thu theo giờ, số đơn trong 15 phút gần nhất cập nhật mỗi phút, và độ dài phiên mua sắm. Với mỗi công việc, ước lượng chi phí trạng thái trước khi chạy, rồi đo bộ nhớ trạng thái thật. Lập bảng so ước lượng với thực đo và giải thích chỗ lệch.",
"Dùng cửa sổ trượt cho báo cáo theo kỳ rồi đếm trùng · đặt cửa sổ phiên với khoảng lặng quá dài nên phiên không bao giờ đóng · không ước lượng trạng thái trước rồi tràn bộ nhớ trong sản xuất.",
"Ba công việc chọn đúng loại cửa sổ, và ước lượng trạng thái cùng bậc độ lớn với số đo thật ở ít nhất hai trong ba."),

(320,"State in a streaming job and where it is kept","LT","Lesson 319",
"Công việc không trạng thái xử lý từng sự kiện độc lập và khởi động lại không mất gì; công việc có trạng thái nhớ thứ đã thấy, nên mọi câu hỏi về tính đúng đều quy về câu hỏi trạng thái sống ở đâu và sống sót ra sao. Ba loại trạng thái và cách chúng lớn lên: trạng thái theo khoá lớn theo số khoá riêng biệt, trạng thái cửa sổ lớn theo lesson 319, và trạng thái toán tử cho việc như theo dõi vị trí đọc. Nơi giữ trạng thái quyết định trần quy mô: giữ trong bộ nhớ thì nhanh nhưng bị giới hạn bởi RAM một nút, giữ trong kho nhúng trên đĩa cục bộ thì vượt RAM được và đổi lấy độ trễ cao hơn. Trạng thái không bao giờ được phép lớn vô hạn, nên mọi trạng thái theo khoá phải có chính sách hết hạn; thiếu chính sách đó là cách công việc chạy tốt sáu tuần rồi chết. Trạng thái là thứ làm việc mở rộng quy mô trở nên khó: thêm nút không chỉ chia việc mà phải chia lại trạng thái theo khoá, cùng vấn đề đã gặp khi tăng phân vùng ở lesson 293.",
"Phân loại trạng thái trong một công việc cho trước và dự đoán nó lớn lên theo đại lượng nào, kèm chính sách hết hạn phù hợp.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho hai bài thực hành tiếp theo; chưa đòi cài đặt phục hồi. Kiểm bằng bài phân tích bốn công việc mẫu; đạt khi phân loại đúng ít nhất ba và nêu đúng đại lượng làm trạng thái lớn lên.",
"Cho bốn công việc mẫu. Với mỗi công việc, phân loại trạng thái, viết công thức ước lượng kích thước theo đại lượng nghiệp vụ, và đề xuất chính sách hết hạn. Chạy một công việc không có chính sách hết hạn với dữ liệu khoá tăng dần và vẽ đồ thị trạng thái lớn theo thời gian.",
"Cho rằng trạng thái nhỏ vì hiện tại nó nhỏ · dùng bộ nhớ làm nơi giữ trạng thái cho khoá không giới hạn · quên rằng thêm nút phải chia lại trạng thái.",
"Phân loại đúng ≥ 3/4 công việc kèm công thức ước lượng, và đồ thị cho thấy trạng thái không hết hạn lớn tuyến tính theo số khoá."),

(321,"Checkpointing, savepoints and recovery","TH","Lesson 320",
"Điểm kiểm tra là ảnh chụp nhất quán của toàn bộ trạng thái cộng vị trí đọc ở nguồn, chụp định kỳ và tự động, để khi công việc chết thì khởi động lại từ ảnh chụp gần nhất chứ từ đầu. Chi tiết quyết định tính đúng: ảnh chụp phải gồm **cả trạng thái lẫn vị trí đọc trong cùng một lần chụp**, nếu tách rời thì khôi phục xong sẽ hoặc bỏ sót hoặc xử lý lại một đoạn, cùng lập luận đã dùng cho offset và kết quả ở lesson 295. Cơ chế chụp mà không dừng dòng dữ liệu dùng dấu mốc đi theo luồng, và engine chờ mọi đầu vào của một toán tử cùng thấy dấu mốc trước khi chụp phần của mình. Chu kỳ chụp là một đánh đổi đo được: chụp dày thì mất ít việc khi hỏng nhưng tốn thông lượng; chụp thưa thì ngược lại. Điểm lưu là ảnh chụp do người chủ động tạo, dùng khi nâng cấp mã hoặc đổi cấu hình, và đây là cơ chế cho phép sửa công việc mà không mất trạng thái. Khi nào trạng thái cũ không tương thích với mã mới.",
"Khôi phục được công việc từ điểm kiểm tra sau khi giết tiến trình và chứng minh kết quả không thiếu không trùng, cùng bảng đánh đổi chu kỳ chụp.",
"Tầng *áp dụng*. Objective là một thao tác vận hành kiểm được bằng đối soát, đúng phương pháp thí nghiệm hỏng đã dùng ở lesson 298. Kiểm bằng ba lần giết tiến trình; đạt khi cả ba lần đối soát khớp tuyệt đối.",
"Bật điểm kiểm tra cho công việc gộp theo cửa sổ. Giết tiến trình ba lần ở ba thời điểm khác nhau trong một cửa sổ, mỗi lần khôi phục rồi đối soát kết quả với bản chạy không bị ngắt. Chạy ở ba chu kỳ chụp và đo thông lượng cùng thời gian khôi phục. Tạo một điểm lưu, sửa logic công việc, khởi động lại từ điểm lưu đó.",
"Chụp trạng thái mà không chụp vị trí đọc · đặt chu kỳ chụp rất dày rồi thắc mắc vì sao thông lượng thấp · khởi động lại từ đầu vì thấy nhanh hơn · đổi mã rồi khôi phục từ điểm lưu cũ mà không xét tương thích.",
"Ba lần giết tiến trình đều khôi phục và đối soát khớp tuyệt đối, bảng ba chu kỳ chụp có cả thông lượng lẫn thời gian khôi phục, và nâng cấp qua điểm lưu giữ nguyên trạng thái."),

(322,"Exactly-once in a streaming job - two-phase commit at the sink","TH","Lesson 321",
"Điểm kiểm tra cho đúng một lần **trong phạm vi engine**: khôi phục thì trạng thái nội bộ trở về nhất quán. Nhưng dữ liệu đã ghi ra đích thì không rút lại được, nên đúng một lần đầu cuối chỉ đạt khi đích hợp tác, đúng kết luận đã rút hai lần ở lesson 278 và 301. Ba loại đích và ba cách xử lý: đích hỗ trợ giao dịch thì dùng chốt hai pha, engine ghi trong giao dịch và chỉ chốt khi điểm kiểm tra hoàn tất; đích hỗ trợ ghi bất biến theo khoá thì ghi lại cho cùng kết quả nên không cần giao dịch, đây là cách rẻ và bền nhất theo lesson 106; đích không hỗ trợ gì thì chỉ đạt được ít nhất một lần và phải khử trùng ở tầng sau. Cái giá của chốt hai pha: dữ liệu chỉ nhìn thấy được sau khi chốt, nên độ trễ đầu cuối bị neo vào chu kỳ điểm kiểm tra ở lesson 321, và đây là điều bất ngờ với nhiều đội. Cách chọn giữa ba cách, và vì sao ghi bất biến thường là câu trả lời đúng.",
"Chọn đúng cơ chế cho một đích cho trước và chứng minh bằng thí nghiệm hỏng rằng kết quả không trùng không thiếu.",
"Tầng *đánh giá*. Objective đòi phán đoán về ranh giới giữa engine và đích, chỗ tài liệu hay gây hiểu nhầm. Kiểm bằng ba đích khác loại cộng thí nghiệm hỏng; đạt khi chọn đúng cả ba và hai đích có bảo đảm đều qua được thí nghiệm.",
"Cài cùng công việc ghi ra ba đích: một cơ sở dữ liệu có giao dịch, một bảng có khoá nghiệp vụ cho phép ghi bất biến, và một tệp nối thêm. Với mỗi đích, giết tiến trình giữa chừng ba lần và đếm trùng cùng thiếu. Đo độ trễ đầu cuối ở cấu hình chốt hai pha và so với cấu hình ghi bất biến.",
"Bật đúng một lần ở engine rồi tưởng đích cũng đúng một lần · dùng chốt hai pha cho đích không hỗ trợ · không lường độ trễ bị neo vào chu kỳ chụp · ghi tệp nối thêm rồi khẳng định không trùng.",
"Hai đích có bảo đảm cho 0 trùng 0 thiếu qua ba lần giết, đích thứ ba định lượng được mức trùng, và có số đo độ trễ của hai cấu hình."),

(323,"Stream-to-stream joins and the buffer they require","TH","Lesson 322",
"Kết hai luồng khác hẳn kết hai bảng: bảng đứng yên còn luồng thì không bao giờ kết thúc, nên phải trả lời câu hỏi chờ bao lâu cho bên kia tới. Kết theo khoảng thời gian là dạng dùng được: một sự kiện bên trái khớp với sự kiện bên phải cùng khoá trong một khoảng thời gian cho trước quanh nó. Khoảng đó quyết định trực tiếp hai thứ: tỉ lệ khớp được và lượng trạng thái phải giữ, vì engine buộc phải đệm mọi sự kiện chưa hết khoảng. Ước lượng trạng thái trước khi chạy: tốc độ sự kiện nhân độ dài khoảng nhân kích thước bản ghi, nhân đôi cho hai bên. Ba chế độ hỏng đặc trưng: khoảng quá hẹp thì mất phần lớn cặp khớp mà không báo lỗi gì, khoảng quá rộng thì trạng thái tràn, và một bên ngừng gửi thì dấu nước đứng lại theo lesson 318 nên không cặp nào được phát ra. Kết ngoài trong luồng chỉ phát được sau khi hết khoảng chờ, nên kết quả ra muộn hơn kết trong, điều này phải nói rõ với bên dùng.",
"Chọn khoảng thời gian kết từ phân bố độ lệch đo được, ước lượng trạng thái trước, và định lượng tỉ lệ cặp bị mất ở khoảng đã chọn.",
"Tầng *áp dụng*. Objective là quyết định thiết kế có hai hệ quả đo được, nối tiếp phương pháp chọn dấu nước ở lesson 318. Kiểm bằng ba mức khoảng; đạt khi có phân bố thật, ước lượng trạng thái cùng bậc với số đo, và tỉ lệ mất được định lượng.",
"Kết luồng đơn hàng với luồng thanh toán. Đo phân bố độ lệch thời gian giữa hai sự kiện cùng đơn. Chạy ở ba mức khoảng, mỗi mức đo tỉ lệ khớp, bộ nhớ trạng thái và độ trễ kết quả. Ngừng luồng thanh toán 5 phút và ghi lại hành vi của công việc.",
"Đặt khoảng theo cảm tính · không đo phân bố độ lệch · coi cặp không khớp là lỗi dữ liệu trong khi là do khoảng hẹp · quên rằng kết ngoài phát muộn.",
"Bảng ba mức khoảng đủ ba đại lượng, ước lượng trạng thái cùng bậc với số đo, và mô tả đúng hành vi khi một luồng ngừng."),

(324,"Stream-to-table joins and the temporal correctness trap","TH","Lesson 323",
"Làm giàu một luồng bằng dữ liệu tham chiếu là việc thường gặp nhất trong xử lý luồng, và cũng là chỗ sai âm thầm nhiều nhất. Cách ngây thơ là tra cứu bảng tham chiếu ở trạng thái hiện tại, và nó cho kết quả **không tái lập được**: chạy lại một tháng sau thì đơn hàng cũ được gắn giá hiện tại chứ giá lúc đó, nên chạy bù cho ra số khác lần chạy đầu, phá đúng tính chất đã đặt bắt buộc ở lesson 222. Cách đúng là kết theo thời điểm: dùng bản tham chiếu có hiệu lực tại thời điểm sự kiện, và điều này đòi bảng tham chiếu phải có lịch sử, tức là một bảng loại 2 như đã dựng từ CDC ở lesson 314. Ba cách nạp bảng tham chiếu vào công việc và đánh đổi: nạp toàn bộ vào bộ nhớ thì nhanh nhưng giới hạn kích thước và phải làm mới; tra cứu ngoài mỗi sự kiện thì luôn mới nhưng chậm và tạo tải lên hệ khác; nhận bảng dưới dạng luồng thay đổi thì đúng và tự cập nhật, và đây là chỗ M31 trả cổ tức.",
"Cài đặt kết theo thời điểm dùng luồng thay đổi, và chứng minh bằng chạy bù rằng kết quả tái lập được.",
"Tầng *sáng tạo*. Bài đòi ghép luồng CDC, bảng lịch sử và ngữ nghĩa thời gian sự kiện thành một thiết kế; cao hơn tầng áp dụng. Kiểm bằng phép chạy bù so hai lần; đạt khi hai lần chạy cách nhau cho kết quả khớp tuyệt đối.",
"Làm giàu luồng đơn hàng bằng bảng giá sản phẩm. Cài bản ngây thơ tra giá hiện tại và bản kết theo thời điểm dùng bảng loại 2 từ lesson 314. Đổi giá 20 sản phẩm. Chạy bù cùng khoảng dữ liệu trên cả hai bản và so kết quả với bản tính theo lô làm chuẩn.",
"Tra cứu trạng thái hiện tại rồi chạy bù ra số khác · dùng bảng tham chiếu không có lịch sử · tra cứu ngoài mỗi sự kiện rồi làm nghẽn hệ nguồn · không so với bản theo lô làm chuẩn.",
"Bản kết theo thời điểm cho kết quả khớp tuyệt đối với bản theo lô ở cả hai lần chạy bù, bản ngây thơ định lượng được mức lệch."),

(325,"Late data - drop, side output or update the result","TH","Lesson 324",
"Dấu nước ở lesson 318 đã đóng cửa sổ thì sự kiện tới sau đó phải đi đâu, và ba lựa chọn cho ba hệ quả nghiệp vụ khác nhau. Bỏ là mặc định của nhiều engine và là lựa chọn nguy hiểm nhất vì nó im lặng: số cuối thiếu mà không ai biết thiếu bao nhiêu. Đưa ra luồng phụ giữ lại sự kiện muộn để đếm, cảnh báo và đối soát, và đây là mức tối thiểu cho hệ có đối soát tài chính. Cập nhật lại kết quả cho số đúng nhất nhưng buộc đích phải chịu được ghi đè và buộc bên dùng chấp nhận số đã công bố có thể đổi, nên phải thoả thuận trước chứ quyết định một mình. Độ trễ cho phép sau dấu nước là tham số riêng, khác với độ trễ của dấu nước, và nhiều người nhầm hai cái. Nối với chất lượng dữ liệu ở M20: tỉ lệ sự kiện muộn là một chỉ số chất lượng phải theo dõi và đặt ngưỡng, cùng loại với các chiều ở lesson 211.",
"Chọn đúng cách xử lý dữ liệu muộn theo yêu cầu nghiệp vụ, cài đặt được, và đo tỉ lệ sự kiện muộn để đặt ngưỡng cảnh báo.",
"Tầng *đánh giá*. Objective đòi cân giữa độ chính xác và tính ổn định của số đã công bố, một quyết định có bên liên quan chứ thuần kỹ thuật. Kiểm bằng ba yêu cầu nghiệp vụ cộng cài đặt; đạt khi chọn đúng cả ba và có số đo tỉ lệ muộn.",
"Cài cả ba cách trên cùng công việc. Với dữ liệu có 5% sự kiện muộn, đo sai lệch kết quả của cách bỏ so với cách cập nhật. Đếm sự kiện ra luồng phụ và đặt cảnh báo theo tỉ lệ. Cho ba yêu cầu nghiệp vụ gồm báo cáo tài chính, bảng theo dõi vận hành và cảnh báo gian lận; chọn cách cho từng yêu cầu và nêu lý do.",
"Để mặc định bỏ rồi không biết mất bao nhiêu · cập nhật lại số đã công bố mà không báo bên dùng · nhầm độ trễ cho phép với độ trễ dấu nước · không theo dõi tỉ lệ muộn như một chỉ số chất lượng.",
"Ba cách chạy được, sai lệch của cách bỏ được định lượng, và ba yêu cầu nghiệp vụ được gán đúng cách kèm lý do."),

(326,"Backpressure, throughput and diagnosing a slow operator","TH","Lesson 325",
"Áp lực ngược trong engine luồng là cơ chế tự bảo vệ: toán tử chậm làm toán tử trước nó chậm theo, lan ngược tới nguồn, và hệ giảm tốc thay vì tràn bộ nhớ. Đây là hành vi đúng, nên nhìn thấy áp lực ngược không phải sự cố mà là **triệu chứng chỉ đường tới nút thắt**. Quy trình chẩn đoán: tìm toán tử đầu tiên tính từ cuối luồng mà không bị áp lực ngược, đó chính là nút thắt, vì mọi thứ trước nó đều đang chờ nó. Bốn nguyên nhân thường gặp ở nút thắt và cách phân biệt bằng số đo: tra cứu ngoài đồng bộ theo lesson 324, trạng thái quá lớn làm mỗi lần truy cập tốn đĩa, lệch dữ liệu theo khoá đúng hiện tượng sẽ gặp lại ở lesson 349, và tuần tự hoá đắt. Phân biệt độ trễ với thông lượng: tăng mức song song làm thông lượng tăng nhưng có thể không làm độ trễ giảm, và với khoá lệch thì tăng song song gần như không giúp gì. Quan hệ với độ trễ tiêu thụ ở lesson 300: độ trễ tăng là dấu hiệu, áp lực ngược chỉ ra chỗ.",
"Định vị toán tử nút thắt trong một công việc chậm bằng chỉ báo áp lực ngược, và quy nó về đúng một trong bốn nguyên nhân bằng số đo.",
"Tầng *phân tích*. Bài vận hành, đòi truy ngược từ triệu chứng toàn cục về một thành phần cụ thể. Kiểm bằng ba công việc chậm tiêm sẵn tính giờ; đạt khi định vị đúng ít nhất hai nút thắt và quy đúng nguyên nhân.",
"Giảng viên đưa ba công việc chạy chậm, mỗi công việc một nguyên nhân khác nhau, mỗi lần 12 phút. Với mỗi công việc, đọc chỉ báo áp lực ngược, định vị nút thắt, nêu nguyên nhân kèm số đo, và sửa. Đo thông lượng trước và sau. Với công việc khoá lệch, tăng mức song song gấp đôi và chứng minh thông lượng gần như không đổi.",
"Tăng tài nguyên toàn cục thay vì tìm nút thắt · coi áp lực ngược là lỗi cần tắt · kết luận nút thắt từ đồ thị CPU · tăng song song cho công việc lệch khoá rồi tưởng đã giải quyết.",
"Định vị đúng ≥ 2/3 nút thắt kèm nguyên nhân có số đo, và chứng minh được tăng song song không cứu được trường hợp lệch khoá."),

(327,"Spark Structured Streaming - the micro-batch model compared","TH","Lesson 326",
"Bài đối chiếu hai mô hình thực thi, không phải bài dạy Spark; phần nội bộ Spark nằm ở M34 và bài này chỉ dùng mức đủ để chạy một công việc tương đương. Mô hình luồng thuần xử lý từng sự kiện khi nó tới; mô hình lô vi mô gom sự kiện thành lô nhỏ rồi chạy như một công việc theo lô, và mọi khác biệt về độ trễ suy ra từ đó. Điều quan trọng cần thấy: **bốn khái niệm ở lesson 317 tới 322 giữ nguyên ý nghĩa ở cả hai mô hình**, chỉ đổi cách hiện thực, nên học ngữ nghĩa trước là đúng thứ tự. Bảng đối chiếu bốn điểm: thời gian sự kiện và dấu nước có ở cả hai; cửa sổ có ở cả hai; trạng thái và điểm kiểm tra có ở cả hai với cơ chế khác nhau; độ trễ sàn thì khác hẳn vì lô vi mô bị neo vào chu kỳ lô. Ba tình huống lô vi mô là lựa chọn hợp lý: đội đã vận hành Spark cho phần theo lô nên dùng chung một engine, yêu cầu độ trễ tính bằng giây chứ mili giây, và cùng một mã dùng được cho cả lô lẫn luồng.",
"Cài lại một công việc đã viết sang mô hình lô vi mô và đối chiếu bốn điểm, kèm số đo độ trễ sàn của cả hai.",
"Tầng *phân tích*. Objective là quy khác biệt quan sát được về khác biệt mô hình thực thi chứ về tên sản phẩm. Kiểm bằng bảng đối chiếu bốn điểm cộng số đo; đạt khi kết quả nghiệp vụ hai bản khớp nhau và chênh lệch độ trễ được giải thích bằng cơ chế lô.",
"Cài lại công việc gộp theo cửa sổ ở lesson 319 bằng Structured Streaming. Chạy song song hai bản trên cùng dữ liệu và chứng minh kết quả nghiệp vụ khớp nhau. Đo độ trễ đầu cuối phân vị 95 của cả hai ở ba chu kỳ lô. Lập bảng đối chiếu bốn điểm.",
"Kết luận engine này nhanh hơn engine kia mà không nêu yêu cầu độ trễ · so hai bản ở hai cấu hình khác nhau · học cú pháp mà bỏ qua chỗ bốn khái niệm ánh xạ sang · đi sâu vào nội bộ Spark ở bài này thay vì chờ M34.",
"Kết quả nghiệp vụ hai bản khớp tuyệt đối, bảng đối chiếu đủ bốn điểm, và chênh lệch độ trễ sàn có số kèm giải thích bằng chu kỳ lô."),

(328,"Gate 7 - a stateful job that survives late data, disorder and a kill","KT","Lesson 327",
"Cổng của chặng 6. Bài kiểm toàn bộ khối từ M27 tới M32: bản thân việc chọn broker, cách đưa dữ liệu vào bằng CDC, và tính đúng của công việc xử lý luồng dưới các điều kiện thực tế. Không có nội dung mới.",
"Nộp một công việc xử lý luồng có trạng thái chạy đúng dưới dữ liệu muộn, dữ liệu sai thứ tự và một lần giết tiến trình, với kết quả khớp bản tính theo lô.",
"Tầng *đánh giá*. Cổng đo năng lực dựng hệ đúng dưới điều kiện hỏng chứ đo trí nhớ về API; hình thức là bài làm có đối soát và có chất vấn.",
"Nhận một luồng sự kiện có 7% tới muộn và 3% sai thứ tự, kèm bản tính theo lô làm chuẩn. Bài chấm năm phần: A (25đ) công việc dùng thời gian sự kiện, độ trễ dấu nước chọn từ phân bố đo được · B (25đ) kết quả khớp bản chuẩn trong sai số cho trước, sự kiện muộn được đếm chứ bỏ im lặng · C (20đ) giết tiến trình giữa chừng, khôi phục từ điểm kiểm tra, đối soát khớp tuyệt đối · D (20đ) định vị nút thắt trong một công việc chậm cho sẵn và sửa · E (10đ) nêu một tình huống nên dùng xử lý theo lô thay vì luồng, kèm lý do.",
"Dùng thời gian xử lý cho nhanh rồi không đối soát được · để mặc định bỏ dữ liệu muộn · bỏ phần E vì hết giờ · nộp công việc chưa từng bị giết tiến trình lần nào.",
"Đạt ≥ 70/100, phần B và C đều ≥ 60%. Không đạt thì làm lại phần đo ở M32 rồi bảo vệ lại."),
]
