# -*- coding: utf-8 -*-
"""DE M29 Apache Kafka + M30 Choosing a message system."""

M29 = ("Apache Kafka", 291, 304, """| | |
|---|---|
| **Objective cấp module** | Xây và vận hành được kịch bản tham chiếu trên Kafka ở mức `A`, giải thích mọi cấu hình đã chọn bằng cơ chế nhật ký phân vùng, và đo bốn chỉ số của M30 |
| **Tiền đề** | M28 |
| **Exit criterion** | Kịch bản tham chiếu chạy đúng dưới cả ba lỗi cài sẵn và dưới việc giết một broker, bốn chỉ số tái lập được, và bảo vệ được lựa chọn `acks` · số bản sao · khoá phân vùng bằng số đo |
| **Kỹ năng SFIA** | `SYSP` mức 4 · `NTAS` mức 4 · `HPCC` mức 3 |
| **Chế độ hỏng** | Học API bên gửi và bên nhận mà bỏ qua bản sao và offset, rồi mất dữ liệu khi một broker chết hoặc sinh trùng khi cân bằng lại nhóm |""",
"""Mức `A` theo quy ước ở mục 2: xây và vận hành được, không chỉ làm lab. Kafka là hiện thân của mô hình nhật ký ở lesson 280, nên module này đo lại đúng những phép thử đã làm trên RabbitMQ ở M28 để M30 có hai cột số đặt cạnh nhau.

Ba phép thử lặp lại nguyên văn từ M28: số sự kiện mà một bên tiêu thụ tham gia sau nhận được, đo ở lesson 288 và đo lại ở lesson 296; số thông điệp mất khi giết tiến trình, đo ở lesson 286 và đo lại ở lesson 298; và bốn chỉ số của kịch bản tham chiếu, đo ở lesson 290 và đo lại ở lesson 304.""")

L29 = [
(291,"Architecture - broker, topic, partition and the log as the core structure","LT","Module 29: M28",
"Kafka không phải hàng đợi mà là nhật ký chỉ ghi thêm được phân vùng, và mọi khác biệt với RabbitMQ đều suy ra từ một câu đó. Chủ đề là tên logic, phân vùng là đơn vị vật lý thật: mỗi phân vùng là một tệp nhật ký có thứ tự, mỗi bản ghi có một số thứ tự tăng dần gọi là offset. Đọc không xoá, nên nhiều nhóm tiêu thụ đọc cùng dữ liệu mà không đụng nhau, và đây là chỗ mô hình nhật ký giải sẵn vấn đề mà RabbitMQ phải dựng bằng fanout ở lesson 284. Ghi luôn nối vào cuối nên ghi tuần tự, nối thẳng về chênh lệch giữa ghi tuần tự và ghi ngẫu nhiên ở M2 và về nhật ký ghi trước ở lesson 118. Ba vai trong cụm: broker giữ phân vùng, một broker làm trưởng cho mỗi phân vùng, phần còn lại giữ bản sao. Phân đoạn tệp và chỉ mục offset ở mức đủ để hiểu vì sao tìm theo offset rẻ còn tìm theo nội dung thì không, cùng lý do với chỉ mục ở lesson 111.",
"Vẽ được đường đi của một bản ghi từ bên gửi tới đĩa và tới bên tiêu thụ, gọi đúng tên chủ đề, phân vùng, offset và trưởng phân vùng.",
"Tầng *hiểu*. Bài mở module, chưa đủ lab để đòi vận hành, nên objective dừng ở tái hiện cơ chế và nối nó với kiến thức lưu trữ đã có. Kiểm bằng bài vẽ có chú thích cộng ba câu hỏi vì sao; đạt khi bản vẽ đúng và trả lời được vì sao đọc không xoá dữ liệu.",
"Dựng cụm ba broker bằng container. Tạo một chủ đề ba phân vùng, gửi 100 bản ghi, xem tệp nhật ký trên đĩa và định vị phân đoạn. Chạy hai nhóm tiêu thụ độc lập trên cùng chủ đề và chứng minh cả hai đọc đủ 100 bản ghi. Vẽ lại kiến trúc có chú thích.",
"Nhầm chủ đề với hàng đợi · tưởng đọc xong là bản ghi biến mất · nghĩ số phân vùng chỉ là chuyện hiệu năng.",
"Bản vẽ gọi đúng bốn khái niệm, hai nhóm tiêu thụ cùng đọc đủ 100 bản ghi, và giải thích đúng vì sao đọc không xoá."),

(292,"The producer path - batching, compression, acks and idempotent writes","TH","Lesson 291",
"Bên gửi không gửi từng bản ghi mà gom thành lô, và ba tham số quyết định hình dạng của lô: kích thước lô, thời gian chờ gom, và bộ nhớ đệm. Tăng thời gian chờ gom làm thông lượng tăng và độ trễ tăng theo, đây là đường đánh đổi phải đo chứ đoán, cùng dạng với prefetch ở lesson 285. Nén đặt ở bên gửi và giữ nguyên qua broker tới bên nhận, nên tiết kiệm cả đĩa lẫn băng thông; bốn thuật toán với ba mức đánh đổi giữa tỉ lệ nén và chi phí CPU. Tham số `acks` là chỗ ngữ nghĩa giao nhận ở lesson 278 thành cấu hình: `0` là gửi rồi quên, `1` là trưởng phân vùng đã ghi, `all` là đủ số bản sao tối thiểu đã ghi. Bên gửi bất biến bật lên thì Kafka tự khử trùng các lần thử lại trong cùng một phiên bằng số thứ tự nội bộ, **nhưng chỉ trong phiên đó**: bên gửi khởi động lại thì trùng vẫn có thể sinh, nên khử trùng theo khoá nghiệp vụ ở lesson 208 vẫn bắt buộc.",
"Đo được quan hệ giữa thời gian chờ gom và cặp thông lượng, độ trễ phân vị 95, rồi chọn cấu hình có căn cứ từ số đo của chính mình.",
"Tầng *đánh giá*. Bài đòi chọn một điểm trên đường đánh đổi từ dữ liệu tự đo, lặp lại đúng phương pháp đã dùng cho prefetch ở lesson 285 để hai cột số so được với nhau. Kiểm bằng bảng ít nhất bốn cấu hình; đạt khi có đường cong, có điểm chọn và lý do dẫn số.",
"Đo thông lượng và độ trễ phân vị 95 ở bốn giá trị thời gian chờ gom và ba thuật toán nén. Chạy lại ở `acks=1` và `acks=all` rồi ghi mức chênh thông lượng. Bật bên gửi bất biến, ép thử lại bằng cách ngắt mạng ngắn, đếm bản ghi trùng; rồi khởi động lại bên gửi giữa chừng và đếm lại.",
"Để `acks=0` trong mã sản xuất · tin rằng bên gửi bất biến là đủ để khỏi khử trùng · so thông lượng giữa hai cấu hình nén khác nhau mà quên chi phí CPU.",
"Bảng có đủ bốn mức thời gian chờ và ba thuật toán nén, chênh lệch giữa hai mức `acks` có số, và đếm đúng số trùng ở cả hai kịch bản thử lại."),

(293,"Partitioning and the key - throughput against order","TH","Lesson 292",
"Số phân vùng đặt trần cho hai thứ cùng lúc: mức song song của bên tiêu thụ, vì một phân vùng chỉ được một bên tiêu thụ trong nhóm đọc, và phạm vi bảo đảm thứ tự ở lesson 279. Không có khoá thì bản ghi rải đều và mất thứ tự; có khoá thì cùng khoá vào cùng phân vùng và giữ thứ tự trong khoá đó. Bài toán khoá nóng: một mã khách chiếm phần lớn lưu lượng thì một phân vùng nặng hơn hẳn, và mức song song thực tế tụt về gần một, cùng hiện tượng lệch dữ liệu sẽ gặp lại ở lesson 349. Ba cách chữa và cái giá: thêm muối vào khoá thì mất thứ tự trong khoá, tách riêng khoá nóng thì thêm phức tạp vận hành, tăng phân vùng thì **ánh xạ khoá đổi nên thứ tự cũ đứt** và không lùi lại được vì Kafka không cho giảm số phân vùng. Chọn số phân vùng là quyết định khó sửa, nên phải ước lượng từ thông lượng đích chia cho thông lượng một phân vùng, cộng biên cho tăng trưởng.",
"Chọn số phân vùng và khoá cho kịch bản tham chiếu, bảo vệ bằng số đo thông lượng, và trình bày được điều gì hỏng khi tăng phân vùng về sau.",
"Tầng *đánh giá*. Objective là một quyết định khó đảo ngược, nên yêu cầu cao hơn tầng áp dụng: phải cân nhắc cả trạng thái tương lai. Kiểm bằng thí nghiệm tăng phân vùng giữa chừng; đạt khi dự đoán trước được hậu quả và số đo xác nhận dự đoán đó.",
"Đo thông lượng ở 1, 3, 6 và 12 phân vùng với cùng số bên tiêu thụ, rồi với số bên tiêu thụ bằng số phân vùng. Tạo khoá nóng chiếm 60% lưu lượng và đo lại. Viết dự đoán về thứ tự trước, rồi tăng phân vùng từ 3 lên 6 trên chủ đề đang chạy và kiểm chứng dự đoán bằng nhật ký.",
"Đặt số phân vùng bằng một con số tròn mà không ước lượng · tăng phân vùng trên chủ đề có khoá mà không lường thứ tự đứt · thêm bên tiêu thụ vượt số phân vùng rồi tưởng nhanh hơn.",
"Bảng thông lượng đủ bốn mức phân vùng, đo được tác động của khoá nóng, và dự đoán về thứ tự khớp với nhật ký sau khi tăng phân vùng."),

(294,"The consumer group protocol - assignment, rebalance and its cost","TH","Lesson 293",
"Nhóm tiêu thụ là cách Kafka chia phân vùng cho nhiều tiến trình, và điều phối viên nhóm nằm ở phía broker giữ việc chia đó. Cân bằng lại kích hoạt khi thành viên vào, ra, hoặc bị coi là chết; trong cân bằng lại kiểu dừng toàn bộ thì **mọi thành viên ngừng xử lý**, nên nhóm càng đông thì mỗi lần triển khai càng tốn thời gian dừng, đúng cảnh báo đã nêu ở lesson 280. Ba tham số quyết định khi nào một thành viên bị coi là chết, và vì sao đặt sai làm nhóm cân bằng lại liên tục: khoảng nhịp tim, thời gian chờ phiên, và khoảng tối đa giữa hai lần lấy dữ liệu. Nguyên nhân hay gặp nhất là xử lý một lô lâu hơn khoảng tối đa giữa hai lần lấy, nên thành viên bị đá ra ngay khi nó đang làm việc bình thường. Hai chiến lược chia giảm đau: chia dính giữ nguyên phần lớn phân vùng cũ, và thành viên tĩnh cho phép khởi động lại mà không kích hoạt chia lại. Đo chi phí cân bằng lại bằng thời gian từ lúc thành viên rời tới lúc tốc độ ra hồi phục.",
"Chẩn đoán một nhóm đang cân bằng lại liên tục về đúng tham số gây ra, và giảm được thời gian dừng bằng cấu hình có số đo chứng minh.",
"Tầng *phân tích*. Bài vận hành với triệu chứng dễ chẩn đoán nhầm, nên objective là truy ngược từ biểu hiện về nguyên nhân. Kiểm bằng sự cố tiêm sẵn tính giờ; đạt khi chẩn đoán đúng trong giới hạn thời gian và thời gian dừng đo được giảm sau khi sửa.",
"Đặt khoảng tối đa giữa hai lần lấy thấp hơn thời gian xử lý một lô và quan sát nhóm cân bằng lại liên tục. Đo thời gian dừng khi một thành viên rời ở nhóm ba và nhóm tám. Bật chia dính rồi đo lại. Bật thành viên tĩnh, khởi động lại một thành viên và ghi lại có kích hoạt chia lại không.",
"Đặt thời gian chờ phiên rất lớn để né cân bằng lại rồi phát hiện thành viên chết mất nhiều phút mới bị nhận ra · xử lý lô dài mà không chỉnh tham số · kết luận về chi phí cân bằng lại mà chưa đo.",
"Chẩn đoán đúng nguyên nhân trong giới hạn thời gian, và bảng thời gian dừng cho thấy chia dính hoặc thành viên tĩnh giảm được số đo đó."),

(295,"Offsets - where they live and committing them with the result","TH","Lesson 294",
"Offset đã xử lý tới đâu được ghi vào một chủ đề nội bộ của Kafka, và chính sách ghi quyết định điều gì xảy ra khi bên tiêu thụ chết. Tự động ghi theo chu kỳ là mặc định và là nguồn sinh trùng lẫn mất dữ liệu phổ biến nhất: ghi sau khi lấy nhưng trước khi xử lý xong thì mất, ghi sau khi xử lý nhưng theo chu kỳ thì phần giữa hai lần ghi bị làm lại. Ghi thủ công sau khi xử lý xong cho ít nhất một lần, đúng định nghĩa ở lesson 278. Cách duy nhất đạt đúng một lần đầu cuối khi đích là cơ sở dữ liệu: **ghi offset vào chính cơ sở dữ liệu đó trong cùng một giao dịch với kết quả**, rồi khi khởi động lại thì đọc offset từ đó thay vì từ Kafka; đây là cách áp dụng trực tiếp nguyên tắc ghi bất biến ở lesson 106 và 207. Ba vị trí bắt đầu khi nhóm mới hoặc offset hết hạn, và vì sao mặc định đọc từ mới nhất làm mất dữ liệu trong lần triển khai đầu.",
"Cài đặt được ghi offset cùng giao dịch với kết quả và chứng minh bằng thực nghiệm rằng giết tiến trình giữa chừng không sinh trùng và không mất bản ghi.",
"Tầng *sáng tạo*. Bài đòi ghép cơ chế giao dịch của cơ sở dữ liệu với cơ chế offset của Kafka thành một mẫu mà không API nào cung cấp sẵn, nên cao hơn tầng áp dụng. Kiểm bằng đối soát sau khi giết tiến trình; đạt khi số bản ghi và tổng tiền khớp tuyệt đối.",
"Chạy ba cấu hình trên cùng tải: tự động ghi, ghi thủ công sau xử lý, và ghi cùng giao dịch với kết quả. Với mỗi cấu hình, giết bên tiêu thụ 5 lần ngẫu nhiên giữa chừng rồi đối soát bảng đích với nguồn. Lập bảng ba cấu hình với số trùng và số thiếu.",
"Để tự động ghi offset trong mã sản xuất · ghi offset trước khi ghi kết quả · bắt đầu từ mới nhất ở lần triển khai đầu rồi mất dữ liệu · đối soát bằng số dòng mà quên tổng tiền.",
"Bảng ba cấu hình có số trùng và số thiếu, và cấu hình cùng giao dịch cho 0 trùng 0 thiếu qua cả 5 lần giết."),

(296,"Retention, compaction and reading the past","TH","Lesson 295",
"Hai chính sách giữ dữ liệu phục vụ hai mục đích khác nhau. Giữ theo thời gian hoặc dung lượng: bản ghi cũ bị xoá theo phân đoạn, dùng cho luồng sự kiện. Nén theo khoá: giữ lại bản ghi mới nhất của mỗi khoá và xoá bản cũ hơn, biến chủ đề thành một ảnh chụp trạng thái hiện hành dựng lại được, và đây là nền của mẫu bảng thay đổi sẽ dùng ở M31. Bản ghi giá trị rỗng là dấu xoá, có thời gian giữ riêng để bên tiêu thụ chậm kịp thấy nó. Đọc lại quá khứ là thao tác bình thường: đặt lại offset của nhóm về đầu, về một offset cụ thể, hoặc về một dấu thời gian. Đây là chỗ khác biệt lớn nhất với RabbitMQ, nên **lặp lại nguyên văn phép thử ở lesson 288**: thêm một bên tiêu thụ sau khi đã phát 1.000 sự kiện và đếm nó nhận được bao nhiêu. Hai con số đặt cạnh nhau là bằng chứng chính của lesson 306. Giới hạn: phát lại chỉ đúng khi bên tiêu thụ bất biến, nếu không thì phát lại là nhân đôi.",
"Đặt lại offset để phát lại một khoảng thời gian cho trước, và giải thích khác biệt số liệu giữa Kafka và RabbitMQ trong cùng phép thử bên tiêu thụ tham gia sau.",
"Tầng *áp dụng*. Objective là một thao tác vận hành có kết quả kiểm được bằng phép đếm, cộng một so sánh đã có sẵn dữ liệu đối chứng. Kiểm bằng phép đếm và đối soát; đạt khi phát lại đúng khoảng yêu cầu và hai con số so sánh được giải thích đúng.",
"Phát 1.000 sự kiện rồi thêm một nhóm tiêu thụ mới và đếm số nhận được. Đặt con số đó cạnh con số đã ghi ở lesson 288. Dựng một chủ đề nén theo khoá cho bảng trạng thái khách hàng, gửi nhiều bản cập nhật cùng khoá, ép nén và chứng minh chỉ còn bản mới nhất. Phát lại đúng một ngày bằng cách đặt lại offset theo dấu thời gian và đối soát mart.",
"Dùng nén theo khoá cho luồng sự kiện nên mất lịch sử · quên thời gian giữ dấu xoá · phát lại khi bên tiêu thụ chưa bất biến · đặt lại offset khi nhóm đang chạy.",
"Bên tiêu thụ mới nhận đủ 1.000 và giải thích đúng chênh lệch với số ở lesson 288; chủ đề nén chỉ còn bản mới nhất mỗi khoá; phát lại một ngày đối soát khớp."),

(297,"Replication, ISR and what min.insync.replicas actually buys","LT","Lesson 296",
"Mỗi phân vùng có một trưởng và các bản sao đi theo; tập bản sao đang bắt kịp gọi là ISR. Bản sao rơi khỏi ISR khi tụt quá xa so với trưởng, và tham số quyết định ngưỡng tụt đó. Ba tham số phải hiểu cùng nhau, vì đặt lẻ từng cái là nguồn mất dữ liệu âm thầm: hệ số nhân bản đặt khi tạo chủ đề, số bản sao tối thiểu phải ghi xong, và `acks` ở bên gửi tại lesson 292. Chỉ khi `acks=all` **và** số bản sao tối thiểu lớn hơn một thì mới thật sự có bảo đảm; đặt `acks=all` với số bản sao tối thiểu bằng một thì bảo đảm rơi về mức của một bản sao duy nhất. Bầu trưởng không sạch: cho phép một bản sao ngoài ISR lên làm trưởng thì cụm tiếp tục phục vụ nhưng **mất bản ghi đã xác nhận**, đây là lựa chọn giữa sẵn sàng và bền, nối lại phân biệt ở lesson 286. Quan hệ với độ trễ bản sao đã học ở lesson 120. Cách đọc trạng thái ISR để biết cụm đang khoẻ hay đang chỉ còn một bản sao thật sự.",
"Với một bộ ba tham số cho trước, kết luận cụm chịu được mấy broker chết mà không mất bản ghi đã xác nhận, và chỉ ra cấu hình nào tạo bảo đảm giả.",
"Tầng *đánh giá*. Objective đòi suy luận về tương tác của ba tham số chứ nhớ ý nghĩa từng cái, và đây là chỗ hay tạo bảo đảm giả trong hệ thật. Kiểm bằng sáu bộ tham số; đạt khi kết luận đúng ít nhất năm và nhận ra đủ các bộ tạo bảo đảm giả.",
"Nhận sáu bộ ba tham số. Với mỗi bộ, viết số broker chết tối đa mà không mất bản ghi đã xác nhận, và đánh dấu bộ nào tạo bảo đảm giả. Đọc trạng thái ISR của cụm đang chạy và nêu cụm hiện chịu được mấy broker chết. Bật bầu trưởng không sạch trên một chủ đề thử và mô tả đánh đổi.",
"Đặt hệ số nhân bản cao mà để số bản sao tối thiểu bằng một · dùng `acks=all` rồi tưởng đã an toàn bất kể cấu hình broker · bật bầu trưởng không sạch trên chủ đề cần bền.",
"Kết luận đúng ≥ 5/6 bộ tham số và nhận ra đủ các bộ tạo bảo đảm giả."),

(298,"Durability under failure - kill a broker and count the messages","TH","Lesson 297",
"Bài thí nghiệm hỏng, lặp lại đúng phương pháp đã dùng ở lesson 286 trên RabbitMQ để hai cột số so được với nhau. Ba kịch bản hỏng với ba biểu hiện khác nhau: giết broker không giữ trưởng của phân vùng đang ghi thì hầu như không thấy gì; giết broker đang giữ trưởng thì có một khoảng bầu lại trưởng, bên gửi thấy lỗi tạm thời và phải thử lại; giết đủ broker để ISR tụt dưới số bản sao tối thiểu thì bên gửi bị từ chối ghi, và **đây là hành vi đúng**, vì từ chối ghi còn hơn nhận rồi mất. Thời gian bầu lại trưởng đo được và phụ thuộc vào cấu hình phát hiện chết. Phân biệt ba loại số phải đếm sau thí nghiệm: bản ghi bên gửi tưởng đã gửi, bản ghi broker đã xác nhận, và bản ghi bên tiêu thụ thực nhận; chỉ khi cả ba khớp mới kết luận được không mất. Quy trình thí nghiệm lặp lại được: cố định tải, cố định thời điểm giết, chạy ba lần lấy trung vị.",
"Đo được số bản ghi mất và thời gian phục hồi ở ba kịch bản hỏng, và kết luận cấu hình hiện tại chịu được kịch bản nào.",
"Tầng *phân tích*. Bài đòi thiết kế và đọc một thí nghiệm hỏng chứ chạy một lệnh, nối tiếp phương pháp của cổng ở lesson 218. Kiểm bằng bảng ba kịch bản ba lần chạy; đạt khi ba số của mỗi kịch bản khớp nhau và kết luận dẫn được từ bảng.",
"Với cấu hình đủ bền, chạy ba kịch bản hỏng, mỗi kịch bản ba lần. Mỗi lần đếm cả ba loại số và đo thời gian phục hồi. Lập bảng và ghi trung vị. Chạy lại kịch bản hai với `acks=1` và ghi mức chênh. Đặt bảng này cạnh bảng ở lesson 286.",
"Chỉ đếm số bản ghi ở đích mà quên số bên gửi tưởng đã gửi · chạy một lần rồi kết luận · coi việc bị từ chối ghi là lỗi cấu hình · quên cố định thời điểm giết nên ba lần không so được.",
"Bảng ba kịch bản ba lần chạy đủ ba loại số, cấu hình đủ bền cho 0 mất ở kịch bản một và hai, và có số đo mức chênh khi hạ xuống `acks=1`."),

(299,"Schema registry and compatible change","TH","Lesson 298",
"Kafka chở byte và không biết gì về cấu trúc bên trong, nên không có gì ngăn bên gửi đổi định dạng và làm mọi bên tiêu thụ hỏng cùng lúc. Sổ đăng ký lược đồ đặt một chốt ở giữa: bên gửi đăng ký lược đồ, bản ghi mang mã lược đồ, bên tiêu thụ tra để giải mã. Ba chế độ tương thích và ý nghĩa vận hành của từng chế độ: tương thích ngược cho phép bên tiêu thụ mới đọc dữ liệu cũ nên nâng cấp bên tiêu thụ trước; tương thích xuôi cho phép bên tiêu thụ cũ đọc dữ liệu mới nên nâng cấp bên gửi trước; tương thích đầy đủ cho cả hai và ràng buộc chặt nhất. Thay đổi nào an toàn và thay đổi nào phá vỡ, với quy tắc thực dụng: thêm trường có giá trị mặc định thì an toàn, xoá trường bắt buộc hoặc đổi kiểu thì không. Nối thẳng về tiến hoá lược đồ ở biên nhận dữ liệu tại lesson 209 và về hợp đồng dữ liệu ở M26: sổ đăng ký là cách cưỡng chế hợp đồng bằng máy thay vì bằng thoả thuận miệng.",
"Chọn chế độ tương thích phù hợp với thứ tự triển khai của đội, và thực hiện được một thay đổi lược đồ phá vỡ mà không làm gián đoạn bên tiêu thụ đang chạy.",
"Tầng *áp dụng*. Objective là một quy trình thay đổi có ràng buộc kiểm được bằng việc bên tiêu thụ cũ vẫn chạy. Kiểm bằng bài thực hiện thay đổi trên hệ đang chạy; đạt khi không bên tiêu thụ nào lỗi trong suốt quá trình.",
"Đăng ký lược đồ cho sự kiện đơn hàng. Thử ba thay đổi: thêm trường có mặc định, xoá trường bắt buộc, đổi kiểu một trường; ghi lại sổ đăng ký chấp nhận cái nào ở từng chế độ. Sau đó thực hiện thay đổi phá vỡ theo quy trình hai giai đoạn trên hệ đang chạy và chứng minh bên tiêu thụ cũ không lỗi lần nào.",
"Đổi lược đồ mà không xét thứ tự triển khai · chọn tương thích đầy đủ rồi bị chặn mọi thay đổi cần thiết · coi sổ đăng ký là nơi lưu tài liệu thay vì một chốt cưỡng chế.",
"Ba thay đổi được phân loại đúng ở cả ba chế độ, và thay đổi phá vỡ hoàn tất mà bên tiêu thụ cũ không lỗi lần nào."),

(300,"Consumer lag - measuring it and alerting on the right signal","TH","Lesson 299",
"Độ trễ tiêu thụ là hiệu giữa offset cuối của phân vùng và offset nhóm đã ghi, đo bằng số bản ghi. Đây là chỉ số sức khoẻ quan trọng nhất của một hệ luồng, nhưng đo sai cách thì báo động sai: độ trễ tính bằng bản ghi không nói được còn bao lâu mới đuổi kịp, vì một bản ghi có thể tốn một mili giây hoặc một giây. Hai chỉ số nên theo dõi cùng nhau: độ trễ theo bản ghi và độ trễ quy đổi ra thời gian, tính bằng độ trễ chia cho tốc độ xử lý hiện tại. Bốn nguyên nhân làm độ trễ tăng, phân biệt được bằng số đo, và ba trong bốn cái đã gặp dưới dạng khác ở lesson 289: bên tiêu thụ chậm hơn bên gửi, một phân vùng lệch tải, nhóm đang cân bằng lại liên tục, và hạ nguồn chậm. Đặt cảnh báo trên xu hướng tăng liên tục thay vì trên ngưỡng tuyệt đối, vì ngưỡng tuyệt đối hoặc quá nhạy lúc tải cao hoặc quá điếc lúc tải thấp, cùng nguyên tắc ngưỡng động đã dùng ở tầng theo lô.",
"Đọc biểu đồ độ trễ và định vị đúng một trong bốn nguyên nhân, rồi đặt cảnh báo báo sớm hơn ngưỡng tuyệt đối trên cùng dữ liệu.",
"Tầng *phân tích*. Bài đòi truy ngược từ hình dạng biểu đồ về cơ chế, kỹ năng trực tiếp dùng khi có sự cố. Kiểm bằng bốn sự cố tiêm sẵn; đạt khi định vị đúng ít nhất ba và cảnh báo mới báo trước cảnh báo ngưỡng ít nhất một khoảng đo được.",
"Dựng theo dõi độ trễ theo cả hai chỉ số. Giảng viên tiêm lần lượt bốn nguyên nhân. Với mỗi lần, ghi hình dạng biểu đồ, nêu nguyên nhân và bằng chứng. Đặt hai cảnh báo trên cùng dữ liệu lịch sử, một theo ngưỡng tuyệt đối và một theo xu hướng, rồi đo cái nào báo trước và trước bao lâu.",
"Chỉ theo dõi độ trễ theo bản ghi · đặt ngưỡng tuyệt đối một con số tròn · bỏ qua độ trễ ở mức từng phân vùng nên không thấy lệch tải · tắt cảnh báo vì kêu nhiều thay vì sửa ngưỡng.",
"Định vị đúng ≥ 3/4 nguyên nhân kèm bằng chứng, và cảnh báo theo xu hướng báo trước cảnh báo ngưỡng một khoảng đo được."),

(301,"Exactly-once with transactions, and its real boundary","TH","Lesson 300",
"Kafka có giao dịch cho mẫu đọc rồi xử lý rồi ghi trong cùng một cụm: bên gửi giao dịch, ghi offset như một phần của giao dịch, và bên tiêu thụ đặt mức cô lập chỉ đọc bản ghi đã chốt. Điều này cho đúng một lần **trong phạm vi Kafka tới Kafka**. Ranh giới thật phải nói rõ: khi đích là cơ sở dữ liệu ngoài hoặc lời gọi tới hệ khác thì giao dịch của Kafka không bao trùm được, và cách duy nhất vẫn là ghi offset cùng giao dịch với kết quả như lesson 295, hoặc ghi có tính bất biến theo khoá nghiệp vụ. Cái giá đo được: giao dịch làm thông lượng giảm và độ trễ tăng vì phải chốt theo lô, và bài lab đo mức đó. Đây cũng là chỗ cần nói thẳng với đội: bật một cờ tên gọi hứa hẹn không làm hệ đúng một lần nếu tuyến đi ra ngoài Kafka, đúng kết luận đã rút ở lesson 278.",
"Phân biệt được tuyến nào giao dịch Kafka bao trùm và tuyến nào không, rồi chọn đúng cơ chế cho từng tuyến kèm số đo chi phí.",
"Tầng *đánh giá*. Objective là một phán đoán về ranh giới cơ chế, chỗ tài liệu nhà cung cấp hay gây hiểu nhầm. Kiểm bằng bốn tuyến khác nhau; đạt khi phân loại đúng cả bốn và có bảng chi phí đo được.",
"Cài đặt mẫu đọc rồi xử lý rồi ghi có giao dịch giữa hai chủ đề; giết tiến trình giữa chừng và chứng minh không trùng không thiếu. Đo thông lượng có và không có giao dịch. Cho bốn tuyến gồm Kafka tới Kafka, Kafka tới PostgreSQL, Kafka tới lời gọi web, và Kafka tới tệp; phân loại tuyến nào giao dịch bao trùm và viết cơ chế thay thế cho các tuyến còn lại.",
"Tin rằng bật giao dịch là hệ thành đúng một lần bất kể đích · quên đặt mức cô lập ở bên tiêu thụ · bỏ qua chi phí thông lượng · dùng giao dịch cho tuyến ra ngoài Kafka rồi vẫn sinh trùng.",
"Mẫu trong Kafka cho 0 trùng 0 thiếu qua các lần giết, bảng chi phí có số, và phân loại đúng cả bốn tuyến kèm cơ chế thay thế."),

(302,"Kafka Connect - moving data without writing a consumer","TH","Lesson 301",
"Phần lớn việc chuyển dữ liệu vào hoặc ra Kafka là việc lặp lại, và viết lại một bên tiêu thụ cho mỗi đích là cách sinh ra mã không ai bảo trì. Connect là tầng chạy sẵn các trình nối: trình nối nguồn kéo vào Kafka, trình nối đích đẩy ra ngoài. Hai chế độ chạy và hệ quả vận hành: đơn lẻ dễ thử nhưng không chịu lỗi, phân tán thì cấu hình và offset nằm trong chính Kafka nên chịu được một nút chết. Trình biến đổi đơn giản cho những việc nhỏ như đổi tên trường hay che dữ liệu nhạy cảm; ranh giới phải giữ là **biến đổi có logic nghiệp vụ không thuộc về đây**, vì Connect không có kiểm thử và không có khả năng chạy lại như một công việc xử lý, cùng lập luận đã dùng khi nói về ranh giới của broker ở lesson 282. Xử lý bản ghi lỗi: chuyển sang chủ đề thư chết thay vì dừng cả trình nối. Khi nào tự viết bên tiêu thụ thì hợp lý hơn dùng Connect: ba tiêu chí quyết định.",
"Dựng được một tuyến vào và một tuyến ra bằng Connect, cấu hình thư chết cho bản ghi lỗi, và nêu tiêu chí chọn giữa Connect và tự viết.",
"Tầng *áp dụng*. Objective là dựng và cấu hình một thành phần có sẵn, chưa đòi thiết kế mới. Kiểm bằng tuyến chạy được cộng bài so sánh ngắn; đạt khi cả hai tuyến chạy, bản ghi lỗi vào thư chết, và tiêu chí chọn nêu được ba điểm.",
"Dựng trình nối nguồn từ PostgreSQL vào Kafka và trình nối đích từ Kafka ra kho đối tượng, chạy ở chế độ phân tán. Tiêm bản ghi sai định dạng và chứng minh trình nối không dừng mà đẩy sang thư chết. Giết một nút Connect và xác nhận công việc chuyển sang nút còn lại. Viết ba tiêu chí chọn giữa Connect và tự viết.",
"Nhồi logic nghiệp vụ vào trình biến đổi đơn giản · chạy chế độ đơn lẻ trong sản xuất · để trình nối dừng vì một bản ghi lỗi · dùng Connect cho việc cần kiểm thử và chạy lại.",
"Hai tuyến chạy ở chế độ phân tán, bản ghi lỗi vào thư chết mà trình nối vẫn chạy, công việc chuyển nút thành công, và ba tiêu chí chọn được viết ra."),

(303,"Operating Kafka - sizing, rolling upgrade and a stuck group","TH","Lesson 302",
"Ước lượng quy mô từ ba đại lượng đầu vào: thông lượng ghi, hệ số nhân bản, và thời gian giữ; nhân lại ra dung lượng đĩa cần, cộng biên cho đỉnh tải và cho việc một broker chết làm phần còn lại gánh thêm. Vì sao đĩa thường hết trước khi CPU hết, và vì sao đặt thời gian giữ dài là quyết định tốn kém âm thầm. Nâng cấp cuốn chiếu: dừng từng broker một, chờ ISR đầy lại rồi mới sang broker kế, và lý do bỏ bước chờ là cách mất dữ liệu nhanh nhất. Quan sát tối thiểu phải có: độ trễ tiêu thụ ở lesson 300, số phân vùng thiếu bản sao, dung lượng đĩa còn lại, và số lần cân bằng lại nhóm mỗi giờ. Bốn sự cố hay gặp và cách phân biệt: nhóm kẹt vì cân bằng lại liên tục, nhóm kẹt vì một bản ghi hỏng chặn đầu, phân vùng thiếu bản sao kéo dài, và đĩa đầy làm broker dừng nhận ghi. Sổ tay xử lý cho từng sự cố, viết theo chuẩn đã dùng ở M26.",
"Ước lượng được dung lượng đĩa cho một yêu cầu cho trước, thực hiện nâng cấp cuốn chiếu không mất bản ghi, và chẩn đoán một nhóm kẹt về đúng nguyên nhân.",
"Tầng *áp dụng*. Bài vận hành tổng hợp, mọi cơ chế đã học ở các bài trước nên đây là bài ghép lại thành quy trình. Kiểm bằng ba phần: bảng ước lượng, nâng cấp thực tế có đếm bản ghi, và chẩn đoán tính giờ; đạt khi cả ba phần đạt.",
"Ước lượng đĩa cho 50.000 bản ghi mỗi giây, mỗi bản 1 KB, nhân bản 3, giữ 7 ngày, kèm biên. Thực hiện nâng cấp cuốn chiếu cụm ba broker trong lúc đang có tải, đếm bản ghi trước và sau. Giảng viên tiêm hai sự cố nhóm kẹt, mỗi lần 10 phút; chẩn đoán và khắc phục.",
"Nâng cấp broker kế tiếp khi ISR chưa đầy lại · ước lượng đĩa mà quên hệ số nhân bản · chỉ theo dõi độ trễ mà bỏ phân vùng thiếu bản sao · khởi động lại cụm để chữa nhóm kẹt.",
"Bảng ước lượng có đủ ba đại lượng và biên, nâng cấp cuốn chiếu mất 0 bản ghi, và chẩn đoán đúng ít nhất 1/2 sự cố trong giới hạn thời gian."),

(304,"Kafka on the reference scenario - measure and record the evidence","TH","Lesson 303",
"Bài khép module, lặp lại nguyên văn yêu cầu của lesson 290 trên Kafka để M30 có hai cột số cùng đơn vị. Cùng kịch bản tham chiếu: sự kiện đơn hàng từ PostgreSQL của pipeline lesson 217, hai bên tiêu thụ độc lập, ba lỗi cài sẵn. Cùng bốn chỉ số với cùng cách đo: thông lượng ổn định trên cửa sổ năm phút sau khi bỏ một phút đầu, độ trễ đầu cuối phân vị 95, thời gian phục hồi sau khi giết tiến trình, và số thao tác để phát lại một ngày dữ liệu. Cảnh báo khi đọc hai cột: một phần chênh lệch đến từ cấu hình chứ từ bản chất công cụ, nên mỗi số phải ghi kèm cấu hình đã dùng, nếu không thì so sánh ở lesson 306 thành so sánh hai lần cấu hình khác nhau chứ hai công cụ. Phần khác biệt rõ nhất cần ghi riêng: phát lại một ngày trên Kafka là đặt lại offset, còn trên RabbitMQ phải tự dựng; ghi lại số thao tác của cả hai.",
"Dựng xong kịch bản tham chiếu trên Kafka, chạy đúng dưới cả ba lỗi cài sẵn và dưới việc giết một broker, và nộp bốn chỉ số kèm cấu hình và cách đo.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hệ chạy được và một bộ bằng chứng so sánh được với M28. Kiểm bằng rà soát chéo như lesson 290; đạt khi ≥ 3/4 số tái lập được trong sai số 20% và mỗi số có cấu hình kèm theo.",
"Dựng trọn kịch bản. Chạy dưới ba lỗi cài sẵn cộng giết một broker giữa chừng, chứng minh mart cuối không trùng không thiếu đúng thứ tự. Đo bốn chỉ số, ghi kèm cấu hình và lệnh tái lập. Đặt bảng này cạnh bảng lesson 290 và đánh dấu những ô mà chênh lệch đến từ cấu hình chứ từ công cụ.",
"Đo với cấu hình khác hẳn cấu hình đã dùng cho RabbitMQ rồi so hai cột · ghi số mà không ghi cấu hình · báo thông lượng đỉnh · bỏ qua chỉ số phát lại vì nó quá dễ trên Kafka.",
"Mart cuối đúng dưới cả bốn tình huống hỏng, bốn chỉ số có cấu hình và cách đo kèm theo, và ≥ 3/4 số tái lập được trong sai số 20%."),
]

M30 = ("Choosing a Message System", 305, 308, """| | |
|---|---|
| **Objective cấp module** | Chấm hai hệ truyền thông điệp trên sáu chiều, mỗi ô dẫn một quan sát từ lab của chính mình, và bảo vệ một lựa chọn cho đội có ràng buộc cho trước |
| **Tiền đề** | M28 · M29 |
| **Exit criterion** | Ma trận sáu chiều đạt rà soát chéo, mọi ô truy được về lab, và giữ vững hoặc đổi kết luận có lý do khi ràng buộc bị đổi giữa buổi |
| **Kỹ năng SFIA** | `ARCH` mức 4 |
| **Chế độ hỏng** | Chấm theo cảm nhận hoặc chép bảng so sánh của nhà cung cấp, cho ra kết luận không đứng vững khi ràng buộc đổi |""",
"""Module chỉ chạy được vì M28 và M29 đã dựng cùng một kịch bản tham chiếu và đo cùng bốn chỉ số ở lesson 290 và 304, cộng hai phép thử lặp lại ở lesson 288 với 296 và lesson 286 với 298. Không cùng bài toán thì đây là bài liệt kê tính năng, không phải bài so sánh, cùng ràng buộc với M18 và M25.

Ba bài đầu dựng tiêu chí và đo, bài cuối là buổi bảo vệ. Sáu chiều thay vì chín như M25 vì khối này có hai công cụ chứ ba, và vì hai chiều của M25 là mô hình hoá phụ thuộc và chạy bù không áp dụng ở đây.""")

L30 = [
(305,"Six dimensions, and how to score each from lab evidence","LT","Module 30: M28 · M29",
"Sáu chiều đánh giá và cách chuyển từng chiều thành một phép đo thực hiện được. Mô hình tiêu thụ: bên tiêu thụ mới tham gia thì thấy được gì, đo bằng phép đếm đã làm ở lesson 288 và 296. Phát lại: số thao tác và thời gian để chạy lại một ngày dữ liệu, số đã có ở lesson 290 và 304. Độ bền dưới sự cố: số bản ghi mất khi giết tiến trình, số đã có ở lesson 286 và 298. Thông lượng và độ trễ: hai số ở cùng một cấu hình so sánh được, kèm cảnh báo ở lesson 304 về chênh lệch do cấu hình. Công sức vận hành: số thành phần phải chạy, thao tác nâng cấp, và số chỉ số phải theo dõi. Kỹ năng đội: thời gian để người thứ hai sửa được một bên tiêu thụ. Nguyên tắc chấm giữ nguyên từ lesson 261: mỗi ô dẫn một quan sát có số hoặc có ảnh chụp từ lab của chính mình; ba nguồn không được dùng là bảng so sánh của nhà cung cấp, bài xếp hạng, và cảm nhận về cú pháp.",
"Phát biểu cho từng chiều trong sáu chiều một phép đo thực hiện được trên lab đã làm, kèm đơn vị đo.",
"Tầng *hiểu*. Bài dựng tiêu chí, chưa đo, nên objective dừng ở chỗ chuyển một chiều mơ hồ thành một phép đo lặp lại được. Kiểm bằng rà soát: mỗi phép đo phải nêu làm gì, đo cái gì, đơn vị là gì, và người khác lặp lại được. Chiều nào chỉ có tính từ mà không có phép đo thì không tính.",
"Với mỗi chiều, viết một phép đo gồm thao tác, đại lượng và đơn vị. Đối chiếu với số đã có ở lesson 286, 288, 290, 296, 298 và 304 xem chiều nào đã có sẵn dữ liệu và chiều nào còn thiếu. Đổi bài với một học viên khác và thử thực hiện phép đo của người kia trên lab của mình.",
"Chấm bằng tính từ như nhanh, bền, dễ dùng · lấy số liệu từ tài liệu nhà cung cấp · đặt phép đo mà chỉ người viết mới thực hiện được.",
"Sáu phép đo đều nêu đủ thao tác, đại lượng và đơn vị, người khác lặp lại được, và chỉ đúng chiều nào còn thiếu dữ liệu."),

(306,"Fan-out, replay and the past - the axis that decides most designs","TH","Lesson 305",
"Trục cho khác biệt lớn nhất giữa hai hệ, và lý do nằm ở mô hình lưu trữ chứ ở chất lượng cài đặt. Mô hình hàng đợi: lấy ra là biến mất, nên phát một nhận nhiều phải nhân bản ở phía broker và quá khứ không còn để đọc lại. Mô hình nhật ký: bản ghi nằm lại theo chính sách giữ, mỗi nhóm giữ con trỏ riêng, nên thêm bên tiêu thụ và đọc lại quá khứ là thao tác thường ngày. Hai con số đã đo ở lesson 288 và 296 là bằng chứng trực tiếp của trục này; đặt cạnh nhau và giải thích chênh lệch bằng cơ chế chứ bằng nhận xét. Ba câu hỏi vận hành dùng để đo trục: thêm một bên tiêu thụ mới tốn bao nhiêu thao tác và nó thấy được bao nhiêu quá khứ, phát lại một ngày tốn bao nhiêu thao tác, và sửa một lỗi logic rồi dựng lại dữ liệu ba tháng thì làm thế nào. Cảnh báo khi kết luận: một phần chênh lệch đến từ chính sách giữ đã chọn chứ từ công cụ, nên phải tách hai yếu tố trước khi kết luận.",
"Trả lời ba câu hỏi vận hành trên cả hai hệ bằng số đo của chính mình, và giải thích chênh lệch bằng cơ chế lưu trữ.",
"Tầng *phân tích*. Bài đòi quy chênh lệch quan sát được về nguyên nhân cơ chế, chứ ghi lại chênh lệch. Kiểm bằng bảng ba câu hỏi hai cột; đạt khi mỗi ô có số, và phần giải thích nêu đúng cơ chế chứ nêu tên công cụ.",
"Trên cả hai hệ, thực hiện ba việc: thêm một bên tiêu thụ mới và đếm số sự kiện quá khứ nó nhận được; phát lại một ngày và đếm số thao tác; dựng lại dữ liệu ba tháng sau khi sửa lỗi logic và ghi cách làm. Lập bảng hai cột. Với mỗi ô chênh lệch, viết một câu quy về cơ chế.",
"Kết luận Kafka tốt hơn mà không nêu bài toán nào · quên rằng chính sách giữ do mình đặt chứ do công cụ · so số thao tác mà không so công sức dựng ban đầu.",
"Bảng ba câu hỏi hai cột đủ số, và mỗi ô chênh lệch có một câu quy về cơ chế lưu trữ chứ về tên công cụ."),

(307,"Operational cost and the team-skill constraint","TH","Lesson 306",
"Chiều hay bị bỏ qua nhất và thường là chiều quyết định trong thực tế. Ba thành phần của công sức vận hành, đếm được chứ ước lượng: số tiến trình phải chạy và theo dõi, số thao tác trong một lần nâng cấp, và số chỉ số phải đặt cảnh báo. Dữ liệu đã có từ lesson 289 và 303. Chi phí hạ tầng ước lượng từ đĩa và bộ nhớ theo cách đã làm ở lesson 303, với lưu ý hệ số nhân bản làm đĩa nhân lên. Ràng buộc kỹ năng đội đo bằng một phép thử cụ thể: đưa một bên tiêu thụ đang chạy cho một học viên chưa làm module đó và tính thời gian tới khi họ sửa được một lỗi cho sẵn. Ba tình huống mà chiều này lật ngược kết luận của lesson 306: đội hai người không trực đêm, khối lượng dưới một nghìn sự kiện mỗi giây, và hệ chỉ có một bên tiêu thụ và không bao giờ cần phát lại. Nguyên tắc: chọn hệ mạnh hơn khả năng vận hành của đội là cách tạo ra sự cố mà không ai sửa được lúc ba giờ sáng.",
"Đo ba thành phần công sức vận hành trên cả hai hệ và chỉ ra ít nhất một tình huống mà chiều này lật ngược kết luận của chiều trước.",
"Tầng *đánh giá*. Objective đòi cân hai chiều mâu thuẫn nhau và kết luận theo ràng buộc, chứ cộng điểm. Kiểm bằng bảng đo cộng một tình huống lật ngược có lập luận; đạt khi ba thành phần đều có số và tình huống lật ngược đứng vững trước phản biện.",
"Đếm ba thành phần trên cả hai hệ. Thực hiện phép thử kỹ năng đội với một học viên chưa làm module tương ứng, tính giờ. Ước lượng chi phí hạ tầng cho cùng khối lượng. Viết một tình huống mà tổng các chiều này lật ngược kết luận của lesson 306, rồi bảo vệ nó trước hai phản biện của bạn cùng lớp.",
"Ước lượng công sức bằng cảm nhận thay vì đếm · bỏ qua ràng buộc kỹ năng đội vì khó đo · cộng điểm các chiều như nhau mà không xét ràng buộc nào là chặn.",
"Ba thành phần có số trên cả hai hệ, phép thử kỹ năng đội có kết quả tính giờ, và tình huống lật ngược đứng vững trước hai phản biện."),

(308,"The decision - defend one choice for a team with given constraints","KT","Lesson 307",
"Buổi bảo vệ, cùng khuôn với lesson 266 ở khối điều phối. Mỗi học viên nhận một hồ sơ đội có ràng buộc cụ thể gồm khối lượng, số bên tiêu thụ, nhu cầu phát lại, quy mô đội, và khả năng trực. Nộp ma trận sáu chiều đã điền từ lab của chính mình, một khuyến nghị, và phần nêu rõ điều kiện nào làm khuyến nghị đó sai. Giữa buổi hội đồng đổi một ràng buộc; học viên phải hoặc giữ kết luận với lý do, hoặc đổi kết luận với lý do, và **cả hai đều được điểm nếu lập luận dẫn từ ma trận**. Cái không được điểm là đổi kết luận mà không nêu ô nào trong ma trận đã đổi giá trị.",
"Bảo vệ được một lựa chọn cho hồ sơ đội cho trước, mọi ô trong ma trận truy được về lab của chính mình, và phản ứng đúng khi một ràng buộc bị đổi.",
"Tầng *đánh giá*. Cổng của khối, kiểm năng lực ra quyết định có bằng chứng chứ kiểm trí nhớ về tính năng. Kiểm bằng buổi bảo vệ có đổi ràng buộc giữa chừng; thang điểm ở phần Đề gồm.",
"Nhận một hồ sơ đội: khối lượng sự kiện, số bên tiêu thụ, nhu cầu phát lại, quy mô đội, ai trực khi hỏng. Bài chấm năm phần: A (25đ) ma trận sáu chiều điền đủ, mỗi ô dẫn một quan sát từ lab · B (25đ) khuyến nghị kèm ba điều kiện làm nó sai · C (25đ) phản ứng khi hội đồng đổi một ràng buộc giữa buổi · D (15đ) chỉ ra hai ô mà chênh lệch đến từ cấu hình chứ từ công cụ · E (10đ) nêu một tình huống không nên dùng broker nào cả, theo lesson 282.",
"Chép bảng so sánh của nhà cung cấp · đổi kết luận khi bị vặn mà không dẫn ô nào · bỏ phần E vì hết giờ · trình bày ma trận mà không ai kiểm được số.",
"Đạt ≥ 70/100 và phần A ≥ 60%. Ô nào không truy được về lab thì không tính điểm ô đó."),
]
