# -*- coding: utf-8 -*-
"""DE M33 Storage, file formats and the lakehouse + M34 Spark."""

M33 = ("Storage, File Formats and the Lakehouse", 329, 342, """| | |
|---|---|
| **Objective cấp module** | Chọn định dạng tệp, cách phân vùng và định dạng bảng cho một khối lượng truy vấn cho trước, và chứng minh lựa chọn bằng lượng dữ liệu thực sự được quét |
| **Tiền đề** | M32 |
| **Exit criterion** | Cùng một tập dữ liệu ở ba cách bố trí, đo được lượng byte quét và thời gian truy vấn của từng cách, và giải thích chênh lệch bằng cơ chế chứ bằng tên định dạng |
| **Kỹ năng SFIA** | `DATM` mức 4 · `HPCC` mức 3 |
| **Chế độ hỏng** | Chọn định dạng theo lời khuyên trên mạng, phân vùng theo cột có số giá trị phân biệt rất cao, rồi sinh hàng triệu tệp nhỏ và làm mọi truy vấn chậm đi |""",
"""Module trả lời một câu hỏi duy nhất ở nhiều tầng: **truy vấn này thực sự đọc bao nhiêu byte từ đĩa, và vì sao**. Định dạng tệp, cách nén, cách phân vùng và định dạng bảng đều là bốn cách trả lời khác nhau cho câu đó.

Mọi bài đo bằng cùng một đại lượng là số byte quét, nên các con số so được với nhau xuyên suốt module và dùng lại được ở M34 khi Spark đọc chính những tệp này.""")

L33 = [
(329,"Three storage models - block, file and object","LT","Module 33: M32",
"Ba mô hình lưu trữ với ba giao diện khác nhau, và chọn sai mô hình là sai ở tầng kiến trúc chứ ở tầng cấu hình. Lưu trữ khối đưa ra một dãy khối thô, hệ tệp hoặc cơ sở dữ liệu tự quản lý cấu trúc bên trên, độ trễ thấp nhất, gắn vào đúng một máy. Lưu trữ tệp đưa ra cây thư mục dùng chung qua mạng, tiện nhưng khó mở rộng. Lưu trữ đối tượng đưa ra một khoá phẳng trỏ tới một khối byte kèm siêu dữ liệu, mở rộng gần như không giới hạn, rẻ nhất trên mỗi đơn vị dung lượng, và đây là nền của mọi hồ dữ liệu. Bốn thuộc tính của lưu trữ đối tượng quyết định thiết kế phía trên nó: ghi là thay cả đối tượng chứ sửa tại chỗ, không có thao tác đổi tên thật, liệt kê thư mục tốn kém vì thư mục chỉ là tiền tố của khoá, và độ trễ mỗi yêu cầu cao hơn đĩa cục bộ hàng trăm lần. Nối lại chênh lệch đọc tuần tự và ngẫu nhiên ở M2: trên lưu trữ đối tượng, đọc một khối lớn rẻ hơn nhiều so với đọc nhiều khối nhỏ.",
"Chọn mô hình lưu trữ cho ba khối lượng công việc cho trước và nêu thuộc tính nào của mô hình quyết định lựa chọn.",
"Tầng *hiểu*. Bài mở module, nối kiến thức lưu trữ vật lý ở M2 với ba giao diện thực tế. Kiểm bằng ba khối lượng công việc; đạt khi chọn đúng cả ba và mỗi lần dẫn một thuộc tính cụ thể chứ một nhận xét chung.",
"Đo độ trễ và thông lượng của cùng một thao tác đọc 1 GB trên đĩa cục bộ và trên lưu trữ đối tượng, ở hai cách: một tệp lớn và một nghìn tệp nhỏ. Lập bảng bốn ô. Chọn mô hình cho ba khối lượng công việc gồm cơ sở dữ liệu giao dịch, kho tệp chia sẻ cho đội, và hồ dữ liệu phân tích.",
"Coi lưu trữ đối tượng như một hệ tệp bình thường · giả định đổi tên là thao tác rẻ · thiết kế cho nhiều tệp nhỏ vì trên máy cục bộ thấy không sao.",
"Bảng bốn ô có số đo thật, và ba khối lượng công việc được gán đúng mô hình kèm thuộc tính quyết định."),

(330,"Object storage semantics and what they break","LT","Lesson 329",
"Bốn thuộc tính ở lesson 329 phá vỡ ba giả định mà mã xử lý dữ liệu thường mang theo từ hệ tệp. Một là ghi tạm rồi đổi tên: mẫu phổ biến để công bố nguyên tử ở lesson 207 không dùng được vì đổi tên thực chất là sao chép rồi xoá, tốn thời gian tỉ lệ với kích thước và không nguyên tử. Hai là liệt kê để biết có gì: liệt kê một tiền tố có hàng triệu khoá tốn nhiều yêu cầu và có thể không phản ánh ngay thứ vừa ghi. Ba là sửa một phần tệp: không có, muốn đổi một dòng phải ghi lại cả đối tượng. Hệ quả trực tiếp: một công việc ghi nhiều tệp ra hồ dữ liệu rồi công bố bằng cách đổi tên thư mục sẽ **để lại trạng thái nửa chừng** nếu chết giữa chừng, và người đọc thấy bảng sai mà không có lỗi nào. Đây chính là bài toán sẽ dẫn tới định dạng bảng mở ở lesson 337. Ba cách sống chung trước khi có định dạng bảng: ghi vào thư mục tạm rồi ghi một tệp đánh dấu hoàn tất, dùng phân vùng theo ngày và chỉ công bố nguyên phân vùng, và giữ một sổ kê bên ngoài.",
"Chỉ ra trong một quy trình ghi cho trước chỗ nào giả định sai về ngữ nghĩa lưu trữ đối tượng, và nêu hậu quả quan sát được.",
"Tầng *phân tích*. Objective là truy một lỗi tiềm ẩn từ giả định sai tới biểu hiện thực tế, chuẩn bị nền cho lesson 337. Kiểm bằng ba quy trình ghi; đạt khi chỉ đúng ít nhất hai chỗ và mô tả đúng trạng thái nửa chừng.",
"Viết một công việc ghi 200 tệp ra lưu trữ đối tượng rồi công bố bằng cách đổi tên tiền tố. Giết tiến trình giữa chừng và quan sát trạng thái người đọc nhìn thấy. Đo thời gian đổi tên một tiền tố 10 GB. Cài lại bằng tệp đánh dấu hoàn tất và lặp lại thí nghiệm giết tiến trình.",
"Dùng lại mẫu ghi tạm rồi đổi tên của hệ tệp · tin rằng liệt kê luôn thấy ngay tệp vừa ghi · sửa một dòng bằng cách đọc, sửa, ghi đè mà không khoá.",
"Thí nghiệm cho thấy trạng thái nửa chừng ở bản đổi tên, bản có tệp đánh dấu không có trạng thái đó, và có số đo thời gian đổi tên."),

(331,"Row against columnar layout and why analytics reads columns","LT","Lesson 330",
"Cùng một bảng, hai cách xếp byte trên đĩa, và mọi khác biệt hiệu năng phân tích suy ra từ đó. Bố trí theo dòng gom mọi cột của một bản ghi cạnh nhau, tốt khi đọc hoặc ghi cả bản ghi, đây là cách cơ sở dữ liệu giao dịch làm và đã gặp ở M10. Bố trí theo cột gom mọi giá trị của một cột cạnh nhau, nên truy vấn chỉ dùng ba cột trong bốn mươi cột chỉ phải đọc ba, và tỉ lệ tiết kiệm bằng đúng tỉ lệ cột bỏ qua. Lợi ích thứ hai lớn không kém: giá trị cùng cột cùng kiểu và thường lặp nhiều, nên nén tốt hơn hẳn, và ít byte hơn nghĩa là ít thời gian đọc hơn. Cái giá: ghi thêm một bản ghi phải chạm vào nhiều chỗ, và đọc nguyên một bản ghi phải ghép từ nhiều nơi, nên bố trí theo cột dở cho khối lượng công việc giao dịch. Quy tắc thực dụng rút ra: kho phân tích dùng cột, hệ vận hành dùng dòng, và đây là lý do kỹ thuật cho việc tách hai hệ đã nêu ở lesson 172.",
"Dự đoán tỉ lệ byte tiết kiệm được khi chuyển một truy vấn cho trước từ bố trí dòng sang cột, rồi đối chiếu dự đoán với số đo.",
"Tầng *áp dụng*. Objective là một dự đoán định lượng kiểm được ngay bằng thực nghiệm. Kiểm bằng ba truy vấn; đạt khi dự đoán cùng bậc với số đo ở ít nhất hai trong ba.",
"Lưu cùng một bảng 40 cột ở hai định dạng dòng và cột. Với ba truy vấn dùng lần lượt 2, 8 và 40 cột, viết dự đoán tỉ lệ byte đọc trước, rồi đo thật. Lập bảng dự đoán và thực đo. Đo thêm kích thước tệp của hai định dạng.",
"Cho rằng bố trí cột luôn nhanh hơn kể cả khi đọc mọi cột · so hai định dạng ở hai mức nén khác nhau · đo thời gian mà quên đo byte đọc.",
"Bảng ba truy vấn có cả dự đoán lẫn thực đo, và dự đoán cùng bậc với thực đo ở ≥ 2/3 trường hợp."),

(332,"Parquet internals - row groups, column chunks, pages and statistics","TH","Lesson 331",
"Parquet không phải một khối byte phẳng mà là một cấu trúc phân tầng, và biết cấu trúc đó là điều kiện để giải thích mọi số đo ở ba bài sau. Tệp chia thành nhóm dòng; trong mỗi nhóm dòng, mỗi cột là một đoạn cột; mỗi đoạn cột chia thành trang, là đơn vị nén và đọc nhỏ nhất. Chân tệp chứa siêu dữ liệu: lược đồ, vị trí từng đoạn, và **thống kê giá trị nhỏ nhất, lớn nhất, số rỗng cho từng đoạn**. Thống kê này là thứ cho phép bỏ qua cả nhóm dòng mà không đọc, và đó là cơ chế thật đứng sau việc đẩy điều kiện lọc xuống ở lesson 334. Kích thước nhóm dòng là đánh đổi: nhóm lớn thì nén tốt và ít siêu dữ liệu nhưng đơn vị bỏ qua thô, nhóm nhỏ thì lọc mịn hơn nhưng chi phí siêu dữ liệu tăng. Cách đọc chân tệp bằng công cụ dòng lệnh để tự kiểm chứng mọi khẳng định trên, thay vì tin vào tài liệu.",
"Đọc được chân tệp Parquet và chỉ ra số nhóm dòng, kích thước từng đoạn cột và thống kê của cột dùng để lọc.",
"Tầng *áp dụng*. Objective là một kỹ năng khảo sát cụ thể, điều kiện cần cho ba bài sau. Kiểm bằng bài đọc tệp có đáp án; đạt khi trả lời đúng ít nhất 5/6 câu về cấu trúc tệp.",
"Ghi cùng dữ liệu ra Parquet ở ba kích thước nhóm dòng. Với mỗi tệp, đọc chân tệp và ghi lại số nhóm dòng, kích thước mỗi đoạn cột, và thống kê của cột ngày. Trả lời sáu câu hỏi về cấu trúc. Sắp xếp dữ liệu theo cột ngày rồi ghi lại và so thống kê trước sau.",
"Coi Parquet là hộp đen · đặt kích thước nhóm dòng mặc định mà không xét kích thước tệp · ghi dữ liệu chưa sắp xếp rồi thắc mắc vì sao thống kê không giúp lọc.",
"Trả lời đúng ≥ 5/6 câu, và chỉ ra được thống kê cột ngày hẹp lại rõ rệt sau khi sắp xếp."),

(333,"Compression and encoding - dictionary, run-length and the CPU trade","TH","Lesson 332",
"Hai tầng thu gọn dữ liệu và nhiều người gộp chúng làm một. Mã hoá khai thác cấu trúc của dữ liệu: từ điển thay giá trị lặp bằng chỉ số, mã hoá độ dài chuỗi lặp thay dãy giá trị giống nhau bằng cặp giá trị và số lần, mã hoá theo độ lệch cho số tăng dần. Nén là bước sau, áp lên byte đã mã hoá, và bốn thuật toán phổ biến trải trên đường đánh đổi giữa tỉ lệ nén và chi phí CPU khi giải nén. Điều quan trọng thực tế: mã hoá từ điển hiệu quả tới mức cột có ít giá trị phân biệt gần như miễn phí về dung lượng, nên **sắp xếp dữ liệu theo cột có ít giá trị phân biệt trước khi ghi** làm cả mã hoá lẫn nén tốt lên rõ rệt. Chọn thuật toán nén là chọn theo khối lượng công việc: dữ liệu đọc nhiều lần thì ưu tiên giải nén nhanh, dữ liệu lưu trữ lâu ít đọc thì ưu tiên tỉ lệ nén. Đo chứ đoán, và đo cả CPU chứ chỉ dung lượng.",
"Chọn thuật toán nén và thứ tự sắp xếp cho một khối lượng công việc, dẫn bằng bảng đo dung lượng, thời gian đọc và CPU.",
"Tầng *đánh giá*. Objective là chọn một điểm trên đường đánh đổi ba chiều từ số đo của chính mình. Kiểm bằng bảng ít nhất ba thuật toán nhân hai thứ tự sắp xếp; đạt khi có đủ ba đại lượng và lý do chọn dẫn số.",
"Ghi cùng dữ liệu với ba thuật toán nén, mỗi thuật toán ở hai trạng thái là chưa sắp xếp và đã sắp xếp theo cột ít giá trị phân biệt. Với mỗi tổ hợp, đo dung lượng tệp, thời gian đọc đầy đủ và CPU dùng khi đọc. Chọn một tổ hợp cho khối lượng công việc phân tích hằng ngày và viết ba câu bảo vệ.",
"Chọn thuật toán nén theo tỉ lệ nén mà bỏ qua CPU · ghi dữ liệu chưa sắp xếp · so dung lượng mà quên thời gian đọc · kết luận từ một tệp mẫu quá nhỏ.",
"Bảng sáu tổ hợp đủ ba đại lượng, và lý do chọn dẫn được ít nhất hai con số từ bảng."),

(334,"Predicate pushdown and partition pruning - measuring what is read","TH","Lesson 333",
"Ba tầng giảm lượng dữ liệu đọc, xếp từ thô tới mịn, và mỗi tầng dùng một cơ chế khác nhau. Cắt phân vùng dùng chính đường dẫn thư mục: điều kiện lọc trên cột phân vùng cho phép bỏ qua cả thư mục mà không mở tệp nào. Bỏ qua nhóm dòng dùng thống kê ở chân tệp tại lesson 332: điều kiện nằm ngoài khoảng nhỏ nhất tới lớn nhất thì bỏ qua cả nhóm. Cắt cột chỉ đọc đoạn cột cần dùng theo lesson 331. Ba tầng cộng lại có thể giảm lượng đọc hàng trăm lần, nhưng chỉ khi dữ liệu được bố trí phù hợp với cách truy vấn: **thống kê chỉ giúp khi dữ liệu đã sắp xếp theo cột lọc**, còn dữ liệu ngẫu nhiên thì mọi nhóm dòng đều chứa cả khoảng rộng nên không bỏ được nhóm nào. Cách kiểm chứng duy nhất đáng tin là đo số byte thực sự quét, có sẵn trong số liệu của engine, chứ nhìn thời gian chạy vì thời gian còn phụ thuộc bộ nhớ đệm.",
"Đo được số byte quét của một truy vấn và quy phần giảm về đúng tầng cơ chế nào tạo ra nó.",
"Tầng *phân tích*. Objective là phân rã một số đo tổng thành đóng góp của ba cơ chế, chứ chỉ ghi nhận truy vấn nhanh hơn. Kiểm bằng bảng bốn cách bố trí; đạt khi quy đúng phần giảm cho ít nhất ba trong bốn.",
"Lưu cùng dữ liệu ở bốn cách: không phân vùng chưa sắp xếp, không phân vùng đã sắp xếp, có phân vùng chưa sắp xếp, có phân vùng đã sắp xếp. Chạy cùng ba truy vấn trên cả bốn và đo số byte quét. Lập bảng và với mỗi ô giải thích phần giảm đến từ tầng nào.",
"Đánh giá bằng thời gian chạy có bộ nhớ đệm · phân vùng theo cột không xuất hiện trong điều kiện lọc · sắp xếp theo cột không dùng để lọc · kết luận mà không đọc số liệu byte quét của engine.",
"Bảng bốn cách bố trí nhân ba truy vấn đủ số byte quét, và quy đúng cơ chế cho ≥ 3/4 trường hợp giảm."),

(335,"The small files problem and compaction","TH","Lesson 334",
"Chế độ hỏng phổ biến nhất của hồ dữ liệu, và nó tích tụ dần nên không ai thấy cho tới khi mọi truy vấn đều chậm. Nguyên nhân sinh tệp nhỏ: công việc luồng ghi mỗi vài phút một tệp, công việc theo lô có quá nhiều phân vùng đầu ra, và phân vùng theo cột có số giá trị phân biệt quá cao. Ba chi phí, và chi phí thứ ba là chi phí ẩn: mỗi tệp là ít nhất một yêu cầu tới lưu trữ đối tượng với độ trễ cố định theo lesson 329, mỗi tệp có chân tệp riêng nên phần siêu dữ liệu tăng tỉ lệ với số tệp, và lập lịch đọc hàng triệu tệp làm chính phần điều phối của engine thành nút thắt. Dồn tệp là công việc bảo trì bắt buộc chứ tuỳ chọn: gộp nhiều tệp nhỏ thành tệp cỡ mục tiêu, thường từ 128 MB tới 1 GB tuỳ engine. Chạy dồn thế nào để người đọc không thấy trạng thái nửa chừng là bài toán mà lesson 337 sẽ giải triệt để. Chỉ số phải theo dõi: kích thước tệp trung vị theo phân vùng, chứ tổng dung lượng.",
"Đo được tác động của số tệp lên thời gian truy vấn ở cùng tổng dung lượng, và chạy dồn tệp đưa kích thước trung vị về khoảng mục tiêu.",
"Tầng *áp dụng*. Objective là một thao tác bảo trì có kết quả đo được trước và sau. Kiểm bằng cặp số đo; đạt khi kích thước trung vị về khoảng mục tiêu và thời gian truy vấn giảm có số chứng minh.",
"Tạo cùng 10 GB dữ liệu ở ba cách: 20 tệp, 2.000 tệp và 200.000 tệp. Chạy cùng truy vấn trên cả ba và đo thời gian cùng số yêu cầu tới lưu trữ. Chạy dồn tệp trên bản tệ nhất và đo lại. Đặt một chỉ số theo dõi kích thước tệp trung vị theo phân vùng.",
"Phân vùng theo cột có số giá trị phân biệt cao · để công việc luồng ghi trực tiếp vào bảng phân tích mà không dồn · theo dõi tổng dung lượng thay vì kích thước tệp · dồn tệp trong lúc có người đọc mà không có cơ chế bảo vệ.",
"Bảng ba cách có thời gian và số yêu cầu, sau khi dồn thì kích thước trung vị vào khoảng mục tiêu và thời gian truy vấn giảm có số."),

(336,"Partition layout design - choosing columns from query patterns","TH","Lesson 335",
"Phân vùng là quyết định khó sửa nhất trong bố trí dữ liệu vì đổi nó nghĩa là ghi lại toàn bộ. Nguyên tắc chọn: phân vùng theo cột **xuất hiện trong điều kiện lọc của phần lớn truy vấn**, và có số giá trị phân biệt đủ thấp để mỗi phân vùng còn đủ lớn. Hai chế độ hỏng đối xứng: quá ít giá trị phân biệt thì phân vùng khổng lồ nên cắt không được bao nhiêu; quá nhiều giá trị phân biệt thì sinh tệp nhỏ theo lesson 335. Quy tắc thực dụng để ước lượng: tổng dung lượng chia số phân vùng mong muốn phải ra kích thước tệp trong khoảng mục tiêu. Phân vùng nhiều tầng như năm rồi tháng rồi ngày: tiện cho cắt theo khoảng, nhưng mỗi tầng thêm một mức thư mục và làm liệt kê tốn hơn. Khi cột lọc có số giá trị phân biệt cao thì dùng sắp xếp hoặc gom cụm thay vì phân vùng, vì hai cách đó cho lọc mịn mà không tạo thư mục. Cách rút mẫu truy vấn từ nhật ký thật thay vì đoán, và vì sao thiết kế phân vùng phải xem lại sau sáu tháng.",
"Thiết kế bố trí phân vùng từ nhật ký truy vấn thật, ước lượng kích thước tệp trước, và chứng minh bằng số byte quét rằng nó tốt hơn bố trí cũ.",
"Tầng *sáng tạo*. Objective đòi tổng hợp mẫu truy vấn, ước lượng dung lượng và cơ chế cắt thành một thiết kế. Kiểm bằng so byte quét trước và sau trên cùng bộ truy vấn; đạt khi giảm có số và ước lượng kích thước tệp cùng bậc với thực tế.",
"Nhận nhật ký 200 truy vấn thật trên một bảng. Rút tần suất cột xuất hiện trong điều kiện lọc. Thiết kế bố trí phân vùng kèm ước lượng kích thước tệp. Ghi lại dữ liệu theo thiết kế mới, chạy lại cả 200 truy vấn, so tổng byte quét với bố trí cũ.",
"Phân vùng theo mã định danh · phân vùng bốn tầng cho bảng nhỏ · thiết kế theo trực giác mà không đọc nhật ký truy vấn · quên ước lượng kích thước tệp.",
"Tổng byte quét của 200 truy vấn giảm có số chứng minh, và kích thước tệp thực tế cùng bậc với ước lượng."),

(337,"Why a data lake needs transactions","LT","Lesson 336",
"Bài gom bốn vấn đề đã gặp rải rác thành một phát biểu duy nhất: hồ dữ liệu là một đống tệp, và đống tệp không có khái niệm phiên bản nên không có thao tác nào là nguyên tử. Bốn biểu hiện, cả bốn đã xuất hiện ở các bài trước: công việc ghi chết giữa chừng để lại tệp nửa vời và người đọc thấy bảng sai theo lesson 330; dồn tệp ở lesson 335 không chạy được an toàn khi có người đọc; sửa hoặc xoá vài dòng để tuân thủ quy định buộc ghi lại cả phân vùng; và hai công việc cùng ghi một bảng thì kết quả không xác định. Vì sao thêm một cơ sở dữ liệu vào giữa không giải được: dữ liệu vẫn nằm ở tệp, và bất kỳ ai đọc thẳng tệp đều vòng qua mọi bảo đảm. Lời giải chung của cả ba định dạng bảng mở: **thêm một tầng siêu dữ liệu trỏ tới danh sách tệp, và đổi bảng là đổi con trỏ siêu dữ liệu một cách nguyên tử**. Từ một ý đó suy ra hết các tính năng ở hai bài sau, nên hiểu ý này quan trọng hơn thuộc tên tính năng.",
"Quy bốn biểu hiện hỏng về cùng một nguyên nhân gốc, và phát biểu được cơ chế chung của định dạng bảng mở.",
"Tầng *hiểu*. Bài lý thuyết tổng hợp, người học đã gặp cả bốn biểu hiện nên đây là bài đặt tên cho thứ họ đã thấy. Kiểm bằng bài quy nguyên nhân; đạt khi quy đúng cả bốn về cùng gốc và phát biểu đúng cơ chế con trỏ.",
"Tái hiện cả bốn biểu hiện trên một bảng Parquet thường: giết công việc ghi giữa chừng, dồn tệp trong lúc đọc, xoá 100 dòng theo yêu cầu tuân thủ, và chạy hai công việc ghi song song. Với mỗi biểu hiện, ghi lại người đọc nhìn thấy gì.",
"Nghĩ bốn biểu hiện là bốn lỗi khác nhau cần bốn cách chữa · tin rằng đặt lịch chạy lệch giờ là đủ để tránh ghi song song · thêm quy ước đặt tên thay cho một tầng siêu dữ liệu.",
"Tái hiện được cả bốn biểu hiện với mô tả người đọc thấy gì, và quy đúng cả bốn về nguyên nhân không có thao tác nguyên tử."),

(338,"Open table formats - the metadata layer and atomic pointer swap","LT","Lesson 337",
"Ba định dạng bảng mở phổ biến khác nhau ở chi tiết nhưng giống nhau ở cơ chế cốt lõi, và học cơ chế thì đọc tài liệu định dạng nào cũng nhanh. Cấu trúc chung ba tầng: tệp dữ liệu vẫn là Parquet như đã học; tệp kê khai liệt kê tệp dữ liệu nào thuộc phiên bản nào, kèm thống kê ở mức tệp; và con trỏ gốc chỉ tới kê khai hiện hành. Ghi là tạo tệp dữ liệu mới, tạo kê khai mới, rồi **đổi con trỏ gốc bằng một thao tác nguyên tử**; người đọc đang đọc phiên bản cũ không bị ảnh hưởng vì tệp cũ vẫn còn. Từ cơ chế đó suy ra bốn tính năng mà không cần nhớ riêng: ảnh chụp và du hành thời gian là giữ lại các kê khai cũ; ghi đồng thời là kiểm tra con trỏ chưa đổi trước khi đổi, đúng kiểu kiểm soát đồng thời lạc quan ở lesson 105; xoá và cập nhật vài dòng là ghi tệp mới và đánh dấu tệp cũ hết hiệu lực; và thống kê ở mức tệp trong kê khai cho phép bỏ qua tệp mà không mở chân tệp.",
"Suy ra được bốn tính năng của định dạng bảng mở từ cơ chế ba tầng, thay vì liệt kê chúng như danh sách rời.",
"Tầng *hiểu*. Objective là nắm cơ chế đủ để tự suy ra tính năng, tiêu chí đã dùng cho mọi module công cụ. Kiểm bằng bài suy luận; đạt khi giải thích đúng ít nhất ba trong bốn tính năng bằng cơ chế con trỏ và kê khai.",
"Tạo một bảng ở định dạng bảng mở, ghi ba lần, và sau mỗi lần đọc thẳng tệp siêu dữ liệu để xem kê khai và con trỏ đổi ra sao. Xoá 10 dòng và quan sát tệp dữ liệu cũ vẫn còn nguyên. Chạy hai công việc ghi song song và quan sát một bên bị từ chối.",
"Học danh sách tính năng mà bỏ qua cơ chế · tin rằng xoá dòng là xoá byte ngay · nghĩ ba định dạng khác nhau về bản chất.",
"Giải thích đúng ≥ 3/4 tính năng bằng cơ chế, và quan sát được con trỏ đổi qua ba lần ghi."),

(339,"Time travel, schema evolution and partition evolution","TH","Lesson 338",
"Ba tính năng trực tiếp giải những bài toán đã tồn đọng từ các module trước. Du hành thời gian đọc bảng ở một phiên bản hoặc một thời điểm, dùng cho ba việc: đối soát lại một báo cáo cũ, khôi phục sau khi ghi sai, và chạy lại một công việc trên đúng dữ liệu nó đã thấy, thứ mà lesson 324 cần để kết quả tái lập được. Tiến hoá lược đồ thêm, xoá, đổi tên cột mà không ghi lại dữ liệu, vì kê khai ánh xạ cột theo mã định danh chứ theo vị trí; đây là lời giải cho bài toán đã đặt ở lesson 209 và 313. Tiến hoá phân vùng đổi cách phân vùng cho dữ liệu mới mà giữ nguyên dữ liệu cũ, nên sửa được quyết định phân vùng sai ở lesson 336 mà không phải ghi lại toàn bộ. Giới hạn phải biết: du hành thời gian chỉ còn trong phạm vi ảnh chụp chưa bị dọn, và dọn ảnh chụp là việc bắt buộc ở lesson 340, nên phải chọn thời gian giữ có chủ ý chứ để mặc định.",
"Dùng du hành thời gian để khôi phục sau một lần ghi sai, và đổi lược đồ cùng cách phân vùng mà không ghi lại dữ liệu cũ.",
"Tầng *áp dụng*. Objective là ba thao tác vận hành có kết quả kiểm được bằng đối soát. Kiểm bằng ba bài thực hành; đạt khi cả ba thành công và bản khôi phục khớp tuyệt đối với bản trước khi ghi sai.",
"Ghi đè nhầm một phân vùng bằng dữ liệu sai, rồi khôi phục bằng du hành thời gian và đối soát với bản đã lưu. Thêm một cột và đổi tên một cột, chứng minh không tệp dữ liệu nào được ghi lại. Đổi phân vùng từ theo tháng sang theo ngày cho dữ liệu mới và chạy truy vấn bắc qua cả hai vùng.",
"Dựa vào du hành thời gian như cơ chế sao lưu duy nhất · đổi lược đồ mà không xét bên tiêu thụ · để thời gian giữ ảnh chụp mặc định rồi mất khả năng khôi phục đúng lúc cần.",
"Bản khôi phục khớp tuyệt đối, đổi lược đồ không sinh ghi lại dữ liệu, và truy vấn bắc qua hai cách phân vùng cho kết quả đúng."),

(340,"Table maintenance - compaction, snapshot expiry and orphan files","TH","Lesson 339",
"Định dạng bảng mở giải bài toán nguyên tử nhưng sinh ba việc bảo trì mới, và bỏ cả ba là cách làm bảng chậm dần rồi tốn tiền dần. Dồn tệp vẫn cần theo lesson 335, nhưng nay chạy an toàn được vì kết quả công bố bằng đổi con trỏ. Hết hạn ảnh chụp xoá các kê khai cũ và tệp dữ liệu chỉ thuộc về chúng; không chạy thì dung lượng tăng vô hạn vì mọi phiên bản đều được giữ, chạy quá mạnh tay thì mất khả năng du hành thời gian ở lesson 339, nên thời gian giữ là một quyết định có đánh đổi phải ghi vào tài liệu. Dọn tệp mồ côi xoá tệp nằm trong kho nhưng không kê khai nào trỏ tới, thường do công việc ghi chết giữa chừng; đây là thao tác nguy hiểm nhất vì xoá nhầm là mất dữ liệu, nên luôn chạy ở chế độ liệt kê trước. Lập lịch ba việc này như một phần của hệ điều phối ở M22, có theo dõi và có cảnh báo khi chúng không chạy.",
"Lập lịch và chạy được ba việc bảo trì, đặt thời gian giữ ảnh chụp có lý do, và chứng minh dung lượng cùng thời gian truy vấn được giữ ổn định.",
"Tầng *áp dụng*. Objective là dựng một quy trình bảo trì định kỳ có số đo trước và sau. Kiểm bằng phép đo qua nhiều chu kỳ; đạt khi cả ba việc chạy tự động và dung lượng không tăng đơn điệu.",
"Chạy một công việc ghi mỗi 5 phút trong hai giờ để sinh tệp nhỏ và nhiều ảnh chụp. Đo dung lượng và thời gian truy vấn theo thời gian. Lập lịch ba việc bảo trì trong Airflow. Chạy dọn tệp mồ côi ở chế độ liệt kê trước rồi mới xoá. Đo lại và vẽ đồ thị.",
"Không lập lịch bảo trì · đặt hết hạn ảnh chụp quá ngắn rồi mất khả năng khôi phục · chạy dọn mồ côi ngay mà không liệt kê trước · dọn mồ côi trong lúc một công việc ghi đang chạy.",
"Ba việc bảo trì chạy tự động có theo dõi, đồ thị cho thấy dung lượng và thời gian truy vấn ổn định, và thời gian giữ ảnh chụp có lý do ghi lại."),

(341,"Lakehouse layout for the reference pipeline","TH","Lesson 340",
"Bài ghép: chuyển tầng lưu trữ của pipeline tham chiếu sang định dạng bảng mở và áp toàn bộ quyết định bố trí đã học. Ba tầng medallion ở lesson 198 nay có nghĩa cụ thể về mặt lưu trữ: tầng đồng giữ nguyên bản gốc bất biến, thường là định dạng nguồn; tầng bạc là bảng mở đã làm sạch, phân vùng theo ngày sự kiện; tầng vàng là bảng mở hướng nghiệp vụ, bố trí theo mẫu truy vấn thật ở lesson 336. Quyết định phải ghi lại cho từng tầng: định dạng tệp, thuật toán nén, cột phân vùng, cột sắp xếp, kích thước tệp mục tiêu, thời gian giữ ảnh chụp. Mỗi quyết định kèm lý do và số đo, vì đây là đầu vào trực tiếp cho hồ sơ kiến trúc ở M39. Luồng CDC ở M31 và công việc luồng ở M32 nay ghi vào bảng mở, nên phần dồn tệp cho dữ liệu luồng là bắt buộc và phải lập lịch.",
"Chuyển ba tầng sang định dạng bảng mở với bộ quyết định bố trí đầy đủ, và chứng minh tổng byte quét của bộ truy vấn chuẩn giảm.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một thiết kế có sáu quyết định cho ba tầng. Kiểm bằng bảng quyết định cộng số đo trước sau; đạt khi mọi ô có lý do và tổng byte quét giảm có số.",
"Chuyển ba tầng sang bảng mở. Lập bảng sáu quyết định cho từng tầng, mỗi ô kèm lý do và số đo hỗ trợ. Chạy bộ truy vấn chuẩn trước và sau, so tổng byte quét và thời gian. Lập lịch bảo trì cho cả ba tầng.",
"Áp cùng một bố trí cho cả ba tầng · quên dồn tệp cho dữ liệu từ luồng · ghi quyết định mà không ghi lý do · đo thời gian mà quên byte quét.",
"Bảng 18 ô quyết định đều có lý do, tổng byte quét của bộ truy vấn chuẩn giảm có số, và bảo trì cả ba tầng đã lập lịch."),

(342,"Choosing storage - warehouse, lake or lakehouse","DA","Lesson 341",
"Bài dự án khép module: chọn kiến trúc lưu trữ cho ba tình huống có ràng buộc khác nhau và bảo vệ bằng số đo của chính mình. Ba phương án và điểm mạnh thật của từng phương án: kho dữ liệu cho hiệu năng truy vấn ổn định và vận hành đơn giản, đổi lại chi phí trên mỗi đơn vị dung lượng cao và khó chứa dữ liệu phi cấu trúc; hồ dữ liệu cho chi phí thấp và linh hoạt định dạng, đổi lại không có bảo đảm giao dịch theo lesson 337; lakehouse ở giữa, đổi lại thêm việc bảo trì ở lesson 340 và phụ thuộc vào engine hỗ trợ định dạng bảng. Ba tình huống: một đội năm người chỉ có dữ liệu bảng và truy vấn theo ngày; một công ty có cả nhật ký thô lẫn dữ liệu bảng, khối lượng hàng chục terabyte; và một hệ phải giữ dữ liệu bảy năm cho tuân thủ nhưng chỉ truy vấn phần nóng. Yêu cầu: mỗi khuyến nghị kèm ít nhất ba số đo lấy từ lab của chính mình.",
"Đưa ra khuyến nghị lưu trữ cho ba tình huống, mỗi khuyến nghị dẫn ít nhất ba số đo từ lab và nêu điều kiện làm nó sai.",
"Tầng *đánh giá*. Bài dự án đo năng lực ra quyết định kiến trúc có bằng chứng, chuẩn bị cho M39. Kiểm bằng rà soát chéo giữa học viên; đạt khi mọi số truy được về lab và mỗi khuyến nghị có điều kiện đảo ngược.",
"Với ba tình huống cho trước, viết khuyến nghị kèm bảng số đo trích từ các lab trong module. Mỗi khuyến nghị nêu hai điều kiện làm nó sai. Rà soát chéo với một học viên khác: họ chọn một số bất kỳ trong bài bạn và bạn phải chỉ ra lab nào sinh ra số đó.",
"Khuyến nghị lakehouse cho mọi tình huống · dẫn số từ tài liệu nhà cung cấp · bỏ qua chi phí vận hành bảo trì · viết điều kiện đảo ngược chung chung.",
"Ba khuyến nghị đều có ≥ 3 số đo truy được về lab, mỗi khuyến nghị có hai điều kiện đảo ngược cụ thể, và qua được rà soát chéo."),
]

M34 = ("Spark and Distributed Processing", 343, 356, """| | |
|---|---|
| **Objective cấp module** | Viết, chẩn đoán và tối ưu được công việc Spark trên dữ liệu vượt bộ nhớ một máy, và giải thích mọi tối ưu bằng kế hoạch thực thi chứ bằng kinh nghiệm truyền miệng |
| **Tiền đề** | M33 |
| **Exit criterion** | Ba công việc chậm cho sẵn được chẩn đoán đúng nút thắt và sửa đạt ngưỡng hiệu năng, mỗi lần dẫn bằng kế hoạch thực thi và số liệu |
| **Kỹ năng SFIA** | `HPCC` mức 4 · `PROG` mức 4 |
| **Chế độ hỏng** | Học API DataFrame rồi coi Spark là pandas chạy trên cụm, nên không hiểu xáo trộn và đổ lỗi mọi chuyện cho thiếu bộ nhớ |""",
"""Mức `A`. Module đọc chính những tệp đã bố trí ở M33, nên mọi số đo byte quét ở đó dùng lại được ở đây.

Lesson 354 dạy Structured Streaming ở mức đầy đủ. Lesson 327 ở M32 đã đối chiếu mô hình lô vi mô ở mức khái niệm khi chưa có Spark; bài này là chỗ trả nợ phần nội bộ.""")

L34 = [
(343,"When not to distribute - one big machine against a cluster","LT","Module 34: M33",
"Bài mở module bằng câu hỏi ngược, và đây là câu hỏi mà phần lớn tài liệu bỏ qua. Một máy hiện nay có thể có hàng trăm gigabyte bộ nhớ và đĩa thể rắn rất nhanh, nên dữ liệu dưới vài trăm gigabyte thường xử lý trên một máy nhanh hơn và rẻ hơn một cụm, vì không có chi phí truyền qua mạng và không có chi phí vận hành cụm. Bốn chi phí của phân tán mà người mới hay bỏ qua: truyền dữ liệu qua mạng chậm hơn đọc bộ nhớ nhiều bậc, cần đồng bộ giữa các nút, gỡ lỗi khó hơn hẳn vì lỗi xảy ra ở một nút trong nhiều nút, và phải vận hành thêm một hệ. Ba dấu hiệu cho thấy thật sự cần phân tán: dữ liệu vượt bộ nhớ và đĩa một máy, thời gian xử lý một máy vượt cửa sổ cho phép, hoặc cần chịu lỗi khi một máy chết. Mô hình chia rồi gộp và giới hạn của nó: phần việc không chia được sẽ đặt trần cho mọi nỗ lực thêm máy.",
"Quyết định có cần phân tán hay không cho bốn khối lượng công việc cho trước, dẫn bằng ước lượng dung lượng và thời gian.",
"Tầng *đánh giá*. Objective là một quyết định kiến trúc có ràng buộc rõ, và là chỗ nhiều đội sai ngay từ đầu. Kiểm bằng bốn khối lượng công việc trong đó ít nhất một không nên phân tán; đạt khi quyết định đúng ít nhất ba và nhận ra trường hợp không nên phân tán.",
"Chạy cùng một phép biến đổi trên 50 GB bằng một máy lớn và bằng cụm bốn nút, đo thời gian và chi phí ước tính. Lặp lại với 5 GB. Cho bốn khối lượng công việc và quyết định phân tán hay không, kèm ước lượng.",
"Dùng cụm vì dữ liệu nghe có vẻ lớn · bỏ qua chi phí vận hành khi so · quên rằng phần không chia được đặt trần cho việc thêm máy.",
"Quyết định đúng ≥ 3/4 khối lượng công việc kèm ước lượng, và nhận ra đúng trường hợp một máy thắng."),

(344,"Architecture - driver, executor and where your code actually runs","LT","Lesson 343",
"Hiểu nhầm phổ biến nhất khi mới học Spark là nghĩ mã chạy ở một chỗ. Thực tế có hai nơi: trình điều khiển chạy phần dựng kế hoạch và điều phối, trình thực thi chạy phần xử lý dữ liệu thật trên từng phần dữ liệu. Hệ quả trực tiếp và hay gây lỗi: biến khai báo ở trình điều khiển được sao chép sang trình thực thi chứ dùng chung, nên gán vào một biến bên trong hàm xử lý không có tác dụng gì ở trình điều khiển; và gọi một thao tác thu về trên dữ liệu lớn sẽ kéo toàn bộ về trình điều khiển rồi làm nó chết. Trình quản lý cụm cấp tài nguyên và có nhiều lựa chọn, trong đó Kubernetes ở M36. Phân vùng là đơn vị song song: một phân vùng do một lõi xử lý tại một thời điểm, nên số phân vùng đặt trần cho mức song song đúng như số phân vùng Kafka ở lesson 293. Biến phát tán và bộ đếm là hai cơ chế chính thức để chia sẻ dữ liệu giữa hai nơi.",
"Chỉ ra với một đoạn mã cho trước phần nào chạy ở trình điều khiển, phần nào ở trình thực thi, và dự đoán lỗi nếu nhầm.",
"Tầng *phân tích*. Objective là truy hành vi lỗi về mô hình thực thi, kỹ năng nền cho mọi bài gỡ lỗi sau. Kiểm bằng năm đoạn mã trong đó ba đoạn có lỗi do nhầm nơi chạy; đạt khi chỉ đúng ít nhất bốn.",
"Cho năm đoạn mã. Với mỗi đoạn, đánh dấu phần chạy ở đâu và dự đoán kết quả. Chạy thật và so với dự đoán. Chạy một thao tác thu về trên bảng 20 GB và quan sát trình điều khiển chết, đọc thông báo lỗi.",
"Dùng biến đếm thường trong hàm xử lý · gọi thu về để xem dữ liệu · nghĩ trình điều khiển cũng xử lý dữ liệu · nhầm số lõi với số phân vùng.",
"Chỉ đúng ≥ 4/5 đoạn mã kèm dự đoán khớp thực tế, và mô tả đúng thông báo lỗi khi trình điều khiển hết bộ nhớ."),

(345,"DataFrame, the lazy plan and the catalyst optimiser","TH","Lesson 344",
"Spark không chạy ngay khi gọi phép biến đổi mà dựng một kế hoạch, và chỉ chạy khi gặp một thao tác hành động. Tính trễ là thứ cho phép bộ tối ưu nhìn toàn bộ chuỗi rồi sắp xếp lại, ví dụ đẩy điều kiện lọc xuống sát nguồn để tận dụng cắt phân vùng ở lesson 334. Bốn giai đoạn của kế hoạch: kế hoạch logic chưa phân giải, kế hoạch logic đã phân giải, kế hoạch logic đã tối ưu, và kế hoạch vật lý. Đọc được bốn giai đoạn này là kỹ năng chẩn đoán chính của cả module. Vì sao DataFrame nhanh hơn RDD cho phần lớn việc: bộ tối ưu hiểu được cấu trúc nên tối ưu được, còn với RDD thì mã người dùng là hộp đen. Hệ quả tương tự cho hàm do người dùng định nghĩa: nó chặn tối ưu và buộc chuyển đổi dữ liệu qua lại, nên thường chậm hơn hàm dựng sẵn nhiều lần, đúng cảnh báo sẽ đo ở lesson 352.",
"Đọc kế hoạch thực thi và chỉ ra bộ tối ưu đã đẩy điều kiện lọc xuống đâu, cắt cột nào, và vì sao.",
"Tầng *áp dụng*. Objective là một kỹ năng đọc cụ thể, điều kiện cần cho mọi bài tối ưu sau. Kiểm bằng ba truy vấn có kế hoạch khác nhau; đạt khi đọc đúng vị trí đẩy lọc và cắt cột ở cả ba.",
"Với ba truy vấn trên bảng ở M33, in cả bốn giai đoạn kế hoạch. Với mỗi truy vấn, chỉ ra điều kiện lọc được đẩy xuống đâu và những cột nào bị cắt. Viết lại một truy vấn bằng hàm do người dùng định nghĩa và so kế hoạch cùng thời gian chạy với bản dùng hàm dựng sẵn.",
"Đọc kế hoạch logic mà tưởng là kế hoạch vật lý · viết hàm tự định nghĩa cho việc hàm dựng sẵn làm được · gọi một hành động giữa chuỗi biến đổi rồi tự cắt mất cơ hội tối ưu.",
"Đọc đúng vị trí đẩy lọc và cắt cột ở cả ba truy vấn, và có số đo chênh lệch giữa hàm tự định nghĩa và hàm dựng sẵn."),

(346,"Transformations, actions and the shuffle boundary","TH","Lesson 345",
"Phép biến đổi chia làm hai loại theo việc dữ liệu có phải đi qua mạng hay không, và ranh giới này quyết định gần như toàn bộ hiệu năng. Biến đổi hẹp như lọc hay thêm cột xử lý trong một phân vùng, không cần dữ liệu từ phân vùng khác, nên chạy song song hoàn toàn và ghép chuỗi lại được. Biến đổi rộng như gộp nhóm, kết bảng, sắp xếp cần gom dữ liệu cùng khoá về một chỗ, và đó là xáo trộn: ghi ra đĩa, truyền qua mạng, đọc lại. Spark chia công việc thành các giai đoạn tại mỗi ranh giới xáo trộn, nên **đếm số giai đoạn trong kế hoạch là cách nhanh nhất để biết có bao nhiêu lần xáo trộn**. Nguyên tắc thiết kế rút ra: lọc càng sớm càng tốt để ít dữ liệu đi qua xáo trộn; gộp hai phép gộp nhóm thành một nếu cùng khoá; tránh sắp xếp toàn cục nếu chỉ cần thứ tự trong nhóm. Đọc giao diện Spark để thấy số giai đoạn, số tác vụ và dữ liệu xáo trộn của từng giai đoạn.",
"Đếm số lần xáo trộn của một truy vấn từ kế hoạch, và viết lại truy vấn để giảm số đó mà giữ nguyên kết quả.",
"Tầng *áp dụng*. Objective là một phép biến đổi mã có kết quả đo được bằng số giai đoạn và dữ liệu xáo trộn. Kiểm bằng ba truy vấn; đạt khi giảm được số xáo trộn ở ít nhất hai mà kết quả vẫn khớp tuyệt đối.",
"Với ba truy vấn cho sẵn, đếm số giai đoạn và đo dung lượng xáo trộn từ giao diện Spark. Viết lại từng truy vấn để giảm xáo trộn, đo lại, và đối soát kết quả với bản gốc.",
"Sắp xếp toàn cục khi chỉ cần thứ tự trong nhóm · gộp nhóm nhiều lần trên cùng khoá · đánh giá bằng thời gian chạy mà không xem dung lượng xáo trộn.",
"Giảm được số lần xáo trộn ở ≥ 2/3 truy vấn với kết quả khớp tuyệt đối, kèm số đo dung lượng xáo trộn trước và sau."),

(347,"Reading the Spark UI and the physical plan","TH","Lesson 346",
"Giao diện Spark là nguồn sự thật duy nhất khi chẩn đoán, và biết đọc nó phân biệt người tối ưu có căn cứ với người đổi tham số theo cảm tính. Năm chỗ phải biết xem: danh sách công việc và giai đoạn để thấy giai đoạn nào tốn thời gian; biểu đồ thời gian của các tác vụ trong một giai đoạn để thấy phân bố có lệch không; số liệu dung lượng đọc, ghi và xáo trộn của từng giai đoạn; kế hoạch vật lý kèm số liệu thực tế; và trang trình thực thi để thấy bộ nhớ cùng thời gian dọn rác. Ba dấu hiệu đọc được ngay từ biểu đồ thời gian tác vụ: phân bố đều thì hệ khoẻ, một tác vụ dài hẳn thì lệch dữ liệu ở lesson 349, nhiều tác vụ rất ngắn thì tệp nhỏ hoặc quá nhiều phân vùng. Nguyên tắc chẩn đoán: bắt đầu từ giai đoạn tốn thời gian nhất, rồi mới đi vào tác vụ, chứ đoán từ mã.",
"Từ giao diện Spark của một công việc chậm, định vị giai đoạn tốn nhất và phân loại hình dạng phân bố tác vụ thành một trong ba dấu hiệu.",
"Tầng *phân tích*. Objective là kỹ năng chẩn đoán từ dữ liệu quan sát, dùng lại ở ba bài sau. Kiểm bằng ba công việc chậm; đạt khi định vị đúng giai đoạn ở cả ba và phân loại đúng dấu hiệu ở ít nhất hai.",
"Chạy ba công việc chậm cho sẵn, mỗi công việc một nguyên nhân. Với mỗi công việc, chụp lại năm chỗ trong giao diện, định vị giai đoạn tốn nhất, và phân loại hình dạng phân bố tác vụ. Chưa sửa, chỉ chẩn đoán.",
"Đoán nguyên nhân từ mã mà không mở giao diện · nhìn tổng thời gian mà không xem phân bố tác vụ · bỏ qua số liệu dung lượng xáo trộn.",
"Định vị đúng giai đoạn tốn nhất ở cả ba công việc và phân loại đúng dấu hiệu ở ≥ 2/3."),

(348,"The shuffle - why it dominates cost","TH","Lesson 347",
"Xáo trộn là thao tác đắt nhất trong Spark và hiểu cơ chế của nó giải thích phần lớn các mẹo tối ưu. Ba pha: bên ghi phân loại dữ liệu theo khoá đích rồi ghi ra đĩa cục bộ; dữ liệu truyền qua mạng; bên đọc gom các mảnh cùng khoá lại. Bốn chi phí cộng dồn: tuần tự hoá, ghi đĩa, truyền mạng, và đọc cùng gộp. Số phân vùng sau xáo trộn là tham số quan trọng nhất và mặc định thường sai với dữ liệu thật: quá ít thì mỗi phân vùng quá lớn nên tràn ra đĩa, quá nhiều thì sinh hàng loạt tác vụ rất ngắn và chi phí lập lịch át phần xử lý. Quy tắc ước lượng: dung lượng xáo trộn chia số phân vùng nên ra khoảng vài trăm megabyte mỗi phân vùng. Thực thi truy vấn thích ứng có thể tự gộp phân vùng sau xáo trộn dựa trên số liệu thật lúc chạy, nên bật nó lên giải được phần lớn trường hợp đặt tham số sai, nhưng vẫn phải hiểu để chẩn đoán khi nó không giúp.",
"Chọn số phân vùng sau xáo trộn từ ước lượng dung lượng, và định lượng mức cải thiện so với giá trị mặc định.",
"Tầng *áp dụng*. Objective là một quyết định tham số có căn cứ ước lượng, kiểm được bằng đo đạc. Kiểm bằng bảng bốn giá trị; đạt khi có đường cong, giá trị chọn gần tối ưu và giải thích được hai đầu đường cong.",
"Chạy một công việc có xáo trộn lớn ở bốn giá trị số phân vùng, đo thời gian, dung lượng tràn ra đĩa và số tác vụ. Vẽ đường cong. Bật thực thi truy vấn thích ứng và đo lại, so với giá trị tốt nhất tự chọn.",
"Để số phân vùng mặc định cho mọi công việc · tăng số phân vùng rất lớn để cho chắc · bỏ qua dung lượng tràn ra đĩa khi đánh giá.",
"Bảng bốn giá trị đủ ba đại lượng, giá trị chọn nằm gần điểm tối ưu của đường cong, và có số so với chế độ thích ứng."),

(349,"Data skew - diagnosis and four remedies","TH","Lesson 348",
"Nguyên nhân số một khiến công việc chạy lâu bất thường, và đã được nhắc tới hai lần ở lesson 293 và 326 dưới dạng khác. Biểu hiện trên giao diện rất đặc trưng: 199 tác vụ xong trong hai phút còn một tác vụ chạy năm tiếng. Nguyên nhân là phân bố khoá lệch, thường do giá trị rỗng gom về một phân vùng, một khách hàng lớn chiếm phần lớn giao dịch, hoặc một giá trị mặc định được dùng cho mọi bản ghi thiếu dữ liệu. Chẩn đoán bằng cách đếm số bản ghi theo khoá và xem phân vị cao nhất, chứ nhìn tổng. Bốn cách chữa và cái giá của từng cách: thêm muối vào khoá rồi gộp hai bước, tách riêng khoá nóng xử lý bằng kết phát tán, lọc bỏ giá trị rỗng trước khi kết nếu nghiệp vụ cho phép, và bật xử lý lệch tự động của chế độ thích ứng. Nguyên tắc: **thêm máy không chữa được lệch dữ liệu**, vì một khoá vẫn phải nằm trên một nút, và đây là điều cần nói rõ khi ai đó đề nghị tăng cụm.",
"Chẩn đoán lệch dữ liệu từ giao diện, định lượng mức lệch bằng phân bố khoá, và chữa bằng một trong bốn cách kèm số đo cải thiện.",
"Tầng *phân tích*. Objective đòi truy từ triệu chứng về phân bố dữ liệu rồi chọn cách chữa phù hợp với ràng buộc nghiệp vụ. Kiểm bằng công việc lệch tiêm sẵn; đạt khi định lượng đúng mức lệch và thời gian chạy giảm ít nhất một nửa.",
"Nhận một công việc kết bảng có khoá lệch. Đếm phân bố khoá và ghi tỉ lệ của khoá lớn nhất. Thử cả bốn cách chữa, mỗi cách đo thời gian và ghi hạn chế của nó. Chứng minh bằng thực nghiệm rằng tăng gấp đôi số trình thực thi gần như không cải thiện.",
"Tăng tài nguyên để chữa lệch · thêm muối mà quên bước gộp thứ hai nên sai kết quả · lọc bỏ giá trị rỗng mà không hỏi nghiệp vụ · kết luận lệch từ tổng thời gian mà không xem phân bố tác vụ.",
"Mức lệch được định lượng bằng phân bố khoá, ít nhất một cách chữa giảm thời gian ≥ 50% với kết quả khớp, và có số chứng minh thêm máy không giúp."),

(350,"Joins - broadcast, sort-merge and choosing between them","TH","Lesson 349",
"Ba chiến lược kết trong Spark với ba điều kiện áp dụng khác nhau. Kết phát tán gửi bảng nhỏ tới mọi trình thực thi rồi kết cục bộ, **không có xáo trộn**, nên nhanh hơn nhiều bậc; điều kiện là bảng nhỏ phải vừa bộ nhớ trình thực thi. Kết sắp xếp gộp xáo trộn cả hai bảng theo khoá rồi gộp, là mặc định cho hai bảng lớn. Kết băm xáo trộn dựng bảng băm phía một bên, dùng khi một bên nhỏ hơn đáng kể nhưng vẫn quá lớn để phát tán. Spark chọn dựa trên ước lượng kích thước, và ước lượng sai là nguyên nhân phổ biến làm công việc chậm: thống kê cũ hoặc bảng sinh từ phép biến đổi phức tạp thì ước lượng lệch xa. Ba cách can thiệp: cập nhật thống kê bảng, đặt gợi ý kết trong truy vấn, và chỉnh ngưỡng phát tán. Cảnh báo: phát tán bảng quá lớn làm trình thực thi hết bộ nhớ, nên gợi ý là dao hai lưỡi và phải kèm số đo kích thước thật.",
"Đọc kế hoạch để biết Spark chọn chiến lược kết nào, đánh giá lựa chọn đó đúng hay sai bằng kích thước thật, và can thiệp khi sai.",
"Tầng *đánh giá*. Objective đòi phán đoán về quyết định của bộ tối ưu chứ chấp nhận nó. Kiểm bằng ba phép kết trong đó một phép bộ tối ưu chọn sai; đạt khi nhận ra trường hợp chọn sai và can thiệp cho kết quả nhanh hơn.",
"Chạy ba phép kết với kích thước bảng khác nhau, đọc kế hoạch để biết chiến lược được chọn, và đo thời gian. Với phép kết mà bộ tối ưu chọn sai, cập nhật thống kê rồi đo lại; nếu vẫn sai thì đặt gợi ý. Thử phát tán một bảng quá lớn và ghi lại lỗi.",
"Đặt gợi ý phát tán mà không đo kích thước bảng · để thống kê cũ · tăng ngưỡng phát tán rất cao cho chắc · kết luận chiến lược từ tên phép kết trong mã.",
"Đọc đúng chiến lược ở cả ba phép kết, can thiệp đúng chỗ bộ tối ưu chọn sai và có số cải thiện, và mô tả đúng lỗi khi phát tán bảng quá lớn."),

(351,"Partitioning, bucketing and file layout for Spark","TH","Lesson 350",
"Bài nối M33 với M34: bố trí dữ liệu trên đĩa quyết định Spark phải làm bao nhiêu việc. Ba khái niệm dễ lẫn nhau: phân vùng trên đĩa là thư mục theo giá trị cột, phân vùng trong bộ nhớ là đơn vị song song lúc chạy, và gom cụm là chia dữ liệu theo băm của khoá thành số tệp cố định khi ghi. Gom cụm giải một bài toán cụ thể: hai bảng cùng gom cụm theo cùng khoá và cùng số cụm thì kết được mà **không cần xáo trộn**, nên phép kết lặp đi lặp lại giữa hai bảng lớn rẻ hẳn đi. Cái giá: ghi tốn hơn, và mọi bên ghi phải tuân cùng quy ước. Điều chỉnh số phân vùng trong bộ nhớ bằng hai cách khác nhau về bản chất: gộp lại không xáo trộn nhưng có thể để phân bố lệch, chia lại có xáo trộn nhưng cho phân bố đều. Quy tắc chọn kích thước tệp đầu ra để tránh vấn đề tệp nhỏ ở lesson 335.",
"Thiết kế bố trí đầu ra cho một chuỗi công việc nối nhau sao cho phép kết lặp lại không phải xáo trộn, và đo mức tiết kiệm.",
"Tầng *sáng tạo*. Objective đòi thiết kế bố trí phục vụ một mẫu truy vấn tương lai chứ tối ưu một truy vấn đơn lẻ. Kiểm bằng so số lần xáo trộn và thời gian trước sau; đạt khi phép kết hết xáo trộn và kích thước tệp trong khoảng mục tiêu.",
"Hai bảng lớn được kết với nhau trong năm công việc khác nhau. Ghi lại chúng có gom cụm theo khoá kết, rồi chạy lại cả năm công việc và đo tổng thời gian cùng dung lượng xáo trộn. So chi phí ghi thêm với phần tiết kiệm. Thử gộp lại và chia lại rồi so phân bố phân vùng.",
"Nhầm phân vùng trên đĩa với phân vùng trong bộ nhớ · gom cụm với số cụm khác nhau giữa hai bảng nên vẫn xáo trộn · dùng gộp lại rồi để phân bố lệch nặng.",
"Phép kết sau khi gom cụm không còn xáo trộn có số chứng minh, và bảng so chi phí ghi thêm với phần tiết kiệm qua năm công việc."),

(352,"Caching, persistence and when it hurts","TH","Lesson 351",
"Giữ lại kết quả trung gian trong bộ nhớ giúp khi cùng một kết quả được dùng nhiều lần, và hại khi không phải vậy. Cơ chế: đánh dấu giữ lại thì lần hành động đầu tiên tính xong sẽ lưu, các lần sau đọc lại thay vì tính lại. Các mức lưu trữ và đánh đổi: chỉ bộ nhớ thì nhanh nhất nhưng thiếu chỗ là mất và phải tính lại, bộ nhớ và đĩa thì an toàn hơn nhưng chậm hơn, có tuần tự hoá thì tốn ít bộ nhớ hơn và tốn CPU hơn. Ba tình huống giữ lại là sai: dữ liệu chỉ dùng một lần, dữ liệu quá lớn nên đẩy thứ khác ra khỏi bộ nhớ, và chuỗi biến đổi rẻ tới mức tính lại còn nhanh hơn đọc lại. Quan hệ với điểm kiểm tra: giữ lại vẫn phụ thuộc vào dòng dõi nên mất bộ nhớ thì tính lại được, còn đặt điểm kiểm tra cắt hẳn dòng dõi và ghi ra kho bền, dùng khi chuỗi biến đổi quá dài. Luôn giải phóng khi không dùng nữa, vì bộ nhớ bị giữ là bộ nhớ lấy mất của phép xáo trộn.",
"Quyết định có nên giữ lại một kết quả trung gian hay không dựa trên số lần dùng và chi phí tính lại, kèm số đo cả hai chiều.",
"Tầng *đánh giá*. Objective đòi cân nhắc chứ áp dụng một quy tắc, vì giữ lại sai làm chậm đi. Kiểm bằng ba tình huống trong đó ít nhất một không nên giữ lại; đạt khi quyết định đúng cả ba và có số đo chứng minh.",
"Với ba chuỗi công việc khác nhau, đo thời gian có và không có giữ lại, và đo cả ảnh hưởng lên bộ nhớ dành cho xáo trộn. Với tình huống không nên giữ lại, định lượng phần chậm đi. Thử ba mức lưu trữ trên cùng dữ liệu.",
"Giữ lại mọi DataFrame trung gian theo thói quen · giữ lại dữ liệu quá lớn rồi làm xáo trộn tràn đĩa · quên giải phóng · đánh giá chỉ bằng thời gian lần chạy thứ hai.",
"Ba quyết định đúng kèm số đo, phần chậm đi của trường hợp giữ lại sai được định lượng, và có bảng so ba mức lưu trữ."),

(353,"Memory management and reading an out-of-memory failure","TH","Lesson 352",
"Bộ nhớ một trình thực thi chia thành các vùng có mục đích khác nhau, và biết vùng nào hết mới sửa đúng chỗ. Vùng thực thi phục vụ xáo trộn, kết và sắp xếp; vùng lưu trữ phục vụ dữ liệu giữ lại ở lesson 352; hai vùng này mượn lẫn nhau được nhưng có mức sàn. Ngoài ra còn bộ nhớ ngoài vùng quản lý cho thư viện gốc và cho mã Python, thứ thường bị quên khi đặt cấu hình. Bốn nguyên nhân hết bộ nhớ và cách phân biệt qua thông báo lỗi: một phân vùng quá lớn do lệch dữ liệu ở lesson 349, phát tán bảng quá lớn ở lesson 350, thu về dữ liệu lớn ở trình điều khiển theo lesson 344, và giữ lại quá nhiều. Tràn ra đĩa là cơ chế tự bảo vệ chứ lỗi: nó làm chậm nhưng cứu công việc, nên thấy tràn là tín hiệu cần chỉnh chứ cần báo động. Cách đọc thông báo lỗi để biết hết bộ nhớ ở trình điều khiển hay trình thực thi, và ở vùng nào.",
"Từ một thông báo lỗi hết bộ nhớ, quy về đúng một trong bốn nguyên nhân và sửa đúng cấu hình hoặc đúng mã.",
"Tầng *phân tích*. Objective là chẩn đoán từ thông báo lỗi, kỹ năng dùng trực tiếp khi trực. Kiểm bằng bốn sự cố tiêm sẵn tính giờ; đạt khi quy đúng ít nhất ba và sửa được ít nhất hai mà không chỉ tăng bộ nhớ.",
"Giảng viên tiêm bốn công việc hết bộ nhớ vì bốn nguyên nhân khác nhau, mỗi lần 12 phút. Với mỗi lần, đọc thông báo lỗi, quy nguyên nhân, sửa, và ghi lại đã sửa bằng cách nào. Đo dung lượng tràn đĩa trước và sau ở một công việc.",
"Tăng bộ nhớ cho mọi lỗi hết bộ nhớ · quên bộ nhớ ngoài vùng quản lý khi chạy Python · coi tràn ra đĩa là lỗi cần loại bỏ hoàn toàn.",
"Quy đúng ≥ 3/4 nguyên nhân, và ≥ 2/4 trường hợp được sửa bằng cách khác chứ chỉ tăng bộ nhớ."),

(354,"Structured Streaming - the micro-batch engine in depth","TH","Lesson 353",
"Bài trả nợ phần nội bộ mà lesson 327 chỉ đối chiếu ở mức khái niệm. Mô hình bảng không giới hạn: luồng đến được xem như các dòng liên tục thêm vào một bảng, và truy vấn chạy trên bảng đó như truy vấn theo lô, nên phần lớn API dùng chung với xử lý lô. Cơ chế thực thi theo lô vi mô: engine chia luồng thành các lô nhỏ, mỗi lô là một công việc Spark đầy đủ với các giai đoạn và xáo trộn như đã học, và đây là lý do độ trễ sàn bị neo vào chu kỳ lô. Bốn khái niệm ở M32 ánh xạ sang đâu: thời gian sự kiện và dấu nước khai báo trực tiếp, cửa sổ dùng cùng cú pháp với lô, trạng thái giữ trong kho trạng thái của trình thực thi, và điểm kiểm tra ghi ra kho bền cùng offset nguồn đúng nguyên tắc ở lesson 321. Ba chế độ xuất và điều kiện dùng. Bên ghi cho đúng một lần đòi đích bất biến, đúng kết luận đã rút ở lesson 322.",
"Cài đặt một công việc Structured Streaming có trạng thái, chỉ ra bốn khái niệm của M32 nằm ở đâu, và đo độ trễ sàn theo chu kỳ lô.",
"Tầng *áp dụng*. Objective là chuyển ngữ nghĩa đã nắm ở M32 sang một engine cụ thể, có đối chứng sẵn từ lesson 327. Kiểm bằng so kết quả với bản Flink và bảng độ trễ; đạt khi kết quả nghiệp vụ khớp và ánh xạ bốn khái niệm đúng cả bốn.",
"Cài lại công việc ở lesson 319 bằng Structured Streaming, chạy trên cùng dữ liệu và đối soát với kết quả bản Flink. Chỉ ra vị trí của bốn khái niệm trong mã và trong cấu hình. Đo độ trễ đầu cuối ở ba chu kỳ lô. Giết tiến trình và khôi phục từ điểm kiểm tra, đối soát.",
"Coi Structured Streaming là engine luồng thuần · quên cấu hình điểm kiểm tra ra kho bền · dùng chế độ xuất sai với phép gộp có trạng thái · so độ trễ với Flink mà không nêu chu kỳ lô.",
"Kết quả nghiệp vụ khớp bản Flink, bốn khái niệm được định vị đúng, và bảng độ trễ ba chu kỳ lô có số."),

(355,"Cluster sizing, dynamic allocation and cost","TH","Lesson 354",
"Ước lượng quy mô cụm từ bốn đại lượng: dung lượng dữ liệu đọc, tỉ lệ phình khi giải nén và chuyển sang biểu diễn trong bộ nhớ, dung lượng xáo trộn, và cửa sổ thời gian cho phép. Hai cách chia sai phổ biến và hệ quả: nhiều trình thực thi rất nhỏ thì chi phí lập lịch và bản sao dữ liệu phát tán tăng; ít trình thực thi rất lớn thì dọn rác lâu và một trình thực thi chết mất nhiều việc. Khoảng hợp lý cho số lõi mỗi trình thực thi và lý do. Cấp phát động thêm bớt trình thực thi theo nhu cầu thật, tiết kiệm rõ với công việc có tải không đều, nhưng cần dịch vụ xáo trộn ngoài để dữ liệu xáo trộn không mất khi trình thực thi bị thu hồi. Máy giá thấp có thể bị thu hồi giữa chừng: rẻ hơn nhiều nhưng chỉ dùng được khi công việc chịu được mất trình thực thi, nên hợp với xử lý lô và không hợp với luồng độ trễ thấp. Tính chi phí cho một lần chạy và so các cấu hình bằng tiền chứ bằng thời gian.",
"Ước lượng cấu hình cụm cho một công việc cho trước và so ba cấu hình bằng cả thời gian lẫn chi phí tiền.",
"Tầng *đánh giá*. Objective đòi tối ưu theo hai mục tiêu mâu thuẫn là thời gian và tiền, chứ chỉ theo thời gian. Kiểm bằng bảng ba cấu hình; đạt khi có cả hai đại lượng và lựa chọn nêu rõ đang tối ưu theo mục tiêu nào.",
"Ước lượng cấu hình cho một công việc đọc 500 GB. Chạy ba cấu hình khác nhau về số và kích thước trình thực thi, đo thời gian và tính chi phí. Bật cấp phát động trên công việc có tải không đều và đo tiết kiệm. Chạy một lần trên máy giá thấp và ghi lại chuyện gì xảy ra khi một trình thực thi bị thu hồi.",
"Chọn cấu hình chỉ theo thời gian chạy · dùng trình thực thi rất lớn cho chắc · bật cấp phát động mà không có dịch vụ xáo trộn ngoài · dùng máy giá thấp cho công việc luồng.",
"Bảng ba cấu hình có cả thời gian lẫn chi phí, và lựa chọn nêu rõ mục tiêu tối ưu kèm số hỗ trợ."),

(356,"Spark on the reference pipeline - batch and streaming","DA","Lesson 355",
"Bài dự án khép module: chuyển phần biến đổi của pipeline tham chiếu sang Spark, cả nhánh theo lô lẫn nhánh luồng, đọc và ghi trên bố trí lakehouse ở lesson 341. Yêu cầu bắt buộc: nhánh lô và nhánh luồng dùng chung phần lớn mã biến đổi, vì đó là lý do chính để chọn một engine làm cả hai. Ba ngưỡng hiệu năng phải đạt và đều đo được: thời gian chạy nhánh lô trong cửa sổ cho trước, độ trễ đầu cuối nhánh luồng dưới ngưỡng, và chi phí một lần chạy dưới ngân sách. Hồ sơ nộp kèm: kế hoạch thực thi của hai truy vấn nặng nhất, ảnh chụp giao diện cho thấy phân bố tác vụ đều, bảng cấu hình cụm kèm lý do, và nhật ký một lần chẩn đoán có thật trong quá trình làm. Điểm quan trọng khi chấm: mọi tối ưu phải dẫn được về một quan sát trong giao diện hoặc kế hoạch, không chấp nhận tối ưu vì đọc được ở đâu đó.",
"Nộp pipeline chạy được cả hai nhánh đạt ba ngưỡng, với mỗi tối ưu dẫn được về một quan sát cụ thể.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hệ chạy được dưới ràng buộc hiệu năng và chi phí. Kiểm bằng chạy thật trên dữ liệu chuẩn cộng rà soát hồ sơ; đạt khi cả ba ngưỡng đạt và mọi tối ưu có bằng chứng.",
"Chuyển phần biến đổi sang Spark cho cả hai nhánh. Đạt ba ngưỡng. Nộp hồ sơ gồm hai kế hoạch thực thi, ảnh chụp phân bố tác vụ, bảng cấu hình kèm lý do, và một nhật ký chẩn đoán. Rà soát chéo: một học viên khác chọn một tối ưu bất kỳ và bạn phải chỉ ra quan sát dẫn tới nó.",
"Sao chép cấu hình từ bài viết trên mạng · tối ưu trước khi đo · để nhánh lô và nhánh luồng thành hai bản mã rời nhau · nộp số mà không nộp kế hoạch thực thi.",
"Cả ba ngưỡng đạt trên dữ liệu chuẩn, hai nhánh dùng chung phần biến đổi, và mọi tối ưu trong hồ sơ dẫn được về một quan sát."),
]
