# -*- coding: utf-8 -*-
"""DE M7 — Python for data engineering."""

M7 = ("Python for Data Engineering", 62, 77, """| | |
|---|---|
| **Objective cấp module** | Viết một công việc dữ liệu bằng Python xử lý được tệp lớn hơn bộ nhớ, chạy lại an toàn, và ghi nhật ký đủ để chẩn đoán khi hỏng |
| **Tiền đề** | M5 · M6 |
| **Exit criterion** | Công cụ dòng lệnh nạp API có phân trang, điểm kiểm tra và giới hạn tốc độ, chạy hai lần cho kết quả bằng chạy một lần |
| **Kỹ năng SFIA** | `PROG` mức 3 |
| **Chế độ hỏng** | Học Python như ngôn ngữ phân tích rồi nạp cả tệp vào bộ nhớ, nên tới chặng 4 không xử lý nổi nguồn 50 ghi ga byte |""",
"Module không dạy Python tổng quát. Nó dạy đúng phần một công việc dữ liệu cần: xử lý theo luồng, quản lý tài nguyên, và ghi nhật ký chẩn đoán được. Mọi bài đều chạy trên dữ liệu lớn hơn bộ nhớ máy để thói quen nạp hết vào RAM không hình thành được.")

L7 = [
(62,"Python basics for data work - types, control flow, functions","TH","Module 7: M5 · M6",
"Kiểu dựng sẵn và điều đáng chú ý với công việc dữ liệu: số nguyên độ rộng tuỳ ý nên không tràn như lesson 6 nhưng tốn bộ nhớ hơn, số thực là dấu phẩy động nên mang đúng vấn đề ở lesson 7, và chuỗi là dãy điểm mã nên độ dài khác số byte như lesson 8. Kiểu thập phân cho tiền. Biến trỏ tới đối tượng chứ không chứa giá trị, và hệ quả: gán một danh sách cho biến khác không sao chép, nên sửa một chỗ đổi cả hai. Sao chép nông và sao chép sâu. Đối số mặc định là đối tượng thay đổi được là bẫy kinh điển và nó sống qua các lần gọi. Hàm, tham số vị trí và tham số khoá, và quy ước đặt tham số có ý nghĩa. Truyền tham chiếu đối tượng và hệ quả khi hàm sửa đối số. Phép so sánh danh tính và phép so sánh giá trị, cùng lý do so sánh với giá trị rỗng phải dùng danh tính.",
"Định vị trong năm đoạn mã chỗ nào một đối tượng bị chia sẻ ngoài ý muốn, và sửa bằng sao chép đúng mức.",
"Tầng *phân tích*. Objective là truy một lớp lỗi có nguyên nhân chung, không phải viết mã mới. Kiểm bằng năm đoạn mã, bốn đoạn có lỗi chia sẻ đối tượng theo bốn cơ chế khác nhau. Đạt khi chỉ đúng cả năm và sửa được bốn đoạn lỗi mà không đổi hành vi đúng.",
"Đọc năm đoạn mã: đối số mặc định thay đổi được, gán danh sách lồng nhau, sao chép nông trên từ điển lồng, hàm sửa đối số của người gọi, và một đoạn đúng. Dự đoán kết quả từng đoạn trước khi chạy, rồi chạy đối chiếu. Sửa bốn đoạn lỗi.",
"Dùng danh sách rỗng làm đối số mặc định · dùng sao chép nông cho cấu trúc lồng · so sánh với giá trị rỗng bằng phép so sánh giá trị.",
"Dự đoán trước khi chạy khớp kết quả cho cả năm đoạn, và bốn đoạn lỗi được sửa mà hành vi đúng không đổi."),

(63,"Collections and choosing the right one","TH","Lesson 62",
"Bốn cấu trúc dựng sẵn và đặc tính chi phí của từng cái, nối trực tiếp lesson 41 và 42: danh sách cho truy cập theo chỉ số và duyệt tuần tự, bộ cho kiểm tra thành viên và phép toán tập hợp, từ điển cho tra cứu theo khoá, bộ giá trị bất biến nên dùng làm khoá được. Kiểm tra thành viên trên danh sách là bậc n còn trên bộ là hằng số, và đây là một trong những sửa lỗi hiệu năng hay gặp nhất trong mã xử lý dữ liệu. Chi phí bộ nhớ thật của từng cấu trúc, nối lại lesson 13. Hàng đợi hai đầu cho thêm bớt ở cả hai phía. Bộ đếm cho đếm tần suất. Từ điển có giá trị mặc định. Bộ giá trị có tên và lúc nào nên chuyển sang lớp dữ liệu ở lesson 67. Cách duyệt nhiều cấu trúc song song và cách duyệt kèm chỉ số. Biểu thức tạo danh sách, tạo bộ và tạo từ điển, cùng ngưỡng mà chúng trở nên khó đọc.",
"Chọn cấu trúc dữ liệu cho năm thao tác cho trước và chứng minh lựa chọn bằng số đo thời gian và bộ nhớ.",
"Tầng *đánh giá*. Objective đòi chọn có biện minh giữa nhiều phương án đều chạy được. Kiểm bằng bảng năm thao tác nhân ít nhất hai cấu trúc mỗi thao tác, có số đo. Đạt khi mỗi lựa chọn dẫn được về số đo, không chấp nhận lý do theo thói quen.",
"Năm thao tác trên 10 triệu bản ghi: kiểm tra thành viên, đếm tần suất, khử trùng, tra cứu theo khoá, và thêm bớt hai đầu. Cài mỗi thao tác bằng ít nhất hai cấu trúc, đo thời gian và bộ nhớ đỉnh. Lập bảng và chọn.",
"Kiểm tra thành viên trên danh sách trong vòng lặp · dùng từ điển khi chỉ cần bộ · nối chuỗi trong vòng lặp bằng phép cộng.",
"Bảng năm thao tác có số đo cho ít nhất hai cấu trúc mỗi thao tác, và mọi lựa chọn dẫn được về số đo."),

(64,"Iterators, generators and processing data larger than memory","TH","Lesson 63",
"Giao thức lặp và khác biệt giữa một đối tượng lặp được với một bộ lặp. Hàm sinh trả về từng phần tử một thay vì dựng cả danh sách, nên bộ nhớ không phụ thuộc số phần tử. Đây là công cụ trung tâm của module: nó biến mọi bài toán nạp cả tệp vào bộ nhớ thành bài toán chảy qua bộ nhớ. Biểu thức sinh so với biểu thức tạo danh sách, khác nhau một ký tự và khác nhau về bộ nhớ nhiều bậc. Xâu chuỗi nhiều hàm sinh thành một đường ống, và tính chất chỉ chạy khi có người lấy. Hệ quả cần cẩn thận: bộ sinh chỉ duyệt được một lần, và một lỗi phổ biến là duyệt hai lần rồi lần thứ hai rỗng. Thư viện công cụ lặp: gộp nhóm, cắt lát, nối, và ghép cặp. Trả về bộ sinh từ hàm đọc tệp thay vì trả về danh sách, mẫu bắt buộc trong mọi mã nạp dữ liệu của chương trình.",
"Viết lại một đoạn nạp cả tệp vào bộ nhớ thành đường ống hàm sinh, và chứng minh bộ nhớ đỉnh không tăng theo kích thước tệp.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm chứng tuyệt đối bằng số đo bộ nhớ. Đạt khi bộ nhớ đỉnh gần như không đổi qua bốn kích thước tệp tăng dần, và khi kết quả khớp bản nạp toàn bộ trên tệp nhỏ nhất. Chạy được mà bộ nhớ vẫn tăng theo kích thước thì không đạt.",
"Nhận đoạn mã nạp cả tệp rồi lọc và gộp. Viết lại thành đường ống hàm sinh. Chạy trên bốn tệp 1, 5, 20, 50 ghi ga byte với máy 4 ghi ga byte. Đo bộ nhớ đỉnh từng lần. Cố ý duyệt bộ sinh hai lần và quan sát lần thứ hai rỗng.",
"Dùng biểu thức tạo danh sách thay vì biểu thức sinh · duyệt bộ sinh hai lần · gọi hàm đếm độ dài trên bộ sinh rồi mất dữ liệu.",
"Bộ nhớ đỉnh gần như không đổi qua bốn kích thước tệp, và kết quả khớp bản nạp toàn bộ trên tệp nhỏ nhất."),

(65,"Exceptions - what to catch, what to let crash","TH","Lesson 64",
"Cây phân cấp ngoại lệ và nguyên tắc bắt hẹp nhất có thể. Bắt quá rộng nuốt mất lỗi lập trình và biến chúng thành lỗi dữ liệu giả, một trong những cách tệ nhất để gỡ lỗi. Ba nhóm lỗi và cách xử lý khác nhau, nối lại lesson 74 của chặng trước: lỗi tạm thời thì thử lại, lỗi dữ liệu thì tách bản ghi ra bảng lỗi và chạy tiếp, lỗi lập trình thì để chương trình chết ngay. Nguyên tắc không loại bản ghi lỗi trong im lặng: mỗi bản ghi bị loại phải kèm lý do và đếm được. Khối cuối cùng luôn chạy và chỗ nó thua trình quản lý ngữ cảnh ở lesson 66. Ngoại lệ tự định nghĩa để mã gọi phân biệt được, nối tới lesson 90 của chặng trước. Chuỗi ngoại lệ giữ nguyên nguyên nhân gốc thay vì che mất nó. Ghi vết ngăn xếp vào nhật ký thay vì in ra. Vì sao bắt rồi ghi nhật ký rồi ném lại thường là mẫu thừa tạo nhật ký trùng.",
"Phân loại 12 tình huống lỗi thành ba nhóm và cài đặt xử lý đúng cho từng nhóm, trong đó bản ghi lỗi được tách ra kèm lý do.",
"Tầng *áp dụng*. Objective gồm phân loại có đáp án và cài đặt kiểm được bằng đối soát. Đạt khi phân loại đúng ít nhất 10 trên 12, và khi chạy trên tệp có 5% bản ghi hỏng thì tổng bản ghi đầu vào bằng bản ghi sạch cộng bản ghi lỗi, không sai một dòng.",
"Nhận tệp 1 triệu bản ghi trong đó 5% hỏng theo sáu kiểu. Phân loại 12 tình huống lỗi thành ba nhóm. Viết trình nạp tách bản ghi lỗi ra bảng riêng kèm lý do. Đối soát phép cộng. Chèn một lỗi lập trình và xác nhận chương trình chết ngay chứ không nuốt.",
"Bắt ngoại lệ gốc rồi bỏ qua · loại bản ghi lỗi mà không đếm · ném lại ngoại lệ mới làm mất nguyên nhân gốc.",
"Phân loại đúng ít nhất 10 trên 12, và phép cộng đối soát khớp tuyệt đối trên tệp 1 triệu bản ghi."),

(66,"Context managers and resource cleanup","TH","Lesson 65",
"Tài nguyên phải được nhả kể cả khi có lỗi, và đây là chỗ khối cuối cùng đủ dùng nhưng dễ quên. Trình quản lý ngữ cảnh gắn việc nhả vào cấu trúc mã nên không quên được. Ba tài nguyên bắt buộc dùng nó trong công việc dữ liệu: tệp, kết nối cơ sở dữ liệu, và khoá. Rò rỉ bộ mô tả tệp nối lại lesson 20: vòng lặp mở tệp không đóng sẽ hết giới hạn. Viết trình quản lý ngữ cảnh riêng bằng hai phương thức hoặc bằng bộ trang trí. Lồng nhiều trình quản lý trong một câu lệnh. Trình quản lý ngữ cảnh cho giao dịch cơ sở dữ liệu: xác nhận khi thoát bình thường, hoàn tác khi có ngoại lệ, và vì sao viết tay dễ quên nhánh hoàn tác. Trình quản lý ngữ cảnh cho tệp tạm và mẫu ghi nguyên tử ở lesson 16: tạo tệp tạm, ghi, đổi tên khi thoát bình thường, xoá khi lỗi. Kết hợp với tín hiệu ở lesson 21: bị giết cưỡng bức thì trình quản lý ngữ cảnh không chạy, nên vẫn cần dọn dẹp lúc khởi động.",
"Viết một trình quản lý ngữ cảnh ghi nguyên tử và chứng minh nó không để lại tệp dở ở cả trường hợp lỗi lẫn trường hợp bị giết.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm lặp lại, nối tiếp lesson 16 nhưng ở tầng mã. Đạt khi 30 lần bơm lỗi và 30 lần giết cưỡng bức đều không để lại tệp dở, và khi lần khởi động sau dọn được tệp tạm còn sót từ lần bị giết.",
"Viết trình quản lý ngữ cảnh ghi nguyên tử. Bơm ngoại lệ giữa chừng 30 lần và giết cưỡng bức 30 lần. Kiểm tra thư mục đích sau mỗi lần. Thêm bước dọn tệp tạm lúc khởi động và xác nhận nó chạy. Viết thêm một trình quản lý ngữ cảnh cho giao dịch cơ sở dữ liệu.",
"Mở tệp trong vòng lặp mà không dùng trình quản lý ngữ cảnh · giả định trình quản lý ngữ cảnh chạy khi bị giết cưỡng bức · quên nhánh hoàn tác khi viết tay.",
"30 lần bơm lỗi và 30 lần giết đều không để lại tệp dở, và bước dọn lúc khởi động xử lý được tệp tạm còn sót."),

(67,"Dataclasses, type hints and making shape explicit","TH","Lesson 66",
"Gợi ý kiểu không được thực thi lúc chạy, chúng là tài liệu cho người đọc và đầu vào cho công cụ kiểm kiểu tĩnh ở lesson 83. Giá trị thật của chúng trong mã dữ liệu: khai báo hình dạng của một bản ghi ở một chỗ thay vì để nó ngầm trong các lượt truy cập từ điển rải khắp mã. Lớp dữ liệu sinh sẵn hàm khởi tạo và phép so sánh, và tuỳ chọn đóng băng để bất biến, nối lại lesson 55. Lớp dữ liệu so với từ điển cho một bản ghi: lớp bắt được lỗi gõ sai tên trường lúc kiểm kiểu còn từ điển thì không, nhưng từ điển linh hoạt hơn khi lược đồ nguồn thay đổi. Tiêu chí chọn giữa hai cái theo tầng: dùng từ điển ở biên nhận dữ liệu thô, chuyển sang lớp dữ liệu sau khi đã xác thực. Kiểu tuỳ chọn và vì sao khai báo rõ trường nào có thể rỗng quan trọng hơn khai báo kiểu của nó. Thư viện xác thực dữ liệu lúc chạy và ranh giới với gợi ý kiểu tĩnh.",
"Chuyển một đoạn mã dùng từ điển thô sang lớp dữ liệu có gợi ý kiểu, và chỉ ra ba lỗi mà công cụ kiểm kiểu bắt được sau khi chuyển.",
"Tầng *áp dụng*. Objective gồm một phép tái cấu trúc và một bằng chứng cụ thể về lợi ích. Đạt khi công cụ kiểm kiểu báo đúng ba lỗi cố ý cài vào và không báo lỗi giả ở phần còn lại. Chuyển xong mà công cụ kiểm kiểu không bắt được gì thì chưa đạt.",
"Nhận đoạn mã 200 dòng xử lý bản ghi đơn hàng bằng từ điển thô. Chuyển sang lớp dữ liệu có gợi ý kiểu. Cài ba lỗi: gõ sai tên trường, dùng sai kiểu, quên xử lý trường rỗng. Chạy công cụ kiểm kiểu và xác nhận nó bắt đủ ba.",
"Gắn gợi ý kiểu rồi tưởng nó được kiểm lúc chạy · dùng lớp dữ liệu ở biên nhận dữ liệu thô nên vỡ khi nguồn đổi lược đồ · bỏ qua việc khai báo trường có thể rỗng.",
"Công cụ kiểm kiểu bắt đúng ba lỗi cài sẵn và không báo lỗi giả ở phần còn lại."),

(68,"Modules, packages and imports","TH","Lesson 67",
"Mô đun là một tệp, gói là một thư mục có tệp khởi tạo. Đường dẫn tìm kiếm mô đun và thứ tự tra cứu, nguyên nhân của phần lớn lỗi không tìm thấy mô đun. Nhập tuyệt đối so với nhập tương đối và vì sao nhập tuyệt đối dễ đọc và dễ di chuyển hơn. Nhập vòng: cơ chế, triệu chứng, và ba cách phá vòng. Mã ở tầng ngoài mô đun chạy lúc nhập, nối thẳng tới bẫy ở chặng 5 khi công cụ điều phối đọc lại tệp định nghĩa đồ thị nhiều lần mỗi phút. Khối bảo vệ điểm vào và vì sao nó bắt buộc khi dùng nhiều tiến trình ở lesson 59. Cấu trúc gói cho một dự án dữ liệu: tách phần đọc nguồn, phần biến đổi, phần ghi đích, và phần điều phối, để phần biến đổi kiểm thử được mà không cần cơ sở dữ liệu. Cài gói ở chế độ chỉnh sửa được để nhập từ thư mục kiểm thử. Ranh giới giữa mô đun và cấu hình.",
"Tổ chức một script một tệp thành gói có bốn phần tách bạch, sao cho phần biến đổi kiểm thử được không cần cơ sở dữ liệu.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm được: phần biến đổi phải chạy kiểm thử mà không kết nối gì. Đạt khi bộ kiểm thử cho phần biến đổi chạy xanh với mạng bị chặn và không có cơ sở dữ liệu, và khi toàn bộ gói vẫn chạy được đầu cuối.",
"Nhận script 400 dòng làm mọi thứ trong một tệp. Tách thành gói bốn phần. Viết kiểm thử cho phần biến đổi, chạy với mạng bị chặn. Tạo một nhập vòng có chủ đích, quan sát lỗi, rồi phá vòng bằng một trong ba cách.",
"Đặt mã nặng ở tầng ngoài mô đun · dùng nhập tương đối nhiều tầng rồi không di chuyển tệp được · trộn phần biến đổi với phần kết nối nên không kiểm thử được.",
"Kiểm thử phần biến đổi chạy xanh khi chặn mạng và không có cơ sở dữ liệu, và gói vẫn chạy được đầu cuối."),

(69,"Reading and writing CSV and JSON correctly","TH","Lesson 68",
"CSV không có chuẩn thống nhất, nên mọi giả định về nó đều phải kiểm. Bốn tham số quyết định kết quả và phải khai báo rõ: ký tự phân cách, ký tự bao chuỗi, ký tự thoát, và ký tự xuống dòng. Trường chứa chính ký tự phân cách, trường chứa dấu xuống dòng, và cơ chế chúng làm số cột thay đổi giữa các dòng. Bảng mã và ký tự đánh dấu đầu tệp, nối lại lesson 8. Không có kiểu dữ liệu trong CSV nên mọi thứ là chuỗi, và việc tự đoán kiểu là nguồn lỗi âm thầm: số điện thoại mất số 0 đầu, mã sản phẩm thành số khoa học. Đọc CSV theo luồng bằng bộ đọc chuẩn thay vì nạp hết. JSON và JSON theo dòng: cái sau xử lý theo luồng được còn cái trước thì không, nên định dạng theo dòng là lựa chọn mặc định cho dữ liệu lớn. JSON lồng sâu và làm phẳng có kiểm soát. Số lớn trong JSON mất độ chính xác khi qua dấu phẩy động, nối lại lesson 7.",
"Đọc một tệp CSV có đủ bốn loại bẫy và chứng minh số dòng cùng số cột đúng, không để công cụ tự đoán kiểu.",
"Tầng *áp dụng*. Objective có tiêu chí đối chứng tuyệt đối. Đạt khi số dòng và số cột khớp đáp án, và khi bốn cột bẫy giữ nguyên giá trị gốc dưới dạng chuỗi. Một cột bị tự đoán kiểu làm mất số 0 đầu là không đạt.",
"Nhận tệp CSV có trường chứa ký tự phân cách, trường chứa dấu xuống dòng, cột số điện thoại có số 0 đầu, và cột mã dài 18 chữ số. Đọc theo luồng, khai báo rõ bốn tham số, tắt tự đoán kiểu. Đối chiếu số dòng, số cột và giá trị bốn cột bẫy.",
"Tách dòng bằng dấu phẩy thay vì dùng bộ đọc CSV · để công cụ tự đoán kiểu · nạp cả tệp JSON lồng vào bộ nhớ.",
"Số dòng và số cột khớp đáp án, và bốn cột bẫy giữ nguyên giá trị gốc."),

(70,"Parquet and columnar files","TH","Lesson 69",
"Định dạng cột lưu dữ liệu theo cột thay vì theo dòng, nối thẳng lesson 41. Ba hệ quả đo được: nén tốt hơn vì giá trị cùng cột giống nhau, đọc một phần cột không phải đọc cả dòng, và phép gộp trên một cột tận dụng dòng bộ nhớ đệm. Cấu trúc tệp: nhóm dòng, khối cột, và siêu dữ liệu ở cuối tệp. Thống kê nhỏ nhất lớn nhất theo nhóm dòng cho phép bỏ qua cả nhóm khi lọc, cơ chế gọi là cắt tỉa và là nền của phân vùng ở chặng 7. Kích thước nhóm dòng và đánh đổi: nhóm lớn nén tốt và cắt tỉa thô, nhóm nhỏ ngược lại. Lược đồ nằm trong tệp nên kiểu dữ liệu không bị đoán như CSV. Thuật toán nén và đánh đổi giữa tỉ lệ nén với thời gian bộ xử lý. Vấn đề nhiều tệp nhỏ, nối lại lesson 15: mỗi tệp có phần đầu và phần siêu dữ liệu nên chia quá nhỏ thì phần thừa lấn át dữ liệu.",
"Đo chênh lệch kích thước và thời gian đọc giữa CSV và định dạng cột trên cùng dữ liệu, và chứng minh cắt tỉa theo thống kê có hiệu lực.",
"Tầng *phân tích*. Objective đòi nối số đo với cơ chế bên trong định dạng. Đạt khi có bảng số đo cho ít nhất ba kiểu truy vấn, và khi người học chứng minh được cắt tỉa hoạt động bằng cách so số byte đọc thật với kích thước tệp, không chỉ bằng thời gian.",
"Chuyển một tập 20 ghi ga byte từ CSV sang định dạng cột ở ba kích thước nhóm dòng. Chạy ba truy vấn: lấy một cột, lọc theo khoảng hẹp trên cột đã sắp, và gộp toàn bảng. Đo kích thước tệp, số byte đọc thật và thời gian cho từng cấu hình.",
"Chia dữ liệu thành hàng nghìn tệp nhỏ · ghi không sắp theo cột lọc nên cắt tỉa vô hiệu · chọn nén mạnh nhất mà không đo chi phí bộ xử lý.",
"Bảng số đo đủ ba truy vấn nhân ba kích thước nhóm dòng, và cắt tỉa được chứng minh bằng số byte đọc thật."),

(71,"Chunking and streaming large files","TH","Lesson 70",
"Ba chiến lược xử lý dữ liệu lớn hơn bộ nhớ và điều kiện áp dụng. Xử lý theo luồng từng bản ghi cho bộ nhớ hằng số nhưng chỉ làm được phép biến đổi không cần nhìn toàn cục. Xử lý theo khối cân bằng giữa bộ nhớ và chi phí gọi, và là lựa chọn mặc định. Chia để trị cho phép toán cần toàn cục như sắp xếp và gộp nhóm trên khoá nhiều giá trị, nối lại lesson 43 và 48. Chọn kích thước khối bằng thực nghiệm: quá nhỏ thì chi phí gọi lấn át, quá lớn thì bộ nhớ đỉnh lớn và rủi ro bị giết. Phép gộp tăng dần giữ trạng thái nhỏ: tổng, đếm, nhỏ nhất, lớn nhất làm được theo luồng; trung vị và đếm giá trị phân biệt chính xác thì không, nối lại lesson 45 và 47. Ghi ra theo khối và điểm kiểm tra sau mỗi khối để chạy lại được, nối lại lesson 35. Đọc nhiều tệp như một luồng liên tục và giữ được thông tin tệp nguồn cho mỗi bản ghi.",
"Chọn kích thước khối cho thông lượng cao nhất trong ràng buộc bộ nhớ cho trước, và cài phép gộp tăng dần giữ trạng thái nhỏ.",
"Tầng *đánh giá*. Objective đòi tinh chỉnh một tham số có đánh đổi hai chiều và biện minh bằng số. Đạt khi bảng thực nghiệm có ít nhất bốn kích thước khối kèm thời gian và bộ nhớ đỉnh, khi lựa chọn không vượt ràng buộc bộ nhớ, và khi kết quả gộp khớp đáp án.",
"Xử lý 50 ghi ga byte với giới hạn 3 ghi ga byte bộ nhớ. Chạy ở bốn kích thước khối. Đo thông lượng và bộ nhớ đỉnh. Cài bốn phép gộp tăng dần và một phép cần toàn cục, xử lý phép cuối bằng chia để trị. Thêm điểm kiểm tra sau mỗi khối và thử giết giữa chừng.",
"Chọn kích thước khối bằng cảm tính · tích luỹ kết quả từng khối vào một danh sách trong bộ nhớ · ghi điểm kiểm tra trước khi ghi dữ liệu.",
"Bảng bốn kích thước khối có thời gian và bộ nhớ đỉnh, lựa chọn nằm trong ràng buộc, và kết quả gộp khớp đáp án."),

(72,"Database drivers, cursors and parameterized queries","TH","Lesson 71",
"Trình điều khiển và giao diện chuẩn. Kết nối, con trỏ, và vòng đời của cả hai. Con trỏ phía máy chủ trả về từng khối thay vì tải hết kết quả về máy khách, bắt buộc khi kết quả lớn hơn bộ nhớ, và đây là lỗi hay gặp: truy vấn chạy được trên bảng nhỏ rồi chết trên bảng lớn. Truy vấn tham số hoá và cơ chế chèn mã độc khi ghép chuỗi: không chỉ là vấn đề bảo mật mà còn là vấn đề đúng đắn khi dữ liệu chứa dấu nháy. Ghi theo lô và chênh lệch thông lượng so với ghi từng dòng, thường nhiều bậc. Giao dịch, xác nhận và hoàn tác; chế độ tự xác nhận và vì sao nó làm ghi theo lô mất ý nghĩa. Kết nối không an toàn luồng, nối lại lesson 55: mỗi luồng một kết nối riêng hoặc dùng nhóm kết nối, nối lại lesson 36. Thời gian chờ ở tầng truy vấn và tầng kết nối. Đóng tài nguyên bằng trình quản lý ngữ cảnh ở lesson 66.",
"Đọc một kết quả truy vấn lớn hơn bộ nhớ bằng con trỏ phía máy chủ, và đo chênh lệch thông lượng giữa ghi từng dòng với ghi theo lô.",
"Tầng *áp dụng*. Objective gồm một ràng buộc cứng về bộ nhớ và một phép đo. Đạt khi đọc hết 100 triệu dòng trên máy 4 ghi ga byte không bị giết, và khi bảng thông lượng cho thấy chênh lệch giữa ba kích thước lô.",
"Truy vấn 100 triệu dòng trên máy 4 ghi ga byte. Thử đọc thường, quan sát bị giết. Chuyển sang con trỏ phía máy chủ. Ghi kết quả vào bảng đích theo ba kích thước lô, đo thông lượng. Thử ghép chuỗi truy vấn với dữ liệu chứa dấu nháy và quan sát.",
"Ghép chuỗi để dựng truy vấn · để chế độ tự xác nhận khi ghi theo lô · dùng chung một kết nối cho nhiều luồng.",
"Đọc hết 100 triệu dòng trên máy 4 ghi ga byte không bị giết, và bảng thông lượng có ba kích thước lô."),

(73,"Memory profiling and finding the leak","TH","Lesson 72",
"Bộ nhớ tăng đều là triệu chứng, không phải chẩn đoán. Ba nguyên nhân khác nhau cho cùng triệu chứng: tích luỹ có chủ đích, giữ tham chiếu ngoài ý muốn, và phân mảnh. Đếm tham chiếu và thu gom rác theo chu kỳ; chu kỳ tham chiếu và cơ chế nó giữ đối tượng sống. Ba nơi tham chiếu bị giữ ngoài ý muốn trong mã dữ liệu: bộ nhớ đệm không có giới hạn, danh sách tích luỹ trong vòng lặp, và bao đóng bắt biến lớn. Công cụ đo: chụp ảnh bộ nhớ theo thời gian, so hai ảnh chụp, và tìm loại đối tượng tăng nhiều nhất. Đo bộ nhớ theo dòng mã cho hàm nghi ngờ. Bộ nhớ trả về hệ điều hành chậm hơn bộ nhớ được giải phóng trong tiến trình, nên số đo của hệ điều hành và của môi trường chạy khác nhau và cả hai đều đúng. Quy trình bốn bước tìm rò rỉ, và nguyên tắc tái hiện được trước khi sửa.",
"Định vị nguyên nhân một rò rỉ bộ nhớ về đúng một trong ba nhóm, và chứng minh bằng ảnh chụp bộ nhớ trước và sau khi sửa.",
"Tầng *phân tích*. Objective là chẩn đoán phân biệt ba nguyên nhân có cùng triệu chứng. Kiểm bằng ba chương trình rò rỉ theo ba cơ chế; đạt khi định vị đúng cả ba và dẫn được ảnh chụp bộ nhớ chỉ ra loại đối tượng tăng.",
"Nhận ba chương trình rò rỉ: bộ nhớ đệm không giới hạn, danh sách tích luỹ trong vòng lặp, và bao đóng giữ khung dữ liệu lớn. Với mỗi cái, chụp ảnh bộ nhớ theo thời gian, so sánh, định vị, sửa, chụp lại. So số đo của hệ điều hành với số đo của môi trường chạy.",
"Kết luận rò rỉ từ số đo của hệ điều hành một mình · thêm lời gọi thu gom rác thủ công để chữa triệu chứng · sửa mà không tái hiện được trước.",
"Định vị đúng cả ba nguyên nhân, mỗi cái có ảnh chụp bộ nhớ trước sau chỉ ra loại đối tượng tăng."),

(74,"Logging with correlation IDs","TH","Lesson 73",
"Nhật ký là thứ duy nhất còn lại khi công việc chạy lúc ba giờ sáng và hỏng. Năm mức nhật ký và tiêu chí dùng từng mức, trong đó mức cảnh báo bị lạm dụng nhiều nhất. Nhật ký có cấu trúc dạng khoá giá trị thay vì câu văn: câu thì người đọc được, khoá giá trị thì máy lọc được, và khi có hàng nghìn dòng mỗi lần chạy thì lọc quan trọng hơn đọc. Mã định danh tương quan gắn vào mọi dòng nhật ký của một lần chạy, để nối được nhật ký khi nhiều lần chạy xen kẽ, và truyền được xuống cả lời gọi mạng ở chặng sau. Bốn thứ mọi công việc dữ liệu phải ghi: số bản ghi vào, số bản ghi ra, số bản ghi bị loại kèm lý do, và thời lượng từng giai đoạn. Không ghi dữ liệu cá nhân vào nhật ký, và cách che trường nhạy cảm. Không dùng lệnh in: nó không có mức, không có dấu thời gian, và không chuyển hướng được. Xoay vòng nhật ký và mất nhật ký cũ.",
"Thêm nhật ký có cấu trúc và mã định danh tương quan cho một công việc, sao cho một lần chạy hỏng truy được toàn bộ dòng của chính nó trong nhật ký chung.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm được bằng thao tác lọc. Đạt khi chạy 20 lần đồng thời rồi lọc theo một mã định danh ra đúng dòng của lần chạy đó, và khi bốn số bắt buộc đều có mặt. Nhật ký đẹp mà không lọc được thì không đạt.",
"Thêm nhật ký có cấu trúc cho trình nạp ở lesson 65. Chạy 20 lần đồng thời ghi vào cùng một tệp. Lọc theo mã định danh của một lần chạy và xác nhận ra đúng dòng của nó. Thêm che trường nhạy cảm và xác nhận bằng cách tìm chuỗi trong nhật ký.",
"Dùng lệnh in thay cho nhật ký · ghi câu văn nên không lọc được · ghi cả bản ghi gốc vào nhật ký khi gỡ lỗi rồi lộ dữ liệu cá nhân.",
"Lọc theo mã định danh ra đúng dòng của một lần chạy trong 20 lần đồng thời, và bốn số bắt buộc đều có."),

(75,"Configuration, environment variables and secrets","TH","Lesson 74",
"Ba loại giá trị và chỗ đặt tương ứng: hằng số của mã thì để trong mã, tham số đổi theo môi trường thì để trong cấu hình, thông tin xác thực thì để trong kho bí mật. Thứ tự ưu tiên khi một giá trị xuất hiện nhiều nơi: tham số dòng lệnh, biến môi trường, tệp cấu hình, giá trị mặc định. Vì sao viết cứng đường dẫn và tên máy chủ trong mã làm công việc không chạy được ở môi trường khác. Xác thực cấu hình lúc khởi động thay vì để lỗi nổ ra giữa chừng: thiếu một biến môi trường phải làm chương trình dừng ngay với thông báo rõ. Bí mật không bao giờ nằm trong kho mã, và lịch sử kho vẫn giữ chúng sau khi xoá, nối tới lesson 78. Tệp môi trường cục bộ và bắt buộc đưa vào danh sách bỏ qua. Bí mật trong biến môi trường lộ qua danh sách tiến trình và qua nhật ký gỡ lỗi. Xoay vòng bí mật và vì sao mã phải đọc lại được thay vì đọc một lần lúc khởi động.",
"Tách một công việc đang viết cứng cấu hình thành ba lớp, và chứng minh bằng quét rằng không bí mật nào nằm trong kho mã hay nhật ký.",
"Tầng *áp dụng*. Objective gồm một phép tái cấu trúc và một bằng chứng quét. Đạt khi công việc chạy được ở hai môi trường mà không sửa dòng mã nào, và khi quét toàn bộ lịch sử kho mã cùng nhật ký không ra thông tin xác thực nào.",
"Nhận công việc viết cứng chuỗi kết nối và đường dẫn. Tách ba lớp. Thêm xác thực cấu hình lúc khởi động. Chạy ở hai môi trường khác nhau không sửa mã. Quét lịch sử kho mã và nhật ký bằng công cụ tìm bí mật.",
"Nộp tệp môi trường vào kho mã · in toàn bộ cấu hình lúc khởi động kể cả bí mật · để lỗi thiếu cấu hình nổ ra giữa chừng thay vì lúc khởi động.",
"Chạy được ở hai môi trường không sửa mã, và quét lịch sử kho mã cùng nhật ký không ra bí mật nào."),

(76,"Command line interfaces for data jobs","TH","Lesson 75",
"Công việc dữ liệu chạy bằng lệnh, nên giao diện dòng lệnh là hợp đồng giữa nó với công cụ điều phối ở chặng 5. Bốn nhóm tham số mọi công việc nên có: khoảng dữ liệu xử lý, đường dẫn nguồn và đích, chế độ chạy thử, và mức nhật ký. Tham số khoảng ngày nối thẳng tới ngày logic ở chặng 5: công việc nhận ngày từ ngoài chứ không đọc đồng hồ hệ thống. Chế độ chạy thử in ra việc sẽ làm mà không ghi gì, và nó phải thật sự không ghi. Mã thoát có nghĩa theo quy ước ở lesson 27, vì công cụ điều phối chỉ nhìn mã thoát. Thông báo trợ giúp tự sinh và giá trị mặc định hiển thị được. Lệnh con khi một công cụ làm nhiều việc. Xác thực tham số sớm và thông báo lỗi nói rõ giá trị nào sai. Đọc tham số từ tệp khi danh sách dài. Không hỏi tương tác: công việc chạy tự động không có ai gõ trả lời.",
"Đóng gói một công việc thành công cụ dòng lệnh có đủ bốn nhóm tham số, và chứng minh chế độ chạy thử không ghi gì.",
"Tầng *áp dụng*. Objective có sản phẩm và tiêu chí kiểm chứng rõ. Đạt khi chế độ chạy thử chạy xong mà bảng đích và tệp đích không đổi một byte, và khi ba giá trị tham số sai đều bị từ chối lúc khởi động với thông báo nói rõ giá trị nào sai.",
"Đóng gói trình nạp thành công cụ dòng lệnh. Chạy chế độ chạy thử, so ảnh chụp thư mục đích và bảng đích trước sau. Thử ba tham số sai: ngày sai định dạng, đường dẫn không tồn tại, mức nhật ký không hợp lệ. Xác nhận mã thoát đúng quy ước.",
"Đọc ngày từ đồng hồ hệ thống thay vì nhận từ tham số · chế độ chạy thử vẫn ghi vào bảng tạm · hỏi tương tác khi thiếu tham số.",
"Chế độ chạy thử không đổi một byte ở đích, và ba tham số sai đều bị từ chối lúc khởi động với thông báo cụ thể."),

(77,"Python project - a resumable API loader","DA","Lesson 76",
"Không có nội dung mới. Dự án gộp M7, và nó dùng lại ứng dụng khách HTTP đã đóng gói ở lesson 39. Yêu cầu đầu ra: công cụ dòng lệnh nạp dữ liệu từ một API có phân trang vào cơ sở dữ liệu, xử lý theo luồng nên bộ nhớ không tăng theo kích thước nguồn, có điểm kiểm tra để chạy lại từ chỗ dừng, tách bản ghi lỗi kèm lý do, ghi nhật ký có cấu trúc và mã định danh tương quan, cấu hình ba lớp, và chế độ chạy thử. Tiêu chí đối soát: tổng bản ghi nguồn bằng bản ghi sạch cộng bản ghi lỗi, và chạy hai lần cho kết quả bằng chạy một lần.",
"Đóng gói một trình nạp API chạy lại được, và chứng minh bằng đối soát rằng chạy hai lần cho kết quả bằng chạy một lần.",
"Tầng *sáng tạo*. Objective là thiết kế một hệ thống nhỏ dưới nhiều ràng buộc cùng lúc, không phải ghép mẫu. Chấm theo năm mục: đối soát khớp 30đ, chạy lại từ điểm kiểm tra 25đ, xử lý lỗi và tách bản ghi hỏng 20đ, nhật ký và cấu hình 15đ, tài liệu 10đ. Đạt khi ≥ 70/100 và mục đối soát ≥ 70% của nó, vì đối soát sai thì mọi phần còn lại không cứu được.",
"Nạp 2 triệu bản ghi từ API lỗi 15% có phân trang và giới hạn tốc độ, trên máy 2 ghi ga byte bộ nhớ. Giết tiến trình 5 lần ở thời điểm ngẫu nhiên, mỗi lần chạy lại từ điểm kiểm tra. Chạy toàn bộ lần thứ hai. Đối soát cả hai điều kiện.",
"Giữ trạng thái trong bộ nhớ nên mất khi bị giết · ghi điểm kiểm tra trước khi ghi dữ liệu · bỏ qua bản ghi lỗi mà không đếm.",
"Đạt ≥ 70/100, mục đối soát ≥ 70%, và chạy hai lần cho kết quả bằng chạy một lần."),
]
