# -*- coding: utf-8 -*-
"""DE M27 Messaging foundations + M28 RabbitMQ."""

M27 = ("Messaging Foundations", 277, 282, """| | |
|---|---|
| **Objective cấp module** | Phát biểu một bài toán truyền thông điệp bằng từ vựng ngữ nghĩa giao nhận, thứ tự, offset và phát lại, trước khi mở bất kỳ broker nào |
| **Tiền đề** | M26 |
| **Exit criterion** | Nhận sáu sự cố của một hệ nối bằng lời gọi trực tiếp, định vị đúng cơ chế cho cả sáu và nêu broker giải được cái nào, không giải được cái nào |
| **Kỹ năng SFIA** | `SYSP` mức 3 · `DTAN` mức 3 |
| **Chế độ hỏng** | Học thẳng vào một broker, rồi coi mọi vấn đề giao nhận là vấn đề cấu hình, nên đổi broker mà trùng bản ghi vẫn còn |""",
"""Module không mở broker nào. Nó dựng từ vựng để M28 và M29 có cái mà so sánh, và để M30 chấm được bằng tiêu chí thay vì bằng danh sách tính năng. Cùng ràng buộc với M21 trước khối điều phối và M9 · M10 trước khối cơ sở dữ liệu.

**Kịch bản tham chiếu chung.** M28 và M29 dựng lại cùng một bài toán: sự kiện đơn hàng sinh từ PostgreSQL của pipeline lesson 217, phát ra cho hai bên tiêu thụ độc lập là bộ nạp mart và bộ kiểm gian lận. Cùng ba lỗi cài sẵn: một thông điệp gửi trùng, một thông điệp tới sai thứ tự, một thông điệp hỏng không giải mã được. Cùng kịch bản giết tiến trình giữa chừng. Không cùng bài toán thì M30 không đo được gì.""")

L27 = [
(277,"Why a message broker exists - coupling, backpressure and load spikes","LT","Module 27: M26",
"Bốn vấn đề của việc nối hai hệ bằng lời gọi trực tiếp, mỗi vấn đề kèm một hậu quả quan sát được trên pipeline lesson 217. Một là ràng buộc thời gian: bên gửi chỉ xong khi bên nhận xong, nên bên nhận chậm thì bên gửi chậm theo, và bên nhận chết thì bên gửi mất dữ liệu. Hai là ràng buộc số lượng: thêm bên tiêu thụ thứ hai thì phải sửa mã bên gửi, nối lại vấn đề phụ thuộc chéo ở lesson 220. Ba là đỉnh tải: bên gửi sinh 5.000 sự kiện trong một phút còn bên nhận xử lý được 500, phần chênh không có chỗ chứa nên hoặc mất hoặc làm sập bên nhận, nối lại hàng đợi có giới hạn và áp lực ngược ở M6. Bốn là phát lại: sửa lỗi logic xong thì không có cách nào cho dữ liệu cũ chạy lại, nối lại lesson 210. Broker giải bốn vấn đề đó bằng một cách duy nhất là chen một vùng lưu trữ có thứ tự vào giữa. Cái giá phải trả: thêm một hệ phải vận hành, thêm độ trễ, và mất tính nhất quán tức thời giữa hai bên.",
"Định vị trong bốn vấn đề cái nào gây ra một sự cố cho trước, dẫn bằng nhật ký và số liệu chứ bằng phỏng đoán.",
"Tầng *phân tích*. Bài mở module, người học đã vận hành pipeline theo lô từ M20 và biết áp lực ngược từ M6, nên có kinh nghiệm để soi lại nhưng chưa có broker nào. Objective dừng ở phân rã một sự cố về đúng cơ chế. Kiểm bằng sáu hồ sơ sự cố có nhật ký và biểu đồ tải; đạt khi định vị đúng ít nhất năm và mỗi lần dẫn được bằng chứng.",
"Nhận sáu hồ sơ sự cố của một hệ nối trực tiếp. Với mỗi hồ sơ, nêu vấn đề nào trong bốn vấn đề, bằng chứng nào trong nhật ký chỉ ra điều đó, và broker giải nó bằng cơ chế gì. Với hai hồ sơ cuối, broker không giải được; nêu vì sao.",
"Cho rằng broker làm hệ thống nhanh hơn · quên rằng broker thêm một hệ phải trực · coi độ trễ tăng thêm là không đáng kể mà không đo.",
"Định vị đúng ≥ 5/6 hồ sơ, mỗi lần dẫn được bằng chứng từ nhật ký, và chỉ đúng hai hồ sơ broker không giải được."),

(278,"Delivery semantics - at most once, at least once, exactly once end to end","LT","Lesson 277",
"Ba mức ngữ nghĩa giao nhận, định nghĩa bằng điều gì xảy ra khi có sự cố chứ bằng tên gọi. Nhiều nhất một lần: xác nhận trước khi xử lý, nên sự cố làm mất thông điệp. Ít nhất một lần: xử lý trước khi xác nhận, nên sự cố làm thông điệp được xử lý lại, và đây là mặc định của mọi broker dùng trong sản xuất. Đúng một lần là **tính chất của toàn tuyến, không phải một nút gạt của broker**: nó chỉ đạt được khi bên tiêu thụ ghi có tính bất biến, tức là ghi lại cho cùng kết quả, đúng cơ chế đã học ở lesson 106 và 207. Phân biệt ba chỗ có thể mất hoặc nhân đôi: giữa bên gửi và broker, trong broker, giữa broker và bên nhận. Bài toán hai vị tướng ở mức kết luận: không có giao thức nào cho phép hai bên biết chắc bên kia đã nhận, nên mọi hệ thực tế chọn ít nhất một lần cộng khử trùng ở đầu ghi. Khoá khử trùng lấy từ đâu: khoá nghiệp vụ ở lesson 208, không lấy từ mã thông điệp do broker sinh.",
"Với một tuyến gửi và nhận cho trước, chỉ ra tuyến đó đạt mức ngữ nghĩa nào và nêu thay đổi nhỏ nhất để nâng lên đúng một lần đầu cuối.",
"Tầng *đánh giá*. Người học đã có tính bất biến từ lesson 106 và 207, nên bài này ghép hai mảnh thành một phán đoán về toàn tuyến. Kiểm bằng năm sơ đồ tuyến có chú thích thứ tự xác nhận và ghi; đạt khi phân loại đúng ít nhất bốn và nêu được thay đổi nhỏ nhất, không chấp nhận câu trả lời bật một tuỳ chọn của broker.",
"Nhận năm sơ đồ tuyến. Với mỗi sơ đồ, phân loại mức ngữ nghĩa, chỉ ra chính xác chỗ mất hoặc nhân đôi xảy ra, và viết thay đổi nhỏ nhất đưa tuyến về đúng một lần đầu cuối. Một sơ đồ trong năm không nâng lên được nếu không đổi thiết kế bên nhận; nêu vì sao.",
'Tin rằng bật một tuỳ chọn tên "exactly once" là xong · khử trùng bằng mã thông điệp của broker thay vì khoá nghiệp vụ · xác nhận trước khi ghi xong.',
"Phân loại đúng ≥ 4/5 sơ đồ và nêu đúng thay đổi nhỏ nhất, kể cả sơ đồ không nâng được."),

(279,"Ordering guarantees and the partition as the unit of order","LT","Lesson 278",
"Thứ tự toàn cục tốn kém tới mức không hệ nào ở quy mô lớn cung cấp, vì nó buộc mọi thông điệp qua một điểm nối tiếp. Cái mọi broker cung cấp là thứ tự trong một đơn vị hẹp hơn: một hàng đợi, một phân vùng, một khoá. Hệ quả thiết kế: **chọn khoá phân vùng chính là chọn cái gì được bảo đảm thứ tự**. Đơn hàng cùng một mã khách phải cùng khoá thì mới thấy đúng trình tự tạo rồi huỷ; chọn khoá ngẫu nhiên thì hai sự kiện của cùng một đơn có thể tới ngược. Ba hậu quả của khoá lệch: một khoá nóng chiếm phần lớn lưu lượng làm mất tác dụng của việc chia phân vùng, đúng hiện tượng lệch dữ liệu sẽ gặp lại ở M34; số phân vùng đổi thì ánh xạ khoá đổi theo nên thứ tự cũ đứt; và thứ tự chỉ được bảo đảm khi mỗi phân vùng có đúng một bên tiêu thụ đang hoạt động. Phân biệt thứ tự tới với thứ tự sự kiện: dấu thời gian trong thông điệp và thứ tự trong hàng đợi là hai thứ khác nhau, sẽ dùng lại ở lesson 317.",
"Chọn khoá phân vùng cho một luồng sự kiện cho trước và nêu bằng phản ví dụ điều gì hỏng nếu chọn khoá khác.",
"Tầng *áp dụng*. Objective là một quyết định thiết kế có ràng buộc rõ, nên kiểm được bằng bài làm chứ bằng câu hỏi trắc nghiệm. Kiểm bằng ba luồng sự kiện có yêu cầu thứ tự khác nhau; đạt khi cả ba chọn đúng khoá và mỗi lần nêu được một phản ví dụ cụ thể.",
"Cho ba luồng sự kiện: thay đổi trạng thái đơn hàng, đo lường thiết bị, và nhật ký thao tác người dùng. Với mỗi luồng, chọn khoá phân vùng, nêu cái gì được bảo đảm thứ tự và cái gì không, rồi viết một phản ví dụ cho thấy hậu quả khi chọn khoá khác. Đo phân bố khoá trên dữ liệu mẫu và chỉ ra luồng nào có nguy cơ khoá nóng.",
"Cho rằng broker giữ thứ tự toàn cục · chọn khoá ngẫu nhiên để chia đều rồi mất thứ tự · quên rằng tăng số phân vùng làm đứt thứ tự của khoá cũ.",
"Ba luồng đều chọn đúng khoá, mỗi luồng có một phản ví dụ cụ thể, và chỉ đúng luồng có nguy cơ khoá nóng kèm số đo phân bố."),

(280,"Consumer groups, offsets and where progress is recorded","LT","Lesson 279",
"Hai mô hình tiêu thụ và hệ quả vận hành của từng mô hình. Mô hình hàng đợi: thông điệp được lấy ra thì biến mất, nhiều bên tiêu thụ chia nhau công việc, muốn hai bên cùng đọc toàn bộ thì phải nhân bản dữ liệu ở phía broker. Mô hình nhật ký: thông điệp nằm lại theo chính sách lưu giữ, mỗi nhóm tiêu thụ giữ con trỏ riêng, nên thêm bên tiêu thụ thứ hai không đụng gì tới bên thứ nhất và đọc lại quá khứ là chuyện bình thường. Con trỏ tiến độ ghi ở đâu quyết định điều gì xảy ra khi bên tiêu thụ chết: ghi ở broker thì bên tiêu thụ khởi động lại đọc tiếp được nhưng có nguy cơ xử lý lại đoạn chưa xác nhận; ghi cùng chỗ với kết quả, trong cùng một giao dịch, thì tiến độ và dữ liệu không bao giờ lệch nhau, và đây là cách duy nhất đạt đúng một lần đầu cuối ở lesson 278. Cân bằng lại nhóm: khi một bên tiêu thụ vào hoặc ra, phần việc được chia lại, và trong lúc chia lại thì xử lý dừng; hệ quả là nhóm càng đông thì mỗi lần triển khai càng tốn thời gian dừng.",
"Với một yêu cầu tiêu thụ cho trước, chọn mô hình hàng đợi hay nhật ký và nêu chỗ ghi tiến độ, kèm điều gì xảy ra khi bên tiêu thụ chết giữa chừng.",
"Tầng *đánh giá*. Bài đòi cân nhắc đánh đổi giữa hai mô hình chứ nhớ định nghĩa, và đây là trục chính mà M30 sẽ chấm. Kiểm bằng bốn yêu cầu tiêu thụ có ràng buộc khác nhau; đạt khi cả bốn chọn đúng mô hình và mô tả đúng hành vi khi chết giữa chừng.",
"Cho bốn yêu cầu: nạp mart theo lô, kiểm gian lận theo thời gian thực, gửi thông báo cho khách, và dựng lại toàn bộ lịch sử sau khi sửa lỗi logic. Với mỗi yêu cầu, chọn mô hình, nêu chỗ ghi tiến độ, và mô tả điều gì xảy ra nếu bên tiêu thụ chết sau khi ghi kết quả nhưng trước khi xác nhận.",
"Ghi tiến độ tách rời kết quả rồi tưởng đã đạt đúng một lần · quên thời gian dừng khi cân bằng lại nhóm · dùng mô hình hàng đợi cho nhu cầu phát lại rồi phát hiện dữ liệu đã biến mất.",
"Bốn yêu cầu đều chọn đúng mô hình, nêu đúng chỗ ghi tiến độ, và mô tả đúng hậu quả của cái chết giữa chừng ở cả bốn."),

(281,"Dead letter queue, poison messages and replay","TH","Lesson 280",
"Thông điệp hỏng là thông điệp mà bên tiêu thụ không xử lý được và sẽ không bao giờ xử lý được: sai định dạng, thiếu trường bắt buộc, tham chiếu tới bản ghi không tồn tại. Nếu chính sách là thử lại thì nó chặn cả phân vùng và thành một vòng lặp vô tận, đúng kiểu bão thử lại đã gặp ở lesson 61. Hàng đợi thư chết là chỗ chuyển những thông điệp đó ra khỏi đường chính, kèm ba thứ bắt buộc phải ghi cùng: nguyên nhân, số lần đã thử, và đủ ngữ cảnh để phát lại. Phân biệt ba loại lỗi và ba cách xử lý khác nhau: lỗi tạm thời thì thử lại có lùi theo hàm mũ, lỗi thông điệp thì đẩy sang thư chết, lỗi hệ thống hạ nguồn thì dừng tiêu thụ chứ đẩy sang thư chết vì sẽ đẩy nhầm cả luồng tốt. Phát lại từ thư chết sau khi sửa: điều kiện bắt buộc là bên tiêu thụ có tính bất biến, nếu không thì phát lại sinh trùng. Ngưỡng cảnh báo trên hàng đợi thư chết: tốc độ vào chứ tổng số, vì tổng số chỉ nói quá khứ.",
"Phân loại một lỗi tiêu thụ thành ba loại và cấu hình đúng cách xử lý cho từng loại, rồi phát lại được từ thư chết mà không sinh trùng.",
"Tầng *áp dụng*. Bài thực hành nối tiếp lesson 214 về vùng cách ly ở tầng theo lô, nay đặt lại trong ngữ cảnh luồng. Kiểm bằng lab có ba loại lỗi tiêm sẵn; đạt khi cả ba được định tuyến đúng và bản phát lại đối soát khớp tuyệt đối với bản đúng.",
"Trên một bên tiêu thụ có sẵn, tiêm ba loại lỗi: một thông điệp sai định dạng, một khoảng thời gian cơ sở dữ liệu đích không truy cập được, và một thông điệp tham chiếu khách hàng không tồn tại. Cấu hình để mỗi loại đi đúng đường. Sửa lỗi logic rồi phát lại toàn bộ thư chết; đối soát số bản ghi và tổng tiền với bản chạy đúng.",
"Đẩy lỗi hạ nguồn sang thư chết nên mất cả luồng tốt · thử lại vô hạn cho thông điệp hỏng · phát lại khi bên tiêu thụ chưa bất biến · cảnh báo theo tổng số thay vì tốc độ vào.",
"Ba loại lỗi đi đúng ba đường, phát lại xong đối soát khớp tuyệt đối, và hàng đợi thư chết có cảnh báo theo tốc độ vào."),

(282,"What a broker is not - database, orchestrator and processing engine","LT","Lesson 281",
"Ba cách dùng sai phổ biến, mỗi cách kèm dấu hiệu nhận biết sớm. Dùng broker làm cơ sở dữ liệu: giữ lưu giữ vĩnh viễn rồi truy vấn lịch sử bằng cách đọc lại từ đầu, hỏng vì không có chỉ mục nên mọi câu hỏi đều là quét toàn bộ, nối lại lesson 111 và 113. Dùng broker làm bộ điều phối: mã hoá thứ tự các bước bằng chuỗi hàng đợi nối nhau, hỏng vì không có chỗ nào nhìn thấy toàn bộ đồ thị, không chạy bù được, và trạng thái lần chạy nằm rải rác, đúng những thứ M21 đã dựng từ vựng để gọi tên. Dùng broker làm bộ xử lý: nhồi logic biến đổi vào bên tiêu thụ tới mức nó thành một công việc xử lý không có kiểm thử và không có khả năng chạy lại. Ranh giới nên giữ: broker chịu trách nhiệm vận chuyển và lưu giữ tạm có thứ tự; điều phối thuộc về M21 tới M25; biến đổi thuộc về M32 và M34; lưu trữ lâu dài thuộc về M33. Ba câu hỏi kiểm tra trước khi thêm một hàng đợi vào thiết kế.",
"Nhận ra trong một thiết kế cho trước chỗ nào đang dùng broker sai vai và nêu thành phần đúng phải nhận việc đó.",
"Tầng *phân tích*. Bài chốt module, người học đã có từ vựng điều phối từ M21 và từ vựng giao nhận từ năm bài trước, nên đủ để phán đoán ranh giới. Kiểm bằng bốn sơ đồ kiến trúc; đạt khi chỉ đúng ít nhất ba chỗ sai vai và nêu đúng thành phần thay thế.",
"Nhận bốn sơ đồ kiến trúc có thật về mặt cấu trúc. Với mỗi sơ đồ, chỉ ra chỗ broker đang làm việc của thành phần khác, nêu dấu hiệu quan sát được của cách dùng sai đó, và vẽ lại phần đó với thành phần đúng. Một trong bốn sơ đồ không sai; nhận ra và giải thích vì sao.",
"Nối hàng đợi thành chuỗi để thay cho đồ thị phụ thuộc · giữ lưu giữ vĩnh viễn rồi coi broker là kho lịch sử · kết luận sơ đồ nào cũng sai vì đang học bài về cách dùng sai.",
"Chỉ đúng ≥ 3/4 chỗ sai vai kèm dấu hiệu quan sát được, và nhận ra đúng sơ đồ không sai."),
]

M28 = ("RabbitMQ", 283, 290, """| | |
|---|---|
| **Objective cấp module** | Dựng và vận hành được kịch bản tham chiếu trên RabbitMQ ở mức `B`, đo bốn chỉ số của M30 và ghi lại bằng chứng |
| **Tiền đề** | M27 |
| **Exit criterion** | Kịch bản tham chiếu chạy đúng dưới cả ba lỗi cài sẵn, bốn chỉ số có số đo lặp lại được, và giải thích được định tuyến của mình bằng exchange, binding và khoá |
| **Kỹ năng SFIA** | `SYSP` mức 3 · `NTAS` mức 3 |
| **Chế độ hỏng** | Học cú pháp khai báo hàng đợi mà bỏ qua xác nhận và prefetch, rồi mất thông điệp hoặc làm bên tiêu thụ ngộp mà không biết vì sao |""",
"""Mức `B` theo quy ước ở mục 2: làm được lab và so sánh có căn cứ, không yêu cầu vận hành cụm sản xuất. RabbitMQ đứng trước Kafka vì mô hình hàng đợi ở lesson 280 dễ quan sát hơn mô hình nhật ký, và vì phần lớn hệ nội bộ ở Việt Nam bắt đầu từ một hàng đợi tác vụ chứ từ một nhật ký sự kiện.

Bốn chỉ số đo ở lesson 290 là bốn chỉ số M30 dùng để chấm: thông lượng ổn định, độ trễ đầu cuối ở phân vị 95, thời gian phục hồi sau khi giết tiến trình, và số thao tác để phát lại một ngày dữ liệu.""")

L28 = [
(283,"Architecture - exchange, queue, binding and the routing decision","LT","Module 28: M27",
"Bên gửi trong RabbitMQ không gửi vào hàng đợi mà gửi vào exchange, và chính chi tiết này quyết định mọi thứ còn lại. Bốn thành phần và trách nhiệm tách bạch: exchange nhận thông điệp và quyết định chuyển đi đâu, binding là luật nối exchange với hàng đợi, hàng đợi là chỗ thông điệp nằm chờ, bên tiêu thụ lấy ra. Hệ quả của việc tách: thêm một bên tiêu thụ mới là thêm một hàng đợi và một binding, **mã bên gửi không đổi**, đúng vấn đề ràng buộc số lượng ở lesson 277. Vhost và cách nó chia tách môi trường. Kênh và vì sao mở một kết nối rồi nhiều kênh trên đó, thay vì nhiều kết nối, nối lại chi phí bắt tay ở M4. Giao thức AMQP 0-9-1 ở mức đủ để đọc nhật ký lỗi. So chiếu với từ vựng M27: RabbitMQ là hiện thân của mô hình hàng đợi, nên lấy ra là biến mất, và phát lại phải tự dựng chứ có sẵn.",
"Vẽ được đường đi của một thông điệp từ bên gửi tới bên tiêu thụ, gọi đúng tên bốn thành phần và chỉ ra chỗ quyết định định tuyến xảy ra.",
"Tầng *hiểu*. Bài mở module, chưa có lab đủ để đòi vận hành, nên objective dừng ở tái hiện cơ chế. Kiểm bằng bài vẽ lại có chú thích; đạt khi cả bốn thành phần đúng vai và chỉ đúng chỗ định tuyến, không chấp nhận bản vẽ nối thẳng bên gửi vào hàng đợi.",
"Cài RabbitMQ bằng container, bật giao diện quản trị. Khai báo một exchange, hai hàng đợi, hai binding. Gửi năm thông điệp, quan sát trên giao diện chúng vào hàng đợi nào. Vẽ lại đường đi có chú thích bốn thành phần, rồi xoá một binding và dự đoán trước khi chạy xem thông điệp đi đâu.",
"Vẽ bên gửi nối thẳng vào hàng đợi · nhầm exchange với hàng đợi · mở một kết nối cho mỗi thao tác.",
"Bản vẽ gọi đúng bốn thành phần, chỉ đúng chỗ định tuyến, và dự đoán đúng đích của thông điệp sau khi xoá binding."),

(284,"Four exchange types and the routing key","TH","Lesson 283",
"Bốn kiểu exchange là bốn luật định tuyến khác nhau, và chọn kiểu chính là chọn hình dạng của hệ. Direct: khớp khoá định tuyến đúng từng ký tự, dùng cho hàng đợi tác vụ chia theo loại việc. Fanout: bỏ qua khoá, chuyển cho mọi hàng đợi đã nối, đây là cách RabbitMQ làm phát một nhận nhiều. Topic: khớp khoá theo mẫu có ký tự đại diện, cho phép bên tiêu thụ tự chọn lát dữ liệu mình quan tâm mà bên gửi không cần biết. Headers: khớp theo thuộc tính, ít dùng, tốn hơn. Thiết kế khoá định tuyến là một quyết định lâu dài: khoá dạng phân cấp từ rộng tới hẹp thì về sau thêm bên tiêu thụ mới không phải đổi bên gửi, còn khoá phẳng thì mọi thay đổi đều chạm vào bên gửi. Exchange mặc định và vì sao gửi thẳng theo tên hàng đợi là một lối tắt nên tránh trong mã sản xuất.",
"Chọn kiểu exchange và thiết kế khoá định tuyến cho một yêu cầu cho trước, rồi chứng minh thêm một bên tiêu thụ mới không phải sửa mã bên gửi.",
"Tầng *áp dụng*. Objective là quyết định thiết kế có ràng buộc kiểm được bằng thực nghiệm, nên kiểm bằng lab chứ bằng lý thuyết. Kiểm bằng việc thêm bên tiêu thụ thứ ba sau khi đã chốt thiết kế; đạt khi mã bên gửi không đổi một dòng.",
"Dựng ba kịch bản: chia việc theo loại, phát một nhận nhiều, và lọc theo lát. Với mỗi kịch bản chọn kiểu exchange và viết khoá định tuyến. Sau khi chạy xong, giảng viên thêm một yêu cầu tiêu thụ mới; thực hiện bằng cách chỉ thêm hàng đợi và binding. Ghi lại phần khác biệt của mã bên gửi trước và sau.",
"Dùng direct cho mọi thứ rồi phải sửa bên gửi mỗi lần thêm bên nhận · đặt khoá phẳng không phân cấp · gửi qua exchange mặc định trong mã sản xuất.",
"Ba kịch bản chọn đúng kiểu exchange, và phần khác biệt của mã bên gửi sau khi thêm bên tiêu thụ thứ ba bằng không."),

(285,"Acknowledgement, prefetch and flow control","TH","Lesson 284",
"Xác nhận là chỗ ngữ nghĩa giao nhận ở lesson 278 trở thành cấu hình cụ thể. Chế độ tự động xác nhận cho nhiều nhất một lần và mất thông điệp khi bên tiêu thụ chết; chế độ thủ công cho ít nhất một lần. Ba lệnh và ba hệ quả: xác nhận thì thông điệp biến mất; từ chối có trả lại thì thông điệp quay vào hàng đợi và có thể lặp vô tận; từ chối không trả lại thì thông điệp đi tiếp theo cấu hình thư chết ở lesson 281. Prefetch là số thông điệp broker giao trước cho một bên tiêu thụ mà chưa cần xác nhận, và đây là núm điều khiển áp lực ngược của RabbitMQ. Prefetch bằng không nghĩa là không giới hạn, nên một bên tiêu thụ chậm sẽ ôm toàn bộ hàng đợi vào bộ nhớ rồi chết, đúng hiện tượng hàng đợi không giới hạn ở M6. Prefetch bằng một cho phân phối đều nhất nhưng thông lượng thấp nhất; chọn giá trị là chọn điểm trên đường đánh đổi, và phải đo chứ đoán.",
"Đo được quan hệ giữa prefetch và hai đại lượng thông lượng và độ trễ phân vị 95, rồi chọn một giá trị có căn cứ từ số đo của chính mình.",
"Tầng *đánh giá*. Bài đòi chọn một điểm trên đường đánh đổi dựa trên dữ liệu tự đo, chứ áp dụng một quy tắc có sẵn. Kiểm bằng bảng số đo ít nhất bốn mức prefetch; đạt khi có đường cong, có điểm chọn, và lý do chọn dẫn từ số trong bảng.",
"Chạy bên tiêu thụ ở bốn mức prefetch: 1, 10, 100 và không giới hạn. Với mỗi mức, đo thông lượng ổn định và độ trễ phân vị 95 trên cùng một tải. Giết tiến trình bên tiêu thụ giữa chừng ở từng mức và đếm số thông điệp bị xử lý lại. Chọn một mức và viết ba câu bảo vệ lựa chọn, dẫn số từ bảng.",
"Để tự động xác nhận trong mã sản xuất · đặt prefetch không giới hạn · từ chối có trả lại cho thông điệp hỏng rồi tạo vòng lặp vô tận · chọn prefetch theo bài viết trên mạng thay vì theo số đo.",
"Bảng có đủ bốn mức với cả hai đại lượng, số thông điệp xử lý lại được đếm ở từng mức, và lý do chọn dẫn được ít nhất hai con số từ bảng."),

(286,"Durability - persistent messages, quorum queues and what survives a restart","TH","Lesson 285",
"Bốn thứ phải cùng bền thì thông điệp mới sống qua một lần khởi động lại, và thiếu một thứ là mất: hàng đợi khai báo bền, thông điệp đánh dấu bền, bên gửi bật xác nhận từ broker, và đĩa thực sự ghi xong. Ba thứ đầu là cấu hình, thứ tư là vật lý và nối thẳng về `fsync` ở M2. Xác nhận từ broker cho bên gửi: không có nó thì bên gửi tưởng đã gửi thành công trong khi broker chưa ghi, đây là chỗ mất thông điệp phổ biến nhất mà nhật ký không ghi lại gì. Hàng đợi quorum dùng đồng thuận Raft để giữ nhiều bản sao, đổi lấy thông lượng thấp hơn và tốn đĩa hơn; hàng đợi cổ điển nhanh hơn nhưng mất khi nút giữ nó chết. Phân biệt bền với sẵn sàng cao: bền là sống qua khởi động lại, sẵn sàng cao là vẫn phục vụ khi một nút chết, và hai thứ cần hai cấu hình khác nhau. Cái giá đo được: bật đủ bốn thứ làm thông lượng giảm, và bài lab đo mức giảm đó.",
"Cấu hình đủ bốn điều kiện bền và chứng minh bằng thực nghiệm rằng không thông điệp nào mất sau khi giết broker, kèm số đo mức giảm thông lượng.",
"Tầng *áp dụng*. Objective là một cấu hình kiểm được bằng thí nghiệm hỏng, đúng kiểu đã dùng ở lesson 218. Kiểm bằng phép đếm trước và sau khi giết tiến trình; đạt khi số thông điệp khớp tuyệt đối và bảng đánh đổi có số.",
"Gửi 10.000 thông điệp. Giết tiến trình broker giữa chừng bằng tín hiệu cứng, khởi động lại, đếm số thông điệp còn lại. Chạy lại thí nghiệm ở bốn cấu hình: không bền, chỉ hàng đợi bền, bền đủ bốn điều kiện, và hàng đợi quorum. Lập bảng bốn cấu hình với số mất và thông lượng.",
"Khai báo hàng đợi bền mà quên đánh dấu thông điệp bền · quên xác nhận từ broker cho bên gửi · nhầm bền với sẵn sàng cao · kết luận về độ bền mà chưa từng giết tiến trình.",
"Cấu hình bền đủ bốn điều kiện mất 0 thông điệp, và bảng bốn cấu hình có đủ số mất lẫn thông lượng."),

(287,"Dead letter exchange, TTL and delayed retry","TH","Lesson 286",
"RabbitMQ không có thử lại có lùi theo hàm mũ sẵn, nên phải dựng bằng cách ghép ba cơ chế, và chính việc phải tự ghép là một dữ kiện để M30 chấm. Exchange thư chết: hàng đợi khai báo chuyển thông điệp bị từ chối, hết hạn hoặc tràn sang một exchange khác. Thời gian sống đặt ở hai chỗ với nghĩa khác nhau: đặt trên hàng đợi là áp cho mọi thông điệp, đặt trên từng thông điệp là linh hoạt nhưng chỉ tính khi thông điệp tới đầu hàng đợi. Mẫu thử lại có độ trễ dựng từ hai thứ trên: thông điệp lỗi đi vào một hàng đợi chờ có thời gian sống, hết hạn thì thư chết đẩy ngược về hàng đợi chính, và số lần thử đếm bằng tiêu đề đính kèm. Dựng nhiều hàng đợi chờ với thời gian sống tăng dần cho ra lùi theo hàm mũ. Ba bẫy: thông điệp hết hạn chỉ được kiểm khi tới đầu hàng đợi nên hàng đợi dài làm độ trễ thực khác độ trễ cấu hình; vòng lặp thư chết khi cấu hình trỏ vòng lại chính nó; và đếm số lần thử bằng tiêu đề bị mất nếu tạo thông điệp mới thay vì chuyển tiếp.",
"Dựng được thử lại có lùi theo hàm mũ với số lần tối đa, và chứng minh bằng nhật ký rằng khoảng cách giữa các lần thử tăng đúng như thiết kế.",
"Tầng *sáng tạo*. Bài đòi ghép ba cơ chế rời thành một mẫu mà công cụ không cung cấp sẵn, nên cao hơn tầng áp dụng. Kiểm bằng nhật ký có dấu thời gian từng lần thử; đạt khi khoảng cách tăng đúng dãy thiết kế và thông điệp dừng đúng ở số lần tối đa.",
"Dựng chuỗi ba hàng đợi chờ với thời gian sống 5, 25 và 125 giây. Tiêm một thông điệp luôn lỗi và một thông điệp lỗi hai lần đầu rồi thành công. Đọc nhật ký, lập bảng dấu thời gian từng lần thử của cả hai. Chứng minh thông điệp luôn lỗi dừng ở lần thứ ba và nằm lại thư chết.",
"Cấu hình thư chết trỏ vòng về chính hàng đợi gốc · đặt thời gian sống trên thông điệp rồi ngạc nhiên vì nó không hết hạn đúng giờ · tạo thông điệp mới khi thử lại nên mất số đếm.",
"Bảng dấu thời gian cho thấy khoảng cách 5, 25, 125 giây, thông điệp luôn lỗi dừng đúng sau ba lần và nằm ở thư chết, thông điệp kia thành công ở lần ba."),

(288,"Consumer patterns - work queue, publish-subscribe and request-reply","TH","Lesson 287",
"Ba mẫu tiêu thụ và điều kiện áp dụng của từng mẫu. Hàng đợi tác vụ: nhiều bên tiêu thụ cùng đọc một hàng đợi, broker chia việc, dùng khi công việc nặng và không cần thứ tự giữa các việc; prefetch ở lesson 285 quyết định chia đều tới đâu. Phát một nhận nhiều: mỗi bên tiêu thụ một hàng đợi riêng nối vào fanout hoặc topic, dùng khi nhiều hệ cần cùng một sự kiện; đây là chỗ RabbitMQ khác mô hình nhật ký rõ nhất, vì bên tiêu thụ mới chỉ nhận được sự kiện từ lúc nó có hàng đợi trở đi, quá khứ đã mất. Yêu cầu và trả lời: bên gửi đính kèm hàng đợi trả lời và mã tương quan, bên nhận trả kết quả về đó; dùng được nhưng thường là dấu hiệu nên dùng lời gọi trực tiếp, và ba câu hỏi để quyết định. Mã tương quan nối lại mã theo dõi ở lesson 74. Mẫu nào cũng phải trả lời được câu hỏi bên tiêu thụ mới tham gia thì thấy được gì.",
"Chọn đúng mẫu cho một yêu cầu cho trước và nêu bên tiêu thụ tham gia sau thì thấy được gì, mất gì.",
"Tầng *đánh giá*. Bài đòi so ba mẫu trên cùng một yêu cầu và chọn có lý do, chuẩn bị trực tiếp cho M30. Kiểm bằng ba yêu cầu kèm câu hỏi về bên tiêu thụ tham gia sau; đạt khi chọn đúng cả ba và trả lời đúng phần quá khứ bị mất.",
"Dựng cả ba mẫu trên kịch bản tham chiếu. Với mẫu phát một nhận nhiều, thêm một bên tiêu thụ sau khi đã phát 1.000 sự kiện và đếm chính xác nó nhận được bao nhiêu. Ghi lại con số đó; lesson 296 sẽ đo lại cùng phép thử trên Kafka.",
"Dùng yêu cầu và trả lời cho việc lẽ ra gọi thẳng · tưởng bên tiêu thụ mới đọc được quá khứ · dùng một hàng đợi chung cho nhiều hệ rồi chúng tranh mất thông điệp của nhau.",
"Ba mẫu chạy được, và con số sự kiện mà bên tiêu thụ tham gia sau nhận được ghi đúng kèm giải thích vì sao bằng con số đó."),

(289,"Operating RabbitMQ - memory watermark, disk alarm and a stuck queue","TH","Lesson 288",
"Ba cơ chế bảo vệ tự động và điều người vận hành nhìn thấy khi chúng kích hoạt. Ngưỡng bộ nhớ: vượt thì broker chặn bên gửi, và triệu chứng là bên gửi treo chứ báo lỗi, nên dễ bị chẩn đoán nhầm thành lỗi mạng. Cảnh báo đĩa: còn dưới ngưỡng thì broker cũng chặn. Giới hạn độ dài hàng đợi: tràn thì bỏ thông điệp cũ nhất hoặc đẩy sang thư chết tuỳ cấu hình. Bốn nguyên nhân làm hàng đợi ứ, kèm cách phân biệt bằng số đo: không có bên tiêu thụ, bên tiêu thụ chậm hơn bên gửi, bên tiêu thụ nhận rồi không xác nhận, và thông điệp hỏng chặn đầu. Ba chỉ số phải theo dõi liên tục: độ sâu hàng đợi, tốc độ vào trừ tốc độ ra, và số thông điệp chưa xác nhận. Vì sao cảnh báo theo tốc độ chênh lệch báo sớm hơn cảnh báo theo độ sâu, cùng nguyên tắc ngưỡng động ở tầng theo lô. Sổ tay xử lý cho ba tình huống hay gặp nhất.",
"Chẩn đoán một hàng đợi đang ứ về đúng một trong bốn nguyên nhân, dẫn bằng số đo, và thực hiện đúng bước khắc phục.",
"Tầng *phân tích*. Bài vận hành, người học đã có đủ cơ chế từ năm bài trước để suy ra nguyên nhân từ triệu chứng. Kiểm bằng bốn sự cố tiêm sẵn tính giờ; đạt khi chẩn đoán đúng ít nhất ba trong giới hạn thời gian và mỗi lần dẫn được số đo.",
"Giảng viên tiêm lần lượt bốn tình huống ứ, mỗi lần 10 phút. Với mỗi tình huống, ghi lại ba chỉ số, nêu nguyên nhân, thực hiện khắc phục, và xác nhận hàng đợi rút về bình thường. Đẩy bộ nhớ vượt ngưỡng một lần và ghi lại chính xác bên gửi biểu hiện thế nào.",
"Chẩn đoán treo bên gửi thành lỗi mạng · cảnh báo theo độ sâu nên biết quá muộn · xoá hàng đợi để dọn thay vì tìm nguyên nhân · bỏ qua số thông điệp chưa xác nhận.",
"Chẩn đoán đúng ≥ 3/4 tình huống trong giới hạn thời gian, mỗi lần dẫn số đo, và mô tả đúng biểu hiện của bên gửi khi vượt ngưỡng bộ nhớ."),

(290,"RabbitMQ on the reference scenario - measure and record the evidence","TH","Lesson 289",
"Bài khép module: dựng trọn kịch bản tham chiếu ở M27 và ghi lại bằng chứng cho M30. Sự kiện đơn hàng từ PostgreSQL của pipeline lesson 217, hai bên tiêu thụ độc lập là bộ nạp mart và bộ kiểm gian lận, ba lỗi cài sẵn gồm một thông điệp trùng, một thông điệp tới sai thứ tự và một thông điệp hỏng. Bốn chỉ số phải đo, mỗi chỉ số kèm cách đo lặp lại được: thông lượng ổn định tính trên cửa sổ năm phút sau khi bỏ một phút đầu, độ trễ đầu cuối phân vị 95 đo từ dấu thời gian sinh sự kiện tới dấu thời gian ghi vào mart, thời gian phục hồi tính từ lúc giết tiến trình tới lúc tốc độ ra trở lại mức trước đó, và số thao tác để phát lại một ngày dữ liệu. Yêu cầu về bằng chứng: mỗi số phải kèm lệnh hoặc ảnh chụp tái lập được, vì lesson 261 đã đặt luật là mọi ô trong ma trận so sánh phải truy được về lab của chính mình. Phần khó riêng của RabbitMQ: phát lại một ngày không có sẵn nên phải ghi rõ cách mình tự dựng và chi phí của cách đó.",
"Dựng xong kịch bản tham chiếu trên RabbitMQ, chạy đúng dưới cả ba lỗi cài sẵn, và nộp bốn chỉ số kèm cách đo lặp lại được.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hệ chạy được và một bộ bằng chứng, cao hơn tầng áp dụng vì phải tự thiết kế cách phát lại mà công cụ không cung cấp. Kiểm bằng rà soát chéo: một học viên khác chạy lại phép đo của bạn trên lab của họ; đạt khi cả bốn số tái lập được trong sai số 20%.",
"Dựng trọn kịch bản. Chạy dưới ba lỗi cài sẵn và chứng minh mart cuối không trùng, không thiếu, đúng thứ tự trạng thái đơn. Đo bốn chỉ số, ghi mỗi số kèm lệnh tái lập. Đổi hồ sơ đo với một học viên khác và chạy lại phép đo của họ.",
"Đo ngay phút đầu khi hệ chưa ổn định · báo thông lượng đỉnh thay vì thông lượng ổn định · ghi số mà không ghi cách đo · bỏ qua chỉ số phát lại vì RabbitMQ không có sẵn.",
"Mart cuối đúng dưới cả ba lỗi, bốn chỉ số đều có cách đo kèm theo, và ≥ 3/4 số tái lập được trong sai số 20% khi người khác đo lại."),
]
