# -*- coding: utf-8 -*-
"""DE M3 — Operating systems and Linux."""

M3 = ("Operating Systems and Linux", 18, 29, """| | |
|---|---|
| **Objective cấp module** | Nhận một sự cố pipeline chậm hoặc chết và chứng minh bằng số đo nó nghẽn ở bộ xử lý, bộ nhớ, đĩa hay mạng |
| **Tiền đề** | M2 |
| **Exit criterion** | Đạt Cổng 1 ≥ 70/100: chẩn đoán đúng bốn ca sự cố dựng sẵn, mỗi ca dẫn được số đo làm bằng chứng |
| **Kỹ năng SFIA** | `SYSP` mức 3 · `USUP` mức 2 |
| **Chế độ hỏng** | Học thuộc danh sách lệnh mà không bao giờ diễn tập sự cố, nên lúc hệ thống thật hỏng thì gõ lệnh ngẫu nhiên |""",
"Bảy bài đầu là cơ chế hệ điều hành, bốn bài giữa là công cụ dòng lệnh, bài cuối là cổng 1. Mọi cơ chế đều được kiểm bằng một diễn tập sự cố chứ không bằng câu hỏi lý thuyết, vì đây là module mà kiến thức chỉ có giá trị lúc hệ thống đang hỏng.")

L3 = [
(18,"Kernel space, user space and the system call boundary","LT","Module 3: M2",
"Hai không gian đặc quyền và lý do tách: một tiến trình lỗi không được phép làm sập máy. Lời gọi hệ thống là cổng duy nhất để chương trình yêu cầu nhân làm việc, và mọi thao tác đọc tệp, gửi mạng, cấp phát bộ nhớ đều đi qua đó. Chi phí một lời gọi hệ thống so với một lời gọi hàm thường, theo thang bậc độ lớn ở lesson 10. Hệ quả trực tiếp cho công việc dữ liệu: đọc tệp từng byte gọi hệ thống một triệu lần, đọc theo khối gọi một nghìn lần, và chênh lệch đó lớn hơn chênh lệch do đĩa. Theo dõi lời gọi hệ thống của một tiến trình để biết nó thật sự làm gì, kỹ thuật dùng khi mã nguồn không sẵn hoặc nhật ký không đủ. Trình điều khiển thiết bị và hệ tệp ảo: vì sao mọi thứ trong Linux trình bày được như tệp, gồm cả thông tin tiến trình và thiết bị.",
"Đếm số lời gọi hệ thống của hai cách đọc cùng một tệp, và giải thích chênh lệch thời gian bằng số đếm đó.",
"Tầng *phân tích*. Objective đòi nối một số đếm với một chênh lệch thời gian, không chỉ nhắc lại định nghĩa. Kiểm bằng báo cáo có hai cột số: số lời gọi hệ thống và thời gian, cho ít nhất ba kích thước khối đọc. Đạt khi chỉ ra được quan hệ giữa hai cột và ước lượng được chi phí trung bình một lời gọi.",
"Đọc một tệp 500 mê ga byte theo bốn kích thước khối: 1 byte, 512 byte, 4 ki lô byte, 1 mê ga byte. Với mỗi cách, đếm lời gọi hệ thống bằng công cụ theo dõi và đo thời gian. Lập bảng và ước lượng chi phí một lời gọi.",
"Theo dõi lời gọi hệ thống trên tải thật rồi tưởng số đo là bình thường, trong khi công cụ theo dõi làm chậm tiến trình nhiều lần · đọc từng byte rồi đổ lỗi cho đĩa · bỏ qua bộ đệm của thư viện khi đếm.",
"Bảng bốn kích thước khối có cả số lời gọi lẫn thời gian, và ước lượng chi phí một lời gọi nằm trong phạm vi một bậc so với thang ở lesson 10."),

(19,"Processes, threads and the scheduler","LT","Lesson 18",
"Tiến trình có không gian địa chỉ riêng, luồng dùng chung không gian địa chỉ của tiến trình. Hệ quả: luồng trao đổi dữ liệu rẻ nhưng làm hỏng nhau dễ, tiến trình thì ngược lại. Cây tiến trình, tiến trình cha con, và tiến trình mồ côi bị nhận nuôi. Tiến trình xác sống: cơ chế sinh ra và vì sao nó không tốn tài nguyên nhưng vẫn là dấu hiệu mã sai. Bộ lập lịch hoàn toàn công bằng và ý niệm thời gian chạy ảo. Độ ưu tiên và giá trị nhường. Trạng thái tiến trình và ý nghĩa vận hành của từng trạng thái, trong đó trạng thái ngủ không ngắt được là trạng thái đáng lo nhất vì nó thường nghĩa là đang chờ vào ra và không giết được. Trung bình tải là gì và vì sao nó không phải phần trăm dùng bộ xử lý, một hiểu nhầm phổ biến dẫn tới chẩn đoán sai. Mối liên hệ tới chặng sau: mỗi tiến trình thực thi của công cụ điều phối là một tiến trình, và giới hạn số luồng của nó là bài toán ở lesson 12.",
"Đọc trạng thái và trung bình tải của một máy đang chạy và kết luận nó nghẽn ở đâu, phân biệt với trường hợp chỉ có nhiều tiến trình đang ngủ.",
"Tầng *phân tích*. Objective là chẩn đoán từ số đo, và bẫy chính là nhầm trung bình tải với mức dùng bộ xử lý. Kiểm bằng ba ca: một nghẽn bộ xử lý thật, một trung bình tải cao do chờ vào ra, một nhiều tiến trình ngủ. Đạt khi phân loại đúng cả ba và giải thích được vì sao trung bình tải không đủ để kết luận.",
"Dựng ba ca tải trên máy ảo. Với mỗi ca đọc trung bình tải, bảng trạng thái tiến trình và mức dùng bộ xử lý theo từng lõi. Kết luận. Sau đó tạo một tiến trình xác sống và một tiến trình mồ côi, quan sát cây tiến trình.",
"Kết luận quá tải bộ xử lý từ trung bình tải · cố giết tiến trình ở trạng thái ngủ không ngắt được · đọc mức dùng bộ xử lý tổng mà không xem theo từng lõi.",
"Phân loại đúng cả ba ca, và giải thích được vì sao trung bình tải cao không đồng nghĩa nghẽn bộ xử lý."),

(20,"File descriptors, pipes and redirection","TH","Lesson 19",
"Bộ mô tả tệp là số nguyên trỏ tới một mục trong bảng của tiến trình, và ba bộ mô tả mặc định. Mọi thứ đọc ghi được đều có bộ mô tả: tệp, ống dẫn, ổ cắm mạng, thiết bị. Giới hạn số bộ mô tả mỗi tiến trình, và lỗi hết bộ mô tả: triệu chứng, nguyên nhân thường gặp là rò rỉ do không đóng kết nối, và cách xác nhận bằng cách liệt kê bộ mô tả đang mở. Ống dẫn nối đầu ra của tiến trình này vào đầu vào của tiến trình kia, và vì sao một chuỗi ống dẫn chạy song song chứ không tuần tự. Áp lực ngược trong ống dẫn: tiến trình đọc chậm làm tiến trình ghi bị chặn, và đây là cơ chế điều tiết tự nhiên, cùng ý tưởng với áp lực ngược trong hệ thống luồng ở chặng 6. Chuyển hướng đầu ra và đầu lỗi, cùng lỗi phổ biến khi gộp hai luồng sai thứ tự. Mã thoát của một chuỗi ống dẫn mặc định lấy từ lệnh cuối, và hệ quả là lỗi ở giữa chuỗi bị nuốt mất.",
"Dựng một chuỗi ống dẫn xử lý dữ liệu lớn hơn bộ nhớ, và chứng minh lỗi ở giữa chuỗi không bị nuốt mất.",
"Tầng *áp dụng*. Objective có sản phẩm chạy được và một tiêu chí đúng sai tuyệt đối về lan truyền lỗi. Đạt khi chuỗi xử lý xong tệp lớn hơn bộ nhớ và khi bơm lỗi vào lệnh giữa chuỗi thì mã thoát khác không. Chuỗi chạy được mà nuốt lỗi thì không đạt.",
"Dựng chuỗi ống dẫn lọc, biến đổi và gộp một tệp 5 ghi ga byte trên máy có 2 ghi ga byte bộ nhớ. Bơm lỗi vào lệnh giữa chuỗi, xác nhận mã thoát khác không. Viết chương trình rò rỉ bộ mô tả tệp, quan sát tới khi hết giới hạn.",
"Gộp đầu lỗi vào đầu ra sai thứ tự nên mất thông báo lỗi · tin mã thoát của chuỗi ống dẫn mà không bật chế độ bắt lỗi giữa chuỗi · mở kết nối trong vòng lặp mà không đóng.",
"Chuỗi xử lý xong tệp lớn hơn bộ nhớ, và lỗi bơm vào lệnh giữa chuỗi làm mã thoát khác không."),

(21,"Signals and what happens when a process is killed","TH","Lesson 19",
"Tín hiệu là cơ chế thông báo không đồng bộ tới tiến trình. Nhóm tín hiệu quan trọng cho công việc dữ liệu: yêu cầu kết thúc lịch sự, ngắt từ bàn phím, kết thúc cưỡng bức không chặn được, treo, và tín hiệu người dùng tự định nghĩa. Bắt tín hiệu và dọn dẹp trước khi thoát: đóng kết nối, ghi nốt bộ đệm, xoá tệp tạm, cập nhật điểm kiểm tra. Vì sao tín hiệu kết thúc cưỡng bức không bắt được, và hệ quả là mọi thiết kế phải chịu được việc bị dừng đột ngột ở bất kỳ điểm nào. Trình tự dừng lịch sự chuẩn: gửi yêu cầu kết thúc, chờ một khoảng, rồi mới cưỡng bức, và đây chính là trình tự công cụ điều phối vùng chứa dùng. Nhóm tiến trình và cơ chế tín hiệu tới cả nhóm, lý do một tiến trình con có thể sống sót khi cha chết. Mối liên hệ tới ghi nguyên tử ở lesson 16: bị giết giữa chừng là ca kiểm thử bắt buộc, không phải ca hiếm.",
"Viết một tiến trình xử lý dữ liệu dừng lịch sự khi nhận yêu cầu kết thúc, và chứng minh nó không để lại trạng thái dở khi bị giết cưỡng bức.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm chứng bằng thực nghiệm lặp lại. Đạt khi 20 lần giết ở thời điểm ngẫu nhiên không lần nào để lại tệp dở hoặc bản ghi trùng, và khi tiến trình ghi được nhật ký dọn dẹp ở trường hợp kết thúc lịch sự.",
"Viết tiến trình đọc một triệu bản ghi và ghi ra tệp, có bắt tín hiệu để ghi điểm kiểm tra. Giết lịch sự 10 lần và cưỡng bức 10 lần ở thời điểm ngẫu nhiên. Sau mỗi lần, chạy lại từ điểm kiểm tra và đối soát tổng số bản ghi.",
"Bắt tín hiệu rồi làm việc nặng trong hàm xử lý tín hiệu · giả định chỉ bị dừng lịch sự · ghi điểm kiểm tra sau khi ghi dữ liệu nên chạy lại bị trùng.",
"20 lần giết không lần nào để lại tệp dở hay bản ghi trùng, và tổng bản ghi sau chạy lại luôn khớp."),

(22,"The page cache and why the second read is fast","TH","Lesson 18",
"Bộ đệm trang giữ nội dung tệp vừa đọc trong bộ nhớ trống, nên lần đọc thứ hai không chạm đĩa. Hệ quả cho phép đo: mọi con số đo hiệu năng đĩa đều vô nghĩa nếu không khai báo bộ đệm nóng hay nguội, nối lại nguyên tắc ở lesson 17. Cách xoá bộ đệm trước khi đo. Bộ nhớ trống theo báo cáo hệ điều hành gồm cả bộ đệm trang, nên con số bộ nhớ trống thấp thường không phải vấn đề, một hiểu nhầm dẫn tới việc mua thêm RAM không cần thiết. Ghi trả sau và cửa sổ mất dữ liệu nó tạo ra, nối lại lesson 16. Gợi ý cho nhân về mẫu truy cập tệp và khi nào đáng dùng. Đọc trước tuần tự và vì sao nó làm đọc tuần tự nhanh hơn dự đoán từ số đo đĩa thuần. Ánh xạ tệp vào bộ nhớ dùng chung cơ chế bộ đệm trang. Hệ quả ở chặng sau: cơ sở dữ liệu có bộ đệm riêng, nên có hai tầng đệm chồng nhau và cấu hình sai làm dữ liệu nằm hai nơi tốn gấp đôi bộ nhớ.",
"Đo cùng một phép đọc ở trạng thái đệm nguội và đệm nóng, và giải thích con số bộ nhớ trống của hệ điều hành cho một máy đang chạy.",
"Tầng *áp dụng*. Objective gồm một phép đo có kiểm soát và một phép đọc số liệu hệ thống. Đạt khi chênh lệch nóng nguội đo được và khi người học phân tách đúng con số bộ nhớ thành phần dùng thật, phần đệm, và phần trống thật, trên một máy có tải.",
"Đo đọc một tệp 2 ghi ga byte ở trạng thái nguội và nóng, lặp ba lần mỗi trạng thái. Đọc và phân tách con số bộ nhớ của máy. Chạy một tải đọc nhiều tệp, quan sát bộ đệm trang lớn dần và bộ nhớ trống nhỏ dần.",
"Đo hiệu năng đĩa mà quên xoá bộ đệm · báo động vì bộ nhớ trống thấp trong khi phần lớn là bộ đệm · cấu hình bộ đệm cơ sở dữ liệu bằng toàn bộ RAM rồi máy rơi vào hoán đổi.",
"Chênh lệch nóng nguội có số đo ba lần mỗi trạng thái, và phân tách đúng ba phần của con số bộ nhớ."),

(23,"Users, groups, permissions and ACLs","TH","Lesson 18",
"Định danh người dùng và nhóm, quyền đọc ghi thực thi cho chủ sở hữu, nhóm và người khác. Ý nghĩa của quyền thực thi trên thư mục khác hẳn trên tệp: nó cho phép đi vào chứ không phải chạy. Mặt nạ tạo tệp và vì sao tệp mới có quyền khác mong đợi. Bit đặt định danh nhóm trên thư mục để tệp mới thừa kế nhóm, mẫu dùng cho thư mục dữ liệu nhiều người ghi. Danh sách kiểm soát truy cập khi mô hình ba nhóm không đủ. Quyền bị từ chối là một trong năm sự cố diễn tập bắt buộc, và quy trình chẩn đoán: kiểm quyền trên tệp, rồi quyền thực thi trên từng thư mục cha, rồi định danh mà tiến trình thật sự chạy dưới. Tài khoản dịch vụ và nguyên tắc đặc quyền tối thiểu: tiến trình pipeline không chạy dưới quyền quản trị, và lý do đây là điều kiện bắt buộc chứ không phải khuyến nghị. Hệ quả ở chặng 7: định danh trong vùng chứa và chuyện tệp ghi ra máy chủ thuộc về ai.",
"Chẩn đoán một lỗi quyền bị từ chối tới đúng nguyên nhân trong ba nguyên nhân khả dĩ, và thiết lập thư mục dữ liệu nhiều người ghi mà tệp mới thừa kế đúng nhóm.",
"Tầng *phân tích*. Objective là chẩn đoán phân biệt, vì triệu chứng giống nhau ở cả ba nguyên nhân. Kiểm bằng ba ca: thiếu quyền trên tệp, thiếu quyền thực thi trên thư mục cha, và tiến trình chạy dưới định danh khác dự kiến. Đạt khi định vị đúng cả ba và dẫn được lệnh kiểm chứng.",
"Dựng ba ca quyền bị từ chối. Với mỗi ca chẩn đoán và sửa, ghi lại lệnh kiểm chứng. Sau đó dựng một thư mục dữ liệu cho hai tài khoản dịch vụ cùng ghi, cấu hình sao cho tệp mới luôn thừa kế đúng nhóm và quyền.",
"Sửa bằng cách cấp quyền cho tất cả · chạy pipeline dưới quyền quản trị cho nhanh · quên kiểm quyền thực thi trên thư mục cha.",
"Định vị đúng cả ba nguyên nhân có lệnh kiểm chứng, và thư mục nhiều người ghi cho tệp mới thừa kế đúng nhóm."),

(24,"Namespaces and cgroups - the mechanism under containers","LT","Lesson 23",
"Không gian tên cô lập cái tiến trình nhìn thấy: tiến trình, điểm gắn hệ tệp, mạng, định danh người dùng, tên máy. Nhóm điều khiển giới hạn cái tiến trình dùng được: bộ xử lý, bộ nhớ, vào ra, số tiến trình. Hai cơ chế này cộng lại là vùng chứa; vùng chứa không phải máy ảo, và khác biệt then chốt là dùng chung nhân. Hệ quả vận hành quan trọng nhất: giới hạn bộ nhớ của nhóm điều khiển gây ra cơ chế giết tiến trình ở lesson 14 nhưng chỉ trong phạm vi nhóm, nên một vùng chứa chết vì cạn bộ nhớ trong khi máy chủ còn thừa RAM. Giới hạn bộ xử lý theo hạn ngạch và cơ chế điều tiết: tiến trình không bị chậm đều mà bị dừng từng đợt, nên biểu đồ độ trễ có gai thay vì dốc lên đều. Đọc thông số nhóm điều khiển từ bên trong tiến trình và vì sao một số môi trường chạy đọc nhầm số lõi của máy chủ thay vì hạn ngạch, dẫn tới đặt số luồng sai. Mối liên hệ tới lesson 12 và tới chặng 7.",
"Giải thích vì sao một tiến trình bị giết vì cạn bộ nhớ trong khi máy chủ còn RAM trống, và vì sao độ trễ có gai khi bị điều tiết bộ xử lý.",
"Tầng *hiểu*. Bài lý thuyết đặt nền cho chặng 7, người học chưa dựng vùng chứa nên objective dừng ở giải thích cơ chế. Kiểm bằng hai ca dựng sẵn bằng nhóm điều khiển trực tiếp, không qua công cụ vùng chứa; đạt khi giải thích đúng cả hai hiện tượng và chỉ ra được thông số nhóm điều khiển tương ứng.",
"Dùng nhóm điều khiển trực tiếp, không qua công cụ vùng chứa. Đặt giới hạn bộ nhớ 256 mê ga byte cho một tiến trình rồi cho nó cấp phát tới khi bị giết, trong khi máy còn nhiều RAM. Đặt hạn ngạch bộ xử lý 20% rồi đo độ trễ theo thời gian, quan sát gai.",
"Nhầm vùng chứa với máy ảo · đặt số luồng theo số lõi máy chủ trong khi hạn ngạch thấp hơn nhiều · kết luận máy chủ hết bộ nhớ khi thấy vùng chứa bị giết.",
"Giải thích đúng cả hai hiện tượng và chỉ đúng thông số nhóm điều khiển gây ra từng cái."),

(25,"The shell - quoting, expansion and the errors they cause","TH","Lesson 20",
"Thứ tự vỏ lệnh xử lý một dòng: khai triển ngoặc, khai triển ký hiệu thư mục nhà, khai triển tham số, thay thế lệnh, khai triển số học, tách từ, rồi khai triển tên tệp. Thứ tự này giải thích gần như mọi lỗi vỏ lệnh khó hiểu. Tách từ là nguồn lỗi lớn nhất: một biến chứa khoảng trắng không đặt trong nháy kép bị tách thành nhiều tham số, nên đường dẫn có dấu cách làm hỏng script. Nháy đơn so với nháy kép: cái nào chặn khai triển nào. Ký tự đại diện khớp tên tệp trước khi lệnh chạy, nên lệnh nhận danh sách đã khai triển và không biết ký tự đại diện tồn tại. Trường hợp danh sách tệp dài quá giới hạn tham số và cách vòng qua. Biến môi trường so với biến vỏ lệnh và cách chúng truyền hoặc không truyền xuống tiến trình con. Mã thoát và ba cờ bắt lỗi nên bật đầu mọi script. Vì sao phân tích đầu ra của lệnh liệt kê tệp là mẫu sai.",
"Sửa một script hỏng khi gặp đường dẫn có dấu cách và khi thư mục rỗng, và giải thích lỗi bằng thứ tự khai triển.",
"Tầng *phân tích*. Objective đòi truy lỗi về đúng chặng trong thứ tự khai triển, không chỉ sửa cho chạy. Kiểm bằng bốn script hỏng theo bốn cơ chế khác nhau; đạt khi sửa được cả bốn và nêu đúng chặng khai triển gây ra ít nhất ba trong bốn.",
"Nhận bốn script hỏng: một do biến không đặt nháy, một do ký tự đại diện không khớp gì, một do thay thế lệnh nuốt dòng mới, một do phân tích đầu ra lệnh liệt kê tệp. Sửa cả bốn, nêu chặng khai triển gây lỗi. Chạy trên thư mục có tên tệp chứa dấu cách và ký tự tiếng Việt.",
"Không đặt biến trong nháy kép · bỏ qua trường hợp thư mục rỗng nên ký tự đại diện thành chuỗi nguyên văn · viết script không bật cờ bắt lỗi.",
"Bốn script chạy đúng trên thư mục có tên tệp chứa dấu cách và tiếng Việt, và nêu đúng chặng khai triển cho ít nhất ba lỗi."),

(26,"Text processing - grep, awk, sed, sort, xargs, jq","TH","Lesson 25",
"Công cụ dòng lệnh xử lý dữ liệu lớn hơn bộ nhớ vì chúng chạy theo luồng, nên một chuỗi ống dẫn thường nhanh hơn nạp cả tệp vào công cụ phân tích. Biểu thức chính quy và ba mức độ hỗ trợ khác nhau giữa các công cụ. Công cụ xử lý theo trường: mô hình mẫu và hành động, biến dựng sẵn, và các phép gộp viết được chỉ bằng một dòng. Công cụ biên tập theo luồng cho thay thế và xoá dòng. Sắp xếp ngoài bộ nhớ: cơ chế chia tệp thành mảnh, sắp từng mảnh rồi trộn, đây chính là sắp xếp ngoài ở lesson 33 và là cơ chế Spark dùng khi tràn ra đĩa. Vì sao vị trí ngôn ngữ ảnh hưởng thứ tự sắp và làm phép nối hai tệp đã sắp bị sai. Truyền danh sách tham số an toàn khi tên tệp chứa ký tự đặc biệt. Xử lý JSON theo luồng cho tệp lớn. Đếm và đối soát bằng dòng lệnh như phép kiểm chéo độc lập với pipeline, một thói quen dùng suốt chương trình.",
"Trả lời năm câu hỏi nghiệp vụ trên một tệp nhật ký 10 ghi ga byte chỉ bằng chuỗi ống dẫn, trên máy có 4 ghi ga byte bộ nhớ.",
"Tầng *áp dụng*. Objective có ràng buộc cứng về bộ nhớ nên kiểm được bằng chạy thật. Đạt khi cả năm câu trả lời đúng so với đáp án đối chứng và không lệnh nào bị giết vì cạn bộ nhớ. Kết quả đúng mà phải nạp cả tệp vào bộ nhớ thì không đạt.",
"Nhận tệp nhật ký 10 ghi ga byte trên máy giới hạn 4 ghi ga byte. Trả lời năm câu: số yêu cầu theo giờ, 10 đường dẫn chậm nhất theo phân vị 95, tỉ lệ lỗi theo mã trạng thái, số người dùng phân biệt, và khoảng thời gian có gai lỗi. Đối chiếu với đáp án.",
"Nạp cả tệp rồi bị giết vì cạn bộ nhớ · sắp xếp mà quên đặt vị trí ngôn ngữ nên phép nối sai · dùng biểu thức chính quy tham lam khớp quá nhiều mà không phát hiện.",
"Năm câu trả lời khớp đáp án đối chứng, và không lệnh nào bị giết vì cạn bộ nhớ."),

(27,"Writing a shell script that fails loudly","TH","Lesson 26",
"Script im lặng khi hỏng là chế độ hỏng nguy hiểm nhất của tự động hoá, vì nó tạo ra niềm tin sai rằng công việc đã chạy. Ba cờ bắt lỗi và đúng cái mỗi cờ bắt: dừng khi lệnh lỗi, dừng khi dùng biến chưa đặt, và lan lỗi qua chuỗi ống dẫn, cờ thứ ba chữa đúng vấn đề ở lesson 20. Bẫy dọn dẹp chạy khi thoát bất kể lý do, và cách dùng nó để xoá tệp tạm và nhả khoá. Khoá tệp để chặn hai lần chạy chồng nhau, mẫu bắt buộc cho công việc theo lịch, và là vấn đề mà công cụ điều phối ở chặng 5 giải bằng cơ chế khác. Ghi nhật ký có dấu thời gian và mã định danh lần chạy, để nối được nhật ký của một lần chạy khi nhiều lần chạy xen kẽ. Mã thoát có nghĩa và quy ước dùng dải nào. Kiểm tra điều kiện tiên quyết đầu script. Tham số hoá bằng biến môi trường có giá trị mặc định. Vì sao script quá 100 dòng nên chuyển sang Python, và tiêu chí chuyển.",
"Viết một script theo lịch mà khi hỏng thì dừng ngay và báo, không chạy tiếp âm thầm, và không bao giờ có hai lần chạy chồng nhau.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm bơm lỗi. Đạt khi năm kịch bản hỏng đều làm script dừng với mã thoát khác không và ghi nhật ký nêu nguyên nhân, và khi chạy đồng thời hai lần thì lần thứ hai từ chối chạy. Script chạy đúng ở đường thuận không chứng minh được gì.",
"Viết script nạp dữ liệu có kiểm tra điều kiện tiên quyết, khoá tệp, bẫy dọn dẹp và nhật ký có mã định danh lần chạy. Bơm năm lỗi: thiếu biến môi trường, tệp nguồn không tồn tại, lệnh giữa chuỗi ống dẫn lỗi, hết dung lượng đĩa, và bị giết giữa chừng. Chạy đồng thời hai lần.",
"Quên cờ lan lỗi qua chuỗi ống dẫn nên lỗi giữa chuỗi bị nuốt · dọn dẹp ở cuối script nên không chạy khi thoát sớm · khoá bằng tệp mà không xoá khi bị giết.",
"Năm kịch bản hỏng đều dừng với mã thoát khác không và nhật ký nêu nguyên nhân, và lần chạy thứ hai bị từ chối."),

(28,"Observing a running system - top, vmstat, iostat, ss, lsof","TH","Lesson 22",
"Bốn tài nguyên và công cụ đọc từng cái, cùng chỉ số nào trong mỗi công cụ thật sự có nghĩa. Bộ xử lý: phân tách thời gian người dùng, thời gian nhân, thời gian chờ vào ra và thời gian bị đánh cắp, trong đó chờ vào ra cao nghĩa là nghẽn đĩa chứ không phải nghẽn bộ xử lý. Bộ nhớ: phân tách dùng thật, bộ đệm, và hoán đổi, nối lại lesson 22. Đĩa: mức dùng, độ sâu hàng đợi, thời gian phục vụ, trong đó mức dùng 100% không nhất thiết là bão hoà với ổ thể rắn. Mạng: kết nối theo trạng thái, hàng đợi gửi và nhận, và số kết nối ở trạng thái chờ đóng. Liên kết ngược từ số đo về tiến trình: tệp nào đang mở, ổ cắm nào thuộc tiến trình nào. Quy trình phân loại bốn bước cho một sự cố chậm, theo thứ tự loại trừ. Nguyên tắc: ghi lại số đo trước khi sửa, vì sửa xong thì không còn bằng chứng.",
"Phân loại một sự cố chậm về đúng một trong bốn tài nguyên bằng quy trình bốn bước, và dẫn số đo làm bằng chứng.",
"Tầng *phân tích*. Objective là chẩn đoán có bằng chứng, chuẩn bị trực tiếp cho cổng. Kiểm bằng bốn ca, mỗi ca nghẽn một tài nguyên; đạt khi phân loại đúng ít nhất ba trên bốn và mỗi lần dẫn được ít nhất hai số đo độc lập. Đoán đúng mà chỉ dẫn một số đo thì tính là chưa vững.",
"Dựng bốn ca tải nghẽn bốn tài nguyên khác nhau. Với mỗi ca chạy quy trình bốn bước, ghi số đo trước khi kết luận. Lập sổ tay một trang: triệu chứng, lệnh chạy, chỉ số cần đọc, kết luận rút ra.",
"Đọc mức dùng bộ xử lý tổng mà bỏ qua thời gian chờ vào ra · kết luận đĩa bão hoà từ mức dùng 100% trên ổ thể rắn · sửa trước rồi mới đo nên mất bằng chứng.",
"Phân loại đúng ít nhất ba trên bốn ca, mỗi lần có ít nhất hai số đo độc lập, và nộp sổ tay một trang."),

(29,"Gate 1 - prove whether a slow pipeline is CPU, RAM, disk or network","KT","Lesson 28",
"Không có nội dung mới. Cổng 1 của chương trình, đo năng lực chẩn đoán trên hệ thống đang chạy.",
"Nhận bốn sự cố chưa từng thấy và chứng minh bằng số đo mỗi sự cố nghẽn ở tài nguyên nào, rồi đề xuất một thay đổi kèm dự đoán định lượng về tác động.",
"Tầng *đánh giá*. Cổng đo chẩn đoán và quyết định dưới ràng buộc thời gian, không đo trí nhớ lệnh. Thang điểm: A 30đ phân loại đúng bốn ca · B 25đ bằng chứng số đo cho từng ca · C 20đ đề xuất thay đổi và dự đoán định lượng · D 15đ giải thích cơ chế phần cứng hoặc hệ điều hành đứng sau · E 10đ sổ tay đủ để người khác lặp lại. Đạt khi ≥ 70/100, phần A ≥ 50% và phần B ≥ 50%. Chẩn đoán đúng mà không có bằng chứng không được tính điểm phần A.",
"120 phút trên bốn máy ảo, mỗi máy một sự cố cài sẵn, không có tài liệu về sự cố. Nộp cho mỗi ca: số đo thu được, kết luận, thay đổi đề xuất, dự đoán định lượng. Sau đó thực hiện thay đổi và đo lại để đối chiếu với dự đoán.",
"Sửa trước khi đo · kết luận từ một chỉ số duy nhất · đề xuất thêm phần cứng mà không dự đoán được nó cải thiện bao nhiêu.",
"Đạt ≥ 70/100, phần A ≥ 50% và phần B ≥ 50%."),
]
