# -*- coding: utf-8 -*-
"""DE M20 — Batch ingestion, accuracy and data quality."""

M20 = ("Batch Ingestion, Accuracy and Data Quality", 203, 218, """| | |
|---|---|
| **Objective cấp module** | Xây một pipeline nạp theo lô chạy lại được ngày bất kỳ cho cùng kết quả, và chứng minh nó phát hiện được dữ liệu sai thay vì chuyển tiếp âm thầm |
| **Tiền đề** | M19 |
| **Exit criterion** | Đạt Cổng 5 ≥ 70/100: xoá, nhân bản và đổi lược đồ 1% dữ liệu, pipeline phải phát hiện, cô lập, sửa và chạy bù được |
| **Kỹ năng SFIA** | `DTAN` mức 4 · `TEST` mức 4 |
| **Chế độ hỏng** | Pipeline chạy xanh mỗi ngày trong khi số liệu sai dần, vì không có phép đối soát nào với nguồn độc lập |""",
"""Module này là chỗ mọi thứ từ chặng 1 tới 3 hợp lại thành một sản phẩm chạy được. Nguyên tắc xuyên suốt: **một pipeline chưa bị phá hoại có chủ đích là một pipeline chưa biết mình hỏng thế nào**, nối lại lesson 60. Sáu bài đầu là cơ chế nạp, bốn bài giữa là chất lượng và độ chính xác, bốn bài sau là hợp đồng và vận hành, hai bài cuối là dự án và Cổng 5.""")

L20 = [
(203,"Source types and what each one makes hard","LT","Module 20: M19",
"Năm loại nguồn và khó khăn đặc trưng của từng loại. Cơ sở dữ liệu giao dịch: dễ đọc nhất nhưng đọc nặng ảnh hưởng hệ sản xuất, nối lại lesson 190, và không có dấu vết xoá nếu ứng dụng xoá cứng. Giao diện lập trình web: phân trang, giới hạn tốc độ và lược đồ đổi không báo, đã giải ở M4 nên bài này chỉ nhắc lại ràng buộc. Tệp trên thư mục hoặc kho đối tượng: đơn giản nhất nhưng hay thiếu tệp, trùng tệp, và tệp ghi dở bị đọc giữa chừng. Dịch vụ bên thứ ba: ít kiểm soát nhất, hạn ngạch và thay đổi không báo trước. Nhật ký ứng dụng: khối lượng lớn, hình dạng không ổn định, và thường không có khoá nghiệp vụ. Ba câu hỏi phải trả lời cho mọi nguồn trước khi viết dòng mã nào: làm sao biết có dữ liệu mới, làm sao biết dữ liệu cũ đã đổi, và làm sao biết dữ liệu đã bị xoá. Câu thứ ba hay không có câu trả lời và đó là thông tin quan trọng.",
"Trả lời ba câu hỏi phát hiện thay đổi cho năm nguồn, và chỉ ra nguồn nào không trả lời được câu hỏi về xoá.",
"Tầng *phân tích*. Objective là khảo sát có cấu trúc trước khi thiết kế. Đạt khi ba câu hỏi được trả lời cho cả năm nguồn bằng bằng chứng từ khảo sát thật, và khi ít nhất một nguồn được kết luận là không phát hiện được xoá kèm phương án bù.",
"Khảo sát năm nguồn dựng sẵn. Với mỗi nguồn, tìm cơ chế phát hiện dữ liệu mới, dữ liệu sửa, và dữ liệu xoá. Ghi lại bằng chứng: cột dấu thời gian nào, nhật ký nào, hay không có gì. Với nguồn không phát hiện được xoá, đề xuất phương án đối chiếu định kỳ.",
"Giả định cột dấu thời gian cập nhật luôn được ứng dụng ghi đúng · bỏ qua câu hỏi về xoá vì nguồn không có cơ chế · đọc trực tiếp bản chính của hệ sản xuất.",
"Ba câu hỏi trả lời cho cả năm nguồn có bằng chứng, và nguồn không phát hiện được xoá có phương án bù."),

(204,"Full load against incremental - choosing a strategy","LT","Lesson 203",
"Nạp toàn bộ đọc lại mọi thứ mỗi lần: đơn giản, tự sửa sai, và bất biến khi chạy lại theo định nghĩa; đổi lại là chi phí tỉ lệ tổng dữ liệu chứ không tỉ lệ dữ liệu mới. Nạp gia tăng chỉ đọc phần thay đổi: rẻ nhưng phải tự bảo đảm mọi tính chất mà nạp toàn bộ có sẵn. Ba chiến lược gia tăng và điều kiện áp dụng: theo con trỏ tăng dần dùng khoá hoặc dấu thời gian, theo ảnh chụp so sánh hai lần chụp, và theo bắt thay đổi từ nhật ký, cái thứ ba ở chặng 6. Quy tắc chọn không theo trực giác: bắt đầu bằng nạp toàn bộ và chỉ chuyển sang gia tăng khi đo được chi phí không chấp nhận được, vì gia tăng đổi chi phí tính toán lấy chi phí độ phức tạp và rủi ro đúng đắn. Ngưỡng chuyển thường ở đâu. Mẫu lai: gia tăng hằng ngày cộng nạp toàn bộ hằng tuần để tự sửa sai tích luỹ, mẫu rẻ và giải quyết phần lớn rủi ro của gia tăng.",
"Chọn chiến lược nạp cho ba bảng có đặc tính khác nhau và biện minh bằng chi phí đo được chứ bằng thói quen.",
"Tầng *đánh giá*. Objective đòi quyết định có đánh đổi giữa chi phí với rủi ro đúng đắn. Đạt khi ba lựa chọn đều có số đo chi phí nạp toàn bộ làm cơ sở so sánh, và khi ít nhất một bảng được kết luận là giữ nạp toàn bộ vì chi phí vẫn chấp nhận được.",
"Ba bảng: 500 nghìn dòng đổi 1% mỗi ngày, 200 triệu dòng đổi 0,1% mỗi ngày, và 5 triệu dòng đổi 60% mỗi ngày. Đo thời gian và chi phí nạp toàn bộ cho từng bảng. Chọn chiến lược. Cài mẫu lai cho bảng thứ hai và đo chi phí tuần.",
"Chuyển sang gia tăng vì thấy chuyên nghiệp hơn · nạp gia tăng mà không có cơ chế tự sửa sai định kỳ · chọn chiến lược trước khi đo chi phí nạp toàn bộ.",
"Ba lựa chọn có số đo chi phí nạp toàn bộ làm cơ sở, và ít nhất một bảng giữ nạp toàn bộ có lý do."),

(205,"Watermarks, cursors and the late-arriving problem","TH","Lesson 204",
"Con trỏ là giá trị đánh dấu đã đọc tới đâu, và lưu nó ở đâu quyết định pipeline chạy lại được hay không: lưu trong bảng trạng thái riêng, không lưu trong bộ nhớ và không suy ra từ dữ liệu đích. Thời điểm cập nhật con trỏ là sau khi ghi dữ liệu thành công, không phải trước, nối lại lesson 35. Dữ liệu tới muộn là bản ghi có dấu thời gian nghiệp vụ cũ nhưng xuất hiện ở nguồn sau khi con trỏ đã vượt qua, nên lần nạp sau bỏ sót nó vĩnh viễn. Ba nguyên nhân: hệ nguồn ghi trễ, múi giờ lệch, và giao dịch dài xác nhận muộn hơn dấu thời gian của nó. Nguyên nhân thứ ba là nguyên nhân tinh vi nhất và nó xảy ra với mọi cơ sở dữ liệu. Cửa sổ nhìn lại: lùi con trỏ một khoảng mỗi lần chạy để bắt lại dữ liệu tới muộn, và điều kiện bắt buộc là phép ghi phải bất biến vì cùng bản ghi sẽ được xử lý nhiều lần, nối lại lesson 106. Chọn độ dài cửa sổ bằng đo phân bố độ trễ thật.",
"Đo phân bố độ trễ tới muộn của một nguồn và chọn độ dài cửa sổ nhìn lại, rồi chứng minh không bỏ sót bản ghi nào.",
"Tầng *áp dụng*. Objective có tiêu chí đối soát tuyệt đối. Đạt khi phân bố độ trễ đo được từ dữ liệu thật, và khi chạy 30 ngày mô phỏng với cửa sổ đã chọn thì tổng bản ghi đích khớp tổng nguồn, không thiếu một dòng.",
"Nguồn có 2% bản ghi tới muộn theo phân bố lệch phải. Đo phân bố độ trễ bằng cách so dấu thời gian nghiệp vụ với thời điểm xuất hiện. Chọn cửa sổ theo phân vị 99. Chạy 30 ngày mô phỏng không cửa sổ rồi có cửa sổ, đối soát cả hai. Đặt cửa sổ trên phép ghi không bất biến và quan sát nhân bản.",
"Cập nhật con trỏ trước khi ghi dữ liệu · chọn cửa sổ nhìn lại bằng cảm tính · dùng cửa sổ nhìn lại với phép ghi không bất biến.",
"Phân bố độ trễ đo từ dữ liệu thật, và chạy 30 ngày với cửa sổ đã chọn cho đối soát khớp tuyệt đối."),

(206,"Immutable landing and why raw is never overwritten","TH","Lesson 205",
"Lớp thô chỉ chèn thêm và không bao giờ sửa, và đây là ràng buộc kiến trúc chứ không phải khuyến nghị. Ba thứ nó cho phép: dựng lại mọi lớp sau từ nó khi logic biến đổi có lỗi, điều tra một số sai bằng cách xem dữ liệu đúng như nguồn gửi, và so sánh hai lần nạp để phát hiện nguồn sửa dữ liệu hồi tố. Cách tổ chức: phân vùng theo thời điểm nạp chứ không theo thời gian nghiệp vụ, vì mục đích là truy vết lần nạp. Đặt tên đối tượng gồm nguồn, thời điểm nạp, và mã lần chạy, để truy được dòng dữ liệu về lần chạy sinh ra nó, nối lại lesson 89. Giữ nguyên định dạng nguồn hay chuyển sang định dạng cột: đánh đổi giữa trung thực với chi phí lưu trữ, và mẫu thường dùng là giữ nguyên bản một thời gian ngắn rồi chuyển. Siêu dữ liệu lần nạp ghi kèm: số bản ghi, tổng kiểm tra, thời điểm bắt đầu và kết thúc. Thời gian lưu giữ lớp thô và chi phí, cùng lý do cắt nó là quyết định phải cân nhắc kỹ.",
"Tổ chức lớp thô sao cho truy được một dòng ở lớp phục vụ về đúng tệp và lần chạy sinh ra nó, và dựng lại được lớp sau từ lớp thô.",
"Tầng *áp dụng*. Objective có hai tiêu chí kiểm bằng thực nghiệm. Đạt khi chọn 10 dòng ngẫu nhiên ở lớp phục vụ và truy được cả 10 về đúng tệp thô và mã lần chạy, và khi xoá sạch lớp sau rồi dựng lại từ lớp thô cho kết quả khớp từng dòng.",
"Dựng lớp thô có quy ước đặt tên và siêu dữ liệu lần nạp. Chạy 10 lần nạp. Chọn 10 dòng ngẫu nhiên ở lớp phục vụ và truy ngược. Xoá lớp sạch và lớp phục vụ, dựng lại hoàn toàn từ lớp thô, đối chiếu. So hai lần nạp của cùng một ngày để phát hiện nguồn sửa hồi tố.",
"Ghi đè tệp thô khi nạp lại cùng ngày · phân vùng lớp thô theo thời gian nghiệp vụ · bỏ siêu dữ liệu lần nạp vì thấy thừa.",
"Truy được cả 10 dòng về đúng tệp và lần chạy, và dựng lại lớp sau từ lớp thô khớp từng dòng."),

(207,"Atomic publish and the partially-written table","TH","Lesson 206",
"Người đọc không bao giờ được thấy trạng thái nửa chừng, và ba mẫu đạt được điều đó. Ghi ra vị trí tạm rồi đổi tên hoặc hoán đổi, cùng ý tưởng với lesson 16 nhưng ở mức bảng. Ghi vào bảng bóng rồi hoán đổi bí danh, mẫu dùng ở lesson 181. Ghi trong một giao dịch khi hệ đích hỗ trợ, đơn giản nhất nhưng giới hạn bởi kích thước giao dịch. Với bảng phân vùng, hoán đổi ở mức phân vùng thay vì cả bảng, rẻ hơn nhiều bậc và là mẫu mặc định cho nạp hằng ngày, nối lại lesson 130. Cửa sổ không nguyên tử còn lại trong từng mẫu và cách đo nó. Người đọc đang chạy lúc hoán đổi: một số hệ cho truy vấn đang chạy đọc tiếp bản cũ, một số huỷ nó, và phải kiểm chứ không giả định. Thứ tự khi ghi nhiều bảng phụ thuộc nhau: công bố bảng chiều trước bảng sự kiện, nếu không thì có khoảng thời gian bảng sự kiện tham chiếu chiều chưa tồn tại.",
"Cài công bố nguyên tử cho một bảng phân vùng, và chứng minh người đọc không bao giờ thấy trạng thái nửa chừng dưới tải đọc liên tục.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm lặp lại. Đạt khi chạy 50 lần công bố trong lúc có tải đọc liên tục mà không lần nào người đọc thấy số dòng bất thường, và khi thứ tự công bố bảng chiều trước bảng sự kiện được chứng minh cần thiết bằng một ca làm ngược.",
"Bảng phân vùng có tải đọc đếm số dòng mỗi 100 mili giây. Công bố một phân vùng 50 lần bằng ba mẫu khác nhau, ghi lại mọi số dòng bất thường người đọc thấy. Công bố bảng sự kiện trước bảng chiều một lần và ghi lại lỗi khoá ngoại hoặc dòng mồ côi.",
"Xoá rồi chèn ngoài giao dịch · hoán đổi cả bảng khi chỉ đổi một phân vùng · công bố bảng sự kiện trước bảng chiều.",
"50 lần công bố không lần nào người đọc thấy số dòng bất thường, và ca công bố sai thứ tự được chứng minh gây lỗi."),

(208,"Deduplication and the business key","TH","Lesson 207",
"Trùng lặp đến từ bốn nguồn khác nhau và mỗi nguồn cần cách xử lý khác: nguồn gửi lại do thử lại, pipeline chạy lại do lỗi, cửa sổ nhìn lại ở lesson 205, và nguồn thật sự có bản ghi trùng. Ba loại trùng theo mức độ giống nhau: trùng toàn bộ cột, trùng khoá nghiệp vụ nhưng khác nội dung, và trùng mờ do khác biểu diễn chuỗi, nối lại lesson 8. Khoá nghiệp vụ là khoá định danh thực thể theo nghĩa nghiệp vụ, khác khoá kỹ thuật của hệ nguồn; xác định nó đúng là điều kiện để khử trùng đúng, và nó phải hỏi người hiểu nghiệp vụ chứ không suy từ dữ liệu. Quy tắc giữ dòng nào khi trùng khoá nhưng khác nội dung phải khai báo rõ: giữ bản mới nhất theo cột nào, và cột đó có đáng tin không. Khử trùng ở đâu trong đường ống: ở lớp sạch chứ không ở lớp thô, vì lớp thô phải giữ nguyên như nguồn. Đếm và ghi nhật ký số bản ghi bị loại.",
"Khử trùng một tập có đủ bốn nguồn trùng lặp, khai báo rõ khoá nghiệp vụ và quy tắc giữ dòng, và đếm được số bản ghi bị loại theo từng loại.",
"Tầng *áp dụng*. Objective có tiêu chí đối soát và một yêu cầu khai báo. Đạt khi tổng bản ghi vào bằng bản ghi ra cộng bản ghi bị loại theo từng loại, và khi quy tắc giữ dòng được khai báo bằng văn bản và cho kết quả khớp bản đối chứng.",
"Tập 5 triệu bản ghi có đủ bốn nguồn trùng. Xác định khoá nghiệp vụ bằng khảo sát và hỏi mô tả nghiệp vụ. Khử trùng theo ba loại, đếm riêng từng loại. Đối soát phép cộng. So kết quả với bản đối chứng. Thử khử trùng ở lớp thô và chỉ ra nó phá vỡ tính tái tạo.",
"Suy khoá nghiệp vụ từ dữ liệu mà không hỏi · khử trùng ở lớp thô · giữ bản mới nhất theo cột dấu thời gian mà chưa kiểm cột đó có đáng tin không.",
"Phép cộng đối soát khớp theo từng loại trùng, và quy tắc giữ dòng khai báo bằng văn bản cho kết quả khớp đối chứng."),

(209,"Schema evolution at the ingestion boundary","TH","Lesson 208",
"Lược đồ nguồn đổi là chuyện chắc chắn xảy ra, nên pipeline phải có hành vi khai báo trước cho từng loại thay đổi thay vì vỡ theo cách ngẫu nhiên. Sáu loại thay đổi và mức nghiêm trọng: thêm cột tuỳ chọn tương thích ngược, thêm cột bắt buộc phá vỡ, xoá cột phá vỡ, đổi kiểu phá vỡ, đổi tên là xoá cộng thêm nên phá vỡ, và đổi ngữ nghĩa mà không đổi cấu trúc là loại nguy hiểm nhất vì không có tín hiệu kỹ thuật nào. Ba chiến lược khi nguồn thêm cột và tiêu chí chọn: bỏ qua cột mới giữ pipeline ổn định nhưng mất dữ liệu, tự thêm vào đích giữ được dữ liệu nhưng lược đồ đích trôi dần, và dừng và báo an toàn nhất nhưng gây gián đoạn. Lựa chọn phụ thuộc lớp: lớp thô nên nhận tất cả, lớp sạch nên dừng và báo. Kiểm lược đồ ở biên nhận, nối lại lesson 87. Đối chiếu lược đồ nguồn theo lịch để phát hiện thay đổi trước khi nó gây lỗi.",
"Khai báo hành vi cho sáu loại thay đổi lược đồ và chứng minh pipeline phản ứng đúng như khai báo cho cả sáu.",
"Tầng *áp dụng*. Objective có tiêu chí kiểm bằng thực nghiệm đầy đủ. Đạt khi sáu loại thay đổi đều cho hành vi đúng như bảng khai báo, và khi loại đổi ngữ nghĩa được phát hiện bằng một phép kiểm phân bố chứ không bằng kiểm lược đồ.",
"Lập bảng khai báo hành vi cho sáu loại thay đổi ở hai lớp. Cài kiểm lược đồ ở biên. Bơm sáu thay đổi vào nguồn, ghi lại hành vi thật của pipeline. Với loại đổi ngữ nghĩa, thêm phép kiểm phân bố giá trị và xác nhận nó bắt được.",
"Tự thêm cột mới vào lớp sạch · coi đổi tên cột là thay đổi nhỏ · không có phép kiểm nào cho loại đổi ngữ nghĩa.",
"Sáu loại thay đổi cho hành vi đúng như bảng khai báo, và loại đổi ngữ nghĩa bắt được bằng kiểm phân bố."),

(210,"Backfill and replay without double counting","TH","Lesson 209",
"Chạy bù là chạy lại một dải thời gian trong quá khứ, và nó chỉ an toàn khi phép ghi bất biến, nối lại lesson 106 và 205. Ba câu hỏi trước mỗi lần chạy bù: các ngày độc lập hay phụ thuộc thứ tự, chạy được mấy ngày cùng lúc mà hệ đích chịu được, và logic mới có tương thích dữ liệu cũ không. Câu thứ ba hay bị bỏ: chạy bù bằng mã hiện tại lên dữ liệu ba tháng trước có thể cho kết quả khác với lúc đó nếu logic đã đổi, và đó có thể đúng ý hoặc không, nên phải quyết định rõ. Phát lại là chạy lại từ lớp thô khi phát hiện lỗi logic biến đổi, khác chạy bù ở chỗ nguồn là lớp thô chứ không phải hệ nguồn. Đây là lý do lớp thô ở lesson 206 tồn tại. Đánh dấu dữ liệu đã chạy bù để người dùng biết số lịch sử vừa đổi, và thông báo cho người đã dùng số cũ. Chạy bù một phần đồ thị phụ thuộc thay vì toàn bộ.",
"Chạy bù 90 ngày cho một bảng có mô hình chiều thay đổi chậm, và chứng minh kết quả khớp bản chạy tuần tự từng ngày.",
"Tầng *áp dụng*. Objective có tiêu chí đối chứng tuyệt đối trên một ca khó, vì chiều thay đổi chậm làm chạy bù phụ thuộc thứ tự. Đạt khi bảng sau chạy bù khớp từng dòng với bản đối chứng, và khi người học chỉ ra được vì sao ngày không độc lập trong ca này.",
"Sinh bản đối chứng bằng cách chạy tuần tự 90 ngày. Xoá bảng đích. Chạy bù 90 ngày. Đối chiếu từng dòng. Thử chạy bù song song và ghi lại sai lệch do chiều thay đổi chậm. Chạy phát lại từ lớp thô sau khi sửa một lỗi logic, so với chạy bù từ nguồn.",
"Chạy bù song song các ngày cho bảng có chiều thay đổi chậm · chạy bù bằng logic mới mà không quyết định rõ có muốn thế không · quên thông báo cho người đã dùng số cũ.",
"Bảng sau chạy bù khớp từng dòng với bản đối chứng, và lý do ngày không độc lập được chỉ ra."),

(211,"Six dimensions of data quality and one that needs an oracle","LT","Lesson 210",
"Sáu chiều và một truy vấn đo cho từng chiều: đầy đủ đo tỉ lệ giá trị có mặt và tỉ lệ bản ghi nhận được so với kỳ vọng, duy nhất đo trùng lặp theo khoá nghiệp vụ, hợp lệ đo tuân thủ định dạng và dải giá trị, nhất quán đo mâu thuẫn giữa các cột và giữa các bảng, kịp thời đo độ trễ so với cam kết, và chính xác đo khớp với thực tế. Chiều chính xác khác năm chiều còn lại về bản chất: năm chiều đầu đo được bằng quy tắc nội bộ, còn chính xác cần một nguồn đối chứng bên ngoài. Hệ quả: một bảng có thể đạt năm chiều mà vẫn sai hoàn toàn, và đây là chỗ nhiều hệ thống chất lượng dữ liệu dừng lại rồi tạo cảm giác an toàn giả. Ba loại nguồn đối chứng khả dụng: hệ thống độc lập đo cùng đại lượng, báo cáo do người khác lập, và xác nhận thủ công trên mẫu. Nói rõ chiều nào đang đo được và chiều nào chưa là yêu cầu của module.",
"Đo sáu chiều cho một bảng và phát biểu rõ chiều chính xác đang được đo bằng nguồn nào hoặc chưa đo được.",
"Tầng *hiểu*. Objective gồm đo và một phán đoán về giới hạn phép đo. Đạt khi sáu chiều đều có số, và khi phần về chiều chính xác nêu rõ nguồn đối chứng cụ thể hoặc tuyên bố chưa đo được kèm lý do. Báo cáo đủ sáu số mà nói chính xác đạt nhờ quy tắc nội bộ là không đạt.",
"Bảng 10 triệu dòng. Viết truy vấn đo cho từng chiều trong sáu chiều. Chạy và lập báo cáo có số. Tìm một nguồn đối chứng độc lập cho một đại lượng và đo chiều chính xác. Với hai đại lượng không có nguồn đối chứng, viết rõ là chưa đo được.",
"Đo chiều chính xác bằng quy tắc nội bộ · gộp chiều hợp lệ với chiều chính xác · báo cáo chất lượng đạt khi năm chiều xanh mà chưa đối soát.",
"Sáu chiều đều có số, và phần chiều chính xác nêu rõ nguồn đối chứng hoặc tuyên bố chưa đo được kèm lý do."),

(212,"Accuracy - reconciliation against an independent source","TH","Lesson 211",
"Đối soát là phép so một đại lượng tính bằng hai đường độc lập, và nó là cách duy nhất đo được chiều chính xác ở lesson 211. Bốn kỹ thuật và cái mỗi cái bắt: tổng kiểm tra số bản ghi bắt mất và thừa dòng, tổng theo khoá nghiệp vụ bắt sai giá trị, kiểm tra biên bắt giá trị ngoài dải, và kiểm tra thứ nguyên bắt sai đơn vị. Đối soát nguồn tới đích theo từng chặng thay vì chỉ ở cuối, để định vị được chặng nào làm sai. Ngưỡng chấp nhận và vì sao ngưỡng bằng không thường không thực tế cho dữ liệu có tới muộn, nối lại lesson 205; cách đặt ngưỡng theo phân bố chênh lệch lịch sử. Chênh lệch nhỏ tích luỹ theo thời gian và cách phát hiện bằng theo dõi xu hướng thay vì theo dõi giá trị tuyệt đối. Ba nguyên nhân chênh lệch thường gặp: khác định nghĩa giữa hai hệ, khác thời điểm chốt, và thật sự mất dữ liệu; phân biệt ba cái này trước khi kết luận.",
"Đối soát một đại lượng qua ba chặng của pipeline, và truy một chênh lệch về đúng một trong ba nguyên nhân.",
"Tầng *phân tích*. Objective là chẩn đoán phân biệt ba nguyên nhân có cùng triệu chứng. Kiểm bằng ba ca chênh lệch dựng sẵn; đạt khi truy đúng cả ba và mỗi lần dẫn được bằng chứng định lượng, không chấp nhận kết luận mất dữ liệu khi chưa loại trừ hai nguyên nhân kia.",
"Cài đối soát bốn kỹ thuật ở ba chặng của pipeline. Bơm ba chênh lệch: một do định nghĩa khác giữa hai hệ, một do thời điểm chốt lệch, và một do mất dữ liệu thật. Với mỗi ca, truy nguyên nhân và dẫn bằng chứng. Đặt ngưỡng chấp nhận từ phân bố chênh lệch 30 ngày lịch sử.",
"Kết luận mất dữ liệu ngay khi thấy chênh lệch · đối soát chỉ ở cuối pipeline · đặt ngưỡng bằng không cho nguồn có dữ liệu tới muộn.",
"Truy đúng cả ba nguyên nhân có bằng chứng định lượng, và ngưỡng đặt từ phân bố lịch sử."),

(213,"Quality rules, thresholds and where to put them","TH","Lesson 212",
"Ba vị trí đặt phép kiểm và cái mỗi vị trí bắt: ở biên nhận bắt dữ liệu nguồn sai trước khi nó vào hệ, giữa các lớp bắt lỗi logic biến đổi, và ở đầu ra bắt lỗi tổng hợp trước khi tới người dùng. Đặt cả ba là lý tưởng nhưng tốn, nên phải chọn theo rủi ro. Phép kiểm chặn so với phép kiểm cảnh báo: cái đầu dừng pipeline, cái sau ghi nhận và chạy tiếp; chọn sai theo hướng nào cũng có hại. Đặt mọi phép kiểm là chặn làm pipeline dừng vì một cảnh báo nhỏ, đặt mọi phép kiểm là cảnh báo làm chúng bị bỏ qua sau hai tuần, nối lại lesson 80. Tiêu chí phân loại: dừng khi dữ liệu sai gây hại nhiều hơn dữ liệu trễ. Ngưỡng cố định so với ngưỡng động theo lịch sử, và vì sao ngưỡng cố định luôn hoặc quá nhạy hoặc quá điếc. Phép kiểm cũng cần được kiểm: một phép kiểm chưa bao giờ đỏ có thể là phép kiểm sai chứ không phải dữ liệu hoàn hảo.",
"Phân loại 15 phép kiểm thành chặn hay cảnh báo và đặt vào đúng vị trí, rồi chứng minh mỗi phép kiểm bắt được lỗi nó nhắm tới.",
"Tầng *đánh giá*. Objective đòi hai quyết định có đánh đổi, cộng một yêu cầu chứng minh. Đạt khi 15 phép kiểm đều có vị trí và mức nghiêm trọng kèm lý do, và khi bơm lỗi tương ứng làm ít nhất 13 phép kiểm đỏ đúng như thiết kế.",
"Nhận 15 phép kiểm. Phân loại và đặt vị trí cho từng cái. Với mỗi phép kiểm, bơm đúng loại lỗi nó nhắm tới và xác nhận nó đỏ. Đặt ngưỡng động từ 30 ngày lịch sử cho ba phép kiểm và so tỉ lệ báo động giả với ngưỡng cố định.",
"Đặt mọi phép kiểm là chặn · dùng ngưỡng cố định cho chỉ số có mùa vụ · tin một phép kiểm chưa bao giờ đỏ là dấu hiệu tốt.",
"15 phép kiểm có vị trí và mức nghiêm trọng kèm lý do, và ít nhất 13 phép kiểm đỏ đúng khi bơm lỗi tương ứng."),

(214,"Quarantine, alerting and the silent-drop ban","TH","Lesson 213",
"Nguyên tắc cứng của module: không bản ghi nào bị loại trong im lặng. Mọi bản ghi không qua được phép kiểm phải đi vào bảng cách ly kèm lý do, mã lần chạy, và bản ghi gốc nguyên vẹn, để sau đó sửa và nạp lại được. Phép cộng bắt buộc: tổng bản ghi vào bằng bản ghi sạch cộng bản ghi cách ly, không sai một dòng, nối lại lesson 65. Quy trình xử lý bảng cách ly: ai xem, bao lâu một lần, và cách nạp lại sau khi sửa; bảng cách ly không có người xem là bảng cách ly vô dụng. Cảnh báo phải nói được ba thứ: cái gì hỏng, ảnh hưởng tới ai, và bước đầu tiên nên làm, nối lại lesson 80. Gom cảnh báo cùng nguyên nhân thay vì gửi một cảnh báo cho mỗi bản ghi. Chỉ cảnh báo thứ người trực làm được gì đó; phần còn lại ghi vào báo cáo. Đo tỉ lệ cách ly theo thời gian như một chỉ số sức khoẻ nguồn.",
"Cài cơ chế cách ly và chứng minh phép cộng khớp tuyệt đối, cùng một quy trình xử lý bảng cách ly có người thực hiện được.",
"Tầng *áp dụng*. Objective có tiêu chí đối soát tuyệt đối cộng một tiêu chí về quy trình. Đạt khi phép cộng khớp trên tập có 8% bản ghi hỏng theo sáu kiểu, và khi một học viên khác theo quy trình sửa và nạp lại được ít nhất 90% bản ghi cách ly.",
"Tập 3 triệu bản ghi có 8% hỏng theo sáu kiểu. Cài cách ly kèm lý do và bản ghi gốc. Đối soát phép cộng. Viết quy trình xử lý. Đưa bảng cách ly và quy trình cho học viên khác, đo tỉ lệ họ sửa và nạp lại được. Viết ba cảnh báo mẫu đủ ba thứ.",
"Loại bản ghi hỏng mà chỉ ghi số lượng · cách ly mà không giữ bản ghi gốc nên không sửa lại được · gửi một cảnh báo cho mỗi bản ghi hỏng.",
"Phép cộng khớp tuyệt đối, và học viên khác sửa cùng nạp lại được ít nhất 90% bản ghi cách ly theo quy trình."),

(215,"Distribution drift and detecting change that breaks nothing","TH","Lesson 214",
"Loại lỗi nguy hiểm nhất là loại không làm gì hỏng: lược đồ đúng, ràng buộc đạt, phép kiểm xanh, nhưng phân bố dữ liệu đã đổi và số liệu không còn nghĩa như trước. Bốn ví dụ: một kênh bán hàng ngừng gửi dữ liệu nên tổng giảm mà không ai báo, mã trạng thái mới xuất hiện và rơi vào nhánh mặc định, đơn vị tiền tệ đổi mà cột không đổi, và tỉ lệ giá trị rỗng của một cột tăng từ 1% lên 40%. Bốn phép đo phát hiện trôi: phân bố tần suất của cột phân loại, phân vị của cột số, tỉ lệ giá trị rỗng, và số bản ghi theo nhóm nguồn. So với cửa sổ lịch sử thay vì với ngưỡng cố định. Phân biệt trôi thật với biến động mùa vụ, và đây là chỗ cần dữ liệu lịch sử đủ dài. Cảnh báo trôi nên là cảnh báo chứ không phải chặn, vì trôi có thể là thay đổi nghiệp vụ hợp lệ, và người phán đoán là người hiểu nghiệp vụ.",
"Cài bốn phép đo trôi và phát hiện được bốn loại thay đổi âm thầm, phân biệt được với biến động mùa vụ.",
"Tầng *phân tích*. Objective đòi phân biệt tín hiệu thật với nhiễu mùa vụ, việc khó hơn đặt ngưỡng. Đạt khi phát hiện được cả bốn loại thay đổi bơm vào, và khi ba biến động mùa vụ cố ý không gây cảnh báo giả.",
"Dữ liệu 18 tháng có mùa vụ theo tuần và theo Tết. Cài bốn phép đo trôi so với cửa sổ lịch sử. Bơm bốn loại thay đổi âm thầm vào các thời điểm khác nhau. Đếm số phát hiện đúng và số báo động giả trong ba kỳ mùa vụ cao điểm.",
"Dùng ngưỡng cố định cho chỉ số có mùa vụ · đặt cảnh báo trôi là chặn · so với tuần trước thay vì với cùng kỳ năm trước cho dữ liệu có mùa vụ.",
"Phát hiện cả bốn loại thay đổi bơm vào, và ba kỳ mùa vụ không sinh báo động giả."),

(216,"The pipeline contract - eleven declarations","TH","Lesson 215",
"Hợp đồng của một pipeline là tài liệu người tiêu thụ dựa vào để dùng dữ liệu đúng, và mười một khai báo ở lesson 200 giờ được hoàn thiện bằng số đo từ chín bài vừa qua. Hạt và khoá nghiệp vụ từ lesson 192 và 208. Lược đồ và hành vi khi nó đổi từ lesson 209. Múi giờ từ lesson 9. Ngữ nghĩa cập nhật và xoá từ lesson 203. Độ tươi phát biểu bằng cam kết cụ thể có giờ chứ không bằng tính từ. Mức đầy đủ và mức chính xác bằng số đo từ lesson 211 và 212, kèm nguồn đối chứng. Lineage từ lesson 206. Chủ sở hữu là một người có tên chứ không phải một nhóm. Thời gian lưu giữ. Quy trình thông báo khi hợp đồng đổi và thời gian chuyển tiếp. Hợp đồng đặt cạnh mã và kiểm trong tích hợp liên tục, nối lại lesson 87 và 90. Vì sao hợp đồng viết xong rồi để đó thì vô dụng: nó phải có phép kiểm tự động, nếu không nó chỉ là lời hứa.",
"Viết hợp đồng đủ mười một khai báo cho một pipeline, và gắn phép kiểm tự động cho ít nhất tám khai báo.",
"Tầng *áp dụng*. Objective có tiêu chí đếm được và một yêu cầu về tính thực thi. Đạt khi mười một khai báo đều có nội dung cụ thể có số, và khi ít nhất tám khai báo có phép kiểm chạy trong tích hợp liên tục và đỏ đúng khi vi phạm.",
"Viết hợp đồng cho pipeline đơn hàng. Với mỗi khai báo, gắn một phép kiểm tự động nếu làm được, hoặc ghi rõ vì sao không. Vi phạm tám khai báo có phép kiểm và xác nhận từng cái đỏ. Đưa hợp đồng cho một học viên khác đóng vai người tiêu thụ và ghi lại câu hỏi phát sinh.",
"Phát biểu độ tươi bằng tính từ · ghi chủ sở hữu là tên nhóm · viết hợp đồng mà không có phép kiểm tự động nào.",
"Mười một khai báo đều có nội dung cụ thể có số, và ít nhất tám khai báo có phép kiểm đỏ đúng khi vi phạm."),

(217,"Batch platform v1 - end to end","DA","Lesson 216",
"Không có cơ chế mới. Dự án gộp M20 và nó là sản phẩm đầu tiên của chương trình có đủ hình dạng một hệ thống thật. Yêu cầu: nạp từ PostgreSQL và một giao diện lập trình web vào lớp thô bất biến, qua lớp sạch có khử trùng và phép kiểm, tới lớp phục vụ theo mô hình chiều ở M19. Kèm theo: bản kê từng lô có số bản ghi và tổng kiểm tra, bộ phép kiểm ba vị trí ở lesson 213, bảng cách ly ở lesson 214, đối soát ba chặng ở lesson 212, hợp đồng mười một khai báo ở lesson 216, và sổ tay xử lý theo khuôn lesson 90. Tiêu chí bắt buộc: chạy lại ngày bất kỳ cho cùng kết quả, và phép cộng vào bằng sạch cộng cách ly khớp tuyệt đối ở mọi lô.",
"Xây một nền tảng nạp theo lô đầu cuối, và chứng minh chạy lại ngày bất kỳ cho cùng kết quả cùng phép cộng đối soát khớp ở mọi lô.",
"Tầng *sáng tạo*. Objective là dựng một hệ thống dưới nhiều ràng buộc đồng thời. Chấm theo sáu mục: tính bất biến khi chạy lại 25đ, đối soát ba chặng 20đ, cách ly và phép cộng 20đ, hợp đồng và phép kiểm 15đ, mô hình chiều 10đ, sổ tay 10đ. Đạt khi ≥ 70/100 và hai mục đầu đều ≥ 70% của chúng.",
"Nguồn 20 triệu dòng có 5% bản ghi hỏng và 2% tới muộn. Xây đủ ba lớp. Chạy 30 ngày mô phỏng. Chọn ngẫu nhiên 5 ngày và chạy lại, đối chiếu từng dòng. Kiểm phép cộng ở cả 30 lô. Nộp hợp đồng, sổ tay và báo cáo đối soát.",
"Bỏ lớp thô để pipeline gọn hơn · đối soát một lần ở cuối · chạy lại một ngày rồi kết luận bất biến.",
"Đạt ≥ 70/100, hai mục đầu ≥ 70%, và 5 ngày chạy lại ngẫu nhiên đều khớp từng dòng."),

(218,"Gate 5 - break the data, prove you catch it","KT","Lesson 217",
"Không có nội dung mới. Cổng 5 đóng chặng 4, và nó đo đúng một thứ: pipeline có phát hiện được khi dữ liệu sai hay không.",
"Nhận một pipeline bị phá hoại theo ba cách trên 1% dữ liệu, phát hiện cả ba, cô lập phạm vi ảnh hưởng, sửa, và chạy bù, rồi chứng minh kết quả cuối khớp bản đối chứng.",
"Tầng *đánh giá*. Cổng đo năng lực phát hiện và phục hồi, không đo năng lực xây. Thang điểm: A 30đ phát hiện cả ba loại phá hoại · B 20đ định vị phạm vi ảnh hưởng bằng lineage · C 20đ chạy bù cho kết quả khớp đối chứng · D 15đ thông báo cho người đã dùng số sai · E 15đ phép kiểm bổ sung để lần sau bắt sớm hơn. Đạt khi ≥ 70/100 và phần A ≥ 60%. Phần D nặng hơn vẻ ngoài vì nó là phần hay bị bỏ nhất.",
"180 phút. Giám khảo xoá 1% bản ghi, nhân bản 1% bản ghi, và đổi lược đồ một cột ở nguồn, không báo trước làm gì và làm lúc nào. Nộp: thời điểm phát hiện từng loại, phạm vi ảnh hưởng, kết quả sau chạy bù đối chiếu bản đối chứng, thông báo gửi người dùng, và phép kiểm bổ sung.",
"Phát hiện được mà không định vị được phạm vi · chạy bù xong không đối chiếu · bỏ phần thông báo vì đã sửa xong.",
"Đạt ≥ 70/100 và phần A ≥ 60%."),
]
