# -*- coding: utf-8 -*-
"""DE M37 Cloud and infrastructure as code + M38 Operations."""

M37 = ("Cloud and Infrastructure as Code", 375, 386, """| | |
|---|---|
| **Objective cấp module** | Dựng hạ tầng cho pipeline tham chiếu bằng mã khai báo, huỷ và dựng lại được, và giải thích mọi quyền đã cấp bằng nguyên tắc đặc quyền tối thiểu |
| **Tiền đề** | M36 |
| **Exit criterion** | Huỷ sạch rồi dựng lại toàn bộ hạ tầng bằng một lệnh, pipeline chạy lại được, và không tài khoản nào có quyền rộng hơn việc nó phải làm |
| **Kỹ năng SFIA** | `ARCH` mức 3 · `SYSP` mức 4 · `CFMG` mức 4 |
| **Chế độ hỏng** | Bấm tay trên giao diện để dựng, không ai biết môi trường gồm những gì, rồi không dựng lại được và không biết đang trả tiền cho cái gì |""",
"""Mức `A` cho một nhà cung cấp, mức `B` cho hai nhà còn lại theo quy ước ở mục 2: học ánh xạ dịch vụ theo chức năng chứ học thuộc tên.

Module này là chỗ mọi thứ đã dựng cục bộ từ M20 tới M36 được đưa lên hạ tầng thật, nên nó cũng là chỗ đầu tiên chi phí trở thành một ràng buộc đo được chứ một lời nhắc.""")

L37 = [
(375,"The shared responsibility model and the four service groups","LT","Module 37: M36",
"Dùng đám mây không bỏ được trách nhiệm vận hành mà chỉ dời ranh giới, và biết ranh giới nằm ở đâu quyết định đội phải làm gì. Với máy ảo, nhà cung cấp lo phần cứng và ảo hoá, đội lo hệ điều hành trở lên. Với cơ sở dữ liệu quản lý, nhà cung cấp lo thêm bản vá và sao lưu, đội vẫn lo lược đồ, chỉ mục, truy vấn và chi phí. Với dịch vụ không máy chủ, nhà cung cấp lo gần hết phần chạy, đội lo mã và cấu hình. Phần **không bao giờ dời đi được**: dữ liệu của ai người đó chịu trách nhiệm, gồm phân loại, quyền truy cập, mã hoá và tuân thủ. Bốn nhóm dịch vụ một đội dữ liệu dùng thường xuyên: tính toán, lưu trữ đối tượng, cơ sở dữ liệu quản lý, và mạng. Học theo chức năng thay vì theo tên riêng, vì tên đổi theo nhà cung cấp còn chức năng thì không, và đây là lý do lesson 385 lập bảng ánh xạ.",
"Với một kiến trúc cho trước, chỉ ra phần nào thuộc trách nhiệm nhà cung cấp và phần nào thuộc đội, ở cả ba mức dịch vụ.",
"Tầng *hiểu*. Bài mở module, đặt đúng kỳ vọng trước khi dựng. Kiểm bằng ba kiến trúc ở ba mức; đạt khi phân định đúng ở cả ba và nêu đúng phần không dời đi được.",
"Cho ba kiến trúc dùng máy ảo, cơ sở dữ liệu quản lý và dịch vụ không máy chủ. Với mỗi kiến trúc, lập bảng hai cột về trách nhiệm. Đọc thoả thuận mức dịch vụ của một dịch vụ lưu trữ thật và ghi lại nhà cung cấp cam kết gì và không cam kết gì.",
"Nghĩ dùng dịch vụ quản lý là hết việc vận hành · cho rằng nhà cung cấp chịu trách nhiệm về dữ liệu · học thuộc tên dịch vụ thay vì chức năng.",
"Ba bảng trách nhiệm phân định đúng, và trích được từ thoả thuận mức dịch vụ thật hai điều nhà cung cấp không cam kết."),

(376,"Identity and access - least privilege in practice","TH","Lesson 375",
"Quyền là chỗ sai nguy hiểm nhất trên đám mây vì sai thì hoặc lộ dữ liệu hoặc xoá được thứ không nên xoá. Bốn khái niệm: danh tính là người hoặc khối lượng công việc, chính sách là tập quyền, vai là danh tính tạm mà một danh tính khác có thể nhận, và tài nguyên là thứ được bảo vệ. Nguyên tắc đặc quyền tối thiểu phát biểu cụ thể: mỗi danh tính chỉ được đúng những hành động nó thật sự gọi, trên đúng những tài nguyên nó thật sự chạm. Ba cách làm sai phổ biến: cấp quyền quản trị cho tiện, dùng khoá dài hạn thay vì vai tạm, và chia sẻ một danh tính cho nhiều dịch vụ nên không truy được ai làm gì. Danh tính cho khối lượng công việc là cách đúng để một tác vụ ở M36 gọi dịch vụ đám mây mà không cần khoá tĩnh. Cách thu hẹp quyền có phương pháp: bắt đầu từ quyền rộng trong môi trường thử, đọc nhật ký gọi thật, rồi viết chính sách đúng những hành động đã dùng.",
"Viết chính sách đặc quyền tối thiểu cho một thành phần từ nhật ký gọi thật, và chứng minh nó đủ chạy nhưng không rộng hơn.",
"Tầng *áp dụng*. Objective là một quy trình thu hẹp quyền có bằng chứng, kiểm được bằng thử cả chiều đủ lẫn chiều thừa. Kiểm bằng hai phép thử; đạt khi pipeline chạy xong và mọi hành động ngoài danh sách đều bị từ chối.",
"Chạy pipeline với quyền rộng trong môi trường thử, thu nhật ký gọi và rút danh sách hành động thật. Viết chính sách chỉ gồm các hành động đó trên đúng tài nguyên. Áp dụng và chạy lại. Thử ba hành động ngoài danh sách và xác nhận bị từ chối. Chuyển từ khoá tĩnh sang danh tính khối lượng công việc.",
"Cấp quyền quản trị cho tiện rồi hẹn sẽ sửa sau · dùng ký tự đại diện cho tài nguyên · để khoá tĩnh trong biến môi trường · chia sẻ một danh tính cho nhiều dịch vụ.",
"Pipeline chạy xong với chính sách hẹp, ba hành động ngoài danh sách đều bị từ chối, và không còn khoá tĩnh nào trong cấu hình."),

(377,"Cloud networking and the private path to data","TH","Lesson 376",
"Mặc định của nhiều hướng dẫn là để dịch vụ dữ liệu có địa chỉ công khai, và đó là cách phổ biến nhất khiến cơ sở dữ liệu bị quét thấy rồi bị tấn công. Bốn khái niệm đủ dùng: mạng riêng ảo là không gian địa chỉ riêng; mạng con chia theo vùng sẵn sàng và theo mức công khai; bảng định tuyến quyết định đường ra; nhóm bảo mật là tường lửa ở mức tài nguyên. Bố trí chuẩn cho hệ dữ liệu: thành phần cần người ngoài gọi vào đặt ở mạng con công khai, cơ sở dữ liệu và kho nội bộ đặt ở mạng con riêng không có đường ra trực tiếp. Cách cho tài nguyên trong mạng riêng gọi ra ngoài mà không phơi mặt ra ngoài. Điểm cuối riêng cho dịch vụ của nhà cung cấp: cho phép gọi kho đối tượng mà lưu lượng không đi qua mạng công cộng, đồng thời giảm chi phí truyền dữ liệu. Ba câu hỏi kiểm tra trước khi mở bất kỳ cổng nào ra ngoài.",
"Bố trí một hệ dữ liệu sao cho cơ sở dữ liệu không có đường vào từ mạng công cộng, và chứng minh bằng quét cổng từ bên ngoài.",
"Tầng *áp dụng*. Objective là một cấu hình bảo mật kiểm được khách quan bằng quét. Kiểm bằng quét từ ngoài cộng phép thử kết nối từ trong; đạt khi ngoài không thấy cổng nào của cơ sở dữ liệu và trong vẫn kết nối được.",
"Dựng mạng riêng ảo có mạng con công khai và riêng. Đặt cơ sở dữ liệu ở mạng con riêng và ứng dụng ở mạng con công khai. Quét cổng từ một máy ngoài và ghi kết quả. Tạo điểm cuối riêng cho kho đối tượng và so chi phí truyền dữ liệu trước sau.",
"Để cơ sở dữ liệu có địa chỉ công khai cho tiện kết nối · mở nhóm bảo mật cho mọi địa chỉ · quên điểm cuối riêng rồi trả phí truyền dữ liệu qua mạng công cộng.",
"Quét từ ngoài không thấy cổng cơ sở dữ liệu, ứng dụng trong mạng vẫn kết nối được, và có số chênh chi phí truyền dữ liệu."),

(378,"Cloud object storage - classes, lifecycle and cost","TH","Lesson 377",
"Kho đối tượng trên đám mây là bản thương mại của thứ đã học ở lesson 329, và ba yếu tố quyết định hoá đơn chứ chỉ dung lượng: dung lượng lưu, số yêu cầu, và lưu lượng ra khỏi vùng. Yếu tố thứ ba là chỗ đội hay bị bất ngờ, vì đọc dữ liệu về máy ngoài vùng tốn tiền nhiều hơn lưu trữ. Các lớp lưu trữ đổi giá lưu lấy giá truy cập và thời gian lấy ra: lớp nóng đắt lưu rẻ đọc, lớp lạnh ngược lại, lớp lưu trữ lâu dài rẻ nhất nhưng lấy ra mất hàng giờ và có phí lấy ra. Quy tắc vòng đời tự chuyển đối tượng sang lớp rẻ hơn theo tuổi và tự xoá theo chính sách lưu giữ, và đây là cách thực thi chính sách ở M38 bằng máy. Bẫy thường gặp: chuyển tệp nhỏ sang lớp lạnh có thể đắt hơn giữ nguyên vì có phí tối thiểu cho mỗi đối tượng, nên phải dồn tệp ở lesson 335 trước. Phiên bản đối tượng và vì sao bật nó mà không có quy tắc dọn làm dung lượng tăng âm thầm.",
"Thiết kế quy tắc vòng đời cho dữ liệu của pipeline và ước lượng mức giảm chi phí, kèm cảnh báo về tệp nhỏ.",
"Tầng *đánh giá*. Objective đòi cân giữa chi phí lưu và chi phí truy cập theo mẫu đọc thật. Kiểm bằng bảng ước lượng ba phương án; đạt khi có cả ba yếu tố chi phí và phương án chọn tính đến kích thước tệp.",
"Phân tích mẫu truy cập dữ liệu của pipeline theo tuổi. Thiết kế quy tắc vòng đời. Ước lượng hoá đơn ba phương án gồm giữ nguyên lớp nóng, chuyển sau 30 ngày, và chuyển sau 90 ngày, tính cả ba yếu tố. Tính riêng trường hợp dữ liệu gồm nhiều tệp nhỏ.",
"Chỉ tính chi phí lưu mà quên phí yêu cầu và phí ra · chuyển tệp nhỏ sang lớp lạnh · bật phiên bản đối tượng mà không có quy tắc dọn · đặt vòng đời cho dữ liệu vẫn đang đọc thường xuyên.",
"Bảng ba phương án tính đủ ba yếu tố chi phí, và phương án chọn nêu rõ điều kiện về kích thước tệp."),

(379,"Managed databases and the operations you still own","TH","Lesson 378",
"Cơ sở dữ liệu quản lý bỏ giúp việc cài đặt, vá lỗi, sao lưu tự động và chuyển đổi khi hỏng, nhưng năm việc vẫn thuộc về đội và bỏ qua chúng là cách tốn tiền hoặc mất dữ liệu: thiết kế lược đồ và chỉ mục theo M10, viết truy vấn không làm nghẽn, chọn kích thước và kiểu máy, đặt chính sách sao lưu cùng thời gian giữ, và kiểm chứng khôi phục thật. Việc thứ năm là việc hay bị bỏ nhất: có bản sao lưu không có nghĩa là khôi phục được, và cách duy nhất biết là khôi phục thử, đúng nguyên tắc sẽ đặt ở lesson 395. Bản sao chỉ đọc và cách dùng đúng: đẩy tải phân tích sang bản sao để không làm nghẽn hệ giao dịch, kèm cảnh báo về độ trễ bản sao ở lesson 120. Triển khai nhiều vùng sẵn sàng đổi chi phí gấp đôi lấy khả năng chịu một vùng chết. Bốn chỉ số phải theo dõi trên cơ sở dữ liệu quản lý và ngưỡng nên đặt.",
"Cấu hình một cơ sở dữ liệu quản lý cho pipeline và chứng minh khôi phục được từ bản sao lưu về một mốc thời gian cho trước.",
"Tầng *áp dụng*. Objective là một quy trình vận hành có kết quả kiểm được bằng phép khôi phục thật. Kiểm bằng khôi phục về một mốc và đối soát; đạt khi dữ liệu khôi phục khớp trạng thái tại mốc đó.",
"Dựng cơ sở dữ liệu quản lý, bật sao lưu và khôi phục theo thời điểm. Ghi dữ liệu, ghi lại mốc thời gian, ghi tiếp rồi xoá nhầm một bảng. Khôi phục về mốc đã ghi và đối soát. Đo thời gian khôi phục. Dựng bản sao chỉ đọc và đo độ trễ bản sao dưới tải.",
"Tin vào bản sao lưu mà chưa khôi phục thử lần nào · chạy truy vấn phân tích thẳng trên bản chính · chọn kích thước máy theo cảm tính · để thời gian giữ sao lưu mặc định.",
"Khôi phục về mốc thời gian cho trước và đối soát khớp, có số đo thời gian khôi phục, và có số đo độ trễ bản sao dưới tải."),

(380,"Managed data services - when they earn their price","LT","Lesson 379",
"Nhà cung cấp có dịch vụ quản lý cho gần như mọi thứ đã học: kho dữ liệu, Spark, Kafka, bộ điều phối, sổ đăng ký lược đồ. Câu hỏi không phải dùng hay tự dựng mà là **ở khối lượng nào thì cái nào rẻ hơn tổng thể**, và tổng thể phải gồm cả thời gian người. Ba thành phần chi phí thường bị bỏ khi so: thời gian dựng ban đầu, thời gian vận hành và trực hằng tháng, và chi phí của một sự cố mà đội không đủ năng lực xử lý. Ba tình huống dịch vụ quản lý gần như luôn thắng: đội dưới năm người, khối lượng không đều nên tự dựng phải để dư công suất, và thành phần cần sẵn sàng cao mà đội chưa từng vận hành. Hai tình huống tự dựng thắng: khối lượng rất lớn và ổn định, và yêu cầu cấu hình mà bản quản lý không cho. Bẫy phụ thuộc nhà cung cấp là có thật nhưng thường bị phóng đại: mức độ phụ thuộc phụ thuộc vào việc dữ liệu và logic có nằm ở định dạng mở hay không, đúng lý do M33 chọn định dạng bảng mở.",
"So tổng chi phí sở hữu giữa tự dựng và dịch vụ quản lý cho một thành phần, tính đủ ba thành phần chi phí thường bị bỏ.",
"Tầng *đánh giá*. Objective đòi so hai phương án bằng tổng chi phí sở hữu chứ bằng giá niêm yết. Kiểm bằng bảng so cho hai khối lượng khác nhau; đạt khi tính đủ ba thành phần và kết luận đổi chiều theo khối lượng.",
"Chọn một thành phần đã tự dựng ở các module trước. Lập bảng tổng chi phí sở hữu cho tự dựng và cho bản quản lý, ở hai mức khối lượng cách nhau mười lần. Ước lượng thời gian người bằng số giờ đã bỏ ra thật trong các module trước. Nêu mức khối lượng mà kết luận đổi chiều.",
"So bằng giá niêm yết · bỏ qua thời gian vận hành · kết luận một chiều cho mọi khối lượng · viện lý do phụ thuộc nhà cung cấp mà không xét định dạng dữ liệu.",
"Bảng so tính đủ ba thành phần ở hai mức khối lượng, và nêu được mức khối lượng mà kết luận đổi chiều."),

(381,"Infrastructure as code - declarative state and the plan","TH","Lesson 380",
"Bấm tay trên giao diện có ba hậu quả tích tụ: không ai biết môi trường gồm những gì, môi trường thử và sản xuất lệch nhau, và dựng lại sau sự cố mất nhiều ngày. Hạ tầng bằng mã giải cả ba bằng cách mô tả trạng thái mong muốn trong tệp nộp vào kho mã, cùng tư duy khai báo như ở lesson 366. Vòng lặp ba bước: viết mô tả, xem kế hoạch, áp dụng. **Bước xem kế hoạch là bước quan trọng nhất và cũng hay bị bỏ qua nhất**: nó nói chính xác cái gì sẽ tạo, sửa, và xoá, nên đọc kỹ nó là cách duy nhất tránh xoá nhầm tài nguyên có dữ liệu. Đọc kế hoạch cần biết phân biệt thay đổi tại chỗ với thay đổi buộc tạo lại, vì loại thứ hai với một cơ sở dữ liệu nghĩa là mất dữ liệu. Tệp trạng thái ghi hệ đang quản lý những gì, và vì sao nó chứa thông tin nhạy cảm nên phải lưu ở kho có mã hoá và có khoá. So với kịch bản mệnh lệnh: mã khai báo chạy lại nhiều lần cho cùng kết quả.",
"Dựng một phần hạ tầng bằng mã, đọc được kế hoạch và chỉ ra thay đổi nào buộc tạo lại tài nguyên.",
"Tầng *áp dụng*. Objective gồm một kỹ năng đọc có hậu quả trực tiếp tới an toàn dữ liệu. Kiểm bằng bài đọc kế hoạch có bẫy; đạt khi nhận ra đúng thay đổi buộc tạo lại trước khi áp dụng.",
"Dựng mạng và một kho đối tượng bằng mã. Sửa một thuộc tính sửa tại chỗ được và một thuộc tính buộc tạo lại, xem kế hoạch và phân loại hai thay đổi trước khi áp dụng. Xoá một tài nguyên bằng tay trên giao diện rồi chạy kế hoạch và quan sát hệ phát hiện lệch.",
"Áp dụng mà không đọc kế hoạch · lưu tệp trạng thái trong kho mã · sửa bằng tay rồi quên cập nhật mã · nhầm thay đổi tại chỗ với thay đổi tạo lại.",
"Phân loại đúng hai loại thay đổi trước khi áp dụng, và hệ phát hiện đúng phần lệch sau khi sửa tay."),

(382,"Modules, state and working in a team","TH","Lesson 381",
"Khi nhiều người cùng sửa hạ tầng, tệp trạng thái thành tài nguyên tranh chấp: hai người chạy áp dụng cùng lúc thì trạng thái hỏng. Kho trạng thái từ xa có khoá giải việc đó, và đây là điều kiện bắt buộc trước khi người thứ hai tham gia. Chia mã thành mô đun theo ranh giới thay đổi cùng nhau chứ theo loại tài nguyên: mạng đổi hiếm, cơ sở dữ liệu đổi vừa, ứng dụng đổi thường xuyên, nên tách ba tầng đó ra ba trạng thái riêng để thay đổi ở tầng nhanh không phải chạm vào tầng chậm và không có nguy cơ xoá nhầm. Tham số hoá theo môi trường để cùng mã dựng cả thử lẫn sản xuất, chỉ khác giá trị đầu vào; đây là cách duy nhất bảo đảm hai môi trường giống nhau. Ghim phiên bản của nhà cung cấp và của mô đun, cùng lý do ghim ảnh nền ở lesson 358. Đưa lệnh xem kế hoạch vào yêu cầu hợp nhất mã để người rà soát thấy hệ quả trước khi duyệt.",
"Tổ chức mã hạ tầng thành nhiều trạng thái theo nhịp thay đổi, và dựng được hai môi trường giống nhau từ cùng một mã.",
"Tầng *sáng tạo*. Objective đòi thiết kế cấu trúc mã theo ranh giới thay đổi, chứ áp dụng một khuôn có sẵn. Kiểm bằng phép so hai môi trường cộng phép thử thay đổi tầng nhanh; đạt khi hai môi trường khác nhau đúng phần tham số và thay đổi tầng ứng dụng không chạm trạng thái tầng mạng.",
"Chuyển mã sang kho trạng thái từ xa có khoá. Tách thành ba trạng thái theo nhịp thay đổi. Dựng hai môi trường từ cùng mã với hai bộ tham số và so khác biệt. Thay đổi một thuộc tính ở tầng ứng dụng và chứng minh kế hoạch không đụng tài nguyên mạng.",
"Giữ mọi thứ trong một trạng thái khổng lồ · dùng trạng thái cục bộ khi làm nhóm · sao chép mã cho môi trường thứ hai thay vì tham số hoá · không ghim phiên bản.",
"Hai môi trường chỉ khác nhau ở phần tham số, và thay đổi tầng ứng dụng cho kế hoạch không chạm tài nguyên tầng mạng."),

(383,"Environments, drift and a destroy that must be safe","TH","Lesson 382",
"Lệch cấu hình xảy ra khi thực tế khác mã, do sửa tay lúc xử lý sự cố hoặc do nhà cung cấp tự đổi. Phát hiện bằng cách chạy kế hoạch định kỳ trong tích hợp liên tục và cảnh báo khi kế hoạch không rỗng; đây là chỉ số sức khoẻ của kỷ luật hạ tầng bằng mã. Hai cách xử lý khi phát hiện và tiêu chí chọn: đưa thực tế về khớp mã, hoặc đưa mã về khớp thực tế nếu thay đổi tay là đúng. Lệnh huỷ là thứ nguy hiểm nhất trong module: nó xoá mọi thứ trạng thái đang quản lý, và chạy nhầm ở sản xuất là sự cố không lùi được. Ba lớp bảo vệ phải đặt trước khi ai đó chạy được lệnh huỷ: bảo vệ chống xoá trên tài nguyên có dữ liệu, tách quyền sao cho tài khoản thường không xoá được tài nguyên có trạng thái, và bắt buộc xem kế hoạch huỷ rồi có người thứ hai duyệt. Vì sao môi trường thử nên huỷ và dựng lại định kỳ: đó là cách duy nhất biết mã hạ tầng còn dựng lại được.",
"Phát hiện lệch cấu hình tự động, và dựng được ba lớp bảo vệ sao cho lệnh huỷ không xoá được tài nguyên có dữ liệu.",
"Tầng *áp dụng*. Objective gồm một cơ chế phát hiện và một cơ chế phòng vệ, cả hai kiểm được bằng thử nghiệm. Kiểm bằng thử huỷ có kiểm soát; đạt khi lệch được phát hiện tự động và lệnh huỷ bị chặn ở tài nguyên có dữ liệu.",
"Sửa tay một tài nguyên trên giao diện. Dựng bước chạy kế hoạch định kỳ và xác nhận nó báo lệch. Đặt bảo vệ chống xoá cho kho dữ liệu. Chạy lệnh huỷ ở môi trường thử và xác nhận nó dừng lại ở tài nguyên được bảo vệ. Huỷ sạch môi trường thử rồi dựng lại từ mã và chạy lại bộ kiểm thử.",
"Không có cơ chế phát hiện lệch · chạy huỷ mà không xem kế hoạch · dùng cùng tài khoản cho thử và sản xuất · chưa bao giờ dựng lại môi trường thử từ đầu.",
"Lệch được phát hiện tự động, lệnh huỷ bị chặn ở tài nguyên có dữ liệu, và môi trường thử dựng lại từ mã chạy được bộ kiểm thử."),

(384,"Cost - tagging, budgets and the bill that surprised the team","TH","Lesson 383",
"Chi phí đám mây tăng âm thầm vì tài nguyên dựng ra thì nhớ mà tắt thì quên, và vì đơn vị tính phí nhỏ tới mức không ai thấy đắt cho tới khi cộng lại cuối tháng. Điều kiện tiên quyết để quản được là gắn nhãn: mọi tài nguyên phải có nhãn về môi trường, đội sở hữu và thành phần, cưỡng chế bằng chính sách chứ bằng nhắc nhở, và gắn ngay trong mã hạ tầng. Không có nhãn thì hoá đơn chỉ là một con số và không truy được về ai. Bốn nguồn chi phí bất ngờ thường gặp trong hệ dữ liệu: truyền dữ liệu ra khỏi vùng ở lesson 378, cụm để chạy qua đêm sau khi thử nghiệm, kho đối tượng có phiên bản mà không dọn, và nhật ký giữ quá lâu. Ngân sách và cảnh báo theo ngưỡng, kèm cảnh báo theo xu hướng vì ngưỡng tháng báo quá muộn. Chi phí trên mỗi đơn vị nghiệp vụ là chỉ số đáng theo dõi hơn tổng chi phí, vì nó tách phần tăng do tăng trưởng khỏi phần tăng do lãng phí.",
"Gắn nhãn toàn bộ hạ tầng bằng mã, truy được chi phí về từng thành phần, và đặt cảnh báo bắt được một khoản tăng bất thường.",
"Tầng *áp dụng*. Objective là một cơ chế quản trị kiểm được bằng việc truy ngược một khoản chi. Kiểm bằng phép truy ngược cộng thử cảnh báo; đạt khi mọi tài nguyên có nhãn và cảnh báo kích hoạt trước ngưỡng tháng.",
"Thêm nhãn bắt buộc vào mọi tài nguyên trong mã. Dựng chính sách từ chối tài nguyên thiếu nhãn. Lập báo cáo chi phí theo thành phần. Đặt ngân sách và hai cảnh báo, một theo ngưỡng và một theo xu hướng. Cố ý dựng một cụm đắt và bỏ chạy qua đêm, rồi kiểm cảnh báo nào báo trước.",
"Gắn nhãn bằng tay · chỉ đặt cảnh báo theo ngưỡng tháng · theo dõi tổng chi phí mà không chia theo thành phần · quên tắt môi trường thử ngoài giờ.",
"Mọi tài nguyên có đủ nhãn và chính sách chặn được tài nguyên thiếu nhãn, và cảnh báo theo xu hướng báo trước cảnh báo ngưỡng có số."),

(385,"Mapping services across providers","LT","Lesson 384",
"Bài duy nhất trong module nhìn ra ngoài một nhà cung cấp, và mục tiêu là đọc được tài liệu của nhà cung cấp khác mà không phải học lại từ đầu. Nguyên tắc: **ánh xạ theo chức năng, không theo tên**, vì chức năng ổn định còn tên thì đổi. Bảng ánh xạ cho tám chức năng đã dùng trong chương trình: lưu trữ đối tượng, kho dữ liệu, cơ sở dữ liệu quan hệ quản lý, Spark quản lý, Kafka quản lý, bộ điều phối quản lý, chạy container, và quản lý bí mật. Với mỗi chức năng, ghi tên của ba nhà cung cấp lớn cùng một khác biệt đáng chú ý, vì các dịch vụ tương đương về chức năng vẫn khác về mô hình tính phí hoặc giới hạn. Ba khác biệt có hệ quả thật khi chuyển nhà cung cấp: mô hình tính phí của kho dữ liệu, cách tính lưu lượng ra, và mức độ tương thích với định dạng bảng mở ở M33. Mức `C` ở đây theo đúng quy ước mục 2: biết dùng đúng tình huống, không đòi vận hành.",
"Lập bảng ánh xạ tám chức năng sang ba nhà cung cấp, và nêu với mỗi chức năng một khác biệt có hệ quả thật.",
"Tầng *hiểu*. Objective là năng lực đọc tài liệu chéo nhà cung cấp, không phải vận hành. Kiểm bằng bảng ánh xạ cộng bài đọc tài liệu; đạt khi đủ tám chức năng và mỗi dòng có một khác biệt cụ thể chứ một nhận xét chung.",
"Lập bảng tám chức năng nhân ba nhà cung cấp từ tài liệu chính thức đang hiện hành. Với mỗi chức năng, đọc trang giá của ít nhất hai nhà và ghi một khác biệt về mô hình tính phí. Cho ba yêu cầu kiến trúc và chọn dịch vụ tương ứng ở cả ba nhà.",
"Học thuộc tên dịch vụ · chép bảng so sánh của bên thứ ba thay vì đọc tài liệu chính thức · kết luận nhà cung cấp nào tốt hơn mà không nêu khối lượng công việc.",
"Bảng tám chức năng nhân ba nhà cung cấp đầy đủ, mỗi dòng có một khác biệt cụ thể dẫn từ tài liệu chính thức."),

(386,"Deploying the reference pipeline to the cloud","DA","Lesson 385",
"Bài dự án khép module: đưa toàn bộ pipeline tham chiếu lên đám mây, dựng hoàn toàn bằng mã. Yêu cầu bắt buộc và mỗi yêu cầu đều kiểm được: mọi tài nguyên dựng bằng mã, không có tài nguyên nào tạo tay; hai môi trường thử và sản xuất từ cùng mã khác tham số; cơ sở dữ liệu không có đường vào từ mạng công cộng; mọi danh tính theo đặc quyền tối thiểu với chính sách rút từ nhật ký gọi thật; mọi tài nguyên có nhãn đầy đủ; và có ngân sách kèm cảnh báo. Phép thử nghiệm thu là phép thử huỷ và dựng lại: huỷ sạch môi trường thử, dựng lại bằng một lệnh, chạy lại pipeline và đối soát kết quả. Nộp kèm ước lượng hoá đơn tháng chia theo thành phần và một danh sách ba khoản có thể cắt kèm số tiền. Đây là hồ sơ đi thẳng vào phần chi phí của bài kiến trúc ở M39.",
"Dựng toàn bộ hạ tầng bằng mã đạt sáu yêu cầu, và huỷ rồi dựng lại được môi trường thử bằng một lệnh.",
"Tầng *sáng tạo*. Bài tổng hợp module thành một hạ tầng hoàn chỉnh dưới ràng buộc bảo mật và chi phí. Kiểm bằng phép thử huỷ và dựng lại cộng rà soát sáu yêu cầu; đạt khi cả sáu đạt và pipeline chạy lại được sau khi dựng lại.",
"Dựng toàn bộ hạ tầng bằng mã cho hai môi trường. Kiểm sáu yêu cầu bằng bảng có bằng chứng cho từng dòng. Huỷ sạch môi trường thử và dựng lại, chạy pipeline và đối soát. Nộp ước lượng hoá đơn theo thành phần và ba khoản cắt được kèm số tiền.",
"Tạo tay vài tài nguyên rồi ghi vào mã sau · dùng chung một tài khoản cho hai môi trường · bỏ phép thử huỷ và dựng lại vì sợ · ước lượng hoá đơn mà không chia theo thành phần.",
"Sáu yêu cầu đều có bằng chứng, môi trường thử dựng lại bằng một lệnh và pipeline đối soát khớp, và ước lượng hoá đơn chia theo thành phần kèm ba khoản cắt được."),
]

M38 = ("Operations, Observability, Security and Cost", 387, 400, """| | |
|---|---|
| **Objective cấp module** | Vận hành được nền tảng dữ liệu dưới sự cố: có mục tiêu mức dịch vụ đo được, cảnh báo đáng tin, quy trình xử lý sự cố, và khôi phục đã kiểm chứng |
| **Tiền đề** | M37 |
| **Exit criterion** | Qua được buổi diễn tập sự cố: phát hiện trong ngưỡng, chẩn đoán đúng, khắc phục, thông báo đúng đối tượng, và viết phân tích sau sự cố không đổ lỗi |
| **Kỹ năng SFIA** | `CFMG` mức 4 · `SYSP` mức 4 |
| **Chế độ hỏng** | Dựng theo dõi rồi để cảnh báo kêu suốt tới khi cả đội tắt thông báo, nên sự cố thật đi qua mà không ai biết |""",
"""Module này là phần phân biệt người xây được hệ với người vận hành được hệ, và là lý do trọng số 25% cho khả năng phục hồi trong thang điểm tốt nghiệp.

Nhiều cơ chế đã gặp lẻ tẻ ở các module trước: cảnh báo theo xu hướng ở lesson 300 và 315, quy trình bảy bước ở M26, thí nghiệm hỏng ở lesson 218 và 298. Module gom chúng thành một hệ vận hành có chuẩn và có bằng chứng.""")

L38 = [
(387,"Service level indicators, objectives and agreements for data","LT","Module 38: M37",
"Ba khái niệm hay bị dùng lẫn và phân biệt được chúng là điều kiện để nói chuyện với bên nghiệp vụ. Chỉ báo là một phép đo, mục tiêu là ngưỡng đội tự đặt cho chỉ báo đó, thoả thuận là cam kết với bên ngoài kèm hậu quả nếu vi phạm. Đội dữ liệu nên có mục tiêu trước, và chỉ ký thoả thuận khi đã đo đủ lâu để biết mình giữ được. Bốn chỉ báo hợp với nền tảng dữ liệu, khác với chỉ báo của dịch vụ trực tuyến: độ tươi tức dữ liệu mới tới đâu, độ đầy đủ tức bao nhiêu phần trăm bản ghi kỳ vọng đã có, độ đúng tức tỉ lệ qua kiểm chất lượng ở M20, và tính sẵn có của truy vấn. Cách đặt mục tiêu có căn cứ: đo phân bố hiện tại rồi đặt ngưỡng ở mức vừa đủ nghiêm để có ý nghĩa và vừa đủ lỏng để giữ được, chứ đặt con số tròn. Ngân sách lỗi là phần được phép vi phạm, và công dụng thật của nó là làm cơ sở quyết định tốc độ phát hành.",
"Đặt mục tiêu mức dịch vụ cho pipeline từ phân bố đo được, và nêu ngân sách lỗi tương ứng cùng cách dùng nó.",
"Tầng *áp dụng*. Objective là chuyển một yêu cầu mơ hồ thành ngưỡng đo được, nối tiếp kỷ luật ở M26. Kiểm bằng bốn chỉ báo có phân bố thật; đạt khi cả bốn có ngưỡng dẫn từ phân bố và có ngân sách lỗi tính ra số.",
"Đo phân bố bốn chỉ báo trên pipeline trong bảy ngày. Đặt mục tiêu cho từng chỉ báo dẫn từ phân bố. Tính ngân sách lỗi theo tháng cho từng cái. Viết một thoả thuận ngắn với bên dùng cho chỉ báo độ tươi, gồm cam kết, cách đo, và cái gì xảy ra khi vi phạm.",
"Đặt mục tiêu bằng số tròn · cam kết mức không thực tế · lẫn mục tiêu nội bộ với cam kết ra ngoài · đặt mục tiêu cho chỉ báo chưa từng đo.",
"Bốn mục tiêu đều dẫn từ phân bố bảy ngày, ngân sách lỗi tính ra số cụ thể, và thoả thuận nêu đủ cam kết, cách đo và hậu quả."),

(388,"What to instrument on a data platform","TH","Lesson 387",
"Đo cái gì quyết định chẩn đoán được hay không, và đo sai chỗ là lý do sự cố kéo dài hàng giờ. Ba tầng phải có số đo và chỉ có tầng thứ ba mới nói được người dùng có vấn đề hay không: tầng hạ tầng gồm CPU, bộ nhớ, đĩa, mạng; tầng thành phần gồm độ trễ tiêu thụ ở lesson 300, khe sao chép ở lesson 315, dung lượng xáo trộn ở M34; tầng dữ liệu gồm bốn chỉ báo ở lesson 387. Nguyên tắc rút ra: **cảnh báo trên tầng dữ liệu vì đó là thứ người dùng cảm nhận, dùng hai tầng dưới để chẩn đoán**. Quy ước đặt tên và gắn nhãn cho số đo để cắt lát được theo pipeline, theo bảng và theo môi trường; thiếu nhãn thì có số mà không trả lời được câu hỏi nào. Ba loại số đo và khi nào dùng loại nào: bộ đếm cho việc đã xảy ra, thước đo cho giá trị hiện tại, biểu đồ phân bố cho độ trễ vì trung bình che mất đuôi phân bố.",
"Dựng bộ số đo ba tầng cho pipeline với nhãn đủ để cắt lát, và chỉ ra số đo nào dùng để cảnh báo, số nào dùng để chẩn đoán.",
"Tầng *áp dụng*. Objective là thiết kế bộ số đo phục vụ chẩn đoán, kiểm được bằng việc trả lời câu hỏi thật. Kiểm bằng năm câu hỏi chẩn đoán; đạt khi trả lời được ít nhất bốn chỉ bằng bảng điều khiển.",
"Gắn số đo ba tầng cho pipeline, dùng đúng ba loại số đo. Dựng một bảng điều khiển. Giảng viên đặt năm câu hỏi chẩn đoán và bạn phải trả lời chỉ bằng bảng điều khiển, không mở nhật ký. Ghi lại câu nào không trả lời được và thiếu số đo gì.",
"Chỉ đo tầng hạ tầng · dùng trung bình cho độ trễ · quên gắn nhãn nên không cắt lát được · dựng bảng điều khiển đẹp mà không trả lời được câu hỏi nào.",
"Trả lời được ≥ 4/5 câu hỏi chẩn đoán chỉ bằng bảng điều khiển, và ghi rõ số đo còn thiếu cho câu không trả lời được."),

(389,"Logs, metrics and traces - and correlating across a pipeline","TH","Lesson 388",
"Ba loại tín hiệu trả lời ba loại câu hỏi và dùng một loại cho mọi việc là cách vừa tốn tiền vừa chẩn đoán chậm. Số đo trả lời có vấn đề không và ở đâu, rẻ để lưu, không có chi tiết từng sự kiện. Nhật ký trả lời chuyện gì đã xảy ra với một bản ghi cụ thể, đắt để lưu nên phải có chính sách giữ. Dấu vết trả lời thời gian tiêu ở đâu trong một chuỗi bước, quan trọng khi một yêu cầu đi qua nhiều thành phần. Mã theo dõi ở lesson 74 là thứ nối cả ba: một mã duy nhất đi theo dữ liệu từ nguồn qua mọi bước tới đích, để khi số sai ở mart thì truy ngược được tới lô nạp nào. Nhật ký có cấu trúc thay vì chuỗi tự do, vì có cấu trúc thì truy vấn được. Ba mức nhật ký và quy tắc dùng, cùng lý do ghi ở mức gỡ lỗi trong sản xuất là cách làm hoá đơn tăng mà không ai đọc.",
"Truy ngược được một bản ghi sai ở mart về đúng lô nạp và bước biến đổi sinh ra nó, chỉ bằng mã theo dõi.",
"Tầng *phân tích*. Objective là năng lực truy ngược xuyên thành phần, kỹ năng quyết định thời gian xử lý sự cố. Kiểm bằng ba bản ghi sai tiêm sẵn tính giờ; đạt khi truy đúng nguồn gốc ít nhất hai trong giới hạn thời gian.",
"Thêm mã theo dõi đi xuyên toàn bộ pipeline và ghi nhật ký có cấu trúc ở mọi bước. Giảng viên tiêm ba bản ghi sai ở mart, mỗi lần 10 phút. Truy ngược từng cái về lô nạp và bước sinh ra nó. Dựng dấu vết cho một yêu cầu đi qua bốn thành phần và chỉ ra bước tốn thời gian nhất.",
"Ghi nhật ký dạng chuỗi tự do · không có mã theo dõi xuyên hệ · để mức gỡ lỗi trong sản xuất · lưu nhật ký vô thời hạn.",
"Truy đúng nguồn gốc ≥ 2/3 bản ghi sai trong giới hạn thời gian, và dấu vết chỉ ra đúng bước tốn thời gian nhất."),

(390,"Alerting that people do not silence","TH","Lesson 389",
"Mệt mỏi cảnh báo là chế độ hỏng của chính hệ theo dõi, và khi đội đã tắt thông báo thì mọi công sức dựng theo dõi thành vô ích. Bốn tiêu chí cho một cảnh báo đáng giữ: nó chỉ ra một vấn đề người dùng cảm nhận được, nó có người cụ thể chịu trách nhiệm, người đó làm được một việc cụ thể ngay, và nó hiếm khi sai. Cảnh báo không đủ bốn tiêu chí thì chuyển thành phiếu công việc hoặc số đo trên bảng điều khiển chứ đánh thức người. Phân biệt cảnh báo theo triệu chứng với cảnh báo theo nguyên nhân: báo theo triệu chứng tức dữ liệu trễ quá ngưỡng thì ít và đáng tin; báo theo nguyên nhân tức CPU cao thì nhiều và hay sai. Kỹ thuật giảm nhiễu: đặt ngưỡng theo xu hướng như đã làm ở lesson 300, yêu cầu vi phạm kéo dài một khoảng, gom cảnh báo cùng nguyên nhân, và tạm ẩn trong cửa sổ bảo trì. Đo chính hệ cảnh báo: tỉ lệ cảnh báo dẫn tới hành động, và xem lại hằng tháng.",
"Rà bộ cảnh báo hiện có theo bốn tiêu chí, loại bỏ hoặc hạ cấp cái không đạt, và đo tỉ lệ cảnh báo dẫn tới hành động.",
"Tầng *đánh giá*. Objective đòi phán đoán giữ hay bỏ từng cảnh báo theo tiêu chí, chứ thêm cảnh báo. Kiểm bằng bảng rà soát cộng số đo hai tuần; đạt khi mọi cảnh báo còn lại đạt cả bốn tiêu chí và tỉ lệ dẫn tới hành động tăng.",
"Lập danh sách mọi cảnh báo đang có, chấm theo bốn tiêu chí. Loại hoặc hạ cấp cái không đạt. Chuyển ít nhất hai cảnh báo từ nguyên nhân sang triệu chứng. Chạy hai tuần, đếm số cảnh báo và số lần dẫn tới hành động thật, so với hai tuần trước.",
"Thêm cảnh báo cho mọi số đo · cảnh báo theo ngưỡng tài nguyên · để cảnh báo không có người chịu trách nhiệm · giảm nhiễu bằng cách tắt thông báo.",
"Mọi cảnh báo còn lại đạt cả bốn tiêu chí, và tỉ lệ cảnh báo dẫn tới hành động của hai tuần sau cao hơn hai tuần trước có số."),

(391,"On-call, escalation and the incident commander","LT","Lesson 390",
"Trực là một hệ thống tổ chức chứ một danh sách số điện thoại, và thiết kế kém làm người giỏi nghỉ việc. Bốn thành phần: lịch trực có người thay, đường leo thang khi người trực không xử lý được, mức độ nghiêm trọng quyết định tốc độ phản ứng, và cam kết thời gian phản hồi theo từng mức. Ba mức nghiêm trọng đủ dùng cho nền tảng dữ liệu, mỗi mức kèm ví dụ cụ thể và kỳ vọng thời gian. Vai người chỉ huy sự cố tách khỏi vai người sửa, và đây là chi tiết quyết định khi sự cố kéo dài: người chỉ huy điều phối, ghi dòng thời gian và liên lạc với bên ngoài, còn người sửa tập trung sửa; gộp hai vai thì hoặc mất liên lạc hoặc mất tập trung. Điều kiện để trực bền vững: sổ tay cho các sự cố hay gặp, quyền đủ để xử lý mà không phải chờ ai, và bù giờ. Ba dấu hiệu hệ trực đang hỏng và cần sửa trước khi mất người.",
"Thiết kế lịch trực và đường leo thang cho một đội cho trước, phân mức nghiêm trọng cho năm sự cố mẫu.",
"Tầng *hiểu*. Bài thiết kế tổ chức chứ kỹ thuật, nên objective dừng ở chỗ áp đúng khuôn vào một bối cảnh. Kiểm bằng bài phân mức cộng bản thiết kế; đạt khi phân đúng ít nhất bốn trong năm và bản thiết kế có đủ bốn thành phần.",
"Cho một đội bốn người và năm sự cố mẫu. Phân mức nghiêm trọng cho từng sự cố kèm lý do. Thiết kế lịch trực có người thay và đường leo thang hai cấp. Viết định nghĩa vai người chỉ huy sự cố cho đội này, nêu rõ việc họ làm và không làm.",
"Gộp vai chỉ huy với vai sửa · đặt mọi sự cố ở mức cao nhất · lịch trực không có người thay · để người trực thiếu quyền xử lý.",
"Phân đúng mức cho ≥ 4/5 sự cố kèm lý do, và bản thiết kế có đủ lịch trực, đường leo thang, ba mức nghiêm trọng và định nghĩa vai chỉ huy."),

(392,"Incident response - the seven steps under time pressure","TH","Lesson 391",
"Quy trình bảy bước đã đặt ở M26 nay áp cho toàn nền tảng, và điểm khác là thứ tự phải giữ được dưới áp lực. Bước một là chặn lan rộng, làm trước cả chẩn đoán: dừng pipeline đang ghi sai còn hơn để nó ghi thêm một giờ. Bước hai thông báo sớm cho người dùng đang dùng số, vì thông báo muộn tốn kém hơn thông báo thừa. Bước ba chẩn đoán bằng ba tầng số đo ở lesson 388. Bước bốn khắc phục, ưu tiên khôi phục dịch vụ chứ tìm nguyên nhân gốc. Bước năm chạy lại lịch sử để sửa dữ liệu đã sai, và đây là chỗ tính bất biến ở lesson 222 trả cổ tức. Bước sáu thông báo kết quả cho đúng những người đã nhận thông báo ở bước hai. Bước bảy phân tích nguyên nhân gốc, làm sau khi hết áp lực chứ trong lúc sự cố. Hai thứ phải ghi ngay trong lúc xử lý vì sau sẽ quên: dòng thời gian và mọi thay đổi đã thực hiện.",
"Chạy đúng bảy bước trong một sự cố mô phỏng tính giờ, giữ đúng thứ tự và ghi được dòng thời gian dùng được.",
"Tầng *áp dụng*. Objective là thực hiện một quy trình dưới áp lực thời gian, kiểm được bằng quan sát. Kiểm bằng diễn tập tính giờ; đạt khi chặn lan rộng trước chẩn đoán, thông báo trong ngưỡng, và dòng thời gian đủ dựng lại được diễn biến.",
"Giảng viên gây một sự cố làm pipeline ghi dữ liệu sai vào mart. Đội chạy bảy bước với vai chỉ huy và vai sửa tách biệt. Tính giờ từng bước. Sau khi xong, dựng lại diễn biến chỉ bằng dòng thời gian đã ghi và kiểm xem có thiếu gì.",
"Chẩn đoán trước khi chặn lan rộng · thông báo sau khi đã sửa xong · quên ghi dòng thời gian · tìm nguyên nhân gốc trong lúc còn đang cháy.",
"Chặn lan rộng trước chẩn đoán, thông báo trong ngưỡng cam kết, và dòng thời gian đủ để người ngoài dựng lại diễn biến."),

(393,"Blameless postmortem and the action that actually lands","TH","Lesson 392",
"Phân tích sau sự cố có hai mục đích và chỉ một mục đích là đúng: học để hệ an toàn hơn, chứ xác định ai sai. Không đổ lỗi không phải lịch sự mà là kỹ thuật: khi đổ lỗi thì người ta giấu thông tin, và mất thông tin thì không học được, nên hệ kém an toàn đi. Cấu trúc một bản phân tích dùng được: tóm tắt tác động bằng số chứ bằng tính từ, dòng thời gian, phân tích nguyên nhân đi qua nhiều tầng chứ dừng ở tầng đầu, những gì đã chạy tốt, và hành động khắc phục. Kỹ thuật hỏi vì sao nhiều lần với cảnh báo: dừng khi tới một nguyên nhân mà hệ thống sửa được, chứ dừng ở lỗi người. Điều kiện để hành động khắc phục thực sự xảy ra: mỗi hành động có một người chịu trách nhiệm, có hạn, và được đưa vào kế hoạch công việc như mọi việc khác; hành động không có chủ và không có hạn là hành động không bao giờ làm. Theo dõi tỉ lệ hành động hoàn thành như một chỉ số sức khoẻ của đội.",
"Viết một bản phân tích sau sự cố không đổ lỗi, truy nguyên nhân tới tầng hệ thống sửa được, và đặt hành động có chủ và có hạn.",
"Tầng *đánh giá*. Objective đòi phán đoán về độ sâu của nguyên nhân và chất lượng hành động, chứ điền một mẫu. Kiểm bằng rà soát chéo; đạt khi nguyên nhân tới tầng hệ thống và mọi hành động có chủ, có hạn, và kiểm chứng được.",
"Viết bản phân tích cho sự cố ở lesson 392. Dùng kỹ thuật hỏi vì sao nhiều lần và ghi lại từng tầng. Đặt ba hành động khắc phục, mỗi hành động có chủ, hạn, và cách biết là đã xong. Rà soát chéo với nhóm khác: họ tìm chỗ nào trong bản của bạn còn ám chỉ lỗi cá nhân.",
'Kết luận nguyên nhân là ai đó bất cẩn · viết hành động dạng "sẽ cẩn thận hơn" · không đặt hạn · bỏ phần những gì đã chạy tốt.',
"Nguyên nhân truy tới tầng hệ thống sửa được, ba hành động đều có chủ và hạn và cách kiểm chứng, và qua được rà soát chéo về ngôn ngữ không đổ lỗi."),

(394,"Failure mode analysis and cascading failure","TH","Lesson 393",
"Phân tích chế độ hỏng làm trước khi sự cố xảy ra: với mỗi thành phần, liệt kê nó hỏng theo những cách nào, hệ phản ứng ra sao, và người dùng thấy gì. Làm có hệ thống thay vì theo trí nhớ, vì trí nhớ chỉ nhớ sự cố gần nhất. Điểm hỏng đơn lẻ là thành phần mà nó chết thì cả hệ dừng, và tìm ra chúng là kết quả chính của bài tập này. Hỏng xếp tầng là cơ chế một sự cố nhỏ thành sự cố lớn: một thành phần chậm làm thành phần gọi nó dồn yêu cầu, hết tài nguyên, rồi kéo theo thành phần kế tiếp. Ba cơ chế chặn xếp tầng: bộ ngắt mạch dừng gọi khi bên kia đang hỏng, vách ngăn cô lập tài nguyên cho từng loại việc, và giảm tải chủ động từ chối bớt để phần còn lại sống. Thử lại có hai chiều tác dụng: không có lùi theo hàm mũ và nhiễu ngẫu nhiên thì thử lại làm sự cố nặng thêm, đúng bão thử lại ở lesson 61 và cơ chế đã học ở lesson 34.",
"Lập bảng chế độ hỏng cho pipeline, tìm ra điểm hỏng đơn lẻ, và chứng minh bằng thực nghiệm một cơ chế chặn xếp tầng hoạt động.",
"Tầng *phân tích*. Objective là phân tích có hệ thống trước sự cố cộng một kiểm chứng thực nghiệm. Kiểm bằng bảng cộng thí nghiệm; đạt khi tìm ra ít nhất hai điểm hỏng đơn lẻ và cơ chế chặn được chứng minh bằng số đo.",
"Lập bảng chế độ hỏng cho mọi thành phần của pipeline, mỗi dòng gồm cách hỏng, phản ứng của hệ, và biểu hiện với người dùng. Đánh dấu điểm hỏng đơn lẻ. Tạo một hỏng xếp tầng bằng cách làm chậm một thành phần hạ nguồn. Thêm bộ ngắt mạch và lặp lại, đo khác biệt.",
"Liệt kê chế độ hỏng theo trí nhớ · bỏ qua hỏng dạng chậm mà chỉ xét hỏng dạng chết · thêm thử lại mà không có lùi theo hàm mũ · coi xếp tầng là chuyện chỉ xảy ra ở hệ lớn.",
"Bảng chế độ hỏng phủ mọi thành phần, tìm ra ≥ 2 điểm hỏng đơn lẻ, và có số đo chứng minh bộ ngắt mạch chặn được xếp tầng."),

(395,"Disaster recovery - RTO, RPO and a restore you have tested","TH","Lesson 394",
"Hai con số quyết định mọi thiết kế khôi phục và **cả hai phải do nghiệp vụ quyết chứ kỹ thuật tự đặt**: mục tiêu thời gian khôi phục là chịu được bao lâu không có dịch vụ, mục tiêu điểm khôi phục là chịu mất bao nhiêu dữ liệu tính theo thời gian. Từ hai con số đó suy ra tần suất sao lưu, chiến lược nhân bản và ngân sách; đặt cả hai về không là yêu cầu bất khả thi về chi phí, nên phần việc thật là đàm phán. Ba mức chiến lược theo chi phí tăng dần: chỉ sao lưu và khôi phục, giữ một bản chờ tối thiểu, và chạy song song hai vùng. Nguyên tắc không thoả hiệp: **bản sao lưu chưa khôi phục thử thì chưa phải bản sao lưu**, và diễn tập khôi phục phải có lịch định kỳ chứ làm khi rảnh. Bốn thứ hay bị quên khỏi kế hoạch khôi phục và đều làm kế hoạch thất bại lúc cần: định nghĩa hạ tầng, bí mật, cấu hình bộ điều phối, và chính người biết quy trình.",
"Xác định hai con số mục tiêu từ yêu cầu nghiệp vụ, chọn chiến lược tương ứng, và khôi phục thật đạt trong thời gian mục tiêu.",
"Tầng *đánh giá*. Objective đòi nối một yêu cầu nghiệp vụ với một thiết kế kỹ thuật và chứng minh bằng diễn tập. Kiểm bằng diễn tập khôi phục tính giờ; đạt khi khôi phục xong trong thời gian mục tiêu và dữ liệu mất nằm trong điểm mục tiêu.",
"Phỏng vấn một người đóng vai bên nghiệp vụ để chốt hai con số. Chọn chiến lược và ước lượng chi phí. Diễn tập: xoá sạch môi trường sản xuất mô phỏng và khôi phục hoàn toàn, tính giờ. Kiểm bốn thứ hay quên có nằm trong kế hoạch không. Ghi lại khoảng cách giữa mục tiêu và thực tế.",
"Kỹ thuật tự đặt hai con số · tin vào sao lưu chưa từng khôi phục · quên bí mật và định nghĩa hạ tầng khỏi kế hoạch · diễn tập trên môi trường không giống sản xuất.",
"Khôi phục hoàn tất trong thời gian mục tiêu với lượng dữ liệu mất trong ngưỡng, và bốn thứ hay quên đều có trong kế hoạch."),

(396,"Data security - classification, encryption and access","TH","Lesson 395",
"Bảo vệ dữ liệu bắt đầu bằng phân loại, vì không biết dữ liệu nào nhạy cảm thì không thể bảo vệ đúng mức và bảo vệ mọi thứ ở mức cao nhất thì không ai làm nổi. Ba tới bốn mức phân loại đủ dùng, mỗi mức kèm yêu cầu cụ thể về mã hoá, quyền và ghi nhật ký truy cập. Mã hoá ở hai trạng thái: khi lưu thường bật một công tắc và ít tranh cãi; khi truyền đòi cấu hình ở mọi chặng và hay bị hở ở chặng nội bộ vì nghĩ mạng riêng là an toàn. Quản lý khoá và vì sao khoá do khách hàng quản lý đổi mô hình trách nhiệm. Che và ẩn danh dữ liệu cho môi trường thử: sao chép dữ liệu sản xuất sang môi trường thử là cách lộ dữ liệu phổ biến nhất trong đội dữ liệu, nên phải che trước khi chép. Bảo mật ở mức dòng và mức cột. Ghi nhật ký truy cập cho dữ liệu nhạy cảm và biến nó thành thứ rà được, chứ chỉ bật rồi quên.",
"Phân loại dữ liệu của pipeline, áp đúng yêu cầu bảo vệ cho từng mức, và dựng quy trình che dữ liệu cho môi trường thử.",
"Tầng *áp dụng*. Objective là áp một khung phân loại thành cấu hình cụ thể kiểm được. Kiểm bằng rà soát cộng phép thử truy cập; đạt khi mọi bảng có mức phân loại, dữ liệu thử đã che, và tài khoản thiếu quyền bị từ chối.",
"Phân loại mọi bảng trong mart. Với mức cao nhất, bật mã hoá, hạn chế quyền và bật nhật ký truy cập. Dựng quy trình che dữ liệu khi chép sang môi trường thử và chứng minh không còn dữ liệu định danh. Thử truy cập bằng tài khoản thiếu quyền và ghi lại kết quả cùng bản ghi nhật ký.",
"Chép thẳng dữ liệu sản xuất sang môi trường thử · nghĩ mạng riêng thì không cần mã hoá khi truyền · bật nhật ký truy cập mà không ai rà · phân loại mọi thứ ở mức cao nhất.",
"Mọi bảng có mức phân loại, dữ liệu môi trường thử đã che hết trường định danh, và truy cập trái phép bị từ chối có ghi nhật ký."),

(397,"Secrets management and rotation","TH","Lesson 396",
"Quy tắc không bao giờ đặt bí mật trong mã đã nêu từ lesson 89 và nhắc lại ở lesson 362 và 368; bài này dựng hệ hoàn chỉnh. Kho bí mật tập trung với ba năng lực cần có: lưu có mã hoá, cấp quyền theo danh tính, và ghi nhật ký mọi lần đọc. Bí mật động là bước tiến đáng kể: kho tự tạo thông tin xác thực có thời hạn ngắn khi ứng dụng cần, nên không có bí mật dài hạn nào tồn tại để mà lộ. Xoay bí mật theo lịch và quy trình xoay không gián đoạn dùng hai bí mật song song trong cửa sổ chuyển tiếp. Quét bí mật trong mã và trong lịch sử kho mã, và lý do phải quét cả lịch sử: xoá ở lần nộp sau không xoá được ở lần nộp trước, nên bí mật vẫn nằm đó. Quy trình khi lộ với thứ tự bắt buộc: xoay trước, điều tra phạm vi sau, vì mỗi phút chậm là thêm rủi ro. Ba chỗ bí mật hay rò rỉ ngoài kho mã: nhật ký, thông báo lỗi, và biến môi trường trong ảnh chụp lỗi.",
"Dựng hệ quản lý bí mật có xoay tự động, và thực hiện một lần xoay mà dịch vụ không gián đoạn.",
"Tầng *áp dụng*. Objective là một cơ chế vận hành kiểm được bằng phép xoay có đo gián đoạn. Kiểm bằng phép xoay thật; đạt khi không yêu cầu nào thất bại trong cửa sổ xoay và quét lịch sử kho mã sạch.",
"Chuyển mọi bí mật của pipeline vào kho tập trung. Cấu hình ứng dụng lấy bí mật lúc chạy bằng danh tính khối lượng công việc. Thực hiện một lần xoay không gián đoạn và đếm số yêu cầu thất bại. Quét lịch sử kho mã tìm bí mật. Viết quy trình bốn bước khi lộ, đặt xoay ở bước một.",
"Xoay bí mật bằng cách đổi rồi khởi động lại mọi thứ · chỉ quét mã hiện tại mà không quét lịch sử · điều tra trước khi xoay · ghi bí mật vào nhật ký lỗi.",
"Lần xoay không gây yêu cầu thất bại nào, quét lịch sử kho mã không còn bí mật, và quy trình khi lộ đặt xoay ở bước đầu."),

(398,"Privacy - PII, retention and the right to erasure","TH","Lesson 397",
"Dữ liệu cá nhân đặt ra ba nghĩa vụ mà thiết kế kỹ thuật phải đỡ được, và đỡ sau thì rất đắt. Một là biết dữ liệu cá nhân nằm ở đâu: cần danh mục và gắn nhãn ở mức cột, nối với phân loại ở lesson 396 và với siêu dữ liệu ở M26. Hai là giữ đúng thời hạn: chính sách lưu giữ phải thực thi bằng máy qua quy tắc vòng đời ở lesson 378 và qua công việc dọn theo lịch, chứ bằng lời hứa. Ba là xoá theo yêu cầu, và đây là nghĩa vụ khó nhất về kỹ thuật vì dữ liệu một người đã lan qua nhiều bảng, nhiều bản sao lưu và nhiều tệp bất biến trên hồ. Ba kỹ thuật làm nó khả thi: mã hoá theo từng chủ thể rồi xoá khoá, đánh dấu xoá rồi dọn theo lô, và tách dữ liệu định danh sang một bảng riêng để chỉ phải xoá ở một chỗ. Định dạng bảng mở ở M33 giúp phần này vì xoá vài dòng không đòi ghi lại cả phân vùng. Ghi lại đã xoá gì và khi nào, vì phải chứng minh được.",
"Định vị mọi dữ liệu cá nhân trong hệ, thực thi được chính sách lưu giữ bằng máy, và hoàn tất một yêu cầu xoá có bằng chứng.",
"Tầng *áp dụng*. Objective là ba nghĩa vụ chuyển thành cơ chế kỹ thuật kiểm được. Kiểm bằng một yêu cầu xoá thực hiện đầu cuối; đạt khi không còn dấu vết chủ thể ở mọi bảng đích và có bản ghi chứng minh.",
"Gắn nhãn cột chứa dữ liệu cá nhân trên toàn mart. Dựng quy tắc vòng đời thực thi chính sách lưu giữ. Nhận một yêu cầu xoá cho một chủ thể và thực hiện đầu cuối, gồm cả bảng loại 2 ở lesson 314 và cả hồ dữ liệu. Chứng minh không còn dấu vết bằng truy vấn. Ghi lại bản ghi chứng minh.",
"Xoá ở mart mà quên hồ dữ liệu và bản sao lưu · thực thi lưu giữ bằng quy trình thủ công · không gắn nhãn ở mức cột nên không biết tìm đâu · xoá mà không ghi lại bằng chứng.",
"Truy vấn kiểm chứng không còn dấu vết chủ thể ở mọi đích, chính sách lưu giữ chạy tự động, và có bản ghi chứng minh việc xoá."),

(399,"Cost engineering for a data platform","TH","Lesson 398",
"Chi phí là một yêu cầu phi chức năng ngang hàng với hiệu năng, và đội không đo nó thì nó tăng cho tới khi có người cắt ngân sách đột ngột. Bốn nguồn chi phí lớn của nền tảng dữ liệu, xếp theo mức hay bị lãng phí: tính toán để chạy không hoặc chạy quá lâu do chưa tối ưu ở M34, lưu trữ do giữ quá lâu và do tệp nhỏ ở lesson 335, truyền dữ liệu ra khỏi vùng ở lesson 378, và dịch vụ quản lý đặt kích thước dư. Chi phí trên mỗi đơn vị nghiệp vụ là chỉ số chính chứ tổng chi phí, vì nó phân biệt tăng do tăng trưởng với tăng do lãng phí; định nghĩa đơn vị nghiệp vụ phù hợp cho một nền tảng dữ liệu. Quy trình cắt chi phí có phương pháp: gắn nhãn và chia hoá đơn theo thành phần, xếp hạng theo chi phí, xử lý từ trên xuống, và đo lại. Ba khoản cắt được mà không ảnh hưởng dịch vụ và thường cắt được nhanh. Cảnh báo về tối ưu quá đà: cắt tới mức không còn biên an toàn thì sự cố kế tiếp đắt hơn phần đã tiết kiệm.",
"Chia hoá đơn theo thành phần, xếp hạng theo chi phí, và thực hiện được ít nhất hai khoản cắt có số đo mà không vi phạm mục tiêu mức dịch vụ.",
"Tầng *đánh giá*. Objective đòi tối ưu dưới ràng buộc không được hạ chất lượng dịch vụ. Kiểm bằng cặp số đo chi phí và mục tiêu mức dịch vụ; đạt khi chi phí giảm có số và mọi mục tiêu ở lesson 387 vẫn đạt.",
"Chia hoá đơn theo thành phần bằng nhãn ở lesson 384. Xếp hạng và chọn ba khoản đắt nhất. Thực hiện ít nhất hai khoản cắt. Đo lại chi phí và đo lại cả bốn chỉ báo mức dịch vụ để chứng minh không hạ chất lượng. Định nghĩa và tính chi phí trên mỗi đơn vị nghiệp vụ.",
"Cắt chi phí bằng cách giảm tài nguyên tới mức mất biên an toàn · theo dõi tổng chi phí mà không chia thành phần · tối ưu khoản nhỏ trước khoản lớn · cắt xong không đo lại chất lượng.",
"Chi phí giảm có số, cả bốn chỉ báo mức dịch vụ vẫn đạt sau khi cắt, và có chỉ số chi phí trên mỗi đơn vị nghiệp vụ."),

(400,"Gate 8 - operate the platform under induced failure","KT","Lesson 399",
"Cổng của chặng 7. Bài kiểm năng lực vận hành chứ năng lực xây: hệ đã có sẵn, việc của học viên là giữ nó chạy và xử lý đúng khi nó hỏng. Không có nội dung mới.",
"Qua buổi diễn tập sự cố: phát hiện trong ngưỡng, chẩn đoán đúng, khắc phục, thông báo đúng đối tượng, và viết phân tích sau sự cố đạt rà soát.",
"Tầng *đánh giá*. Cổng đo năng lực dưới áp lực thời gian, nên hình thức là diễn tập trực tiếp có tính giờ cộng sản phẩm viết.",
"Buổi diễn tập kéo dài 120 phút trên nền tảng đã dựng. Giảng viên gây ba sự cố ở ba mức nghiêm trọng khác nhau. Bài chấm năm phần: A (25đ) phát hiện qua cảnh báo trong ngưỡng, không phải do người dùng báo · B (25đ) chẩn đoán đúng nguyên nhân cả ba, dẫn bằng số đo · C (20đ) khắc phục và chạy lại lịch sử, đối soát khớp · D (20đ) thông báo đúng đối tượng đúng thời điểm, có dòng thời gian · E (10đ) phân tích sau sự cố truy tới tầng hệ thống, hành động có chủ và hạn.",
"Chẩn đoán trước khi chặn lan rộng · phát hiện sự cố nhờ người dùng báo · sửa xong mà quên chạy lại lịch sử · bỏ phần thông báo vì bận sửa.",
"Đạt ≥ 70/100, phần A và D đều ≥ 60%. Sự cố nào người dùng báo trước cảnh báo thì phần A của sự cố đó bằng không."),
]
