# -*- coding: utf-8 -*-
"""DE M11 — PostgreSQL in depth (mức A)."""

M11 = ("PostgreSQL in Depth", 122, 135, """| | |
|---|---|
| **Objective cấp module** | Vận hành một cụm PostgreSQL ở mức sản xuất: chẩn đoán kế hoạch lệch, xử lý phình bảng, chỉnh thu hồi tự động, phục hồi tới một thời điểm, và di trú lược đồ không ngừng phục vụ |
| **Tiền đề** | M10 |
| **Exit criterion** | Sáu diễn tập đều đạt: kế hoạch lệch ước lượng, phình bảng, giao dịch dài, sao lưu và phục hồi tới thời điểm, độ trễ bản sao, và di trú không ngừng phục vụ |
| **Kỹ năng SFIA** | `DBAD` mức 4 · `SYSP` mức 4 |
| **Chế độ hỏng** | Chỉnh tham số theo bài hướng dẫn trên mạng mà không đo, nên cấu hình trông hợp lý nhưng không khớp tải thật |""",
"PostgreSQL là hệ duy nhất trong bảy hệ được học ở mức `A`, tức xây và vận hành được. M10 đã dạy cơ chế chung; module này đi vào cái PostgreSQL làm khác và cái chỉ lộ ra khi vận hành thật. Mọi tham số chỉnh trong module phải kèm số đo trước và sau trên tải của chính người học.")

L11 = [
(122,"Installing, configuring and the parameters that matter","TH","Module 11: M10",
"Cài đặt và bố trí thư mục: dữ liệu, nhật ký ghi trước, và nhật ký hệ thống nên nằm trên phân vùng riêng, lý do ở lesson 118. Tệp cấu hình chính và tệp xác thực kết nối, cùng thứ tự áp dụng. Phân loại tham số theo cách nạp lại: một số áp dụng ngay, một số cần nạp lại cấu hình, một số cần khởi động lại, và biết loại nào là điều kiện để chỉnh an toàn trên hệ đang chạy. Mười tham số ảnh hưởng nhiều nhất và cái mỗi tham số đánh đổi: bộ đệm chia sẻ, bộ nhớ làm việc, bộ nhớ bảo trì, kích thước nhật ký tối đa, khoảng điểm kiểm tra, chi phí trang ngẫu nhiên, số kết nối tối đa, số công nhân song song, tham số thu hồi tự động, và mức ghi nhật ký. Quy tắc của module: không chép giá trị từ bài hướng dẫn, mỗi tham số phải có số đo trước và sau trên tải của mình. Khung nhìn cấu hình để biết giá trị hiện hành đến từ tệp nào.",
"Chỉnh năm tham số cho một tải cho trước và chứng minh cải thiện bằng số đo trước và sau, nêu rõ tham số nào cần khởi động lại.",
"Tầng *đánh giá*. Objective đòi chọn giá trị có đánh đổi và biện minh bằng số, không có cấu hình đúng chung. Đạt khi năm tham số đều có số đo trước sau trên cùng tải, khi phân loại đúng tham số nào cần khởi động lại, và khi ít nhất một tham số được giữ nguyên vì số đo cho thấy đổi không có lợi.",
"Dựng cụm PostgreSQL với ba phân vùng riêng. Chạy tải chuẩn và ghi số nền. Chỉnh năm tham số từng cái một, đo lại sau mỗi lần. Lập bảng. Thử chỉnh một tham số cần khởi động lại bằng lệnh nạp lại và quan sát nó không có hiệu lực. Đọc khung nhìn cấu hình xem giá trị đến từ đâu.",
"Chép cấu hình từ bài hướng dẫn · đổi nhiều tham số cùng lúc rồi không biết cái nào có tác dụng · đặt bộ đệm chia sẻ bằng phần lớn RAM, nối lại lesson 110.",
"Năm tham số đều có số đo trước sau, phân loại đúng loại nạp lại, và ít nhất một tham số được giữ nguyên có lý do."),

(123,"Heap, page, tuple and the visibility map","LT","Lesson 122",
"Bảng lưu dưới dạng đống không sắp thứ tự, nên thứ tự dòng trả về không có bảo đảm nếu không có mệnh đề sắp xếp. Cấu trúc trang tám ki lô byte theo mô hình ở lesson 109. Định danh dòng vật lý gồm số trang và số vị trí, và vì sao nó đổi khi dòng được cập nhật. Cập nhật tại chỗ chỉ xảy ra khi trang còn chỗ và cột được cập nhật không có chỉ mục, cơ chế tối ưu giảm được việc cập nhật chỉ mục; khi không thoả thì dòng mới sang trang khác và mọi chỉ mục phải cập nhật. Bản đồ khả kiến đánh dấu trang mà mọi dòng đều thấy được bởi mọi giao dịch, và nó cho phép quét chỉ mục thuần bỏ qua bước lấy dòng từ đống, nên nó là điều kiện để chỉ mục phủ có tác dụng. Bản đồ không gian trống. Cột quá lớn lưu ngoài dòng có nén, và chi phí giải nén khi đọc. Hệ số lấp đầy và khi nào nên hạ nó xuống.",
"Giải thích vì sao quét chỉ mục thuần có lúc nhanh có lúc không, bằng trạng thái bản đồ khả kiến của bảng.",
"Tầng *hiểu*. Bài lý thuyết nhưng objective nối cơ chế với một hiện tượng đo được. Đạt khi giải thích đúng chuỗi nhân quả và khi thực nghiệm cho thấy cùng một truy vấn đổi từ quét chỉ mục thuần sang quét có lấy dòng sau khi cập nhật dữ liệu.",
"Tạo bảng 5 triệu dòng có chỉ mục phủ. Chạy thu hồi để cập nhật bản đồ khả kiến. Chạy truy vấn và xác nhận quét chỉ mục thuần trong kế hoạch. Cập nhật 20% số dòng. Chạy lại truy vấn, quan sát số lần lấy dòng từ đống tăng. Chạy thu hồi rồi đo lại.",
"Giả định thứ tự dòng ổn định khi không có mệnh đề sắp xếp · tin chỉ mục phủ luôn cho quét thuần · bỏ qua ảnh hưởng của cập nhật lên bản đồ khả kiến.",
"Thực nghiệm cho thấy truy vấn đổi chế độ quét sau khi cập nhật, và chuỗi nhân quả được giải thích đúng."),

(124,"MVCC in PostgreSQL - xmin, xmax and tuple visibility","TH","Lesson 123",
"PostgreSQL cài điều khiển đồng thời nhiều phiên bản bằng cách giữ phiên bản cũ ngay trong bảng chứ không đưa sang vùng riêng như một số hệ khác, và lựa chọn thiết kế này giải thích gần như mọi đặc thù vận hành của nó. Hai cột hệ thống ghi giao dịch tạo và giao dịch xoá của mỗi phiên bản dòng. Quy tắc khả kiến: một giao dịch thấy phiên bản nào dựa trên ảnh chụp của nó và trạng thái hai giao dịch đó. Đọc trực tiếp hai cột hệ thống để quan sát cơ chế thay vì chỉ đọc mô tả. Hệ quả thứ nhất: cập nhật là chèn phiên bản mới cộng đánh dấu phiên bản cũ, nên bảng lớn lên dù số dòng logic không đổi, dẫn thẳng tới lesson 125. Hệ quả thứ hai: đếm số dòng phải quét vì không có bộ đếm sẵn, khác với một số hệ khác. Hệ quả thứ ba: giao dịch chỉ đọc cũng giữ ảnh chụp và chặn thu hồi, nối lại lesson 116.",
"Quan sát trực tiếp cơ chế nhiều phiên bản bằng hai cột hệ thống, và dự đoán phiên bản nào một giao dịch nhìn thấy trước khi chạy.",
"Tầng *phân tích*. Objective đòi suy luận về khả kiến chứ không chỉ mô tả cơ chế. Kiểm bằng sáu tình huống hai phiên; đạt khi dự đoán đúng ít nhất năm và mỗi lần dẫn được giá trị hai cột hệ thống làm bằng chứng.",
"Mở hai phiên. Chèn, cập nhật, xoá một dòng ở phiên một và đọc hai cột hệ thống sau mỗi thao tác. Ở phiên hai, dự đoán thấy phiên bản nào trước khi truy vấn, rồi truy vấn đối chiếu. Lặp cho sáu tình huống ở hai mức cô lập. Đếm số phiên bản vật lý của một dòng sau 10 lần cập nhật.",
"Tin rằng cập nhật sửa dòng tại chỗ · dùng đếm số dòng làm phép kiểm nhanh trên bảng lớn · cho rằng giao dịch chỉ đọc không ảnh hưởng gì.",
"Dự đoán đúng ít nhất năm trên sáu tình huống, mỗi lần dẫn được giá trị hai cột hệ thống."),

(125,"Bloat, VACUUM and autovacuum tuning","TH","Lesson 124",
"Phình là dung lượng chiếm bởi phiên bản dòng chết chưa được thu hồi, và nó là hệ quả trực tiếp của thiết kế ở lesson 124 chứ không phải lỗi. Đo phình: so kích thước bảng với kích thước ước lượng từ số dòng và lược đồ, nối lại lesson 109. Thu hồi thường đánh dấu không gian dùng lại được nhưng không trả về hệ điều hành; thu hồi toàn phần trả về được nhưng giữ khoá độc quyền nên không dùng được trên bảng đang phục vụ. Thu hồi tự động và ba tham số quyết định nó chạy khi nào: ngưỡng theo số dòng, tỉ lệ theo kích thước bảng, và số tiến trình song song. Vì sao cấu hình mặc định quá thưa cho bảng lớn: ngưỡng theo tỉ lệ nghĩa là bảng một tỉ dòng phải có 200 triệu dòng chết mới chạy. Chỉnh theo từng bảng thay vì toàn cục. Giới hạn chi phí thu hồi và cơ chế nó tự dừng để không ảnh hưởng tải, cùng hệ quả là nó không đuổi kịp trên bảng ghi nhiều.",
"Đo phình của một bảng, chỉnh thu hồi tự động cho riêng bảng đó, và chứng minh phình được giữ dưới ngưỡng dưới tải ghi liên tục.",
"Tầng *đánh giá*. Objective đòi chọn tham số cho một bảng cụ thể và chứng minh bằng theo dõi theo thời gian. Đạt khi tỉ lệ phình được giữ dưới 20% qua 60 phút tải ghi liên tục, và khi người học nêu được vì sao cấu hình toàn cục mặc định không đủ cho bảng này bằng phép tính ngưỡng.",
"Tạo bảng 20 triệu dòng, chạy tải cập nhật liên tục. Đo phình mỗi 5 phút trong 60 phút với cấu hình mặc định. Tính ngưỡng kích hoạt mặc định cho bảng này. Chỉnh tham số riêng cho bảng, chạy lại 60 phút, vẽ hai đường cong. Thử thu hồi toàn phần và đo thời gian khoá.",
"Chạy thu hồi toàn phần trên bảng đang phục vụ · chỉnh ngưỡng toàn cục để chữa một bảng · tin rằng thu hồi trả dung lượng về hệ điều hành.",
"Tỉ lệ phình dưới 20% qua 60 phút tải ghi, và phép tính ngưỡng cho thấy vì sao mặc định không đủ."),

(126,"Transaction ID wraparound and why it can stop the database","LT","Lesson 125",
"Định danh giao dịch là số nguyên 32 bit nên nó quay vòng, và đây là nơi lesson 6 về tràn số gặp lại ở quy mô hệ thống. Cơ chế: khả kiến so sánh định danh theo thứ tự vòng, nên một giao dịch quá cũ sẽ trông như ở tương lai và dữ liệu cũ biến mất. Để ngăn điều đó, PostgreSQL đóng băng phiên bản dòng đủ cũ, và việc đóng băng do thu hồi thực hiện. Hệ quả: thu hồi không phải tuỳ chọn hiệu năng mà là yêu cầu để cơ sở dữ liệu sống. Ba mức cảnh báo khi tuổi giao dịch tăng dần và hành vi ở mức cuối: hệ thống từ chối mọi lệnh ghi để tự bảo vệ, một sự cố dừng hoàn toàn. Ba nguyên nhân thường gặp đẩy tuổi lên: giao dịch mở rất lâu, khe bản sao bỏ quên, và bảng bị loại khỏi thu hồi tự động. Theo dõi tuổi giao dịch như một chỉ số vận hành bắt buộc. Phiên bản mới hơn có định danh 64 bit ở một số nhánh, nhưng phải kiểm phiên bản đang chạy chứ không giả định.",
"Giải thích chuỗi nhân quả từ một giao dịch mở lâu tới việc cơ sở dữ liệu từ chối ghi, và nêu ba chỉ số cần theo dõi để chặn trước.",
"Tầng *hiểu*. Objective là giải thích cơ chế và rút ra chỉ số theo dõi; gây ra sự cố thật tốn hàng giờ nên không đặt trong lab. Đạt khi chuỗi nhân quả nêu đủ bốn mắt xích, và khi ba chỉ số nêu ra đều truy vấn được trên cụm đang chạy với ngưỡng cảnh báo cụ thể.",
"Đọc tuổi giao dịch của mọi cơ sở dữ liệu và bảng trên cụm. Mở một giao dịch và để 30 phút, quan sát tuổi không giảm được cho các bảng. Tạo một khe bản sao rồi bỏ quên, quan sát tác động. Viết ba truy vấn theo dõi kèm ngưỡng cảnh báo. Kiểm phiên bản đang chạy dùng định danh mấy bit.",
"Giả định phiên bản đang chạy đã dùng định danh 64 bit · tắt thu hồi tự động cho bảng lớn để tiết kiệm vào ra · tạo khe bản sao cho công cụ thử nghiệm rồi quên xoá.",
"Chuỗi nhân quả nêu đủ bốn mắt xích, và ba truy vấn theo dõi chạy được kèm ngưỡng cảnh báo cụ thể."),

(127,"Index types - B-tree, GIN, GiST, BRIN and when each wins","TH","Lesson 126",
"Bốn họ chỉ mục và bài toán mỗi họ giải. Cây B cho so sánh và khoảng, mặc định và phủ phần lớn nhu cầu, nối lại lesson 111. Chỉ mục đảo tổng quát cho giá trị chứa nhiều phần tử: mảng, tài liệu JSON, và tìm kiếm toàn văn; chi phí ghi cao hơn nhiều và có cơ chế hoãn cập nhật để giảm. Chỉ mục tìm kiếm tổng quát cho dữ liệu không xếp thứ tự tuyến tính được như hình học và khoảng thời gian. Chỉ mục phạm vi khối lưu giá trị nhỏ nhất và lớn nhất theo nhóm trang, nên nó rất nhỏ nhưng chỉ hiệu quả khi dữ liệu vật lý tương quan với cột chỉ mục, điều kiện thường đúng với bảng chỉ chèn theo thời gian. Chỉ mục một phần cho truy vấn luôn kèm một điều kiện cố định. Chỉ mục trên biểu thức khi truy vấn bọc hàm quanh cột, nối lại lesson 96. Tạo chỉ mục không chặn ghi và điều kiện nó thất bại giữa chừng để lại chỉ mục không hợp lệ.",
"Chọn họ chỉ mục cho năm mẫu truy vấn, và chứng minh lựa chọn bằng kích thước chỉ mục, thời gian truy vấn và chi phí ghi.",
"Tầng *đánh giá*. Objective đòi chọn có đánh đổi ba chiều, không có đáp án chung. Đạt khi năm lựa chọn đều có ba số đo, và khi ít nhất một lựa chọn đi ngược trực giác được giải thích bằng số, ví dụ chỉ mục phạm vi khối thắng cây B trên bảng theo thời gian.",
"Tạo bảng 50 triệu dòng có cột thời gian tăng dần, cột JSON, và cột văn bản. Tạo bốn họ chỉ mục cho năm mẫu truy vấn. Đo kích thước chỉ mục, thời gian truy vấn, và thời gian chèn 1 triệu dòng. So chỉ mục phạm vi khối với cây B trên cột thời gian. Tạo chỉ mục không chặn ghi trong lúc có tải.",
"Dùng cây B cho mọi thứ · tạo chỉ mục phạm vi khối trên cột không tương quan với thứ tự vật lý · tạo chỉ mục nặng trên bảng ghi nhiều mà không đo chi phí ghi.",
"Năm lựa chọn đều có ba số đo, và ít nhất một lựa chọn đi ngược trực giác được giải thích bằng số."),

(128,"The planner - cost parameters, statistics targets and extended statistics","TH","Lesson 127",
"Bộ lập kế hoạch tính chi phí bằng một mô hình có tham số, và bốn tham số chi phí quyết định phần lớn lựa chọn: chi phí trang tuần tự, chi phí trang ngẫu nhiên, chi phí xử lý một dòng, và chi phí xử lý một toán tử. Tỉ lệ giữa chi phí trang ngẫu nhiên và tuần tự mặc định phản ánh đĩa từ, nên trên ổ thể rắn nó làm bộ lập kế hoạch tránh chỉ mục quá mức, nối lại lesson 15. Đây là một trong ít tham số mà đổi mặc định thường đúng, nhưng vẫn phải đo. Mục tiêu thống kê điều khiển độ chi tiết của biểu đồ phân bố, và tăng nó cho cột lệch giúp ước lượng bản số chính xác hơn, nối lại lesson 112. Thống kê mở rộng khai báo tương quan giữa nhiều cột, giải đúng nguyên nhân thứ ba trong bốn nguyên nhân ước lượng sai. Vô hiệu hoá một loại toán tử để kiểm giả thuyết trong lúc chẩn đoán, và vì sao không được để lại trong sản xuất.",
"Sửa một kế hoạch tồi bằng cách chỉnh đúng nguyên nhân trong ba nguyên nhân, và chứng minh ước lượng bản số cải thiện chứ không chỉ thời gian.",
"Tầng *phân tích*. Objective đòi sửa nguyên nhân chứ không sửa triệu chứng, và bẫy chính là ép kế hoạch bằng cách vô hiệu hoá toán tử. Đạt khi ba ca đều được sửa bằng đúng cơ chế, và khi số dòng ước lượng tiến gần số dòng thật, đọc từ kế hoạch trước và sau.",
"Dựng ba ca kế hoạch tồi: tỉ lệ chi phí trang không hợp ổ thể rắn, cột lệch có biểu đồ quá thô, và hai cột tương quan. Sửa từng ca bằng chỉnh tham số chi phí, tăng mục tiêu thống kê, và khai báo thống kê mở rộng. So ước lượng với số thật trước sau. Thử vô hiệu hoá toán tử để kiểm giả thuyết rồi bật lại.",
"Để vô hiệu hoá toán tử trong cấu hình sản xuất · chỉnh tham số chi phí mà không đo trên ổ thật · tăng mục tiêu thống kê toàn cục thay vì cho cột cần.",
"Ba ca sửa đúng cơ chế, và số dòng ước lượng tiến gần số thật đọc được từ kế hoạch trước sau."),

(129,"EXPLAIN in PostgreSQL - buffers, timing and JIT","TH","Lesson 128",
"Các tuỳ chọn của lệnh giải thích kế hoạch và cái mỗi tuỳ chọn thêm vào. Chế độ phân tích thật chạy truy vấn nên phải bọc trong giao dịch có hoàn tác khi truy vấn ghi, nếu không sẽ ghi thật. Tuỳ chọn bộ đệm cho biết số trang đọc từ bộ đệm chia sẻ và số trang đọc từ đĩa, và đây là số đo hữu ích nhất mà phần lớn người dùng không bật. Tỉ lệ giữa hai con số đó là tỉ lệ trúng của chính truy vấn, cụ thể hơn tỉ lệ trúng toàn cục ở lesson 110. Đọc số lần lặp và nhân với thời gian mỗi lần, nối lại lesson 113. Dấu hiệu tràn ra đĩa hiện trong kế hoạch kèm dung lượng, cho biết cần tăng bộ nhớ làm việc bao nhiêu. Công nhân song song và vì sao thời gian tổng không bằng tổng thời gian các nhánh. Biên dịch tức thời bật ở ngưỡng chi phí và có thể làm truy vấn ngắn chậm hơn vì chi phí biên dịch, một hiện tượng gây bối rối khi mới gặp.",
"Đọc một kế hoạch có đủ bộ đệm và thời gian, và rút ra ba kết luận hành động được: cần chỉ mục nào, cần bộ nhớ làm việc bao nhiêu, và tỉ lệ trúng của truy vấn.",
"Tầng *phân tích*. Objective đòi chuyển số đo thành hành động cụ thể có định lượng. Đạt khi ba kết luận đều kèm con số, và khi dự đoán cải thiện sau khi áp dụng sai không quá hệ số hai so với số đo thật.",
"Chạy năm truy vấn với đầy đủ tuỳ chọn. Với mỗi cái, lập bảng: trang từ bộ đệm, trang từ đĩa, tỉ lệ trúng, có tràn đĩa không và bao nhiêu, số lần lặp nút tốn nhất. Rút ba kết luận kèm số, áp dụng, đo lại. Chạy một truy vấn ngắn ở ngưỡng bật biên dịch tức thời và quan sát.",
"Chạy chế độ phân tích thật trên truy vấn ghi ngoài giao dịch · đọc kế hoạch mà không bật tuỳ chọn bộ đệm · cộng thời gian các nhánh song song.",
"Ba kết luận đều kèm con số, và dự đoán cải thiện sai không quá hệ số hai so với số đo thật."),

(130,"Partitioning - declarative partitions, pruning and maintenance","TH","Lesson 129",
"Phân vùng khai báo và ba kiểu: theo khoảng, theo danh sách, theo băm, nối lại lesson 115. Cắt tỉa lúc lập kế hoạch so với cắt tỉa lúc chạy, cái sau áp dụng khi điều kiện chỉ biết lúc chạy, và đọc được trong kế hoạch. Khoá phân vùng phải nằm trong khoá chính, ràng buộc kéo theo hệ quả thiết kế: khoá chính thành phức hợp. Gắn và tháo phân vùng là thao tác siêu dữ liệu nên gần như tức thì, đây là cách xoá dữ liệu cũ đúng cách thay vì xoá dòng. Gắn một bảng có sẵn làm phân vùng đòi kiểm ràng buộc, và cách tránh quét toàn bảng bằng khai báo ràng buộc trước. Chỉ mục trên bảng phân vùng tạo ra chỉ mục con trên từng phân vùng. Phân vùng mặc định và rủi ro của nó: một dòng sai khoá rơi vào đó và chặn việc gắn phân vùng mới. Số phân vùng hợp lý và chi phí lập kế hoạch khi quá nhiều. Tự động hoá tạo phân vùng theo lịch.",
"Chuyển một bảng lớn sang phân vùng theo khoảng, và chứng minh cắt tỉa hoạt động cùng việc tháo phân vùng cũ nhanh hơn xoá dòng nhiều bậc.",
"Tầng *áp dụng*. Objective có hai tiêu chí đo được. Đạt khi số phân vùng quét đọc từ kế hoạch đúng như mong đợi cho ba truy vấn, và khi thời gian tháo một phân vùng nhỏ hơn thời gian xoá số dòng tương đương ít nhất một bậc độ lớn.",
"Chuyển bảng 100 triệu dòng sang phân vùng theo tháng. Chạy ba truy vấn, đọc số phân vùng quét. So thời gian tháo một phân vùng với xoá số dòng tương đương. Chèn một dòng sai khoá vào phân vùng mặc định rồi thử gắn phân vùng mới, quan sát lỗi. Viết script tạo phân vùng theo lịch.",
"Quên đưa khoá phân vùng vào khoá chính · để phân vùng mặc định nhận dòng sai rồi không gắn được phân vùng mới · tạo phân vùng theo ngày cho dữ liệu giữ 10 năm.",
"Số phân vùng quét đúng mong đợi cho ba truy vấn, và tháo phân vùng nhanh hơn xoá dòng ít nhất một bậc."),

(131,"WAL, checkpoints and tuning for write-heavy loads","TH","Lesson 130",
"Nhật ký ghi trước của PostgreSQL theo mô hình ở lesson 118, và bài này chỉnh nó cho tải ghi nặng. Bốn tham số và đánh đổi: kích thước nhật ký tối đa quyết định khoảng cách giữa hai điểm kiểm tra, mục tiêu hoàn thành điểm kiểm tra trải việc ghi ra thời gian để tránh gai vào ra, khoảng thời gian điểm kiểm tra, và bộ đệm nhật ký. Ghi toàn trang sau mỗi điểm kiểm tra: lần sửa đầu tiên của một trang sau điểm kiểm tra phải ghi cả trang vào nhật ký để chống rách trang khi mất điện, nên điểm kiểm tra dày làm dung lượng nhật ký tăng vọt, một quan hệ phản trực giác. Gai vào ra lúc điểm kiểm tra và cách nhận ra trong biểu đồ giám sát. Nhật ký chưa lưu trữ chất đống khi lệnh lưu trữ hỏng, làm đầy đĩa và dừng cơ sở dữ liệu, một sự cố vận hành kinh điển. Mức nhật ký tối thiểu cho tải nạp một lần và rủi ro kèm theo.",
"Chỉnh bốn tham số nhật ký cho một tải ghi nặng và chứng minh gai vào ra lúc điểm kiểm tra giảm, không đổi bằng việc tăng thời gian phục hồi quá mục tiêu.",
"Tầng *đánh giá*. Objective đòi cân hai ràng buộc ngược nhau. Đạt khi độ lệch chuẩn của vào ra theo thời gian giảm ít nhất 30% so với cấu hình gốc, và khi thời gian phục hồi đo được vẫn dưới mục tiêu đã đặt ở lesson 118.",
"Chạy tải ghi nặng 30 phút, ghi biểu đồ vào ra theo giây với cấu hình mặc định, xác định gai điểm kiểm tra. Chỉnh bốn tham số, chạy lại, so hai biểu đồ và tính độ lệch chuẩn. Ngắt điện và đo thời gian phục hồi. Thử đặt điểm kiểm tra rất dày và đo dung lượng nhật ký sinh ra.",
"Đặt điểm kiểm tra dày để giảm thời gian phục hồi rồi dung lượng nhật ký tăng vọt · để lệnh lưu trữ hỏng im lặng · đặt mức nhật ký tối thiểu trên cụm có bản sao.",
"Độ lệch chuẩn vào ra giảm ít nhất 30%, và thời gian phục hồi đo được vẫn dưới mục tiêu."),

(132,"Physical replication, streaming and failover","TH","Lesson 131",
"Bản sao vật lý truyền nhật ký ghi trước theo mô hình ở lesson 120. Bản sao nóng cho phép đọc trên bản sao, và xung đột phục hồi: một truy vấn dài trên bản sao chặn việc áp nhật ký, nên hệ thống phải chọn huỷ truy vấn hoặc để bản sao tụt lại, và hai tham số điều khiển lựa chọn đó. Khe bản sao giữ nhật ký cho tới khi bản sao nhận, tránh mất nhật ký nhưng gây đầy đĩa khi bản sao chết, nối lại lesson 126. Phản hồi từ bản sao về bản chính để hoãn thu hồi, giải xung đột phục hồi nhưng gây phình trên bản chính, một đánh đổi phải chọn có ý thức. Xác nhận đồng bộ và các mức của nó. Chuyển đổi dự phòng: nâng bản sao thành bản chính, và vấn đề bản chính cũ sống lại gây hai bản cùng nhận ghi. Dựng lại bản sao cũ sau chuyển đổi bằng công cụ đồng bộ thay vì sao chép toàn bộ. Đo độ trễ theo byte và theo thời gian, hai con số nói hai chuyện khác nhau.",
"Dựng bản sao trực tuyến, gây xung đột phục hồi có chủ đích, và thực hiện chuyển đổi dự phòng rồi dựng lại bản sao cũ.",
"Tầng *áp dụng*. Objective gồm ba thao tác vận hành có tiêu chí kiểm được. Đạt khi tái hiện được xung đột phục hồi và giải bằng đúng tham số, khi chuyển đổi dự phòng xong ứng dụng ghi được vào bản chính mới, và khi bản sao cũ được dựng lại mà không sao chép toàn bộ dữ liệu.",
"Dựng bản chính và bản sao nóng. Chạy truy vấn dài trên bản sao trong lúc bản chính cập nhật nhiều, quan sát truy vấn bị huỷ. Chỉnh tham số theo hai hướng và so hậu quả. Nâng bản sao thành bản chính. Dựng lại bản chính cũ thành bản sao bằng công cụ đồng bộ, đo lượng dữ liệu truyền.",
"Bật phản hồi từ bản sao mà không theo dõi phình trên bản chính · để khe bản sao cho bản sao đã chết · dựng lại bản sao bằng cách sao chép toàn bộ thư mục dữ liệu.",
"Tái hiện và giải được xung đột phục hồi, chuyển đổi dự phòng thành công, và dựng lại bản sao cũ không sao chép toàn bộ."),

(133,"Logical replication and publication-subscription","TH","Lesson 132",
"Bản sao logic giải mã nhật ký ghi trước thành thay đổi mức dòng rồi phát đi, khác bản sao vật lý ở chỗ nó chọn được bảng, chuyển được giữa phiên bản chính, và bên nhận ghi được. Ấn phẩm và thuê bao. Điều kiện bảng tham gia: phải có định danh bản ghi, thường là khoá chính, nếu không thì cập nhật và xoá không truyền được. Ba hành vi khi thiếu khoá chính và cách khai báo định danh thay thế. Giải mã logic là nền của bắt thay đổi dữ liệu ở chặng 6, nên module này là chỗ học cơ chế trước khi gặp công cụ. Ảnh chụp ban đầu khi thuê bao bắt đầu và chi phí của nó trên bảng lớn. Xung đột trên bên nhận khi có ghi cục bộ, và cơ chế thuê bao dừng lại chờ can thiệp. Độ trễ và khe giải mã, cùng rủi ro đầy đĩa giống lesson 132. Thay đổi lược đồ không tự truyền, nên phải phối hợp thủ công, một hạn chế quan trọng.",
"Dựng bản sao logic cho một tập bảng, và chỉ ra ba hạn chế khiến nó không thay thế được bản sao vật lý cho mục đích dự phòng.",
"Tầng *phân tích*. Objective gồm một cài đặt và một phán đoán về ranh giới áp dụng. Đạt khi bản sao logic chạy và dữ liệu khớp, và khi ba hạn chế nêu ra đều được chứng minh bằng một thực nghiệm chứ không bằng trích dẫn tài liệu.",
"Dựng ấn phẩm cho ba bảng và thuê bao trên cụm khác. Đối soát dữ liệu. Tạo một bảng không có khoá chính, thử cập nhật và quan sát. Đổi lược đồ ở bên phát và quan sát bên nhận. Ghi cục bộ gây xung đột và quan sát thuê bao dừng. Đo thời gian ảnh chụp ban đầu trên bảng 20 triệu dòng.",
"Dùng bản sao logic làm dự phòng toàn cụm · thêm bảng không có khoá chính vào ấn phẩm · đổi lược đồ một bên rồi tưởng bên kia tự theo.",
"Bản sao logic chạy và dữ liệu khớp, và ba hạn chế đều có thực nghiệm chứng minh."),

(134,"Connection management, pooling and why PostgreSQL needs it","TH","Lesson 133",
"PostgreSQL tạo một tiến trình hệ điều hành cho mỗi kết nối, khác với mô hình luồng của một số hệ khác, và lựa chọn thiết kế này quyết định mọi thứ về quản lý kết nối. Chi phí một kết nối: bộ nhớ riêng, thời gian tạo tiến trình, và chi phí chuyển ngữ cảnh khi số tiến trình lớn, nối lại lesson 12. Hệ quả: số kết nối tối đa đặt cao không làm hệ thống chịu tải tốt hơn mà làm nó chậm đi, và ngưỡng hợp lý thường thấp hơn nhiều so với trực giác. Nhóm kết nối bên ngoài và ba chế độ gộp: theo phiên, theo giao dịch, theo câu lệnh, cùng tính năng nào mất đi ở từng chế độ. Chế độ theo giao dịch là mặc định hợp lý nhưng làm truy vấn chuẩn bị sẵn và bảng tạm không dùng được như thường. Kết nối rỗi trong giao dịch là trạng thái nguy hiểm nhất: nó giữ khoá và chặn thu hồi, nối lại lesson 116 và 125. Thời gian chờ để tự đóng kết nối rỗi trong giao dịch.",
"Tìm số kết nối cho thông lượng cao nhất bằng thực nghiệm, và chứng minh nhóm kết nối bên ngoài giữ được thông lượng khi số ứng dụng khách vượt xa số đó.",
"Tầng *đánh giá*. Objective đòi tìm một điểm cực đại và chứng minh giá trị của một thành phần thêm vào. Đạt khi có đường cong thông lượng theo số kết nối ở ít nhất sáu điểm cho thấy cực đại rồi giảm, và khi với 1.000 ứng dụng khách thì có nhóm kết nối giữ được ít nhất 80% thông lượng đỉnh còn không có thì sụp.",
"Chạy tải ở 10, 25, 50, 100, 200, 500 kết nối trực tiếp, đo thông lượng và độ trễ phân vị 95. Vẽ đường cong, xác định cực đại. Dựng nhóm kết nối chế độ theo giao dịch, chạy 1.000 ứng dụng khách qua nó, so với 1.000 kết nối trực tiếp. Thử truy vấn chuẩn bị sẵn qua nhóm và quan sát.",
"Đặt số kết nối tối đa rất cao cho chắc · dùng chế độ theo giao dịch mà vẫn dựa vào bảng tạm · không đặt thời gian chờ cho kết nối rỗi trong giao dịch.",
"Đường cong sáu điểm cho thấy cực đại rồi giảm, và nhóm kết nối giữ ít nhất 80% thông lượng đỉnh ở 1.000 ứng dụng khách."),

(135,"PostgreSQL operations project - diagnose, tune, recover","DA","Lesson 134",
"Không có nội dung mới. Dự án gộp M11, gồm đúng sáu diễn tập trong tiêu chí ra module: một kế hoạch lệch ước lượng phải truy về nguyên nhân và sửa; một bảng phình phải đo và chỉnh thu hồi tự động cho riêng nó; một giao dịch dài phải định vị và chặn bằng thời gian chờ; một lần phục hồi tới thời điểm phải đo được điểm phục hồi và thời lượng phục hồi thật; độ trễ bản sao phải đo dưới ba mức tải và giải được một xung đột phục hồi; và một di trú lược đồ phá vỡ phải chạy không ngừng phục vụ theo mẫu bốn bước ở lesson 121. Nộp kèm sổ tay xử lý cho cả sáu tình huống theo khuôn ở lesson 90, mỗi bước là lệnh chạy được.",
"Hoàn thành sáu diễn tập vận hành trên một cụm PostgreSQL có tải, mỗi diễn tập nộp số đo trước và sau cùng một mục sổ tay xử lý dùng lại được.",
"Tầng *sáng tạo*. Objective là dựng một bộ quy trình vận hành dưới ràng buộc thật, không phải chạy sáu bài tập rời. Chấm theo sáu mục 15đ mỗi mục cộng 10đ cho tính nhất quán của sổ tay. Đạt khi ≥ 70/100 và không mục nào dưới 50%, vì một diễn tập bỏ trống nghĩa là sự cố đó chưa từng được luyện.",
"Cụm PostgreSQL có tải đọc ghi liên tục và một bản sao. Sáu diễn tập theo thứ tự tuỳ chọn, mỗi diễn tập tối đa 90 phút. Sau khi xong, đưa sổ tay cho một học viên khác và để họ thực hiện lại hai diễn tập bất kỳ theo tài liệu.",
"Chỉnh tham số theo bài hướng dẫn thay vì theo số đo của mình · bỏ diễn tập phục hồi vì tốn thời gian · viết sổ tay bằng mô tả thay vì lệnh chạy được.",
"Đạt ≥ 70/100, không mục nào dưới 50%, và học viên khác thực hiện lại được hai diễn tập theo sổ tay."),
]
