# -*- coding: utf-8 -*-
"""ADE Phase 10: M22 system design + M23 AI engineering (bounded) + M24 trajectory."""

M22 = ("System Design Progression", 405, 420, """| | |
|---|---|
| **Objective cấp module** | Chạy một quy trình thiết kế mười bước cho năm loại hệ, và bảo vệ được quyết định rồi thay đổi nó khi một ràng buộc đổi |
| **Tiền đề** | M8 · M11 · M14 · M15 · M19 · M20 · M21 |
| **Exit criterion** | Người rà soát truy được mọi thành phần về một yêu cầu hoặc một bảo đảm; bảng năng lực có giả định và độ nhạy; bảng chế độ hỏng có phát hiện, ứng phó và hệ quả với dữ liệu |
| **Kỹ năng SFIA** | `ARCH` mức 5 · `SYSP` mức 5 |
| **Chế độ hỏng** | Vẽ một thành phần không gắn với yêu cầu nào, nói cuối cùng nhất quán mà không có hợp đồng với người dùng, coi bộ nhớ đệm là nguồn sự thật, và bỏ qua năng lực, bảo mật cùng đường quay lui |""",
"""Module không dạy kiến thức mới; nó buộc dùng lại toàn bộ chương trình dưới áp lực của một quy trình có thứ tự và của phản biện.

Hai phép thử chạy cho mọi thiết kế. **Phép thử bỏ thành phần:** gỡ một hộp ra thì mất bảo đảm nào; nếu không mất gì thì hộp đó không có lý do tồn tại. **Phép thử đổi ràng buộc:** gấp mười lưu lượng, yêu cầu xoá dữ liệu nghiêm ngặt, mất một vùng, hoặc cắt nửa ngân sách; thiết kế phải đổi được mà không mất tính đúng.

Bậc thang mười bài toán đi từ một dịch vụ đơn tới một nền tảng nhiều khách hàng; ba bài được cài đặt, ba bài được đo thử, bốn bài rà soát trên giấy.""")

L22 = [
(405,"The ten-step design process","LT","Module 22: M21",
"Bài mở module bằng một quy trình có thứ tự cố định, vì bỏ bước hoặc đảo bước là nguồn của phần lớn thiết kế hỏng. Mười bước: làm rõ người dùng cùng ca sử dụng, yêu cầu chức năng cùng phi chức năng và phi mục tiêu; lượng hoá lưu lượng, dữ liệu, thời hạn giữ, độ trễ, khả dụng, nhất quán, hai con số phục hồi và chi phí; định nghĩa giao diện, sự kiện, mô hình dữ liệu và quyền sở hữu; vẽ kiến trúc tối thiểu cùng đường dữ liệu trọng yếu; phát biểu bất biến và ranh giới nhất quán; tính năng lực từng thành phần rồi tìm nút thắt; liệt kê chế độ hỏng cùng phát hiện, giảm thiểu và phục hồi; bảo mật cùng quyền riêng tư cùng quản trị cùng quan sát được cùng triển khai cùng di trú; nêu phương án thay thế và đánh đổi cùng điều kiện thiết kế không còn phù hợp; và kiểm chứng bằng một thử nghiệm nhỏ rồi viết bản ghi quyết định. **Phi mục tiêu ở bước một là phần lọc mạnh nhất** và hay bị bỏ nhất.",
"Chạy đủ mười bước cho một bài toán nhỏ và dừng được ở bước hai với các con số có căn cứ.",
"Tầng *áp dụng*. Bài mở module, áp một quy trình vào một bài toán đã quen. Kiểm bằng rà soát mười bước; đạt khi mọi bước có đầu ra ghi lại và bước hai có con số kèm giả định chứ để trống.",
"Lấy bài toán rút gọn địa chỉ. Chạy đủ mười bước và nộp đầu ra từng bước. Ở bước một, viết ít nhất ba phi mục tiêu. Ở bước hai, mọi con số kèm giả định và nguồn. Đổi bài chéo: người khác đọc và tìm một thành phần chưa gắn với yêu cầu nào.",
"Vẽ kiến trúc trước khi lượng hoá yêu cầu · bỏ phi mục tiêu · ghi con số mà không ghi giả định · nhảy tới phương án thay thế trước khi có kiến trúc tối thiểu.",
"Mười bước có đầu ra ghi lại, ít nhất ba phi mục tiêu, và mọi con số ở bước hai kèm giả định cùng nguồn."),

(406,"Quantifying requirements - traffic, data, latency, RPO and cost","TH","Lesson 405",
"Bài rèn bước hai, vì đây là bước quyết định mọi con số sau. Sáu nhóm phải lượng hoá: số yêu cầu mỗi giây ở mức trung bình và mức đỉnh cùng tỉ số giữa chúng; lượng dữ liệu mỗi ngày, tổng dữ liệu theo thời hạn giữ, và tập dữ liệu làm việc; mục tiêu độ trễ phát biểu theo phân vị chứ theo trung bình; mục tiêu khả dụng cùng mô hình nhất quán mà người dùng quan sát được; hai con số phục hồi; và ngân sách chi phí. **Phân bố mới là thứ quyết định thiết kế, không phải giá trị trung bình**: một hệ có tỉ số đỉnh trên trung bình bằng mười cần thiết kế khác hẳn hệ có tỉ số bằng hai. Khoá nóng và khách hàng nóng phải ước lượng riêng. Mọi con số kèm giả định và kèm độ nhạy: nếu giả định sai gấp đôi thì kết luận nào đổi. Ba cách lấy con số khi chưa có hệ: từ hệ tương tự, từ quy mô nghiệp vụ, và từ giới hạn trên hiển nhiên.",
"Lượng hoá sáu nhóm cho hai bài toán, kèm giả định, độ nhạy và ước lượng khoá nóng.",
"Tầng *áp dụng*. Objective đòi con số có căn cứ và có biên độ chứ một con số đơn. Kiểm bằng rà soát chéo; đạt khi mọi con số có giả định và nguồn, tỉ số đỉnh trên trung bình được nêu, và độ nhạy chỉ ra được kết luận nào đổi.",
"Cho hai bài toán khác nhau về hình dạng tải. Lượng hoá sáu nhóm cho từng cái. Với mỗi con số, ghi cách lấy và giả định. Tính tỉ số đỉnh trên trung bình và ước lượng phân bố khoá. Chạy phân tích độ nhạy: nhân đôi hai giả định quan trọng nhất và ghi kết luận nào đổi.",
"Thiết kế theo giá trị trung bình · phát biểu độ trễ bằng trung bình · bỏ ước lượng khoá nóng · ghi con số mà không ghi cách lấy.",
"Sáu nhóm có con số kèm giả định và nguồn ở cả hai bài toán, tỉ số đỉnh trên trung bình được nêu, và phân tích độ nhạy chỉ ra kết luận đổi."),

(407,"Invariants and consistency boundaries","TH","Lesson 406",
"Bài rèn bước năm, và nó là bước phân biệt một thiết kế đúng với một sơ đồ hợp lý. Bất biến là mệnh đề luôn đúng bất kể thứ tự thao tác và bất kể lỗi; ví dụ số dư không âm, một khoá nghiệp vụ có đúng một bản ghi hiện hành theo lesson 157, hoặc tổng ở hai tầng phải khớp. **Bất biến quyết định ranh giới giao dịch và ranh giới phân vùng**: mọi thứ phải đúng cùng lúc thì phải nằm trong cùng một ranh giới nguyên tử; đặt chúng ở hai nơi thì bất biến đó không cưỡng chế được và phải chuyển sang bù trừ theo lesson 318. Từ đó suy ra câu hỏi thứ hai của bài: cái gì là nguồn sự thật và cái gì là dữ liệu dẫn xuất dựng lại được; **bộ nhớ đệm và dữ liệu dẫn xuất không bao giờ là nguồn sự thật**, và đường dựng lại phải mô tả được. Nhất quán cuối cùng phải kèm hợp đồng với người dùng về mức cũ tối đa, theo lesson 314.",
"Phát biểu bất biến cho hai thiết kế và suy ra ranh giới giao dịch cùng đường dựng lại dữ liệu dẫn xuất.",
"Tầng *phân tích*. Objective đòi suy ranh giới từ bất biến chứ đặt theo thói quen. Kiểm bằng bài phân tích; đạt khi mỗi bất biến chỉ ra đúng ranh giới cưỡng chế nó, mọi dữ liệu dẫn xuất có đường dựng lại, và mọi nhất quán cuối cùng có hợp đồng mức cũ.",
"Với hai thiết kế, liệt kê ít nhất năm bất biến mỗi cái. Với từng bất biến, chỉ ra nó được cưỡng chế ở đâu và chuyện gì xảy ra nếu hai thành phần liên quan nằm hai phân vùng. Phân loại mọi kho dữ liệu thành nguồn sự thật hay dẫn xuất, và mô tả đường dựng lại cho từng cái dẫn xuất. Với mỗi chỗ nhất quán cuối cùng, viết hợp đồng mức cũ tối đa.",
"Coi bộ nhớ đệm là nguồn sự thật · nói cuối cùng nhất quán mà không có hợp đồng mức cũ · đặt ranh giới phân vùng trước khi phát biểu bất biến · không có đường dựng lại cho dữ liệu dẫn xuất.",
"Mỗi bất biến chỉ ra đúng ranh giới cưỡng chế, mọi dữ liệu dẫn xuất có đường dựng lại, và mọi nhất quán cuối cùng có hợp đồng mức cũ."),

(408,"The capacity sheet - assumptions and sensitivity","TH","Lesson 407",
"Bài rèn bước sáu và tạo ra một hiện vật bắt buộc cho mọi thiết kế về sau. Bảng năng lực tính cho từng thành phần: số yêu cầu mỗi giây nó phải chịu, số kết nối đồng thời, lượng byte mỗi ngày, tập dữ liệu làm việc phải nằm trong bộ nhớ, và băng thông mạng. Mỗi ô có công thức chứ một con số, để đổi giả định thì bảng tự cập nhật. Từ bảng suy ra hai thứ: thành phần nào chạm trần trước, và ở giả định nào nó chạm. **Biết nút thắt đầu tiên quan trọng hơn biết năng lực tổng**, vì nó cho biết nên đầu tư vào đâu và cho biết thiết kế còn dùng được tới quy mô nào. Ngưỡng theo giai đoạn: thay vì thiết kế cho quy mô xa, nêu ngưỡng mà kiến trúc phải đổi và đổi thành gì. Độ nhạy chỉ ra giả định nào ảnh hưởng lớn nhất, và đó là giả định cần kiểm bằng thử nghiệm nhỏ trước tiên.",
"Lập bảng năng lực có công thức cho một thiết kế và chỉ ra nút thắt đầu tiên cùng ngưỡng đổi kiến trúc.",
"Tầng *áp dụng*. Objective có hiện vật kiểm được và một kết luận cụ thể. Kiểm bằng rà soát bảng; đạt khi mọi ô có công thức, nút thắt đầu tiên được chỉ ra kèm giả định, và ít nhất hai ngưỡng đổi kiến trúc được nêu.",
"Lập bảng năng lực cho mọi thành phần của một thiết kế, mỗi ô là công thức tham chiếu tới các giả định ở lesson 406. Tìm thành phần chạm trần trước và ghi ở giả định nào. Nhân đôi ba giả định lần lượt và ghi nút thắt có đổi không. Nêu hai ngưỡng mà kiến trúc phải đổi kèm mô tả đổi thành gì.",
"Ghi con số cố định thay vì công thức · tính năng lực tổng mà không tìm nút thắt · thiết kế thẳng cho quy mô xa nhất · bỏ tập dữ liệu làm việc khỏi bảng.",
"Mọi ô có công thức, nút thắt đầu tiên được chỉ ra kèm giả định, và ≥ 2 ngưỡng đổi kiến trúc được nêu kèm mô tả."),

(409,"Sequence 1 - a single stateful service","TH","Lesson 408",
"Bậc thứ nhất của bậc thang, và nó rèn thói quen truy một phép ghi cùng một phép đọc qua mọi thành phần. Một dịch vụ đơn có trạng thái gồm giao diện, logic, cơ sở dữ liệu và bộ nhớ đệm. Bốn câu hỏi cho mỗi thành phần: trạng thái nào được lưu bền, ranh giới thử lại ở đâu, điểm nhất quán ở đâu, và phục hồi lấy dữ liệu từ nguồn nào. Ba bài toán ở bậc này: rút gọn địa chỉ với sinh khoá, bộ nhớ đệm chuyển hướng, khoá nóng và hết hạn; bộ giới hạn tốc độ với trạng thái phân tán và đánh đổi giữa chính xác với khả dụng; và dịch vụ tệp với việc tách siêu dữ liệu khỏi khối dữ liệu, tải lên nhiều phần, toàn vẹn và vòng đời. **Bộ nhớ đệm làm hỏng tính đúng theo hai cách phải nêu: dữ liệu cũ và mất hiệu lực sai**, nên chính sách vô hiệu hoá phải viết ra chứ để mặc định.",
"Truy một phép ghi và một phép đọc qua mọi thành phần của ba thiết kế bậc một.",
"Tầng *áp dụng*. Objective là một thói quen truy vết áp cho mọi thiết kế sau. Kiểm bằng bài truy vết; đạt khi bốn câu hỏi có câu trả lời ở mọi thành phần của cả ba thiết kế và chính sách vô hiệu hoá bộ nhớ đệm được viết ra.",
"Thiết kế ba bài toán bậc một. Với mỗi cái, truy một phép ghi và một phép đọc qua mọi thành phần và trả lời bốn câu hỏi. Với bài rút gọn địa chỉ, tính năng lực và chỉ ra khoá nóng. Với bộ giới hạn tốc độ, nêu đánh đổi giữa đếm chính xác với khả dụng khi kho trạng thái chậm. Viết chính sách vô hiệu hoá bộ nhớ đệm.",
"Thêm bộ nhớ đệm mà không có chính sách vô hiệu hoá · bỏ qua khoá nóng · không truy phép đọc riêng khỏi phép ghi · để ranh giới thử lại không xác định.",
"Bốn câu hỏi có câu trả lời ở mọi thành phần của ba thiết kế, và chính sách vô hiệu hoá bộ nhớ đệm được viết ra."),

(410,"Sequence 2 - replicated and partitioned","TH","Lesson 409",
"Bậc thứ hai thêm nhiều bản sao và nhiều phân vùng, nên nó kéo theo toàn bộ M15. Bốn quyết định: định tuyến yêu cầu tới phân vùng nào; chọn giữa người dẫn và số đông theo lesson 312 và 315; xử lý tái phân bố khi thêm hoặc bớt nút theo lesson 313; và hành vi khi đọc phải bản sao cũ. Ba câu hỏi phải trả lời cho mọi thiết kế ở bậc này: mất một nút thì mất bảo đảm gì, phân vùng mạng thì bên nào tiếp tục phục vụ, và tái phân bố chạy trong lúc phục vụ thì ảnh hưởng ra sao. **Nói thêm một bản sao là không đủ; phải nói bản sao đồng bộ hay bất đồng bộ và lượng dữ liệu mất tối đa là bao nhiêu.** Bài toán ở bậc này là dịch vụ thông báo có nhiều kênh, có tuỳ chọn của người dùng, có khử trùng, có thử lại và có yêu cầu về thứ tự.",
"Thiết kế một dịch vụ có bản sao và phân vùng, trả lời được ba câu hỏi và nêu lượng dữ liệu mất tối đa.",
"Tầng *áp dụng*. Objective đòi nối lựa chọn sao chép với một con số rủi ro. Kiểm bằng rà soát thiết kế; đạt khi ba câu hỏi có câu trả lời cụ thể, lượng dữ liệu mất tối đa tính được, và cách xử lý khoá nóng được nêu.",
"Thiết kế dịch vụ thông báo nhiều kênh. Chọn cách phân vùng và cách sao chép kèm lý do. Trả lời ba câu hỏi. Tính lượng dữ liệu mất tối đa từ độ trễ sao chép. Mô tả quy trình tái phân bố có giới hạn tốc độ. Nêu chính sách khử trùng và yêu cầu về thứ tự mà người dùng quan sát được.",
"Nói thêm bản sao mà không nói đồng bộ hay bất đồng bộ · bỏ qua ảnh hưởng của tái phân bố lên dịch vụ đang chạy · giả định thứ tự toàn cục · không nêu hành vi khi đọc phải bản sao cũ.",
"Ba câu hỏi có câu trả lời cụ thể, lượng dữ liệu mất tối đa tính được từ độ trễ sao chép, và quy trình tái phân bố có giới hạn tốc độ."),

(411,"Sequence 3 - asynchronous workflow","TH","Lesson 410",
"Bậc thứ ba tách xử lý ra khỏi đường yêu cầu, và nó kéo theo M16 cùng M18. Ranh giới đồng bộ và bất đồng bộ là quyết định trung tâm: phần nào phải xong trước khi trả lời người dùng, phần nào làm sau. Bốn thứ phải thiết kế: trạng thái của bên tiêu thụ và cách nó tiến, thử lại cùng luỹ đẳng theo lesson 105, áp lực ngược khi bên tiêu thụ chậm hơn bên sản xuất, và bản ghi độc cùng hàng đợi lỗi. **Chuyển sang bất đồng bộ đổi hợp đồng với người dùng chứ chỉ đổi kiến trúc**: người dùng nhận lời hứa sẽ xử lý thay vì kết quả, nên giao diện phải có cách tra trạng thái và có cách báo khi thất bại. Bài toán ở bậc này là nền tảng nhật ký với nạp, đệm, đánh chỉ mục, lưu trữ lâu dài, truy vấn, thời hạn giữ và nhiều khách hàng.",
"Thiết kế một luồng bất đồng bộ có hợp đồng người dùng rõ và xử lý được bên tiêu thụ chậm.",
"Tầng *áp dụng*. Objective gồm một hệ quả về hợp đồng mà thiết kế hay bỏ qua. Kiểm bằng rà soát thiết kế; đạt khi ranh giới đồng bộ và bất đồng bộ có lý do, hợp đồng người dùng nêu cách tra trạng thái cùng cách báo thất bại, và áp lực ngược có cơ chế cụ thể.",
"Thiết kế nền tảng nhật ký. Chỉ ra ranh giới đồng bộ và bất đồng bộ cùng lý do. Viết hợp đồng người dùng cho phần bất đồng bộ gồm cách tra trạng thái và cách báo thất bại. Thiết kế áp lực ngược và chính sách bản ghi độc. Tính năng lực cho phần đệm khi bên tiêu thụ dừng một giờ.",
"Chuyển sang bất đồng bộ mà không đổi hợp đồng với người dùng · không có cách tra trạng thái · để hàng đợi không giới hạn · bỏ chính sách bản ghi độc.",
"Ranh giới đồng bộ và bất đồng bộ có lý do, hợp đồng người dùng đủ hai phần, và năng lực đệm khi bên tiêu thụ dừng một giờ tính được."),

(412,"Sequence 4 - an analytical platform","TH","Lesson 411",
"Bậc thứ tư là bậc gần nhất với công việc thật của chương trình, và nó gộp M11 tới M14D. Năm chặng: nạp dữ liệu, lưu trữ bất biến, chốt siêu dữ liệu, tính toán phân tán, và tầng phục vụ. Với mỗi chặng, nêu hợp đồng vào và hợp đồng ra, và nêu chặng đó chạy lại được từ đâu. Ba bài toán ở bậc này: nền tảng phân tích với hợp đồng sự kiện cùng quản trị; kho dữ liệu kết hợp với nạp theo lô cùng bắt thay đổi, chốt bảng, danh mục và cách ly tính toán; và phân tích dòng chảy với phân vùng, thời gian sự kiện, mốc nước, trạng thái và đích. **Yêu cầu riêng của bậc này là chứng minh tính đầy đủ, chứ chỉ vẽ luồng**: thiết kế phải chỉ ra đối soát chạy ở đâu và chênh lệch được quy về đoạn nào, theo lesson 284.",
"Thiết kế một nền tảng phân tích có chốt đối soát ở mọi chặng và đường chạy lại rõ.",
"Tầng *áp dụng*. Objective đòi tính đầy đủ chứ một sơ đồ luồng. Kiểm bằng rà soát thiết kế; đạt khi mỗi chặng có hợp đồng vào ra cùng đường chạy lại, và chốt đối soát đặt đủ để quy chênh lệch về một đoạn.",
"Thiết kế một trong ba bài toán bậc bốn. Với mỗi chặng, viết hợp đồng vào ra và đường chạy lại. Đặt chốt đối soát và chỉ ra một chênh lệch giả định được quy về đoạn nào. Tính năng lực cho chặng tốn nhất. Nêu cách cách ly tính toán giữa các khối lượng công việc.",
"Vẽ luồng mà không có chốt đối soát · bỏ đường chạy lại ở một chặng · để mọi khối lượng công việc dùng chung một cụm tính toán · bỏ quản trị và quyền sở hữu khỏi thiết kế.",
"Mỗi chặng có hợp đồng vào ra và đường chạy lại, và chốt đối soát đủ để quy một chênh lệch giả định về đúng đoạn."),

(413,"Sequence 5 - a multi-tenant platform","TH","Lesson 412",
"Bậc cao nhất, và nó thêm một chiều mà bốn bậc trước không có: nhiều khách hàng dùng chung hạ tầng. Tách mặt phẳng điều khiển khỏi mặt phẳng dữ liệu theo lesson 361. Bốn cơ chế bắt buộc: cách ly dữ liệu giữa các khách hàng cưỡng chế ở mọi lối vào; hạn mức để một khách hàng không ăn hết năng lực theo lesson 333; chính sách và ngoại lệ có chủ cùng hạn; và tự phục vụ để đội nền tảng không thành nút cổ chai. **Vấn đề đặc trưng là khách hàng ồn ào: một khách chạy khối lượng nặng làm mọi khách khác chậm**, và cách chặn là hạn mức cộng vách ngăn chứ trông chờ vào thiện chí. Quy chi phí về từng khách hàng cần gắn thẻ và đo theo đơn vị theo lesson 368. Thiết kế này còn phải nêu cách đội dùng nền tảng tự làm được việc mà không mở phiếu yêu cầu.",
"Thiết kế nền tảng nhiều khách hàng có cách ly, hạn mức, quy chi phí và đường tự phục vụ.",
"Tầng *đánh giá*. Objective gồm cả chiều tổ chức chứ chỉ kỹ thuật. Kiểm bằng rà soát thiết kế cộng ba tình huống; đạt khi cách ly cưỡng chế ở mọi lối vào, tình huống khách hàng ồn ào có cơ chế chặn cụ thể, và chi phí quy được về từng khách hàng.",
"Thiết kế nền tảng dữ liệu nhiều khách hàng. Liệt kê mọi lối vào và chỉ ra cách ly cưỡng chế ở từng lối. Thiết kế hạn mức và vách ngăn; mô phỏng tình huống khách hàng ồn ào và chỉ ra cơ chế chặn. Thiết kế cách quy chi phí về từng khách hàng. Mô tả đường tự phục vụ cho ba việc thường gặp nhất.",
"Cách ly chỉ ở giao diện chính mà quên đường phụ · không có hạn mức nên một khách ăn hết năng lực · không quy được chi phí về khách hàng · để mọi thay đổi đi qua phiếu yêu cầu cho đội nền tảng.",
"Cách ly cưỡng chế ở mọi lối vào, tình huống khách hàng ồn ào có cơ chế chặn cụ thể, chi phí quy được về từng khách hàng, và ba việc tự phục vụ được mô tả."),

(414,"The failure table and the remove-component test","TH","Lesson 413",
"Hai hiện vật bắt buộc cho mọi thiết kế, và cả hai đều lọc ra những thứ không có lý do tồn tại. Bảng chế độ hỏng có sáu cột: thành phần, tác nhân kích hoạt, triệu chứng, cách phát hiện, ứng phó tự động hay thủ công, và **hệ quả với dữ liệu**; cột cuối là cột hay thiếu nhất và là cột quan trọng nhất với một hệ dữ liệu, vì mất khả dụng khác mất dữ liệu. Phép thử bỏ thành phần: với từng hộp trong sơ đồ, giả sử gỡ nó ra và hỏi mất bảo đảm nào; **nếu không mất gì thì hộp đó chưa được biện minh** và phải gỡ hoặc phải viết ra bảo đảm nó giữ. Phép thử này bắt được ba thứ thừa hay gặp: một tầng đệm không ai cần, một hàng đợi giữa hai dịch vụ luôn đồng bộ, và một kho dữ liệu trùng chức năng với kho khác.",
"Lập bảng chế độ hỏng sáu cột và chạy phép thử bỏ thành phần cho mọi hộp trong một thiết kế.",
"Tầng *đánh giá*. Objective đòi biện minh từng thành phần chứ mô tả chúng. Kiểm bằng hai hiện vật; đạt khi mọi thành phần có ít nhất một dòng trong bảng hỏng kèm hệ quả với dữ liệu, và mọi hộp qua được phép thử bỏ thành phần hoặc bị gỡ.",
"Với một thiết kế đã làm, lập bảng chế độ hỏng đủ sáu cột cho mọi thành phần. Chạy phép thử bỏ thành phần cho từng hộp và ghi bảo đảm mất đi. Gỡ mọi hộp không biện minh được và vẽ lại sơ đồ. So số thành phần trước và sau.",
"Bỏ cột hệ quả với dữ liệu · viết ứng phó mà không nói cách phát hiện · giữ thành phần vì kiến trúc tham khảo nào đó có nó · chạy phép thử bỏ thành phần chỉ cho vài hộp.",
"Mọi thành phần có dòng trong bảng hỏng kèm hệ quả với dữ liệu, và mọi hộp còn lại đều qua phép thử bỏ thành phần."),

(415,"Cost model and unit economics in a design","TH","Lesson 414",
"Chi phí là một chiều thiết kế ngang hàng với hiệu năng và độ tin cậy, nên nó có mô hình chứ một ước tính. Mô hình chi phí tính từ bảng năng lực ở lesson 408: mỗi thành phần có công thức chi phí theo các giả định, nên đổi giả định thì chi phí tự cập nhật. Chi phí trên mỗi đơn vị theo lesson 368 là con số dùng để so hai phương án và để phát hiện vấn đề khi quy mô tăng. **Ba thành phần chi phí không tỉ lệ với công việc hữu ích và hay bị bỏ sót: lưu lượng ra ngoài, năng lực nhàn rỗi, và chi phí của chính hệ đo lường.** Chi phí của độ tin cậy phải nêu tường minh: chạy nhiều vùng đắt gấp mấy lần và mua được gì. Ngưỡng chi phí theo giai đoạn giống ngưỡng năng lực: tới quy mô nào thì mô hình chi phí đổi và phải thiết kế lại.",
"Lập mô hình chi phí theo công thức cho một thiết kế và so hai phương án theo chi phí trên mỗi đơn vị.",
"Tầng *đánh giá*. Objective đòi so phương án bằng chi phí đơn vị chứ tổng ước tính. Kiểm bằng mô hình cộng bài so; đạt khi mọi ô là công thức, ba thành phần hay bị bỏ sót đều có mặt, và hai phương án so được ở ít nhất hai mức quy mô.",
"Lập mô hình chi phí theo công thức cho mọi thành phần của một thiết kế. Tính chi phí trên mỗi đơn vị. Dựng phương án thứ hai khác về kiến trúc và so ở hai mức quy mô cách nhau mười lần; chỉ ra mức mà thứ hạng đảo ngược nếu có. Tính riêng chi phí của độ tin cậy nhiều vùng và nêu nó mua được gì.",
"Ước tính tổng mà không quy về đơn vị · bỏ lưu lượng ra ngoài · bỏ chi phí của hệ đo lường · so hai phương án ở một mức quy mô duy nhất.",
"Mọi ô là công thức, ba thành phần hay bị bỏ sót đều có mặt, và hai phương án so được ở hai mức quy mô kèm điểm đảo ngược nếu có."),

(416,"Alternatives, trade-offs and reversibility","TH","Lesson 415",
"Bài rèn bước chín, và nó là bước phân biệt một thiết kế với một lựa chọn đã định sẵn. Ba phương án thật, luôn gồm phương án không làm gì; **một phương án thật là phương án mà nếu ràng buộc đổi thì nó sẽ thắng**, nên hai phương án dựng lên chỉ để loại bỏ là dấu hiệu quyết định đã định trước. Với mỗi phương án, lượng hoá hệ quả theo cùng bộ tiêu chí. Phân loại quyết định theo mức đảo ngược: quyết định dễ đảo thì quyết nhanh và học từ thực tế; quyết định khó đảo thì cần thử nghiệm nhỏ trước và cần bản ghi quyết định. Ba loại chi phí của việc đảo ngược: chi phí kỹ thuật, chi phí di trú dữ liệu, và chi phí tổ chức. **Điều kiện thiết kế không còn phù hợp phải viết ra cùng lúc với quyết định**, vì viết sau thì không ai viết, và không có nó thì kiến trúc sống quá hạn.",
"Trình ba phương án thật có lượng hoá và nêu điều kiện làm lựa chọn không còn phù hợp.",
"Tầng *đánh giá*. Objective chống lại việc trình bày một quyết định đã định sẵn. Kiểm bằng rà soát chéo; đạt khi mỗi phương án có ít nhất một bối cảnh mà nó thắng, mọi hệ quả được lượng hoá theo cùng bộ tiêu chí, và điều kiện đảo ngược được nêu.",
"Với một quyết định kiến trúc thật, dựng ba phương án gồm cả không làm gì. Lượng hoá hệ quả theo cùng bộ tiêu chí. Với mỗi phương án, nêu một bối cảnh mà nó thắng. Phân loại quyết định theo mức đảo ngược và tính ba loại chi phí đảo ngược cho phương án chọn. Viết hai điều kiện làm lựa chọn không còn phù hợp.",
"Dựng phương án rơm để loại · so các phương án theo bộ tiêu chí khác nhau · bỏ phương án không làm gì · không viết điều kiện thiết kế hết phù hợp.",
"Mỗi phương án có một bối cảnh mà nó thắng, hệ quả lượng hoá theo cùng bộ tiêu chí, và hai điều kiện đảo ngược được nêu kèm chi phí."),

(417,"Migration design - dual run, cutover, rollback","TH","Lesson 416",
"Phần lớn thiết kế trong công việc thật là thiết kế cho một hệ đang chạy, nên di trú là một phần của thiết kế chứ một việc sau đó. Bốn giai đoạn: kiểm kê bên tiêu thụ theo lesson 264; chạy song song hai hệ và đối soát kết quả; chuyển đổi dần theo từng phần lưu lượng hoặc từng khách hàng; và giữ đường quay lui cho tới khi hệ cũ được gỡ. **Chạy song song là giai đoạn cho bằng chứng, và bỏ nó là bỏ cách duy nhất biết hệ mới đúng trước khi phụ thuộc vào nó.** Một lần chuyển đổi toàn bộ là chế độ hỏng đặc trưng vì nó không có đường lùi. Thời hạn giữ hệ cũ tính từ thời gian cần để phát hiện vấn đề, chứ từ mong muốn dọn sớm. Di trú dữ liệu có hai bài toán riêng: chuyển khối dữ liệu lịch sử, và giữ hai hệ đồng bộ trong lúc chuyển.",
"Thiết kế kế hoạch di trú bốn giai đoạn có đối soát khi chạy song song và đường quay lui đã thử.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là bằng chứng từ giai đoạn chạy song song. Kiểm bằng rà soát kế hoạch cộng một lần diễn tập; đạt khi kiểm kê bên tiêu thụ đầy đủ, đối soát chạy song song có tiêu chí đạt, và quay lui được diễn tập.",
"Lập kế hoạch di trú cho một thay đổi kiến trúc thật. Kiểm kê bên tiêu thụ bằng khai báo cộng nhật ký truy vấn. Thiết kế giai đoạn chạy song song kèm tiêu chí đối soát để chuyển sang giai đoạn sau. Chia chuyển đổi theo từng phần. Diễn tập quay lui ở một môi trường thử. Tính thời hạn giữ hệ cũ từ thời gian phát hiện vấn đề.",
"Chuyển đổi toàn bộ một lần · bỏ giai đoạn chạy song song vì tốn gấp đôi · gỡ hệ cũ theo lịch thay vì theo kiểm kê · không diễn tập quay lui.",
"Kiểm kê bên tiêu thụ đầy đủ, đối soát chạy song song có tiêu chí đạt, quay lui diễn tập thành công, và thời hạn giữ hệ cũ có căn cứ."),

(418,"Design review simulation - three passes","TH","Lesson 417",
"Bài rèn năng lực rà soát, vì đọc thiết kế của người khác là cách nhanh nhất để thấy lỗ hổng trong thiết kế của mình. Ba lượt rà soát có trọng tâm khác nhau và phải chạy tách biệt: lượt một về tính đúng, kiểm bất biến cùng ngữ nghĩa giao diện và mô hình dữ liệu; lượt hai về vận hành, kiểm chế độ hỏng cùng quy mô cùng bảo mật cùng chi phí; lượt ba về ràng buộc đổi. Người rà soát phải truy được mọi thành phần về một yêu cầu hoặc một bảo đảm, và câu hỏi mặc định là thành phần này giữ bảo đảm nào. Ba câu hỏi lọc dùng được ở mọi lượt: bất biến nào quyết định ranh giới giao dịch, thành phần nào chạm trần trước và ở giả định nào, và mỗi phụ thuộc hỏng thì cái gì mất khả dụng hoặc mất nhất quán. **Rà soát mà chỉ ghi nhận đồng ý là một buổi diễn**; mỗi lượt phải ghi phản đối và ghi quyết định.",
"Rà soát ba thiết kế của người khác theo ba lượt và ghi được phản đối cùng quyết định cho từng lượt.",
"Tầng *đánh giá*. Objective đo năng lực phát hiện lỗ hổng chứ năng lực đồng ý. Kiểm bằng rà soát chéo; đạt khi mỗi thiết kế nhận ít nhất ba phát hiện có căn cứ ở các lượt khác nhau, và mọi phát hiện dẫn ra thành phần cùng bảo đảm liên quan.",
"Đổi thiết kế với ba học viên khác. Với mỗi thiết kế, chạy ba lượt riêng biệt và ghi biên bản gồm phản đối, câu hỏi chưa trả lời được, và quyết định. Dùng ba câu hỏi lọc ở mọi lượt. Nhận biên bản về thiết kế của mình và sửa; ghi rõ phát hiện nào chấp nhận, phát hiện nào từ chối cùng lý do.",
"Gộp ba lượt thành một buổi · chỉ ghi nhận đồng ý · phát hiện mà không dẫn ra thành phần liên quan · từ chối phản đối mà không nêu lý do.",
"Mỗi thiết kế nhận ≥ 3 phát hiện có căn cứ ở các lượt khác nhau, và biên bản ghi đủ phản đối cùng quyết định cho từng lượt."),

(419,"The changed-constraint defence","TH","Lesson 418",
"Bài rèn năng lực quan trọng nhất của module: bảo vệ một quyết định rồi thay đổi nó khi ràng buộc đổi, mà không bám vào quyết định cũ. Bốn ràng buộc đổi chuẩn: lưu lượng gấp mười; yêu cầu xoá dữ liệu nghiêm ngặt theo quy định; mất một vùng; và cắt nửa ngân sách. Thêm hai ràng buộc về tổ chức: đội nhỏ lại một nửa, và thời hạn rút ngắn còn một phần ba. Với mỗi ràng buộc, ba câu hỏi: phần nào của thiết kế còn đúng, phần nào phải đổi, và đổi đó tốn gì. **Câu trả lời đúng thường không phải giữ nguyên thiết kế và cũng không phải vẽ lại từ đầu**, mà là chỉ ra đúng phần bị ảnh hưởng dựa trên bảng năng lực và bảng chế độ hỏng đã có. Hai thói quen cần bỏ: bảo vệ quyết định vì đã bỏ công vào nó, và đổi toàn bộ thiết kế vì một ràng buộc đổi.",
"Điều chỉnh một thiết kế cho bốn ràng buộc đổi, mỗi lần chỉ đúng phần bị ảnh hưởng kèm chi phí.",
"Tầng *đánh giá*. Objective đo năng lực thích ứng có căn cứ, và nó là tiêu chí ra của module. Kiểm bằng bốn tình huống đổi ràng buộc; đạt khi ít nhất ba lần chỉ đúng phần bị ảnh hưởng dẫn từ bảng năng lực hoặc bảng chế độ hỏng, và không lần nào vẽ lại toàn bộ khi không cần.",
"Người chấm đổi lần lượt bốn ràng buộc trên thiết kế đã làm. Với mỗi cái, trả lời ba câu hỏi trong 15 phút, dẫn từ bảng năng lực và bảng chế độ hỏng. Ghi chi phí của việc đổi. Với ràng buộc về tổ chức, chỉ ra phần nào của thiết kế phải bỏ đi thay vì làm chậm hơn.",
"Bám vào quyết định cũ vì đã bỏ công · vẽ lại toàn bộ thiết kế khi một ràng buộc đổi · trả lời mà không dẫn từ bảng năng lực · bỏ qua ràng buộc về tổ chức.",
"≥ 3/4 lần chỉ đúng phần bị ảnh hưởng dẫn từ hiện vật đã có, mỗi lần kèm chi phí, và không lần nào vẽ lại toàn bộ khi không cần."),

(420,"Capstone design dossier - RFC, spike and ADRs","DA","Lesson 419",
"Bài dự án khép module, và hồ sơ này là hiện vật chính để bảo vệ tốt nghiệp. Nộp gồm sáu phần: một bản đề xuất kỹ thuật từ sáu tới mười trang kèm sơ đồ; bảng năng lực có công thức và độ nhạy theo lesson 408; bảng chế độ hỏng sáu cột cùng mô hình mối đe doạ theo lesson 400 và 414; **một thử nghiệm nhỏ chạy được kiểm chứng giả định rủi ro nhất**, chứ một lập luận; ba bản ghi quyết định cho ba quyết định khó đảo ngược, mỗi bản có phương án thay thế và điều kiện xem lại; và kế hoạch di trú bốn giai đoạn theo lesson 417 cùng danh mục kiểm sẵn sàng vận hành và kế hoạch đo trong 30, 60, 90 ngày. Bài toán chọn ở bậc bốn hoặc bậc năm của bậc thang. Yêu cầu chấm nghiêm nhất: người rà soát phải truy được mọi thành phần về một yêu cầu hoặc một bảo đảm.",
"Nộp hồ sơ thiết kế đủ sáu phần, có thử nghiệm nhỏ chạy được và mọi thành phần truy được về một yêu cầu.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hiện vật bảo vệ được. Kiểm bằng rà soát ba lượt cộng phép thử truy ngược; đạt khi mọi thành phần truy được về một yêu cầu hoặc bảo đảm, thử nghiệm nhỏ cho kết quả kiểm chứng giả định, và bốn ràng buộc đổi được trả lời.",
"Chọn một bài toán bậc bốn hoặc bậc năm. Dựng đủ sáu phần của hồ sơ. Chạy thử nghiệm nhỏ cho giả định rủi ro nhất và báo cáo kết quả kể cả khi nó bác bỏ giả định. Trình bày 30 phút và chịu ba lượt rà soát cùng bốn ràng buộc đổi.",
"Viết thử nghiệm nhỏ thành một đoạn lập luận thay vì chạy thật · để một thành phần không truy được về yêu cầu nào · bỏ kế hoạch di trú vì thiết kế là hệ mới · giấu kết quả thử nghiệm khi nó bác bỏ giả định.",
"Sáu phần đầy đủ, mọi thành phần truy được về một yêu cầu hoặc bảo đảm, thử nghiệm nhỏ chạy thật có kết quả báo cáo trung thực, và bốn ràng buộc đổi được trả lời."),
]

M23 = ("Modern AI Engineering, Bounded", 421, 430, """| | |
|---|---|
| **Objective cấp module** | Dùng mô hình ngôn ngữ như một thành phần có hợp đồng, có đánh giá, có ngân sách và có mô hình mối đe doạ; biết khi nào một phương án đơn giản hơn thắng |
| **Tiền đề** | M2 · M6 · M8 · M11 · M14 · M19 · M21 |
| **Exit criterion** | Mã do công cụ sinh ra không được hợp nhất khi chưa có kiểm thử, rà soát tĩnh và rà soát bảo mật; bộ đánh giá bắt được hồi quy; kiến trúc giải thích được khi nào tìm kiếm đơn giản thắng phương án tăng cường truy hồi |
| **Kỹ năng SFIA** | `DATS` mức 3 · `SCTY` mức 4 |
| **Chế độ hỏng** | Lấy vài lần chạy thử thành công làm kết quả đánh giá, dựa vào câu lệnh nhắc để bảo mật, và coi thành công khi trình diễn là sẵn sàng cho sản xuất |""",
"""Module ở **mức `C`**: biết khi nào nên dùng và khi nào không, chứ không phải xây mô hình. Ranh giới này là chủ ý và được kiểm ở phần đánh giá: nếu một phương án đơn giản hơn đạt cùng kết quả thì phương án phức tạp không được chọn.

Hai nguyên tắc chi phối toàn module. **Đầu ra của mô hình là dữ liệu không tin cậy**, nên nó phải được kiểm lược đồ và phải bị giới hạn quyền ở ranh giới công cụ. Và **vài lần chạy thử thành công không phải kết quả đánh giá**: phải có tập đối chứng, có số đo, và có bộ kịch bản đối kháng.

Nền tảng học máy chỉ ở mức nhận biết; đây không phải đường đi sâu về vận hành mô hình.""")

L23 = [
(421,"The boundary of this module - what it is and is not","LT","Module 23: M22",
"Bài mở module bằng việc đặt ranh giới, vì đây là chỗ dễ trôi nhất. Module này học cách dùng mô hình ngôn ngữ như một thành phần trong hệ dữ liệu: nó có hợp đồng giao diện, có độ trễ, có chi phí, có tỉ lệ lỗi, và có mô hình mối đe doạ riêng. Nó **không** dạy huấn luyện mô hình, không dạy vận hành mô hình ở mức chuyên sâu, và không thay công việc phân tích. Mô hình khái niệm tối thiểu cần có: đơn vị mã hoá văn bản và cửa sổ ngữ cảnh, cơ chế chú ý ở mức khái niệm, và ba giai đoạn huấn luyện ở mức nhận biết. Ba thuộc tính kỹ thuật có hệ quả thiết kế: **đầu ra không tất định nên phép thử phải chịu được biến thiên**; chi phí và độ trễ tỉ lệ với số đơn vị mã hoá nên chúng tính trước được; và cửa sổ ngữ cảnh là ràng buộc cứng nên việc chọn đưa gì vào là một bài toán thiết kế chứ một chi tiết.",
"Phân định việc thuộc và không thuộc phạm vi module, và nêu ba hệ quả thiết kế của ba thuộc tính kỹ thuật.",
"Tầng *hiểu*. Bài mở module, đặt ranh giới. Kiểm bằng bài phân định mười tình huống; đạt khi phân đúng ít nhất tám và ba hệ quả thiết kế được nêu cụ thể.",
"Cho mười tình huống công việc; phân loại thuộc phạm vi module, thuộc một module khác, hay không thuộc chương trình. Với ba thuộc tính kỹ thuật, viết một hệ quả thiết kế cụ thể cho từng cái. Tính trước chi phí và độ trễ của một lời gọi từ số đơn vị mã hoá ước lượng và đối chiếu với số đo thật.",
"Trôi sang huấn luyện mô hình · coi đầu ra tất định nên viết phép thử so khớp chuỗi · bỏ qua ràng buộc cửa sổ ngữ cảnh khi thiết kế · ước lượng chi phí sau khi chạy thay vì trước.",
"Phân đúng ≥ 8/10 tình huống, ba hệ quả thiết kế được nêu cụ thể, và chi phí cùng độ trễ ước lượng trước khớp số đo thật trong sai số thoả thuận."),

(422,"AI-assisted engineering with verification","TH","Lesson 421",
"Dùng công cụ sinh mã trong công việc thật, với kỷ luật kiểm chứng làm trung tâm. Câu lệnh nhắc và ngữ cảnh là một bản đặc tả: cung cấp giao diện, ràng buộc, kiểm thử và ví dụ thì kết quả dùng được; mô tả mơ hồ thì nhận về mã trông hợp lý mà sai. Cách dùng đúng là **yêu cầu giả thuyết và kiểm thử, rồi tự chạy, chứ áp bản vá một cách mù quáng**. Khi gỡ lỗi, làm sạch nhật ký trước khi đưa vào và tái hiện lỗi độc lập chứ tin lời giải thích. Rà soát mã sinh ra theo bốn trục: tính đúng, bảo mật, giấy phép, và nguồn gốc; đo hiệu năng của mã sinh ra thay vì giả định. Một điểm phải kiểm luôn: **thư viện và tham số do công cụ đề xuất có thể đã lỗi thời hoặc không tồn tại**, nên đối chiếu với tài liệu chính thức kèm phiên bản là bước bắt buộc.",
"Dùng công cụ sinh mã cho ba nhiệm vụ với kỷ luật kiểm chứng và phát hiện được lỗi trong mã sinh ra.",
"Tầng *áp dụng*. Objective đòi kiểm chứng chứ tiêu thụ. Kiểm bằng ba nhiệm vụ; đạt khi mọi đoạn mã sinh ra đều qua kiểm thử cùng rà soát bảo mật trước khi hợp nhất, và ít nhất một lỗi trong mã sinh ra được phát hiện bằng kiểm thử.",
"Chọn ba nhiệm vụ lập trình có tiêu chí rõ. Với mỗi cái, viết đặc tả gồm giao diện, ràng buộc và kiểm thử trước khi yêu cầu sinh mã. Chạy kiểm thử, rà soát tĩnh và rà soát bảo mật. Ghi lại mọi chỗ mã sinh ra sai, gồm cả tham số hoặc thư viện không tồn tại. Đo hiệu năng và so với bản viết tay.",
"Hợp nhất mã sinh ra mà chưa có kiểm thử · dán nhật ký chứa bí mật vào công cụ · tin lời giải thích thay vì tái hiện lỗi · dùng tham số công cụ đề xuất mà không tra tài liệu.",
"Mọi đoạn mã sinh ra qua kiểm thử và rà soát bảo mật trước khi hợp nhất, và ≥ 1 lỗi trong mã sinh ra được kiểm thử phát hiện."),

(423,"The LLM API contract - structured output, tools, budgets","TH","Lesson 422",
"Coi mô hình như một dịch vụ bên ngoài và áp đúng kỷ luật ở M8. Hợp đồng gồm: chọn mô hình theo năng lực, độ trễ, chi phí, quyền riêng tư và hỗ trợ công cụ, kèm ghim phiên bản và phương án dự phòng khi nhà cung cấp hỏng hoặc khai tử mô hình. Đầu ra có cấu trúc kèm kiểm lược đồ: **đầu ra sai lược đồ là chuyện bình thường phải xử lý chứ một sự cố**, nên cần thử lại có giới hạn và cần đường dự phòng. Gọi công cụ chỉ là mô hình đề nghị một lời gọi, và việc thực hiện thuộc về mã của ta; đây là chỗ đặt kiểm quyền ở lesson 428. Hết giờ, thử lại và hạn mức theo lesson 224, với lưu ý thử lại chỉ áp cho lỗi an toàn. Ngân sách số đơn vị mã hoá, ngân sách tốc độ và giới hạn đồng thời phải đặt trước. Câu lệnh nhắc và cấu hình là mã có phiên bản, gắn với bộ đánh giá của bản phát hành.",
"Cài lớp gọi có kiểm lược đồ, ngân sách và dự phòng, chịu được ba chế độ hỏng của nhà cung cấp.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là hệ vẫn đúng dưới lỗi của bên ngoài. Kiểm bằng ba chế độ hỏng tiêm; đạt khi cả ba được xử lý không sập, đầu ra sai lược đồ không lọt xuống hạ nguồn, và ngân sách không bị vượt.",
"Cài lớp gọi có kiểm lược đồ đầu ra, thử lại có giới hạn, ngân sách đơn vị mã hoá và giới hạn đồng thời. Tiêm ba chế độ hỏng: hết giờ, vượt hạn mức, và đầu ra sai lược đồ. Chứng minh không đầu ra sai nào lọt xuống hạ nguồn. Đặt câu lệnh nhắc và cấu hình vào kho mã có phiên bản. Kiểm phương án dự phòng khi mô hình chính không dùng được.",
"Phân tích đầu ra bằng cách tìm chuỗi thay vì kiểm lược đồ · thử lại mọi lỗi · không ghim phiên bản mô hình · để câu lệnh nhắc nằm ngoài kho mã.",
"Ba chế độ hỏng được xử lý không sập, không đầu ra sai lược đồ nào lọt hạ nguồn, ngân sách không bị vượt, và dự phòng hoạt động."),

(424,"Retrieval - chunking, embedding, filters and rerank","TH","Lesson 423",
"Tầng truy hồi quyết định chất lượng câu trả lời nhiều hơn phần sinh văn bản, nên nó được học kỹ hơn. Đường đi: lấy tài liệu, phân tích, chia đoạn, nhúng thành véctơ, đánh chỉ mục, truy hồi, lọc, sắp xếp lại, rồi mới dựng ngữ cảnh. Chia đoạn theo ranh giới ngữ nghĩa cùng phần chồng lấn và giữ siêu dữ liệu; cấu trúc cha con giữ được ngữ cảnh mục lớn. Truy hồi thưa dựa trên từ khoá và truy hồi dày dựa trên véctơ bắt được hai loại truy vấn khác nhau, nên kết hợp thường thắng. Bộ sắp xếp lại đắt nhưng cải thiện rõ ở phần đầu danh sách. Hai điểm bắt buộc: **kho véctơ là một chỉ mục chứ nguồn sự thật**, nên dựng lại được từ nguồn; và **lọc theo quyền phải áp trước khi trả kết quả**, không phải sau, nếu không thì rò rỉ dữ liệu giữa các khách hàng. Đổi phiên bản mô hình nhúng buộc dựng lại toàn bộ chỉ mục.",
"Dựng đường truy hồi có lọc theo quyền và đo được độ phủ ở k trước khi tới phần sinh văn bản.",
"Tầng *áp dụng*. Objective đo tầng truy hồi riêng chứ đo kết quả cuối. Kiểm bằng tập đối chứng truy hồi; đạt khi độ phủ ở k đo được cho ba cấu hình, và phép thử phủ định về quyền không trả về tài liệu ngoài phạm vi.",
"Dựng tập tài liệu có phân quyền theo khách hàng. Cài ba cấu hình truy hồi: chỉ từ khoá, chỉ véctơ, và kết hợp có sắp xếp lại. Xây tập đối chứng gồm truy vấn và tài liệu đúng. Đo độ phủ ở k và độ chính xác cho cả ba. Chạy phép thử phủ định về quyền. Đổi phiên bản mô hình nhúng và đo ảnh hưởng khi chưa dựng lại chỉ mục.",
"Coi kho véctơ là nguồn sự thật · lọc quyền sau khi truy hồi · chia đoạn theo số ký tự cố định cắt ngang câu · đổi mô hình nhúng mà không dựng lại chỉ mục.",
"Độ phủ ở k đo được cho ba cấu hình, phép thử phủ định về quyền không rò tài liệu, và ảnh hưởng của việc đổi mô hình nhúng được định lượng."),

(425,"Grounding, citation and abstention","TH","Lesson 424",
"Ba cơ chế biến một câu trả lời trôi chảy thành một câu trả lời dùng được. Bám nguồn nghĩa là mọi khẳng định phải dẫn được về một đoạn văn bản cụ thể trong tài liệu, kèm phiên bản tài liệu. Trích dẫn ánh xạ từng khẳng định tới đoạn nguồn chứ tới cả tài liệu, vì trích dẫn ở mức tài liệu không kiểm chứng được. **Trích dẫn bịa là chế độ hỏng nguy hiểm nhất** vì nó tạo vẻ đáng tin: câu trả lời trông có căn cứ trong khi nguồn không nói điều đó; cách chặn là kiểm trích dẫn bằng máy, đối chiếu đoạn được dẫn với nội dung thật. Từ chối trả lời khi bằng chứng không đủ là một tính năng chứ một thất bại, và ngưỡng từ chối là một tham số phải đo theo lesson 426. Chính sách cho tài liệu mâu thuẫn hoặc đã cũ: trình bày cả hai kèm phiên bản chứ chọn bừa một bên.",
"Cài kiểm trích dẫn bằng máy và cơ chế từ chối, chứng minh không trích dẫn bịa nào lọt.",
"Tầng *áp dụng*. Objective có một tiêu chí nghiệm thu nhị phân về tính trung thực. Kiểm bằng tập đối chứng có tài liệu mâu thuẫn và câu hỏi không có đáp án; đạt khi không trích dẫn bịa nào lọt và tỉ lệ từ chối đúng trên nhóm câu không có đáp án vượt ngưỡng.",
"Xây tập đối chứng gồm câu hỏi có đáp án, câu hỏi không có đáp án trong tài liệu, và câu hỏi có hai tài liệu mâu thuẫn. Cài trích dẫn ở mức đoạn và kiểm trích dẫn bằng máy. Cài cơ chế từ chối có ngưỡng. Đo tỉ lệ trích dẫn bịa, tỉ lệ từ chối đúng và tỉ lệ từ chối nhầm. Áp chính sách cho tài liệu mâu thuẫn.",
"Trích dẫn ở mức tài liệu · không kiểm trích dẫn bằng máy · coi từ chối là thất bại rồi ép mô hình luôn trả lời · chọn một tài liệu khi có mâu thuẫn mà không nói.",
"Không trích dẫn bịa nào lọt qua phép kiểm máy, tỉ lệ từ chối đúng vượt ngưỡng trên nhóm không có đáp án, và tài liệu mâu thuẫn được trình bày kèm phiên bản."),

(426,"The evaluation blueprint - five layers","TH","Lesson 425",
"Bài đặt ra chuẩn đánh giá của module, thay cho việc thử vài câu rồi kết luận. Năm tầng, mỗi tầng có số đo riêng: tầng nạp tài liệu đo độ phủ phân tích, độ tươi, quyền truy cập và trùng lặp; tầng truy hồi đo độ phủ ở k, độ chính xác và tính đúng của bộ lọc; tầng sinh văn bản đo mức bám nguồn, tính đúng của nhiệm vụ, chất lượng trích dẫn và tỉ lệ từ chối; tầng hệ thống đo độ trễ phân vị, tỉ lệ lỗi, chi phí trên mỗi đơn vị và khả dụng; tầng an toàn đo kết quả trên bộ kịch bản đối kháng. **Đo tách từng tầng là điều kiện để biết sửa chỗ nào**, vì một câu trả lời sai có thể do truy hồi trượt hoặc do sinh văn bản sai, và hai nguyên nhân cần hai cách sửa. Tập đối chứng phải gắn với bản phát hành và chạy lại ở mỗi lần đổi câu lệnh nhắc, đổi mô hình hoặc đổi chỉ mục. Rà soát người cho phần không đo được bằng máy.",
"Dựng bộ đánh giá năm tầng chạy tự động và bắt được hồi quy khi đổi một thành phần.",
"Tầng *áp dụng*. Objective là một cửa chặn hồi quy có số đo theo tầng. Kiểm bằng ba thay đổi tiêm; đạt khi mỗi thay đổi làm đúng tầng tương ứng xuống điểm và bộ đánh giá chặn được bản phát hành.",
"Dựng bộ đánh giá năm tầng trên tập đối chứng cố định. Chạy lấy đường cơ sở. Tiêm ba thay đổi: đổi cách chia đoạn, đổi câu lệnh nhắc, và đổi phiên bản mô hình. Với mỗi cái, chỉ ra tầng nào xuống điểm. Đặt ngưỡng chặn phát hành và xác nhận nó chặn đúng. Thêm một vòng rà soát người cho phần không đo được.",
"Thử vài câu rồi kết luận · chỉ đo kết quả cuối nên không biết sửa tầng nào · đổi tập đối chứng mỗi lần đánh giá · bỏ tầng chi phí và độ trễ.",
"Ba thay đổi tiêm làm đúng tầng tương ứng xuống điểm, và bộ đánh giá chặn được bản phát hành theo ngưỡng."),

(427,"Baseline first - when simple search beats retrieval augmentation","TH","Lesson 426",
"Bài chống lại việc mặc định chọn phương án phức tạp, và nó là bài thể hiện rõ nhất mức `C` của module. Quy trình bắt buộc: dựng đường cơ sở đơn giản nhất trước, đo trên cùng tập đối chứng, rồi mới thêm độ phức tạp và **chỉ giữ phần nào cải thiện đủ bù chi phí của nó**. Ba đường cơ sở phải thử: tìm kiếm theo từ khoá, tra cứu có cấu trúc trên dữ liệu đã có, và một quy tắc nghiệp vụ đơn giản. Bốn tình huống mà phương án đơn giản thắng: câu hỏi có đáp án nằm trong một trường dữ liệu; tập tài liệu nhỏ và ít đổi; yêu cầu độ trễ rất thấp; và yêu cầu giải thích được đến mức không chấp nhận sinh văn bản. Chi phí của độ phức tạp phải nêu tường minh: thêm thành phần phải vận hành, thêm chi phí trên mỗi truy vấn, thêm chế độ hỏng, và thêm bề mặt bảo mật ở lesson 428.",
"So đường cơ sở với phương án tăng cường truy hồi trên cùng tập đối chứng và biện minh độ phức tạp bằng số.",
"Tầng *đánh giá*. Objective đòi biện minh độ phức tạp chứ mặc định chọn nó. Kiểm bằng bài so; đạt khi ba đường cơ sở có số đo trên cùng tập đối chứng, và quyết định dùng hay không dùng phương án phức tạp dẫn được từ cặp cải thiện với chi phí.",
"Dựng ba đường cơ sở cho cùng bài toán. Đo trên cùng tập đối chứng với cùng số đo ở lesson 426. Dựng phương án tăng cường truy hồi và đo lại. Tính chi phí trên mỗi truy vấn và số thành phần phải vận hành cho từng phương án. Kết luận bằng cặp cải thiện với chi phí. Tìm một loại câu hỏi mà đường cơ sở thắng.",
"Bắt đầu từ phương án phức tạp nhất · so hai phương án trên hai tập dữ liệu khác nhau · bỏ chi phí vận hành khỏi so sánh · kết luận bằng cảm nhận về chất lượng câu trả lời.",
"Ba đường cơ sở có số đo trên cùng tập đối chứng, quyết định dẫn từ cặp cải thiện với chi phí, và một loại câu hỏi mà đường cơ sở thắng được chỉ ra."),

(428,"Prompt injection, tool permission and tenant isolation","TH","Lesson 427",
"Bài bảo mật của module, và nó dựa trên một nguyên tắc duy nhất: **mọi thứ mô hình đọc được đều là dữ liệu không tin cậy, gồm cả tài liệu được truy hồi**. Tiêm chỉ dẫn qua nội dung xảy ra khi một tài liệu chứa câu lệnh hướng mô hình làm việc khác; nó không chặn được bằng cách viết thêm câu lệnh nhắc, vì cả hai đều là văn bản trong cùng ngữ cảnh. Ba lớp phòng thủ thật: **kiểm quyền ở ranh giới công cụ chứ ở câu lệnh nhắc**, tức mã thực hiện lời gọi tự kiểm quyền của người dùng thật; danh sách cho phép cho công cụ và tham số; và phê duyệt của người cho thao tác không đảo ngược được. Rò rỉ dữ liệu ra ngoài qua một công cụ có khả năng gửi đi là ca hỏng nặng nhất. Cách ly giữa các khách hàng áp trước truy hồi theo lesson 424. Vòng lặp gọi công cụ không kiểm soát gây chi phí tăng vọt, nên cần giới hạn số bước và ngân sách.",
"Tái hiện ba tấn công và chặn bằng ba lớp phòng thủ ở ranh giới công cụ, không bằng câu lệnh nhắc.",
"Tầng *phân tích*. Objective đòi đặt chốt kiểm soát đúng chỗ. Kiểm bằng bộ 30 kịch bản đối kháng; đạt khi mọi kịch bản rò rỉ dữ liệu hoặc vượt quyền bị chặn ở ranh giới công cụ, và không phòng thủ nào chỉ dựa trên câu lệnh nhắc.",
"Dựng bộ 30 kịch bản đối kháng gồm tiêm chỉ dẫn qua tài liệu, cố lấy dữ liệu của khách hàng khác, và cố gọi công cụ ngoài quyền. Chạy trên hệ chưa có phòng thủ và đếm số kịch bản thành công. Thêm ba lớp phòng thủ và chạy lại. Chứng minh phòng thủ nằm ở mã chứ ở câu lệnh nhắc. Đặt giới hạn số bước gọi công cụ và ngân sách.",
"Chặn tiêm chỉ dẫn bằng cách viết thêm vào câu lệnh nhắc · cho công cụ dùng quyền của dịch vụ thay vì của người dùng · không giới hạn số bước gọi công cụ · ghi cả nội dung nhạy cảm vào vết theo dõi.",
"Mọi kịch bản rò rỉ hoặc vượt quyền bị chặn ở ranh giới công cụ, không phòng thủ nào chỉ dựa vào câu lệnh nhắc, và vòng lặp gọi công cụ có giới hạn."),

(429,"Serving - latency, cost, fallback and version lineage","TH","Lesson 428",
"Bài vận hành của module, áp M21 vào một thành phần có đặc thù riêng. Độ trễ phân vị 95 chịu ảnh hưởng của số đơn vị mã hoá đầu ra nhiều hơn đầu vào, nên giới hạn độ dài đầu ra là đòn bẩy chính. Bộ nhớ đệm có hai mức: đệm theo câu hỏi giống hệt, và đệm theo kết quả truy hồi; **đệm phải tính tới quyền của người dùng, nếu không thì một người thấy câu trả lời dựng từ tài liệu của người khác**. Xử lý theo lô và hàng đợi cho khối lượng không cần tức thời. Đường dự phòng khi mô hình chính hỏng: mô hình khác, đường cơ sở đơn giản hơn ở lesson 427, hoặc trả lời rằng chưa phục vụ được. Truy vết nguồn gốc phải ghi đủ bốn thứ cho mỗi câu trả lời: phiên bản mô hình, phiên bản câu lệnh nhắc, phiên bản chỉ mục, và tập tài liệu đã dùng; thiếu bốn thứ này thì không điều tra được một câu trả lời sai.",
"Đạt ngưỡng độ trễ và chi phí với đệm an toàn theo quyền và truy vết nguồn gốc đủ bốn thứ.",
"Tầng *áp dụng*. Objective có ba tiêu chí nghiệm thu gồm một ca bảo mật. Kiểm bằng phép thử tải cộng phép thử đệm; đạt khi độ trễ phân vị 95 và chi phí trên mỗi truy vấn dưới ngưỡng, đệm không rò dữ liệu giữa người dùng, và mọi câu trả lời truy được bốn thứ.",
"Chạy tải và đo độ trễ phân vị cùng chi phí trên mỗi truy vấn. Giới hạn độ dài đầu ra và đo lại. Bật hai mức đệm và chạy phép thử phủ định: hai người dùng có quyền khác nhau hỏi cùng câu và kiểm không ai thấy tài liệu ngoài quyền. Cài ghi nguồn gốc bốn thứ. Tiêm lỗi nhà cung cấp và kiểm đường dự phòng.",
"Đệm theo câu hỏi mà bỏ qua quyền người dùng · tối ưu độ trễ bằng cách bỏ bước truy hồi · không ghi phiên bản chỉ mục nên không điều tra được câu trả lời cũ · không có đường dự phòng.",
"Độ trễ phân vị 95 và chi phí trên mỗi truy vấn dưới ngưỡng, đệm không rò dữ liệu giữa người dùng, và mọi câu trả lời truy được đủ bốn thứ."),

(430,"Grounded assistant project with a red-team suite","DA","Lesson 429",
"Bài dự án khép module, lấy đúng yêu cầu dự án của hợp đồng nguồn: một trợ lý trả lời câu hỏi trên tài liệu kỹ thuật, có bám nguồn. Nộp gồm bảy hạng mục: nạp tài liệu có phiên bản và truy vết nguồn gốc từng đoạn; trả lời có cấu trúc kèm trích dẫn ở mức đoạn và **có từ chối khi bằng chứng không đủ**; tập đối chứng gồm câu hỏi bình thường, câu hỏi đối kháng, tài liệu đã cũ và tài liệu mâu thuẫn; số đo năm tầng theo lesson 426 gồm cả độ trễ phân vị 95 và chi phí; ba lớp phòng thủ ở lesson 428 cùng kết quả bộ 30 kịch bản đối kháng; so với đường cơ sở đơn giản theo lesson 427; và quy trình thử nghiệm dần khi đổi câu lệnh nhắc, đổi mô hình hoặc đổi chỉ mục, kèm đường quay lui. Bốn điều kiện tự động chưa đạt: lấy vài lần chạy thử làm đánh giá, phòng thủ chỉ bằng câu lệnh nhắc, rò rỉ dữ liệu nhạy cảm, và không có cơ chế từ chối cùng ngân sách cùng dự phòng.",
"Nộp trợ lý đủ bảy hạng mục, vượt đường cơ sở có số đo, và không vi phạm bốn điều kiện tự động chưa đạt.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module. Kiểm bằng số đo năm tầng cộng bộ đối kháng; đạt khi mọi tầng có số đo, bộ 30 kịch bản không có kịch bản nào rò rỉ, và phần cải thiện so với đường cơ sở đủ bù chi phí tăng thêm.",
"Dựng trợ lý theo bảy hạng mục. Chạy bộ đánh giá năm tầng và bộ 30 kịch bản đối kháng. So với ba đường cơ sở. Thực hiện một lần đổi mô hình theo quy trình thử nghiệm dần rồi quay lui. Trình bày 20 phút và trả lời chất vấn về một câu trả lời sai: nó sai ở tầng nào và sửa thế nào.",
"Trình diễn vài câu hỏi thuận lợi thay vì chạy bộ đánh giá · bỏ cơ chế từ chối để tỉ lệ trả lời cao · dựa vào câu lệnh nhắc để chặn tiêm chỉ dẫn · bỏ so sánh với đường cơ sở.",
"Năm tầng đều có số đo, không kịch bản đối kháng nào rò rỉ, cải thiện so với đường cơ sở đủ bù chi phí, và không vi phạm bốn điều kiện tự động chưa đạt."),
]

M24 = ("Staff and Principal Trajectory", 431, 440, """| | |
|---|---|
| **Objective cấp module** | Chuyển từ làm xong việc sang thay đổi cách nhiều đội làm việc, bằng hiện vật có người đọc, có áp dụng và có kết quả đo được |
| **Tiền đề** | M1 tới M22, cộng ít nhất một hệ đã vận hành đủ lâu để có bằng chứng về sự cố, chi phí và thay đổi |
| **Exit criterion** | Ba bản đề xuất được rà soát, một bản được triển khai và đo sau khi áp dụng; một lần di trú có tương thích, quay lui, chủ sở hữu, số đo và bằng chứng bên tiêu thụ thật; **ít nhất hai kỹ sư hoặc hai đội làm được việc mà không cần tới mình**, nhờ giao diện, tài liệu và rào chắn tốt hơn |
| **Kỹ năng SFIA** | `ARCH` mức 5 · `ITMG` mức 5 |
| **Chế độ hỏng** | Tuyên bố tầm ảnh hưởng nhiều đội từ một danh mục cá nhân, đếm số tài liệu như là kết quả, giấu bất đồng và rủi ro, và không đo mức áp dụng |""",
"""Module này **không cấp danh hiệu**. Bậc cao đòi phạm vi, niềm tin và kết quả trong một tổ chức thật, nên phần lớn bằng chứng chỉ tạo ra được khi đi làm.

Cái module dạy được là **bộ hiện vật và tiêu chuẩn chất lượng của chúng**: cách khung một bài toán, cách viết một bản đề xuất có ba phương án thật, cách thiết kế một lần di trú, cách coi nền tảng như một sản phẩm, và cách đo kết quả thay vì đếm tài liệu.

Ranh giới bằng chứng được giữ nghiêm suốt module: **tách rõ cái làm trong lab, cái làm trong dự án cá nhân, và cái có tác động trong sản xuất**; gộp ba thứ này là một dạng nói quá.""")

L24 = [
(431,"The competency ladder and what evidence means","LT","Module 24: M23",
"Bài mở module bằng ba bậc năng lực và bằng chứng tương ứng của từng bậc. Bậc cao cấp sở hữu kết quả của một hệ có yêu cầu mơ hồ: chia nhỏ, ước lượng, giao hàng đầu cuối, trực và phục hồi; bằng chứng là một dịch vụ hoặc đường dữ liệu được sở hữu cùng một cải thiện đo được về cam kết, chi phí hoặc tính đúng. Bậc tiếp theo dẫn dắt kỹ thuật xuyên đội: nhận ra vấn đề hệ thống, lập bản đồ bên liên quan cùng động cơ cùng phụ thuộc, viết đề xuất, điều phối rà soát và giải quyết bất đồng, dựng kiến trúc đích cùng đường di trú từng bước, và coi nền tảng như sản phẩm. Bậc cao nhất định hướng toàn tổ chức. **Danh hiệu thay đổi theo công ty, còn bằng chứng thì không**: bằng chứng là quyết định, kết quả và mức đòn bẩy. Ranh giới bằng chứng phải giữ nghiêm: lab khác dự án cá nhân, và cả hai khác tác động trong sản xuất.",
"Chấm bằng chứng hiện có của mình theo ba bậc và phân tách đúng ba loại bằng chứng.",
"Tầng *hiểu*. Bài mở module, đặt chuẩn bằng chứng. Kiểm bằng bài tự chấm có rà soát chéo; đạt khi mọi mục bằng chứng được phân đúng ba loại và mỗi tuyên bố có một cách kiểm chứng từ bên ngoài.",
"Liệt kê mọi bằng chứng hiện có. Phân mỗi mục vào lab, dự án cá nhân, hay tác động trong sản xuất. Với mỗi mục thuộc loại thứ ba, ghi cách một người bên ngoài kiểm chứng được. Chấm theo ba bậc và chỉ ra khoảng trống lớn nhất. Đổi bài chéo: người khác đọc và đánh dấu mọi chỗ nói quá.",
"Gộp bằng chứng lab với bằng chứng sản xuất · tuyên bố bậc cao từ việc học xong chương trình · đếm dự án thay vì nêu kết quả · không có cách để bên ngoài kiểm chứng.",
"Mọi mục bằng chứng phân đúng ba loại, mỗi tuyên bố về sản xuất có cách kiểm chứng từ bên ngoài, và rà soát chéo không tìm thấy chỗ nói quá."),

(432,"Problem framing on one page","TH","Lesson 431",
"Hiện vật đầu tiên và cũng là hiện vật quyết định nhất, vì phần lớn công việc sai hướng bắt đầu từ một bài toán chưa được khung đúng. Một trang gồm sáu phần: hiện trạng có bằng chứng từ sự cố, chi phí, thời gian của đội hoặc trải nghiệm người dùng; ảnh hưởng lượng hoá được; ai chịu ảnh hưởng và ai quyết định; ràng buộc gồm cả ràng buộc về tổ chức; phi mục tiêu; và tiêu chí thành công đo được. **Phần hiện trạng phải có dữ liệu chứ ý kiến**, và đây là phần phân biệt một bài toán thật với một sở thích kỹ thuật. Ba dấu hiệu một bài toán chưa được khung đúng: giải pháp đã có tên trước khi vấn đề được mô tả; không ai đo được nó đang tốn bao nhiêu; và không rõ ai sẽ quyết. Nối với lesson 1: phát biểu bài toán sáu phần áp ở đây với thêm chiều tổ chức.",
"Khung ba bài toán thật thành ba trang một, mỗi trang có bằng chứng định lượng cho hiện trạng.",
"Tầng *áp dụng*. Objective đòi bằng chứng chứ ý kiến. Kiểm bằng rà soát chéo; đạt khi cả ba trang có dữ liệu cho hiện trạng và ảnh hưởng, và mỗi trang nêu rõ người quyết định cùng tiêu chí thành công đo được.",
"Chọn ba vấn đề thật từ hệ đã dựng hoặc từ nơi làm việc. Với mỗi cái, thu bằng chứng định lượng cho hiện trạng: số sự cố, giờ công, chi phí, hoặc số đo trải nghiệm. Viết một trang đủ sáu phần. Đổi bài chéo và nhờ người khác tìm chỗ nào là ý kiến chứ dữ liệu. Sửa theo phản hồi.",
"Đặt tên giải pháp trước khi mô tả vấn đề · mô tả hiện trạng bằng cảm nhận · bỏ phi mục tiêu · không nêu ai là người quyết định.",
"Ba trang đều có dữ liệu cho hiện trạng và ảnh hưởng, nêu rõ người quyết định, và có tiêu chí thành công đo được."),

(433,"The RFC with three real options","TH","Lesson 432",
"Bản đề xuất kỹ thuật là hiện vật trung tâm của việc dẫn dắt xuyên đội, và chất lượng của nó quyết định quyết định được đưa ra thế nào. Cấu trúc: bài toán cùng bằng chứng, ba phương án thật gồm cả không làm gì, hệ quả lượng hoá theo cùng bộ tiêu chí, khuyến nghị, kế hoạch triển khai, và điều kiện xem lại. Theo đúng lesson 416, **một phương án thật là phương án sẽ thắng trong một bối cảnh nào đó**; bản đề xuất bán sẵn một công cụ là dấu hiệu hỏng rõ nhất và người đọc nhận ra ngay. Quy trình rà soát: gửi bất đồng bộ trước để người đọc có thời gian, họp đồng bộ chỉ để giải quyết bất đồng, và **ghi lại phản đối kể cả phản đối bị bác**, vì đó là thứ cho phép xem lại quyết định về sau. Quyết định phải ghi ai quyết và quyết vào lúc nào. Ba lý do một bản đề xuất tốt vẫn không dẫn tới thay đổi.",
"Nộp ba bản đề xuất được rà soát thật, trong đó một bản được triển khai và đo sau khi áp dụng.",
"Tầng *đánh giá*. Objective đo cả hiện vật, quá trình dẫn tới quyết định, và kết quả sau khi áp dụng. Kiểm bằng ba bản đề xuất cộng số đo sau áp dụng; đạt khi cả ba được rà soát bởi người ngoài, mọi phản đối được ghi kèm cách xử lý, và bản được triển khai có số đo trước và sau.",
"Từ ba trang khung bài toán ở lesson 432, viết ba bản đề xuất đầy đủ. Gửi mỗi bản cho ít nhất ba người đọc và thu phản hồi bất đồng bộ. Tổ chức một buổi rà soát chỉ để giải quyết bất đồng. Ghi biên bản gồm mọi phản đối, cách xử lý từng phản đối, quyết định và người quyết. **Chọn một bản, triển khai nó, rồi đo kết quả sau khi có người dùng thật**: số đo trước, số đo sau, mức áp dụng, và phần chưa đạt. Viết điều kiện xem lại quyết định cho cả ba.",
"Dựng phương án rơm · bỏ qua phản đối bị bác · họp trước khi người đọc kịp đọc · không ghi ai là người quyết · **coi bản đề xuất được duyệt là kết quả, trong khi kết quả là số đo sau khi có người dùng**.",
"Ba bản đề xuất đều được người ngoài rà soát, mỗi phương án có một bối cảnh mà nó thắng, mọi phản đối được ghi kèm cách xử lý, và bản được triển khai có số đo trước cùng sau khi áp dụng."),

(434,"Architecture decision records for irreversible choices","TH","Lesson 433",
"Bản ghi quyết định kiến trúc là hiện vật rẻ nhất và có giá trị lâu nhất, vì nó giữ lại bối cảnh mà tài liệu kiến trúc không giữ. Mỗi bản ghi gồm: bối cảnh lúc quyết, quyết định, phương án đã cân nhắc, hệ quả cả tốt lẫn xấu, và điều kiện xem lại. Chỉ viết cho quyết định khó đảo ngược theo phân loại ở lesson 416; viết cho mọi thứ làm bộ hồ sơ loãng và không ai đọc. **Giá trị lớn nhất của bản ghi là khi có người hỏi vì sao hồi đó lại chọn thế**, thường sau nhiều năm và người quyết đã đi; không có nó thì đội sau hoặc giữ một quyết định đã hết lý do, hoặc phá một quyết định vẫn còn lý do. Hệ quả xấu phải viết thật: một bản ghi chỉ liệt kê ưu điểm là một bản quảng cáo. Bản ghi bất biến: quyết định đổi thì viết bản mới và đánh dấu bản cũ đã bị thay thế, chứ sửa bản cũ.",
"Viết ba bản ghi cho ba quyết định khó đảo ngược, mỗi bản có hệ quả xấu và điều kiện xem lại.",
"Tầng *áp dụng*. Objective đòi trung thực về hệ quả xấu. Kiểm bằng rà soát chéo; đạt khi cả ba bản có ít nhất hai hệ quả xấu cụ thể và điều kiện xem lại kiểm được, và không bản nào viết cho quyết định dễ đảo.",
"Chọn ba quyết định khó đảo ngược trong hệ đã dựng. Viết bản ghi cho từng cái. Với mỗi bản, liệt kê ít nhất hai hệ quả xấu cụ thể và một điều kiện xem lại có thể kiểm bằng số đo. Đưa cho một người chưa tham gia quyết định và hỏi họ có hiểu vì sao chọn vậy không. Thay thế một bản ghi cũ và giữ bản cũ.",
"Viết bản ghi cho mọi quyết định · chỉ liệt kê ưu điểm · sửa bản ghi cũ khi quyết định đổi · viết điều kiện xem lại mơ hồ không kiểm được.",
"Ba bản ghi có ≥ 2 hệ quả xấu cụ thể và điều kiện xem lại kiểm được bằng số đo, và người chưa tham gia hiểu được lý do chọn."),

(435,"Migration playbook with consumer inventory","TH","Lesson 434",
"Di trú là nơi phần lớn sáng kiến kỹ thuật chết, nên nó có một sổ tay riêng. Năm phần: kiểm kê bên tiêu thụ với chủ sở hữu và mức dùng thật; ma trận tương thích cho từng nhóm bên tiêu thụ; chạy song song có tiêu chí đối soát theo lesson 417; chuyển đổi theo từng phần với đường quay lui; và khai tử có thời hạn cùng theo dõi mức dùng còn lại. **Kiểm kê phải dựa trên dữ liệu sử dụng thật chứ trên trí nhớ**, vì bên tiêu thụ luôn nhiều hơn người ta nghĩ, và những bên không ai nhớ chính là những bên sẽ hỏng. Hỗ trợ bên tiêu thụ là một phần của kế hoạch chứ một việc phát sinh: đường dẫn mẫu, công cụ chuyển đổi, tài liệu, và thời gian của người. Chế độ hỏng đặc trưng về tổ chức: di trú làm quá tải đội dùng, nên họ hoãn, nên hệ cũ sống mãi và ta phải nuôi hai hệ.",
"Lập sổ tay di trú năm phần có kiểm kê từ dữ liệu thật và kế hoạch hỗ trợ bên tiêu thụ.",
"Tầng *áp dụng*. Objective gồm cả chiều tổ chức chứ chỉ kỹ thuật. Kiểm bằng rà soát sổ tay; đạt khi kiểm kê dựa trên dữ liệu sử dụng thật, mọi nhóm bên tiêu thụ có đường chuyển đổi cùng chủ sở hữu, và kế hoạch có ước lượng thời gian của đội dùng.",
"Chọn một thay đổi cần di trú. Lập kiểm kê bên tiêu thụ từ nhật ký truy vấn cùng khai báo theo lesson 265. So với danh sách từ trí nhớ và ghi chênh lệch. Lập ma trận tương thích theo nhóm. Thiết kế chạy song song và chuyển đổi từng phần. Ước lượng thời gian mà mỗi đội dùng phải bỏ ra và lập kế hoạch hỗ trợ. Đặt thời hạn khai tử và cách theo dõi mức dùng còn lại.",
"Kiểm kê bằng trí nhớ · chuyển đổi toàn bộ một lần · không tính thời gian của đội dùng · gỡ hệ cũ theo lịch thay vì theo mức dùng còn lại.",
"Kiểm kê dựa trên dữ liệu sử dụng thật với chênh lệch so với trí nhớ được ghi, mọi nhóm có đường chuyển đổi cùng chủ sở hữu, và kế hoạch có ước lượng thời gian đội dùng."),

(436,"Platform as product - paved road, guardrails, adoption","TH","Lesson 435",
"Nền tảng nội bộ hỏng theo một cách đặc trưng: đúng về kỹ thuật mà không ai dùng. Coi nó như sản phẩm nghĩa là áp lại M11C cho người dùng nội bộ: hành trình người dùng, khả năng tìm thấy, tài liệu, và số đo mức dùng thật. Ba cơ chế: đường dẫn mẫu tức cách làm mặc định đã được bảo đảm sẵn về bảo mật và vận hành; rào chắn tức chốt kiểm soát tự động thay cho việc phê duyệt thủ công; và tự phục vụ để đội nền tảng không thành nút cổ chai. **Rào chắn tốt hơn phê duyệt vì nó mở rộng được và vì nó không phụ thuộc vào một người**; mỗi lần phải xin phép là một lần mất thời gian của cả hai bên. Đo mức áp dụng bằng chỉ số hợp lệ theo lesson 197: tỉ lệ đội dùng đường dẫn mẫu, thời gian tới thay đổi đầu tiên chạy được ở sản xuất, và tỉ lệ việc làm được không cần mở phiếu; số phiếu đã đóng không phải chỉ số.",
"Dựng đường dẫn mẫu có rào chắn và chứng minh **hai kỹ sư hoặc hai đội** đưa được thay đổi lên sản xuất mà không cần tới mình.",
"Tầng *đánh giá*. Objective đo bằng hành vi người dùng nội bộ chứ bằng tính năng đã xây. Kiểm bằng phép thử người; đạt khi **hai người thuộc hai đội khác nhau** đều đưa được thay đổi đầu tiên lên sản xuất trong giới hạn thời gian mà không hỏi mình, và ít nhất ba rào chắn thay được phê duyệt thủ công.",
"Chọn một quy trình mà đội dùng hay phải xin phê duyệt. Dựng đường dẫn mẫu gồm khuôn mẫu, tài liệu và ví dụ chạy được. Thay ít nhất ba điểm phê duyệt thủ công bằng rào chắn tự động. Nhờ hai người thuộc hai đội khác nhau dùng đường dẫn mẫu và bấm giờ tới thay đổi đầu tiên chạy được; đếm số lần họ phải hỏi mình. Đo ba chỉ số mức áp dụng và ghi mọi chỗ họ vấp; mỗi lần phải hỏi là một thiếu sót của tài liệu hoặc của rào chắn, sửa rồi đo lại với người thứ hai.",
"Xây nền tảng rồi chờ người ta tới · đo bằng số phiếu đã đóng · giữ phê duyệt thủ công vì an tâm hơn · không có ví dụ chạy được trong tài liệu.",
"Hai người thuộc hai đội khác nhau đều đưa được thay đổi đầu tiên lên sản xuất trong giới hạn thời gian mà không hỏi mình, ≥ 3 điểm phê duyệt được thay bằng rào chắn, và ba chỉ số mức áp dụng có số đo."),

(437,"Strategy memo - diagnosis, bets, sequence, revisit signals","TH","Lesson 436",
"Hiện vật của bậc cao nhất, và nó khác một bản đề xuất ở chỗ nó nói về nhiều năm và nhiều hệ. Năm phần: bối cảnh, chẩn đoán tức nêu đúng vấn đề cốt lõi chứ liệt kê triệu chứng, nguyên tắc dùng để ra quyết định về sau, các cược tức những chỗ chọn đầu tư và chấp nhận rủi ro, trình tự tức làm gì trước và vì sao, số đo, và rủi ro. **Chiến lược là một tập lựa chọn, nên một bản chiến lược không nói mình sẽ không làm gì thì chưa phải chiến lược**; đó là phép thử nhanh nhất để nhận ra một bản tầm nhìn đội lốt. Tín hiệu xem lại phải viết ra cùng lúc: điều gì xảy ra thì chiến lược này không còn đúng, và ai được quyền khởi động việc xem lại. Chi phí chìm là cái bẫy đặc trưng: chiến lược đã sai vì thị trường hoặc tổ chức đổi mà vẫn tiếp tục vì đã bỏ nhiều công vào.",
"Viết một bản chiến lược có chẩn đoán, có phần không làm, và có tín hiệu xem lại cùng người khởi động.",
"Tầng *đánh giá*. Objective đòi lựa chọn chứ mong muốn. Kiểm bằng rà soát chéo; đạt khi bản chiến lược nêu rõ ít nhất ba việc sẽ không làm, chẩn đoán chỉ ra vấn đề cốt lõi chứ triệu chứng, và tín hiệu xem lại kiểm được kèm người có quyền khởi động.",
"Chọn một phạm vi nhiều hệ. Viết bản chiến lược đủ năm phần. Trong phần các cược, nêu ít nhất ba việc sẽ không làm và lý do. Với mỗi cược, viết một tín hiệu cho biết nó sai kèm cách đo. Ghi ai được quyền khởi động việc xem lại. Đổi bài chéo và nhờ người khác tìm chỗ nào là tầm nhìn chứ lựa chọn.",
"Viết tầm nhìn mà không có lựa chọn · liệt kê triệu chứng thay vì chẩn đoán · không nêu việc sẽ không làm · tín hiệu xem lại mơ hồ không đo được.",
"Bản chiến lược nêu ≥ 3 việc sẽ không làm, chẩn đoán chỉ ra vấn đề cốt lõi, và mỗi cược có tín hiệu xem lại đo được cùng người khởi động."),

(438,"Influence, review and the bottleneck anti-pattern","LT","Lesson 437",
"Bài về phần mà hiện vật không làm thay được. Ảnh hưởng không có thẩm quyền dựa trên ba thứ: bằng chứng, việc hiểu động cơ của người khác, và độ tin cậy tích luỹ từ những lần dự đoán đúng. Bất đồng nên được nêu ra chứ tránh; **giấu bất đồng và rủi ro làm quyết định trông đồng thuận rồi vỡ khi triển khai**. Hệ thống rà soát thiết kế cần thiết kế có chủ ý: ai rà cái gì, rà để làm gì, và làm sao rà soát không thành một cửa phê duyệt. Ba mẫu hỏng đặc trưng của bậc cao: trở thành nút cổ chai vì mọi thứ phải qua mình; giữ bối cảnh cho riêng mình nên đội không tự quyết được; và đi giải cứu các đội thay vì làm cho họ tự làm được. **Phép thử của mức đòn bẩy: sau khi mình rời đi, hai đội có tiếp tục làm đúng không**, nhờ giao diện, tài liệu và rào chắn tốt hơn chứ nhờ trí nhớ của ai đó.",
"Nhận ra ba mẫu hỏng trong tình huống thật và thiết kế một hệ thống rà soát không thành cửa phê duyệt.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho bài hồ sơ bằng chứng. Kiểm bằng bài phân tích ba tình huống cộng một thiết kế; đạt khi nhận đúng mẫu hỏng ở ít nhất hai tình huống và hệ thống rà soát nêu rõ cách nó không thành nút cổ chai.",
"Cho ba tình huống về một người dẫn dắt kỹ thuật; nhận ra mẫu hỏng trong từng cái và đề xuất cách đổi. Thiết kế một hệ thống rà soát thiết kế cho một tổ chức giả định: ai rà cái gì, tiêu chí nào cần rà và tiêu chí nào để rào chắn tự động lo. Áp phép thử mức đòn bẩy vào công việc của chính mình và chỉ ra chỗ mình đang là nút cổ chai.",
"Coi mọi thứ phải qua mình là trách nhiệm · giấu bất đồng để họp trôi chảy · giải cứu đội khác thay vì cải thiện giao diện · đo ảnh hưởng bằng số buổi rà soát đã tham gia.",
"Nhận đúng mẫu hỏng ở ≥ 2/3 tình huống, hệ thống rà soát nêu rõ cách tránh thành nút cổ chai, và phép thử mức đòn bẩy được áp vào công việc của chính mình."),

(439,"The evidence dossier - baseline, decision, outcome, limits","TH","Lesson 438",
"Bài gom toàn bộ hiện vật thành một hồ sơ bằng chứng dùng được khi ứng tuyển hoặc khi đề nghị thăng cấp. Ba sáng kiến trong hồ sơ không được chọn tuỳ ý: hợp đồng nguồn chỉ định hai loại bắt buộc, vì chúng là hai loại bằng chứng khó nguỵ tạo nhất. **Một là cắt chi phí hoặc cải thiện một cam kết dịch vụ có số đo**, kèm đánh đổi đã chấp nhận, vì nó buộc phải có đường cơ sở trước khi làm. **Hai là dẫn một buổi diễn tập sự cố và một phân tích sau sự cố xuyên ít nhất hai thành phần thuộc hai đội**, kèm bằng chứng hành động sau đó làm giảm tái diễn, vì nó buộc phải phối hợp ngoài phạm vi của mình. Sáng kiến thứ ba tự chọn. Mỗi mục có năm phần: đường cơ sở trước khi làm, quyết định cùng lý do, việc triển khai cùng mức áp dụng, kết quả đo được, và **giới hạn của lập luận nhân quả**; phần cuối là phần hiếm ai viết và là phần làm hồ sơ đáng tin: kết quả tốt có thể do nhiều nguyên nhân, và nói rõ điều đó mạnh hơn là tuyên bố chắc chắn. Ranh giới bằng chứng giữ nghiêm theo lesson 431. Cùng một sáng kiến trình bày cho ba nhóm người khác nhau: ban lãnh đạo cần phương án, mức rủi ro và kinh tế; kỹ sư cần đánh đổi kỹ thuật; người vận hành cần thay đổi trong công việc hằng ngày. **Ba bản trình bày khác về chi tiết nhưng không được khác về sự thật**, và đây là ranh giới đạo đức của bài.",
"Lập hồ sơ năm phần cho ba sáng kiến, trong đó bắt buộc có một sáng kiến về chi phí hoặc cam kết dịch vụ và một buổi diễn tập xuyên hai thành phần, rồi trình bày một sáng kiến cho ba nhóm người.",
"Tầng *đánh giá*. Objective đòi trung thực về giới hạn nhân quả. Kiểm bằng rà soát hồ sơ cộng ba lần trình bày; đạt khi hai loại sáng kiến bắt buộc đều có mặt kèm số đo trước và sau, mọi mục có giới hạn nhân quả nêu rõ, và ba bản trình bày nhất quán về sự thật khi đối chiếu.",
"Thực hiện sáng kiến bắt buộc thứ nhất: đo đường cơ sở, cắt chi phí hoặc cải thiện một cam kết dịch vụ, đo lại, và báo cáo đánh đổi đã chấp nhận. Thực hiện sáng kiến bắt buộc thứ hai: dẫn một buổi diễn tập sự cố xuyên hai thành phần thuộc hai đội, viết phân tích sau sự cố, rồi theo dõi xem hành động có làm giảm tái diễn không. Lập hồ sơ cho ba sáng kiến, mỗi cái đủ năm phần. Với mỗi kết quả, nêu ít nhất hai cách giải thích khác. Chọn một sáng kiến và chuẩn bị ba bản trình bày: mười phút cho ban lãnh đạo, sáu mươi phút cho kỹ sư, và một bản hướng dẫn cho người vận hành. Trình bày cả ba và nhờ người nghe đối chiếu xem có mâu thuẫn không.",
"Tuyên bố nhân quả từ một tương quan · **đo sau khi làm mà không có đường cơ sở trước khi làm** · diễn tập trong phạm vi một đội rồi gọi là xuyên đội · giấu phần không thành công · đổi sự thật khi đổi người nghe · gộp bằng chứng lab vào phần kết quả sản xuất.",
"Hai loại sáng kiến bắt buộc đều có mặt với số đo trước và sau, mọi mục có giới hạn nhân quả nêu rõ cùng ít nhất hai cách giải thích khác, và ba bản trình bày được đối chiếu không có mâu thuẫn về sự thật."),

(440,"Graduation defence - one design, three audiences","KT","Lesson 439",
"Bài bảo vệ tốt nghiệp của toàn chương trình. Không có nội dung mới; nó kiểm năng lực tổng hợp trên chính hồ sơ thiết kế đã làm ở lesson 420 cùng hồ sơ bằng chứng ở lesson 439.",
"Bảo vệ một thiết kế đầu cuối trước ba nhóm người nghe, chịu được bốn ràng buộc đổi, và phân tách trung thực ba loại bằng chứng.",
"Tầng *đánh giá*. Bài bảo vệ cuối cùng, đo năng lực thiết kế, năng lực truyền đạt và tính trung thực về bằng chứng.",
"Buổi 180 phút: 135 phút bảo vệ và chất vấn, 45 phút hội đồng nghị án và phản hồi. Hội đồng ba người. Bài chấm sáu phần: A (20đ) trình bày hồ sơ thiết kế, mọi thành phần truy được về một yêu cầu hoặc bảo đảm · B (20đ) bảo vệ bảng năng lực và bảng chế độ hỏng, chỉ ra nút thắt đầu tiên cùng hệ quả với dữ liệu · C (20đ) bốn ràng buộc đổi do hội đồng đưa ra; điều chỉnh đúng phần bị ảnh hưởng kèm chi phí · D (15đ) trình kế hoạch di trú có kiểm kê bên tiêu thụ, chạy song song và quay lui · E (15đ) cùng một sáng kiến trình bày mười phút cho ban lãnh đạo và mười phút cho người vận hành; hội đồng đối chiếu tính nhất quán · F (10đ) hồ sơ bằng chứng, phân tách ba loại và nêu giới hạn nhân quả.",
"Bảo vệ quyết định cũ vì đã bỏ công vào nó · đổi sự thật khi đổi người nghe · tuyên bố tác động sản xuất từ bằng chứng lab · trình thiết kế có thành phần không gắn với yêu cầu nào.",
"Đạt ≥ 70/100, phần A và C đều ≥ 60%. Hai bản trình bày ở phần E mâu thuẫn về sự thật thì phần đó bằng không; gộp bằng chứng lab vào phần tác động sản xuất thì phần F bằng không."),
]
