# -*- coding: utf-8 -*-
"""ADE Phase 2: M4 Computer architecture + M5 OS/concurrency/Linux + M6 Networking."""

M4 = ("Computer Architecture and the Performance Model", 45, 60, """| | |
|---|---|
| **Objective cấp module** | Dự đoán rồi đo được chi phí từ tầng lệnh, bộ nhớ đệm, RAM và thiết bị lưu trữ, và dùng mô hình đó giải thích hành vi của cơ sở dữ liệu, engine phân tán và dịch vụ |
| **Tiền đề** | M3 |
| **Exit criterion** | Vẽ được đường đi của một phép đọc và một phép ghi từ ứng dụng tới CPU, bộ nhớ đệm, RAM, bộ đệm trang và thiết bị; phân loại đúng SISD, SIMD và MIMD và giải thích SPMD chạy trên nền MIMD; dùng số đo tìm trần tính toán, bộ nhớ đệm, băng thông, đồng bộ hay mạng trước khi thêm làn, lõi hoặc nút |
| **Kỹ năng SFIA** | `HPCC` mức 3 · `SYSP` mức 3 |
| **Chế độ hỏng** | Học thông số phần cứng như kiến thức rời, rồi không nối được với việc vì sao một truy vấn chậm hay vì sao thêm luồng không tăng thông lượng |""",
"""Module này là nền của mọi lập luận hiệu năng trong chương trình. Bốn kết luận ở đây được dùng lại liên tục: tuần tự rẻ hơn ngẫu nhiên nhiều bậc, bố trí theo cột thắng vì tính cục bộ, bền vững tốn tiền vì `fsync`, và thêm luồng chỉ giúp khi nút thắt là chờ chứ tính.

Mọi khẳng định trong module phải kèm số đo của chính người học, theo đúng kỷ luật đã đặt ở lesson 21 và 33.""")

L4 = [
(45,"The memory hierarchy and the cost model","LT","Module 4: M3",
"Một phép truy cập dữ liệu có thể tốn một nhịp đồng hồ hoặc tốn rất nhiều nhịp, tuỳ dữ liệu đang nằm ở đâu; khoảng cách giữa các bậc là nhiều bậc độ lớn chứ vài phần trăm, và con số của từng bậc do phần cứng quyết định nên bài này đo chứ tra bảng, và khoảng cách đó là thứ giải thích gần như mọi hiện tượng hiệu năng. Thứ bậc từ nhanh tới chậm: thanh ghi, ba mức bộ nhớ đệm, RAM, đĩa thể rắn, đĩa quay, mạng. Mỗi bậc chậm hơn bậc trên khoảng một tới ba bậc độ lớn, và dung lượng thì ngược lại. Bộ số mốc cần thuộc để ước lượng mà không tra: truy cập bộ nhớ đệm mức một, truy cập RAM, đọc ngẫu nhiên trên đĩa thể rắn, đọc tuần tự một megabyte, và một vòng mạng trong trung tâm dữ liệu. Ba loại nút thắt và cách phân biệt bằng số đo chứ bằng cảm nhận: nghẽn CPU, nghẽn băng thông bộ nhớ, và nghẽn vào ra. **Xác định sai loại nút thắt thì mọi tối ưu sau đó đều đi sai hướng**, và đây là lỗi tốn kém nhất trong cả chương trình.",
"Phân loại nút thắt của một chương trình cho trước vào đúng một trong ba loại, dẫn bằng số đo chứ bằng phỏng đoán.",
"Tầng *phân tích*. Bài mở module, người học đã biết đo từ lesson 21 nên đủ nền để phân loại. Kiểm bằng ba chương trình có ba loại nút thắt khác nhau; đạt khi phân loại đúng cả ba và mỗi lần dẫn được một số đo cụ thể.",
"Cho ba chương trình, mỗi cái nghẽn ở một tầng khác nhau. Với mỗi cái, đo mức dùng CPU, băng thông bộ nhớ và thời gian chờ vào ra, rồi phân loại nút thắt. Viết bộ số mốc từ chính máy của mình bằng cách đo, không chép từ tài liệu.",
"Kết luận nghẽn CPU vì thấy CPU cao trong khi thực ra là chờ bộ nhớ · tối ưu thuật toán khi nút thắt là đĩa · dùng số mốc của máy khác.",
"Phân loại đúng cả ba nút thắt kèm số đo, và có bộ số mốc đo trên chính máy mình."),

(46,"Cache lines, locality and the cache cliff","TH","Lesson 45",
"Bộ nhớ đệm không nạp từng byte mà nạp cả một dòng, thường 64 byte, nên đọc một byte thì 63 byte lân cận được nạp theo miễn phí. Từ một sự thật đó suy ra toàn bộ khái niệm tính cục bộ: cục bộ theo không gian là dùng dữ liệu nằm gần nhau, cục bộ theo thời gian là dùng lại dữ liệu vừa dùng. Hệ quả đo được và gây bất ngờ: duyệt một mảng theo thứ tự nhanh hơn duyệt ngẫu nhiên nhiều lần dù cùng số phép đọc. **Con số cụ thể phụ thuộc phần cứng nên nó là giả thuyết phải tự đo ở lab bài này, không phải một hằng số nhớ được**; phần phải giải thích là vì sao có chênh lệch, không phải chênh lệch bằng mấy. Vách bộ nhớ đệm là hiện tượng tốc độ tụt đột ngột khi dữ liệu vượt dung lượng một mức đệm, và đo được thành một đồ thị có bậc rõ ràng. Chia sẻ giả: hai luồng ghi hai biến khác nhau nhưng nằm cùng một dòng đệm thì chúng tranh nhau và chậm hơn chạy tuần tự; đây là lỗi hiệu năng khó đoán nhất trong lập trình đa luồng. Nối tới M12: engine cột nhanh vì khai thác đúng tính cục bộ này.",
"Đo được vách bộ nhớ đệm trên máy của mình và suy ra dung lượng các mức đệm từ đồ thị.",
"Tầng *phân tích*. Objective đòi suy đặc tính phần cứng từ dữ liệu đo, chứ đọc thông số. Kiểm bằng đồ thị quét kích thước; đạt khi đồ thị có bậc rõ và dung lượng suy ra gần đúng với thông số thật.",
"Viết phép đo duyệt mảng với bước nhảy thay đổi, quét kích thước dữ liệu từ 4 KB tới 256 MB. Vẽ đồ thị thời gian trên mỗi phần tử và chỉ ra các bậc. So thông số suy ra với thông số thật của máy. Tái hiện chia sẻ giả với hai luồng và đo mức chậm đi, rồi sửa bằng cách chèn đệm.",
"Đo với dữ liệu nhỏ hơn bộ nhớ đệm nên không thấy bậc nào · quên hâm nóng trước khi đo · kết luận chia sẻ giả mà không đo bản đã chèn đệm.",
"Đồ thị có bậc rõ ràng, dung lượng suy ra cùng bậc với thông số thật, và bản sửa chia sẻ giả nhanh hơn có số chứng minh."),

(47,"Row-major against column-major layout","TH","Lesson 46",
"Cùng một bảng dữ liệu, hai cách xếp trong bộ nhớ, và chênh lệch tốc độ cho phép gộp thường lớn tới mức đổi cả quyết định thiết kế. Mức chênh cụ thể phụ thuộc số cột, kiểu dữ liệu và kích thước bộ nhớ đệm, nên nó được đo ở lab chứ nêu sẵn. Xếp theo dòng gom mọi trường của một bản ghi cạnh nhau; xếp theo cột gom mọi giá trị của một trường cạnh nhau. Khi tính tổng một cột trên bảng 40 cột: bố trí theo dòng phải nạp cả 40 cột vào đệm dù chỉ dùng một, nên 39 phần bốn mươi băng thông bị lãng phí; bố trí theo cột chỉ nạp phần cần. **Đây là lý do vật lý của mọi engine phân tích cột** và là bài học sẽ dùng lại nguyên vẹn ở M12 và M13. Chiều ngược lại cũng đúng và phải nói rõ: đọc nguyên một bản ghi thì bố trí theo dòng thắng, nên hệ giao dịch dùng dòng. Thực thi theo lô và theo véc tơ: xử lý một khối giá trị cùng kiểu một lần cho phép dùng lệnh song song của CPU, và đó là tầng tăng tốc thứ hai sau tính cục bộ.",
"Đo chênh lệch giữa hai bố trí trên cùng phép gộp và giải thích bằng tỉ lệ băng thông bị lãng phí.",
"Tầng *phân tích*. Objective đòi quy chênh lệch đo được về cơ chế nạp dòng đệm. Kiểm bằng bảng đo hai bố trí nhân hai loại truy vấn; đạt khi cả bốn ô có số và giải thích đúng chiều đảo ngược ở truy vấn đọc cả bản ghi.",
"Dựng cùng dữ liệu 40 cột ở hai bố trí. Chạy hai truy vấn: tính tổng một cột, và đọc nguyên 100 bản ghi. Đo cả bốn ô. Tính tỉ lệ băng thông lãng phí của bố trí theo dòng ở truy vấn thứ nhất và so với chênh lệch thời gian đo được.",
"Kết luận bố trí cột luôn nhanh hơn · so hai bố trí ở hai kích thước dữ liệu khác nhau · bỏ qua truy vấn đọc cả bản ghi nên không thấy chiều ngược.",
"Bảng bốn ô đủ số đo, tỉ lệ băng thông lãng phí giải thích được chênh lệch, và chiều đảo ngược ở truy vấn thứ hai được chỉ ra."),

(48,"Flynn taxonomy - SISD, SIMD, MIMD and where SPMD fits","LT","Lesson 47",
"Bài đặt từ vựng chính xác cho toàn bộ phần song song, vì bốn từ dưới đây bị dùng lẫn thường xuyên và dùng lẫn thì không bàn được thiết kế. Phân loại theo hai trục là số dòng lệnh và số dòng dữ liệu: một lệnh một dữ liệu là mô hình tuần tự cổ điển; một lệnh nhiều dữ liệu áp cùng phép toán lên nhiều phần tử trong một dòng lệnh; nhiều lệnh nhiều dữ liệu cho mỗi lõi hoặc mỗi nút một bộ đếm chương trình riêng nên chúng chạy mã khác nhau được; nhiều lệnh một dữ liệu chỉ cần biết là có. Bốn khái niệm phải tách và đây là điểm ra của bài: **một lệnh nhiều dữ liệu, nhiều lệnh nhiều dữ liệu, đồng thời, và song song không phải bốn tên của một thứ**; đồng thời là nhiều việc chồng lấn theo thời gian, song song là nhiều việc chạy thật sự cùng lúc. Một chương trình nhiều dữ liệu là khuôn mẫu lập trình: cùng một chương trình chạy trên nhiều tiến trình với phân vùng dữ liệu khác nhau, và nó thường được triển khai trên nền nhiều lệnh nhiều dữ liệu.",
"Phân loại đúng bốn khái niệm cho một tập hệ thống thật và giải thích quan hệ giữa một chương trình nhiều dữ liệu với nền nhiều lệnh nhiều dữ liệu.",
"Tầng *hiểu*. Bài lý thuyết đặt từ vựng cho năm bài sau; chưa đo gì. Kiểm bằng bài phân loại tám hệ thống; đạt khi phân đúng ít nhất sáu và giải thích được hai ca nằm ở nhiều tầng cùng lúc.",
"Cho tám hệ thống hoặc đoạn mã thật, gồm một vòng lặp véctơ hoá, một bể luồng, một cụm xử lý phân tán, và một engine phân tích. Phân loại từng cái theo bốn khái niệm. Với hai ca có nhiều tầng song song lồng nhau, mô tả từng tầng. Viết một đoạn phân biệt đồng thời với song song bằng một ví dụ của chính mình.",
"Gọi mọi thứ chạy nhanh là một lệnh nhiều dữ liệu · dùng đồng thời và song song thay nhau · nghĩ một chương trình nhiều dữ liệu là một kiến trúc phần cứng · bỏ qua việc một hệ có thể thuộc nhiều tầng cùng lúc.",
"Phân đúng ≥ 6/8 hệ thống, và hai ca song song lồng nhau được mô tả đủ từng tầng."),

(49,"SIMD from lane to operator - width, mask, tail and gather","TH","Lesson 48",
"Bài đi vào cơ chế của một lệnh nhiều dữ liệu ở mức đủ để giải thích hiệu năng, chứ mức viết mã máy. Lệnh vô hướng xử lý một giá trị, lệnh véctơ áp cùng phép toán lên nhiều làn; số làn bằng độ rộng thanh ghi véctơ chia độ rộng phần tử, nên cùng một thanh ghi cho tám làn số thực 32 bit hoặc bốn làn 64 bit. Phần đuôi khi số phần tử không chia hết cho số làn phải xử lý bằng vòng lặp vô hướng hoặc bằng mặt nạ. Dữ liệu liền kề và căn chỉnh làm việc nạp rẻ; **thu thập rải rác và đuổi theo con trỏ thường đắt hơn nhiều và là lý do chính làm tăng tốc thấp hơn kỳ vọng**. Rẽ nhánh trong vòng lặp được chuyển thành mặt nạ hoặc véctơ chọn lọc khi có lợi, nhưng bỏ rẽ nhánh không mặc định nhanh hơn vì nó tính cả hai nhánh. Sáu chế độ hỏng: phụ thuộc vòng lặp, lô quá nhỏ, rẽ nhánh phân kỳ, đường thu thập nhiều giá trị rỗng, bão hoà băng thông bộ nhớ, và cấp phát quá mức.",
"Đo phần tăng tốc thật của một vòng lặp véctơ hoá và quy mức tăng tốc thấp về đúng một trong sáu chế độ hỏng.",
"Tầng *phân tích*. Objective đòi giải thích một con số chứ chỉ tạo ra nó. Kiểm bằng ba vòng lặp có đặc trưng khác nhau; đạt khi mỗi vòng lặp có số đo kèm bộ đếm phần cứng và mức tăng tốc thấp được quy đúng nguyên nhân ở ít nhất hai.",
"Viết cùng một phép tính ở ba dạng: vô hướng, để trình biên dịch tự véctơ hoá, và dùng thư viện đã véctơ hoá. Đo thời gian cùng bộ đếm gồm số chu kỳ, số lệnh, lỗi bộ nhớ đệm và băng thông; tính số chu kỳ trên mỗi dòng. Chạy lại với ba biến thể dữ liệu: liền kề, rải rác cần thu thập, và nhiều giá trị rỗng. Quy mỗi lần tăng tốc thấp về một trong sáu chế độ hỏng.",
"Kết luận từ một số đo thời gian duy nhất · dùng lô quá nhỏ rồi kết luận véctơ hoá vô dụng · so hai bản mà không kiểm kết quả giống nhau · viết mã đặc thù tập lệnh trước khi đo.",
"Ba dạng đều có số đo kèm bộ đếm phần cứng và số chu kỳ trên mỗi dòng, và ≥ 2 lần tăng tốc thấp được quy đúng chế độ hỏng."),

(50,"Auto-vectorization - when the compiler gives up","TH","Lesson 49",
"Trình biên dịch véctơ hoá giúp được nhiều, nhưng nó bỏ cuộc trong im lặng, nên biết nó có làm hay không là kỹ năng đo lường. Điều kiện để nó làm được: không có phụ thuộc mang qua vòng lặp, không có khả năng hai con trỏ trỏ chồng nhau, số vòng lặp biết được hoặc xử lý được phần đuôi, và thân vòng lặp không gọi hàm không nội tuyến được. Báo cáo tối ưu hoá của trình biên dịch nói rõ nó véctơ hoá chỗ nào và từ chối chỗ nào kèm lý do; đọc báo cáo rẻ hơn nhiều so với đoán. Đọc mã máy ở mức nhận ra lệnh véctơ là đủ, không cần viết được. **Mã dùng lệnh đặc thù tập lệnh chỉ viết sau khi đã đo và đã thử cách đơn giản**, vì nó kéo theo chi phí về khả năng mang đi, về hạ xung nhịp, và về bảo trì; với phần lớn công việc dữ liệu, dùng thư viện hoặc engine đã véctơ hoá là lựa chọn đúng. Ba cách viết lại vòng lặp để trình biên dịch làm được.",
"Làm cho ba vòng lặp bị từ chối véctơ hoá trở nên véctơ hoá được, chứng minh bằng báo cáo và bằng số đo.",
"Tầng *áp dụng*. Objective có bằng chứng hai lớp là báo cáo trình biên dịch và số đo thời gian. Kiểm bằng ba vòng lặp; đạt khi cả ba chuyển từ bị từ chối sang được véctơ hoá với kết quả tính không đổi.",
"Viết ba vòng lặp bị từ chối vì ba lý do khác nhau. Bật báo cáo tối ưu hoá và ghi lại lý do từ chối của từng cái. Viết lại từng vòng lặp để gỡ nguyên nhân. Xác nhận trong báo cáo và trong mã máy sinh ra rằng nó đã dùng lệnh véctơ. Đo thời gian trước sau và đối chiếu kết quả tính để chứng minh không đổi.",
"Đoán trình biên dịch có véctơ hoá hay không · viết lệnh đặc thù tập lệnh trước khi đọc báo cáo · sửa vòng lặp mà không kiểm kết quả giữ nguyên · dùng cờ tối ưu hoá làm đổi ngữ nghĩa số thực mà không nói rõ.",
"Ba vòng lặp chuyển từ bị từ chối sang được véctơ hoá theo báo cáo, có số đo trước sau, và kết quả tính không đổi."),

(51,"Virtual memory, page faults and mmap","LT","Lesson 50",
"Chương trình nhìn thấy không gian địa chỉ liên tục của riêng nó, còn bộ nhớ vật lý thì không; ánh xạ giữa hai thứ là bộ nhớ ảo, và nó giải thích nhiều hiện tượng vận hành. Trang là đơn vị ánh xạ, bảng trang giữ ánh xạ, và bộ đệm ánh xạ giữ những mục gần đây để tra nhanh. Lỗi trang nhẹ là trang đã trong RAM nhưng chưa ánh xạ, rẻ; lỗi trang nặng là phải đọc từ đĩa, đắt gấp nhiều bậc, và **tỉ lệ lỗi trang nặng là chỉ số chẩn đoán quan trọng mà nhiều người bỏ qua**. Vùng hoán đổi và vì sao một máy bắt đầu hoán đổi thì mọi thứ chậm thảm hại chứ chậm dần. Sao chép khi ghi làm việc tạo tiến trình con rẻ, và đây là cơ chế đứng sau chi phí khởi động tiến trình đã đo ở lesson 23. Ánh xạ tệp vào bộ nhớ cho phép đọc tệp như đọc mảng, tiện nhưng giấu mất chi phí vào ra nên khó đo.",
"Phân biệt lỗi trang nhẹ với lỗi trang nặng bằng số đo, và nhận ra dấu hiệu một tiến trình đang hoán đổi.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho phần chẩn đoán ở M5; chưa đòi xử lý sự cố. Kiểm bằng bài đo cộng nhận dạng; đạt khi phân biệt đúng hai loại lỗi trang và nhận ra đúng trạng thái hoán đổi qua số đo.",
"Viết chương trình cấp phát dần bộ nhớ vượt RAM khả dụng. Đo số lỗi trang nhẹ và nặng theo thời gian. Ghi lại thời điểm máy bắt đầu hoán đổi và mức chậm đi. Chạy một chương trình tạo tiến trình con và đo chi phí, giải thích bằng sao chép khi ghi.",
"Nhầm lỗi trang nhẹ với nặng nên hoảng nhầm · tăng bộ nhớ khi nguyên nhân là ánh xạ tệp · bỏ qua tỉ lệ lỗi trang nặng khi chẩn đoán chậm.",
"Phân biệt đúng hai loại lỗi trang bằng số đo, và chỉ ra đúng thời điểm bắt đầu hoán đổi kèm mức chậm đi."),

(52,"Storage - sequential against random, and the device model","TH","Lesson 51",
"Đĩa quay và đĩa thể rắn khác nhau về cơ chế nên khác nhau về hình dạng chi phí, và biết khác biệt đó quyết định nhiều thiết kế. Đĩa quay phải quay và dịch đầu đọc nên đọc ngẫu nhiên đắt hơn tuần tự nhiều bậc độ lớn; tỉ số cụ thể do tốc độ quay và thời gian dịch đầu đọc của từng thiết bị quyết định, và lab bài này đo trên thiết bị đang có. Đĩa thể rắn không có bộ phận cơ nên đọc ngẫu nhiên rẻ hơn nhiều, nhưng vẫn có ba đặc tính phải biết: đơn vị đọc là trang còn đơn vị xoá là khối lớn hơn nhiều, nên ghi đè sinh ra khuếch đại ghi; hiệu năng phụ thuộc độ sâu hàng đợi nên một luồng không khai thác hết; và ghi liên tục lâu dài làm tốc độ tụt khi bộ gom rác bên trong phải chạy. Ba đại lượng đo khác nhau và hay bị gộp: số thao tác mỗi giây, thông lượng byte, và độ trễ; một thiết bị có thể tốt ở đại lượng này và tệ ở đại lượng kia. Nối tới M13: đây là lý do tệp nhỏ đắt và tệp lớn rẻ trên kho đối tượng.",
"Đo được ba đại lượng của thiết bị lưu trữ và chỉ ra chênh lệch giữa đọc tuần tự với đọc ngẫu nhiên trên chính máy mình.",
"Tầng *áp dụng*. Objective là một phép đo theo quy trình cộng đọc kết quả đúng. Kiểm bằng bảng đo bốn cấu hình; đạt khi cả ba đại lượng có số và chênh lệch tuần tự so với ngẫu nhiên đúng chiều.",
"Đo đọc tuần tự và đọc ngẫu nhiên ở hai độ sâu hàng đợi, ghi cả ba đại lượng cho mỗi cấu hình. Tính tỉ lệ chênh lệch. Chạy ghi liên tục 10 phút và vẽ tốc độ theo thời gian để quan sát mức tụt. So kết quả với thông số nhà sản xuất công bố.",
"Đo với tệp nhỏ hơn bộ đệm trang nên chỉ đo RAM · đo ở một độ sâu hàng đợi rồi kết luận · gộp ba đại lượng làm một · tin thông số nhà sản xuất mà không đo.",
"Bảng bốn cấu hình đủ ba đại lượng, chênh lệch tuần tự so với ngẫu nhiên đúng chiều, và đồ thị ghi liên tục cho thấy mức tụt."),

(53,"Buffering, page cache and fsync","TH","Lesson 52",
"Giữa lệnh ghi của chương trình và byte nằm trên đĩa có ít nhất ba tầng đệm, và không biết tầng nào đã qua thì không biết dữ liệu có sống sót khi mất điện hay không. Đệm của thư viện, bộ đệm trang của nhân, và bộ đệm của chính thiết bị. Lệnh ghi thường chỉ chép vào bộ đệm trang rồi trả về ngay, nên **ghi xong không có nghĩa là dữ liệu đã bền**. `fsync` buộc nhân đẩy xuống thiết bị và chờ xác nhận, và đó là lý do nó chậm hơn ghi thường nhiều bậc. Ba mức cam kết bền vững và giá của từng mức, đo được thành số. Đây chính là cơ chế đứng sau nhật ký ghi trước ở M10 và sau tham số xác nhận của hệ truyền thông điệp: mọi hệ hứa không mất dữ liệu đều phải trả giá `fsync` ở đâu đó. Bộ đệm trang cũng giải thích vì sao lần đo thứ hai luôn nhanh hơn lần đầu, một cái bẫy đã nêu ở lesson 33.",
"Đo được cái giá của `fsync` và phát biểu chính xác mức cam kết bền vững của ba cấu hình ghi.",
"Tầng *phân tích*. Objective đòi nối một tham số cấu hình với một cam kết ngữ nghĩa và một con số. Kiểm bằng bảng ba cấu hình cộng thí nghiệm mất điện mô phỏng; đạt khi ba mức cam kết được phát biểu đúng và số đo đúng chiều.",
"Ghi 100.000 bản ghi ở ba cấu hình: ghi đệm, ghi đệm rồi đẩy một lần cuối, và gọi `fsync` sau mỗi bản ghi. Đo thông lượng từng cấu hình. Mô phỏng mất điện bằng cách giết tiến trình cứng và đếm số bản ghi còn lại ở mỗi cấu hình. Lập bảng ba cột.",
"Tin rằng ghi xong là dữ liệu đã bền · gọi `fsync` sau mỗi bản ghi rồi thắc mắc vì sao chậm · đo lần hai mà quên bộ đệm trang đã ấm.",
"Bảng ba cấu hình có cả thông lượng lẫn số bản ghi sống sót, và ba mức cam kết bền vững được phát biểu đúng."),

(54,"The kernel boundary - syscalls and context switches","TH","Lesson 53",
"Mỗi lần chương trình cần nhân làm gì đó thì phải vượt ranh giới người dùng và nhân, và mỗi lần vượt tốn chi phí cố định. Hệ quả thực tế lớn hơn người ta tưởng: đọc một tệp bằng một triệu lời gọi mỗi lần một byte chậm hơn nhiều bậc độ lớn so với đọc theo khối lớn, dù cùng tổng số byte. Kích thước khối tốt nhất và mức chênh đều phụ thuộc hệ điều hành cùng thiết bị, nên lab đo bốn kích thước khối rồi tự tìm điểm bão hoà. Đây là lý do mọi thư viện vào ra đều có đệm, và là lý do xử lý theo lô luôn thắng xử lý từng phần tử khi có ranh giới nhân ở giữa. Chuyển ngữ cảnh khi nhân đổi tiến trình đang chạy: tốn vì phải lưu và khôi phục trạng thái, và tốn thêm vì bộ nhớ đệm bị làm nguội. Từ đó suy ra vì sao chạy quá nhiều luồng so với số lõi làm thông lượng giảm chứ tăng. Cách đo số lời gọi hệ thống và số lần chuyển ngữ cảnh của một chương trình thật, và dùng hai số đó làm bằng chứng thay vì suy đoán.",
"Đo số lời gọi hệ thống của một chương trình và giảm nó bằng cách gộp lô, chứng minh bằng số đo thời gian.",
"Tầng *áp dụng*. Objective là một tối ưu có cơ chế rõ và kết quả đo được hai chiều. Kiểm bằng cặp số đo lời gọi và thời gian; đạt khi số lời gọi giảm ít nhất một bậc và thời gian giảm tương ứng.",
"Viết chương trình đọc tệp 500 MB theo từng byte, đếm số lời gọi hệ thống và đo thời gian. Viết lại theo khối 64 KB và đo lại cả hai. Chạy một tác vụ tính với số luồng bằng 1, bằng số lõi và gấp 8 lần số lõi; đo thông lượng và số lần chuyển ngữ cảnh.",
"Tối ưu thuật toán khi nút thắt là số lời gọi hệ thống · tăng số luồng cho tới khi máy chậm lại · đo thời gian mà không đếm lời gọi nên không biết nguyên nhân.",
"Số lời gọi hệ thống giảm ≥ 1 bậc sau khi gộp lô với thời gian giảm tương ứng, và bảng ba mức luồng cho thấy điểm quá tải."),

(55,"Amdahl, Gustafson and why adding threads stops helping","LT","Lesson 54",
"Bài này trả lời một câu hỏi vận hành gặp liên tục: đã tăng số luồng mà thông lượng không tăng, vì sao. Bốn nguyên nhân và cách phân biệt bằng số đo. Một là nút thắt vốn không phải CPU: nếu đang chờ đĩa hoặc mạng thì thêm luồng tính không giúp gì, theo phân loại ở lesson 45. Hai là đã bão hoà lõi: vượt số lõi thì chỉ thêm chuyển ngữ cảnh, theo lesson 54. Ba là tranh khoá: các luồng chờ nhau ở vùng tranh chấp nên phần chạy song song thật nhỏ hơn nhiều so với số luồng. Bốn là bão hoà băng thông bộ nhớ: mọi luồng cùng kéo dữ liệu từ RAM và kênh bộ nhớ đầy, một nguyên nhân hay bị bỏ sót vì CPU vẫn hiện là bận. Định luật Amdahl ở mức dùng được: **phần không song song hoá được đặt trần cho toàn bộ nỗ lực thêm lõi**, và ước lượng được phần đó từ số đo. Góc nhìn đối lập cũng phải biết: khi bài toán lớn lên theo số lõi thì phần tuần tự chiếm tỉ lệ nhỏ dần, nên trần của định luật Amdahl áp cho bài toán cố định kích thước chứ mọi bài toán. Hai chỉ số phải báo cùng nhau là tăng tốc và hiệu suất song song, vì tăng tốc 4 lần trên 16 lõi là một kết quả kém mà con số tăng tốc không nói ra.",
"Chẩn đoán một chương trình không tăng tốc khi thêm luồng về đúng một trong bốn nguyên nhân, dẫn bằng số đo.",
"Tầng *phân tích*. Objective đòi phân biệt bốn nguyên nhân có biểu hiện bề ngoài giống nhau. Kiểm bằng bốn chương trình tiêm sẵn; đạt khi chẩn đoán đúng ít nhất ba và mỗi lần dẫn được số đo phân biệt.",
"Cho bốn chương trình không tăng tốc khi thêm luồng, mỗi cái một nguyên nhân. Với mỗi cái, đo mức dùng lõi, thời gian chờ vào ra, thời gian chờ khoá và băng thông bộ nhớ, rồi chẩn đoán. Với chương trình bị giới hạn bởi phần tuần tự, ước lượng tỉ lệ phần đó từ đồ thị tăng tốc.",
"Kết luận thiếu CPU vì thấy CPU cao · bỏ qua băng thông bộ nhớ · thêm luồng cho tác vụ chờ đĩa · không đo thời gian chờ khoá.",
"Chẩn đoán đúng ≥ 3/4 chương trình kèm số đo phân biệt, ước lượng được tỉ lệ phần tuần tự từ đồ thị, và mọi kết luận về tăng tốc đều kèm hiệu suất song song."),

(56,"MIMD - shared memory, distributed memory and SPMD","TH","Lesson 55",
"Bài đi vào tầng song song thứ hai, nơi mỗi đơn vị thực thi có dòng lệnh riêng. Hai dạng và hai mô hình chi phí khác hẳn nhau. Bộ nhớ dùng chung: nhiều lõi cùng nhìn một không gian địa chỉ, nên cần giao thức nhất quán bộ nhớ đệm và cần đồng bộ; chia sẻ giả xảy ra khi hai lõi ghi hai biến khác nhau nằm cùng một dòng đệm, và nó làm chậm mà không có tranh chấp logic nào; truy cập bộ nhớ không đồng nhất biến vị trí bộ nhớ thành một quyết định đặt chỗ. Bộ nhớ phân tán: trao đổi bằng thông điệp qua mạng, nên độ trễ, chi phí tuần tự hoá, cách phân vùng và hỏng một phần trở thành mô hình chi phí và mô hình hỏng. Một chương trình nhiều dữ liệu là khuôn mẫu phổ biến trên cả hai. **Tăng tốc bị chặn bởi phần tuần tự, mất cân bằng, đồng bộ, truyền thông và băng thông bộ nhớ**, nên phải báo cáo cả tăng tốc lẫn hiệu suất song song chứ chỉ con số tăng tốc.",
"Đo tăng tốc và hiệu suất song song khi tăng số đơn vị thực thi, và quy trần hiệu năng về đúng nguyên nhân.",
"Tầng *phân tích*. Objective đòi giải thích vì sao đường tăng tốc bão hoà chứ chỉ vẽ nó. Kiểm bằng thí nghiệm thay đổi quy mô; đạt khi đường hiệu suất song song được vẽ tới ít nhất tám đơn vị và trần được quy về nguyên nhân bằng số đo.",
"Chạy cùng khối lượng công việc với 1, 2, 4 và 8 đơn vị thực thi; tính tăng tốc và hiệu suất song song ở mỗi mức. Ước lượng phần tuần tự từ đường cong và đối chiếu với dự đoán của định luật tăng tốc. Tái hiện chia sẻ giả và đo chi phí của nó. Chạy một bản đặt bộ nhớ ở nút xa và đo chênh lệch. Với bản phân tán, đo thời gian truyền thông tách khỏi thời gian tính.",
"Báo cáo tăng tốc mà không báo hiệu suất song song · thêm đơn vị thực thi khi trần là băng thông bộ nhớ · bỏ qua chia sẻ giả vì không thấy tranh chấp trong mã · so bản phân tán mà không tách thời gian truyền thông.",
"Đường hiệu suất song song có số đo tới ≥ 8 đơn vị, phần tuần tự được ước lượng từ dữ liệu, và trần hiệu năng được quy về nguyên nhân cụ thể."),

(57,"Linking the model to databases","LT","Lesson 56",
"Bài nối, và nó biến mọi thứ đã đo thành công cụ đọc hành vi cơ sở dữ liệu ở M9 và M10. Bốn liên hệ bắt buộc. Trang và hồ đệm: cơ sở dữ liệu đọc ghi theo trang chứ theo dòng, và hồ đệm chính là bộ đệm trang của riêng nó, nên tỉ lệ trúng hồ đệm là chỉ số hiệu năng hàng đầu. Tra chỉ mục so với quét toàn bảng: tra chỉ mục là đọc ngẫu nhiên còn quét là đọc tuần tự, nên **khi số dòng cần lấy đủ lớn thì quét thắng dù chỉ mục tồn tại**, và đây là lý do bộ tối ưu đôi khi cố ý bỏ qua chỉ mục. Độ rẽ nhánh của cây B và chi phí đọc khối, nối lại lesson 36. Nhật ký ghi trước và `fsync`: mọi cam kết bền vững của giao dịch quy về một lần đẩy xuống đĩa, theo lesson 53. Ba câu hỏi để đọc một kế hoạch thực thi chậm trước khi biết cú pháp của công cụ nào.",
"Giải thích bằng mô hình chi phí vì sao một truy vấn cụ thể chọn quét toàn bảng thay vì dùng chỉ mục.",
"Tầng *hiểu*. Bài nối, chuẩn bị trực tiếp cho M9 và M10; chưa đòi vận hành cơ sở dữ liệu. Kiểm bằng bài lập luận trên bốn tình huống; đạt khi giải thích đúng ít nhất ba bằng chi phí đọc chứ bằng quy tắc thuộc lòng.",
"Cho bốn tình huống truy vấn với tỉ lệ dòng lấy ra khác nhau, từ 0,01% tới 40% bảng. Với mỗi tình huống, ước lượng số lần đọc ngẫu nhiên nếu dùng chỉ mục và số lần đọc tuần tự nếu quét, rồi dự đoán bộ tối ưu chọn cách nào. Ước lượng độ rẽ nhánh và chiều cao cây chỉ mục cho một bảng một triệu dòng.",
"Cho rằng có chỉ mục thì luôn nên dùng chỉ mục · bỏ qua tỉ lệ dòng lấy ra · quên rằng tra chỉ mục còn phải đọc thêm dòng dữ liệu · học quy tắc thay vì tính chi phí.",
"Giải thích đúng ≥ 3/4 tình huống bằng ước lượng số lần đọc, và tính đúng chiều cao cây chỉ mục."),

(58,"Linking the model to distributed engines","LT","Lesson 57",
"Bài nối thứ hai, chuẩn bị cho M18 và M12. Bốn liên hệ. Tuần tự hoá: dữ liệu đi qua mạng hoặc qua ranh giới tiến trình phải chuyển thành byte rồi chuyển lại, và chi phí đó thường lớn hơn phép tính; đây là lý do hàm do người dùng định nghĩa chậm hơn hàm dựng sẵn ở engine phân tán. Xáo trộn: gom dữ liệu cùng khoá về một chỗ nghĩa là ghi đĩa cục bộ, truyền mạng, đọc lại, tức là đi qua ba bậc chậm nhất của thứ bậc bộ nhớ cùng lúc, nên nó là thao tác đắt nhất. Tràn ra đĩa khi dữ liệu không vừa bộ nhớ, và vì sao đó là cơ chế tự bảo vệ chứ lỗi. Áp lực bộ nhớ và bộ dọn rác: giữ quá nhiều dữ liệu sống làm bộ dọn chạy liên tục và ăn CPU mà không làm việc hữu ích. Thực thi theo véc tơ ở engine cột khai thác đúng tính cục bộ ở lesson 47, nên hiểu lesson 47 là hiểu vì sao engine cột nhanh. Ba tầng song song lồng nhau đặt ra ở lesson 48 và lesson 56 gặp lại đầy đủ ở đây: tiến trình trên nhiều nút, toán tử xử lý theo lô trong mỗi tiến trình, và làn véctơ trong mỗi toán tử; M12 và M18 sẽ đo từng tầng riêng.",
"Ước lượng thứ tự chi phí của bốn thao tác trong một công việc phân tán và chỉ ra thao tác đắt nhất.",
"Tầng *hiểu*. Bài nối chuẩn bị cho M18; kiểm bằng lập luận chứ bằng vận hành engine. Kiểm bằng bài xếp hạng có lý do; đạt khi xếp đúng thứ tự và giải thích xáo trộn bằng ba bậc thứ bậc bộ nhớ.",
"Cho mô tả một công việc phân tán gồm đọc tệp, lọc, gộp nhóm theo khoá, và ghi kết quả. Xếp hạng chi phí bốn bước và giải thích từng bước bằng thứ bậc bộ nhớ ở lesson 45. Đo chi phí tuần tự hoá bằng cách so truyền một triệu bản ghi qua ranh giới tiến trình ở hai định dạng khác nhau.",
"Nghĩ phép tính là phần đắt nhất · bỏ qua chi phí tuần tự hoá · coi tràn ra đĩa là lỗi cấu hình · xếp hạng theo cảm tính mà không đo.",
"Xếp đúng thứ tự chi phí bốn bước, giải thích xáo trộn bằng ba bậc thứ bậc bộ nhớ, và có số đo chi phí tuần tự hoá."),

(59,"Writing a performance report that survives review","TH","Lesson 58",
"Số đo không có ngữ cảnh thì không thuyết phục được ai và cũng không dùng lại được sau ba tháng. Sáu phần của một báo cáo hiệu năng dùng được: khối lượng công việc mô tả đủ để lặp lại, môi trường gồm phần cứng và phiên bản, giả thuyết đặt trước khi đo, phương pháp đo gồm số lần lặp và cách xử lý giai đoạn khởi động, kết quả kèm mức phân tán chứ chỉ giá trị trung bình, và **giới hạn của kết luận**. Phần cuối là phần phân biệt báo cáo kỹ thuật với quảng cáo: nêu rõ kết luận này đúng trong khoảng nào và ngoài khoảng đó thì không biết. Vì sao báo cáo trung vị và phân vị cao thay vì trung bình: trung bình che mất đuôi phân bố, và đuôi mới là thứ người dùng cảm nhận. Ba cách trình bày số làm người đọc hiểu sai và cách tránh. Mẫu báo cáo này dùng lại ở mọi module có đo, tới tận M18 và M21.",
"Viết một báo cáo hiệu năng đủ sáu phần cho một phép đo đã làm, và qua được rà soát chéo về phần giới hạn.",
"Tầng *áp dụng*. Objective là sản phẩm viết theo chuẩn, đo bằng khả năng người khác lặp lại. Kiểm bằng rà soát chéo cộng phép thử lặp lại; đạt khi người khác lặp lại được phép đo và ra kết quả cùng bậc.",
"Chọn một phép đo đã làm trong module. Viết báo cáo đủ sáu phần, báo trung vị và phân vị 95 thay vì trung bình. Đưa cho một học viên khác: họ phải lặp lại được phép đo chỉ bằng báo cáo, trên máy của họ. So hai kết quả và giải thích chênh lệch bằng khác biệt môi trường.",
"Báo giá trị trung bình · bỏ phần giới hạn · không ghi phiên bản và phần cứng · đo một lần rồi báo cáo.",
"Người khác lặp lại được phép đo chỉ bằng báo cáo và ra kết quả cùng bậc, và phần giới hạn nêu rõ khoảng áp dụng."),

(60,"Performance project - predict, measure, explain","DA","Lesson 59",
"Bài dự án khép module, và điểm chấm nằm ở chất lượng lập luận chứ ở con số đẹp. Nhận một chương trình xử lý dữ liệu chạy chậm. Quy trình bắt buộc theo đúng thứ tự: đọc mã và **viết dự đoán nút thắt trước khi đo**, đo để xác nhận hoặc bác bỏ dự đoán, sửa đúng một thứ, đo lại, rồi lặp. Ghi lại mọi dự đoán sai và lý do sai, vì đó là phần có giá trị học tập cao nhất và cũng là phần hay bị giấu đi. Yêu cầu đạt: cải thiện ít nhất một mức bậc, kết quả tính ra không đổi, và mỗi lần sửa dẫn được về một số đo. Nộp kèm báo cáo hiệu năng sáu phần theo lesson 59 và sơ đồ đường đi của dữ liệu từ ứng dụng tới thiết bị theo yêu cầu của module. Cấm một điều: sửa nhiều chỗ cùng lúc, vì khi đó không biết chỗ nào có tác dụng.",
"Tăng tốc một chương trình ít nhất một mức bậc, mỗi lần sửa dẫn được về một số đo, và kết quả tính ra không đổi.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một quy trình tối ưu có bằng chứng. Kiểm bằng cặp số đo trước sau cộng rà soát nhật ký; đạt khi cải thiện đạt ngưỡng, kết quả không đổi, và mọi lần sửa có số đo dẫn chứng.",
"Nhận chương trình chậm. Viết dự đoán trước. Đo, sửa từng thứ một, đo lại sau mỗi lần. Ghi nhật ký gồm cả dự đoán sai. Nộp báo cáo sáu phần và sơ đồ đường đi dữ liệu. Đối soát kết quả tính ra với bản gốc.",
"Sửa nhiều chỗ cùng lúc · tối ưu trước khi đo · giấu dự đoán sai · cải thiện tốc độ mà đổi kết quả tính ra.",
"Cải thiện ≥ 1 mức bậc, kết quả tính ra khớp tuyệt đối với bản gốc, và mọi lần sửa dẫn được về một số đo trong nhật ký."),
]

M5 = ("Operating Systems, Concurrency and Linux", 61, 76, """| | |
|---|---|
| **Objective cấp module** | Dùng bằng chứng từ Linux để chẩn đoán tiến trình, bộ nhớ, hệ tệp, socket và tranh chấp, thay vì đoán từ triệu chứng |
| **Tiền đề** | M2 · M4 |
| **Exit criterion** | Chẩn đoán đúng bốn tình huống tải khác nhau chỉ bằng số đo hệ thống, sửa được một rò rỉ mô tả tệp cùng một khoá chết, và truy được đường từ hiệp trình tới tác vụ tới vòng lặp sự kiện tới bộ theo dõi tới mô tả tệp không chặn |
| **Kỹ năng SFIA** | `SYSP` mức 4 · `PROG` mức 3 |
| **Chế độ hỏng** | Học thuộc danh sách lệnh mà không biết mỗi lệnh đo cái gì, nên khi hệ chậm thì chạy lần lượt mọi lệnh và vẫn không kết luận được |""",
"""Đây là module công cụ chẩn đoán của cả chương trình. Mọi module vận hành sau, từ M10 tới M21, đều giả định người học đọc được số đo hệ thống và phân biệt được bốn loại tải.

Phần đồng thời ở đây là phần hệ điều hành của chủ đề đã học ở mức ngôn ngữ tại lesson 22 tới 29; hai phần bổ sung nhau chứ lặp lại.""")

L5 = [
(61,"User mode, kernel mode and the process lifecycle","LT","Module 5: M2 · M4",
"Hai chế độ thực thi và ranh giới giữa chúng là thứ đã gặp ở lesson 54 dưới góc chi phí; bài này nhìn từ góc cơ chế. Chương trình chạy ở chế độ người dùng và không đụng trực tiếp vào phần cứng; mọi yêu cầu đều qua lời gọi hệ thống. Ngắt và bẫy là hai đường vào nhân khác nhau. Vòng đời tiến trình: tạo bằng nhân bản rồi thay thế ảnh chương trình, và vì sao hai bước đó tách rời lại hữu dụng. Các trạng thái của tiến trình và ý nghĩa vận hành của từng trạng thái, đặc biệt trạng thái chờ vào ra không ngắt được vì nó là dấu hiệu đĩa hoặc mạng có vấn đề. Tiến trình xác sống và tiến trình mồ côi, cùng cách chúng phát sinh; nối lại vấn đề tiến trình con mồ côi đã gặp ở lesson 23. Tiến trình so với luồng ở mức nhân: khác nhau ở chỗ chia sẻ không gian địa chỉ hay không, và mọi hệ quả suy ra từ đó.",
"Đọc trạng thái của một tiến trình và suy ra nó đang chờ cái gì, phân biệt được chờ vào ra với chờ CPU.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng cho phần chẩn đoán sau. Kiểm bằng bài đọc trạng thái trên năm tiến trình thật; đạt khi phân loại đúng ít nhất bốn và nhận ra đúng tiến trình đang ở trạng thái chờ vào ra không ngắt được.",
"Tạo năm tiến trình ở năm trạng thái khác nhau gồm đang chạy, chờ được cấp CPU, chờ vào ra, dừng, và xác sống. Quan sát trạng thái qua công cụ hệ thống và qua hệ tệp ảo của nhân. Phân loại từng cái. Tạo một tiến trình mồ côi và quan sát nó được nhận nuôi.",
"Nhầm chờ vào ra với chờ CPU nên chẩn đoán sai · không biết trạng thái xác sống nghĩa là gì · dùng lệnh liệt kê tiến trình mà không đọc cột trạng thái.",
"Phân loại đúng ≥ 4/5 trạng thái, và nhận ra đúng tiến trình đang chờ vào ra không ngắt được."),

(62,"Scheduling, priority and load average","TH","Lesson 61",
"Bộ lập lịch quyết định tiến trình nào chạy khi nào, và hiểu nó giải thích vài chỉ số hay bị đọc sai. Lát thời gian và tính công bằng; độ ưu tiên và giá trị nhường. Chỉ số tải trung bình là chỉ số bị hiểu sai nhiều nhất trên Linux: nó đếm cả tiến trình đang chạy lẫn tiến trình đang chờ vào ra không ngắt được, nên **tải trung bình cao không đồng nghĩa CPU bận**; một máy đĩa hỏng có tải trung bình rất cao trong khi CPU rảnh. Cách đọc đúng: so tải trung bình với số lõi, rồi đối chiếu với tỉ lệ CPU chờ vào ra để biết đang nghẽn ở đâu. Mức dùng CPU chia theo loại và ý nghĩa của từng loại, đặc biệt phần chờ vào ra và phần bị đánh cắp trên máy ảo. Độ dài hàng đợi chạy. Ba tình huống mà thêm tiến trình làm mọi thứ chậm đi thay vì nhanh lên.",
"Phân biệt máy nghẽn CPU với máy nghẽn vào ra chỉ bằng chỉ số hệ thống, không cần đọc mã.",
"Tầng *phân tích*. Objective là đọc và diễn giải chỉ số đúng, kỹ năng dùng trực tiếp khi trực. Kiểm bằng bốn máy mô phỏng; đạt khi phân loại đúng ít nhất ba và mỗi lần dẫn được chỉ số phân biệt chứ chỉ tải trung bình.",
"Tạo bốn tình huống tải: bão hoà CPU, chờ vào ra nặng, áp lực bộ nhớ, và nhiều tiến trình chờ được cấp CPU. Với mỗi tình huống, ghi tải trung bình, mức dùng CPU chia theo loại, và độ dài hàng đợi chạy. Phân loại từng tình huống. Chỉ ra tình huống nào có tải trung bình cao mà CPU rảnh.",
"Kết luận CPU bận vì tải trung bình cao · so tải trung bình mà quên số lõi · bỏ qua phần chờ vào ra trong mức dùng CPU.",
"Phân loại đúng ≥ 3/4 tình huống, và chỉ ra đúng tình huống tải trung bình cao trong khi CPU rảnh."),

(63,"Memory - virtual, resident, shared and OOM","TH","Lesson 62",
"Câu hỏi tiến trình này dùng bao nhiêu bộ nhớ không có một câu trả lời duy nhất, và chọn sai chỉ số dẫn tới kết luận sai. Bốn chỉ số và ý nghĩa: bộ nhớ ảo là không gian địa chỉ đã đăng ký và thường lớn vô lý nên gần như vô dụng để đánh giá; bộ nhớ thường trú là phần thật đang trong RAM; bộ nhớ chia sẻ bị đếm nhiều lần khi cộng các tiến trình; và kích thước tập làm việc là phần thật sự đang được dùng. Bộ nhớ khả dụng khác bộ nhớ trống: phần bộ đệm trang tính là dùng nhưng giải phóng được ngay, nên **bộ nhớ trống thấp không phải vấn đề**, và đây là báo động giả phổ biến nhất. Bộ giết khi cạn bộ nhớ: khi nào kích hoạt, chọn nạn nhân theo điểm số nào, và cách đọc bản ghi của nó trong nhật ký nhân; nối lại tình huống tác vụ bị giết ở tầng container sẽ gặp ở M20.",
"Chọn đúng chỉ số để trả lời câu hỏi một tiến trình dùng bao nhiêu bộ nhớ, và đọc được bản ghi của bộ giết khi cạn bộ nhớ.",
"Tầng *phân tích*. Objective đòi chọn đúng công cụ đo cho câu hỏi, chỗ rất dễ kết luận sai. Kiểm bằng bài đo cộng thí nghiệm cạn bộ nhớ; đạt khi chọn đúng chỉ số và đọc đúng nguyên nhân từ nhật ký nhân.",
"Chạy ba tiến trình có hồ sơ bộ nhớ khác nhau gồm ánh xạ tệp lớn, cấp phát thật lớn, và dùng chung thư viện. Với mỗi cái, ghi cả bốn chỉ số và giải thích chênh lệch. Đẩy máy tới cạn bộ nhớ, tìm bản ghi của bộ giết trong nhật ký nhân và xác định nạn nhân cùng lý do.",
"Dùng bộ nhớ ảo để đánh giá mức dùng · cộng bộ nhớ thường trú của nhiều tiến trình dùng chung thư viện · hoảng vì bộ nhớ trống thấp · không biết tìm bản ghi bộ giết ở đâu.",
"Chọn đúng chỉ số cho cả ba tiến trình kèm giải thích chênh lệch, và đọc đúng nạn nhân cùng lý do từ nhật ký nhân."),

(64,"Filesystems, inodes, file descriptors and leaks","TH","Lesson 63",
"Hệ tệp tách tên khỏi nội dung: nút chỉ mục giữ siêu dữ liệu và con trỏ tới khối, còn thư mục chỉ là ánh xạ tên sang nút chỉ mục. Từ đó suy ra ba điều hay gây ngạc nhiên: liên kết cứng là hai tên trỏ cùng nút chỉ mục nên xoá một tên không xoá dữ liệu; **xoá một tệp đang được tiến trình mở thì dung lượng không được giải phóng cho tới khi tiến trình đóng**, và đây là nguyên nhân kinh điển của việc đĩa đầy mà tìm không ra tệp nào; và đổi tên trong cùng hệ tệp là thao tác rẻ vì chỉ đổi mục thư mục. Mô tả tệp là chỉ số trỏ vào bảng của tiến trình, và giới hạn số mô tả tệp là giới hạn hay chạm trong dịch vụ dữ liệu. Rò rỉ mô tả tệp: triệu chứng, cách tìm bằng hệ tệp ảo của nhân, và cách sửa bằng trình quản lý ngữ cảnh ở lesson 15. Hai lệnh đo dung lượng cho kết quả khác nhau và lý do.",
"Tìm được nguyên nhân đĩa đầy mà không thấy tệp, và định vị một rò rỉ mô tả tệp về đúng đoạn mã.",
"Tầng *phân tích*. Objective là hai chẩn đoán cụ thể mà người mới gần như luôn bế tắc. Kiểm bằng hai tình huống tiêm sẵn tính giờ; đạt khi tìm ra nguyên nhân cả hai và sửa được rò rỉ có bằng chứng số mô tả tệp không tăng.",
"Tạo tình huống đĩa đầy do tệp đã xoá nhưng còn mở; dùng công cụ hệ thống tìm ra tiến trình giữ nó. Chạy một dịch vụ rò rỉ mô tả tệp, quan sát số mô tả tăng theo thời gian, định vị đoạn mã, sửa bằng trình quản lý ngữ cảnh, và chứng minh số mô tả ổn định sau 10.000 yêu cầu.",
"Xoá tệp rồi tưởng đã giải phóng dung lượng · so hai lệnh đo dung lượng mà không biết vì sao khác nhau · tăng giới hạn mô tả tệp thay vì sửa rò rỉ.",
"Tìm đúng tiến trình giữ tệp đã xoá, và sau khi sửa thì số mô tả tệp ổn định qua 10.000 yêu cầu."),

(65,"Non-blocking descriptors, select, poll and epoll","TH","Lesson 64",
"Bài giải thích cơ chế dưới mọi vòng lặp sự kiện, nên nó là nền của phần bất đồng bộ đã học ở M2. Bộ mô tả chặn làm luồng gọi ngủ tới khi thao tác xong; bộ mô tả không chặn trả về ngay một trạng thái chưa sẵn sàng thay vì chờ, nên một luồng theo dõi được nhiều kết nối. Ba thế hệ cơ chế theo dõi và khác biệt về chi phí: hai cơ chế cũ quét toàn bộ tập bộ mô tả mỗi lần gọi nên chi phí tăng theo số kết nối; cơ chế mới giữ sẵn tập quan tâm và chỉ trả về phần đã sẵn sàng, nên chi phí không tăng theo số kết nối đang mở. Hai chế độ báo: báo theo mức lặp lại trạng thái tới khi được xử lý, báo theo sườn chỉ báo một lần khi trạng thái đổi; **chế độ báo theo sườn bắt buộc đọc tới khi hết dữ liệu**, và bỏ quy tắc đó làm treo kết nối mà không có lỗi nào. Tệp thường không có ngữ nghĩa sẵn sàng hữu ích như ổ cắm.",
"Viết một máy chủ một luồng theo dõi nhiều kết nối và đo chi phí của hai cơ chế theo dõi khi số kết nối tăng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là đường chi phí theo số kết nối. Kiểm bằng phép đo thay đổi quy mô; đạt khi hai đường chi phí tách nhau rõ ở 10.000 kết nối và ca báo theo sườn bị treo được tái hiện rồi sửa.",
"Viết máy chủ một luồng dùng bộ mô tả không chặn. Cài cả hai cơ chế theo dõi. Đo thời gian mỗi vòng lặp ở 100, 1.000 và 10.000 kết nối nhàn rỗi, vẽ hai đường. Chuyển sang chế độ báo theo sườn mà không đọc tới khi hết dữ liệu, tái hiện kết nối treo, rồi sửa theo quy tắc đọc cạn.",
"Dùng bộ mô tả chặn trong vòng lặp sự kiện · dùng chế độ báo theo sườn mà không đọc cạn · đo chi phí chỉ ở số kết nối nhỏ · giả định tệp thường có ngữ nghĩa sẵn sàng như ổ cắm.",
"Hai đường chi phí tách nhau rõ ở 10.000 kết nối, và ca treo do báo theo sườn được tái hiện rồi sửa."),

(66,"Readiness against completion - partial I/O, cancellation and io_uring awareness","TH","Lesson 65",
"Hai mô hình vào ra khác nhau ở chỗ hệ điều hành báo gì cho ứng dụng. Mô hình sẵn sàng báo rằng thao tác có thể tiến triển, còn ứng dụng tự gọi đọc hoặc ghi; mô hình hoàn tất nhận yêu cầu rồi báo khi đã xong. Hệ quả quan trọng nhất của mô hình sẵn sàng và là lỗi hay gặp: **sẵn sàng không bảo đảm đọc hoặc ghi được trọn vẹn thông điệp**, nên mọi lời gọi phải xử lý đọc thiếu và ghi thiếu, và ứng dụng phải tự đóng khung thông điệp. Huỷ bỏ ở tầng ứng dụng không tự hoàn tác một lời gọi hệ thống đã phát ra hay một tác dụng phụ đã xảy ra ở bên kia, nên ranh giới sở hữu, dọn dẹp và công bố phải do mã định nghĩa, đúng nguyên tắc ở lesson 27. Giao diện gửi và nhận theo hàng đợi ở mức nhận biết: nó giảm số lời gọi hệ thống và chi phí chuyển ngữ cảnh, và **không dùng chỉ vì nó mới** khi khối lượng công việc và môi trường chạy chưa hưởng lợi.",
"Xử lý đúng đọc thiếu và ghi thiếu dưới tải, và nêu ranh giới mà huỷ bỏ không hoàn tác được.",
"Tầng *áp dụng*. Objective có một ca hỏng đặc trưng chỉ lộ ra dưới tải. Kiểm bằng phép thử thông điệp lớn; đạt khi không thông điệp nào bị cắt hay ghép sai qua 10.000 lượt và ca huỷ giữa chừng được mô tả đúng hậu quả.",
"Viết bên gửi và bên nhận trao đổi thông điệp lớn hơn bộ đệm ổ cắm. Chạy 10.000 lượt dưới tải và đếm số thông điệp bị cắt hoặc ghép sai khi chưa xử lý đọc thiếu, rồi sửa bằng cách đóng khung và lặp tới đủ. Huỷ một thao tác giữa chừng sau khi đã ghi một phần và mô tả trạng thái bên kia nhìn thấy. Viết một đoạn nêu điều kiện mà giao diện theo hàng đợi đáng cân nhắc.",
"Giả định một lần gọi đọc trả về trọn thông điệp · không đóng khung thông điệp · tin rằng huỷ bỏ hoàn tác được tác dụng phụ đã gửi đi · chọn giao diện mới vì nghe hiện đại.",
"Không thông điệp nào bị cắt hay ghép sai qua 10.000 lượt, và hậu quả của huỷ giữa chừng được mô tả đúng ở phía bên kia."),

(67,"Signals, exit codes and graceful shutdown","TH","Lesson 66",
"Tín hiệu là cách nhân và các tiến trình báo cho nhau, và xử lý sai tín hiệu là nguyên nhân mất dữ liệu khi triển khai. Phân biệt hai tín hiệu dừng: một cái bắt được và cho phép dọn dẹp, một cái không bắt được và giết ngay. Quy trình tắt đúng của một tiến trình xử lý dữ liệu: nhận tín hiệu, ngừng nhận việc mới, hoàn tất việc đang dở trong hạn, đẩy dữ liệu xuống đĩa, rồi thoát với mã đúng. Thời gian chờ trước khi bị giết cứng là hữu hạn nên phần dọn dẹp phải nằm trong hạn đó, và đây là ràng buộc sẽ gặp lại ở M20. Mã thoát và quy ước: không là thành công, khác không là thất bại, và bị tín hiệu giết thì mã thoát mã hoá số hiệu tín hiệu. Vì sao mã thoát đúng quan trọng: hệ điều phối ở M14 và hệ chạy container ở M20 đều dựa vào nó để biết việc thành công hay thất bại.",
"Cài đặt tắt có kiểm soát cho một tiến trình xử lý và chứng minh không mất việc đang dở khi nhận tín hiệu dừng.",
"Tầng *áp dụng*. Objective là một cơ chế kiểm được bằng thí nghiệm dừng. Kiểm bằng 20 lần gửi tín hiệu ở thời điểm ngẫu nhiên; đạt khi không lần nào mất việc và mã thoát đúng ở mọi trường hợp.",
"Viết tiến trình xử lý hàng đợi. Cài bắt tín hiệu dừng, hoàn tất việc đang dở, đẩy dữ liệu xuống đĩa rồi thoát. Gửi tín hiệu dừng 20 lần ở thời điểm ngẫu nhiên và đối soát kết quả. Gửi tín hiệu giết cứng và ghi lại khác biệt. Kiểm mã thoát ở ba trường hợp thành công, thất bại và bị giết.",
"Không bắt tín hiệu nên bị giết giữa lúc ghi · dọn dẹp quá lâu rồi bị giết cứng · trả mã thoát không khi thực ra thất bại · dùng shell làm tiến trình chính nên tín hiệu không tới được chương trình.",
"20 lần gửi tín hiệu dừng đều không mất việc đang dở, và mã thoát đúng ở cả ba trường hợp."),

(68,"Shell scripting that fails loudly","TH","Lesson 67",
"Shell là keo dán của mọi hệ vận hành, và script shell viết ẩu là nguồn sự cố âm thầm vì mặc định của shell là chạy tiếp khi có lỗi. Ba tuỳ chọn nghiêm ngặt và tác dụng từng cái: dừng khi một lệnh lỗi, coi biến chưa đặt là lỗi, và cho lỗi trong đường ống lan ra. Kèm theo là cảnh báo về các trường hợp tuỳ chọn dừng khi lỗi **không** kích hoạt, vì tin tưởng mù vào nó cũng nguy hiểm. Trích dẫn và khai triển: quên ngoặc kép quanh biến là nguồn lỗi số một khi tên tệp có dấu cách. Bẫy để dọn dẹp khi thoát, tương đương trình quản lý ngữ cảnh ở lesson 15. Mã thoát và cách kiểm tra từng bước theo lesson 67. Khi nào nên dừng viết shell và chuyển sang Python: ba dấu hiệu cụ thể, thường là khi cần cấu trúc dữ liệu, cần xử lý lỗi phân tầng, hoặc script vượt khoảng một trăm dòng.",
"Viết script vận hành dừng đúng lúc lỗi, dọn dẹp khi thoát, và trả mã thoát đúng trong mọi nhánh.",
"Tầng *áp dụng*. Objective là một tập quy tắc kiểm được bằng thí nghiệm tiêm lỗi. Kiểm bằng năm lỗi tiêm; đạt khi cả năm đều làm script dừng với mã thoát khác không và tài nguyên tạm được dọn.",
"Viết script nạp dữ liệu có tạo thư mục tạm, tải tệp, xử lý, rồi dọn. Tiêm năm lỗi: lệnh thất bại giữa chừng, biến chưa đặt, lỗi trong đường ống, tên tệp có dấu cách, và bị dừng giữa chừng. Chứng minh cả năm được xử lý đúng và thư mục tạm luôn được dọn.",
"Quên ngoặc kép quanh biến · tin tuỳ chọn dừng khi lỗi bắt được mọi trường hợp · không dọn khi bị dừng giữa chừng · viết 500 dòng shell cho việc cần Python.",
"Năm lỗi đều làm script dừng với mã thoát khác không, và thư mục tạm được dọn trong cả năm trường hợp."),

(69,"Services with systemd and the journal","TH","Lesson 68",
"Chạy một tiến trình lâu dài bằng cách mở terminal rồi để đó không phải cách vận hành, và trình quản lý dịch vụ giải bốn việc: khởi động cùng máy, khởi động lại khi chết, thu thập nhật ký, và quản lý phụ thuộc giữa các dịch vụ. Tệp định nghĩa dịch vụ và các trường quan trọng: lệnh chạy, người dùng chạy, chính sách khởi động lại, biến môi trường, và giới hạn tài nguyên. Chính sách khởi động lại và bẫy vòng lặp: dịch vụ chết ngay khi khởi động cộng với chính sách luôn khởi động lại cho ra vòng lặp khởi động liên tục, nên phải đặt giới hạn số lần trong một khoảng. Nhật ký tập trung: đọc theo dịch vụ, theo thời gian, theo mức, và vì sao ghi ra luồng chuẩn tiện hơn tự ghi tệp, nối lại nguyên tắc ở lesson 20. Ranh giới bí mật: biến môi trường trong tệp định nghĩa đọc được bởi ai, và cách đưa bí mật vào đúng cách.",
"Chạy một dịch vụ dữ liệu dưới trình quản lý dịch vụ với chính sách khởi động lại đúng và nhật ký đọc được tập trung.",
"Tầng *áp dụng*. Objective là một cấu hình vận hành kiểm được bằng thí nghiệm giết tiến trình. Kiểm bằng ba phép thử; đạt khi dịch vụ tự khởi động lại, vòng lặp khởi động bị chặn, và nhật ký truy được theo mã theo dõi.",
"Đóng gói tiến trình xử lý ở lesson 67 thành một dịch vụ. Giết nó và xác nhận tự khởi động lại. Làm nó chết ngay khi khởi động và xác nhận giới hạn số lần chặn được vòng lặp. Đọc nhật ký theo dịch vụ và lọc theo mã theo dõi. Đưa một bí mật vào đúng cách và kiểm tài khoản thường không đọc được.",
"Đặt chính sách luôn khởi động lại mà không giới hạn số lần · chạy dịch vụ bằng quyền quản trị · ghi nhật ký vào tệp riêng thay vì luồng chuẩn · đặt bí mật thẳng trong tệp định nghĩa dịch vụ.",
"Dịch vụ tự khởi động lại sau khi bị giết, vòng lặp khởi động bị chặn theo giới hạn, và nhật ký lọc được theo mã theo dõi."),

(70,"Races, locks and deadlock at the OS level","TH","Lesson 69",
"Phần này lặp lại chủ đề của lesson 22 nhưng ở tầng hệ điều hành và với công cụ chẩn đoán thật. Ba tính chất phải phân biệt vì chúng hỏng theo ba cách khác nhau: tính nguyên tử, tính nhìn thấy được, và thứ tự. Ba nguyên hàm đồng bộ và khi nào dùng cái nào: khoá loại trừ, cờ hiệu đếm, và biến điều kiện. Bốn điều kiện cần cùng lúc để có khoá chết, và phá bất kỳ điều kiện nào là chặn được; cách phá thực dụng nhất là quy định thứ tự lấy khoá. Đói tài nguyên và khoá sống là hai chế độ hỏng khác khoá chết và cần cách chữa khác. Đo tranh chấp: thời gian tiến trình nằm chờ ở nguyên hàm đồng bộ quan sát được bằng công cụ theo dõi lời gọi hệ thống, nên tranh chấp là thứ đo được chứ đoán. Từ số đo đó suy ra phần song song thật, nối lại định luật ở lesson 55.",
"Chẩn đoán một khoá chết thật bằng công cụ hệ thống và sửa bằng cách phá đúng một trong bốn điều kiện.",
"Tầng *phân tích*. Objective đòi truy từ hiện tượng treo về cấu trúc lấy khoá, dùng bằng chứng hệ thống. Kiểm bằng tình huống khoá chết tiêm sẵn tính giờ; đạt khi định vị đúng cặp khoá và nêu đúng điều kiện đã phá.",
"Viết chương trình có hai khoá lấy theo thứ tự chéo nhau và làm nó treo. Dùng công cụ theo dõi lời gọi hệ thống để thấy cả hai luồng đang chờ ở đâu. Sửa bằng cách quy định thứ tự lấy khoá. Đo thời gian chờ ở nguyên hàm đồng bộ trước và sau khi giảm vùng tranh chấp.",
"Thêm khoá bao quanh mọi thứ · tăng thời gian chờ khoá thay vì sửa thứ tự · kết luận treo do mạng mà chưa xem tiến trình đang chờ gì · không đo tranh chấp.",
"Định vị đúng cặp khoá gây treo bằng bằng chứng hệ thống, sửa xong chương trình không treo qua 1000 lần chạy, và có số đo tranh chấp trước sau."),

(71,"Tracing a program with strace and perf","TH","Lesson 70",
"Hai công cụ trả lời hai câu hỏi khác nhau, và biết dùng cái nào cho câu nào tiết kiệm rất nhiều thời gian. Theo dõi lời gọi hệ thống trả lời chương trình đang nói gì với nhân: mở tệp nào, kết nối tới đâu, chờ ở đâu; rất hữu dụng khi chương trình treo hoặc khi không rõ nó đọc tệp cấu hình nào. Nhược điểm là làm chương trình chậm đáng kể nên không dùng trong sản xuất khi tải cao. Lấy mẫu hiệu năng trả lời thời gian CPU tiêu ở hàm nào, nhẹ nên dùng được trong sản xuất, nhưng không thấy phần chờ. Từ đó rút ra quy tắc chọn: chương trình bận CPU thì lấy mẫu hiệu năng, chương trình treo hoặc chờ thì theo dõi lời gọi hệ thống. Cách đọc kết quả: đếm theo lời gọi để thấy cái nào nhiều, và xem thời gian nằm trong lời gọi nào để thấy chờ ở đâu. Nối tới M21: đây là hai công cụ của bước chẩn đoán trong quy trình xử lý sự cố.",
"Chọn đúng công cụ cho một triệu chứng cho trước và định vị nguyên nhân từ kết quả của nó.",
"Tầng *phân tích*. Objective là chọn công cụ theo câu hỏi rồi đọc kết quả, kỹ năng dùng lại suốt phần vận hành. Kiểm bằng ba chương trình có ba triệu chứng; đạt khi chọn đúng công cụ ít nhất hai và định vị đúng nguyên nhân.",
"Cho ba chương trình: một treo khi khởi động, một bận CPU bất thường, một chậm vì gọi hệ thống quá nhiều. Với mỗi cái, chọn công cụ, chạy, và định vị nguyên nhân. Với chương trình treo, chỉ ra chính xác lời gọi hệ thống nó đang chờ.",
"Dùng theo dõi lời gọi hệ thống cho chương trình bận CPU · chạy công cụ theo dõi trên sản xuất lúc tải cao · đọc kết quả mà không đếm theo lời gọi · bỏ qua thời gian nằm trong lời gọi.",
"Chọn đúng công cụ ≥ 2/3 trường hợp và định vị đúng nguyên nhân, kể cả chỉ ra lời gọi mà chương trình treo đang chờ."),

(72,"Distinguishing four kinds of system pressure","TH","Lesson 71",
"Bài tổng hợp phần chẩn đoán, và nó là thứ dùng nhiều nhất khi trực. Bốn loại tải và bộ chỉ số phân biệt từng loại. Bão hoà CPU: mức dùng cao ở phần người dùng hoặc phần nhân, hàng đợi chạy dài, chờ vào ra thấp. Nghẽn vào ra: chờ vào ra cao, độ sâu hàng đợi thiết bị cao, thời gian phục vụ cao, trong khi CPU rảnh. Áp lực bộ nhớ: lỗi trang nặng tăng, hoạt động hoán đổi, bộ nhớ khả dụng thấp; phân biệt với bộ nhớ trống thấp theo lesson 63. Đĩa đầy: khác ba loại trên vì nó làm thao tác ghi thất bại chứ chỉ chậm, và có thể do tệp đã xoá còn mở theo lesson 64. Quy trình chẩn đoán bốn bước theo thứ tự cố định để không bỏ sót. Nguyên tắc: **kết luận phải dẫn được về ít nhất hai chỉ số nhất quán với nhau**, vì một chỉ số đơn lẻ dễ dẫn tới kết luận sai.",
"Chẩn đoán đúng loại tải trong bốn loại chỉ bằng chỉ số hệ thống, trong giới hạn thời gian.",
"Tầng *phân tích*. Objective là chẩn đoán dưới áp lực thời gian, đúng điều kiện khi trực. Kiểm bằng bốn tình huống tiêm sẵn, mỗi tình huống 8 phút; đạt khi chẩn đoán đúng ít nhất ba và mỗi lần dẫn được hai chỉ số nhất quán.",
"Giảng viên tạo lần lượt bốn loại tải trên một máy, mỗi lần 8 phút. Với mỗi lần, chạy quy trình bốn bước, ghi bộ chỉ số, và kết luận. Với tình huống đĩa đầy, xác định thêm nguyên nhân là tệp thật hay tệp đã xoá còn mở.",
"Kết luận từ một chỉ số · chạy mọi lệnh rồi vẫn không kết luận · nhầm bộ nhớ trống thấp với áp lực bộ nhớ · bỏ qua bước xác định nguyên nhân sâu hơn.",
"Chẩn đoán đúng ≥ 3/4 tình huống trong giới hạn thời gian, mỗi lần dẫn được hai chỉ số nhất quán."),

(73,"Permissions, users and the least-privilege habit","TH","Lesson 72",
"Quyền trên Linux là tầng phòng vệ đầu tiên và cũng là tầng hay bị vô hiệu hoá vì tiện. Ba nhóm quyền và ba loại quyền, cùng cách đọc và đặt. Mặt nạ tạo tệp quyết định quyền mặc định của tệp mới và là nguồn lỗi hay gặp khi một dịch vụ ghi tệp mà dịch vụ khác không đọc được. Quyền trên thư mục có nghĩa khác quyền trên tệp và đây là chỗ hay nhầm: quyền thực thi trên thư mục nghĩa là đi vào được. Chạy dịch vụ bằng người dùng riêng có quyền tối thiểu thay vì quyền quản trị: lý do không phải hình thức mà là phạm vi thiệt hại khi dịch vụ bị lợi dụng. Chủ sở hữu tệp giữa tiến trình trong container và tiến trình trên máy chủ, một vấn đề sẽ gặp lại ở M20. Ba phép thử truy cập trái phép phải chạy sau khi đặt quyền, vì đặt quyền mà không thử là không biết nó có tác dụng không.",
"Đặt quyền tối thiểu cho một dịch vụ và chứng minh bằng phép thử rằng tài khoản khác không đọc hay ghi được.",
"Tầng *áp dụng*. Objective là một cấu hình bảo mật kiểm được bằng phép thử phủ định. Kiểm bằng ba phép thử truy cập trái phép; đạt khi cả ba bị từ chối và dịch vụ vẫn chạy đúng.",
"Chạy dịch vụ ở lesson 69 bằng người dùng riêng. Đặt quyền tối thiểu cho thư mục dữ liệu và tệp cấu hình. Thử đọc, ghi và thực thi bằng một tài khoản khác và ghi lại kết quả cả ba. Đặt mặt nạ tạo tệp và kiểm tệp mới sinh ra có quyền đúng.",
"Chạy dịch vụ bằng quyền quản trị cho tiện · đặt quyền mở cho mọi người để hết lỗi · quên mặt nạ tạo tệp nên tệp mới sai quyền · đặt quyền mà không thử truy cập trái phép.",
"Ba phép thử truy cập trái phép đều bị từ chối, dịch vụ vẫn chạy đúng, và tệp mới sinh ra có quyền đúng theo mặt nạ."),

(74,"Networking from the command line","TH","Lesson 73",
"Bộ công cụ tối thiểu để trả lời câu hỏi vì sao không kết nối được, và bài này chuẩn bị trực tiếp cho M6. Năm câu hỏi theo thứ tự chẩn đoán và công cụ tương ứng cho từng câu: tên miền phân giải ra địa chỉ nào, máy có đường đi tới địa chỉ đó không, cổng có mở và có ai đang nghe không, bắt tay có thành công không, và ứng dụng trả lời gì. Đi theo thứ tự này tránh được việc đoán lung tung. Phân biệt ba loại thất bại có triệu chứng giống nhau nhưng nguyên nhân khác hẳn: không phân giải được tên, kết nối bị từ chối, và kết nối hết giờ; loại thứ ba thường là tường lửa chặn im lặng. Xem socket đang mở và trạng thái của chúng, đặc biệt trạng thái chờ đóng tích tụ nhiều là dấu hiệu cạn cổng tạm. Bắt gói ở mức đủ để xác nhận gói có đi ra không, chưa cần phân tích sâu vì phần đó ở M6.",
"Chẩn đoán một lỗi kết nối về đúng một trong ba loại thất bại, theo đúng thứ tự năm bước.",
"Tầng *phân tích*. Objective là một quy trình chẩn đoán có thứ tự, chuẩn bị cho M6. Kiểm bằng ba lỗi kết nối tiêm sẵn; đạt khi phân loại đúng ít nhất hai và chỉ ra bước nào trong năm bước phát hiện ra.",
"Giảng viên tạo ba lỗi kết nối: tên miền trỏ sai, dịch vụ không nghe cổng, và tường lửa chặn im lặng. Với mỗi lỗi, chạy đủ năm bước theo thứ tự và ghi bước nào phát hiện ra. Liệt kê socket đang mở và chỉ ra trạng thái chờ đóng nếu có.",
"Bắt gói ngay từ đầu thay vì kiểm phân giải tên trước · nhầm bị từ chối với hết giờ · bỏ qua bước kiểm ai đang nghe cổng · không biết trạng thái socket nghĩa là gì.",
"Phân loại đúng ≥ 2/3 lỗi và chỉ ra đúng bước phát hiện, kèm bảng socket đang mở có đọc trạng thái."),

(75,"A diagnosis runbook for a data service","TH","Lesson 74",
"Bài ghép: biến mọi kỹ năng chẩn đoán trong module thành một sổ tay dùng được lúc ba giờ sáng. Cấu trúc sổ tay theo đúng trình tự người trực cần, đã đặt ở lesson 10: triệu chứng nào, ảnh hưởng ra sao, chẩn đoán theo bước nào, giảm nhẹ thế nào, leo thang cho ai, và xác nhận đã hồi phục bằng gì. Năm mục bắt buộc cho một dịch vụ dữ liệu, mỗi mục tương ứng một bài đã học: dịch vụ không khởi động, dịch vụ chậm bất thường, đĩa đầy, rò rỉ mô tả tệp, và không kết nối được tới nguồn. Nguyên tắc viết: mỗi bước là một lệnh chạy được kèm cái cần nhìn trong kết quả, chứ một lời khuyên chung. Ngưỡng phải là số chứ tính từ. Phép thử của một sổ tay tốt là người chưa từng chạm vào hệ làm theo được, và đó chính là cách bài này chấm điểm.",
"Viết sổ tay năm mục mà một người khác dùng được để chẩn đoán và khắc phục, không cần hỏi.",
"Tầng *đánh giá*. Objective đo chất lượng sổ tay bằng kết quả của người dùng nó chứ bằng độ dày. Kiểm bằng phép thử với người ngoài; đạt khi họ xử lý được ít nhất ba trong năm tình huống mà không phải hỏi.",
"Viết sổ tay năm mục cho dịch vụ ở lesson 69. Đưa cho một học viên chưa từng chạm vào dịch vụ đó. Giảng viên tạo lần lượt năm tình huống; người kia chỉ được dùng sổ tay. Ghi lại tình huống nào họ xử lý được và mọi câu họ phải hỏi. Sửa sổ tay theo danh sách đó.",
"Viết bước dạng kiểm tra nhật ký mà không nói tìm gì · đặt ngưỡng bằng tính từ · bỏ bước xác nhận đã hồi phục · viết cho người đã biết hệ.",
"Người ngoài xử lý được ≥ 3/5 tình huống chỉ bằng sổ tay, và bản sửa sau đó giảm được số câu phải hỏi."),

(76,"Linux diagnosis project","DA","Lesson 75",
"Bài dự án khép module. Nhận một máy có dịch vụ dữ liệu đang chạy sai theo nhiều cách cùng lúc, và nhiệm vụ là đưa nó về trạng thái khoẻ mạnh với bằng chứng cho từng bước. Ba loại vấn đề cài sẵn, mỗi loại thuộc một nhóm đã học: một vấn đề tài nguyên, một vấn đề cấu hình dịch vụ, và một vấn đề quyền hoặc kết nối. Yêu cầu nộp: dòng thời gian chẩn đoán ghi theo thứ tự thật gồm cả nhánh sai đã thử, bằng chứng số đo cho từng kết luận, thay đổi đã thực hiện, và cách xác nhận đã hồi phục. Chấm nặng phần lập luận: một chẩn đoán đúng do đoán trúng được ít điểm hơn một chẩn đoán có ba giả thuyết bị bác bỏ bằng bằng chứng, theo đúng kỷ luật đặt ở lesson 8. Cấm khởi động lại máy như bước đầu tiên, vì nó xoá mất bằng chứng.",
"Đưa một máy có ba vấn đề về trạng thái khoẻ mạnh, mỗi kết luận dẫn được về số đo, và xác nhận được đã hồi phục.",
"Tầng *phân tích*. Bài tổng hợp toàn module thành một buổi chẩn đoán thật. Kiểm bằng trạng thái cuối cộng rà soát dòng thời gian; đạt khi cả ba vấn đề được sửa và mỗi kết luận có số đo dẫn chứng.",
"Nhận máy có ba vấn đề cài sẵn, 90 phút. Chẩn đoán và sửa từng cái. Nộp dòng thời gian gồm cả nhánh sai, bằng chứng số đo, thay đổi đã làm, và cách xác nhận. Không được khởi động lại máy trước khi thu thập bằng chứng.",
"Khởi động lại máy rồi mất bằng chứng · sửa nhiều thứ cùng lúc nên không biết cái nào có tác dụng · giấu nhánh sai · kết luận không kèm số đo.",
"Cả ba vấn đề được sửa và xác nhận hồi phục, mỗi kết luận dẫn được về số đo, và dòng thời gian có ghi nhánh sai đã thử."),
]

M6 = ("Networking from Packet to API", 77, 88, """| | |
|---|---|
| **Objective cấp module** | Theo được một yêu cầu qua phân giải tên, bắt tay, mã hoá, giao thức ứng dụng, proxy và cân bằng tải, rồi chẩn đoán độ trễ cùng hết giờ bằng gói tin và nhật ký |
| **Tiền đề** | M5 |
| **Exit criterion** | Vẽ được trình tự từ phân giải tên tới phản hồi và chỉ ra trạng thái cùng hạn chờ ở từng bước; từ một bản bắt gói phân biệt được truyền lại, đặt lại kết nối và lỗi ứng dụng |
| **Kỹ năng SFIA** | `NTAS` mức 4 · `SYSP` mức 3 |
| **Chế độ hỏng** | Gọi giao diện lập trình web mà không đặt hạn chờ và không giới hạn thử lại, rồi một nguồn chậm kéo sập cả pipeline |""",
"""Module này phục vụ trực tiếp M14B khi nạp dữ liệu từ giao diện lập trình web, và M16 cùng M21 khi chẩn đoán hệ phân tán. Trọng tâm không phải lý thuyết mạng mà là **đọc được bằng chứng**: gói tin, trạng thái socket, và nhật ký.

Ba con số sẽ dùng lại suốt phần sau: hạn chờ kết nối, hạn chờ đọc, và hạn chờ tổng. Không đặt đủ ba là để hệ có thể treo vô hạn.""")

L6 = [
(77,"Layers, addresses and routing","LT","Module 6: M5",
"Mô hình phân tầng dùng để định vị vấn đề chứ để học thuộc: khi có sự cố, câu hỏi đầu tiên là nó nằm ở tầng nào. Địa chỉ và khối địa chỉ: cách đọc ký hiệu tiền tố và tính được dải địa chỉ của một mạng con, kỹ năng dùng trực tiếp khi thiết kế mạng riêng ở M19. Bảng định tuyến và cổng ra: máy quyết định gửi gói đi đâu bằng cách so địa chỉ đích với bảng định tuyến, và đọc được bảng đó là trả lời được câu gói này đi đường nào. Phân giải địa chỉ vật lý trong mạng cục bộ ở mức nhận biết. Đơn vị truyền tối đa và phân mảnh: gói vượt kích thước tối đa bị chia hoặc bị loại, và triệu chứng của nó rất dễ nhầm với lỗi ứng dụng vì kết nối thành công nhưng truyền dữ liệu lớn thì treo. Chuyển đổi địa chỉ và tường lửa: hai thứ đứng giữa và làm thay đổi những gì bên kia nhìn thấy.",
"Tính được dải địa chỉ của một mạng con và dự đoán đường đi của một gói trước khi kiểm chứng bằng lệnh.",
"Tầng *áp dụng*. Bài mở module, kỹ năng tính toán cụ thể chuẩn bị cho M19. Kiểm bằng bài tính cộng dự đoán; đạt khi tính đúng ít nhất bốn trong năm mạng con và dự đoán đúng đường đi ở cả ba trường hợp.",
"Cho năm khối địa chỉ, tính dải địa chỉ dùng được và địa chỉ quảng bá cho từng cái. Đọc bảng định tuyến của máy mình. Với ba địa chỉ đích khác nhau, viết dự đoán gói đi qua cổng nào **trước khi** chạy lệnh tra đường, rồi đối chiếu.",
"Học thuộc bảy tầng mà không dùng để định vị · tính nhầm số địa chỉ dùng được · bỏ qua đơn vị truyền tối đa nên không giải thích được lỗi treo khi truyền dữ liệu lớn.",
"Tính đúng ≥ 4/5 mạng con, và dự đoán đường đi khớp kết quả lệnh tra ở cả ba trường hợp."),

(78,"DNS - resolution, caching and stale records","TH","Lesson 77",
"Phân giải tên là bước đầu tiên của mọi kết nối và cũng là nguồn sự cố hay bị bỏ qua nhất vì nó thường hoạt động. Quá trình phân giải đệ quy và vai trò của máy chủ có thẩm quyền. Các loại bản ghi hay dùng và ý nghĩa vận hành của từng loại. Thời gian sống quyết định bộ đệm giữ kết quả bao lâu, và từ đó suy ra hai hệ quả quan trọng: đổi bản ghi không có hiệu lực ngay với mọi nơi, nên **kế hoạch chuyển đổi hạ tầng phải hạ thời gian sống trước nhiều giờ**; và một bản ghi cũ nằm trong bộ đệm có thể trỏ tới máy đã ngừng hoạt động. Ba tầng đệm hay quên: đệm của thư viện trong tiến trình, đệm của hệ điều hành, và đệm của máy chủ phân giải. Triệu chứng của bản ghi cũ và cách phân biệt với lỗi mạng: một số máy gọi được và một số không, đó là dấu hiệu đặc trưng.",
"Chẩn đoán một sự cố do bản ghi cũ trong bộ đệm và phân biệt nó với lỗi kết nối thật.",
"Tầng *phân tích*. Objective là nhận ra một loại sự cố có triệu chứng gây hiểu nhầm. Kiểm bằng hai tình huống trong đó một là bản ghi cũ; đạt khi phân biệt đúng và chỉ ra tầng đệm nào đang giữ bản ghi.",
"Dựng một tên miền thử trỏ tới một máy, gọi thành công, rồi đổi sang máy khác. Quan sát thời gian bản ghi cũ còn hiệu lực ở từng tầng đệm. Tạo tình huống một số tiến trình gọi được và một số không, rồi chẩn đoán. So thời gian sống đặt trước và sau khi hạ xuống.",
"Bỏ qua bước phân giải tên khi chẩn đoán · đổi bản ghi rồi mong có hiệu lực ngay · quên đệm trong tiến trình · kết luận lỗi mạng khi thực ra là bản ghi cũ.",
"Phân biệt đúng hai tình huống, chỉ ra đúng tầng đệm giữ bản ghi cũ, và có số đo thời gian hiệu lực ở từng tầng."),

(79,"TCP - handshake, retransmission and connection states","TH","Lesson 78",
"Giao thức bảo đảm thứ tự và không mất dữ liệu, và mọi bảo đảm đó đều có cái giá quan sát được. Bắt tay ba bước và vì sao kết nối tốn ít nhất một vòng khứ hồi trước khi gửi được byte dữ liệu đầu tiên; từ đó suy ra vì sao mở lại kết nối cho mỗi yêu cầu là lãng phí và vì sao cần hồ kết nối. Số thứ tự và xác nhận, truyền lại khi mất gói, và vì sao truyền lại làm độ trễ tăng đột biến chứ tăng dần. Cửa sổ và kiểm soát luồng: bên nhận báo mình còn chứa được bao nhiêu, đây là áp lực ngược ở tầng mạng và cùng ý tưởng với hàng đợi có giới hạn ở lesson 30. Đóng kết nối và trạng thái chờ đóng: vì sao nó tồn tại và vì sao tích tụ nhiều gây cạn cổng tạm. Đặt lại kết nối khác hết giờ: một cái là bên kia chủ động từ chối, một cái là im lặng.",
"Từ một bản bắt gói, phân biệt được truyền lại, đặt lại kết nối và lỗi ở tầng ứng dụng.",
"Tầng *phân tích*. Objective là đọc bằng chứng thô, kỹ năng mà không đọc được thì mọi chẩn đoán mạng đều là phỏng đoán. Kiểm bằng ba bản bắt gói; đạt khi phân loại đúng ít nhất hai và chỉ ra được gói cụ thể làm bằng chứng.",
"Bắt gói cho ba tình huống: mạng mất gói mô phỏng, dịch vụ từ chối kết nối, và dịch vụ trả về lỗi ứng dụng. Với mỗi bản, chỉ ra gói nào là bằng chứng và phân loại. Đếm số socket ở trạng thái chờ đóng sau khi chạy 10.000 kết nối ngắn, rồi chạy lại với hồ kết nối và đếm lại.",
"Nhầm đặt lại kết nối với hết giờ · mở kết nối mới cho mỗi yêu cầu · bỏ qua trạng thái chờ đóng tới khi cạn cổng · kết luận từ nhật ký ứng dụng mà không bắt gói.",
"Phân loại đúng ≥ 2/3 bản bắt gói kèm gói làm bằng chứng, và số socket chờ đóng giảm rõ rệt khi dùng hồ kết nối."),

(80,"TLS - certificates, verification and the handshake cost","TH","Lesson 79",
"Lớp mã hoá thêm hai thứ vào mọi kết nối: chi phí bắt tay và một tập lỗi mới. Chuỗi chứng chỉ và xác minh: máy khách kiểm chứng chỉ có do một gốc tin cậy ký không, còn hạn không, và **tên miền có khớp không**; bỏ qua bước cuối là lỗ hổng chứ tiện lợi. Bắt tay tốn thêm vòng khứ hồi, sau đó chuyển sang mã hoá đối xứng rẻ hơn nhiều; nên chi phí nằm ở lúc mở kết nối và đây là lý do nữa để dùng hồ kết nối. Ba lỗi hay gặp và cách phân biệt: chứng chỉ hết hạn, tên miền không khớp, và thiếu chứng chỉ trung gian; lỗi thứ ba đặc biệt khó vì trình duyệt thường tự vá được còn thư viện thì không, nên chạy được trên trình duyệt mà hỏng trong mã. Xác thực hai chiều ở mức nhận biết. Ba cách tắt xác minh và vì sao cả ba đều không được xuất hiện trong mã sản xuất.",
"Chẩn đoán ba loại lỗi chứng chỉ bằng công cụ dòng lệnh và giải thích vì sao trình duyệt chạy được mà thư viện thì không.",
"Tầng *phân tích*. Objective là phân biệt ba lỗi có cùng thông báo mơ hồ. Kiểm bằng ba tình huống; đạt khi phân loại đúng cả ba và giải thích đúng trường hợp thiếu chứng chỉ trung gian.",
"Dựng ba tình huống lỗi chứng chỉ. Với mỗi cái, dùng công cụ dòng lệnh xem chuỗi chứng chỉ và xác định nguyên nhân. Với trường hợp thiếu chứng chỉ trung gian, chứng minh trình duyệt gọi được còn thư viện thì lỗi. Đo chi phí bắt tay bằng cách so thời gian yêu cầu đầu với yêu cầu sau trên cùng kết nối.",
"Tắt xác minh chứng chỉ để hết lỗi · kết luận từ thông báo lỗi của thư viện mà không xem chuỗi chứng chỉ · quên chứng chỉ trung gian · đo chi phí bắt tay trên kết nối đã mở sẵn.",
"Phân loại đúng cả ba lỗi chứng chỉ, giải thích đúng trường hợp thiếu chứng chỉ trung gian, và có số đo chi phí bắt tay."),

(81,"HTTP semantics - methods, status, idempotency and caching","LT","Lesson 80",
"Giao thức ứng dụng phổ biến nhất, và phần quan trọng với người làm dữ liệu là ngữ nghĩa chứ cú pháp. Phương thức và hai tính chất tách bạch: an toàn nghĩa là không đổi trạng thái, bất biến nghĩa là gọi lại cho cùng kết quả; **bất biến là tính chất quyết định có được thử lại hay không**, và đây là cầu nối trực tiếp tới lesson 30. Mã trạng thái theo nhóm và cách xử lý từng nhóm khi nạp dữ liệu: nhóm lỗi máy khách thường không nên thử lại, nhóm lỗi máy chủ thì nên, và mã báo quá nhiều yêu cầu cần chờ theo tiêu đề máy chủ trả về. Tiêu đề quan trọng với việc nạp dữ liệu: nén, kiểu nội dung, phân trang, và giới hạn tốc độ. Bộ đệm và các tiêu đề điều khiển. Giữ kết nối sống và ghép nhiều yêu cầu trên một kết nối, nối lại chi phí bắt tay ở lesson 79 và 80.",
"Quyết định một yêu cầu thất bại có được thử lại hay không dựa trên phương thức và mã trạng thái.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho lesson 83 và cho M14B; chưa đòi cài đặt. Kiểm bằng bảng quyết định trên mười tổ hợp; đạt khi đúng ít nhất tám và giải thích được bằng tính bất biến chứ bằng thói quen.",
"Cho mười tổ hợp phương thức và mã trạng thái. Với mỗi tổ hợp, quyết định có thử lại không và giải thích bằng tính bất biến cùng ngữ nghĩa mã trạng thái. Gọi một giao diện thật có giới hạn tốc độ và đọc tiêu đề cho biết phải chờ bao lâu.",
"Thử lại mọi lỗi · thử lại một yêu cầu tạo tài nguyên mà không có khoá bất biến · bỏ qua tiêu đề chờ của giới hạn tốc độ · nhầm an toàn với bất biến.",
"Quyết định đúng ≥ 8/10 tổ hợp kèm giải thích bằng tính bất biến, và đọc đúng tiêu đề chờ từ giao diện thật."),

(82,"Proxies, load balancers and what they hide","LT","Lesson 81",
"Giữa máy khách và máy chủ hiếm khi chỉ có một chặng, và mỗi thứ đứng giữa đều thêm trạng thái cùng hạn chờ riêng. Phân biệt proxy chuyển tiếp với proxy đảo: một cái đại diện cho máy khách, một cái đại diện cho máy chủ. Cân bằng tải ở tầng bốn và tầng bảy: tầng bốn chỉ nhìn địa chỉ và cổng nên nhanh và không hiểu giao thức; tầng bảy đọc được nội dung nên định tuyến theo đường dẫn được nhưng tốn hơn. Kiểm tra sức khoẻ và khác biệt giữa kiểm tiến trình còn sống với kiểm dịch vụ còn phục vụ được, một khác biệt sẽ gặp lại ở M20. Phiên dính và vì sao nó làm việc mở rộng khó. Ba thứ lớp trung gian che mất và gây chẩn đoán sai: địa chỉ thật của máy khách, lỗi thật của máy chủ gốc, và hạn chờ của chính nó thường ngắn hơn hạn chờ của ứng dụng nên cắt kết nối trước. Mạng phân phối nội dung ở mức nhận biết.",
"Chỉ ra trong một kiến trúc có lớp trung gian chỗ nào có thể cắt kết nối trước ứng dụng, và nêu cách xác minh.",
"Tầng *hiểu*. Objective là nhận ra nguồn gây nhầm lẫn khi chẩn đoán qua nhiều chặng. Kiểm bằng ba kiến trúc; đạt khi chỉ đúng ít nhất hai chặng có hạn chờ riêng và nêu đúng cách xác minh.",
"Dựng một proxy đảo đứng trước hai bản sao dịch vụ. Đặt hạn chờ của proxy ngắn hơn thời gian xử lý của dịch vụ và quan sát máy khách nhận lỗi gì. Tắt một bản sao và quan sát kiểm tra sức khoẻ loại nó ra. Thử kiểm tra sức khoẻ chỉ kiểm tiến trình còn sống trong khi dịch vụ đã mất kết nối cơ sở dữ liệu.",
"Nghĩ lỗi đến từ ứng dụng trong khi proxy cắt trước · dùng kiểm tra sức khoẻ chỉ kiểm tiến trình · bật phiên dính mà không cần · quên rằng lớp trung gian che địa chỉ máy khách thật.",
"Chỉ đúng ≥ 2/3 chặng có hạn chờ riêng, và chứng minh được kiểm tra sức khoẻ sai loại không phát hiện dịch vụ đã hỏng."),

(83,"Timeout budgets, retries and connection pools","TH","Lesson 82",
"Bài quan trọng nhất của module với người làm dữ liệu, vì nó quyết định pipeline có chịu được nguồn chậm hay không. Ba hạn chờ phải đặt riêng và đặt đủ: hạn mở kết nối, hạn chờ dữ liệu, và hạn tổng cho cả yêu cầu; thiếu hạn tổng thì một nguồn trả từng byte rất chậm sẽ giữ kết nối vô hạn. Ngân sách hạn chờ theo tầng: hạn của tầng ngoài phải lớn hơn tổng hạn của các tầng trong cộng với thời gian thử lại, nếu không thì tầng ngoài cắt trước và mọi thử lại bên trong thành vô ích. Khuếch đại thử lại: ba tầng mỗi tầng thử ba lần cho ra 27 lần gọi thật, nên **thử lại phải có ngân sách toàn tuyến chứ đặt độc lập từng tầng**. Lùi theo hàm mũ có nhiễu ngẫu nhiên, theo lesson 30. Hồ kết nối: kích thước hồ là một giới hạn đồng thời, và hồ cạn biểu hiện giống mạng chậm nên hay bị chẩn đoán nhầm.",
"Đặt ngân sách hạn chờ nhất quán cho một tuyến ba tầng và chứng minh không có khuếch đại thử lại.",
"Tầng *áp dụng*. Objective là một cấu hình có ràng buộc số học kiểm được bằng đếm lời gọi thật. Kiểm bằng thí nghiệm nguồn chậm; đạt khi tổng số lời gọi thật nằm trong ngân sách và không yêu cầu nào treo quá hạn tổng.",
"Dựng tuyến ba tầng gọi nhau. Đặt hạn chờ độc lập mỗi tầng thử ba lần, đếm số lời gọi thật tới tầng cuối khi nó lỗi. Đặt lại theo ngân sách toàn tuyến và đếm lại. Mô phỏng nguồn trả byte rất chậm và chứng minh hạn tổng cắt đúng lúc. Làm cạn hồ kết nối và ghi triệu chứng.",
"Chỉ đặt một hạn chờ chung · để thử lại độc lập từng tầng · không có hạn tổng · chẩn đoán hồ cạn thành mạng chậm.",
"Tổng lời gọi thật nằm trong ngân sách đã đặt, hạn tổng cắt đúng với nguồn trả chậm, và mô tả đúng triệu chứng hồ cạn."),

(84,"Designing an API client for data ingestion","TH","Lesson 83",
"Bài ghép, và kết quả của nó được dùng lại nguyên vẹn ở M14B. Sáu yêu cầu của một trình gọi giao diện lập trình web dùng để nạp dữ liệu. Ba hạn chờ theo lesson 83. Thử lại có lùi và nhiễu, chỉ cho lỗi đáng thử lại theo lesson 81. Tôn trọng giới hạn tốc độ bằng cách đọc tiêu đề máy chủ trả về chứ đoán. Phân trang: ba kiểu phân trang và **vì sao phân trang theo số trang không an toàn khi dữ liệu đang thay đổi**, một chi tiết sẽ quay lại ở M14B. Khoá bất biến khi ghi để thử lại không sinh trùng. Và ghi nhật ký có mã theo dõi theo lesson 20 để truy ngược được. Kèm theo là một phần thường bị bỏ: lưu trạng thái đã nạp tới đâu để lần chạy sau tiếp tục được thay vì bắt đầu lại.",
"Viết trình gọi đạt sáu yêu cầu và chứng minh nó nạp đủ, không trùng, dưới điều kiện nguồn lỗi và giới hạn tốc độ.",
"Tầng *sáng tạo*. Objective đòi ghép sáu cơ chế thành một thành phần chịu lỗi. Kiểm bằng thí nghiệm nguồn xấu; đạt khi đối soát khớp tuyệt đối dưới cả ba điều kiện lỗi.",
"Dựng một máy chủ giả có phân trang, giới hạn tốc độ, lỗi ngẫu nhiên 10%, và chèn thêm bản ghi giữa lúc đang phân trang. Viết trình gọi đạt sáu yêu cầu. Nạp toàn bộ và đối soát số bản ghi với nguồn. Giết tiến trình giữa chừng và chứng minh lần chạy sau tiếp tục đúng chỗ.",
"Phân trang theo số trang trên dữ liệu đang đổi · thử lại mà không có khoá bất biến · đoán thời gian chờ thay vì đọc tiêu đề · không lưu trạng thái nên chạy lại từ đầu.",
"Đối soát khớp tuyệt đối dưới cả ba điều kiện lỗi, và sau khi giết tiến trình thì lần chạy sau tiếp tục đúng chỗ."),

(85,"Building a TCP protocol with framing","TH","Lesson 84",
"Bài này dạy một thứ mà dùng thư viện sẵn sẽ không bao giờ thấy: dòng byte không có ranh giới thông điệp. Giao thức bảo đảm thứ tự byte nhưng **không bảo đảm một lần đọc trả về đúng một thông điệp**; một lần đọc có thể trả về nửa thông điệp hoặc hai thông điệp rưỡi. Từ đó suy ra mọi giao thức trên nó đều phải tự đóng khung: theo độ dài đặt trước, theo ký tự phân tách, hoặc theo độ dài cố định. Đọc thiếu là lỗi kinh điển của người tự viết giao thức và biểu hiện là dữ liệu hỏng ngẫu nhiên khi tải cao. Ba tình huống hỏng phải xử lý: máy khách ngắt giữa chừng, máy khách gửi rất chậm, và máy khách gửi thông điệp lớn bất thường. Vì sao bài này quan trọng dù ít khi phải tự viết giao thức: nó giải thích vì sao thư viện có tham số kích thước bộ đệm và vì sao dữ liệu hỏng ở biên thông điệp.",
"Cài một giao thức có đóng khung xử lý đúng ba tình huống hỏng, và tái hiện được lỗi do đọc thiếu.",
"Tầng *áp dụng*. Objective là một cài đặt có ba ca biên kiểm được. Kiểm bằng ba phép thử hỏng; đạt khi cả ba được xử lý đúng và tái hiện được lỗi đọc thiếu ở bản chưa sửa.",
"Viết máy chủ lặp lại có đóng khung theo độ dài. Cố ý cài bản đọc thiếu và tái hiện dữ liệu hỏng khi tải cao. Sửa. Tiêm ba tình huống: ngắt giữa chừng, gửi rất chậm, và thông điệp vượt giới hạn. Chứng minh máy chủ xử lý đúng cả ba mà không treo và không cạn bộ nhớ.",
"Giả định một lần đọc trả về đúng một thông điệp · không giới hạn kích thước thông điệp · treo vô hạn với máy khách gửi chậm · không đóng khung mà dựa vào kích thước gói.",
"Ba tình huống hỏng đều được xử lý đúng, và tái hiện được dữ liệu hỏng ở bản đọc thiếu."),

(86,"Diagnosing latency across the whole path","TH","Lesson 85",
"Bài tổng hợp phần chẩn đoán. Một yêu cầu chậm có thể chậm ở sáu chặng và mỗi chặng có cách đo riêng: phân giải tên, mở kết nối, bắt tay mã hoá, gửi yêu cầu, chờ máy chủ xử lý, và nhận phản hồi. Công cụ dòng lệnh tách được thời gian theo từng chặng, và đây là bước đầu tiên nên làm thay vì đoán. Nguyên tắc: **đo phân vị cao chứ trung bình**, vì độ trễ hầu như luôn có đuôi dài và người dùng cảm nhận đuôi đó. Ba nguyên nhân chậm có triệu chứng giống nhau và cách phân biệt: mạng mất gói gây truyền lại, máy chủ xử lý chậm, và hồ kết nối cạn ở phía máy khách. Đo từ nhiều phía: chỉ đo ở máy khách thì không biết phần nào là mạng và phần nào là máy chủ, nên phải đối chiếu với nhật ký phía máy chủ qua mã theo dõi ở lesson 20.",
"Phân rã độ trễ của một yêu cầu thành sáu chặng và chỉ ra chặng chiếm phần lớn thời gian.",
"Tầng *phân tích*. Objective là phân rã một số đo tổng thành thành phần, kỹ năng dùng lại ở M21. Kiểm bằng ba tình huống chậm; đạt khi chỉ đúng chặng nút thắt ở ít nhất hai và dẫn được số đo của chặng đó.",
"Giảng viên tạo ba tình huống chậm ở ba chặng khác nhau. Với mỗi cái, đo tách theo chặng, báo phân vị 95, và chỉ ra chặng nút thắt. Đối chiếu số đo phía máy khách với nhật ký phía máy chủ qua mã theo dõi để tách phần mạng khỏi phần xử lý.",
"Báo độ trễ trung bình · chỉ đo ở một phía · kết luận mạng chậm mà chưa bắt gói · bỏ qua chặng phân giải tên.",
"Chỉ đúng chặng nút thắt ở ≥ 2/3 tình huống kèm số đo, và tách được phần mạng khỏi phần xử lý bằng đối chiếu hai phía."),

(87,"Rate limiting and backpressure between services","TH","Lesson 86",
"Hai mặt của cùng một vấn đề: bên gọi phải tự kiềm chế, và bên bị gọi phải tự bảo vệ. Giới hạn tốc độ ở phía máy chủ: ba thuật toán thường dùng và khác biệt về hành vi khi có đợt dồn. Phía máy khách: đọc tiêu đề giới hạn và tự điều tiết thay vì cứ gọi tới khi bị chặn, theo lesson 81. Áp lực ngược giữa các dịch vụ không có cơ chế tự động như trong một tiến trình, nên phải dựng bằng tay: hàng đợi có giới hạn, từ chối khi đầy, và báo cho bên gọi biết. Giảm tải chủ động: khi quá tải thì từ chối một phần để phần còn lại được phục vụ đúng, và tiêu chí chọn từ chối cái gì phải theo mức ưu tiên nghiệp vụ chứ ngẫu nhiên. Bộ ngắt mạch: ngừng gọi khi bên kia đang hỏng, để không lãng phí tài nguyên vào những lời gọi chắc chắn thất bại và để bên kia có cơ hội hồi phục. Ba cơ chế này sẽ gặp lại ở M21.",
"Dựng giới hạn tốc độ và bộ ngắt mạch cho một tuyến, và chứng minh hệ suy giảm có kiểm soát khi quá tải.",
"Tầng *áp dụng*. Objective là hai cơ chế phòng vệ kiểm được bằng thí nghiệm quá tải. Kiểm bằng phép thử tải gấp năm lần công suất; đạt khi phần ưu tiên cao vẫn được phục vụ và không thành phần nào cạn tài nguyên.",
"Dựng giới hạn tốc độ ở máy chủ và bộ ngắt mạch ở máy khách. Đẩy tải gấp năm lần công suất và đo tỉ lệ phục vụ của phần ưu tiên cao, có và không có giảm tải. Làm máy chủ hỏng hoàn toàn và chứng minh bộ ngắt mạch ngừng gọi thay vì tiếp tục thử.",
"Không có giới hạn nên máy chủ sập · thử lại ngay khi bị từ chối · giảm tải ngẫu nhiên thay vì theo ưu tiên · bộ ngắt mạch không bao giờ đóng lại.",
"Phần ưu tiên cao vẫn được phục vụ ở mức chấp nhận được khi quá tải, và bộ ngắt mạch ngừng gọi khi máy chủ hỏng hoàn toàn."),

(88,"Gate 2 - trace a request and diagnose the system","KT","Lesson 87",
"Cổng của Phase 2. Bài kiểm ba năng lực: mô hình chi phí phần cứng ở M4, chẩn đoán hệ điều hành ở M5, và theo vết mạng ở M6. Không có nội dung mới.",
"Chẩn đoán đúng ba sự cố thuộc ba tầng khác nhau, mỗi kết luận dẫn được về số đo hoặc gói tin làm bằng chứng.",
"Tầng *phân tích*. Cổng đo năng lực chẩn đoán dưới áp lực thời gian, nên hình thức là buổi thực hành tính giờ chứ bài viết.",
"Buổi 120 phút: 75 phút làm bài độc lập, 45 phút chữa bài. Làm trên một hệ có ba sự cố cài sẵn ở ba tầng. Bài chấm sáu phần: A (20đ) phân loại đúng loại tải bằng chỉ số hệ thống · B (20đ) chẩn đoán sự cố mạng bằng bản bắt gói, chỉ đúng gói làm bằng chứng · C (20đ) giải thích một hiện tượng hiệu năng bằng mô hình chi phí, dẫn số đo của chính mình · D (15đ) sửa cả ba và xác nhận đã hồi phục · E (15đ) dòng thời gian chẩn đoán có ghi nhánh sai đã thử · F (10đ) báo cáo hiệu năng sáu phần cho một phép đo trong buổi.",
"Khởi động lại hệ rồi mất bằng chứng · kết luận từ một chỉ số · đoán trúng mà không có bằng chứng · bỏ phần dòng thời gian vì hết giờ.",
"Đạt ≥ 70/100, phần A và B đều ≥ 60%. Kết luận nào không dẫn được về số đo hoặc gói tin thì phần đó bằng không."),
]
