# -*- coding: utf-8 -*-
"""ADE Phase 7b: M14C Data quality and reliability + M14D Metadata, lineage and governance."""

M14C = ("Data Quality and Data Reliability Engineering", 275, 292, """| | |
|---|---|
| **Objective cấp module** | Biến câu dữ liệu đúng thành hợp đồng, bất biến, cam kết dịch vụ, chốt kiểm soát và một vòng đời sự cố có phục hồi |
| **Tiền đề** | M9 · M10 · M11 · M14B · M14 |
| **Exit criterion** | Kế hoạch kiểm soát theo tầng có chủ sở hữu, mức nghiêm trọng, hành động và đường phục hồi cho mọi tài sản trọng yếu; hai sự cố được sửa, đối soát và ghi lại |
| **Kỹ năng SFIA** | `DTAN` mức 5 · `USUP` mức 4 |
| **Chế độ hỏng** | Dùng số lượng phép kiểm làm bằng chứng độ phủ mà không ánh xạ với rủi ro, và chọn ngưỡng sao cho bảng theo dõi luôn xanh |""",
"""**Module bù năng lực Analytics Engineer thứ ba.** Nó sở hữu tính đúng, tính đầy đủ và tính kịp thời của dữ liệu, cùng toàn bộ vòng đời sự cố dữ liệu.

Ranh giới lấy từ hợp đồng nguồn: sửa lỗi ở khâu nạp thuộc M14B, sửa lỗi mô hình thuộc M11 và M14, còn nền tảng quan sát và bảo mật đi tiếp ở M21.

Hai nhầm lẫn bị bác bỏ ngay từ bài đầu và được kiểm lại ở cổng: **nhiều phép kiểm không đồng nghĩa với dữ liệu đáng tin**, và **tính chính xác thường không chứng minh được chỉ từ dữ liệu ở đích**.""")

L14C = [
(275,"Quality dimensions defined operationally","LT","Module 14C: M14",
"Bài mở module bằng việc đổi bảy tính từ mơ hồ thành bảy định nghĩa quan sát được, vì không quan sát được thì không kiểm được. Đầy đủ: đủ bản ghi và đủ trường đã kỳ vọng cho một phân vùng. Hợp lệ: đúng miền giá trị, kiểu, khoảng và định dạng. Duy nhất: một thực thể hoặc sự kiện xuất hiện đúng số lần quy định. Nhất quán: các biểu diễn tuân thủ quy tắc xuyên hệ. Kịp thời: sẵn sàng trước một thời điểm nghiệp vụ. Toàn vẹn: quan hệ và chuyển trạng thái được giữ. Chính xác: giá trị khớp thực tế đáng tin cậy, và đây là chiều khác hẳn sáu chiều kia. **Tính chính xác thường không chứng minh được chỉ từ dữ liệu ở đích**, vì đích không biết thế giới thật; muốn chứng minh phải có một nguồn có thẩm quyền để đối chiếu, còn không thì phải nói rõ đang dùng một đại lượng thay thế. Phân biệt hợp lệ với chính xác bằng ví dụ: một số tiền đúng định dạng và đúng khoảng vẫn có thể sai.",
"Chuyển bảy chiều thành định nghĩa quan sát được cho một tài sản thật và chỉ ra chiều nào không tự kiểm được.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng và đặt một giới hạn nhận thức. Kiểm bằng bài định nghĩa bảy chiều; đạt khi mỗi chiều có một phép quan sát cụ thể và chiều chính xác được nêu rõ cần nguồn đối chiếu nào.",
"Với một bảng phục vụ thật, viết định nghĩa quan sát được cho cả bảy chiều, mỗi cái kèm phép đo. Chỉ ra chiều nào cần nguồn có thẩm quyền bên ngoài. Tìm ba ví dụ dữ liệu hợp lệ nhưng không chính xác trong chính dữ liệu của mình. Nếu chưa có nguồn đối chiếu, viết rõ đang dùng đại lượng thay thế nào và giới hạn của nó.",
"Gọi dữ liệu là chất lượng cao mà không nói theo chiều nào · tuyên bố chính xác dựa trên phép kiểm chạy ở đích · gộp hợp lệ với chính xác · định nghĩa chiều bằng tính từ thay vì bằng phép quan sát.",
"Bảy chiều đều có phép quan sát cụ thể, và chiều chính xác được nêu rõ nguồn đối chiếu hoặc nêu rõ đại lượng thay thế cùng giới hạn."),

(276,"Rule anatomy - seven parts","TH","Lesson 275",
"Một quy tắc chất lượng thiếu phần nào thì hỏng theo một kiểu tương ứng, nên bài này đặt ra bảy phần bắt buộc. Tài sản, trường và phân vùng cùng bối cảnh nghiệp vụ. Bất biến hoặc truy vấn hoặc kỳ vọng thống kê. Ngưỡng, cửa sổ và đường cơ sở. Mức nghiêm trọng và hành động, chọn một trong bốn: cảnh báo, cách ly, chặn, hoặc quay lui. Chủ sở hữu và đường leo thang cùng ảnh hưởng tới bên tiêu thụ. Ngoại lệ có thời hạn và cách khắc phục. Bằng chứng được giữ lại cùng chi phí chạy. Phần thứ tư là phần hay bị bỏ nhất và bỏ nó gây hậu quả cụ thể: **một quy tắc không nói rõ hành động thì khi nó đỏ không ai biết phải chặn hay chỉ ghi nhận**, nên sau vài tuần nó bị tắt. Ngoại lệ phải có ngày hết hạn, nếu không thì danh sách miễn trừ chỉ dài thêm. Sổ đăng ký quy tắc nằm trong kho mã và được rà soát cùng mã.",
"Viết sổ đăng ký quy tắc đủ bảy phần cho bốn tầng dữ liệu và chỉ ra hậu quả của từng phần bị thiếu.",
"Tầng *áp dụng*. Objective là một chuẩn tài liệu có thể rà soát máy móc. Kiểm bằng rà soát sổ đăng ký; đạt khi mọi quy tắc đủ bảy phần và mỗi quy tắc có hành động nằm trong bốn lựa chọn cho phép.",
"Lập sổ đăng ký cho ít nhất 20 quy tắc phủ bốn tầng. Với mỗi quy tắc, điền đủ bảy phần. Viết một phép kiểm tự động chặn mọi quy tắc thiếu phần bắt buộc. Với ba quy tắc, cố ý bỏ một phần khác nhau và mô tả chế độ hỏng vận hành nó gây ra. Đặt hạn cho mọi ngoại lệ đang có.",
"Viết quy tắc mà không nói hành động khi đỏ · gán chủ sở hữu là một phòng ban · miễn trừ không có ngày hết hạn · không ghi chi phí chạy nên quy tắc đắt bị tắt lặng lẽ.",
"20 quy tắc đủ bảy phần, phép kiểm tự động chặn quy tắc thiếu phần, và mọi ngoại lệ đều có ngày hết hạn."),

(277,"Layered controls - where each check belongs","LT","Lesson 276",
"Đặt phép kiểm sai tầng vừa tốn vừa bắt muộn, nên bài này ánh xạ từng loại kiểm vào từng tầng. Trước khi nạp: hợp đồng nguồn, lược đồ, khoá, ngữ nghĩa thay đổi, khối lượng và lịch kỳ vọng. Vùng thô: tổng kiểm tra tệp, giải mã được lược đồ, trùng lặp, dữ liệu hỏng hoặc cụt; **giữ lại tải trọng bị từ chối cùng xuất xứ, không bỏ im lặng**. Tầng chuẩn hoá: kiểu, miền giá trị, giá trị rỗng, khử trùng, toàn vẹn tham chiếu, quy tắc thời gian và thứ tự, kèm vùng cách ly có lý do và đường phát lại. Tầng phục vụ: tính duy nhất theo hạt, quan hệ, khoảng hiệu lực của chiều biến đổi chậm, đối soát tổng hợp, bất biến chỉ số và tương thích với tầng ngữ nghĩa. Tầng tiêu thụ: độ tươi, đầy đủ, bảo mật, đối soát giữa bảng điều khiển với chỉ số, và trạng thái suy giảm hiển thị cho người dùng. Nguyên tắc chọn tầng: bắt càng sớm càng rẻ, nhưng bất biến nghiệp vụ chỉ kiểm được ở tầng có đủ ngữ cảnh.",
"Ánh xạ 20 phép kiểm vào đúng tầng và giải thích ba phép kiểm không thể đặt sớm hơn.",
"Tầng *hiểu*. Bài lý thuyết đặt bản đồ cho tám bài thực hành sau. Kiểm bằng bài ánh xạ; đạt khi đặt đúng ít nhất 16 và ba ca không đặt sớm được có lý do dựa trên ngữ cảnh cần thiết.",
"Cho 20 phép kiểm và năm tầng. Ánh xạ từng cái vào tầng rẻ nhất mà nó vẫn bắt được lỗi. Với ba phép kiểm phải đặt muộn, giải thích ngữ cảnh nào chỉ có ở tầng đó. Rà đường dẫn hiện có và tìm mọi chỗ dữ liệu bị bỏ im lặng, rồi chuyển sang cách ly có lý do.",
"Dồn mọi phép kiểm vào tầng phục vụ · bỏ bản ghi hỏng thay vì cách ly · kiểm bất biến nghiệp vụ ở vùng thô nơi chưa đủ ngữ cảnh · trộn dữ liệu cách ly với dữ liệu đã nhận.",
"Ánh xạ đúng ≥ 16/20 phép kiểm, ba ca đặt muộn có lý do dựa trên ngữ cảnh, và không còn chỗ nào bỏ dữ liệu im lặng."),

(278,"Schema and contract tests at the boundary","TH","Lesson 277",
"Tầng kiểm rẻ nhất và bắt sớm nhất, chạy ngay tại ranh giới giữa hai hệ. Bốn nhóm: tên và kiểu trường; trường bắt buộc và giá trị mặc định; tương thích giữa phiên bản bên ghi và bên đọc theo ma trận bốn ô ở lesson 220; và ngữ nghĩa khoá cùng cách thay đổi. Hợp đồng bên sản xuất khai báo lược đồ, khoá, ngữ nghĩa thay đổi và xoá, cam kết dịch vụ cùng chủ sở hữu; hợp đồng bên tiêu thụ khai báo hạt, ý nghĩa, độ tươi, mức tương thích cần và yêu cầu bảo mật. Hai hợp đồng gặp nhau ở một điểm và chênh lệch giữa chúng là thứ phải phát hiện trước khi chạy. Chạy phép kiểm hợp đồng ở cả hai phía khi thẩm quyền cho phép: bên sản xuất chạy để biết mình sắp phá vỡ ai, bên tiêu thụ chạy để biết mình đang dựa vào gì. **Miễn trừ phải có chủ sở hữu, lý do, hạn và một biện pháp bù**, nếu không thì nó là một cách tắt phép kiểm có giấy tờ.",
"Cài phép kiểm hợp đồng ở cả hai phía và chặn được một thay đổi phá vỡ trước khi nó tới môi trường chạy.",
"Tầng *áp dụng*. Objective là một cửa chặn hai phía có tiêu chí nghiệm thu bằng phép thử tiêm. Kiểm bằng ba thay đổi phá vỡ; đạt khi cả ba bị chặn ở phía sản xuất và mọi miễn trừ đang có đều đủ bốn phần.",
"Viết hợp đồng bên sản xuất và bên tiêu thụ cho hai tài sản. Cài phép kiểm hợp đồng chạy ở cả hai phía trong tích hợp liên tục. Tiêm ba thay đổi phá vỡ khác loại và xác nhận bị chặn kèm thông báo chỉ rõ bên tiêu thụ nào ảnh hưởng. Rà mọi miễn trừ đang có và bổ sung chủ sở hữu, lý do, hạn cùng biện pháp bù.",
"Chỉ chạy phép kiểm hợp đồng ở phía tiêu thụ · miễn trừ không có hạn · không liệt kê bên tiêu thụ ảnh hưởng khi chặn · coi lược đồ khớp là hợp đồng được tôn trọng.",
"Ba thay đổi phá vỡ bị chặn ở phía sản xuất kèm danh sách bên tiêu thụ ảnh hưởng, và mọi miễn trừ đủ bốn phần."),

(279,"Row, aggregate and relationship tests","TH","Lesson 278",
"Ba nhóm phép kiểm phủ ba loại lỗi khác nhau, và dùng một nhóm thay cho nhóm khác là nguồn của lỗ hổng. Kiểm theo dòng xét từng bản ghi: miền giá trị, khoảng, mẫu, giá trị rỗng và ràng buộc có điều kiện; nó bắt được bản ghi xấu nhưng **không bắt được lỗi mà mọi dòng đều hợp lệ**. Kiểm tổng hợp xét phân bố theo phân vùng hoặc theo nhóm: số dòng, tổng, và hình dạng phân bố; đây là nhóm duy nhất bắt được lỗi nhân dòng do phép kết, vì từng dòng vẫn hợp lệ còn tổng thì gấp đôi. Kiểm quan hệ xét khoá mồ côi, bản số và phân bổ trong quan hệ nhiều nhiều theo lesson 156. Ví dụ đối chiếu bắt buộc chạy: một phép kết sai làm chỉ số gấp đôi thì kiểm theo dòng xanh hết, chỉ đối soát tổng mới thấy; và một phân vùng thiếu hoàn toàn thì kiểm theo dòng không chạy lần nào nên cũng xanh.",
"Chứng minh bằng dữ liệu rằng kiểm theo dòng bỏ sót hai loại lỗi, và bịt chúng bằng hai nhóm còn lại.",
"Tầng *phân tích*. Objective đòi nhận ra giới hạn của nhóm phép kiểm quen dùng nhất. Kiểm bằng hai lỗi tiêm; đạt khi cả hai lọt qua kiểm theo dòng, bị nhóm khác bắt, và độ phủ được ánh xạ theo loại lỗi chứ theo số lượng.",
"Cài đủ ba nhóm cho một mô hình phục vụ. Tiêm một phép kết nhân dòng và một phân vùng thiếu. Chứng minh kiểm theo dòng vẫn xanh ở cả hai. Thêm đối soát tổng và kiểm độ đầy đủ theo phân vùng kỳ vọng, rồi xác nhận bắt được. Lập bảng ánh xạ loại lỗi với nhóm phép kiểm bắt được nó.",
"Coi số lượng phép kiểm là độ phủ · chỉ kiểm theo dòng rồi kết luận dữ liệu sạch · không kiểm phân vùng kỳ vọng nên phân vùng thiếu không ai biết · kiểm quan hệ mà bỏ chiều bản số.",
"Hai lỗi tiêm lọt qua kiểm theo dòng và bị hai nhóm còn lại bắt, và bảng ánh xạ loại lỗi với nhóm phép kiểm đầy đủ."),

(280,"Temporal tests - late, out of order and overlap","TH","Lesson 279",
"Nhóm phép kiểm thứ tư, dành riêng cho lỗi về thời gian, vì chúng không lộ ra trong bất kỳ nhóm nào ở bài trước. Bốn loại kiểm: dữ liệu tới muộn vượt cửa sổ đã thoả thuận ở lesson 251; sự kiện tới sai thứ tự so với thời gian sự kiện; khoảng hiệu lực chồng nhau ở chiều biến đổi chậm theo lesson 157; và chuyển trạng thái đi ngược chiều trong một vòng đời. Loại thứ ba và thứ tư là bất biến chứ ngưỡng, nên chúng phải đỏ tuyệt đối chứ có dung sai. Một ca hỏng đặc trưng và bắt buộc tái hiện: **toàn bộ dữ liệu bị dịch múi giờ thì mọi kiểm kiểu và kiểm khoảng đều xanh**, vì giá trị vẫn hợp lệ, chỉ là thuộc sai ngày; cách bắt là một bộ dữ liệu đối chứng có mốc thời gian biết trước cùng một phép kiểm ranh giới ngày. Bộ đối chứng cố định là công cụ chính của nhóm này.",
"Cài bốn phép kiểm thời gian và bắt được ca dịch múi giờ mà mọi phép kiểm khác bỏ qua.",
"Tầng *phân tích*. Objective nhắm vào một lỗi đi qua được toàn bộ phép kiểm thông thường. Kiểm bằng bốn lỗi tiêm gồm ca dịch múi giờ; đạt khi cả bốn bị bắt và hai bất biến không có dung sai.",
"Cài bốn phép kiểm thời gian. Dựng một bộ đối chứng có mốc thời gian biết trước. Tiêm bốn lỗi: dữ liệu muộn vượt cửa sổ, sự kiện sai thứ tự, khoảng hiệu lực chồng nhau, và toàn bộ dữ liệu bị dịch một múi giờ. Chứng minh ba nhóm phép kiểm ở lesson 279 đều xanh với ca dịch múi giờ, còn phép kiểm ranh giới ngày thì đỏ.",
"Đặt dung sai cho bất biến khoảng hiệu lực · kiểm thời gian mà không có bộ đối chứng · giả định mốc thời gian nguồn luôn cùng múi giờ · bỏ kiểm chuyển trạng thái ngược chiều vì hiếm.",
"Bốn lỗi thời gian đều bị bắt, ca dịch múi giờ được chứng minh lọt qua ba nhóm kia, và hai bất biến chạy không dung sai."),

(281,"Metamorphic and property tests for pipelines","TH","Lesson 280",
"Nhóm phép kiểm không cần biết kết quả đúng là gì, chỉ cần biết quan hệ giữa hai lần chạy phải đúng; nhờ vậy nó kiểm được cả những chỗ không có kết quả kỳ vọng. Bốn quan hệ biến hình dùng được cho đường dẫn dữ liệu: đảo thứ tự bản ghi đầu vào không được đổi kết quả; chia đầu vào thành nhiều phân vùng rồi gộp phải cho cùng kết quả với chạy một lần; chạy lại với cùng đầu vào phải cho trạng thái tương đương, tức chính tính luỹ đẳng ở lesson 250; và nhân đôi một bản ghi phải làm kết quả đổi theo đúng cách đã khai báo chứ tuỳ. Kiểm theo tính chất sinh dữ liệu ngẫu nhiên có ràng buộc rồi khẳng định bất biến, nên nó tìm ra ca biên mà con người không nghĩ tới. **Giá trị lớn nhất của nhóm này là nó bắt lỗi logic thầm lặng**, loại lỗi mà kết quả vẫn hợp lệ và vẫn trông hợp lý.",
"Viết bốn phép kiểm biến hình cho một đường dẫn và bắt được một lỗi logic thầm lặng tiêm sẵn.",
"Tầng *áp dụng*. Objective nhắm vào loại lỗi mà mọi phép kiểm giá trị đều bỏ qua. Kiểm bằng lỗi logic tiêm; đạt khi bốn quan hệ chạy tự động và lỗi tiêm bị ít nhất một quan hệ phát hiện.",
"Viết bốn phép kiểm biến hình cho một mô hình phục vụ. Viết thêm một phép kiểm theo tính chất sinh 1.000 trường hợp có ràng buộc. Giảng viên sửa một dòng logic biến đổi sao cho kết quả vẫn hợp lệ nhưng sai; chạy toàn bộ phép kiểm và xác định quan hệ nào bắt được. Đo thời gian chạy của nhóm này và đặt lịch phù hợp.",
"Chỉ kiểm bằng giá trị kỳ vọng cố định · bỏ quan hệ chia rồi gộp vì nghĩ hiển nhiên đúng · sinh dữ liệu ngẫu nhiên không ràng buộc nên toàn ca vô nghĩa · chạy nhóm này ở mỗi lần nộp mã dù nó chậm.",
"Bốn quan hệ chạy tự động, lỗi logic thầm lặng bị ít nhất một quan hệ phát hiện, và nhóm này có lịch chạy phù hợp thời gian đo được."),

(282,"Statistical anomaly detection and its cost","TH","Lesson 281",
"Phát hiện bất thường bằng thống kê phủ được phần mà quy tắc tất định không phủ, nhưng nó có bản chất khác và phải dùng khác. Bốn yếu tố cấu hình: đường cơ sở, cửa sổ, tính mùa vụ, và cách phân đoạn dữ liệu trước khi so. Thống kê bền vững trước giá trị ngoại lai tốt hơn trung bình và độ lệch chuẩn, vì chính giá trị ngoại lai là thứ ta đang tìm. Nhận biết điểm đổi để phân biệt một thay đổi thật với một bất thường. Đánh đổi trung tâm phải định lượng: ngưỡng chặt cho nhiều báo giả và người trực sẽ bỏ qua cảnh báo, ngưỡng lỏng cho lỗi lọt; nên phải tính độ chính xác và độ phủ chứ chọn ngưỡng theo cảm giác. **Bất thường là tín hiệu để phân loại, không phải bằng chứng dữ liệu sai**, và nhầm điều này biến mọi thay đổi nghiệp vụ hợp lệ thành sự cố. Quy tắc tất định luôn được ưu tiên khi biểu diễn được bằng bất biến.",
"Cấu hình phát hiện bất thường cho ba chỉ số với độ chính xác và độ phủ được đo, không dùng nó thay bất biến.",
"Tầng *đánh giá*. Objective đòi cân hai loại sai lầm và biết ranh giới dùng của phương pháp. Kiểm bằng cặp số độ chính xác với độ phủ; đạt khi cả ba chỉ số có cặp số đo trên dữ liệu lịch sử và không bất biến nào bị thay bằng phát hiện thống kê.",
"Chọn ba chỉ số có tính mùa vụ khác nhau. Dựng đường cơ sở bằng thống kê bền vững, phân đoạn theo nguồn hoặc theo phân khúc. Chạy trên sáu tháng dữ liệu lịch sử đã gắn nhãn sự cố và sự kiện nghiệp vụ hợp lệ. Tính độ chính xác và độ phủ ở ba mức ngưỡng. Chỉ ra ba chỗ đang định dùng phát hiện thống kê nhưng viết được thành bất biến.",
"Dùng phát hiện thống kê cho thứ biểu diễn được bằng bất biến · dùng trung bình và độ lệch chuẩn trên dữ liệu có giá trị ngoại lai · bỏ tính mùa vụ nên mỗi thứ hai là một sự cố · coi bất thường là bằng chứng lỗi.",
"Ba chỉ số có cặp độ chính xác với độ phủ ở ba mức ngưỡng, và ba trường hợp viết lại được thành bất biến đã được chuyển."),

(283,"Backtesting rules against known incidents","TH","Lesson 282",
"Một quy tắc chưa chạy lại trên quá khứ là một quy tắc chưa biết có dùng được không, nên bài này đặt ra nghĩa vụ kiểm ngược. Quy trình bốn bước: gắn nhãn một tập lịch sử gồm cả khoảng có sự cố đã biết và khoảng bình thường có thay đổi nghiệp vụ hợp lệ; chạy bộ quy tắc trên toàn bộ tập; đếm bốn ô gồm bắt đúng, bỏ sót, báo giả và im đúng; rồi điều chỉnh ngưỡng cùng phạm vi. Hai kết quả phải xử lý khác nhau: quy tắc bỏ sót một sự cố đã biết là quy tắc chưa phủ rủi ro đó, cần thêm hoặc sửa; quy tắc báo giả ở một thay đổi nghiệp vụ hợp lệ là quy tắc sẽ bị tắt, cần thu hẹp phạm vi hoặc đổi mức nghiêm trọng. **Độ phủ phải ánh xạ theo rủi ro chứ đếm theo số quy tắc**, nên đầu ra của bài là một bảng rủi ro với quy tắc phủ nó chứ một con số.",
"Kiểm ngược bộ quy tắc trên sáu tháng dữ liệu có nhãn và nộp bảng ánh xạ rủi ro với quy tắc.",
"Tầng *đánh giá*. Objective thay phép đếm quy tắc bằng phép đo độ phủ rủi ro. Kiểm bằng bảng bốn ô cộng bảng rủi ro; đạt khi mọi rủi ro trọng yếu có ít nhất một quy tắc phủ và tỉ lệ báo giả nằm dưới ngưỡng thoả thuận.",
"Gắn nhãn sáu tháng dữ liệu gồm ba sự cố đã biết và bốn thay đổi nghiệp vụ hợp lệ. Chạy bộ quy tắc và lập bảng bốn ô. Với mỗi sự cố bị bỏ sót, thêm hoặc sửa quy tắc rồi chạy lại. Với mỗi báo giả, thu hẹp phạm vi hoặc hạ mức nghiêm trọng. Nộp bảng ánh xạ rủi ro với quy tắc phủ nó.",
"Báo cáo độ phủ bằng số lượng quy tắc · chỉ kiểm ngược trên khoảng có sự cố · giữ quy tắc báo giả nhiều vì nó đã từng bắt đúng một lần · không gắn nhãn thay đổi nghiệp vụ hợp lệ.",
"Mọi rủi ro trọng yếu có quy tắc phủ, ba sự cố lịch sử đều bị bắt sau khi sửa, và tỉ lệ báo giả dưới ngưỡng thoả thuận."),

(284,"The reconciliation ladder - seven levels","TH","Lesson 283",
"Bài mở rộng thang đối soát bốn bậc ở lesson 242 thành bảy bậc phủ toàn tuyến. Bậc một là kê khai tệp cùng tổng kiểm tra byte. Bậc hai là số dòng theo một ranh giới bất biến. Bậc ba là so tập khoá để biết thiếu, thừa hay trùng cụ thể. Bậc bốn là tổng kiểm soát theo lát cắt có nghĩa nghiệp vụ. Bậc năm là băm dòng trên giá trị đã chuẩn hoá. Bậc sáu là bất biến của quy trình nghiệp vụ xuyên nhiều tài sản. Bậc bảy là đối soát chỉ số hoặc báo cáo mà người dùng nhìn thấy, và đây là bậc duy nhất trả lời được câu người dùng có thấy đúng không. Chốt kiểm soát đặt ở bốn điểm: nguồn, vùng thô, tầng chuẩn hoá, tầng phục vụ; chênh lệch ở mỗi chốt quy được về một đoạn cụ thể thay vì một chênh lệch tổng không biết ở đâu. **Lấy mẫu hỗ trợ chẩn đoán nhưng không chứng minh được không mất và không trùng**, nên mọi tuyên bố phải nêu tổng thể, cửa sổ, phép kiểm và dung sai.",
"Chạy bảy bậc đối soát qua bốn chốt kiểm soát và quy được mọi chênh lệch về một đoạn cụ thể.",
"Tầng *áp dụng*. Objective đòi định vị chênh lệch chứ chỉ phát hiện. Kiểm bằng ba lỗi tiêm ở ba đoạn khác nhau; đạt khi cả ba được quy đúng đoạn và mọi tuyên bố đối soát nêu đủ bốn yếu tố phạm vi.",
"Dựng bộ đối soát chạy bảy bậc tại bốn chốt. Tiêm ba lỗi ở ba đoạn: mất dữ liệu khi nạp, nhân dòng khi biến đổi, và lệch làm tròn ở tầng phục vụ. Với mỗi lỗi, chỉ ra bậc nào và chốt nào phát hiện, rồi quy về đoạn gây ra. Viết một tuyên bố đối soát nêu rõ tổng thể, cửa sổ, phép kiểm và dung sai.",
"Chỉ đối soát hai đầu nên không biết chênh lệch sinh ở đâu · đối soát bằng lấy mẫu rồi tuyên bố đầy đủ · bỏ bậc bảy nên người dùng thấy sai mà hệ báo xanh · đối soát hai bên ở hai thời điểm khác nhau.",
"Ba lỗi tiêm được quy đúng đoạn gây ra, và tuyên bố đối soát nêu đủ tổng thể, cửa sổ, phép kiểm và dung sai."),

(285,"Normalization before comparison","TH","Lesson 284",
"Hai hệ cùng đúng vẫn cho hai kết quả đối soát khác nhau nếu chưa chuẩn hoá, nên chuẩn hoá là điều kiện để phép so có nghĩa. Bảy nhóm phải quy về một dạng trước khi so hoặc băm: giá trị rỗng so với thiếu so với chuỗi rỗng; khoảng trắng, chữ hoa chữ thường và dạng chuẩn ký tự; múi giờ và độ phân giải thời gian; số thập phân, cách làm tròn và đơn vị tiền tệ; thứ tự bản ghi và chính sách trùng lặp; thời điểm tham chiếu khi so với dữ liệu có lịch sử; và hiệu chỉnh từ nguồn cùng dung sai về độ trễ được chấp nhận. Nhóm thứ nhất và nhóm thứ tư gây nhiều chênh lệch giả nhất. **Chênh lệch giả nguy hiểm vì nó làm người vận hành quen với việc đối soát không khớp**, và khi có chênh lệch thật thì không ai để ý. Bộ quy tắc chuẩn hoá phải là mã dùng chung cho cả hai phía, chứ mỗi bên tự viết một bản.",
"Loại hết chênh lệch giả trên một cặp đối soát và chứng minh chênh lệch còn lại đều có nguyên nhân thật.",
"Tầng *phân tích*. Objective đòi tách chênh lệch giả khỏi chênh lệch thật. Kiểm bằng phép đối soát trước và sau chuẩn hoá; đạt khi số chênh lệch giả về không và mọi chênh lệch còn lại được nêu tên nguyên nhân.",
"Đối soát hai hệ khi chưa chuẩn hoá và đếm số chênh lệch. Phân loại từng chênh lệch vào bảy nhóm. Viết một thư viện chuẩn hoá dùng chung cho cả hai phía. Đối soát lại và chứng minh số chênh lệch giả về không. Với mỗi chênh lệch còn lại, nêu nguyên nhân thật. Đưa thư viện chuẩn hoá vào bộ kiểm để nó không lệch giữa hai phía.",
"Mỗi bên tự viết quy tắc chuẩn hoá · băm trực tiếp trên giá trị thô · coi chênh lệch nhỏ là chấp nhận được mà không tìm nguyên nhân · bỏ nhóm thời điểm tham chiếu khi so dữ liệu có lịch sử.",
"Số chênh lệch giả về không sau khi chuẩn hoá, mọi chênh lệch còn lại có nguyên nhân nêu tên, và thư viện chuẩn hoá dùng chung cho hai phía."),

(286,"Data SLI and SLO design","TH","Lesson 285",
"Cam kết chất lượng phải phát biểu được bằng số, nếu không thì nó là một lời hứa. Sáu chỉ số phục vụ: độ trễ tới khi sẵn sàng và thời điểm sẵn sàng cam kết; tỉ lệ phân vùng thành công và đầy đủ; tỉ lệ bản ghi hợp lệ và đã đối soát; tỉ lệ trùng, mồ côi và bị cách ly; thời gian phát hiện cùng thời gian phục hồi sự cố; và bằng chứng về tính đúng của truy vấn hoặc chỉ số đã chứng nhận. Thiết kế cam kết theo hành trình người dùng và mức trọng yếu nghiệp vụ trước, chứ theo công việc chạy; **cam kết đặt theo công việc không nói gì cho người dùng**, vì một công việc xanh vẫn có thể phục vụ dữ liệu cũ. Tử số, mẫu số, cửa sổ và phần loại trừ phải định nghĩa tường minh, nếu không hai người tính ra hai con số. Ngân sách sai sót nối cam kết với quyết định phát hành.",
"Định nghĩa ba cam kết theo hành trình người dùng với tử số, mẫu số, cửa sổ và loại trừ tường minh.",
"Tầng *áp dụng*. Objective đòi đặt cam kết theo người dùng chứ theo công việc. Kiểm bằng phép thử hai người tính độc lập; đạt khi ba cam kết cho cùng con số ở hai người và mỗi cam kết dẫn được về một hành trình người dùng.",
"Chọn ba hành trình người dùng khác mức trọng yếu. Với mỗi cái, định nghĩa chỉ số phục vụ và cam kết đủ bốn phần. Nhờ một học viên khác tính độc lập ba cam kết trên cùng dữ liệu và so con số. Tạo một tình huống công việc xanh mà cam kết vẫn vỡ, và giải thích vì sao. Đặt ngân sách sai sót và nêu quyết định nó chi phối.",
"Đặt cam kết theo công việc chạy · không nêu phần loại trừ nên hai người tính khác nhau · đặt cam kết bằng năng lực hiện có · bỏ chỉ số về tính đúng vì khó đo.",
"Ba cam kết cho cùng con số khi hai người tính độc lập, mỗi cam kết dẫn về một hành trình người dùng, và tình huống công việc xanh mà cam kết vỡ được tái hiện."),

(287,"Low-noise alerting and the error budget","TH","Lesson 286",
"Cảnh báo ồn tệ hơn không có cảnh báo, vì nó dạy người trực bỏ qua. Nguyên tắc chọn cái gì đáng cảnh báo: cảnh báo trên triệu chứng người dùng chịu chứ trên mọi quy tắc theo dòng; một quy tắc dòng đỏ là một sự kiện cần ghi nhận, còn một cam kết sắp vỡ mới là một cảnh báo. Cảnh báo theo tốc độ tiêu ngân sách sai sót cho hai mức: tiêu nhanh thì gọi ngay, tiêu chậm nhưng bền thì mở việc. Bốn thuộc tính bắt buộc của một cảnh báo: có chủ sở hữu, có sổ tay xử lý, có mô tả ảnh hưởng tới bên tiêu thụ, và có hành động cụ thể; **thiếu một trong bốn thì nó là thông báo chứ cảnh báo**. Chống ồn bằng gộp theo nguyên nhân gốc, im lặng có thời hạn khi đang xử lý, và phụ thuộc giữa các cảnh báo. Chọn ngưỡng sao cho bảng theo dõi luôn xanh là một chế độ hỏng tự động chưa đạt.",
"Dựng bộ cảnh báo có bốn thuộc tính bắt buộc và giảm được số cảnh báo không hành động được sau một vòng rà.",
"Tầng *đánh giá*. Objective đo chất lượng cảnh báo bằng tỉ lệ hành động được, chứ bằng độ phủ. Kiểm bằng phát lại sự cố cũ; đạt khi ba sự cố đều sinh cảnh báo đúng chủ sở hữu và tỉ lệ cảnh báo không hành động được giảm có số đo.",
"Rà toàn bộ cảnh báo đang có, đếm tỉ lệ không hành động được trong 30 ngày. Chuyển các quy tắc dòng từ cảnh báo sang ghi nhận. Dựng cảnh báo theo tốc độ tiêu ngân sách ở hai mức. Bổ sung đủ bốn thuộc tính. Phát lại ba sự cố lịch sử và kiểm cảnh báo có nổ đúng lúc, đúng người. Đo lại tỉ lệ không hành động được.",
"Cảnh báo trên từng quy tắc dòng · cảnh báo không có sổ tay xử lý · đặt ngưỡng để bảng theo dõi xanh · im lặng vĩnh viễn thay vì im lặng có hạn.",
"Ba sự cố phát lại đều sinh cảnh báo đúng người, mọi cảnh báo có đủ bốn thuộc tính, và tỉ lệ không hành động được giảm có số đo."),

(288,"The incident lifecycle - eight steps","LT","Lesson 287",
"Sự cố dữ liệu khác sự cố hệ thống ở một điểm quyết định: dữ liệu sai đã công bố thì người ta đã ra quyết định dựa trên nó, nên dừng lan rộng quan trọng hơn khôi phục nhanh. Tám bước theo thứ tự: phát hiện và phân loại mức nghiêm trọng cùng phạm vi ảnh hưởng; **dừng công bố tiếp hoặc đánh dấu suy giảm, và giữ nguyên bằng chứng**; xác định phân vùng hỏng, bên tiêu thụ bị ảnh hưởng và trạng thái tốt gần nhất; giảm thiểu bằng quay lui, cách ly, chặn truy cập hoặc thông báo; truy nguyên nhân gốc xuyên nguồn, mã, cấu hình, nền tảng và vận hành; sửa, nạp bù hoặc trình bày lại trong luồng cách ly; đối soát và lấy chấp thuận trước khi công bố lại; rồi phân tích sau sự cố. Bước hai chứa một quy tắc hay bị vi phạm khi dọn dẹp vội: **ghi đè bằng chứng sự cố là mất khả năng truy nguyên nhân**.",
"Chạy đúng thứ tự tám bước trên một sự cố mô phỏng và nêu quyết định của từng bước.",
"Tầng *hiểu*. Bài lý thuyết đặt quy trình cho hai bài thực hành sau. Kiểm bằng bài chạy quy trình; đạt khi tám bước có quyết định ghi lại, bằng chứng được giữ nguyên, và bên tiêu thụ bị ảnh hưởng được liệt kê trước khi sửa.",
"Nhận một sự cố mô phỏng thuộc một trong chín lớp sự cố: phân vùng thiếu hoặc muộn, trùng lặp, phá vỡ lược đồ, hồi quy logic thầm lặng, hỏng lịch sử chiều, nạp bù dở dang, bảng điều khiển cũ, lộ dữ liệu xuyên khách hàng, và công cụ chất lượng hỏng gây tin nhầm. Chạy tám bước và ghi quyết định từng bước. Liệt kê bên tiêu thụ ảnh hưởng bằng dòng dõi trước khi sửa.",
"Sửa dữ liệu trước khi giữ bằng chứng · công bố lại trước khi đối soát · bỏ bước liệt kê bên tiêu thụ · phân tích sau sự cố quy về lỗi cá nhân.",
"Tám bước có quyết định ghi lại theo đúng thứ tự, bằng chứng được giữ nguyên, và danh sách bên tiêu thụ lập trước khi sửa."),

(289,"Repair, backfill and restatement","TH","Lesson 288",
"Sửa dữ liệu hỏng là thao tác dễ tạo ra hỏng lần hai, nên nó có quy trình riêng. Bốn bước bắt buộc: chạy thử không ghi để biết phạm vi sẽ chạm; chạy vào đích cách ly theo lesson 252; đối soát đích cách ly với nguồn; rồi mới thăng cấp bằng hoán đổi nguyên tử và giữ đường quay lại. **Sửa mà không cách ly tạo hỏng lần hai**, và đó là ô nguy hiểm nhất trong ma trận chế độ hỏng của module. Trình bày lại là quyết định nghiệp vụ theo lesson 158: số đã công bố có đổi hay giữ nguyên, ai duyệt, và bên tiêu thụ được báo ra sao. Sửa dữ liệu lịch sử phải giữ dấu vết đã sửa gì, vào lúc nào, bởi ai. Ba tình huống không nên sửa mà nên đánh dấu suy giảm rồi sửa gốc trước, vì sửa hạ nguồn khi gốc còn sai chỉ tạo hai nguồn sự thật.",
"Sửa hai sự cố qua đủ bốn bước, đối soát đạt trước khi công bố lại, và không tạo hỏng lần hai.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là đối soát đạt trước công bố và quay lại được sau đó. Kiểm bằng hai sự cố sửa đầy đủ; đạt khi cả hai đối soát đạt ở đích cách ly trước khi thăng cấp và quay lại thực hiện được.",
"Nhận hai sự cố: một phân vùng thiếu và một hồi quy logic thầm lặng. Với mỗi cái, chạy thử không ghi, sửa trong đích cách ly, đối soát, thăng cấp, rồi thực hiện quay lại. Ghi chính sách trình bày lại kèm người duyệt và cách báo bên tiêu thụ. Ghi lại dấu vết đã sửa gì và bởi ai.",
"Sửa thẳng vào bảng phục vụ · công bố lại trước khi đối soát · nạp lại toàn bộ để chữa mà không truy nguyên nhân · sửa hạ nguồn khi nguồn vẫn còn sai.",
"Hai sự cố đều đối soát đạt ở đích cách ly trước khi thăng cấp, quay lại thực hiện được, và dấu vết sửa được ghi đầy đủ."),

(290,"False positives, coverage and quality debt","TH","Lesson 289",
"Bộ quy tắc là tài sản phải bảo trì, và không bảo trì thì nó tự mục theo ba cách. Báo giả tích luỹ làm người trực mất tin, và cách đo là tỉ lệ cảnh báo bị đóng với lý do không phải vấn đề. Độ phủ suy giảm khi hệ đổi mà quy tắc không đổi, và cách đo là ánh xạ rủi ro với quy tắc theo lesson 283 chạy lại định kỳ. Nợ chất lượng tích luỹ dưới dạng miễn trừ hết hạn, quy tắc bị tắt và chênh lệch được chấp nhận; nó phải có sổ, có chủ và có hạn giống nợ kỹ thuật. Một chế độ hỏng tinh vi phải nhận ra: **phép kiểm có bộ lọc thu hẹp sẽ che đúng phần dữ liệu hỏng**, vì người viết đã loại ca gây đỏ ra khỏi phạm vi; cách phát hiện là đối chiếu số dòng phép kiểm thực sự xét với số dòng của bảng. Rà soát định kỳ bộ quy tắc và điều kiện gỡ một quy tắc.",
"Đo ba chỉ số sức khoẻ của bộ quy tắc và tìm được phép kiểm có phạm vi che dữ liệu hỏng.",
"Tầng *đánh giá*. Objective đòi đánh giá chính hệ kiểm chứ dữ liệu. Kiểm bằng ba chỉ số cộng bài rà phạm vi; đạt khi ba chỉ số có số đo và mọi phép kiểm có bộ lọc thu hẹp đều được đối chiếu số dòng xét.",
"Đo tỉ lệ báo giả trong 30 ngày, chạy lại ánh xạ rủi ro với quy tắc, và lập sổ nợ chất lượng gồm miễn trừ hết hạn cùng quy tắc đang tắt. Với mọi phép kiểm có bộ lọc, đối chiếu số dòng nó xét với số dòng bảng và tìm ca che dữ liệu hỏng. Gỡ những quy tắc không còn phủ rủi ro nào.",
"Coi phép kiểm xanh là dữ liệu sạch mà không xem phạm vi · để miễn trừ hết hạn nằm mãi · thêm quy tắc mà không bao giờ gỡ · đo độ phủ bằng số lượng quy tắc.",
"Ba chỉ số sức khoẻ có số đo, mọi phép kiểm có bộ lọc được đối chiếu số dòng xét, và sổ nợ chất lượng có chủ cùng hạn."),

(291,"The quality failure matrix","TH","Lesson 290",
"Bài gom bảy chế độ hỏng mà hợp đồng nguồn liệt kê thành một bảng dùng được khi trực, mỗi dòng gồm hiện tượng, lý do phép kiểm thông thường bỏ sót, và chốt kiểm soát tốt hơn. Toàn bộ dữ liệu lệch múi giờ thì kiểu và khoảng đều hợp lệ, cần bộ đối chứng và kiểm ranh giới thời gian. Phép kết nhân dòng làm chỉ số sai thì kiểm theo dòng xanh, cần đối soát theo hạt và tổng kiểm soát. Phân vùng thiếu thì phép kiểm theo dòng không chạy lần nào, cần kiểm đầy đủ theo phân vùng kỳ vọng. Quy tắc tốt chặn nhầm dữ liệu tốt vì ngưỡng hoặc bối cảnh sai, cần kiểm ngược và cách ly thay vì chặn. Phép kiểm loại trừ chính phần hỏng, cần đối chiếu số dòng xét. Đường dẫn xanh trên nguồn cũ vì mọi việc chạy xong trên đầu vào cũ, cần chỉ số độ tươi của nguồn. Sửa tạo hỏng lần hai, cần chạy thử, cách ly và đối soát trước khi thăng cấp.",
"Lập ma trận bảy chế độ hỏng có chốt kiểm soát tự động cho từng dòng và chứng minh bằng phép thử tiêm.",
"Tầng *đánh giá*. Objective tổng hợp toàn module thành một hệ phòng vệ có bằng chứng. Kiểm bằng bảy lỗi tiêm; đạt khi ít nhất sáu bị chốt kiểm soát tương ứng phát hiện tự động.",
"Lập ma trận bảy dòng đủ ba cột. Với mỗi dòng, cài chốt kiểm soát tự động. Giảng viên tiêm bảy lỗi tương ứng vào hệ và đếm bao nhiêu cái bị phát hiện, mất bao lâu. Với lỗi không bị bắt, bổ sung chốt và tiêm lại. Đưa cả bảy vào bộ kiểm hồi quy.",
"Viết cột chốt kiểm soát mà không cài tự động · bỏ dòng đường dẫn xanh trên nguồn cũ vì nghĩ hiếm · tin bộ kiểm hiện có đã phủ cả bảy · không đo thời gian phát hiện.",
"≥ 6/7 lỗi tiêm bị phát hiện tự động kèm thời gian phát hiện, và cả bảy chốt kiểm soát nằm trong bộ kiểm hồi quy."),

(292,"Reliability capstone - twenty seeded defects","DA","Lesson 291",
"Bài dự án khép module, lấy đúng yêu cầu capstone của hợp đồng nguồn: bổ sung lớp kiểm soát tin cậy vào nền tảng đã dựng ở M14. Nộp gồm bảy hạng mục: hợp đồng dữ liệu và sổ đăng ký quy tắc đủ bảy phần; bộ kiểm cài trên một nền được chọn; đối soát bảy bậc từ nguồn tới tầng phục vụ; vùng cách ly cùng đường phát lại và một cửa chặn công bố có chứng nhận; cam kết dịch vụ, bảng theo dõi, cảnh báo, trạng thái và sổ tay vận hành; ma trận bảy chế độ hỏng có chốt tự động; và kết quả diễn tập ba tình huống gồm hồi quy logic thầm lặng, phân vùng thiếu, và một lần nạp bù hỏng. Nghiệm thu bằng 20 lỗi gieo sẵn: đo độ phủ phát hiện và tỉ lệ báo giả. Sáu điều kiện tự động chưa đạt lấy từ phần *Critical failures* của nguồn, gồm dùng số lượng phép kiểm làm bằng chứng độ phủ, tuyên bố chính xác không có nguồn đối chiếu, bỏ lỗi chất lượng im lặng, công bố bản sửa trước khi đối soát, cảnh báo không có chủ hoặc sổ tay, và ghi đè bằng chứng sự cố khi dọn dẹp.",
"Nộp lớp kiểm soát tin cậy đủ bảy hạng mục, đạt ngưỡng phát hiện trên 20 lỗi gieo sẵn và không vi phạm sáu điều kiện.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hệ vận hành có bằng chứng định lượng. Kiểm bằng 20 lỗi gieo; đạt khi phát hiện ít nhất 16 với tỉ lệ báo giả dưới ngưỡng, và hai sự cố được sửa cùng đối soát cùng ghi lại.",
"Dựng lớp kiểm soát theo bảy hạng mục. Gieo 20 lỗi thuộc nhiều loại, trong đó ít nhất bốn lỗi thuộc loại phép kiểm theo dòng không bắt được. Đo độ phủ phát hiện, thời gian phát hiện và tỉ lệ báo giả. Người chấm tiêm thêm một lỗi thầm lặng chưa từng gặp; định vị phạm vi ảnh hưởng và chạy phục hồi an toàn.",
"Thêm quy tắc để tăng độ phủ mà không ánh xạ rủi ro · tắt quy tắc ồn ngay trước khi chấm · công bố bản sửa trước khi đối soát · ghi đè bằng chứng sự cố khi dọn dẹp.",
"Phát hiện ≥ 16/20 lỗi gieo với tỉ lệ báo giả dưới ngưỡng, hai sự cố được sửa và đối soát và ghi lại, và không vi phạm sáu điều kiện tự động chưa đạt."),
]

M14D = ("Metadata Engineering, Catalog, Lineage and Governance", 293, 308, """| | |
|---|---|
| **Objective cấp module** | Thiết kế mô hình siêu dữ liệu chuẩn, thu thập được dòng dõi có xuất xứ và độ tin cậy, rồi vận hành quyền sở hữu, từ điển, chứng nhận và khai tử |
| **Tiền đề** | M11 · M11C · M14 · M14C |
| **Exit criterion** | Định danh chuẩn phân giải cùng một tài sản xuyên hệ và xuyên môi trường mà không đụng độ; đường dòng dõi trọng yếu có xuất xứ cùng độ tin cậy; chú thích thủ công không bị thu thập tự động ghi đè |
| **Kỹ năng SFIA** | `DATM` mức 5 · `GOVN` mức 4 |
| **Chế độ hỏng** | Báo cáo dòng dõi do bộ phân tích suy ra như một sự thật, và tuyên bố danh mục cưỡng chế quyền truy cập trong khi nó chỉ lưu siêu dữ liệu |""",
"""**Module bù năng lực Analytics Engineer thứ tư và cuối cùng.** Nó sở hữu mô hình siêu dữ liệu, việc thu thập, dòng dõi, khả năng khám phá, từ điển, quyền sở hữu và các luồng phê duyệt.

Ranh giới lấy từ hợp đồng nguồn: nó **không thay** mô hình hoá dữ liệu, không thay việc chạy kiểm chất lượng, không phải hệ quản lý danh tính, và không phải thẩm quyền quản trị của tổ chức.

Nguyên tắc nhận thức xuyên module: **siêu dữ liệu thu thập tự động không tự nhiên trở thành ý nghĩa đáng tin**. Mỗi trường phải mang xuất xứ, thời điểm quan sát và thẩm quyền; cạnh dòng dõi không chắc chắn phải giữ nguyên trạng thái không chắc chắn thay vì vẽ thành một cạnh trông như sự thật.""")

L14D = [
(293,"Metadata taxonomy - seven types and their authority","LT","Module 14D: M14C",
"Bài mở module bằng việc tách bảy loại siêu dữ liệu, vì mỗi loại có một nguồn có thẩm quyền khác nhau và trộn chúng làm hỏng cả bảy. Kỹ thuật gồm lược đồ, kiểu, phân vùng, câu lệnh và vị trí, lấy từ nền tảng và hiện vật. Vận hành gồm lần chạy, độ tươi, khối lượng, lỗi và kế hoạch truy vấn, lấy từ bộ điều phối cùng engine. Nghiệp vụ gồm định nghĩa, hạt, chỉ số và thuật ngữ, lấy từ chủ sở hữu miền chứ từ bộ thu thập. Quyền sở hữu gồm đội, người quản lý và người trực. Quản trị gồm phân loại, chính sách, thời hạn giữ và chứng nhận. Sử dụng gồm truy vấn, bảng điều khiển, người dùng và mức phổ biến. Dòng dõi gồm các cạnh giữa tài sản, trường và công việc. **Mỗi trường cần xuất xứ, thời điểm quan sát và thẩm quyền**; một mô tả do bộ thu thập lấy từ chú thích cột không có cùng thẩm quyền với định nghĩa do chủ sở hữu miền viết.",
"Phân bảy loại cho một tập trường siêu dữ liệu thật và chỉ đúng nguồn có thẩm quyền của từng loại.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng và đặt nguyên tắc xuất xứ. Kiểm bằng bài phân loại 20 trường; đạt khi phân đúng ít nhất 16 và mỗi trường có nguồn thẩm quyền nêu tên.",
"Cho 20 trường siêu dữ liệu thật lấy từ một danh mục đang chạy. Phân vào bảy loại và ghi nguồn có thẩm quyền của từng cái. Tìm ba trường đang lấy từ nguồn không có thẩm quyền và chỉ ra hậu quả. Bổ sung xuất xứ cùng thời điểm quan sát cho mọi trường chưa có.",
"Coi mọi siêu dữ liệu thu thập được là đáng tin như nhau · lấy định nghĩa nghiệp vụ từ chú thích cột · không ghi thời điểm quan sát nên không biết dữ liệu cũ hay mới · gộp quyền sở hữu với quản trị.",
"Phân đúng ≥ 16/20 trường, mỗi trường có nguồn thẩm quyền nêu tên, và ba trường lấy sai thẩm quyền được chỉ ra."),

(294,"The canonical model - entities, URNs and identity","TH","Lesson 293",
"Không có định danh ổn định thì mọi thứ còn lại sụp, nên bài này đặt nền định danh trước khi thu thập bất cứ gì. Danh sách thực thể cần mô hình hoá: cơ sở dữ liệu, lược đồ, bảng, khung nhìn, cột, tệp, chủ đề, công việc, tác vụ, mô hình, bảng điều khiển, biểu đồ, chỉ số, giao diện lập trình, sản phẩm dữ liệu, miền, đội, người dùng, nhãn, thuật ngữ và chính sách. Tên định danh chuẩn phải mang đủ nền tảng, thể hiện và môi trường, vì cùng một tên bảng tồn tại ở cả môi trường phát triển lẫn sản xuất. **Định danh trùng làm quyền sở hữu và dòng dõi bị chẻ đôi**, và đây là chế độ hỏng nền tảng nhất của module: hai bản ghi cho cùng một bảng nghĩa là nửa dòng dõi nằm ở bản này, nửa ở bản kia, nên phân tích ảnh hưởng thiếu. Cơ chế gộp danh tính trùng và cơ chế bí danh. Đánh đổi giữa kho đồ thị với kho quan hệ hoặc kho tài liệu.",
"Thiết kế tên định danh chuẩn phân giải đúng cùng một tài sản xuyên bốn hệ và ba môi trường.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là không đụng độ và không chẻ danh tính. Kiểm bằng bài phân giải; đạt khi 40 tài sản từ bốn hệ phân giải đúng, không cặp nào đụng độ, và ca trùng danh tính được gộp đúng.",
"Định nghĩa lược đồ thực thể và quy tắc sinh tên định danh chuẩn. Lấy 40 tài sản thật từ bốn hệ và ba môi trường, sinh định danh cho từng cái. Kiểm không có hai tài sản khác nhau nhận cùng định danh và không có một tài sản nhận hai định danh. Tạo một ca trùng danh tính và gộp bằng cơ chế bí danh. So hai cách lưu trữ trên một truy vấn đồ thị điển hình.",
"Dùng tên bảng làm định danh · bỏ môi trường khỏi định danh nên phát triển và sản xuất lẫn nhau · cho phép cặp khoá giá trị tuỳ ý thay vì mở rộng lược đồ có kiểm soát · không có cơ chế gộp danh tính trùng.",
"40 tài sản phân giải đúng không đụng độ và không chẻ danh tính, và ca trùng được gộp bằng bí danh."),

(295,"Relationships, versioning, rename and soft deletion","TH","Lesson 294",
"Cạnh quan hệ và vòng đời của chúng, nơi ba thao tác thường ngày phá hỏng đồ thị nếu xử lý sai. Bảy loại quan hệ: chứa, sinh ra, tiêu thụ, dẫn xuất, sở hữu, tài liệu hoá, và phân loại. Phiên bản cùng thời gian hiệu lực cho phép trả lời câu tài sản này hồi tháng trước có lược đồ gì. Xoá mềm bằng bia mộ giữ lại lịch sử thay vì xoá thật. **Đổi tên bị xử lý như xoá rồi tạo mới là chế độ hỏng làm mất toàn bộ lịch sử và mất cả danh sách bên tiêu thụ**; cách đúng là nhận diện đổi tên rồi ghi quan hệ kế thừa cùng bí danh, và cơ chế nhận diện dựa trên định danh ổn định hoặc trên so khớp lược đồ cùng dòng dõi. Bản số của quan hệ và những chỗ không được phép có chu trình. Mở rộng lược đồ có kiểm soát thay vì cho gắn cặp khoá giá trị tuỳ ý, vì cái sau biến danh mục thành bãi rác trong vài tháng.",
"Xử lý đổi tên, xoá và phiên bản sao cho lịch sử cùng danh sách bên tiêu thụ không mất.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là truy được lịch sử sau ba thao tác phá hoại. Kiểm bằng ba thao tác; đạt khi sau cả ba vẫn truy được lược đồ cũ và danh sách bên tiêu thụ, và không có cạnh treo.",
"Dựng đồ thị có đủ bảy loại quan hệ cho 30 tài sản. Thực hiện ba thao tác: đổi tên một bảng, xoá một bảng còn bên tiêu thụ, và đổi lược đồ hai lần. Sau mỗi thao tác, truy lịch sử và danh sách bên tiêu thụ. Viết phép kiểm chặn cạnh treo và chặn chu trình ở nơi không cho phép.",
"Xử lý đổi tên như xoá rồi tạo mới · xoá cứng bản ghi tài sản · cho phép gắn thuộc tính tuỳ ý · không kiểm cạnh treo sau mỗi lần thu thập.",
"Sau ba thao tác vẫn truy được lược đồ cũ và danh sách bên tiêu thụ, và phép kiểm không tìm thấy cạnh treo nào."),

(296,"Ingestion architecture - the six-step harvest","TH","Lesson 295",
"Đường thu thập siêu dữ liệu là một đường dẫn dữ liệu, nên nó chịu mọi kỷ luật đã học ở M14B. Sáu bước: bộ nối đọc giao diện lập trình, hiện vật, nhật ký hoặc lịch sử truy vấn của nguồn; chuẩn hoá về thực thể và cạnh chuẩn kèm xuất xứ; so sánh rồi chèn hoặc cập nhật có phiên bản, xử lý xoá cùng đổi tên và nguồn đã cũ; phát sự kiện thay đổi và cập nhật đồ thị cùng chỉ mục tìm kiếm; kiểm tính đầy đủ, độ tươi, danh tính và quan hệ; rồi đưa thay đổi, ảnh hưởng và luồng phê duyệt ra cho người dùng. Bước năm là bước hay bị bỏ và bỏ nó thì danh mục trông đầy mà sai. Nguồn đầu vào giàu nhất là hiện vật của công cụ biến đổi theo lesson 266 và sự kiện thời gian chạy của bộ điều phối, vì chúng khai báo tường minh chứ phải suy đoán. Thu thập phải luỹ đẳng theo lesson 250.",
"Cài đường thu thập sáu bước luỹ đẳng từ hai nguồn và chứng minh chạy lại không tạo bản ghi trùng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là trạng thái đồ thị hội tụ sau nhiều lần chạy. Kiểm bằng phép thử chạy lại; đạt khi đồ thị sau năm lần chạy chồng chéo khớp đồ thị sau một lần chạy sạch và bước kiểm phát hiện được lỗi tiêm.",
"Cài bộ nối cho hiện vật của công cụ biến đổi và cho sự kiện của bộ điều phối. Chạy đủ sáu bước. Chạy lại năm lần với thời điểm bắt đầu chồng chéo và có lần bị giết giữa chừng; so đồ thị cuối với đồ thị của một lần chạy sạch. Tiêm một lỗi về danh tính và một cạnh treo, xác nhận bước kiểm bắt được.",
"Bỏ bước kiểm nên danh mục đầy mà sai · thu thập không luỹ đẳng nên chạy lại sinh bản trùng · suy đoán quan hệ khi nguồn đã khai báo tường minh · không phát sự kiện thay đổi nên chỉ mục tìm kiếm lệch với đồ thị.",
"Đồ thị sau năm lần chạy chồng chéo khớp đồ thị của một lần chạy sạch, và bước kiểm bắt được cả hai lỗi tiêm."),

(297,"Connector concerns - incremental crawl, partial failure, preserved annotations","TH","Lesson 296",
"Bộ nối gặp đúng những vấn đề của một trình trích xuất ở M14B, cộng thêm một vấn đề riêng. Quét toàn bộ so với thu thập tăng dần theo sự kiện, và đánh đổi giữa độ tươi với tải đặt lên nguồn. Hạn mức, phân trang, điểm kiểm tra và quyền hạn, theo lesson 237 và 238. Luỹ đẳng, trùng lặp, quét dở dang và nguồn đã xoá tài sản. Bí mật và nguyên tắc quyền tối thiểu chỉ đọc: **dùng quyền quản trị sản xuất để thu thập là một chế độ hỏng tự động chưa đạt**, vì một bộ nối chỉ cần đọc siêu dữ liệu. Tương thích phiên bản khi nâng cấp bộ nối. Vấn đề riêng của module và là ô nguy hiểm nhất: **chú thích thủ công do người viết bị lần thu thập sau ghi đè**, làm mất toàn bộ ngữ cảnh nghiệp vụ; lời giải là một chính sách ưu tiên nguồn tường minh, trong đó trường do người có thẩm quyền viết thắng trường do bộ thu thập lấy. Nạp lại và dựng lại chỉ mục mà không mất chú thích.",
"Vận hành bộ nối qua bốn tình huống hỏng và chứng minh chú thích thủ công không bị mất.",
"Tầng *áp dụng*. Objective có một tiêu chí nghiệm thu đặc trưng là bảo toàn chú thích. Kiểm bằng bốn tình huống; đạt khi cả bốn phục hồi đúng và không chú thích thủ công nào bị ghi đè sau khi dựng lại chỉ mục.",
"Thêm 20 chú thích thủ công vào các tài sản. Chạy bốn tình huống: quét dở dang, bộ nối trễ, nguồn xoá tài sản, và nâng cấp bộ nối lên phiên bản mới. Sau mỗi tình huống, đếm chú thích còn lại. Viết chính sách ưu tiên nguồn và chứng minh nó chặn ghi đè. Rà quyền của bộ nối và hạ xuống mức chỉ đọc siêu dữ liệu.",
"Cho bộ nối quyền quản trị sản xuất · để lần thu thập ghi đè mọi trường · dựng lại danh mục từ đầu mà không di trú danh tính và chú thích · quét toàn bộ mỗi giờ làm nguồn quá tải.",
"20 chú thích thủ công còn nguyên sau cả bốn tình huống, chính sách ưu tiên nguồn chặn được ghi đè, và bộ nối chạy bằng quyền chỉ đọc."),

(298,"Lineage levels and what each answers","LT","Lesson 297",
"Năm mức dòng dõi trả lời năm câu hỏi khác nhau, và đòi mức sai thì vừa tốn vừa không trả lời được câu mình cần. Dòng dõi mức tập dữ liệu nối nguồn với đích, đủ để trả lời câu bảng này lấy dữ liệu từ đâu. Dòng dõi mức trường nối biểu thức dẫn xuất từng cột, cần cho phân tích ảnh hưởng chính xác và đắt hơn nhiều. Dòng dõi mức công việc nối thành phần thực thi cùng phiên bản của nó. Dòng dõi mức bảng điều khiển và chỉ số nối tới nơi tiêu thụ, và đây là mức duy nhất trả lời được câu đổi cột này thì ai nhìn thấy số khác. Khác biệt cuối cùng và quan trọng: **dòng dõi tĩnh mô tả đồ thị có thể xảy ra, dòng dõi thời gian chạy mô tả đường đã thật sự chạy**; một cạnh có trong mã nhưng chưa bao giờ chạy và một cạnh đã chạy hôm qua là hai sự thật khác nhau, và câu hỏi vận hành thường cần cái thứ hai.",
"Chọn mức dòng dõi cho năm câu hỏi thực tế và phân biệt dòng dõi tĩnh với dòng dõi thời gian chạy.",
"Tầng *hiểu*. Bài lý thuyết đặt khung cho bốn bài thực hành sau. Kiểm bằng bài ánh xạ năm câu hỏi; đạt khi chọn đúng ít nhất bốn mức và nêu đúng một câu hỏi chỉ trả lời được bằng dòng dõi thời gian chạy.",
"Cho năm câu hỏi vận hành thật. Với mỗi câu, chỉ ra mức dòng dõi tối thiểu trả lời được và chi phí kéo theo. Trên hệ đang có, tìm một cạnh có trong mã nhưng chưa từng chạy và một cạnh đã chạy; giải thích hai loại bằng chứng khác nhau ra sao. Ước lượng chi phí nâng từ mức tập dữ liệu lên mức trường.",
"Đòi dòng dõi mức trường cho mọi thứ · dùng dòng dõi tĩnh để trả lời câu hỏi về lần chạy hôm qua · bỏ mức tiêu thụ nên không biết ai bị ảnh hưởng · coi năm mức là một khái niệm.",
"Chọn đúng mức cho ≥ 4/5 câu hỏi kèm chi phí, và hai loại cạnh tĩnh với thời gian chạy được phân biệt bằng ví dụ thật."),

(299,"Five extraction methods and their weaknesses","TH","Lesson 298",
"Năm cách lấy dòng dõi, mỗi cách mạnh ở một chỗ và mù ở một chỗ, nên hệ thật dùng nhiều cách rồi hợp nhất. Khai báo tường minh từ hiện vật của khung biến đổi cho đồ thị chính xác nhưng chỉ trong phạm vi khung đó. Phân tích câu lệnh cho chi tiết tới mức cột ở quy mô lớn nhưng vấp phương ngữ, câu lệnh sinh động và hàm tự viết. Sự kiện thời gian chạy theo một chuẩn mở cho bối cảnh thật của lần chạy nhưng phụ thuộc mức tích hợp và thời hạn giữ. Lịch sử truy vấn cho thấy tiêu thụ thật nhưng chịu giới hạn về mẫu và về quyền, và bỏ sót truy vấn gián tiếp. Khai báo thủ công cho cạnh nghiệp vụ mà không cách nào tự lấy được, đổi lại nó cũ đi và tốn công quản trị. **Vùng mù của bốn cách đầu cộng lại vẫn còn khoảng trống**, nên phần còn thiếu phải hiện ra dưới dạng không rõ chứ bị lấp bằng suy đoán.",
"Lấy dòng dõi bằng ít nhất ba cách, hợp nhất, và định lượng độ phủ cùng vùng mù của từng cách.",
"Tầng *phân tích*. Objective đòi đo độ phủ chứ chỉ dựng được đồ thị. Kiểm bằng bảng độ phủ ba cách; đạt khi mỗi cách có tỉ lệ phủ đo được trên cùng tập tài sản và phần không cách nào phủ được đánh dấu rõ.",
"Trên cùng một nền tảng, lấy dòng dõi bằng khai báo tường minh, phân tích câu lệnh, và sự kiện thời gian chạy. Hợp nhất ba đồ thị. Với mỗi cách, tính tỉ lệ tài sản được phủ và liệt kê loại tài sản nó không thấy. Chỉ ra phần không cách nào phủ và đánh dấu trạng thái không rõ thay vì bỏ trống.",
"Dùng một cách rồi coi đồ thị là đầy đủ · lấp khoảng trống bằng suy đoán · bỏ lịch sử truy vấn nên không biết ai đang tiêu thụ · không đo độ phủ.",
"Ba cách đều có tỉ lệ phủ đo được trên cùng tập tài sản, và phần không cách nào phủ được đánh dấu trạng thái không rõ."),

(300,"Edge provenance - extracted, inferred, manual, unknown","TH","Lesson 299",
"Bài đặt ra quy tắc nhận thức trung tâm của module: một cạnh dòng dõi phải mang theo bằng chứng của chính nó. Bốn trạng thái xuất xứ: trích xuất được, tức có khai báo tường minh hoặc bằng chứng thời gian chạy; suy ra, tức do bộ phân tích hoặc luật sinh, kèm tên luật, phiên bản và độ tin cậy; thủ công, tức một khẳng định của chủ sở hữu đã được duyệt; và không rõ hoặc nhập nhằng, tức giữ nguyên sự không chắc chắn. **Vẽ một cạnh suy ra như một cạnh sự thật làm phân tích ảnh hưởng sai**, và sai theo hướng nguy hiểm: người dùng tin rằng đã liệt kê hết bên bị ảnh hưởng trong khi thực tế còn thiếu. Hiển thị phải phân biệt được bốn trạng thái, và truy vấn ảnh hưởng phải trả về cả phần không chắc chắn kèm cảnh báo. Ngưỡng độ tin cậy để một cạnh được dùng trong quyết định tự động.",
"Gắn xuất xứ cho mọi cạnh và chứng minh truy vấn ảnh hưởng phân biệt được cạnh chắc chắn với cạnh suy ra.",
"Tầng *áp dụng*. Objective là một ràng buộc nhận thức kiểm được bằng truy vấn. Kiểm bằng phép kiểm xuất xứ cộng truy vấn ảnh hưởng; đạt khi không cạnh nào thiếu xuất xứ và truy vấn ảnh hưởng trả về phần không chắc chắn kèm cảnh báo.",
"Gắn một trong bốn trạng thái xuất xứ cho mọi cạnh trong đồ thị đã hợp nhất, cạnh suy ra kèm tên luật và độ tin cậy. Viết phép kiểm chặn cạnh không có xuất xứ. Chạy một truy vấn ảnh hưởng và chứng minh kết quả tách phần chắc chắn khỏi phần suy ra và phần không rõ. Đặt ngưỡng độ tin cậy cho quyết định tự động và nêu lý do.",
"Vẽ cạnh suy ra như cạnh sự thật · bỏ cạnh không chắc chắn cho đồ thị sạch · không ghi phiên bản luật suy diễn · dùng cạnh độ tin cậy thấp cho quyết định tự động.",
"Không cạnh nào thiếu xuất xứ, và truy vấn ảnh hưởng tách rõ phần chắc chắn, phần suy ra và phần không rõ."),

(301,"Column lineage - why a parser cannot always prove it","TH","Lesson 300",
"Dòng dõi mức cột là thứ đáng giá nhất và cũng là thứ không bao giờ đạt được hoàn toàn bằng máy, nên bài này liệt kê chính xác chỗ bộ phân tích chịu thua. Chọn toàn bộ cột làm tập cột đầu ra phụ thuộc lược đồ tại thời điểm chạy. Bí danh, trường lồng nhau, biểu thức bảng chung và truy vấn con làm chuỗi dẫn xuất dài và dễ đứt. Hàm tự viết cùng thủ tục lưu trữ là hộp đen với bộ phân tích. Câu lệnh sinh động và mã vĩ mô chỉ biết được nội dung sau khi kết xuất. Bảng tạm và mã ngoài viết bằng ngôn ngữ khác nằm ngoài tầm. Phép hợp, hàm cửa sổ và phép gộp tạo ra khác biệt giữa dẫn xuất theo biểu thức với ảnh hưởng theo ngữ nghĩa: một cột nằm trong điều kiện lọc ảnh hưởng tới kết quả mà không xuất hiện trong biểu thức đầu ra. **Khi bộ phân tích không chứng minh được, câu trả lời đúng là đánh dấu không rõ** chứ đoán một cạnh trông hợp lý.",
"Chạy phân tích cột trên một tập câu lệnh đại diện và đánh dấu đúng mọi cạnh bộ phân tích không chứng minh được.",
"Tầng *phân tích*. Objective đòi nhận ra giới hạn của công cụ và biểu diễn giới hạn đó. Kiểm bằng tập câu lệnh có ca khó; đạt khi mọi ca bộ phân tích chịu thua đều được đánh dấu không rõ và không ca nào bị vẽ thành cạnh sự thật.",
"Chuẩn bị 15 câu lệnh đại diện gồm chọn toàn bộ cột, biểu thức bảng chung lồng nhau, hàm tự viết, câu lệnh sinh động, phép hợp và hàm cửa sổ. Chạy bộ phân tích và đối chiếu kết quả với dòng dõi đúng do người xác định. Đếm số cạnh đúng, số cạnh sai và số cạnh bị bỏ sót. Đánh dấu không rõ cho mọi ca không chứng minh được. Tìm một cột ảnh hưởng qua điều kiện lọc mà không nằm trong biểu thức đầu ra.",
"Tin kết quả bộ phân tích là đầy đủ · bỏ ca chọn toàn bộ cột vì khó · vẽ cạnh cho hàm tự viết theo phỏng đoán · bỏ qua ảnh hưởng qua điều kiện lọc.",
"Mọi ca bộ phân tích chịu thua được đánh dấu không rõ, không cạnh suy đoán nào được vẽ thành sự thật, và ca ảnh hưởng qua điều kiện lọc được tìm ra."),

(302,"Impact analysis from a source column to a dashboard","TH","Lesson 301",
"Bài chứng minh giá trị thật của đồ thị dòng dõi bằng câu hỏi mà nó sinh ra để trả lời. Truy vấn ảnh hưởng đi xuôi từ một cột nguồn qua các mô hình, qua chỉ số, tới bảng điều khiển và tới bên tiêu thụ; truy vấn nguyên nhân đi ngược từ một con số sai về tới nguồn. Kết quả phải kèm ba thứ để dùng được: danh sách bên tiêu thụ cùng chủ sở hữu của họ, mức tin cậy của từng đường, và phần không chắc chắn được nêu riêng. Ba tình huống dùng thật: trước khi đổi lược đồ thì biết phải báo ai theo lesson 264; khi có sự cố thì biết phạm vi ảnh hưởng theo lesson 288; và khi cắt chi phí thì biết tài sản nào không phục vụ ai. **Truy vấn ảnh hưởng thiếu vẫn trông như một câu trả lời đầy đủ**, nên nó phải luôn nói rõ độ phủ của đồ thị bên dưới, nếu không người dùng tưởng đã liệt kê hết.",
"Chạy truy vấn ảnh hưởng hai chiều và trả về danh sách bên tiêu thụ kèm chủ sở hữu, mức tin cậy và phần không chắc chắn.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng đối chiếu với danh sách đúng. Kiểm bằng ba truy vấn; đạt khi kết quả khớp danh sách đúng ở ít nhất hai và mọi kết quả đều kèm độ phủ của đồ thị.",
"Chạy ba truy vấn ảnh hưởng từ ba cột nguồn khác nhau tới bảng điều khiển. Đối chiếu kết quả với danh sách đúng xác định bằng tay. Chạy một truy vấn nguyên nhân ngược từ một con số sai. Với mỗi kết quả, kèm chủ sở hữu, mức tin cậy và độ phủ của đồ thị. Dùng kết quả để lập danh sách thông báo cho một lần đổi lược đồ.",
"Trình bày kết quả truy vấn ảnh hưởng như danh sách đầy đủ · bỏ mức tin cậy · không kèm chủ sở hữu nên không báo được ai · bỏ phần không chắc chắn cho kết quả gọn.",
"Kết quả khớp danh sách đúng ở ≥ 2/3 truy vấn, mọi kết quả kèm chủ sở hữu cùng mức tin cậy cùng độ phủ đồ thị."),

(303,"Catalog and discovery - search, relevance and the asset page","TH","Lesson 302",
"Danh mục chỉ có giá trị khi người ta tìm thấy và tin được thứ tìm thấy, nên bài này nối thẳng với phép thử khả năng tìm thấy ở lesson 192. Tìm kiếm theo tên, mô tả, lược đồ, thuật ngữ, miền, chủ sở hữu, nhãn và mức sử dụng. Xếp hạng kết hợp khớp chính xác, khớp gần đúng, mức phổ biến, độ tươi, trạng thái chứng nhận, và **lọc theo quyền trước khi trả kết quả**, vì trả về siêu dữ liệu của tài sản mà người dùng không được xem cũng là rò rỉ. Trang tài sản phải có đủ mục đích, hạt, lược đồ, chủ sở hữu, cam kết dịch vụ, tình trạng chất lượng, dòng dõi, bên tiêu thụ, truy vấn mẫu và cách xin quyền. Duyệt theo miền và theo sản phẩm dữ liệu. Một cạm bẫy của xếp hạng theo mức phổ biến: **một tài sản bị dùng rộng rãi nhưng sai sẽ được đẩy lên đầu và trông như đã được chứng nhận**, nên mức phổ biến không được thay tín hiệu chứng nhận.",
"Dựng tìm kiếm có lọc theo quyền và trang tài sản đủ mục, đạt ngưỡng trong phép thử khả năng tìm thấy.",
"Tầng *đánh giá*. Objective đo bằng hành vi người dùng và bằng phép thử rò rỉ. Kiểm bằng phép thử với năm người cộng phép thử quyền; đạt khi tỉ lệ tìm thấy vượt ngưỡng và không kết quả nào lộ siêu dữ liệu ngoài quyền.",
"Dựng trang tài sản đủ mười mục cho 20 tài sản. Cài xếp hạng có lọc theo quyền. Chạy phép thử khả năng tìm thấy với năm người, mỗi người một nhu cầu, tính giờ ba phút. Chạy phép thử phủ định với một tài khoản hạn chế và kiểm không kết quả nào lộ tài sản ngoài quyền. Tạo một tài sản phổ biến nhưng chưa chứng nhận và chứng minh giao diện không làm nó trông như đã chứng nhận.",
"Trả kết quả tìm kiếm trước khi lọc quyền · xếp hạng chỉ theo mức phổ biến · trang tài sản thiếu hạt và chủ sở hữu · đo danh mục bằng số tài sản đã đăng ký.",
"Tỉ lệ tìm thấy trong ba phút vượt ngưỡng, không kết quả nào lộ siêu dữ liệu ngoài quyền, và tài sản phổ biến chưa chứng nhận không bị hiển thị như đã chứng nhận."),

(304,"Ownership, glossary and conflicting domain meanings","TH","Lesson 303",
"Quyền sở hữu và từ vựng là hai thứ quyết định danh mục có được dùng hay không, và cả hai đều là vấn đề tổ chức được biểu diễn bằng dữ liệu. Năm vai: chủ sở hữu kỹ thuật, chủ sở hữu sản phẩm hoặc miền, người quản lý dữ liệu, người trực, và người phê duyệt. Ba phép đo về quyền sở hữu: độ phủ, phát hiện đội hoặc người đã rời, và đường leo thang. Một nguyên tắc dễ bị vi phạm: **chủ sở hữu phải có thẩm quyền và có năng lực**, nên gán tự động người tạo bảng chỉ là bước khởi tạo chứ không phải trạng thái quản trị cuối cùng. Thuật ngữ trong từ điển gồm định nghĩa, phạm vi, ví dụ cùng phản ví dụ, từ đồng nghĩa, chủ sở hữu và quan hệ; gắn thuật ngữ vào cột, tài sản và chỉ số, và phân biệt thuật ngữ nghiệp vụ với tên cột vật lý. Xung đột nghĩa giữa hai miền phải được giải bằng cách ghi nhận cả hai theo ngữ cảnh, theo đúng lesson 161, chứ ép một định nghĩa toàn công ty.",
"Đạt độ phủ quyền sở hữu có thẩm quyền và ghi nhận được một xung đột nghĩa giữa hai miền mà không ép một định nghĩa.",
"Tầng *áp dụng*. Objective đo chất lượng quyền sở hữu chứ chỉ sự tồn tại của một trường. Kiểm bằng phép thử xác nhận; đạt khi chủ sở hữu được chính họ xác nhận ở ít nhất 80 phần trăm tài sản trọng yếu và xung đột nghĩa được ghi theo ngữ cảnh.",
"Gán năm vai cho toàn bộ tài sản trọng yếu. Gửi xác nhận tới từng chủ sở hữu và đếm tỉ lệ xác nhận. Chạy phép kiểm phát hiện đội hoặc người đã rời. Xây từ điển cho 15 thuật ngữ và gắn vào cột cùng chỉ số. Tìm một từ mang hai nghĩa ở hai miền và ghi nhận cả hai theo ngữ cảnh kèm cách phân biệt cho người tìm kiếm.",
"Gán tự động người tạo bảng rồi coi là xong · gán chủ sở hữu là một phòng ban · ép một định nghĩa toàn công ty cho từ có hai nghĩa · lập từ điển mà không gắn vào cột nào.",
"Chủ sở hữu được chính họ xác nhận ở ≥ 80% tài sản trọng yếu, phép kiểm phát hiện người đã rời chạy tự động, và xung đột nghĩa được ghi theo cả hai ngữ cảnh."),

(305,"Certification, deprecation and the expiry rule","TH","Lesson 304",
"Chứng nhận là tín hiệu tin cậy mạnh nhất trong danh mục, nên nó là thứ dễ bị lạm dụng nhất. Năm trạng thái: bản nháp, đã kiểm, đã chứng nhận, đã khai tử, đã gỡ. Phạm vi chứng nhận phải nói rõ nó bảo đảm gì: tính đúng về ngữ nghĩa, tình trạng chất lượng và cam kết dịch vụ, quyền sở hữu, mức hỗ trợ, và ngày rà soát lại. **Chứng nhận không bao giờ hết hạn tạo ra niềm tin sai**, vì một tài sản được chứng nhận hai năm trước có thể đã đổi hoàn toàn; nên mỗi chứng nhận có ngày rà soát và có cơ chế tự hạ cấp khi quá hạn hoặc khi cam kết dịch vụ vỡ. Điều kiện chứng nhận lấy từ các module trước và phải kiểm được bằng máy, chứ dựa trên việc tài liệu đã điền đủ: **tự động chứng nhận chỉ vì tài liệu đầy đủ là một chế độ hỏng tự động chưa đạt**. Khai tử cần danh sách bên tiêu thụ, phương án thay thế, thời hạn và theo dõi mức dùng còn lại.",
"Vận hành năm trạng thái với điều kiện chứng nhận kiểm được bằng máy và cơ chế tự hạ cấp khi quá hạn.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là chặn đúng và tự hạ cấp đúng. Kiểm bằng ba tài sản đi qua vòng đời; đạt khi tài sản thiếu điều kiện bị chặn chứng nhận, tài sản quá hạn tự hạ cấp, và tài sản khai tử không còn người dùng khi gỡ.",
"Dựng vòng đời năm trạng thái với danh mục điều kiện chứng nhận kiểm tự động, gồm tình trạng chất lượng từ M14C và quyền sở hữu đã xác nhận. Đưa ba tài sản qua vòng đời, trong đó một cái chỉ có tài liệu đầy đủ mà chưa đạt chất lượng và phải bị chặn. Đẩy đồng hồ qua ngày rà soát và chứng minh tự hạ cấp. Khai tử một tài sản với thời hạn và theo dõi mức dùng tới khi về không.",
"Chứng nhận dựa trên tài liệu đầy đủ · chứng nhận không có ngày rà soát · gỡ tài sản khi còn người dùng · không nói rõ chứng nhận bảo đảm điều gì.",
"Tài sản thiếu điều kiện bị chặn chứng nhận, tài sản quá ngày rà soát tự hạ cấp, và tài sản khai tử về không người dùng trước khi gỡ."),

(306,"Classification, retention and the enforcement boundary","LT","Lesson 305",
"Bài đặt ra ranh giới mà module này không được vượt, và vượt nó là chế độ hỏng nguy hiểm nhất về mặt pháp lý. Phân loại gồm mức nhạy cảm, dữ liệu cá nhân và phân loại nghiệp vụ; lan truyền phân loại theo dòng dõi là một tính năng mạnh và cũng dễ sai, nên nó cần cơ chế ghi đè có kiểm soát ở nơi phép lan truyền cho kết quả không đúng. Gắn chính sách vào tài sản. **Danh mục ghi lại bằng chứng và trạng thái; việc cưỡng chế quyền truy cập, che dữ liệu và xoá theo thời hạn do hệ có thẩm quyền thực hiện.** Tuyên bố danh mục cưỡng chế điều nó chỉ đang ghi lại là một tuyên bố sai và là một trong những chế độ hỏng tự động chưa đạt; hậu quả là tổ chức tin rằng một nghĩa vụ đã được thực hiện trong khi chưa. Một rủi ro riêng của danh mục: lưu giá trị mẫu hoặc thống kê phân bố có thể làm lộ dữ liệu nhạy cảm, nên phần đó cũng phải có phân loại và kiểm soát truy cập.",
"Nêu chính xác ranh giới giữa ghi nhận với cưỡng chế và thiết kế lan truyền phân loại có cơ chế ghi đè.",
"Tầng *hiểu*. Bài lý thuyết chốt phần quản trị. Kiểm bằng bài phân định; đạt khi phân đúng ít nhất tám trong mười nghĩa vụ vào ghi nhận hay cưỡng chế và thiết kế lan truyền có ghi đè cùng phép kiểm rò rỉ giá trị mẫu.",
"Cho mười nghĩa vụ quản trị cụ thể. Phân từng cái vào ghi nhận hay cưỡng chế và nêu hệ nào thực hiện. Thiết kế lan truyền phân loại theo dòng dõi cho một miền, kèm cơ chế ghi đè. Tìm ba chỗ phép lan truyền cho kết quả sai. Rà phần giá trị mẫu và thống kê trong danh mục, phân loại chúng và đặt kiểm soát truy cập.",
"Nói danh mục đang cưỡng chế chính sách · lan truyền phân loại mà không có ghi đè · lưu giá trị mẫu không phân loại · coi phân loại là việc một lần chứ trạng thái phải rà lại.",
"Phân đúng ≥ 8/10 nghĩa vụ giữa ghi nhận và cưỡng chế, lan truyền phân loại có ghi đè cùng ba ca sai được tìm ra, và giá trị mẫu có phân loại cùng kiểm soát truy cập."),

(307,"Metadata control-plane capstone","DA","Lesson 306",
"Bài dự án khép module và khép cả Phase 7, lấy đúng yêu cầu capstone của hợp đồng nguồn: bổ sung một mặt phẳng điều khiển siêu dữ liệu cho nền tảng đã dựng. Nộp gồm bảy hạng mục: một danh mục được chọn để cài đặt; thu thập từ khung biến đổi, bộ điều phối, kho dữ liệu, nền tảng dòng sự kiện và công cụ báo cáo; dòng dõi ở mức tập dữ liệu, cột, công việc, bảng điều khiển và chỉ số, mỗi cạnh có xuất xứ; miền cùng sản phẩm dữ liệu, từ điển, chủ sở hữu, phân loại và chứng nhận; nối với tình trạng chất lượng cùng cam kết dịch vụ ở M14C và phân tích ảnh hưởng khi có sự cố; luồng tìm kiếm, xin quyền và khai tử; và bảng theo dõi cùng sổ tay cho chính đường thu thập siêu dữ liệu. Chỉ số phục vụ của siêu dữ liệu phải đo được: độ phủ, độ tươi thu thập, tỉ lệ danh tính mồ côi hoặc trùng, độ phủ dòng dõi trên đường trọng yếu, tỉ lệ tìm kiếm không ra kết quả, và mức dùng tài sản đã chứng nhận.",
"Nộp mặt phẳng điều khiển siêu dữ liệu đủ bảy hạng mục với chỉ số phục vụ đo được và không vi phạm sáu điều kiện tự động chưa đạt.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một hệ vận hành. Kiểm bằng tiêm bốn tình huống cộng rà chỉ số; đạt khi bốn tình huống giữ được sự không chắc chắn hiện rõ và phục hồi an toàn, và sáu chỉ số phục vụ có số đo.",
"Dựng mặt phẳng điều khiển theo bảy hạng mục. Đo sáu chỉ số phục vụ. Người chấm tiêm bốn tình huống: đổi tên một tài sản, một câu lệnh sinh động mà bộ phân tích không đọc được, nguồn thu thập mất kết nối, và hai danh tính trùng. Với mỗi cái, chứng minh phần không chắc chắn vẫn hiện rõ và phục hồi không mất chú thích thủ công.",
"Báo cáo dòng dõi suy ra như sự thật · tuyên bố danh mục cưỡng chế quyền truy cập · thu thập bằng quyền sản xuất quá rộng · dựng lại danh mục mà không sao lưu và không di trú danh tính.",
"Bảy hạng mục đầy đủ, sáu chỉ số phục vụ có số đo, bốn tình huống tiêm đều giữ sự không chắc chắn hiện rõ và phục hồi không mất chú thích."),

(308,"Gate 7 - defend a lineage claim and prove completeness","KT","Lesson 307",
"Cổng của Phase 7, cổng lớn nhất chương trình vì nó phủ bốn module và 78 bài. Bài kiểm nạp dữ liệu ở M14B, biến đổi cùng điều phối ở M14, chất lượng cùng tin cậy ở M14C, và siêu dữ liệu cùng quản trị ở M14D. Không có nội dung mới.",
"Chứng minh tính đầy đủ từ nguồn tới đích bằng đối soát, bảo vệ một khẳng định về dòng dõi trước chất vấn, và phục hồi một sự cố dữ liệu an toàn.",
"Tầng *đánh giá*. Cổng đo năng lực chứng minh và vận hành dưới chất vấn, nên hình thức là thực hành tại chỗ cộng bảo vệ trực tiếp.",
"Buổi 180 phút: 135 phút làm bài độc lập, 45 phút chữa bài. Bài chấm sáu phần: A (20đ) chứng minh tính đầy đủ từ nguồn tới tầng phục vụ bằng thang đối soát, nêu rõ tổng thể, cửa sổ, phép kiểm và dung sai · B (20đ) trình chứng minh bảy phần cho một mô hình tăng dần và chạy hai ô của ma trận chế độ hỏng tại chỗ · C (15đ) một lỗi thầm lặng được tiêm; định vị phạm vi ảnh hưởng bằng dòng dõi và chạy phục hồi an toàn · D (20đ) bảo vệ một khẳng định về dòng dõi: cạnh này đến từ đâu, độ tin cậy bao nhiêu, phần nào chưa biết · E (15đ) giải thích ranh giới giữa danh mục ghi nhận và hệ cưỡng chế cho ba nghĩa vụ · F (10đ) rà một bộ quy tắc chất lượng và tìm phép kiểm có phạm vi che dữ liệu hỏng.",
"Dùng mọi việc xanh làm bằng chứng đầy đủ · trình bày cạnh suy ra như sự thật · công bố bản sửa trước khi đối soát · tuyên bố danh mục cưỡng chế chính sách.",
"Đạt ≥ 70/100, phần A và D đều ≥ 60%. Tuyên bố đầy đủ dựa trên lấy mẫu thì phần A bằng không; trình bày cạnh suy ra như sự thật mà không nêu xuất xứ thì phần D bằng không."),
]
