# -*- coding: utf-8 -*-
"""ADE Phase 9: M19 cloud abstractions + M20 container/IaC/Kubernetes + M21 observability."""

M19 = ("Cloud Abstractions Before Service Names", 361, 372, """| | |
|---|---|
| **Objective cấp module** | Gọi tên trừu tượng cần dùng trước khi chọn dịch vụ, rồi triển khai một lát cắt nền tảng trên một đám mây có danh tính, mạng, đường dữ liệu, miền hỏng và ranh giới chi phí |
| **Tiền đề** | M5 · M6 · M10 · M15 |
| **Exit criterion** | Không có khoá tĩnh trong kho mã; quyền tối thiểu có lý do và có bằng chứng kiểm toán; phục hồi và chuyển dự phòng đã thử; chi phí hằng tháng cùng ba yếu tố nhạy cảm nhất được nêu ra |
| **Kỹ năng SFIA** | `ARCH` mức 4 · `ITMG` mức 4 · `SCTY` mức 4 |
| **Chế độ hỏng** | Dùng khoá tĩnh hoặc tài khoản cao nhất cho nhanh, mở công khai như một lối tắt, và trừu tượng hoá đa đám mây trước khi một đám mây chạy được |""",
"""Module có một quy tắc thứ tự tường minh: **gọi tên trừu tượng trước, chọn dịch vụ sau**. Với mỗi trừu tượng, có một câu hỏi phải trả lời và một bằng chứng phải đưa ra trước khi được phép nêu tên bất kỳ dịch vụ nào.

Chọn một đám mây để thành thạo theo tín hiệu thật từ nơi làm việc hoặc thị trường mục tiêu; hai đám mây còn lại chỉ tới mức ánh xạ trừu tượng. **Đa đám mây chỉ ở mức nhận biết cho tới khi một đám mây đã chạy được ở mức sản xuất.**

Ba thứ được kiểm ở mọi bài và ở cổng: danh tính, ranh giới tin cậy của mạng, và chi phí trên mỗi đơn vị công việc.""")

L19 = [
(361,"Regions, zones, failure domains and shared responsibility","LT","Module 19: M15",
"Bài mở module bằng ba khái niệm quyết định mọi quyết định kiến trúc về sau. Vùng và khu khả dụng là các miền hỏng: hai tài nguyên trong cùng một khu có thể hỏng cùng lúc, hai khu khác nhau thì độc lập hơn nhưng không độc lập hoàn toàn vì chúng vẫn dùng chung mặt phẳng điều khiển của vùng. Mặt phẳng điều khiển và mặt phẳng dữ liệu hỏng độc lập: **mặt phẳng điều khiển hỏng thì không tạo được tài nguyên mới và không chuyển dự phòng được, trong khi tài nguyên đang chạy vẫn phục vụ**, và phân biệt hai trạng thái này khi trực là quan trọng, đúng như ở lesson 330. Trách nhiệm chia sẻ: nhà cung cấp lo phần dưới một đường kẻ, khách hàng lo phần trên, và đường kẻ đó khác nhau giữa dịch vụ tự quản với dịch vụ được quản lý; hiểu sai đường kẻ tạo ra khoảng trống không ai lo, thường là sao lưu, vá lỗi và cấu hình truy cập.",
"Vẽ miền hỏng cho một kiến trúc và chỉ đúng đường kẻ trách nhiệm cho bốn dịch vụ.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng. Kiểm bằng bài phân định; đạt khi vẽ đúng miền hỏng và chỉ đúng phần khách hàng phải lo ở ít nhất ba trong bốn dịch vụ.",
"Cho một kiến trúc bốn thành phần; vẽ sơ đồ miền hỏng và chỉ ra thành phần nào cùng chết khi mất một khu khả dụng. Với bốn dịch vụ thuộc bốn mức quản lý khác nhau, liệt kê phần nhà cung cấp lo và phần mình lo. Tìm ba khoảng trống không ai lo trong một kiến trúc thật.",
"Giả định dịch vụ được quản lý thì không cần sao lưu · coi nhiều khu khả dụng là thay được sao lưu · nhầm sự cố mặt phẳng điều khiển với sự cố mặt phẳng dữ liệu · vẽ kiến trúc mà không đánh dấu miền hỏng.",
"Sơ đồ miền hỏng đúng cho kiến trúc bốn thành phần, và phần trách nhiệm khách hàng đúng ở ≥ 3/4 dịch vụ kèm ba khoảng trống tìm được."),

(362,"Identity before services - principal, role, least privilege","TH","Lesson 361",
"Danh tính là trừu tượng phải chốt trước mọi thứ khác, vì mọi lỗi bảo mật lớn đều bắt đầu ở đây. Bốn câu hỏi trước khi cấp quyền: ai đóng vai gì, từ đâu, trong bao lâu, và để làm gì. Chủ thể có thể là người hoặc là khối lượng công việc; danh tính cho khối lượng công việc là cách bỏ hẳn khoá tĩnh, vì tiến trình lấy thông tin xác thực ngắn hạn từ môi trường chạy thay vì đọc từ tệp. **Khoá tĩnh trong kho mã là chế độ hỏng tự động chưa đạt của module**, và nó được kiểm bằng máy chứ bằng lời hứa. Chính sách gắn vào danh tính khác chính sách gắn vào tài nguyên, và hai loại giao nhau theo cách phải hiểu để gỡ lỗi từ chối. Quyền tối thiểu đạt được bằng cách bắt đầu từ không có gì rồi thêm theo lỗi từ chối thật, chứ bắt đầu từ ký tự đại diện rồi thu hẹp. Bằng chứng bắt buộc: một phép thử cho thấy bị từ chối và một phép thử cho thấy được phép, cùng bản ghi kiểm toán tương ứng.",
"Cấp quyền tối thiểu cho ba khối lượng công việc bằng danh tính cho khối lượng công việc, có bằng chứng kiểm toán hai chiều.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng phép thử hai chiều chứ bằng rà soát chính sách. Kiểm bằng sáu phép thử; đạt khi ba phép thử được phép thành công, ba phép thử bị từ chối đúng, và không khoá tĩnh nào tồn tại trong kho mã.",
"Với ba khối lượng công việc, bắt đầu từ chính sách rỗng và thêm quyền theo từng lỗi từ chối thật; ghi lại lý do cho mỗi quyền. Chuyển toàn bộ sang danh tính cho khối lượng công việc và xoá mọi khoá tĩnh. Chạy sáu phép thử hai chiều và đối chiếu với bản ghi kiểm toán. Chạy một bộ quét chặn khoá tĩnh trong kho mã.",
"Bắt đầu bằng ký tự đại diện rồi định thu hẹp sau · dùng tài khoản cao nhất cho việc thường ngày · để khoá tĩnh trong biến môi trường của kho mã · không chạy phép thử bị từ chối.",
"Ba phép thử được phép thành công và ba phép thử bị từ chối đúng, mỗi quyền có lý do ghi lại, và bộ quét không tìm thấy khoá tĩnh nào."),

(363,"Network - CIDR, route, trust boundary, egress and DNS","TH","Lesson 362",
"Trừu tượng thứ hai: đường đi của gói tin và ranh giới tin cậy, dựng trên nền M6. Mạng riêng chia thành các dải địa chỉ; dải công khai có đường ra thẳng, dải riêng thì không và phải đi qua một cổng dịch địa chỉ hoặc một điểm cuối riêng để tới dịch vụ của nhà cung cấp. Bảng định tuyến quyết định gói đi đâu; quy tắc tường lửa quyết định gói nào được qua. Hai lựa chọn cho lưu lượng ra và đánh đổi phải tính bằng tiền: cổng dịch địa chỉ tính phí theo lượng dữ liệu nên nó là nguồn hoá đơn bất ngờ hay gặp, còn điểm cuối riêng giữ lưu lượng trong mạng nhà cung cấp và thường rẻ hơn cùng an toàn hơn. Phân giải tên và cân bằng tải. **Nhóm bảo mật mở cho toàn bộ internet là một lối tắt bị cấm**, kể cả trong môi trường thử. Bằng chứng bắt buộc của bài là một sơ đồ đường đi gói tin, không phải một sơ đồ hộp.",
"Dựng mạng có dải riêng không đi ra internet trực tiếp và vẽ được sơ đồ đường đi gói tin có bằng chứng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là đường đi thật quan sát được. Kiểm bằng phép thử kết nối; đạt khi tài nguyên ở dải riêng không ra được internet trực tiếp, vẫn gọi được dịch vụ qua điểm cuối riêng, và sơ đồ khớp kết quả truy vết thật.",
"Dựng mạng có dải công khai và dải riêng, cổng dịch địa chỉ và ít nhất một điểm cuối riêng. Từ một máy ở dải riêng, thử ra internet trực tiếp và xác nhận bị chặn; thử gọi dịch vụ nhà cung cấp qua điểm cuối riêng và xác nhận thành công. Truy vết đường đi và vẽ sơ đồ. So chi phí ước tính giữa đi qua cổng dịch địa chỉ và đi qua điểm cuối riêng cho một khối lượng cho trước.",
"Mở quy tắc cho toàn bộ internet để gỡ lỗi nhanh · đặt mọi thứ ở dải công khai · bỏ qua chi phí lưu lượng qua cổng dịch địa chỉ · vẽ sơ đồ hộp thay vì sơ đồ đường đi gói tin.",
"Tài nguyên ở dải riêng bị chặn ra internet nhưng gọi được dịch vụ qua điểm cuối riêng, và sơ đồ khớp kết quả truy vết thật."),

(364,"Compute - state, startup, scale unit and replacement","TH","Lesson 363",
"Trừu tượng thứ ba, và bốn câu hỏi quyết định chọn dạng tính toán nào. Trạng thái nằm ở đâu: nếu nằm trong máy thì thay máy là mất dữ liệu. Thời gian khởi động bao lâu: quyết định phản ứng được với tải đột biến hay không. Đơn vị mở rộng là gì: một máy, một vùng chứa, hay một lời gọi hàm. Thay thế ra sao khi một đơn vị chết. Ba dạng và điều kiện dùng: máy ảo cho khối lượng công việc cần kiểm soát môi trường; vùng chứa được quản lý cho dịch vụ dài hạn không muốn nuôi cụm; hàm không máy chủ cho việc ngắn theo sự kiện, với ba giới hạn phải biết là thời gian chạy tối đa, khởi động nguội, và trạng thái không giữ được giữa hai lần gọi. **Ảnh máy bất biến cộng thay thế thay vì sửa tại chỗ** là nguyên tắc chung, và nó là điều kiện để dựng lại được từ mã ở lesson 371.",
"Chọn dạng tính toán cho ba khối lượng công việc theo bốn câu hỏi và chứng minh mất một đơn vị không mất dữ liệu.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng diễn tập mất máy. Kiểm bằng phép thử giết; đạt khi dịch vụ tự thay thế đơn vị đã mất và không dữ liệu nào nằm lại trên đơn vị đó.",
"Cho ba khối lượng công việc; trả lời bốn câu hỏi cho từng cái rồi chọn dạng tính toán. Triển khai một cái theo nhóm tự mở rộng dùng ảnh bất biến. Giết một đơn vị và đo thời gian tới khi đơn vị thay thế phục vụ được. Chứng minh không có trạng thái nằm lại trên đơn vị bị giết. Đo khởi động nguội của một hàm không máy chủ.",
"Lưu trạng thái trên đĩa cục bộ của máy tự mở rộng · sửa cấu hình trên máy đang chạy thay vì dựng ảnh mới · chọn hàm không máy chủ cho việc chạy dài · bỏ qua khởi động nguội khi hứa độ trễ.",
"Đơn vị bị giết được thay thế tự động với thời gian đo được, và không dữ liệu nào nằm lại trên đơn vị đó."),

(365,"Storage and managed databases chosen by the data contract","TH","Lesson 364",
"Trừu tượng thứ tư và thứ năm, chọn theo hợp đồng dữ liệu chứ theo tên dịch vụ. Ba dạng lưu trữ và ranh giới dùng: kho đối tượng cho dữ liệu bất biến quy mô lớn với ngữ nghĩa đã học ở lesson 224; khối cho đĩa gắn vào một máy; tệp chia sẻ cho nhiều máy cùng đọc ghi. Bốn thuộc tính phải hỏi trước: tính nhất quán, độ bền, độ khả dụng, và vòng đời cùng phiên bản cùng sao chép. **Độ bền và độ khả dụng là hai con số khác nhau**: dữ liệu bền tuyệt đối vẫn có thể không truy cập được trong một sự cố, nên hứa hẹn của nhà cung cấp phải đọc đúng cột. Cơ sở dữ liệu được quản lý chọn theo hợp đồng giao dịch, quy mô, cách chuyển dự phòng và đường kết nối; chuyển dự phòng nhiều khu không thay sao lưu, vì nó nhân bản cả một lệnh xoá nhầm. Đường mạng tới cơ sở dữ liệu và giới hạn số kết nối là hai chỗ hay bị bỏ qua tới khi có tải thật.",
"Chọn lưu trữ và cơ sở dữ liệu cho ba hợp đồng dữ liệu và chứng minh khác biệt giữa độ bền với độ khả dụng.",
"Tầng *đánh giá*. Objective đòi đọc đúng hợp đồng của nhà cung cấp chứ so tên dịch vụ. Kiểm bằng ba lựa chọn cộng một diễn tập; đạt khi mỗi lựa chọn dẫn từ bốn thuộc tính và diễn tập chuyển dự phòng cho số đo gián đoạn thật.",
"Cho ba hợp đồng dữ liệu khác nhau; chọn lưu trữ và cơ sở dữ liệu cho từng cái kèm lý do theo bốn thuộc tính. Bật phiên bản và vòng đời trên kho đối tượng, rồi xoá nhầm một đối tượng và khôi phục. Kích hoạt chuyển dự phòng của cơ sở dữ liệu nhiều khu và đo thời gian gián đoạn cùng số kết nối bị đứt.",
"Coi nhiều khu là đã có sao lưu · đọc nhầm độ bền thành độ khả dụng · bỏ qua giới hạn số kết nối tới cơ sở dữ liệu · chọn dịch vụ theo tên rồi ép hợp đồng dữ liệu vào nó.",
"Ba lựa chọn dẫn từ bốn thuộc tính, khôi phục được đối tượng xoá nhầm, và chuyển dự phòng có số đo thời gian gián đoạn."),

(366,"Messaging services mapped by delivery semantics","TH","Lesson 365",
"Trừu tượng thứ sáu, và bài này ánh xạ thẳng từ M16 sang các dịch vụ được quản lý. Bốn câu hỏi trước khi chọn: thứ tự được giữ ở phạm vi nào, ngữ nghĩa giao nhận là gì, thời hạn giữ bao lâu, và đọc lại được không. Bốn nhóm dịch vụ tương ứng bốn ngữ nghĩa: hàng đợi giao mỗi thông điệp cho một bên tiêu thụ rồi xoá; phát hành đăng ký gửi cho mọi bên đăng ký; bus sự kiện định tuyến theo quy tắc; nhật ký phân tán giữ lại và đọc lại được. **Chọn nhầm nhóm thì không sửa được bằng cấu hình**, vì thời hạn giữ và khả năng đọc lại là thuộc tính của nhóm chứ một tham số. Giới hạn của dịch vụ được quản lý phải đọc trước: kích thước thông điệp tối đa, số bên tiêu thụ, thời hạn giữ tối đa, và hạn mức tốc độ. Bằng chứng bắt buộc: một diễn tập tạo bản trùng hoặc mất thông điệp, giống lesson 328.",
"Ánh xạ bốn ngữ nghĩa sang dịch vụ được quản lý và chứng minh bằng diễn tập trùng lặp hoặc mất.",
"Tầng *áp dụng*. Objective đòi kiểm ngữ nghĩa bằng thực nghiệm chứ đọc tài liệu. Kiểm bằng diễn tập; đạt khi ngữ nghĩa quan sát được khớp ngữ nghĩa đã tuyên bố ở cả hai dịch vụ và giới hạn dịch vụ được ghi lại.",
"Chọn hai dịch vụ thuộc hai nhóm khác nhau. Với mỗi cái, trả lời bốn câu hỏi bằng tài liệu rồi kiểm bằng thực nghiệm: giết bên tiêu thụ giữa chừng và đếm bản trùng hoặc mất; thử đọc lại từ một thời điểm cũ. Ghi lại bốn giới hạn của dịch vụ. Chỉ ra một yêu cầu mà nhóm đã chọn không đáp ứng được.",
"Chọn hàng đợi rồi cần đọc lại · tin ngữ nghĩa theo tài liệu mà không kiểm · bỏ qua giới hạn kích thước thông điệp · coi dịch vụ được quản lý là miễn trừ khỏi việc khử trùng.",
"Ngữ nghĩa quan sát được khớp tuyên bố ở cả hai dịch vụ, bốn giới hạn được ghi lại, và một yêu cầu không đáp ứng được chỉ ra."),

(367,"Reliability - failure domains, RPO and RTO with a tested restore","TH","Lesson 366",
"Độ tin cậy phát biểu bằng hai con số và chúng phải đo được chứ tuyên bố. Mục tiêu điểm phục hồi là lượng dữ liệu chấp nhận mất tính theo thời gian; mục tiêu thời gian phục hồi là thời gian chấp nhận ngừng phục vụ. Hai con số này quyết định kiến trúc chứ ngược lại. Nhiều khu khả dụng chống mất một khu; nhiều vùng chống mất một vùng và đắt hơn nhiều; sao lưu chống lỗi logic mà hai cái kia không chống được. **Một bản sao lưu chưa được phục hồi thử thì không phải bản sao lưu**, và ba nguyên nhân làm phục hồi thất bại dù bản sao lưu tồn tại là thiếu quyền, thiếu khoá mã hoá, và bản sao lưu nằm trong cùng tài khoản đã bị xoá. Hạn mức và phụ thuộc bên ngoài là miền hỏng thứ tư hay bị quên: hết hạn mức thì không tạo được tài nguyên thay thế giữa lúc sự cố.",
"Đo được cả hai con số phục hồi bằng một lần phục hồi thật vào môi trường sạch.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là số đo từ một lần phục hồi thật, không phải một kế hoạch. Kiểm bằng diễn tập phục hồi; đạt khi hai con số đo được, dữ liệu sau phục hồi đối soát khớp, và ba nguyên nhân thất bại được kiểm tường minh.",
"Đặt mục tiêu hai con số cho một dịch vụ. Tạo sao lưu và phục hồi vào một tài khoản hoặc dự án sạch; bấm giờ và đối soát dữ liệu. Kiểm ba nguyên nhân thất bại bằng cách thử phục hồi khi thiếu quyền và khi thiếu khoá. Mất một khu khả dụng có kiểm soát và đo lại. Kiểm hạn mức còn đủ để tạo tài nguyên thay thế.",
"Coi có lịch sao lưu là có khả năng phục hồi · phục hồi vào chính môi trường cũ nên không kiểm được phụ thuộc · để sao lưu cùng tài khoản với dữ liệu gốc · bỏ qua hạn mức khi lập kế hoạch phục hồi.",
"Hai con số phục hồi đo được từ một lần phục hồi thật vào môi trường sạch, dữ liệu đối soát khớp, và ba nguyên nhân thất bại được kiểm."),

(368,"Cost - unit economics, egress and the budget alarm","TH","Lesson 367",
"Chi phí là một ràng buộc thiết kế và phải đo theo đơn vị công việc chứ theo tổng hoá đơn. Sáu thành phần: số yêu cầu, thời gian tính toán, dung lượng lưu trữ, thao tác vào ra, lưu lượng ra ngoài, và năng lực nhàn rỗi. Hai thành phần hay gây bất ngờ nhất là lưu lượng ra ngoài theo lesson 363 và năng lực nhàn rỗi, vì cả hai không tỉ lệ với lượng công việc hữu ích. Chi phí trên mỗi đơn vị là con số so sánh được: chi phí trên mỗi nghìn yêu cầu, trên mỗi lần làm mới bảng, trên mỗi người dùng hoạt động, nối với lesson 198. Gắn thẻ tài nguyên là điều kiện để quy chi phí về đội và về sản phẩm; không gắn thẻ thì không quy được và không ai chịu trách nhiệm. **Cảnh báo ngân sách phải đặt trước khi chạy khối lượng công việc mới**, không phải sau khi nhận hoá đơn. Cam kết dài hạn chỉ hợp lý sau khi đã có dữ liệu sử dụng ổn định.",
"Tính chi phí trên mỗi đơn vị cho ba khối lượng công việc và dựng cảnh báo ngân sách trước khi chạy.",
"Tầng *áp dụng*. Objective đòi nối chi phí với đơn vị công việc chứ đọc tổng hoá đơn. Kiểm bằng đối chiếu ước tính với hoá đơn thật; đạt khi sai lệch dưới ngưỡng thoả thuận ở cả ba và cảnh báo ngân sách kích hoạt đúng ngưỡng.",
"Với ba khối lượng công việc, ước tính sáu thành phần chi phí trước khi chạy. Gắn thẻ mọi tài nguyên. Chạy một chu kỳ rồi đối chiếu ước tính với chi phí thật và giải thích chênh lệch. Tính chi phí trên mỗi đơn vị cho từng cái. Dựng cảnh báo ngân sách và kích hoạt nó bằng một khối lượng thử. Xác định ba yếu tố nhạy cảm nhất.",
"Đọc tổng hoá đơn mà không quy về đơn vị công việc · bỏ lưu lượng ra ngoài khỏi ước tính · không gắn thẻ nên không quy được chi phí · cam kết dài hạn trước khi có dữ liệu sử dụng.",
"Sai lệch giữa ước tính và chi phí thật dưới ngưỡng ở cả ba, chi phí trên mỗi đơn vị tính được, và cảnh báo ngân sách kích hoạt đúng."),

(369,"Secrets, keys and the audit trail","TH","Lesson 368",
"Bài chốt phần bảo mật nền tảng bằng ba cơ chế. Kho bí mật giữ thông tin xác thực ngoài mã và ngoài ảnh máy, và cho phép xoay mà không sửa mã; xoay phải thử được chứ để trong tài liệu. Dịch vụ quản lý khoá giữ khoá mã hoá và ghi lại mọi lần dùng; điểm quan trọng và hay bị bỏ qua: **ai sở hữu khoá thì thực sự kiểm soát dữ liệu**, nên khoá nằm ở tài khoản khác với dữ liệu là một biện pháp phòng vệ thật. Mã hoá khi truyền và khi lưu là hai lớp khác nhau và cả hai đều cần. Nhật ký kiểm toán ghi ai làm gì lúc nào; nó chỉ có giá trị nếu được giữ ở nơi mà kẻ tấn công không xoá được, nên tách tài khoản lưu nhật ký là thực hành chuẩn. Ba phép kiểm tự động phải chạy trong tích hợp liên tục: không có khoá tĩnh, không có tài nguyên mở công khai ngoài ý muốn, và không có chính sách dùng ký tự đại diện.",
"Dựng ba cơ chế và chứng minh xoay thông tin xác thực không gián đoạn cùng nhật ký kiểm toán đầy đủ.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là xoay thật và truy vết thật. Kiểm bằng phép thử xoay cộng truy vết; đạt khi xoay không gây gián đoạn, mọi thao tác nhạy cảm truy được trong nhật ký, và ba phép kiểm tự động chặn đúng vi phạm tiêm.",
"Chuyển toàn bộ thông tin xác thực sang kho bí mật. Thực hiện một lần xoay khi dịch vụ đang chạy và đo gián đoạn. Mã hoá một tập dữ liệu bằng khoá do mình quản lý; thu hồi quyền dùng khoá và chứng minh dữ liệu không đọc được. Tách tài khoản lưu nhật ký. Tiêm ba vi phạm và xác nhận ba phép kiểm tự động chặn được.",
"Xoay bằng cách dừng dịch vụ · để khoá mã hoá cùng tài khoản với dữ liệu · lưu nhật ký kiểm toán trong chính tài khoản bị kiểm · coi mã hoá khi lưu là đủ khi thiếu kiểm soát khoá.",
"Xoay thông tin xác thực không gây gián đoạn, thao tác nhạy cảm truy được trong nhật ký, và ba vi phạm tiêm đều bị chặn."),

(370,"The primitive table - mapping one cloud to the others","LT","Lesson 369",
"Bài cuối phần lý thuyết, và nó chỉ được học sau khi đã triển khai trên một đám mây. Bảng trừu tượng liệt kê bảy trừu tượng ở các bài trước theo hàng và ba nhà cung cấp theo cột, mỗi ô ghi tên dịch vụ tương ứng. Nhưng giá trị của bảng nằm ở cột thứ tư: **khác biệt về ngữ nghĩa, chứ khác biệt về tên**. Bốn chỗ khác biệt thật và phải ghi rõ: mô hình danh tính và cách chính sách giao nhau; mô hình mạng và cách lưu lượng ra được tính tiền; sự kiện của kho đối tượng có bảo đảm gì về thứ tự và về giao nhận; và cơ sở dữ liệu được quản lý khác nhau ở cách chuyển dự phòng cùng giới hạn kết nối. Cảnh báo về trừu tượng hoá sớm: xây một lớp trừu tượng chung cho nhiều đám mây trước khi một đám mây chạy được là cách chắc chắn có một lớp sai ở cả hai phía.",
"Lập bảng ánh xạ bảy trừu tượng và ghi được khác biệt ngữ nghĩa chứ chỉ khác biệt tên.",
"Tầng *hiểu*. Bài lý thuyết đặt sau khi đã triển khai, đúng thứ tự của hợp đồng nguồn. Kiểm bằng bảng ánh xạ; đạt khi mỗi hàng có ít nhất một khác biệt ngữ nghĩa cụ thể chứ chỉ tên dịch vụ.",
"Lập bảng bảy trừu tượng nhân ba nhà cung cấp. Với bốn hàng quan trọng nhất, tra tài liệu chính thức và ghi khác biệt ngữ nghĩa cụ thể kèm ngày tra. Chọn một kiến trúc đã dựng và mô tả nó phải đổi gì nếu chuyển sang đám mây khác. Viết hai câu nêu vì sao chưa nên xây lớp trừu tượng chung lúc này.",
"Lập bảng chỉ ghi tên dịch vụ · kết luận hai dịch vụ tương đương vì cùng loại · học ba đám mây song song · xây lớp trừu tượng chung trước khi một đám mây chạy được.",
"Mỗi hàng có ít nhất một khác biệt ngữ nghĩa cụ thể kèm nguồn và ngày tra, và bốn hàng quan trọng nhất có mô tả thay đổi khi chuyển đám mây."),

(371,"Landing zone project - one cloud, one data service","DA","Lesson 370",
"Bài dự án khép module. Dựng một lát cắt nền tảng trên đám mây đã chọn, gồm: ranh giới tài khoản hoặc dự án theo môi trường; danh tính với quyền tối thiểu và danh tính cho khối lượng công việc; mạng có dải riêng, đường ra được kiểm soát và ít nhất một điểm cuối riêng; một dịch vụ dữ liệu gồm giao diện lập trình, cơ sở dữ liệu và một đường xử lý ghi ra kho đối tượng; bí mật và khoá theo lesson 369; nhật ký, số đo và nhật ký kiểm toán; sao lưu cùng một lần phục hồi đã thử; và gắn thẻ cùng cảnh báo ngân sách. Toàn bộ phải dựng bằng mã theo M20, để dựng lại được từ đầu. Nộp kèm sơ đồ kiến trúc có đủ năm thứ: danh tính, mạng, đường dữ liệu, miền hỏng và ranh giới chi phí; và một bảng chi phí hằng tháng kèm ba yếu tố nhạy cảm nhất.",
"Nộp lát cắt nền tảng dựng lại được từ mã, không có khoá tĩnh, có phục hồi đã thử và chi phí đã đo.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module. Kiểm bằng dựng lại từ đầu cộng rà soát bằng chứng; đạt khi môi trường dựng lại được từ mã trong môi trường sạch, phục hồi thành công với đối soát, và không có khoá tĩnh hay tài nguyên mở công khai ngoài ý muốn.",
"Dựng lát cắt nền tảng đầy đủ bằng mã. Xoá sạch môi trường rồi dựng lại từ đầu chỉ bằng mã và sao lưu; bấm giờ. Chạy bộ quét bảo mật ba phép kiểm. Phục hồi dữ liệu và đối soát. Nộp sơ đồ năm thứ và bảng chi phí hằng tháng kèm ba yếu tố nhạy cảm.",
"Tạo tài nguyên bằng tay rồi ghi lại vào mã sau · mở công khai một kho đối tượng cho tiện · bỏ bước dựng lại từ đầu vì tốn thời gian · nộp sơ đồ hộp không có miền hỏng và ranh giới chi phí.",
"Môi trường dựng lại được từ mã trong môi trường sạch, phục hồi có đối soát khớp, không khoá tĩnh và không tài nguyên mở ngoài ý muốn, và bảng chi phí có ba yếu tố nhạy cảm."),

(372,"Failure drill - remove a zone, a service and a credential","TH","Lesson 371",
"Bài diễn tập khép module, chạy trên chính lát cắt nền tảng vừa dựng, với hành vi kỳ vọng viết trước. Sáu tình huống bắt buộc: mất một khu khả dụng; một dịch vụ được quản lý bị suy giảm trong vùng; mặt phẳng điều khiển không dùng được nên không tạo được tài nguyên mới; thông tin xác thực hết hạn giữa lúc chạy; chạm hạn mức của một dịch vụ; và một cú sốc chi phí do lượng quét hoặc lưu lượng ra tăng gấp mười. Với mỗi tình huống ghi ba số: thời gian phát hiện, mức suy giảm dịch vụ, và thời gian phục hồi. **Tình huống cú sốc chi phí phải trả lời bằng thiết kế lại có số đo trên mỗi đơn vị, chứ bằng việc tắt bớt tính năng**. Kết quả diễn tập là đầu vào sửa sổ tay vận hành và sửa kiến trúc, theo đúng kỷ luật ở lesson 246.",
"Chạy sáu tình huống với hành vi kỳ vọng viết trước và đề xuất thiết kế lại cho cú sốc chi phí.",
"Tầng *đánh giá*. Objective đo năng lực vận hành dưới sự cố cùng dưới ràng buộc chi phí. Kiểm bằng sáu tình huống; đạt khi ít nhất năm phục hồi trong mục tiêu thời gian đã đặt và cú sốc chi phí có phương án thiết kế lại kèm số đo trên mỗi đơn vị.",
"Viết hành vi kỳ vọng cho sáu tình huống trước khi chạy. Chạy từng cái trên lát cắt nền tảng. Ghi ba số cho mỗi tình huống. Với tình huống hạn mức, chứng minh cảnh báo nổ trước khi chạm trần. Với cú sốc chi phí, tính lại chi phí trên mỗi đơn vị và đề xuất thiết kế lại. Sửa sổ tay vận hành theo chênh lệch quan sát được.",
"Viết hành vi kỳ vọng sau khi thấy kết quả · xử lý cú sốc chi phí bằng cách tắt tính năng · bỏ tình huống mặt phẳng điều khiển vì khó dựng · không đo mức suy giảm mà chỉ đo phục hồi.",
"≥ 5/6 tình huống phục hồi trong mục tiêu thời gian, cú sốc chi phí có phương án thiết kế lại kèm số đo trên mỗi đơn vị, và sổ tay được sửa."),
]

M20 = ("Containers, Infrastructure as Code and Kubernetes", 373, 388, """| | |
|---|---|
| **Objective cấp module** | Giải thích được mọi trường trong bản khai báo mình dùng thông qua hành vi của bộ điều khiển và của môi trường chạy; dựng lại được cụm cùng dịch vụ từ mã, kho ảnh và bản sao lưu |
| **Tiền đề** | M5 · M6 · M7 · M19 |
| **Exit criterion** | Ảnh bất biến và kế hoạch hạ tầng tái tạo được; quay lui đã thử; không rò rỉ bí mật; chẩn đoán được vòng lặp khởi động lại, trạng thái chờ, bị kết thúc vì hết bộ nhớ, thăm dò hỏng và sự cố triển khai |
| **Kỹ năng SFIA** | `SYSP` mức 4 · `ITOP` mức 4 · `PROG` mức 4 |
| **Chế độ hỏng** | Sửa trực tiếp trên cụm rồi coi là xong, chạy không đặt giới hạn tài nguyên và không có thăm dò, và dùng điều phối vùng chứa ở nơi một máy ảo hoặc một dịch vụ được quản lý an toàn hơn |""",
"""Module có một câu hỏi lọc đặt ngay ở bài về điều phối: **khi nào một cách triển khai đơn giản hơn lại thắng**. Điều phối vùng chứa là một khoản thuế vận hành, và trả khoản thuế đó chỉ hợp lý khi có đủ dịch vụ và đủ nhu cầu tự phục hồi.

Kỷ luật xuyên module: **mọi thay đổi đi qua mã, không đi qua thao tác tay trên cụm**. Sửa tay là cách chắc chắn làm môi trường trôi khỏi mã và làm mất khả năng dựng lại.

Ba tầng được học theo thứ tự cơ chế: tiến trình bị cô lập, trạng thái mong muốn, rồi vòng lặp hoà giải.""")

L20 = [
(373,"A container is an isolated process","LT","Module 20: M19",
"Bài mở module bằng việc bác bỏ một hình dung sai phổ biến: vùng chứa không phải máy ảo nhỏ. Nó là một tiến trình thường của hệ điều hành máy chủ, chỉ khác ở chỗ nó nhìn thấy một thế giới bị giới hạn. Ba cơ chế tạo ra giới hạn đó: không gian tên làm tiến trình chỉ thấy một tập tiến trình, một cây thư mục, một giao diện mạng và một tập người dùng riêng; nhóm điều khiển giới hạn lượng bộ xử lý và bộ nhớ nó dùng được; khả năng cùng bộ lọc lời gọi hệ thống giới hạn nó làm được gì với nhân. **Vì dùng chung nhân với máy chủ, mức cô lập yếu hơn máy ảo**, và đó là lý do khối lượng công việc không tin cậy cần thêm lớp cách ly. Hệ quả thực hành quan trọng: tiến trình trong vùng chứa vẫn chịu lịch biểu của nhân máy chủ, nên bị điều tiết vì vượt hạn mức bộ xử lý trông giống như chậm không rõ nguyên nhân.",
"Quan sát ba cơ chế cô lập bằng công cụ và giải thích một lần bị điều tiết bằng nhóm điều khiển.",
"Tầng *hiểu*. Bài mở module, kiểm bằng quan sát hệ thật chứ bằng lập luận. Kiểm bằng bài quan sát cộng thí nghiệm hạn mức; đạt khi ba không gian tên được chỉ ra bằng công cụ và hiện tượng điều tiết được tái hiện kèm số đo.",
"Chạy một vùng chứa và từ máy chủ tìm tiến trình tương ứng. Kiểm tra bốn không gian tên của nó và so với của máy chủ. Đặt hạn mức bộ xử lý thấp và chạy một tải tính toán; đo mức điều tiết. Đặt hạn mức bộ nhớ thấp và quan sát tiến trình bị kết thúc vì hết bộ nhớ. Ghi lại khác biệt so với chạy trên máy ảo.",
"Coi vùng chứa là máy ảo nhỏ · chạy khối lượng công việc không tin cậy mà không thêm lớp cách ly · không đặt hạn mức nên một vùng chứa ăn hết máy · kết luận chậm mà không kiểm mức điều tiết.",
"Bốn không gian tên được chỉ ra bằng công cụ, và hiện tượng điều tiết cùng bị kết thúc vì hết bộ nhớ được tái hiện kèm số đo."),

(374,"Images, layers, digests and the multi-stage build","TH","Lesson 373",
"Ảnh là một chồng lớp chỉ đọc cộng siêu dữ liệu, và hiểu cấu trúc đó giải thích cả tốc độ dựng lẫn kích thước. Mỗi chỉ thị dựng tạo một lớp; lớp được chia sẻ giữa các ảnh nhờ nội dung giống nhau, nên thứ tự chỉ thị quyết định bộ đệm dựng có dùng lại được không: **đặt bước cài phụ thuộc trước bước sao chép mã nguồn là mẹo quan trọng nhất**, vì mã đổi thường xuyên còn phụ thuộc thì không. Thẻ có thể bị đẩy lại trỏ sang ảnh khác, còn mã băm nội dung thì không; nên ghim theo mã băm là điều kiện để triển khai tái tạo được. Dựng nhiều giai đoạn tách môi trường biên dịch khỏi ảnh chạy, giảm kích thước và giảm bề mặt tấn công. Một điểm bắt buộc: **bí mật đưa vào trong một lớp thì vẫn nằm đó dù lớp sau có xoá**, vì lớp trước vẫn tồn tại trong ảnh.",
"Dựng ảnh nhiều giai đoạn nhỏ hơn đáng kể, ghim theo mã băm, và chứng minh không bí mật nào nằm trong lớp.",
"Tầng *áp dụng*. Objective có ba tiêu chí nghiệm thu đo được. Kiểm bằng cặp số đo cộng bộ quét; đạt khi kích thước giảm có số đo, thời gian dựng lại giảm nhờ bộ đệm, và bộ quét lớp không tìm thấy bí mật.",
"Dựng một ảnh theo cách thông thường rồi dựng lại theo nhiều giai đoạn; so kích thước và số lớp. Đảo thứ tự bước cài phụ thuộc và bước sao chép mã, đo thời gian dựng lại sau khi sửa một dòng mã ở cả hai cách. Ghim ảnh nền theo mã băm. Cố ý đưa một bí mật vào một lớp rồi xoá ở lớp sau; dùng công cụ tìm lại nó trong lịch sử lớp.",
"Sao chép mã nguồn trước khi cài phụ thuộc · ghim ảnh nền theo thẻ · đưa bí mật vào thời điểm dựng · chạy bằng người dùng cao nhất trong vùng chứa.",
"Kích thước ảnh giảm có số đo, thời gian dựng lại giảm nhờ thứ tự lớp, và bí mật đã xoá vẫn tìm lại được ở bản sai rồi được loại bỏ hẳn ở bản đúng."),

(375,"PID 1, signals and graceful shutdown in a container","TH","Lesson 374",
"Tiến trình đầu tiên trong vùng chứa mang số một, và nó có hành vi đặc biệt của nhân: nó không nhận tín hiệu mặc định như tiến trình thường. Hệ quả cụ thể và phải tái hiện: **nếu tiến trình chính không xử lý tín hiệu kết thúc thì nó bị buộc dừng sau thời gian chờ, nên công việc đang dở bị cắt ngang**; với một tiến trình ghi dữ liệu thì đó là mất dữ liệu hoặc ghi dở. Chạy tiến trình qua một lớp vỏ làm tín hiệu không tới được tiến trình thật, là lỗi hay gặp nhất. Tiến trình con mồ côi tích tụ khi tiến trình số một không thu hồi chúng. Tắt có kiểm soát trong vùng chứa gồm ba bước theo lesson 67: nhận tín hiệu, ngừng nhận việc mới, hoàn tất việc đang dở rồi thoát, tất cả trong khoảng thời gian chờ đã cấu hình. Chạy bằng người dùng không đặc quyền và hệ tệp chỉ đọc là hai biện pháp giảm rủi ro.",
"Chứng minh tiến trình trong vùng chứa tắt có kiểm soát trong thời gian chờ và không mất công việc đang dở.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là không mất việc khi dừng. Kiểm bằng phép thử dừng; đạt khi 100 lần dừng đều hoàn tất việc đang dở, và bản chạy qua lớp vỏ được chứng minh là bị cắt ngang.",
"Viết một tiến trình xử lý có việc kéo dài vài giây. Đóng gói theo hai cách: chạy trực tiếp và chạy qua một lớp vỏ. Dừng vùng chứa 100 lần ở cả hai cách và đếm số việc bị cắt ngang. Thêm xử lý tín hiệu và tắt có kiểm soát. Kiểm tiến trình con mồ côi. Chuyển sang chạy bằng người dùng không đặc quyền với hệ tệp chỉ đọc.",
"Chạy tiến trình qua một lớp vỏ nên tín hiệu không tới · không xử lý tín hiệu kết thúc · đặt thời gian chờ ngắn hơn việc dài nhất · chạy bằng người dùng cao nhất.",
"100 lần dừng đều hoàn tất việc đang dở ở bản đúng, và bản chạy qua lớp vỏ được chứng minh bị cắt ngang kèm số việc mất."),

(376,"Container networking, volumes and the UID mismatch","TH","Lesson 375",
"Hai phần hạ tầng của vùng chứa và ba lỗi đặc trưng của chúng. Mạng: vùng chứa có không gian tên mạng riêng, nối với máy chủ qua một cặp giao diện ảo và một cầu nối; ánh xạ cổng dịch địa chỉ từ máy chủ vào; phân giải tên giữa các vùng chứa dùng một máy chủ tên nội bộ. Truy vết đường đi của một gói từ ngoài vào ứng dụng là bài tập bắt buộc. Ổ đĩa: dữ liệu trong lớp ghi của vùng chứa biến mất khi vùng chứa bị xoá, nên **mọi dữ liệu cần giữ phải nằm trên ổ đĩa gắn ngoài**. Lỗi đặc trưng thứ ba và tốn thời gian nhất: định danh người dùng bên trong vùng chứa khác định danh sở hữu tệp trên máy chủ, nên tiến trình không ghi được vào thư mục gắn vào dù quyền trông có vẻ đúng; cách chẩn đoán là so định danh số chứ so tên người dùng.",
"Truy vết đường gói tin vào ứng dụng và chẩn đoán đúng lỗi lệch định danh người dùng.",
"Tầng *áp dụng*. Objective gồm một lỗi có triệu chứng gây hiểu nhầm. Kiểm bằng bài truy vết cộng ba lỗi tiêm; đạt khi sơ đồ đường gói khớp truy vết thật và ba lỗi được chẩn đoán đúng nguyên nhân.",
"Chạy nhiều dịch vụ nối nhau. Truy vết đường đi của một yêu cầu từ máy chủ vào ứng dụng qua ánh xạ cổng và cầu nối; vẽ sơ đồ. Tiêm ba lỗi: sai tên dịch vụ khi phân giải, dữ liệu mất vì không gắn ổ đĩa, và tiến trình không ghi được vì lệch định danh người dùng. Chẩn đoán từng cái bằng số đo chứ đoán.",
"Ghi dữ liệu vào lớp ghi của vùng chứa · chẩn đoán quyền bằng tên người dùng thay vì định danh số · mở cổng ra máy chủ khi chỉ cần gọi nội bộ · giả định phân giải tên giữa vùng chứa giống trên máy chủ.",
"Sơ đồ đường gói khớp truy vết thật, và ba lỗi tiêm được chẩn đoán đúng nguyên nhân kèm bằng chứng."),

(377,"Supply chain - minimal base, pinned digest, no secret in a layer","TH","Lesson 376",
"Ảnh là một hiện vật được phân phối, nên nó có chuỗi cung ứng và chuỗi đó là một bề mặt tấn công. Năm biện pháp theo thứ tự hiệu quả: chọn ảnh nền tối thiểu để giảm số gói và giảm số lỗ hổng phải theo; ghim theo mã băm để bản dựng tái tạo được; quét lỗ hổng trong tích hợp liên tục có cửa chặn; sinh bản kê thành phần để biết mình đang chạy những gì; và ký cùng kiểm nguồn gốc ở mức nhận biết. **Quét mà không chặn thì chỉ là một báo cáo không ai đọc**, nên ngưỡng chặn phải đặt tường minh kèm quy trình miễn trừ có hạn, theo đúng kỷ luật ở lesson 276. Bí mật trong tích hợp liên tục phải lấy từ kho bí mật và không bao giờ ghi ra nhật ký. Ba rủi ro riêng của chuỗi cung ứng ảnh: ảnh nền bị đẩy lại dưới cùng một thẻ, phụ thuộc bắc cầu không ai kiểm, và kho ảnh nội bộ không có kiểm soát truy cập.",
"Dựng quy trình có cửa chặn lỗ hổng và bản kê thành phần, chặn được ba vi phạm tiêm.",
"Tầng *áp dụng*. Objective là một cửa chặn tự động có phép thử tiêm. Kiểm bằng ba vi phạm; đạt khi cả ba bị chặn ở đúng bước, bản kê thành phần sinh được, và mọi miễn trừ có hạn.",
"Dựng quy trình gồm quét lỗ hổng có ngưỡng chặn, sinh bản kê thành phần, và kiểm ghim mã băm. Tiêm ba vi phạm: ảnh nền ghim theo thẻ, một phụ thuộc có lỗ hổng nghiêm trọng, và một bí mật lọt vào lớp. Xác nhận cả ba bị chặn. So số lỗ hổng giữa ảnh nền đầy đủ và ảnh nền tối thiểu. Đặt hạn cho mọi miễn trừ.",
"Quét mà không chặn · ghim ảnh nền theo thẻ · miễn trừ lỗ hổng không có hạn · để nhật ký tích hợp liên tục in ra bí mật.",
"Ba vi phạm bị chặn ở đúng bước, bản kê thành phần sinh được, số lỗ hổng giảm có số đo khi đổi ảnh nền, và mọi miễn trừ có hạn."),

(378,"Infrastructure as code - desired state and the dependency graph","LT","Lesson 377",
"Bài mở phần hạ tầng khai báo bằng mô hình tư duy của nó. Ta mô tả trạng thái mong muốn; công cụ so trạng thái mong muốn với trạng thái đã ghi và với thực tế, rồi tính ra tập thay đổi tối thiểu. Đồ thị phụ thuộc giữa các tài nguyên được suy ra từ tham chiếu, nên nó quyết định thứ tự tạo và thứ tự xoá; phụ thuộc ngầm không khai báo được là nguồn của lỗi thứ tự khó tái hiện. Bốn loại hành động trong một bản kế hoạch và ý nghĩa rủi ro rất khác nhau: tạo, cập nhật tại chỗ, **thay thế tức xoá rồi tạo lại**, và xoá; loại thứ ba là loại nguy hiểm nhất vì một thay đổi trông nhỏ có thể kéo theo thay thế một cơ sở dữ liệu sản xuất. Từ đó suy ra quy tắc bắt buộc: **đọc kế hoạch trước khi áp dụng, và mọi hành động thay thế hoặc xoá ở môi trường sản xuất phải được người thứ hai duyệt**.",
"Đọc một bản kế hoạch và nhận ra mọi hành động thay thế cùng hệ quả của chúng.",
"Tầng *hiểu*. Bài lý thuyết đặt khung cho hai bài thực hành. Kiểm bằng bài đọc kế hoạch; đạt khi nhận đúng mọi hành động thay thế trong ba kế hoạch và giải thích được nguyên nhân gây thay thế.",
"Cho ba bản kế hoạch thật, mỗi cái chứa ít nhất một hành động thay thế. Với mỗi cái, liệt kê bốn loại hành động và chỉ ra tài nguyên nào bị thay thế cùng thuộc tính nào gây ra. Vẽ đồ thị phụ thuộc của một tập tài nguyên và suy ra thứ tự xoá. Tạo một ca có phụ thuộc ngầm và chỉ ra lỗi thứ tự nó gây ra.",
"Áp dụng mà không đọc kế hoạch · bỏ qua hành động thay thế vì thấy thay đổi nhỏ · dựa vào thứ tự viết trong tệp thay vì đồ thị phụ thuộc · không khai báo phụ thuộc ngầm.",
"Nhận đúng mọi hành động thay thế trong ba kế hoạch kèm thuộc tính gây ra, và thứ tự xoá suy đúng từ đồ thị phụ thuộc."),

(379,"State, locking, drift and the recovery you must not improvise","TH","Lesson 378",
"Tệp trạng thái là bản ghi công cụ tin về thế giới, và nó là thành phần quan trọng nhất cần bảo vệ. Ba yêu cầu bắt buộc: lưu từ xa và mã hoá vì nó chứa thông tin nhạy cảm; khoá khi đang áp dụng để hai người không cùng sửa; và có phiên bản để quay lại được. Trôi cấu hình xảy ra khi ai đó sửa tay trên đám mây: thực tế khác trạng thái ghi, và lần áp dụng tiếp theo sẽ hoàn tác thay đổi tay đó mà không báo trước; **phát hiện trôi định kỳ là biện pháp phòng ngừa chứ một việc làm khi có sự cố**. Nhập tài nguyên có sẵn và di chuyển tài nguyên trong mã là hai thao tác hay cần. Quy tắc nghiêm nhất của bài: **không sửa tay tệp trạng thái khi chưa có bản sao lưu**, vì một thao tác sai làm công cụ quên mất tài nguyên đang chạy và lần áp dụng sau sẽ tạo trùng hoặc xoá nhầm.",
"Vận hành trạng thái từ xa có khoá, phát hiện và xử lý trôi cấu hình, và phục hồi sau một sự cố trạng thái.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là phục hồi được mà không mất tài nguyên. Kiểm bằng ba tình huống; đạt khi trôi được phát hiện tự động, khoá chặn được áp dụng song song, và phục hồi trạng thái không làm mất hay tạo trùng tài nguyên nào.",
"Dựng trạng thái từ xa có mã hoá, khoá và phiên bản. Chạy hai lần áp dụng song song và xác nhận bị chặn. Sửa tay một tài nguyên trên đám mây rồi chạy phát hiện trôi; quyết định hoàn tác hay nhập vào mã. Mô phỏng mất tệp trạng thái và phục hồi từ phiên bản trước; đối soát danh sách tài nguyên thật với trạng thái sau phục hồi.",
"Để tệp trạng thái trên máy cá nhân · sửa tay tệp trạng thái mà không sao lưu · bỏ qua trôi cấu hình tới khi lần áp dụng sau hoàn tác nó · để lộ giá trị nhạy cảm trong đầu ra.",
"Áp dụng song song bị khoá chặn, trôi cấu hình được phát hiện tự động, và phục hồi trạng thái không làm mất hay tạo trùng tài nguyên nào."),

(380,"Modules, environments and the plan review","TH","Lesson 379",
"Tổ chức mã hạ tầng để nhiều môi trường dùng chung mà không sao chép. Hợp đồng của một mô đun gồm đầu vào có kiểm tra giá trị, đầu ra, phiên bản nhà cung cấp và cách nâng cấp; nó chịu cùng kỷ luật hợp đồng như một thư viện phần mềm ở M7. Chiến lược môi trường: tách tài khoản hoặc dự án theo môi trường là ranh giới mạnh nhất, tách bằng không gian tên trong cùng tài khoản là ranh giới yếu và dễ nhầm. Danh tính cho quy trình tự động phải riêng và có quyền tối thiểu, không dùng lại thông tin xác thực của người. Rà soát kế hoạch trong tích hợp liên tục: hiển thị kế hoạch trong yêu cầu hợp nhất, chạy kiểm chính sách để chặn cấu hình cấm, và ước tính chi phí của thay đổi. **Áp dụng ở môi trường sản xuất phải có phê duyệt của người thứ hai**, và hiện vật của lần áp dụng được giữ lại để truy vết.",
"Dựng quy trình rà soát kế hoạch có kiểm chính sách và phê duyệt, chặn được ba cấu hình cấm.",
"Tầng *áp dụng*. Objective là một cửa chặn tự động cộng một cửa chặn người. Kiểm bằng ba vi phạm tiêm; đạt khi cả ba bị kiểm chính sách chặn và mọi lần áp dụng ở môi trường sản xuất đều có dấu phê duyệt cùng hiện vật lưu lại.",
"Tách mã thành mô đun có kiểm tra đầu vào và ghim phiên bản nhà cung cấp. Dựng quy trình hiển thị kế hoạch trong yêu cầu hợp nhất, chạy kiểm chính sách và ước tính chi phí. Tiêm ba cấu hình cấm gồm mở công khai, chính sách dùng ký tự đại diện, và một hành động thay thế cơ sở dữ liệu. Xác nhận bị chặn. Áp dụng ở môi trường sản xuất có phê duyệt và lưu hiện vật.",
"Sao chép mã giữa các môi trường thay vì dùng mô đun · dùng thông tin xác thực cá nhân cho quy trình tự động · áp dụng ở sản xuất không cần phê duyệt · không ghim phiên bản nhà cung cấp.",
"Ba cấu hình cấm bị chặn bởi kiểm chính sách, và mọi lần áp dụng ở sản xuất có dấu phê duyệt cùng hiện vật lưu lại."),

(381,"Why orchestration, and when a simpler deployment wins","LT","Lesson 380",
"Bài đặt câu hỏi lọc trước khi học công cụ điều phối, vì đây là chỗ nhiều đội trả thuế vận hành mà không cần. Bốn thứ điều phối cho: hoà giải về trạng thái mong muốn, lập lịch lên các nút, khám phá dịch vụ, và triển khai dần cùng tự khởi động lại. Khoản thuế phải trả: một mặt phẳng điều khiển phải vận hành và nâng cấp, một mô hình mạng và bảo mật mới phải học, và một lớp chẩn đoán mới nằm giữa mã và máy. Ba tình huống mà cách đơn giản hơn thắng: ít dịch vụ và tải ổn định thì máy ảo cùng trình quản lý dịch vụ ở lesson 69 là đủ; công việc theo lô chạy định kỳ thì một dịch vụ chạy vùng chứa được quản lý đủ và rẻ hơn; và đội chưa có năng lực vận hành nền tảng thì **khoản thuế vận hành lớn hơn lợi ích và rủi ro cao hơn**. Ba dấu hiệu một đội đang dùng điều phối vì nó phổ biến chứ vì ràng buộc thật.",
"So ba cách triển khai cho một dự án theo bốn tiêu chí và chọn một kèm điều kiện đảo ngược.",
"Tầng *đánh giá*. Objective chống lại việc mặc định chọn phương án phức tạp nhất. Kiểm bằng bảng ba cách nhân bốn tiêu chí; đạt khi hai tiêu chí đầu có số đo và lựa chọn kèm hai điều kiện đảo ngược cụ thể.",
"Triển khai cùng một dịch vụ theo ba cách: máy ảo cùng trình quản lý dịch vụ, dịch vụ vùng chứa được quản lý, và cụm điều phối. Đo thời gian triển khai đầu, thời gian một lần cập nhật, thời gian phục hồi khi mất một máy, và ước lượng giờ công vận hành mỗi tháng. Chọn một cho dự án và nêu hai điều kiện làm lựa chọn đó sai.",
"Chọn điều phối vì nó phổ biến · so ba cách mà không tính giờ công vận hành · bỏ qua yêu cầu nâng cấp mặt phẳng điều khiển · khuyến nghị không có điều kiện đảo ngược.",
"Ba cách có số đo ở hai tiêu chí đầu cùng ước lượng giờ công vận hành, và lựa chọn kèm hai điều kiện đảo ngược cụ thể."),

(382,"From object to controller - the five-step trace","TH","Lesson 381",
"Bài dạy cơ chế trung tâm của điều phối: vòng lặp hoà giải. Năm bước khi ta gửi một đối tượng: máy chủ giao diện xác thực, phân quyền, chạy các bộ kiểm nạp rồi lưu vào kho khoá giá trị; bộ điều khiển thấy đối tượng mới và tạo các đối tượng phụ thuộc; bộ lập lịch gán một đơn vị chạy vào một nút; tiến trình trên nút tạo môi trường chạy, gắn ổ đĩa, nối mạng rồi chạy vùng chứa, và các phép thăm dò cập nhật trạng thái sẵn sàng; bộ điều khiển quan sát trạng thái và tiếp tục hoà giải cho tới khi khớp trạng thái mong muốn. Hai ý phải rút ra: **đặc tả là mong muốn còn trạng thái là thực tế, và khoảng cách giữa chúng là nơi mọi sự cố nằm**; và **hệ khởi động lại hoặc lập lịch lại chứ không tự khôi phục trạng thái ứng dụng**. Sự kiện của đối tượng là nguồn chẩn đoán đầu tiên, trước nhật ký.",
"Truy đủ năm bước cho một lần triển khai thật và đọc được khoảng cách giữa đặc tả với trạng thái.",
"Tầng *phân tích*. Objective đòi quan sát cơ chế thật thay vì mô tả nó. Kiểm bằng bài truy vết; đạt khi năm bước có bằng chứng quan sát được và ba lần triển khai hỏng được quy đúng bước.",
"Gửi một đối tượng triển khai và theo dõi từng bước bằng sự kiện cùng trạng thái của các đối tượng liên quan. Ghi lại thời gian ở mỗi bước. Tạo ba lần triển khai hỏng ở ba bước khác nhau: bị bộ kiểm nạp từ chối, không lập lịch được, và không kéo được ảnh; với mỗi cái, quy về đúng bước chỉ bằng sự kiện và trạng thái.",
"Xem nhật ký ứng dụng trước khi xem sự kiện của đối tượng · giả định hệ khôi phục được trạng thái ứng dụng · sửa bằng cách xoá rồi tạo lại mà không tìm nguyên nhân · bỏ qua bước kiểm nạp khi chẩn đoán.",
"Năm bước có bằng chứng quan sát được kèm thời gian, và ba lần triển khai hỏng được quy đúng bước chỉ bằng sự kiện và trạng thái."),

(383,"Pods, probes, requests and limits","TH","Lesson 382",
"Bốn trường có ảnh hưởng lớn nhất tới hành vi thật, nên chúng có một bài riêng. Yêu cầu tài nguyên là thứ bộ lập lịch dùng để chọn nút; giới hạn tài nguyên là trần mà môi trường chạy cưỡng chế. **Đặt yêu cầu quá cao lãng phí năng lực, đặt quá thấp làm nút quá tải; đặt giới hạn bộ nhớ quá thấp làm tiến trình bị kết thúc vì hết bộ nhớ, còn giới hạn bộ xử lý gây điều tiết chứ kết thúc**, và phân biệt hai hiện tượng này là kỹ năng chẩn đoán chính. Ba loại thăm dò cho ba mục đích: thăm dò khởi động cho ứng dụng khởi động chậm, thăm dò sẵn sàng quyết định có nhận lưu lượng không, thăm dò sống quyết định có khởi động lại không. Chế độ hỏng đặc trưng: **thăm dò nông chỉ kiểm tiến trình còn sống làm một dịch vụ hỏng vẫn được đánh dấu sẵn sàng và vẫn nhận lưu lượng**; thăm dò sống quá nhạy gây vòng lặp khởi động lại dưới tải.",
"Đặt bốn trường từ số đo thật và phân biệt được bị kết thúc vì hết bộ nhớ với bị điều tiết bộ xử lý.",
"Tầng *áp dụng*. Objective đòi rút tham số từ đo lường và phân biệt hai triệu chứng gần giống. Kiểm bằng bốn tình huống tiêm; đạt khi bốn tình huống được chẩn đoán đúng và giá trị cuối dẫn được từ số đo chứ từ phỏng đoán.",
"Đo lượng bộ nhớ và bộ xử lý thật của một dịch vụ dưới tải; đặt yêu cầu và giới hạn từ số đo đó. Tiêm bốn tình huống: giới hạn bộ nhớ quá thấp, giới hạn bộ xử lý quá thấp, thăm dò sẵn sàng nông trên một dịch vụ hỏng, và thăm dò sống quá nhạy dưới tải. Chẩn đoán từng cái bằng sự kiện và số đo. Sửa và đo lại.",
"Đặt yêu cầu và giới hạn bằng con số tròn · bỏ giới hạn cho khỏi bị kết thúc · viết thăm dò sẵn sàng chỉ kiểm tiến trình còn sống · đặt thăm dò sống nhạy hơn thăm dò sẵn sàng.",
"Bốn tình huống được chẩn đoán đúng, và giá trị bốn trường dẫn được từ số đo tải thật."),

(384,"Service, endpoint, DNS and network policy","TH","Lesson 383",
"Cách lưu lượng tìm tới một đơn vị chạy, và bốn lỗi đặc trưng. Dịch vụ chọn các đơn vị chạy theo nhãn; danh sách điểm cuối được cập nhật khi trạng thái sẵn sàng đổi; tên dịch vụ phân giải qua máy chủ tên trong cụm. Từ đó suy ra chuỗi chẩn đoán có thứ tự: kiểm nhãn có khớp bộ chọn không, kiểm danh sách điểm cuối có rỗng không, kiểm phân giải tên, rồi mới kiểm ứng dụng. **Danh sách điểm cuối rỗng gần như luôn có nghĩa là nhãn sai hoặc không đơn vị nào sẵn sàng**, và đó là hai nguyên nhân chiếm phần lớn sự cố loại này. Cổng của dịch vụ khác cổng của vùng chứa và nhầm hai cái là lỗi phổ biến. Chính sách mạng mặc định cho phép mọi thứ nói chuyện với nhau; đặt chính sách từ chối mặc định rồi mở theo nhu cầu là thực hành đúng, theo nguyên tắc ở lesson 73.",
"Chẩn đoán bốn sự cố kết nối theo đúng thứ tự chuỗi và dựng chính sách mạng từ chối mặc định.",
"Tầng *áp dụng*. Objective có một chuỗi chẩn đoán có thứ tự và một cấu hình bảo mật kiểm được. Kiểm bằng bốn sự cố tiêm cộng phép thử phủ định; đạt khi cả bốn được chẩn đoán đúng nguyên nhân và chính sách từ chối mặc định chặn đúng mọi kết nối không được phép.",
"Tiêm bốn sự cố: nhãn không khớp bộ chọn, sai cổng, tên dịch vụ sai, và một đơn vị chạy chưa sẵn sàng. Với mỗi cái, chạy chuỗi chẩn đoán theo thứ tự và ghi bằng chứng ở mỗi bước. Đặt chính sách mạng từ chối mặc định rồi mở đúng các đường cần thiết; chạy phép thử phủ định cho mọi cặp dịch vụ.",
"Xem nhật ký ứng dụng trước khi kiểm danh sách điểm cuối · nhầm cổng dịch vụ với cổng vùng chứa · để chính sách mạng mặc định cho phép mọi thứ · sửa bằng cách khởi động lại.",
"Bốn sự cố được chẩn đoán đúng theo thứ tự chuỗi, và chính sách từ chối mặc định chặn đúng mọi kết nối không được phép trong phép thử phủ định."),

(385,"Config, secrets, volumes and stateful workloads","TH","Lesson 384",
"Tách cấu hình khỏi ảnh và xử lý trạng thái. Cấu hình và bí mật được gắn vào dưới dạng biến môi trường hoặc tệp; gắn dưới dạng tệp có lợi hơn vì cập nhật được mà không dựng lại đơn vị chạy và không lộ trong danh sách tiến trình. **Bí mật ở dạng mặc định chỉ được mã hoá cơ bản chứ mã hoá thật, nên nó cần lớp bảo vệ bổ sung**, chẳng hạn mã hoá khi lưu ở kho khoá giá trị hoặc lấy từ kho bí mật bên ngoài theo lesson 369. Ổ đĩa bền vững gắn vào đơn vị chạy và tồn tại độc lập với nó. Khối lượng công việc có trạng thái cần danh tính ổn định và ổ đĩa riêng cho từng bản sao; nhưng phải nói rõ giới hạn: **hệ điều phối cấp danh tính và ổ đĩa, còn việc sao chép dữ liệu giữa các bản sao vẫn là việc của ứng dụng**, nên chạy một cơ sở dữ liệu ở đây không tự có tính sẵn sàng cao.",
"Gắn cấu hình và bí mật an toàn, và chỉ ra chính xác điều mà khối lượng công việc có trạng thái không tự cho.",
"Tầng *áp dụng*. Objective gồm một giới hạn phải phát biểu đúng. Kiểm bằng phép thử cập nhật cộng bài lập luận; đạt khi cấu hình cập nhật được không dựng lại đơn vị chạy, bí mật không lộ trong nhật ký hay danh sách tiến trình, và giới hạn về sao chép dữ liệu được nêu đúng.",
"Gắn cấu hình theo cả hai cách và so: cập nhật giá trị rồi xem cách nào cần dựng lại đơn vị chạy. Lấy bí mật từ kho bên ngoài. Kiểm bí mật không xuất hiện trong nhật ký, trong biến môi trường in ra, hay trong đặc tả đối tượng. Chạy một khối lượng công việc có trạng thái ba bản sao; giết một bản và quan sát danh tính cùng ổ đĩa được giữ. Viết một đoạn nêu rõ phần sao chép dữ liệu ai lo.",
"Đưa bí mật vào biến môi trường rồi in ra nhật ký · tin bí mật ở dạng mặc định đã được mã hoá thật · nghĩ chạy cơ sở dữ liệu theo dạng có trạng thái là đã có sẵn sàng cao · gắn ổ đĩa chung cho nhiều bản sao cần ghi.",
"Cấu hình cập nhật được không dựng lại đơn vị chạy, bí mật không lộ ở cả ba nơi kiểm, và giới hạn về sao chép dữ liệu được nêu đúng."),

(386,"Rollout, rollback, drain and the disruption budget","TH","Lesson 385",
"Triển khai phiên bản mới mà không gián đoạn, và bốn cơ chế kiểm soát. Triển khai dần thay thế từng phần với hai tham số là số đơn vị thừa được tạo thêm và số đơn vị được phép không sẵn sàng; hai con số này quyết định tốc độ và mức rủi ro. Quay lui là thao tác phải thử trước khi cần, theo lesson 97. Rút nút ra khỏi phục vụ khi bảo trì phải phối hợp với tắt có kiểm soát ở lesson 375, nếu không thì yêu cầu đang xử lý bị cắt. Ngân sách gián đoạn giới hạn số đơn vị được phép mất cùng lúc do thao tác chủ động; **đặt ngân sách quá chặt làm việc rút nút bị kẹt vô hạn**, một bế tắc hay gặp khi cụm không còn đủ năng lực để tạo đơn vị thay thế. Triển khai song song hai phiên bản và triển khai thử với một phần lưu lượng là hai chiến lược an toàn hơn, đổi lại tốn năng lực gấp đôi hoặc cần định tuyến theo tỉ lệ.",
"Triển khai và quay lui không gián đoạn, và tái hiện được bế tắc do ngân sách gián đoạn quá chặt.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là không yêu cầu nào lỗi trong suốt quá trình. Kiểm bằng phép thử tải liên tục; đạt khi tỉ lệ lỗi bằng không suốt triển khai và quay lui, và bế tắc do ngân sách được tái hiện rồi gỡ.",
"Chạy tải liên tục trong lúc triển khai phiên bản mới; đo tỉ lệ lỗi và độ trễ. Thực hiện quay lui và đo lại. Rút một nút khi có tải và kiểm không yêu cầu nào bị cắt giữa chừng. Đặt ngân sách gián đoạn quá chặt rồi rút nút; quan sát bế tắc và gỡ bằng cách thêm năng lực hoặc nới ngân sách.",
"Triển khai mà không chạy tải nên không thấy lỗi · chưa từng thử quay lui · rút nút mà không có tắt có kiểm soát · đặt ngân sách gián đoạn mà không xét năng lực dự phòng.",
"Tỉ lệ lỗi bằng không suốt triển khai và quay lui, không yêu cầu nào bị cắt khi rút nút, và bế tắc do ngân sách được tái hiện rồi gỡ."),

(387,"Diagnosing ten broken workloads","TH","Lesson 386",
"Bài rèn chẩn đoán, dùng lại quy trình ở lesson 75 nhưng cho môi trường điều phối. Thứ tự cố định: đọc trạng thái của đối tượng, đọc sự kiện, đọc đặc tả, rồi mới đọc nhật ký ứng dụng và số đo của nút. Mười lỗi thuộc năm nhóm và mỗi nhóm có một dấu hiệu phân biệt: không kéo được ảnh do tên, thẻ hoặc quyền kho ảnh; vòng lặp khởi động lại do lỗi khi khởi động hoặc do thăm dò sống; trạng thái chờ do không đủ tài nguyên, do quy tắc chặn nút, hoặc do ổ đĩa chưa sẵn sàng; bị kết thúc vì hết bộ nhớ do giới hạn thấp hơn nhu cầu thật; và sẵn sàng nhưng hỏng do thăm dò nông. **Mỗi chẩn đoán phải dẫn ra bằng chứng cụ thể đã đọc ở bước nào**, và sửa bằng mã chứ bằng thao tác tay trên cụm. Ba lỗi trông giống nhau nhưng khác nguyên nhân được đặt cạnh nhau để rèn phân biệt.",
"Chẩn đoán mười khối lượng công việc hỏng theo đúng thứ tự và sửa bằng mã.",
"Tầng *phân tích*. Objective đo năng lực chẩn đoán có phương pháp. Kiểm bằng mười ca; đạt khi chẩn đoán đúng ít nhất tám kèm bằng chứng dẫn ra, và mọi bản sửa đi qua mã chứ thao tác tay.",
"Nhận mười khối lượng công việc hỏng thuộc năm nhóm. Với mỗi cái, chạy đúng thứ tự bốn bước và ghi bằng chứng ở bước phát hiện ra nguyên nhân. Sửa bằng cách đổi mã rồi triển khai lại. Bấm giờ từng ca. Lập bảng năm nhóm với dấu hiệu phân biệt để dùng khi trực.",
"Sửa trực tiếp trên cụm · đọc nhật ký ứng dụng trước khi đọc sự kiện · khởi động lại để xem có hết không · chẩn đoán mà không dẫn bằng chứng.",
"Chẩn đoán đúng ≥ 8/10 ca kèm bằng chứng dẫn ra, mọi bản sửa đi qua mã, và bảng năm nhóm dấu hiệu phân biệt hoàn chỉnh."),

(388,"Rebuild project - cluster and service from code and backup","DA","Lesson 387",
"Bài dự án khép module, và tiêu chí nghiệm thu của nó là một phép thử duy nhất: dựng lại được từ con số không. Trong một môi trường sạch, dựng lại toàn bộ chỉ từ ba thứ: mã hạ tầng, kho ảnh, và bản sao lưu dữ liệu. Không được dùng bất kỳ thao tác tay nào và không được chép cấu hình từ môi trường cũ. Nộp gồm: mã hạ tầng có mô đun, trạng thái từ xa và kiểm chính sách; ảnh nhiều giai đoạn ghim theo mã băm, chạy bằng người dùng không đặc quyền; bản khai báo đầy đủ có thăm dò, yêu cầu và giới hạn tài nguyên, phân quyền theo vai và chính sách mạng từ chối mặc định; quy trình triển khai có quay lui đã thử; và sổ tay chẩn đoán năm nhóm ở lesson 387. **Mọi trường trong bản khai báo phải giải thích được bằng hành vi của bộ điều khiển hoặc của môi trường chạy**; trường nào không giải thích được thì gỡ bỏ.",
"Dựng lại toàn bộ trong môi trường sạch chỉ từ mã, kho ảnh và bản sao lưu, và giải thích được mọi trường đã dùng.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một phép thử tái tạo. Kiểm bằng dựng lại từ đầu cộng bảo vệ bản khai báo; đạt khi môi trường sạch dựng lại thành công với dữ liệu đối soát khớp, và mọi trường được giải thích bằng cơ chế.",
"Dựng lại toàn bộ trong môi trường sạch, bấm giờ và ghi lại mọi chỗ phải can thiệp tay; mỗi lần can thiệp tay là một thiếu sót phải đưa vào mã rồi làm lại. Phục hồi dữ liệu và đối soát. Thực hiện một lần triển khai và một lần quay lui dưới tải. Bảo vệ bản khai báo: người chấm chỉ vào năm trường bất kỳ và hỏi cơ chế đằng sau.",
"Chép cấu hình từ môi trường cũ · giữ lại trường trong bản khai báo mà không biết nó làm gì · bỏ bước phục hồi dữ liệu · can thiệp tay rồi không đưa vào mã.",
"Môi trường sạch dựng lại thành công không can thiệp tay, dữ liệu đối soát khớp, quay lui thử thành công dưới tải, và năm trường bất kỳ được giải thích bằng cơ chế."),
]

M21 = ("Observability, Reliability and Security", 389, 404, """| | |
|---|---|
| **Objective cấp module** | Một bảng theo dõi trả lời được chuỗi ảnh hưởng người dùng tới dịch vụ tới phụ thuộc tới tài nguyên; cam kết dịch vụ dẫn tới một quyết định phát hành cụ thể |
| **Tiền đề** | M7 · M8 · M14 · M19 · M20 |
| **Exit criterion** | Cảnh báo hành động được và có sổ tay đi kèm, không bùng nổ số chuỗi nhãn; phục hồi và xoay thông tin xác thực đã thử; mô hình mối đe doạ ánh xạ chốt kiểm soát với rủi ro |
| **Kỹ năng SFIA** | `USUP` mức 5 · `SCTY` mức 4 · `ITOP` mức 4 |
| **Chế độ hỏng** | Gọi người trực vì một số đo không hành động được, để số chuỗi nhãn không giới hạn, phân tích sau sự cố quy về lỗi cá nhân, và để dữ liệu nhạy cảm lọt vào tín hiệu đo lường |""",
"""Module khép Phase 9 bằng cách gộp ba mặt vốn bị tách rời: quan sát được, tin cậy và bảo mật. Chúng gộp vì một sự cố thật luôn chạm cả ba, và ma trận sự cố hợp nhất ở cuối module thể hiện đúng điều đó.

Nguyên tắc thiết kế tín hiệu chạy suốt module: **bắt đầu từ câu hỏi và từ hành trình người dùng, không bắt đầu từ những số đo sẵn có**. Đo cái đo được rồi mới nghĩ dùng làm gì là cách tạo ra bảng theo dõi đầy biểu đồ mà không trả lời được câu nào.

Phần cam kết dịch vụ nối thẳng với M14C: ở đó là cam kết về dữ liệu, ở đây là cam kết về dịch vụ, và hai loại dùng chung một bộ máy.""")

L21 = [
(389,"Observability against monitoring - instrument from the question","LT","Module 21: M20",
"Bài mở module bằng một phép phân biệt có hệ quả thực hành. Theo dõi trả lời những câu hỏi đã biết trước: dịch vụ còn sống không, mức dùng bộ nhớ bao nhiêu. Quan sát được là khả năng trả lời những câu hỏi chưa nghĩ tới, và nó đòi tín hiệu mang đủ ngữ cảnh để cắt lát theo nhiều chiều sau này. Ba loại tín hiệu cho ba nhiệm vụ khác nhau và không thay nhau được: nhật ký giải thích một sự kiện rời rạc; số đo định lượng một tập hợp; vết nối các bước của một đường nhân quả. Quy trình thiết kế tín hiệu có thứ tự bắt buộc: bắt đầu từ hành trình người dùng hoặc từ một bất biến, ánh xạ dịch vụ cùng phụ thuộc cùng tài nguyên, rồi mới quyết định đo gì ở đâu. **Đo những gì có sẵn rồi mới nghĩ dùng làm gì là cách tạo ra bảng theo dõi không trả lời được câu nào**, và ba dấu hiệu của tình trạng đó.",
"Thiết kế bộ tín hiệu bắt đầu từ ba câu hỏi vận hành và chỉ ra loại tín hiệu nào trả lời câu nào.",
"Tầng *hiểu*. Bài mở module, đặt phương pháp. Kiểm bằng bài thiết kế ngược; đạt khi ba câu hỏi đều có tín hiệu tương ứng và mỗi tín hiệu được chọn đúng loại kèm lý do.",
"Chọn ba câu hỏi vận hành thật, chẳng hạn người dùng nào bị ảnh hưởng, chậm ở chặng nào, và nguyên nhân thuộc dịch vụ nào. Với mỗi câu, xác định tín hiệu cần và chọn loại. Rà bảng theo dõi hiện có và đếm bao nhiêu biểu đồ trả lời được một câu hỏi cụ thể; bỏ những biểu đồ không trả lời câu nào.",
"Đo mọi thứ đo được rồi vẽ hết lên bảng · dùng nhật ký để làm việc của số đo · vẽ bảng theo dõi theo thành phần hạ tầng thay vì theo hành trình người dùng · coi theo dõi là quan sát được.",
"Ba câu hỏi đều có tín hiệu tương ứng chọn đúng loại, và bảng theo dõi hiện có được rà với số biểu đồ không trả lời câu nào được đếm."),

(390,"Logs - structure, correlation, retention and redaction","TH","Lesson 389",
"Nhật ký có cấu trúc dùng lại nội dung ở lesson 20 và thêm bốn yêu cầu của môi trường phân tán. Lược đồ thống nhất cho mọi dịch vụ để truy vấn được xuyên hệ. Định danh tương quan truyền qua mọi chặng, gồm cả qua hàng đợi, để nối các dòng nhật ký của cùng một yêu cầu; **qua ranh giới hàng đợi là chỗ định danh hay bị rơi mất nhất**, vì bên tiêu thụ là một tiến trình khác và phải đọc định danh từ thông điệp. Mức nhật ký phải có kỷ luật, nếu không thì mức lỗi mất ý nghĩa. Lấy mẫu và thời hạn giữ vì nhật ký là tín hiệu đắt nhất trên mỗi đơn vị thông tin. Che dữ liệu nhạy cảm ngay tại nơi sinh ra chứ ở nơi lưu: **dữ liệu cá nhân lọt vào nhật ký là một sự cố bảo mật**, và nó khó dọn vì nhật ký đã nhân bản sang nhiều nơi. Ba thứ không bao giờ được ghi.",
"Nối được toàn bộ dòng nhật ký của một yêu cầu đi qua hàng đợi và chứng minh không dữ liệu nhạy cảm nào lọt.",
"Tầng *áp dụng*. Objective có hai tiêu chí nghiệm thu kiểm được bằng truy vấn. Kiểm bằng phép thử tương quan cộng bộ quét; đạt khi 100 yêu cầu qua hàng đợi đều nối đủ chặng, và bộ quét không tìm thấy dữ liệu nhạy cảm trong nhật ký.",
"Thống nhất lược đồ nhật ký cho ba dịch vụ. Truyền định danh tương quan qua cả lời gọi trực tiếp lẫn hàng đợi. Chạy 100 yêu cầu và truy vấn nhật ký theo định danh; đếm số yêu cầu nối đủ chặng. Cài che dữ liệu tại nơi sinh và chạy bộ quét tìm dữ liệu nhạy cảm. Đặt lấy mẫu cùng thời hạn giữ và tính chi phí.",
"Để định danh tương quan rơi mất ở ranh giới hàng đợi · che dữ liệu ở nơi lưu thay vì nơi sinh · ghi toàn bộ thân yêu cầu vào nhật ký · giữ mọi nhật ký vô thời hạn.",
"100 yêu cầu qua hàng đợi đều nối đủ chặng, bộ quét không tìm thấy dữ liệu nhạy cảm, và chi phí nhật ký được tính."),

(391,"Metrics - the three types, cardinality and the percentile trap","TH","Lesson 390",
"Ba kiểu số đo và ba cái bẫy đi kèm. Bộ đếm chỉ tăng và dùng để tính tốc độ; đồng hồ đo giá trị tức thời; biểu đồ phân bố ghi phân phối và cho phép tính phân vị. Bẫy thứ nhất là số chuỗi nhãn: mỗi tổ hợp giá trị nhãn tạo một chuỗi riêng, nên **thêm một nhãn có nhiều giá trị như định danh người dùng làm số chuỗi bùng nổ và làm sập hệ thu thập**; quy tắc là nhãn chỉ dùng cho giá trị có miền hữu hạn và nhỏ. Bẫy thứ hai là gộp phân vị: **không thể lấy trung bình của các phân vị**, vì phân vị 95 của tổng thể không bằng trung bình các phân vị 95 của từng phần; muốn gộp đúng thì phải gộp từ biểu đồ phân bố. Bẫy thứ ba là giá trị trung bình che mất đuôi phân phối. Bộ chỉ số theo yêu cầu và bộ chỉ số theo tài nguyên bị ràng buộc là hai khung chọn số đo.",
"Chứng minh bằng số hai cái bẫy về nhãn và về phân vị, rồi sửa bộ số đo cho đúng.",
"Tầng *phân tích*. Objective đòi chứng minh hai lỗi thường gặp bằng dữ liệu. Kiểm bằng hai thí nghiệm; đạt khi số chuỗi nhãn được đo trước sau và chênh lệch giữa phân vị gộp đúng với phân vị lấy trung bình được định lượng.",
"Thêm một nhãn có miền giá trị lớn và đo số chuỗi cùng mức dùng bộ nhớ của hệ thu thập; gỡ nhãn và đo lại. Tính phân vị 95 của một dịch vụ theo hai cách: lấy trung bình phân vị của từng bản sao, và gộp từ biểu đồ phân bố; so hai con số với giá trị đúng tính từ dữ liệu thô. Dựng bộ chỉ số theo yêu cầu cho một dịch vụ và theo tài nguyên cho một hàng đợi.",
"Đặt định danh người dùng làm nhãn · lấy trung bình của các phân vị · theo dõi bằng giá trị trung bình · dùng đồng hồ đo cho thứ cần tính tốc độ.",
"Số chuỗi nhãn đo được trước sau, và chênh lệch giữa phân vị gộp đúng với phân vị lấy trung bình được định lượng so với giá trị đúng."),

(392,"Traces - span, context propagation and the queue boundary","TH","Lesson 391",
"Vết trả lời câu hỏi mà nhật ký và số đo không trả lời được: thời gian của một yêu cầu tiêu ở chặng nào. Một vết gồm nhiều đoạn lồng nhau, mỗi đoạn là một đơn vị công việc có thời điểm bắt đầu và kết thúc. Ngữ cảnh truyền qua tiêu đề khi gọi trực tiếp; **qua hàng đợi thì phải nhúng vào thông điệp, và đây là chỗ vết hay bị đứt**, làm phần xử lý bất đồng bộ trở thành một vết rời không nối được với yêu cầu gốc. Lấy mẫu là bắt buộc vì lưu mọi vết quá đắt; ba chiến lược và đánh đổi, trong đó lấy mẫu theo đuôi giữ được các vết chậm hoặc lỗi nhưng cần bộ đệm. Dữ liệu đính kèm truyền theo ngữ cảnh phải hạn chế vì nó đi qua mọi chặng. Đọc một vết để tìm chặng tốn nhất là kỹ năng chính, và nó phân biệt chậm do chờ với chậm do tính.",
"Nối được vết đi qua hàng đợi và chỉ ra chặng tốn nhất của một yêu cầu chậm.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là vết liền mạch qua ranh giới bất đồng bộ. Kiểm bằng phép thử nối vết; đạt khi vết nối đủ chặng qua hàng đợi ở ít nhất 95 phần trăm mẫu, và chặng tốn nhất của ba yêu cầu chậm được chỉ đúng.",
"Gắn đo lường cho ba dịch vụ nối nhau qua một hàng đợi. Chạy tải và kiểm tỉ lệ vết nối đủ chặng. Cố ý bỏ truyền ngữ cảnh qua hàng đợi và quan sát vết đứt. Tạo ba yêu cầu chậm vì ba nguyên nhân khác nhau; đọc vết và chỉ ra chặng tốn nhất cùng phân biệt chờ với tính. Bật lấy mẫu theo đuôi và đo chi phí.",
"Không truyền ngữ cảnh qua hàng đợi · lấy mẫu đầu với tỉ lệ thấp rồi mất hết vết lỗi · nhét dữ liệu lớn vào dữ liệu đính kèm · đọc vết mà không phân biệt chờ với tính.",
"Vết nối đủ chặng qua hàng đợi ở ≥ 95% mẫu, và chặng tốn nhất của ba yêu cầu chậm được chỉ đúng kèm phân biệt chờ với tính."),

(393,"One telemetry pipeline - SDK, collector, exporter","TH","Lesson 392",
"Gom ba loại tín hiệu vào một đường thống nhất để không phụ thuộc vào một nhà cung cấp và để xử lý tín hiệu ở một chỗ. Ba thành phần: thư viện đo lường trong ứng dụng, bộ thu gom chạy riêng, và bộ xuất đẩy sang hệ lưu trữ. Bộ thu gom là nơi đặt các phép xử lý dùng chung: gộp, lấy mẫu, che dữ liệu nhạy cảm, và thêm siêu dữ liệu về môi trường; đặt chúng ở đây thay vì trong từng ứng dụng làm chính sách nhất quán và đổi được mà không triển khai lại ứng dụng. **Đường tín hiệu cũng có thể hỏng, và khi nó hỏng thì ta mù mà không biết mình mù**; nên phải có nhịp tim, phải theo dõi độ sâu hàng đợi của bộ thu gom, và cảnh báo phải hành xử thận trọng khi mất tín hiệu chứ coi im lặng là bình thường. Chi phí đo lường phải tính vào ngân sách theo lesson 368.",
"Dựng đường tín hiệu thống nhất có che dữ liệu ở bộ thu gom và phát hiện được khi chính nó hỏng.",
"Tầng *áp dụng*. Objective gồm một yêu cầu về chính hệ đo lường. Kiểm bằng phép thử mất tín hiệu; đạt khi mất tín hiệu được phát hiện trong ngưỡng thoả thuận và che dữ liệu ở bộ thu gom có hiệu lực cho cả ba dịch vụ.",
"Dựng đường tín hiệu cho ba dịch vụ với một bộ thu gom chung. Đặt che dữ liệu nhạy cảm và lấy mẫu ở bộ thu gom; xác nhận có hiệu lực cho cả ba mà không sửa ứng dụng. Dựng nhịp tim và cảnh báo mất tín hiệu. Dừng bộ thu gom và đo thời gian tới khi phát hiện. Làm đầy hàng đợi của bộ thu gom và quan sát hành vi. Tính chi phí đo lường.",
"Đặt logic che dữ liệu trong từng ứng dụng · coi im lặng là hệ đang khoẻ · không theo dõi hàng đợi của bộ thu gom · bỏ chi phí đo lường khỏi ngân sách.",
"Mất tín hiệu được phát hiện trong ngưỡng thoả thuận, che dữ liệu ở bộ thu gom có hiệu lực cho cả ba dịch vụ, và chi phí đo lường được tính."),

(394,"Dashboard from the user journey","TH","Lesson 393",
"Bảng theo dõi tốt có cấu trúc theo chuỗi suy luận chứ theo danh sách thành phần. Bốn tầng theo thứ tự đọc: ảnh hưởng người dùng, rồi dịch vụ nào gây ra, rồi phụ thuộc nào của dịch vụ đó, rồi tài nguyên nào bị ràng buộc. **Người trực đọc từ trên xuống và mỗi tầng phải thu hẹp phạm vi**, nên một bảng theo dõi chỉ có biểu đồ tài nguyên không giúp trả lời câu người dùng có bị ảnh hưởng không. Ba câu hỏi một bảng theo dõi phải trả lời trong vòng một phút: có đang có sự cố không, ai bị ảnh hưởng, và nên xem tiếp ở đâu. Phép thử của một bảng tốt là phép thử người: đưa cho một người chưa biết hệ cùng một sự cố đang diễn ra và bấm giờ xem họ mất bao lâu để thu hẹp tới đúng thành phần. Số biểu đồ không phải thước đo; biểu đồ không trả lời câu nào thì gỡ đi.",
"Dựng bảng theo dõi bốn tầng và chứng minh người chưa biết hệ thu hẹp được tới đúng thành phần trong giới hạn thời gian.",
"Tầng *đánh giá*. Objective đo bằng kết quả của người dùng bảng chứ bằng độ đầy đủ. Kiểm bằng phép thử người có tính giờ; đạt khi ít nhất hai trong ba người thu hẹp đúng thành phần trong năm phút.",
"Dựng bảng theo dõi bốn tầng cho một dịch vụ. Tiêm một sự cố. Đưa cho ba người chưa biết hệ và bấm giờ tới khi họ chỉ ra đúng thành phần gây ra. Ghi lại mọi chỗ họ vấp và mọi biểu đồ họ không dùng tới. Gỡ biểu đồ không trả lời câu nào và chạy lại với một sự cố khác.",
"Xếp bảng theo dõi theo thành phần hạ tầng · thêm biểu đồ vì có số đo · đánh giá bảng bằng cảm nhận của chính người dựng · giữ biểu đồ không ai dùng.",
"≥ 2/3 người chưa biết hệ thu hẹp đúng thành phần trong năm phút, và biểu đồ không trả lời câu nào đã được gỡ."),

(395,"SLI and SLO from raw events","TH","Lesson 394",
"Bài dùng lại bộ máy ở lesson 286 nhưng cho cam kết về dịch vụ, và nhấn vào phần định nghĩa chính xác. Chỉ số phục vụ định nghĩa bằng tỉ lệ sự kiện tốt trên tổng sự kiện hợp lệ, nên bốn thứ phải nêu tường minh: tử số tức thế nào là tốt, mẫu số tức sự kiện nào được tính, cửa sổ đo, và phần loại trừ. **Thiếu phần loại trừ thì hai người tính ra hai con số**, chẳng hạn yêu cầu bị chặn vì vượt hạn mức có tính là hỏng không. Ngưỡng tốt phải chọn từ dữ liệu về hành vi người dùng chứ từ con số tròn. Bốn khía cạnh chất lượng dịch vụ cần cam kết riêng và không thay nhau: khả dụng, độ trễ, tính đúng, và độ tươi; một dịch vụ khả dụng 100 phần trăm mà trả số sai thì cam kết khả dụng không nói gì. Mục tiêu đặt theo giá trị nghiệp vụ và chi phí đạt được, chứ theo mong muốn.",
"Định nghĩa ba chỉ số phục vụ từ dữ liệu sự kiện thô với bốn phần tường minh và ngưỡng dẫn từ dữ liệu.",
"Tầng *áp dụng*. Objective có phép kiểm chứng khách quan bằng hai người tính độc lập. Kiểm bằng phép thử hai người; đạt khi ba chỉ số cho cùng con số ở hai người và mỗi ngưỡng dẫn được từ dữ liệu hành vi.",
"Từ nhật ký sự kiện thô, định nghĩa ba chỉ số phục vụ thuộc ba khía cạnh khác nhau, mỗi cái nêu đủ bốn phần. Chọn ngưỡng tốt từ phân bố độ trễ thật và từ dữ liệu hành vi người dùng. Nhờ một học viên khác tính độc lập ba chỉ số trên cùng dữ liệu và so con số. Tạo một tình huống khả dụng cao mà tính đúng thấp.",
"Bỏ phần loại trừ · chọn ngưỡng bằng con số tròn · chỉ cam kết khả dụng rồi coi là đủ · tính chỉ số phục vụ từ số đo đã gộp thay vì từ sự kiện.",
"Ba chỉ số cho cùng con số khi hai người tính độc lập, ngưỡng dẫn từ dữ liệu hành vi, và tình huống khả dụng cao mà tính đúng thấp được tái hiện."),

(396,"Error budget, burn rate and the release decision","TH","Lesson 395",
"Ngân sách sai sót biến cam kết thành một công cụ ra quyết định thay vì một con số báo cáo. Ngân sách là phần được phép hỏng trong cửa sổ; tốc độ tiêu cho biết đang tiêu nhanh gấp bao nhiêu lần mức bền vững. Cảnh báo hai mức là thực hành chuẩn: tiêu rất nhanh trong cửa sổ ngắn thì gọi người ngay; tiêu vừa phải nhưng kéo dài trong cửa sổ dài thì mở một việc cần xử lý. **Cảnh báo theo tốc độ tiêu thay thế được phần lớn cảnh báo ngưỡng lặt vặt**, vì nó cảnh báo trên thứ người dùng chịu thay vì trên từng chỉ số thành phần. Mức giảm ồn thật phải đo trên chính hệ của mình bằng tỉ lệ cảnh báo hành động được ở lesson 287, chứ nhận theo lời. Chính sách ngân sách phải viết ra trước khi cần dùng: còn ngân sách thì được phát hành tính năng, cạn ngân sách thì dừng phát hành và chuyển sang việc về độ tin cậy; ngoại lệ cần ai duyệt. Viết chính sách trước là điều kiện để nó không bị tranh cãi ngay lúc đang căng thẳng.",
"Dựng cảnh báo hai mức theo tốc độ tiêu và nối ngân sách với một quyết định phát hành cụ thể.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là cảnh báo nổ đúng và một quyết định thật được dẫn ra. Kiểm bằng phát lại sự cố; đạt khi cảnh báo nhanh nổ ở sự cố lớn, cảnh báo chậm nổ ở suy giảm kéo dài, và không cái nào nổ trong khoảng bình thường.",
"Tính ngân sách sai sót cho ba cam kết đã đặt. Dựng cảnh báo hai mức theo tốc độ tiêu. Phát lại ba đoạn dữ liệu lịch sử: một sự cố lớn ngắn, một suy giảm nhỏ kéo dài, và một khoảng bình thường; kiểm phản ứng của từng cảnh báo. Viết chính sách ngân sách và áp vào một quyết định phát hành thật.",
"Cảnh báo trên từng ngưỡng riêng lẻ thay vì theo tốc độ tiêu · viết chính sách ngân sách sau khi đã cạn · không có ngoại lệ có người duyệt · coi ngân sách là chỉ số báo cáo.",
"Cảnh báo nhanh nổ ở sự cố lớn, cảnh báo chậm nổ ở suy giảm kéo dài, không cái nào nổ ở khoảng bình thường, và một quyết định phát hành được dẫn ra từ ngân sách."),

(397,"Failure-mode analysis, dependency map and blast radius","TH","Lesson 396",
"Phân tích trước khi hỏng thay vì sau khi hỏng. Bản đồ phụ thuộc liệt kê mọi thứ dịch vụ dựa vào, gồm cả phụ thuộc ngầm hay bị quên như phân giải tên, kho bí mật, sổ đăng ký ảnh và chính hệ đo lường. Với mỗi phụ thuộc, ba câu hỏi: nó hỏng thì dịch vụ còn chạy được phần nào, phạm vi ảnh hưởng tới đâu, và có cách suy giảm thay vì hỏng hẳn không. **Phụ thuộc cứng là phụ thuộc mà khi nó hỏng thì ta hỏng theo, và mục tiêu thiết kế là biến chúng thành phụ thuộc mềm** bằng bộ nhớ đệm, giá trị mặc định hoặc chế độ chỉ đọc. Phạm vi ảnh hưởng đo bằng tỉ lệ người dùng và tỉ lệ chức năng bị ảnh hưởng; thiết kế để thu hẹp phạm vi gồm phân vùng theo khách hàng và vách ngăn ở lesson 319. Năng lực dự phòng và dự báo tải, dùng lại lesson 110.",
"Lập bản đồ phụ thuộc có phạm vi ảnh hưởng và biến được ít nhất hai phụ thuộc cứng thành mềm.",
"Tầng *đánh giá*. Objective đòi phân tích trước rồi kiểm bằng thực nghiệm. Kiểm bằng tiêm lỗi phụ thuộc; đạt khi dự đoán khớp thực tế ở ít nhất ba phụ thuộc và hai phụ thuộc cứng được chuyển thành mềm có số đo.",
"Lập bản đồ phụ thuộc đầy đủ gồm cả phụ thuộc ngầm. Với mỗi cái, dự đoán hành vi khi nó hỏng và phạm vi ảnh hưởng. Tiêm lỗi cho năm phụ thuộc và so với dự đoán. Chọn hai phụ thuộc cứng và biến thành mềm bằng đệm hoặc chế độ suy giảm; đo lại phạm vi ảnh hưởng. Kiểm năng lực dự phòng bằng một lần chạy tải.",
"Bỏ sót phụ thuộc ngầm như phân giải tên và kho bí mật · đo phạm vi ảnh hưởng bằng số máy thay vì tỉ lệ người dùng · dự đoán mà không tiêm lỗi kiểm chứng · coi mọi phụ thuộc là cứng.",
"Dự đoán khớp thực tế ở ≥ 3/5 phụ thuộc tiêm lỗi, và hai phụ thuộc cứng chuyển thành mềm với phạm vi ảnh hưởng giảm có số đo."),

(398,"Overload control - timeout budget, jitter, circuit breaker, shedding","TH","Lesson 397",
"Bài áp các cơ chế ở lesson 319 vào một hệ thật và đo hiệu lực từng cái. Ngân sách thời gian chờ đầu cuối theo lesson 27, phân bổ xuống từng chặng, và chặng nào thấy ngân sách cạn thì bỏ sớm thay vì thử. Thử lại có ngân sách cùng nhiễu ngẫu nhiên; **thử lại không giới hạn là chất xúc tác của sập dây chuyền**. Ngắt mạch mở ra khi tỉ lệ lỗi vượt ngưỡng và đóng dần lại qua trạng thái thăm dò; ba tham số phải đặt từ số đo. Vách ngăn tách bể tài nguyên theo phụ thuộc để một phụ thuộc hỏng không ăn hết. Loại bỏ tải có chủ ý khi quá tải: từ chối sớm một phần yêu cầu theo mức ưu tiên giữ cho phần còn lại vẫn đúng cam kết; **phục vụ một phần tốt hơn sập toàn bộ**, và quyết định ưu tiên là quyết định nghiệp vụ. Áp lực ngược từ hàng đợi ngược về nguồn.",
"Áp năm cơ chế và đo đóng góp của từng cái vào việc giữ tỉ lệ phục vụ dưới quá tải.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là hệ giữ được cam kết cho phần lưu lượng ưu tiên. Kiểm bằng phép thử quá tải; đạt khi bản chưa có cơ chế sập, bản có cơ chế giữ tỉ lệ phục vụ trên ngưỡng, và đóng góp của từng cơ chế có số đo.",
"Chạy tải vượt năng lực hai lần cho một dịch vụ ba chặng. Đo điểm sập của bản chưa có cơ chế. Thêm lần lượt năm cơ chế và đo sau mỗi lần. Đặt ba tham số của ngắt mạch từ số đo chứ mặc định. Phân loại lưu lượng theo mức ưu tiên và chứng minh phần ưu tiên vẫn đúng cam kết khi đang loại bỏ tải.",
"Thử lại không có ngân sách · đặt tham số ngắt mạch theo giá trị mặc định · dùng một bể tài nguyên chung cho mọi phụ thuộc · loại bỏ tải ngẫu nhiên thay vì theo mức ưu tiên.",
"Bản chưa có cơ chế sập còn bản có cơ chế giữ tỉ lệ phục vụ trên ngưỡng, đóng góp từng cơ chế có số đo, và phần lưu lượng ưu tiên vẫn đúng cam kết."),

(399,"Disaster recovery - RPO, RTO and a restore into a clean environment","TH","Lesson 398",
"Bài nâng phần phục hồi ở lesson 367 lên mức toàn hệ thống. Ba cấp thảm hoạ và cách chuẩn bị khác nhau: mất một thành phần, mất một vùng, và lỗi logic lan ra mọi bản sao. Cấp thứ ba là cấp mà sao chép không cứu được, vì nó nhân bản cả lệnh xoá nhầm hay bản ghi hỏng; chỉ có sao lưu theo thời điểm mới cứu được, theo lesson 145. Kế hoạch phục hồi phải nêu thứ tự khôi phục theo bản đồ phụ thuộc: khôi phục sai thứ tự làm dịch vụ khởi động rồi lỗi và phải làm lại. **Diễn tập phục hồi phải vào một môi trường sạch, vì phục hồi vào môi trường cũ không phát hiện được các phụ thuộc ngầm** đang tồn tại sẵn ở đó. Ba thứ hay thiếu khi phục hồi vào môi trường sạch: thông tin xác thực, cấu hình phân giải tên, và chứng chỉ. Kết quả diễn tập là hai con số đo được, và chúng thường tệ hơn nhiều so với con số trong kế hoạch.",
"Chạy phục hồi toàn hệ vào môi trường sạch và đo được hai con số thật, kèm đối soát dữ liệu.",
"Tầng *đánh giá*. Objective có tiêu chí nghiệm thu là một lần phục hồi thật chứ một kế hoạch. Kiểm bằng diễn tập; đạt khi hệ phục vụ lại được trong môi trường sạch, dữ liệu đối soát khớp, và chênh lệch giữa số đo với mục tiêu được giải thích.",
"Lập kế hoạch phục hồi có thứ tự theo bản đồ phụ thuộc. Phục hồi toàn hệ vào một môi trường sạch; bấm giờ và ghi lại mọi thứ thiếu. Đối soát dữ liệu sau phục hồi. So hai con số đo được với mục tiêu và giải thích chênh lệch. Diễn tập một lỗi logic lan ra mọi bản sao và phục hồi theo thời điểm.",
"Coi sao chép là phương án chống thảm hoạ · phục hồi vào môi trường cũ · bỏ bước đối soát dữ liệu sau phục hồi · không thử ca lỗi logic lan ra mọi bản sao.",
"Hệ phục vụ lại được trong môi trường sạch với hai con số đo thật, dữ liệu đối soát khớp, và chênh lệch so với mục tiêu được giải thích."),

(400,"Threat modelling - asset, actor, trust boundary, abuse case","LT","Lesson 399",
"Bài mở phần bảo mật bằng một quy trình có cấu trúc thay vì một danh sách kiểm. Bốn bước: liệt kê tài sản gồm dữ liệu cùng phân loại của nó theo lesson 306; xác định tác nhân cùng năng lực của họ, gồm cả người trong tổ chức; vẽ ranh giới tin cậy là nơi dữ liệu đi từ vùng tin cậy này sang vùng khác; và viết ca lạm dụng tức cách một tác nhân đạt mục tiêu của họ. Xếp hạng theo khả năng xảy ra và mức tác động, có nêu mức không chắc chắn chứ giả vờ chính xác. Với mỗi rủi ro, chọn chốt kiểm soát thuộc một trong bốn nhóm: ngăn chặn, phát hiện, ứng phó, và phục hồi; **một mô hình chỉ có chốt ngăn chặn là một mô hình giả định mình không bao giờ bị xuyên thủng**. Phòng thủ theo chiều sâu. Đầu ra là một bảng ánh xạ rủi ro với chốt kiểm soát, và nó là tài liệu sống được rà lại khi kiến trúc đổi.",
"Lập mô hình mối đe doạ bốn bước cho một hệ thật và ánh xạ mỗi rủi ro với chốt kiểm soát đủ bốn nhóm.",
"Tầng *hiểu*. Bài lý thuyết đặt khung cho hai bài thực hành. Kiểm bằng bảng ánh xạ; đạt khi mọi ranh giới tin cậy được vẽ, ít nhất sáu ca lạm dụng được viết, và mỗi rủi ro lớn có chốt ở ít nhất hai trong bốn nhóm.",
"Với hệ đã dựng ở M19 và M20, chạy bốn bước. Vẽ sơ đồ luồng dữ liệu có ranh giới tin cậy. Viết ít nhất sáu ca lạm dụng, trong đó có ít nhất một từ người trong tổ chức. Xếp hạng theo khả năng và tác động kèm mức không chắc chắn. Ánh xạ rủi ro với chốt kiểm soát theo bốn nhóm và chỉ ra chỗ chỉ có chốt ngăn chặn.",
"Dùng danh sách kiểm thay cho mô hình mối đe doạ · bỏ qua tác nhân trong tổ chức · chỉ đặt chốt ngăn chặn · xếp hạng rủi ro bằng con số trông chính xác mà không có căn cứ.",
"Mọi ranh giới tin cậy được vẽ, ≥ 6 ca lạm dụng gồm ít nhất một từ người trong tổ chức, và mỗi rủi ro lớn có chốt ở ≥ 2 nhóm."),

(401,"Identity, secrets and key lifecycle in practice","TH","Lesson 400",
"Bài thực hành phần bảo mật thứ nhất, dựng trên lesson 362 và lesson 369. Phân biệt xác thực với phân quyền và ba lỗi hay gặp ở ranh giới đó, gồm kiểm được đăng nhập mà quên kiểm quyền trên đúng tài nguyên. Giới hạn của mã thông báo dạng tự chứa: nó không thu hồi được trước khi hết hạn, nên thời hạn sống phải ngắn và phải có cơ chế thu hồi riêng cho ca khẩn. Vòng đời khoá và thông tin xác thực gồm tạo, phân phát, xoay, thu hồi, và huỷ; **xoay phải thử được khi dịch vụ đang chạy chứ nằm trong tài liệu**. Đường thoát khẩn cấp cần cho ca mất quyền truy cập, và nó phải được ghi lại cùng cảnh báo khi dùng. Cách ly giữa các khách hàng khi hệ phục vụ nhiều bên: kiểm quyền sở hữu ở mọi lối vào chứ chỉ ở giao diện chính, vì đường phụ là chỗ hay quên.",
"Thực hiện xoay và thu hồi khi dịch vụ đang chạy, và chặn được ba lỗi phân quyền bằng phép thử phủ định.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng phép thử phủ định và một thao tác vận hành thật. Kiểm bằng sáu phép thử phủ định cộng một lần xoay; đạt khi cả sáu bị chặn đúng và xoay không gây gián đoạn.",
"Viết sáu phép thử phủ định gồm truy cập tài nguyên của khách hàng khác qua cả giao diện chính lẫn một đường phụ. Chạy và xác nhận bị chặn. Thực hiện xoay thông tin xác thực khi dịch vụ đang chạy và đo gián đoạn. Thu hồi một mã thông báo trước hạn và chứng minh nó không dùng được nữa. Dùng đường thoát khẩn cấp và xác nhận có cảnh báo cùng bản ghi.",
"Kiểm đăng nhập mà quên kiểm quyền sở hữu tài nguyên · đặt thời hạn mã thông báo dài vì tiện · chưa từng thử xoay · để đường thoát khẩn cấp không sinh cảnh báo.",
"Sáu phép thử phủ định bị chặn đúng gồm cả đường phụ, xoay không gây gián đoạn, và mã thông báo thu hồi trước hạn không dùng được."),

(402,"Supply chain and the secure delivery pipeline","TH","Lesson 401",
"Bài thực hành bảo mật thứ hai, mở rộng lesson 377 ra toàn bộ đường giao hàng. Bốn chốt trong quy trình tích hợp và triển khai: khoá phiên bản phụ thuộc và quét lỗ hổng có cửa chặn; sinh bản kê thành phần cho mọi hiện vật phát hành; quét bí mật trên mã và trên nhật ký quy trình; và kiểm nguồn gốc hiện vật ở mức nhận biết. Bản thân quy trình tự động là một mục tiêu tấn công giá trị cao vì nó có quyền triển khai: **danh tính của quy trình phải có quyền tối thiểu và phải giới hạn phạm vi theo nhánh cùng môi trường**, nếu không thì một yêu cầu hợp nhất từ nguồn không tin cậy có thể chạy mã với quyền triển khai sản xuất. Ba lỗ hổng điển hình của quy trình tự động. Ứng phó khi có lỗ hổng mới công bố: biết mình đang chạy những gì ở đâu, và đó chính là lý do có bản kê thành phần.",
"Dựng bốn chốt trong quy trình giao hàng và chứng minh quy trình không thể tự nâng quyền.",
"Tầng *áp dụng*. Objective gồm cả bảo vệ chính quy trình tự động. Kiểm bằng bốn vi phạm tiêm cộng một phép thử nâng quyền; đạt khi bốn vi phạm bị chặn và yêu cầu hợp nhất từ nguồn không tin cậy không chạm được vào quyền triển khai.",
"Dựng bốn chốt trong quy trình. Tiêm bốn vi phạm và xác nhận bị chặn ở đúng chốt. Giới hạn danh tính của quy trình theo nhánh và môi trường; mở một yêu cầu hợp nhất từ một nhánh không tin cậy và chứng minh nó không lấy được quyền triển khai. Với một lỗ hổng giả định mới công bố, dùng bản kê thành phần trả lời trong bao lâu mình đang chạy nó ở đâu.",
"Cho quy trình tự động quyền triển khai rộng · chạy mã của yêu cầu hợp nhất từ nguồn không tin cậy với bí mật · không quét bí mật trong nhật ký quy trình · không có bản kê thành phần nên không biết mình chạy gì.",
"Bốn vi phạm bị chặn ở đúng chốt, yêu cầu hợp nhất từ nguồn không tin cậy không chạm được quyền triển khai, và câu hỏi về lỗ hổng mới trả lời được từ bản kê thành phần."),

(403,"Two game days - overload cascade and credential incident","DA","Lesson 402",
"Bài dự án khép module, chạy hai buổi diễn tập trên hệ đã dựng, với ma trận sự cố hợp nhất làm khung: mỗi sự cố xem qua ba mặt là quan sát được, phản ứng về độ tin cậy, và khía cạnh bảo mật. Buổi thứ nhất là sập dây chuyền do quá tải: một phụ thuộc chậm lại, quan sát chuỗi lan truyền, áp các cơ chế ở lesson 398, và giữ cam kết cho phần lưu lượng ưu tiên. Buổi thứ hai là sự cố thông tin xác thực bị lộ: xác định phạm vi bằng nhật ký kiểm toán, xoay và thu hồi, cô lập, đánh giá dữ liệu nào có thể đã bị lấy, và phục hồi. Cả hai buổi chạy theo vòng đời sự cố ở lesson 288 với vai trò rõ, dòng thời gian, và truyền thông cho bên liên quan. **Phân tích sau sự cố không quy lỗi cá nhân**; mỗi hành động có chủ, có cách kiểm chứng hiệu lực, và có hạn.",
"Chạy hai buổi diễn tập đủ vòng đời và nộp phân tích sau sự cố có hành động kiểm chứng được.",
"Tầng *sáng tạo*. Bài tổng hợp ba mặt của module vào hai sự cố thật. Kiểm bằng hai buổi diễn tập; đạt khi cả hai có dòng thời gian đầy đủ, phạm vi ảnh hưởng xác định bằng bằng chứng, và mọi hành động sau sự cố có chủ cùng cách kiểm chứng cùng hạn.",
"Chuẩn bị vai trò và kênh truyền thông. Chạy buổi một: tiêm phụ thuộc chậm, ghi thời gian phát hiện, mức suy giảm và thời gian phục hồi. Chạy buổi hai: lộ một thông tin xác thực trong môi trường lab, xác định phạm vi bằng nhật ký kiểm toán, xoay và cô lập. Viết hai bản phân tích sau sự cố theo bốn nhóm hành động là phát hiện, ngăn chặn, kiềm chế và phục hồi.",
"Chẩn đoán trước khi giảm thiểu khi người dùng đang chịu ảnh hưởng · quy lỗi cá nhân trong phân tích sau sự cố · hành động không có chủ và không có hạn · xoá bằng chứng khi dọn dẹp sự cố.",
"Hai buổi có dòng thời gian đầy đủ và phạm vi ảnh hưởng xác định bằng bằng chứng, và mọi hành động sau sự cố có chủ, cách kiểm chứng và hạn."),

(404,"Gate 9 - redeploy from code and recover from an injected incident","KT","Lesson 403",
"Cổng của Phase 9. Bài kiểm ba module: trừu tượng đám mây ở M19, vùng chứa cùng hạ tầng khai báo cùng điều phối ở M20, và quan sát được cùng tin cậy cùng bảo mật ở M21. Không có nội dung mới.",
"Dựng lại toàn hệ từ mã trong môi trường sạch, phục hồi sau một sự cố được tiêm, và bảo vệ các lựa chọn về danh tính, chi phí và độ tin cậy.",
"Tầng *đánh giá*. Cổng đo năng lực vận hành đầu cuối, nên hình thức là thực hành tại chỗ cộng bảo vệ.",
"Buổi 180 phút: 135 phút làm bài độc lập, 45 phút chữa bài. Bài chấm sáu phần: A (20đ) dựng lại một lát cắt hệ trong môi trường sạch chỉ từ mã, kho ảnh và bản sao lưu, không thao tác tay · B (15đ) chẩn đoán ba khối lượng công việc hỏng theo đúng thứ tự bằng chứng · C (20đ) một sự cố được tiêm; chạy vòng đời sự cố, xác định phạm vi ảnh hưởng bằng bằng chứng và phục hồi · D (15đ) định nghĩa một chỉ số phục vụ từ sự kiện thô đủ bốn phần và dẫn ra một quyết định phát hành từ ngân sách sai sót · E (15đ) trình mô hình mối đe doạ và chỉ ra chốt kiểm soát cho ba rủi ro lớn nhất, đủ ít nhất hai nhóm · F (15đ) trình bảng chi phí trên mỗi đơn vị và một phương án cho cú sốc chi phí gấp mười.",
"Sửa trực tiếp trên cụm thay vì qua mã · gọi người trực vì một số đo không hành động được · phục hồi mà không đối soát dữ liệu · trình mô hình mối đe doạ chỉ có chốt ngăn chặn.",
"Đạt ≥ 70/100, phần A và C đều ≥ 60%. Dùng thao tác tay để hoàn thành phần A thì phần đó bằng không; phục hồi ở phần C mà không đối soát dữ liệu thì phần đó bằng không."),
]
