# -*- coding: utf-8 -*-
"""ADE Phase 8: M15 distributed systems + M16 Kafka + M17 CDC + M18 Spark/Flink."""

M15 = ("Distributed Systems Fundamentals", 309, 320, """| | |
|---|---|
| **Objective cấp module** | Với mỗi bảo đảm được tuyên bố, nêu được giả định hệ thống nó dựa vào và chế độ hỏng nó không chịu được |
| **Tiền đề** | M5 · M6 · M9 · M10 · M14 |
| **Exit criterion** | Giải thích bầu chọn người dẫn, sao chép nhật ký, chốt theo số đông và cách chặn chia rẽ; mọi thiết kế có thử lại, luỹ đẳng, thẻ chặn và hết giờ, không dùng cụm từ đúng một lần theo nghĩa mơ hồ |
| **Kỹ năng SFIA** | `SYSP` mức 5 · `ARCH` mức 4 |
| **Chế độ hỏng** | Coi hết giờ là bằng chứng bên kia đã hỏng, và nói số đông thì suy ra tuần tự hoá được |""",
"""Module đặt nền cho ba module còn lại của phase, và nó có một câu bản lề chi phối mọi bài: **hết giờ không phải một lỗi, nó là một trạng thái không biết**. Bên kia có thể đã làm xong, có thể chưa làm, có thể đang làm; thiết kế phải đúng ở cả ba khả năng.

Hai nhầm lẫn bị bác bỏ ngay và được kiểm lại ở cổng: số đông không tự suy ra tuần tự hoá được, và đồng hồ treo tường không dùng để xác lập thứ tự.

Đồng thuận học sâu ở một thuật toán, thuật toán còn lại chỉ tới mức khái niệm.""")

L15 = [
(309,"The formal model - safety, liveness and what the network may do","LT","Module 15: M14",
"Bài mở module bằng một mô hình đủ chặt để lập luận, vì bàn về hệ phân tán bằng trực giác dẫn tới kết luận sai. Mô hình gồm nút, tiến trình, thông điệp và trạng thái; lịch sử thao tác gồm lời gọi và phản hồi, và khoảng giữa hai mốc đó là chỗ mọi sự không chắc chắn nằm. Hai loại tính chất phải tách: an toàn nghĩa là việc xấu không bao giờ xảy ra, sống động nghĩa là việc tốt cuối cùng sẽ xảy ra; **hy sinh an toàn để đổi lấy sống động là một quyết định, không phải một tối ưu hoá**, và nó phải được nói ra. Giả định về mạng và tiến trình: đồng bộ, bán đồng bộ, hay bất đồng bộ hoàn toàn; trong mô hình bất đồng bộ hoàn toàn có những việc không làm được, và trực giác về giới hạn đó giải thích vì sao mọi hệ thật đều thêm giả định về thời gian. Bảo đảm phải phát biểu theo thứ khách hàng quan sát được. Tách nhất quán của hệ sao chép khỏi mức cô lập của giao dịch ở lesson 142.",
"Phát biểu một bảo đảm theo thứ khách hàng quan sát được và phân loại năm mệnh đề vào an toàn hay sống động.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng cho toàn phase. Kiểm bằng bài phân loại cộng bài phát biểu lại; đạt khi phân đúng ít nhất bốn trong năm và bảo đảm được phát biểu bằng quan sát của khách hàng chứ bằng cơ chế nội bộ.",
"Cho năm mệnh đề về một hệ lưu trữ; phân loại an toàn hay sống động và nêu giả định mỗi cái dựa vào. Lấy ba tuyên bố kiểu tiếp thị về một hệ thật và phát biểu lại bằng thứ khách hàng quan sát được. Chỉ ra chỗ nào tuyên bố gốc trộn nhất quán của hệ với mức cô lập giao dịch.",
"Bàn về hệ phân tán bằng trực giác về trường hợp thuận lợi · phát biểu bảo đảm bằng cơ chế nội bộ · trộn nhất quán với mức cô lập · bỏ qua việc phải nêu giả định về mạng.",
"Phân đúng ≥ 4/5 mệnh đề kèm giả định, và ba tuyên bố được phát biểu lại theo quan sát của khách hàng."),

(310,"Failure modes and why a timeout is not a failure","TH","Lesson 309",
"Bài chốt câu bản lề của module bằng thực nghiệm. Các chế độ hỏng phải phân biệt: dừng hẳn, dừng rồi khởi động lại, bỏ sót thông điệp, phân vùng mạng, và trì hoãn cùng nhân bản cùng đảo thứ tự; hành vi tuỳ tiện chỉ cần biết là có. Từ đó suy ra điều quan trọng nhất: khi một lời gọi hết giờ, ta không biết bên kia đã thực hiện hay chưa, **nên mọi thao tác có thể bị gọi lại phải luỹ đẳng** theo lesson 105. Phản hồi chậm tới sau khi đã hết giờ là ca cụ thể: bên gọi đã coi như thất bại và đã thử lại, nên tác dụng phụ xảy ra hai lần. Phân vùng mạng khác nút chết ở một điểm quyết định: nút bên kia vẫn sống và vẫn đang phục vụ, nên có hai bên cùng tin mình đúng. Bộ phát hiện hỏng chỉ đoán, và mọi bộ phát hiện đều có thể đoán sai theo cả hai chiều.",
"Tái hiện năm chế độ hỏng trên một dịch vụ nhỏ và chứng minh hành vi đúng ở cả ba khả năng sau khi hết giờ.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là trạng thái đúng bất kể kết cục thật của lời gọi. Kiểm bằng phép thử tiêm; đạt khi trạng thái cuối đúng ở cả ba khả năng và không tác dụng phụ nào xảy ra hai lần.",
"Dựng một dịch vụ có tác dụng phụ ghi được. Tiêm năm chế độ hỏng bằng lớp mạng giả lập: chậm, mất gói, nhân đôi, đảo thứ tự, và phân vùng. Với ca hết giờ, tạo cả ba kết cục thật và chứng minh trạng thái cuối đúng ở cả ba. Đo số lần tác dụng phụ lặp trước và sau khi thêm khoá chống trùng.",
"Coi hết giờ là bên kia đã hỏng · thử lại thao tác không luỹ đẳng · giả định mất gói và chậm là một · tin bộ phát hiện hỏng nói đúng.",
"Trạng thái cuối đúng ở cả ba kết cục sau hết giờ, và không tác dụng phụ nào xảy ra hai lần qua 1.000 lượt tiêm."),

(311,"Time and order - wall clock, monotonic clock and logical clocks","TH","Lesson 310",
"Đồng hồ là công cụ đo thời gian, không phải công cụ xác lập thứ tự, và nhầm hai việc này gây mất dữ liệu im lặng. Đồng hồ treo tường có thể nhảy lùi khi đồng bộ, nên hai sự kiện có dấu thời gian nhỏ hơn chưa chắc xảy ra trước. Đồng hồ đơn điệu chỉ đo khoảng, dùng được cho hết giờ nhưng không so được giữa hai máy. Đồng hồ logic gán số đếm tăng theo quan hệ xảy ra trước; đồng hồ véctơ giữ một số đếm cho mỗi nút nên phân biệt được hai sự kiện đồng thời với hai sự kiện có quan hệ nhân quả, điều đồng hồ logic đơn không làm được. **Chiến lược bản ghi có dấu thời gian lớn nhất thắng làm mất cập nhật khi đồng hồ lệch**, và đây là ca phải tái hiện bằng số. Chính sách giải quyết xung đột phải chọn tường minh chứ để mặc định, và mọi chính sách đều mất thông tin theo một cách nào đó.",
"Chứng minh bằng thực nghiệm rằng chiến lược theo dấu thời gian làm mất cập nhật, và thay bằng đồng hồ logic.",
"Tầng *phân tích*. Objective đòi nhận ra một lỗi không báo lỗi và sửa bằng cơ chế đúng. Kiểm bằng thí nghiệm lệch đồng hồ; đạt khi số cập nhật bị mất được định lượng và bản dùng đồng hồ véctơ phát hiện đúng mọi cặp sự kiện đồng thời.",
"Dựng kho khoá giá trị hai bản sao. Đặt lệch đồng hồ giữa hai nút. Ghi song song và đếm số cập nhật bị mất với chiến lược dấu thời gian lớn nhất thắng. Cài đồng hồ logic rồi đồng hồ véctơ; chứng minh đồng hồ véctơ phân biệt được đồng thời với nhân quả. Chọn một chính sách giải quyết xung đột tường minh và nêu nó mất thông tin gì.",
"Dùng đồng hồ treo tường để xác lập thứ tự · dùng đồng hồ đơn điệu để so giữa hai máy · để chính sách xung đột theo mặc định · nghĩ đồng hồ logic đơn phát hiện được đồng thời.",
"Số cập nhật bị mất được định lượng, đồng hồ véctơ phát hiện đúng mọi cặp đồng thời, và chính sách xung đột nêu rõ thông tin bị mất."),

(312,"Replication - single leader, multi leader, leaderless","LT","Lesson 311",
"Ba kiểu sao chép cho ba mô hình xung đột khác nhau, và chọn kiểu là chọn loại vấn đề mình sẵn sàng xử lý. Một người dẫn: mọi phép ghi qua một nút nên không có xung đột ghi, đổi lại người dẫn là điểm nghẽn và là điểm hỏng; sao chép đồng bộ không mất dữ liệu khi chuyển đổi dự phòng nhưng chậm, sao chép bất đồng bộ nhanh nhưng **mất phần nhật ký chưa kịp truyền khi người dẫn chết**, và lượng mất đó bằng đúng độ trễ sao chép ở lesson 143. Nhiều người dẫn: ghi được ở nhiều nơi nên chịu được phân vùng tốt hơn, đổi lại phải giải quyết xung đột và phải chọn cách hội tụ. Không người dẫn: ghi vào nhiều bản sao và đọc từ nhiều bản sao, dùng số đông để bù; sửa khi đọc và chống lệch nền chỉ cần biết là có. Vị trí nhật ký, độ trễ và hành vi khi chuyển đổi dự phòng phải trả lời được cho cả ba kiểu.",
"Chọn kiểu sao chép cho ba bối cảnh và định lượng lượng dữ liệu có thể mất khi chuyển đổi dự phòng.",
"Tầng *đánh giá*. Objective đòi nối lựa chọn với một con số về rủi ro mất dữ liệu. Kiểm bằng ba bối cảnh cộng phép đo; đạt khi mỗi lựa chọn kèm lượng mất tối đa tính được từ độ trễ đo được.",
"Dựng bản sao một người dẫn ở cả chế độ đồng bộ và bất đồng bộ. Đo độ trễ sao chép dưới tải. Giết người dẫn và đếm số phép ghi đã báo thành công nhưng mất. Cho ba bối cảnh khác nhau về yêu cầu mất dữ liệu và độ trễ; chọn kiểu sao chép và tính lượng mất tối đa cho từng cái.",
"Dùng sao chép bất đồng bộ rồi tuyên bố không mất dữ liệu · chọn nhiều người dẫn mà chưa có chính sách xung đột · bỏ qua độ trễ sao chép khi tính rủi ro · coi bản sao đọc là bản sao lưu.",
"Ba bối cảnh có lựa chọn kèm lượng mất tối đa tính từ độ trễ đo được, và số phép ghi mất khi giết người dẫn được đếm thật."),

(313,"Partitioning, consistent hashing and rebalancing","TH","Lesson 312",
"Chia dữ liệu ra nhiều nút để vượt giới hạn một máy, và ba quyết định đi kèm. Chia theo khoảng giá trị cho phép quét theo khoảng hiệu quả nhưng dễ tạo phân vùng nóng khi khoá phân bố lệch. Chia theo băm rải đều hơn nhưng mất khả năng quét theo khoảng. Băm nhất quán giảm lượng dữ liệu phải di chuyển khi thêm hoặc bớt nút, và nút ảo làm phân bố đều hơn. **Phân vùng nóng là chế độ hỏng chính**: một khoá chiếm phần lớn lưu lượng thì thêm nút không giúp gì, vì mọi yêu cầu của khoá đó vẫn về một nơi; ba cách xử lý và đánh đổi từng cách. Tái cân bằng là thao tác nặng và phải có giới hạn tốc độ, nếu không nó làm sập hệ đang phục vụ. Nối với phân vùng trong một cơ sở dữ liệu ở lesson 144: ở đây phân vùng nằm giữa các máy nên thêm chi phí mạng và chi phí di chuyển.",
"Đo phân bố tải qua ba cách chia và xử lý được một phân vùng nóng có bằng chứng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là độ lệch tải giảm có số đo. Kiểm bằng phép đo phân bố; đạt khi ba cách chia có số đo độ lệch, lượng dữ liệu di chuyển khi thêm nút được đo, và phân vùng nóng giảm lệch sau khi xử lý.",
"Cài ba cách chia trên cùng tập khoá thật có phân bố lệch. Đo độ lệch tải giữa các phân vùng. Thêm một nút và đo lượng dữ liệu phải di chuyển ở từng cách. Tạo một khoá nóng chiếm phần lớn lưu lượng, thử ba cách xử lý và đo lại. Chạy tái cân bằng có giới hạn tốc độ trong lúc hệ đang phục vụ và đo ảnh hưởng.",
"Chia theo băm rồi vẫn cần quét theo khoảng · thêm nút để chữa phân vùng nóng · tái cân bằng không giới hạn tốc độ · đo phân bố bằng khoá sinh ngẫu nhiên đều thay vì khoá thật.",
"Ba cách chia có số đo độ lệch và lượng dữ liệu di chuyển, và phân vùng nóng giảm độ lệch sau khi xử lý."),

(314,"Consistency models named by what the client observes","LT","Lesson 313",
"Năm mô hình nhất quán, đặt tên theo thứ khách hàng quan sát được chứ theo cơ chế bên trong. Tuần tự hoá được: mọi thao tác trông như xảy ra tức thời tại một thời điểm giữa lời gọi và phản hồi, đây là mô hình mạnh nhất và đắt nhất. Tuần tự: mọi nút thấy cùng một thứ tự nhưng thứ tự đó không nhất thiết khớp thời gian thật. Nhân quả: các thao tác có quan hệ nhân quả được thấy đúng thứ tự, thao tác đồng thời thì không ràng buộc. Đọc thấy phép ghi của chính mình: bảo đảm yếu nhưng là thứ người dùng thật hay kỳ vọng nhất. Cuối cùng nhất quán: chỉ hứa hội tụ khi ngừng ghi, nên **nó phải đi kèm một hợp đồng về mức cũ tối đa**, nếu không nó là một lời hứa rỗng. Định lý đánh đổi chỉ áp dụng khi có phân vùng; khi không có phân vùng thì đánh đổi thật là giữa độ trễ với nhất quán, và đó mới là trường hợp thường gặp hằng ngày.",
"Xếp năm mô hình theo độ mạnh và chỉ ra bảo đảm nào một hệ cho trước thật sự cung cấp.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho hai bài về số đông và đồng thuận. Kiểm bằng bài phân tích bốn lịch sử thao tác; đạt khi xác định đúng mô hình bị vi phạm ở ít nhất ba và nêu được đánh đổi khi không có phân vùng.",
"Cho bốn lịch sử thao tác của một thanh ghi; với mỗi cái, xác định mô hình nào bị vi phạm và giải thích bằng lời gọi cùng phản hồi cụ thể. Lấy tài liệu của hai hệ thật và phát biểu lại bảo đảm của chúng theo năm mô hình. Với một hệ hứa cuối cùng nhất quán, tìm hợp đồng về mức cũ tối đa; nếu không có thì ghi rõ là không có.",
"Dùng định lý đánh đổi để biện minh cho mọi quyết định · nói cuối cùng nhất quán mà không kèm mức cũ tối đa · nhầm tuần tự với tuần tự hoá được · đặt tên mô hình theo cơ chế bên trong.",
"Xác định đúng mô hình bị vi phạm ở ≥ 3/4 lịch sử, và hai hệ thật được phát biểu lại bảo đảm theo năm mô hình."),

(315,"Quorum reasoning, and why a quorum is not linearizability","TH","Lesson 314",
"Số đông là một kỹ thuật giao nhau giữa tập ghi và tập đọc, và hiểu đúng giới hạn của nó là mục tiêu chính của bài. Với tổng số bản sao, số bản sao phải ghi, và số bản sao phải đọc, điều kiện giao nhau bảo đảm phép đọc chạm ít nhất một bản sao có phiên bản mới nhất. Nhưng chạm được không bằng nhận ra: **phép đọc chỉ trả đúng nếu có cách so phiên bản và có cơ chế sửa**, nên số đông không tự suy ra tuần tự hoá được. Ba ca phá vỡ trực giác về số đông: phép ghi hỏng giữa chừng nên một số bản sao có giá trị mới còn số khác thì không, mà không có ai quay lui; số đông lỏng cùng trao tay gợi ý làm tập giao nhau không còn bảo đảm; và hai phép đọc liên tiếp có thể thấy giá trị mới rồi lại thấy giá trị cũ. Sửa khi đọc và chống lệch nền ở mức khái niệm.",
"Tái hiện ca số đông giao nhau mà phép đọc vẫn trả giá trị cũ, và giải thích cần thêm gì.",
"Tầng *phân tích*. Objective nhắm vào một kết luận sai rất phổ biến. Kiểm bằng ba ca tái hiện; đạt khi cả ba được tái hiện bằng dữ liệu và nêu đúng cơ chế còn thiếu cho từng ca.",
"Dựng kho khoá giá trị không người dẫn với tham số số đông cấu hình được. Tái hiện ba ca: phép ghi hỏng giữa chừng, hai phép đọc liên tiếp thấy mới rồi cũ, và số đông lỏng làm mất bảo đảm giao nhau. Với mỗi ca, nêu cơ chế còn thiếu. Bật sửa khi đọc và đo nó giảm ca nào, không giảm ca nào.",
"Kết luận số đông suy ra tuần tự hoá được · bật số đông lỏng mà không nói rõ mất bảo đảm gì · không có cách so phiên bản giữa các bản sao · tin sửa khi đọc chữa được mọi ca.",
"Ba ca được tái hiện bằng dữ liệu, mỗi ca nêu đúng cơ chế còn thiếu, và hiệu lực của sửa khi đọc được đo theo từng ca."),

(316,"Consensus - the replicated log, term, election and commit","TH","Lesson 315",
"Đồng thuận giải bài toán mà số đông không giải được: làm cho nhiều nút đồng ý về một chuỗi thao tác theo đúng một thứ tự. Học sâu một thuật toán, thuật toán còn lại chỉ tới mức khái niệm. Cấu trúc: một nhật ký được sao chép, mỗi mục có chỉ số và nhiệm kỳ; một người dẫn được bầu cho mỗi nhiệm kỳ; mục được chốt khi đã sao chép tới số đông; nút theo sau áp dụng theo đúng thứ tự đã chốt. Ba tính chất an toàn phải phát biểu được và phải kiểm được bằng thí nghiệm. Nhiệm kỳ là cơ chế chặn chia rẽ: một người dẫn cũ quay lại với nhiệm kỳ nhỏ hơn sẽ bị từ chối, nên **chia rẽ được chặn bằng nhiệm kỳ chứ bằng việc phát hiện nhanh**. Thay đổi thành viên cụm và vì sao nó khó. Khác biệt với chốt hai pha ở lesson 318: đồng thuận không chặn khi một nút chết vì số đông vẫn tiến được.",
"Cài phần bầu chọn và sao chép nhật ký, rồi giữ được ba tính chất an toàn qua các lần giết nút.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là bất biến an toàn giữ được dưới lỗi ngẫu nhiên. Kiểm bằng phép thử hỗn loạn; đạt khi ba tính chất an toàn không bị vi phạm lần nào qua 200 chu kỳ giết và khôi phục nút.",
"Cài bầu chọn người dẫn và sao chép nhật ký cho cụm năm nút. Chạy 200 chu kỳ giết ngẫu nhiên một hoặc hai nút rồi cho khôi phục, kèm phân vùng mạng ngắn. Sau mỗi chu kỳ, kiểm ba tính chất an toàn. Tái hiện ca người dẫn cũ quay lại và chứng minh nó bị từ chối bằng nhiệm kỳ. Vẽ trình tự một lần chốt đi qua một lần người dẫn chết.",
"Bầu người dẫn mà không so nhật ký nên mất mục đã chốt · dùng thời gian phát hiện nhanh thay cho nhiệm kỳ · chỉ kiểm ở trường hợp thuận lợi · nhầm đã sao chép với đã chốt.",
"Ba tính chất an toàn không bị vi phạm qua 200 chu kỳ, và ca người dẫn cũ quay lại bị từ chối bằng nhiệm kỳ."),

(317,"Leases, fencing tokens and the returning old leader","TH","Lesson 316",
"Khoá phân tán là chỗ trực giác sai nhiều nhất, nên bài này tái hiện ca hỏng kinh điển. Hợp đồng thuê là một khoá có hạn, và nó dựa vào đồng hồ; nhưng tiến trình giữ hợp đồng thuê có thể bị tạm dừng lâu hơn hạn, chẳng hạn vì bộ dọn rác hoặc vì máy bị treo, nên nó tỉnh dậy và vẫn tưởng mình đang giữ khoá trong khi khoá đã cấp cho người khác. Hậu quả: hai tiến trình cùng ghi và dữ liệu hỏng. **Hợp đồng thuê một mình không đủ, phải có thẻ chặn**: mỗi lần cấp khoá kèm một số tăng dần, và tài nguyên ở đích từ chối mọi yêu cầu mang số nhỏ hơn số lớn nhất đã thấy. Điểm quan trọng là thẻ chặn phải được cưỡng chế ở phía tài nguyên chứ ở phía khách, vì khách đang là bên nhầm lẫn. Khoá chống trùng cùng bộ nhớ kết quả có thời hạn giữ. Thử lại khi không biết kết cục theo lesson 310.",
"Tái hiện ca hai tiến trình cùng tưởng mình giữ khoá và chặn nó bằng thẻ chặn cưỡng chế ở đích.",
"Tầng *áp dụng*. Objective có một ca hỏng cụ thể phải tái hiện được trước khi sửa. Kiểm bằng phép thử tạm dừng tiến trình; đạt khi ca hỏng được tái hiện kèm bằng chứng dữ liệu sai, và bản có thẻ chặn từ chối đúng mọi yêu cầu cũ.",
"Dựng dịch vụ cấp hợp đồng thuê và một tài nguyên dùng chung. Tạm dừng tiến trình giữ khoá lâu hơn hạn thuê rồi cho chạy tiếp; ghi lại dữ liệu hỏng. Thêm thẻ chặn tăng dần và cưỡng chế ở phía tài nguyên; chạy lại và chứng minh yêu cầu cũ bị từ chối. Thử cưỡng chế ở phía khách và chỉ ra vì sao không đủ.",
"Dùng hợp đồng thuê mà không có thẻ chặn · cưỡng chế thẻ chặn ở phía khách · đặt hạn thuê ngắn hơn thời gian tạm dừng có thể xảy ra · giả định tiến trình không bao giờ bị tạm dừng lâu.",
"Ca hai tiến trình cùng ghi được tái hiện kèm bằng chứng dữ liệu sai, và bản có thẻ chặn từ chối đúng 100% yêu cầu mang số cũ."),

(318,"Distributed transactions - two-phase commit against saga and outbox","TH","Lesson 317",
"Ba cách giữ tính nhất quán qua nhiều hệ, với ba mô hình hỏng khác nhau. Chốt hai pha: điều phối viên hỏi mọi bên sẵn sàng chưa rồi mới ra lệnh chốt; đúng về mặt nguyên tử nhưng **chặn khi điều phối viên chết sau pha chuẩn bị**, vì các bên đã khoá tài nguyên và không ai dám tự quyết. Chuỗi bù trừ: chia thành nhiều bước nhỏ, mỗi bước có một thao tác bù nghĩa; nó không nguyên tử nên có trạng thái trung gian nhìn thấy được, và phải chấp nhận điều đó tường minh. Hộp thư đi theo lesson 109: ghi dữ liệu và ghi ý định gửi trong cùng một giao dịch cục bộ, rồi một tiến trình riêng đọc hộp thư và gửi đi; nó biến bài toán hai hệ thành bài toán một giao dịch cộng một lần gửi có thể lặp. Kết luận thực dụng dùng lại ở M16 và M17: **giao nhận ít nhất một lần cộng tác dụng phụ luỹ đẳng thực tế hơn theo đuổi nguyên tử xuyên hệ**.",
"So ba cách trên cùng bài toán và lập ma trận hỏng tại mọi ranh giới cho từng cách.",
"Tầng *đánh giá*. Objective đòi so ba mô hình hỏng chứ ba cách cài đặt. Kiểm bằng ma trận hỏng; đạt khi mỗi cách có hành vi ghi rõ tại mọi ranh giới hỏng và ca điều phối viên chết được tái hiện thật.",
"Cài cùng một quy trình đặt hàng gồm thanh toán và trừ kho theo cả ba cách. Với mỗi cách, giết tiến trình tại từng ranh giới và ghi trạng thái cuối. Tái hiện ca điều phối viên chết sau pha chuẩn bị và đo thời gian tài nguyên bị khoá. Lập ma trận hỏng ba cách nhân các ranh giới. Chọn một cách cho một bối cảnh và nêu trạng thái trung gian mà nghiệp vụ phải chấp nhận.",
"Dùng chốt hai pha mà không tính ca điều phối viên chết · viết thao tác bù bằng cách hoàn tác kỹ thuật thay vì bù nghĩa nghiệp vụ · gửi thông điệp ngoài giao dịch cục bộ · tuyên bố nguyên tử xuyên hệ.",
"Ma trận hỏng đầy đủ cho cả ba cách tại mọi ranh giới, ca điều phối viên chết được tái hiện kèm thời gian khoá đo được."),

(319,"Overload, backpressure and cascading failure","TH","Lesson 318",
"Hệ phân tán hỏng theo dây chuyền, và cơ chế lan truyền phải hiểu để chặn. Chuỗi điển hình: một phụ thuộc chậm lại, bên gọi giữ kết nối lâu hơn, bể kết nối cạn, hàng đợi dài ra, hết giờ kích hoạt, thử lại làm tải tăng thêm, rồi phụ thuộc sập hẳn; **thử lại là chất xúc tác của sập dây chuyền** chứ một biện pháp phòng thủ, nên nó cần ngân sách. Bốn cơ chế chặn: áp lực ngược theo lesson 27, ngắt mạch, vách ngăn để một phụ thuộc hỏng không ăn hết tài nguyên, và suy giảm có kiểm soát. Loại bỏ tải có chủ ý tốt hơn sập toàn bộ: từ chối sớm một phần yêu cầu giữ cho phần còn lại vẫn chạy. Cơn bão thử lại đồng bộ do nhiều khách cùng lùi theo cùng công thức, chặn bằng nhiễu ngẫu nhiên. Sấm sét khi cùng lúc hàng loạt yêu cầu tới một tài nguyên vừa hết đệm.",
"Tái hiện một lần sập dây chuyền và chặn nó bằng bốn cơ chế, có số đo trước sau.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là hệ giữ được một phần năng lực thay vì sập toàn bộ. Kiểm bằng phép thử tải có phụ thuộc chậm; đạt khi bản chưa phòng thủ sập hoàn toàn và bản có phòng thủ giữ được tỉ lệ phục vụ trên ngưỡng.",
"Dựng ba dịch vụ nối nhau. Làm dịch vụ cuối chậm dần và đo chuỗi lan truyền: thời gian giữ kết nối, độ sâu hàng đợi, tỉ lệ hết giờ, tỉ lệ thử lại. Ghi lại thời điểm sập toàn bộ. Thêm lần lượt bốn cơ chế và đo đóng góp của từng cái. Tái hiện cơn bão thử lại đồng bộ rồi chặn bằng nhiễu ngẫu nhiên.",
"Thử lại không có ngân sách · dùng một bể kết nối chung cho mọi phụ thuộc · lùi dần không có nhiễu · coi sập toàn bộ và suy giảm một phần là như nhau.",
"Bản chưa phòng thủ sập hoàn toàn còn bản có phòng thủ giữ tỉ lệ phục vụ trên ngưỡng, và đóng góp của từng cơ chế có số đo."),

(320,"History analysis project - judge a guarantee from evidence","DA","Lesson 319",
"Bài dự án khép module. Cho một tập lịch sử thao tác thu được từ nhiều khách hàng chạy song song trên một kho dữ liệu, mỗi bản ghi có lời gọi, phản hồi và dấu thời gian cục bộ. Nhiệm vụ: xác định lịch sử đó vi phạm mô hình nhất quán nào và chứng minh bằng một chuỗi thao tác cụ thể, chứ nói cảm nhận. Viết một bộ kiểm lịch sử cho một thanh ghi đơn giản và **nêu rõ giới hạn của chính bộ kiểm đó**: nó kiểm được gì, không kiểm được gì, và vì sao không được coi kết quả của nó là một chứng minh đầy đủ về hệ. Phần hai: chạy thử nghiệm của chính mình trên kho khoá giá trị đã dựng ở các bài trước, tiêm phân vùng và lệch đồng hồ, thu lịch sử rồi phân tích. Nộp kèm một bảng ghi với mỗi bảo đảm được tuyên bố thì giả định nào phải đúng và chế độ hỏng nào phá vỡ nó.",
"Xác định đúng mô hình bị vi phạm trên bốn lịch sử và nêu giới hạn của bộ kiểm mình viết.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một năng lực lập luận có bằng chứng. Kiểm bằng bốn lịch sử cộng rà soát bộ kiểm; đạt khi xác định đúng ít nhất ba kèm chuỗi thao tác chứng minh, và giới hạn của bộ kiểm được nêu rõ.",
"Nhận bốn lịch sử, trong đó một lịch sử hợp lệ. Viết bộ kiểm cho thanh ghi. Với mỗi lịch sử vi phạm, chỉ ra chuỗi thao tác cụ thể chứng minh. Chạy thử nghiệm riêng có tiêm phân vùng và lệch đồng hồ, thu lịch sử và phân tích. Nộp bảng bảo đảm với giả định và chế độ hỏng phá vỡ.",
"Tuyên bố đã kiểm chứng toàn hệ từ một bộ kiểm nhỏ · kết luận vi phạm mà không chỉ ra chuỗi thao tác · dùng dấu thời gian cục bộ làm thứ tự toàn cục · bỏ lịch sử hợp lệ nên không kiểm được báo giả.",
"Xác định đúng ≥ 3/4 lịch sử kèm chuỗi thao tác chứng minh, lịch sử hợp lệ không bị báo nhầm, và giới hạn bộ kiểm được nêu rõ."),
]

M16 = ("Kafka and Event Streaming", 321, 334, """| | |
|---|---|
| **Objective cấp module** | Dự đoán được vị trí, thứ tự và quyền sở hữu của bất kỳ khoá nào; giải thích được khi nào một bản ghi hiển thị và khi nào nó bền vững |
| **Tiền đề** | M6 · M10 · M13 · M15 |
| **Exit criterion** | Sổ tay vận hành phủ được độ trễ tiêu thụ, thiếu bản sao đồng bộ, đầy đĩa, bản ghi độc và phá vỡ lược đồ; tính được số bản trùng và lượng mất tối đa cho một cấu hình cho trước |
| **Kỹ năng SFIA** | `SYSP` mức 4 · `ITOP` mức 4 |
| **Chế độ hỏng** | Tăng số phân vùng mà không xử lý khoá và thứ tự, đặt lại vị trí tiêu thụ mà không đối soát, và gọi giao nhận ít nhất một lần là đúng một lần |""",
"""Nhật ký phân tán khác hàng đợi ở một điểm quyết định: bản ghi **không bị xoá khi đã đọc**, nên nhiều nhóm tiêu thụ đọc độc lập và đọc lại được. Hiểu điều đó là hiểu vì sao nó thành xương sống của kiến trúc dữ liệu.

Ranh giới bảo đảm phải phát biểu chính xác: thứ tự chỉ có trong một phân vùng, giao dịch chỉ bao trong phạm vi hệ này, và mọi tuyên bố về đúng một lần phải nêu nguồn, đích và giả định lỗi, theo đúng kết luận ở lesson 318.""")

L16 = [
(321,"Event, command and state - and three messaging shapes","LT","Module 16: M15",
"Bài mở module bằng hai phép phân biệt quyết định thiết kế. Thứ nhất, ba loại thông điệp: sự kiện kể lại một việc đã xảy ra và không kỳ vọng ai làm gì; lệnh yêu cầu một việc được làm và có một người nhận xác định; trạng thái mô tả hiện trạng của một thực thể. Đặt tên sai loại dẫn tới ghép nối sai: gọi một lệnh là sự kiện làm bên sản xuất phụ thuộc ngầm vào việc bên nào đó phải xử lý. Thứ hai, ba hình thái hạ tầng: hàng đợi giao mỗi thông điệp cho một bên tiêu thụ rồi xoá; phát hành và đăng ký gửi cho mọi bên đăng ký tại thời điểm đó; nhật ký phân tán ghi bản ghi vào một chuỗi bền vững có thứ tự và **giữ lại theo thời hạn chứ theo việc đã đọc hay chưa**. Ba hệ quả của việc giữ lại: nhiều nhóm đọc độc lập, đọc lại được từ một vị trí cũ, và nhóm mới bắt đầu từ đầu được.",
"Phân loại thông điệp và chọn hình thái hạ tầng cho bốn tình huống, nêu hệ quả của việc giữ lại bản ghi.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng. Kiểm bằng bài phân loại cộng bài chọn; đạt khi phân đúng ít nhất sáu trong tám thông điệp và chọn đúng hình thái ở ít nhất ba trong bốn tình huống.",
"Cho tám thông điệp thật trong một hệ; phân loại thành sự kiện, lệnh hay trạng thái và chỉ ra ba cái đang đặt tên sai kèm hệ quả ghép nối. Cho bốn tình huống; chọn hình thái hạ tầng và nêu lý do. Với tình huống chọn nhật ký phân tán, liệt kê ba việc làm được nhờ giữ lại bản ghi.",
"Gọi lệnh là sự kiện · dùng hàng đợi rồi muốn đọc lại · giả định nhật ký phân tán thay được mọi hàng đợi · bỏ qua việc thời hạn giữ quyết định đọc lại được bao xa.",
"Phân đúng ≥ 6/8 thông điệp kèm hệ quả của ba cái đặt tên sai, và chọn đúng hình thái ở ≥ 3/4 tình huống."),

(322,"Topic, partition, key and the ordering boundary","TH","Lesson 321",
"Bài dạy mô hình định vị, và nó là bài phải nắm chắc nhất vì mọi thứ sau đều dựa vào. Chủ đề chia thành phân vùng; mỗi bản ghi có vị trí tăng dần trong phân vùng của nó; khoá quyết định phân vùng qua một hàm băm, nên cùng khoá thì cùng phân vùng. Hệ quả trung tâm và là ranh giới bảo đảm: **thứ tự chỉ được giữ trong một phân vùng, không giữ giữa các phân vùng**; muốn hai bản ghi có thứ tự với nhau thì chúng phải cùng khoá. Bản ghi không khoá được rải theo cách khác và không có thứ tự với nhau. Vị trí không phải định danh của bản ghi: nó là vị trí trong một phân vùng cụ thể, nên cùng một con số ở hai phân vùng là hai bản ghi khác nhau. Tăng số phân vùng làm hàm băm cho kết quả khác, nên **khoá cũ có thể chuyển sang phân vùng khác và thứ tự lịch sử bị phá**.",
"Dự đoán đúng phân vùng, thứ tự và nhóm sở hữu cho một tập tình huống khoá, và chứng minh hậu quả của việc tăng phân vùng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là dự đoán khớp thực tế. Kiểm bằng mười tình huống; đạt khi dự đoán đúng ít nhất tám trước khi chạy, và ca phá thứ tự khi tăng phân vùng được tái hiện.",
"Dựng cụm ba máy chủ với một chủ đề sáu phân vùng. Với mười tình huống về khoá và nhóm tiêu thụ, dự đoán phân vùng, thứ tự và bên sở hữu trước khi chạy, rồi đối chiếu. Tăng số phân vùng và chứng minh một khoá cụ thể chuyển sang phân vùng khác, làm bản ghi mới của nó không còn thứ tự với bản ghi cũ.",
"Giả định thứ tự toàn cục trong một chủ đề · dùng vị trí như định danh bản ghi · tăng phân vùng mà không xử lý khoá và thứ tự · gửi bản ghi không khoá rồi mong có thứ tự.",
"Dự đoán đúng ≥ 8/10 tình huống trước khi chạy, và ca khoá chuyển phân vùng sau khi tăng được tái hiện bằng dữ liệu."),

(323,"Broker internals - segment, index, page cache and retention","TH","Lesson 322",
"Bên trong một máy chủ, và hiểu nó giải thích cả hiệu năng lẫn các giới hạn vận hành. Đường đi của một bản ghi: lô bản ghi tới người dẫn phân vùng, ghi nối vào đoạn nhật ký hiện tại, cập nhật chỉ mục, nằm trong bộ đệm trang của hệ điều hành, rồi nút theo sau kéo về. **Ghi nối vào cuối tệp là lý do thông lượng cao**, và nó dùng lại đúng nguyên lý tuần tự nhanh hơn ngẫu nhiên ở lesson 52. Bộ đệm trang đóng vai trò chính nên bộ nhớ trống của máy quan trọng hơn kích thước bộ nhớ tiến trình. Đoạn nhật ký cuộn theo kích thước hoặc thời gian; thời hạn giữ theo thời gian hoặc dung lượng quyết định đọc lại được bao xa. Hai hệ quả vận hành: dung lượng đĩa là ràng buộc cứng, và đầy đĩa làm máy chủ ngừng nhận ghi; nên theo dõi dung lượng là việc bắt buộc chứ tuỳ chọn.",
"Truy đường đi của một bản ghi trên hệ thật và tính được thời hạn đọc lại từ cấu hình cùng dung lượng.",
"Tầng *phân tích*. Objective đòi đọc trạng thái thật thay vì mô tả kiến trúc. Kiểm bằng bài truy vết cộng bài tính; đạt khi truy đủ các chặng trên hệ thật và thời hạn đọc lại tính được khớp quan sát trong sai số thoả thuận.",
"Gửi một lô bản ghi và truy đường đi qua từng chặng: tìm tệp đoạn trên đĩa, xem chỉ mục, quan sát bộ đệm trang, và xác nhận nút theo sau đã kéo về. Tính thời hạn đọc lại từ tốc độ ghi, cấu hình giữ và dung lượng đĩa; đối chiếu với quan sát. Làm đầy đĩa có kiểm soát và ghi lại hành vi của máy chủ.",
"Bỏ qua bộ đệm trang khi tính bộ nhớ cần · đặt thời hạn giữ mà không tính dung lượng · không theo dõi dung lượng đĩa · nghĩ thông lượng cao đến từ phần cứng chứ từ cách ghi nối.",
"Đường đi của bản ghi được truy đủ chặng trên hệ thật, và thời hạn đọc lại tính từ cấu hình khớp quan sát."),

(324,"Log compaction and the tombstone lifecycle","TH","Lesson 323",
"Cơ chế giữ lại bản ghi mới nhất cho mỗi khoá thay vì giữ theo thời gian, dùng khi chủ đề biểu diễn trạng thái chứ chuỗi sự kiện. Quá trình nén giữ lại bản ghi cuối cùng của mỗi khoá và xoá các bản cũ hơn, nên chủ đề trở thành một bản chụp trạng thái có thể đọc lại từ đầu để dựng lại toàn bộ. Bản ghi bia mộ có khoá và giá trị rỗng, báo rằng khoá đã bị xoá; nó phải nằm lại một khoảng đủ lâu để mọi bên tiêu thụ kịp thấy. **Bia mộ hết hạn trước khi một bên tiêu thụ chậm kịp đọc làm bên đó không bao giờ biết khoá đã bị xoá**, nên trạng thái dựng lại của nó thừa một bản ghi; đây là chế độ hỏng đặc trưng và phải tái hiện. Quan hệ với chủ đề theo thời gian: hai chế độ cho hai mục đích, và trộn chúng trên một chủ đề gây nhầm lẫn về nghĩa.",
"Dựng lại trạng thái từ một chủ đề đã nén và tái hiện ca bia mộ hết hạn trước bên tiêu thụ chậm.",
"Tầng *áp dụng*. Objective có một ca hỏng cụ thể cần tái hiện. Kiểm bằng đối soát trạng thái dựng lại; đạt khi trạng thái dựng lại khớp nguồn tuyệt đối, và ca bia mộ hết hạn được tái hiện kèm số khoá thừa.",
"Dựng một chủ đề chế độ nén biểu diễn trạng thái khách hàng. Ghi chuỗi tạo, cập nhật và xoá. Chạy nén rồi đọc lại từ đầu và đối soát trạng thái dựng lại với nguồn. Đặt thời hạn giữ bia mộ ngắn, dừng một bên tiêu thụ đủ lâu rồi cho chạy lại; đếm số khoá đã xoá mà nó vẫn giữ.",
"Dùng chế độ nén cho chủ đề chuỗi sự kiện · đặt thời hạn giữ bia mộ ngắn hơn thời gian dừng tối đa của bên tiêu thụ · gửi bản ghi không khoá vào chủ đề nén · không đối soát trạng thái dựng lại.",
"Trạng thái dựng lại khớp nguồn tuyệt đối, và ca bia mộ hết hạn được tái hiện kèm số khoá thừa đếm được."),

(325,"Producer - acks, retry, idempotent producer and the sequence","TH","Lesson 324",
"Bên sản xuất quyết định một bản ghi bền vững tới mức nào, và ba tham số kiểm soát điều đó. Mức xác nhận: không chờ ai thì nhanh nhất và mất khi người dẫn chết; chờ người dẫn thì mất khi người dẫn chết trước khi nút theo sau kéo về; chờ toàn bộ bản sao đồng bộ thì bền nhất và chậm nhất. Thử lại và hết giờ giao hàng: **một lần thử lại sau khi máy chủ đã ghi thành công nhưng phản hồi thất lạc sẽ tạo bản trùng**, đúng ca không biết kết cục ở lesson 310. Bên sản xuất luỹ đẳng giải ca này bằng số thứ tự và nhiệm kỳ cho mỗi phân vùng, nên máy chủ nhận ra và bỏ bản trùng; giới hạn của nó là chỉ trong phạm vi một phiên và một phân vùng. Số yêu cầu đang bay ảnh hưởng thứ tự khi có thử lại. Gom lô, nén và thời gian chờ gom là ba nút điều chỉnh giữa thông lượng, độ trễ và bộ nhớ.",
"Tính lượng mất và số bản trùng tối đa cho ba cấu hình, và chứng minh bằng thí nghiệm giết máy chủ.",
"Tầng *phân tích*. Objective đòi nối cấu hình với một con số về rủi ro. Kiểm bằng ba cấu hình đo song song; đạt khi số đo khớp con số tính trước trong sai số thoả thuận ở cả ba.",
"Với ba cấu hình xác nhận khác nhau, tính trước lượng mất và số bản trùng tối đa. Chạy tải rồi giết người dẫn phân vùng; đếm bản ghi mất và bản ghi trùng thật, đối chiếu với tính toán. Bật bên sản xuất luỹ đẳng và đo lại số bản trùng. Đo ảnh hưởng của gom lô, nén và thời gian chờ lên thông lượng cùng độ trễ.",
"Dùng mức xác nhận thấp rồi tuyên bố không mất · thử lại mà không bật chế độ luỹ đẳng · tăng số yêu cầu đang bay mà không xét thứ tự · chỉnh ba nút gom lô mà không đo.",
"Số đo mất và trùng khớp tính toán ở cả ba cấu hình, và bên sản xuất luỹ đẳng đưa số bản trùng về không trong phạm vi phiên."),

(326,"Producer transactions and the scope of the guarantee","TH","Lesson 325",
"Giao dịch ở đây cho phép ghi nguyên tử qua nhiều phân vùng và ghi cả vị trí tiêu thụ trong cùng một giao dịch, nên nó giải được mẫu đọc rồi xử lý rồi ghi. Định danh giao dịch cùng cơ chế chặn ngăn một tiến trình cũ ghi tiếp sau khi đã có tiến trình mới, dùng lại đúng ý tưởng thẻ chặn ở lesson 317. Bên tiêu thụ phải đặt ở chế độ chỉ đọc bản đã chốt, nếu không nó vẫn thấy bản ghi của giao dịch chưa chốt. **Ranh giới bảo đảm phải phát biểu chính xác và đây là điểm ra của bài: giao dịch chỉ bao những gì nằm trong hệ này**; nó không bao một lần ghi vào cơ sở dữ liệu bên ngoài, không bao một lời gọi dịch vụ, không bao một lần gửi thư. Muốn đầu cuối thì phải cộng thêm đích luỹ đẳng hoặc hộp thư đi theo lesson 318. Chi phí của giao dịch về độ trễ và về thông lượng phải đo.",
"Cài mẫu đọc rồi xử lý rồi ghi có giao dịch và phát biểu chính xác ranh giới bảo đảm.",
"Tầng *đánh giá*. Objective đòi nêu đúng phạm vi bảo đảm chứ chỉ bật tính năng. Kiểm bằng phép thử giết tiến trình cộng bài phát biểu; đạt khi không bản trùng nào trong phạm vi hệ, và ca ghi ra hệ ngoài được chỉ ra là nằm ngoài bảo đảm kèm cách bù.",
"Cài luồng đọc từ một chủ đề, xử lý, rồi ghi sang chủ đề khác kèm ghi vị trí, tất cả trong một giao dịch. Giết tiến trình ở từng ranh giới và đếm bản trùng ở đích. Thêm một bước ghi vào cơ sở dữ liệu ngoài và chứng minh nó không được giao dịch bảo vệ; bổ sung cơ chế luỹ đẳng cho bước đó. Đo chi phí độ trễ và thông lượng của giao dịch.",
"Tuyên bố đúng một lần đầu cuối nhờ giao dịch · để bên tiêu thụ đọc cả bản chưa chốt · đưa lời gọi dịch vụ ngoài vào trong giao dịch · bật giao dịch mà không đo chi phí.",
"Không bản trùng nào trong phạm vi hệ qua mọi ranh giới giết, và bước ghi ra hệ ngoài được chỉ rõ nằm ngoài bảo đảm kèm cơ chế bù."),

(327,"Consumer - the poll loop, group, assignment and rebalance","TH","Lesson 326",
"Bên tiêu thụ làm việc theo vòng lặp lấy dữ liệu, và mô hình nhóm quyết định ai đọc phân vùng nào. Một nhóm chia các phân vùng cho các thành viên, mỗi phân vùng thuộc đúng một thành viên tại một thời điểm, nên **mức song song tối đa bằng số phân vùng**; thêm thành viên vượt số phân vùng không tăng thông lượng. Điều phối viên nhóm quản lý thành viên qua nhịp tim và thời hạn phiên. Tái cân bằng xảy ra khi thành viên vào, ra, hoặc quá hạn; ca hay gặp và phải tái hiện: **xử lý một lô quá lâu làm thành viên quá hạn giữa chừng và bị coi là chết**, gây tái cân bằng, rồi lô đó bị giao cho người khác xử lý lại. Ba cách giảm: giảm số bản ghi mỗi lần lấy, tăng thời hạn, hoặc tách việc nặng ra khỏi vòng lặp. Kiểu gán hợp tác và thành viên tĩnh chỉ cần biết là có.",
"Dự đoán quyền sở hữu phân vùng qua các lần thay đổi thành viên và tái hiện bão tái cân bằng do xử lý chậm.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là dự đoán khớp và ca hỏng được chặn có số đo. Kiểm bằng sáu tình huống cộng thí nghiệm xử lý chậm; đạt khi dự đoán đúng ít nhất năm và bão tái cân bằng được chặn với số lần tái cân bằng giảm có số đo.",
"Với chủ đề sáu phân vùng, chạy nhóm từ một tới tám thành viên; dự đoán phân bổ trước mỗi lần thay đổi rồi đối chiếu. Đo thông lượng khi số thành viên vượt số phân vùng. Làm xử lý một lô chậm hơn thời hạn và quan sát bão tái cân bằng; đếm số lần tái cân bằng và số bản ghi bị xử lý lại. Áp ba cách giảm và đo lại.",
"Thêm thành viên vượt số phân vùng để tăng thông lượng · để việc nặng trong vòng lặp lấy dữ liệu · tăng thời hạn phiên mà không xét thời gian phát hiện chết · bỏ qua số bản ghi bị xử lý lại sau tái cân bằng.",
"Dự đoán đúng ≥ 5/6 tình huống phân bổ, và số lần tái cân bằng giảm có số đo sau khi áp biện pháp."),

(328,"Offset commit - the two failure windows","TH","Lesson 327",
"Bài chốt ngữ nghĩa giao nhận bằng hai cửa sổ hỏng, và đây là bài quyết định của module. Nếu ghi vị trí trước khi thực hiện tác dụng phụ rồi tiến trình chết ở giữa, bản ghi đó không bao giờ được xử lý: **mất dữ liệu**. Nếu thực hiện tác dụng phụ trước rồi ghi vị trí và chết ở giữa, bản ghi đó được xử lý lại: **trùng lặp**. Không có thứ tự nào tránh được cả hai, nên phải chọn một cửa sổ và bù bằng thiết kế: chọn trùng lặp rồi làm đích luỹ đẳng là lựa chọn đúng trong phần lớn trường hợp, theo kết luận ở lesson 318. Ghi vị trí tự động theo chu kỳ làm cửa sổ rộng và khó suy luận, nên ghi thủ công sau khi xử lý là mặc định nên chọn. Độ trễ tiêu thụ đọc được theo ba cách: theo số bản ghi, theo thời gian, và theo tốc độ xử lý; ba cách cho ba kết luận khác nhau. Chính sách bản ghi độc và hàng đợi bản ghi lỗi.",
"Tái hiện cả hai cửa sổ hỏng bằng thực nghiệm và chọn một cửa sổ rồi bù bằng đích luỹ đẳng.",
"Tầng *phân tích*. Objective đòi chứng minh đánh đổi thay vì phát biểu nó. Kiểm bằng hai thí nghiệm giết tiến trình; đạt khi số mất và số trùng được đếm ở hai thứ tự, và bản có đích luỹ đẳng đưa số trùng quan sát được về không.",
"Cài hai bản: ghi vị trí trước khi xử lý và sau khi xử lý. Giết tiến trình 100 lần ở từng bản và đếm số bản ghi mất cùng số bản ghi xử lý lại. Chọn bản gây trùng và thêm đích luỹ đẳng bằng khoá xác định; chạy lại và đối soát. Đọc độ trễ tiêu thụ theo ba cách trong lúc bên tiêu thụ chậm và giải thích ba kết luận khác nhau.",
"Dùng ghi vị trí tự động rồi suy luận về cửa sổ hỏng · ghi vị trí trước khi xử lý · đọc độ trễ chỉ theo số bản ghi · đặt lại vị trí về cuối để làm sạch cảnh báo mà không đối soát.",
"Hai cửa sổ hỏng có số đo mất và trùng qua 100 lần giết, và bản có đích luỹ đẳng đưa số trùng quan sát được về không."),

(329,"Replication - in-sync replicas, high watermark and leader epoch","TH","Lesson 328",
"Sao chép bên trong, và nó quyết định khi nào một bản ghi hiển thị với bên tiêu thụ. Tập bản sao đồng bộ là những nút theo sau đang bắt kịp người dẫn; một nút tụt quá ngưỡng bị loại khỏi tập. Mốc nước cao là vị trí mà mọi bản sao đồng bộ đã có; **bên tiêu thụ chỉ thấy bản ghi dưới mốc nước cao**, nên có độ trễ giữa lúc ghi xong và lúc đọc được. Ngưỡng số bản sao đồng bộ tối thiểu kết hợp với mức xác nhận toàn bộ mới cho bảo đảm bền vững thật: đặt ngưỡng bằng một thì mức xác nhận toàn bộ không còn nghĩa. Nhiệm kỳ người dẫn giải bài toán nút theo sau có phần nhật ký không thuộc nhiệm kỳ hiện tại, theo đúng cơ chế ở lesson 316. Bầu chọn người dẫn không sạch cho phép một nút không đồng bộ lên làm người dẫn để giữ khả dụng, và **nó đánh đổi bằng mất dữ liệu đã xác nhận**; bật hay tắt là một quyết định nghiệp vụ.",
"Tính lượng dữ liệu có thể mất theo ba tổ hợp cấu hình và chứng minh bằng thí nghiệm giết máy chủ.",
"Tầng *đánh giá*. Objective đòi nối ba tham số thành một con số rủi ro. Kiểm bằng ba tổ hợp; đạt khi lượng mất đo được khớp tính toán ở cả ba và ca bầu chọn không sạch được tái hiện kèm số bản ghi mất.",
"Dựng cụm ba máy chủ, hệ số sao chép ba. Với ba tổ hợp mức xác nhận và ngưỡng bản sao đồng bộ tối thiểu, tính trước lượng mất tối đa. Giết người dẫn rồi giết thêm một nút theo sau; đếm bản ghi đã xác nhận mà mất. Bật bầu chọn không sạch, tái hiện ca mất dữ liệu đã xác nhận. Đo độ trễ giữa lúc ghi và lúc đọc được.",
"Đặt mức xác nhận toàn bộ với ngưỡng bản sao đồng bộ bằng một · bật bầu chọn không sạch mà không coi là quyết định nghiệp vụ · giả định bản ghi ghi xong là đọc được ngay · bỏ theo dõi số phân vùng thiếu bản sao.",
"Lượng mất đo được khớp tính toán ở cả ba tổ hợp, và ca bầu chọn không sạch được tái hiện kèm số bản ghi đã xác nhận bị mất."),

(330,"Controller quorum and metadata","LT","Lesson 329",
"Mặt phẳng điều khiển quản lý siêu dữ liệu của cụm: danh sách máy chủ, phân vùng nào có người dẫn nào, và cấu hình. Nó dựa trên một nhật ký được sao chép cùng số đông, tức chính cơ chế đồng thuận ở lesson 316 áp dụng cho siêu dữ liệu chứ cho dữ liệu người dùng. Hệ quả vận hành: số đông điều khiển mất số đông thì cụm không bầu được người dẫn mới và không đổi được cấu hình, dù dữ liệu vẫn còn nguyên trên đĩa; **cụm vẫn phục vụ đọc ghi trên các phân vùng chưa đổi người dẫn nhưng không tự hồi phục được**, và phân biệt hai trạng thái này khi trực là quan trọng. Đăng ký máy chủ và nhiệm kỳ. Kiến trúc cũ dùng một hệ phối hợp riêng chỉ cần biết ở mức lịch sử. Ba chỉ số phải theo dõi cho mặt phẳng điều khiển và vì sao chúng khác chỉ số của mặt phẳng dữ liệu.",
"Phân biệt sự cố mặt phẳng điều khiển với sự cố mặt phẳng dữ liệu từ triệu chứng và số đo.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho bài diễn tập. Kiểm bằng bốn tình huống chẩn đoán; đạt khi phân đúng ít nhất ba và nêu đúng việc cụm còn làm được gì trong mỗi tình huống.",
"Cho bốn tình huống với triệu chứng và số đo. Với mỗi cái, xác định sự cố thuộc mặt phẳng nào và liệt kê việc cụm còn làm được. Trên cụm lab, dừng số đông điều khiển và quan sát: ghi và đọc trên phân vùng cũ còn chạy không, tạo chủ đề mới có được không, người dẫn mới có bầu được không.",
"Nhầm sự cố điều khiển với sự cố dữ liệu · giả định mất số đông điều khiển là cụm ngừng hoàn toàn · theo dõi cụm chỉ bằng chỉ số của mặt phẳng dữ liệu · đổi cấu hình khi số đông điều khiển chưa lành.",
"Phân đúng ≥ 3/4 tình huống, và quan sát thật trên cụm xác nhận đúng việc cụm còn làm được khi mất số đông điều khiển."),

(331,"Schema registry, compatibility and consumer rollout order","TH","Lesson 330",
"Hợp đồng dữ liệu trên nhật ký phân tán có một khó khăn riêng: bản ghi cũ vẫn nằm trong nhật ký và vẫn được đọc lại, nên bên tiêu thụ mới phải đọc được cả bản ghi viết bằng lược đồ cũ. Sổ đăng ký lược đồ giữ phiên bản và cưỡng chế quy tắc tương thích tại thời điểm đăng ký, nên thay đổi phá vỡ bị chặn trước khi tới môi trường chạy. Mức tương thích quyết định thứ tự triển khai, theo đúng lesson 220: tương thích ngược thì nâng cấp bên tiêu thụ trước, tương thích xuôi thì nâng cấp bên sản xuất trước; **chọn sai thứ tự làm một phía không đọc được dữ liệu của phía kia**. Khác biệt so với hợp đồng theo yêu cầu phản hồi ở M8: ở đây không điều phối được thời điểm, vì dữ liệu cũ tồn tại suốt thời hạn giữ. Cách xử lý bản ghi không giải mã được: đưa vào hàng đợi bản ghi lỗi kèm nguyên nhân, không bỏ im lặng.",
"Thực hiện một thay đổi lược đồ theo đúng thứ tự triển khai và chứng minh không bên nào ngừng đọc được.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là không gián đoạn ở cả hai phía. Kiểm bằng thí nghiệm triển khai có tải; đạt khi không bên tiêu thụ nào lỗi suốt quá trình và bản ghi cũ trong nhật ký vẫn đọc được sau khi nâng cấp.",
"Đăng ký lược đồ với mức tương thích chọn trước. Ghi 100.000 bản ghi bằng lược đồ cũ. Thực hiện một thay đổi tương thích và một thay đổi phá vỡ; xác nhận thay đổi phá vỡ bị sổ đăng ký chặn. Triển khai theo đúng thứ tự suy ra từ mức tương thích, với cả hai phía đang chạy tải. Đọc lại toàn bộ nhật ký từ đầu bằng bên tiêu thụ mới và đối soát.",
"Nâng cấp bên sản xuất trước khi mức tương thích cho phép · đặt sổ đăng ký ở chế độ không cưỡng chế · bỏ bản ghi không giải mã được · quên rằng dữ liệu cũ vẫn nằm trong nhật ký.",
"Không bên tiêu thụ nào lỗi suốt quá trình triển khai, và bên tiêu thụ mới đọc lại toàn bộ nhật ký cũ với đối soát khớp."),

(332,"Capacity - partition count from throughput, not a rule","TH","Lesson 331",
"Số phân vùng là quyết định khó đảo ngược nhất, nên nó phải tính chứ chọn theo quy tắc ngón tay. Bốn yếu tố đầu vào: thông lượng mục tiêu, mức song song tiêu thụ cần, thời gian phục hồi khi một máy chủ chết, và chi phí siêu dữ liệu trên mỗi phân vùng. Quá ít phân vùng thì không đủ song song và có phân vùng nóng; quá nhiều thì tăng chi phí siêu dữ liệu, kéo dài thời gian bầu chọn khi máy chủ chết, và tăng độ trễ đầu cuối vì lô nhỏ đi. **Tăng số phân vùng về sau phá thứ tự theo khoá** theo lesson 322, nên việc di trú phải có kế hoạch chứ làm tại chỗ. Khoá nóng là bài toán khác với thiếu phân vùng và cần cách khác: thêm phân vùng không chia nhỏ được một khoá. Kích thước bản ghi, thời hạn giữ và dung lượng cho ra ràng buộc lưu trữ. Đọc lại toàn bộ là một hợp đồng phải tính vào năng lực.",
"Tính số phân vùng từ bốn yếu tố đầu vào và kiểm bằng phép thử tải ở ba mức.",
"Tầng *đánh giá*. Objective đòi tính từ ràng buộc chứ chọn theo quy tắc. Kiểm bằng phép thử tải ba mức; đạt khi con số tính ra đạt thông lượng mục tiêu và đường cong cho thấy điểm tăng phân vùng bắt đầu phản tác dụng.",
"Tính số phân vùng cho một khối lượng công việc cho trước từ bốn yếu tố. Chạy tải với ba mức số phân vùng quanh con số tính được; đo thông lượng, độ trễ phân vị 95, thời gian phục hồi khi giết một máy chủ, và chi phí siêu dữ liệu. Tạo một khoá nóng và chứng minh thêm phân vùng không giúp. Lập kế hoạch di trú nếu phải tăng phân vùng.",
"Chọn số phân vùng theo một quy tắc chung · tăng phân vùng để chữa khoá nóng · tăng phân vùng tại chỗ mà không có kế hoạch di trú khoá · bỏ thời gian phục hồi khỏi tính toán.",
"Con số tính ra đạt thông lượng mục tiêu trong phép thử, và đường cong ba mức cho thấy điểm tăng phân vùng phản tác dụng."),

(333,"Security, quota and multi-tenancy","TH","Lesson 332",
"Cụm dùng chung nhiều đội đặt ra ba yêu cầu mà một cụm lab không có. Mã hoá đường truyền và xác thực cho cả máy khách lẫn giữa các máy chủ. Quyền truy cập ở mức chủ đề và mức nhóm, theo nguyên tắc quyền tối thiểu ở lesson 106: một bên tiêu thụ chỉ cần quyền đọc một chủ đề và quyền quản lý nhóm của nó. Hạn mức theo người dùng hoặc theo máy khách giới hạn băng thông và tốc độ yêu cầu, để **một đội chạy đọc lại toàn bộ không làm chậm mọi đội khác**; đây là ca cụ thể phải tái hiện vì đọc lại là thao tác hợp lệ nhưng nặng. Xoay thông tin xác thực mà không gián đoạn. Phân loại dữ liệu trên chủ đề và hệ quả về thời hạn giữ cùng quyền xem, nối với lesson 306. Ba chế độ hỏng của cụm dùng chung và cách cô lập.",
"Cài xác thực, phân quyền và hạn mức, rồi chứng minh một bên đọc lại không làm vỡ cam kết của bên khác.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là cách ly đo được dưới tải. Kiểm bằng phép thử đọc lại; đạt khi bên bị ảnh hưởng giữ độ trễ trong cam kết, và phép thử phủ định về quyền bị chặn hết.",
"Bật mã hoá đường truyền và xác thực. Cấp quyền tối thiểu cho hai đội. Chạy phép thử phủ định: mỗi đội thử đọc và ghi chủ đề của đội kia. Đặt hạn mức. Cho một đội đọc lại toàn bộ chủ đề lớn trong khi đội kia đang chạy tải bình thường; đo độ trễ của đội kia trước và trong lúc đọc lại. Xoay thông tin xác thực không gián đoạn.",
"Cấp quyền theo chủ đề mà quên quyền nhóm · không đặt hạn mức nên một đội chiếm hết băng thông · dùng chung một tài khoản cho nhiều đội · xoay thông tin xác thực bằng cách dừng dịch vụ.",
"Phép thử phủ định bị chặn hết, độ trễ của đội không liên quan giữ trong cam kết suốt lần đọc lại, và xoay thông tin xác thực không gây gián đoạn."),

(334,"Game day - kill the leader, the controller and the consumer","DA","Lesson 333",
"Bài dự án khép module. Chạy diễn tập trên cụm đã dựng, với hành vi kỳ vọng viết trước theo đúng kỷ luật ở lesson 246. Tám tình huống bắt buộc: giết người dẫn của một phân vùng đang có tải; giết một máy chủ mang nhiều người dẫn; làm mất số đông điều khiển; giết bên tiêu thụ giữa lúc đã thực hiện tác dụng phụ nhưng chưa ghi vị trí; làm tập bản sao đồng bộ co lại; làm đầy đĩa một máy chủ; đưa một bản ghi độc vào chủ đề; và triển khai một thay đổi lược đồ phá vỡ. Với mỗi tình huống ghi ba số: thời gian phát hiện, thời gian phục hồi, và số bản ghi mất hoặc trùng đo bằng đối soát. **Phục hồi bằng cách đặt lại vị trí về cuối là lối tắt bị cấm**, vì nó bỏ qua dữ liệu chưa xử lý mà không ai biết; mọi lần đặt lại vị trí phải kèm đối soát. Nộp sổ tay vận hành gồm cả năm mục bắt buộc.",
"Chạy tám tình huống với hành vi kỳ vọng viết trước và nộp sổ tay vận hành có bằng chứng đối soát.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành năng lực vận hành có số đo. Kiểm bằng tám tình huống; đạt khi ít nhất bảy phục hồi với đối soát khớp và không lần nào dùng lối tắt đặt lại vị trí về cuối.",
"Viết hành vi kỳ vọng cho tám tình huống. Chạy từng cái trên cụm có tải. Ghi ba số cho mỗi tình huống. Đối soát số bản ghi ở đích với nguồn sau mỗi lần phục hồi. Nộp sổ tay gồm độ trễ tiêu thụ, thiếu bản sao, đầy đĩa, bản ghi độc và phá vỡ lược đồ.",
"Đặt lại vị trí về cuối để hết cảnh báo · viết hành vi kỳ vọng sau khi thấy kết quả · bỏ tình huống mất số đông điều khiển vì khó dựng · không đối soát sau phục hồi.",
"≥ 7/8 tình huống phục hồi với đối soát khớp, ba số đo đầy đủ cho mỗi tình huống, và sổ tay có đủ năm mục bắt buộc."),
]

M17 = ("Change Data Capture Internals", 335, 344, """| | |
|---|---|
| **Objective cấp module** | Vẽ được đường từ vị trí nhật ký nguồn tới vị trí trình kết nối tới vị trí trên nhật ký phân tán tới điểm kiểm tra ở đích, và chứng minh tính đầy đủ bằng đối soát |
| **Tiền đề** | M10 · M13 · M15 · M16 |
| **Exit criterion** | Giải thích được tính nhất quán của bản chụp ban đầu cùng cửa sổ hỏng của nó và chứng minh bằng đối soát; sổ tay phủ rủi ro thời hạn giữ ở nguồn, độ trễ, bản ghi độc, chụp lại và phá vỡ lược đồ |
| **Kỹ năng SFIA** | `DTAN` mức 4 · `SYSP` mức 4 |
| **Chế độ hỏng** | Xoá khe sao chép để tắt cảnh báo mà không có kế hoạch phục hồi, và chụp lại đè lên trạng thái đang phục vụ |""",
"""Module học sâu cơ chế mà M14B chỉ nhắc tới. Nó nối trực tiếp ba module trước: nhật ký ghi trước ở M10 là nguồn, nhật ký phân tán ở M16 là đường truyền, và lập luận về hỏng ở M15 là khung phân tích.

Điểm khó nhất và cũng là đóng góp chính của module: **bản chụp ban đầu phải được đan xen với dòng thay đổi đang chạy**, vì nguồn vẫn đang ghi trong lúc ta chụp. Làm sai chỗ này tạo ra khoảng trống hoặc ghi đè ngược, và cả hai đều im lặng.""")

L17 = [
(335,"Three ways to capture change and their cost","LT","Module 17: M16",
"Bài mở module bằng việc so ba cách lấy thay đổi, để thấy vì sao cách thứ ba đáng học sâu. Hỏi theo dấu thời gian hoặc theo khoá: đơn giản, chạy được ở mọi nguồn, nhưng **bỏ sót thay đổi xảy ra giữa hai lần hỏi và không thấy bản ghi bị xoá**, đúng năm giả định ở lesson 234. Bẫy cơ sở dữ liệu ghi thay đổi vào một bảng phụ: bắt được đủ thao tác gồm cả xoá, nhưng thêm chi phí ghi lên mọi giao dịch của nguồn và phải bảo trì bẫy. Đọc nhật ký giao dịch: bắt đủ mọi thay đổi theo đúng thứ tự, độ trễ thấp, và gần như không thêm tải ghi cho nguồn; đổi lại phức tạp về vận hành và tạo một phụ thuộc mới lên thời hạn giữ nhật ký của nguồn. Ba tiêu chí so: tải đặt lên nguồn, độ trễ, và tính đầy đủ. Phân biệt với nguồn sự kiện: ở đó ứng dụng chủ động phát ý định nghiệp vụ, còn ở đây ta suy ra thay đổi từ trạng thái vật lý.",
"So ba cách theo ba tiêu chí và chứng minh cách hỏi theo dấu thời gian bỏ sót thay đổi.",
"Tầng *hiểu*. Bài mở module, kiểm bằng một thí nghiệm nhỏ chứ chỉ lập luận. Kiểm bằng phép đếm bỏ sót; đạt khi số thay đổi bị bỏ sót được đo thật và bảng ba cách nhân ba tiêu chí có số ở tiêu chí tải nguồn.",
"Dựng một bảng nguồn có ghi liên tục. Chạy cách hỏi theo dấu thời gian mỗi 10 giây trong khi ghi nhiều lần một bản ghi và xoá vài bản ghi; đếm số thay đổi bị bỏ sót và số bản xoá không thấy. Cài một bẫy và đo chi phí ghi thêm trên nguồn. Lập bảng ba cách nhân ba tiêu chí.",
"Dùng cách hỏi theo dấu thời gian rồi tuyên bố bắt đủ thay đổi · cài bẫy mà không đo chi phí ghi thêm · nhầm bắt thay đổi với nguồn sự kiện · chọn đọc nhật ký mà chưa tính phụ thuộc thời hạn giữ.",
"Số thay đổi bỏ sót và số bản xoá không thấy được đo thật, và bảng ba cách có số đo ở tiêu chí tải nguồn."),

(336,"Inside the transaction log - WAL, logical decoding and the replication slot","TH","Lesson 335",
"Bài đi vào cơ chế của nguồn, dùng lại nhật ký ghi trước ở lesson 137 nhưng ở vai người đọc. Với hệ quan hệ phổ biến: nhật ký ghi trước ghi mọi thay đổi vật lý; bộ giải mã logic dịch chúng thành thay đổi mức hàng có nghĩa; khe sao chép giữ vị trí mà bên đọc đã xác nhận, và **nguồn không được xoá phần nhật ký chưa được khe nào xác nhận**. Từ đó suy ra rủi ro trung tâm của module: bên đọc dừng thì nhật ký tích luỹ và đĩa nguồn đầy dần, nên một trình kết nối chết có thể làm sập cơ sở dữ liệu sản xuất. Vị trí khởi động lại và vị trí đã xác nhận là hai con số khác nhau. Với hệ khác thì có nhật ký nhị phân cùng định dạng và vị trí hoặc định danh giao dịch toàn cục. Ranh giới giao dịch có trong nhật ký, và đây là thứ cách hỏi theo dấu thời gian không bao giờ có.",
"Đọc được vị trí và trạng thái khe trên nguồn thật, và định lượng tốc độ tích luỹ nhật ký khi bên đọc dừng.",
"Tầng *phân tích*. Objective đòi quan sát trạng thái thật của nguồn. Kiểm bằng thí nghiệm dừng bên đọc; đạt khi tốc độ tích luỹ được đo theo đơn vị dung lượng trên giờ và thời gian tới khi đầy đĩa tính được.",
"Bật giải mã logic trên một cơ sở dữ liệu lab và tạo một khe. Đọc vị trí khởi động lại và vị trí đã xác nhận, giải thích khác biệt. Chạy tải ghi, dừng bên đọc, và đo tốc độ tích luỹ nhật ký. Tính thời gian còn lại tới khi đầy đĩa. Cho bên đọc chạy lại và xác nhận nhật ký được giải phóng.",
"Tạo khe rồi quên bên đọc · nhầm vị trí khởi động lại với vị trí đã xác nhận · không đo tốc độ tích luỹ nên không đặt được cảnh báo · giả định nguồn tự dọn nhật ký.",
"Tốc độ tích luỹ được đo theo dung lượng trên giờ, thời gian tới khi đầy đĩa tính được, và nhật ký được giải phóng sau khi bên đọc chạy lại."),

(337,"The consistent bootstrap - snapshot interleaved with the live log","TH","Lesson 336",
"Bài khó nhất của module và là đóng góp chính của nó. Bài toán: phải chụp toàn bộ dữ liệu hiện có, nhưng nguồn vẫn đang ghi trong lúc chụp, nên một bản ghi có thể được chụp ở trạng thái cũ rồi ngay sau đó một sự kiện thay đổi cũ hơn tới đích và ghi đè lên, tạo ra dữ liệu lùi về quá khứ. Thuật toán năm bước: xác lập vị trí nhật ký và ranh giới nhất quán trước khi chụp; đọc bảng theo từng khối trong khi vẫn thu sự kiện thay đổi; **đan xen sao cho một dòng của bản chụp không bao giờ ghi đè một sự kiện mới hơn**, dùng cơ chế mốc nước hoặc so phiên bản theo khoá; hoàn tất bản chụp rồi tiếp tục phát dòng từ đúng vị trí đã xác lập; và chỉ lưu vị trí của trình kết nối theo đúng giao thức giao nhận. Chia khối theo khoá có chỉ mục và ảnh hưởng lên nguồn theo lesson 238. Hai chế độ hỏng: khoảng trống, và ghi đè ngược.",
"Chạy bản chụp ban đầu trong khi nguồn đang ghi và chứng minh không có khoảng trống cũng không có ghi đè ngược.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là đối soát khớp tuyệt đối dưới ghi đồng thời. Kiểm bằng đối soát tập khoá và giá trị; đạt khi đích khớp nguồn tại một ranh giới bất biến, và bản cài sai được chứng minh tạo ghi đè ngược.",
"Chạy tải ghi liên tục trên nguồn. Khởi tạo bản chụp trong lúc đó. Sau khi hoàn tất, dừng ghi và đối soát tập khoá cùng giá trị giữa nguồn và đích. Cài thêm một bản cố ý bỏ bước đan xen và chứng minh nó tạo ra dữ liệu lùi về quá khứ; đếm số bản ghi sai. Đo ảnh hưởng của việc chụp lên nguồn.",
"Chụp xong rồi mới bắt đầu thu dòng thay đổi · để dòng bản chụp ghi đè sự kiện mới hơn · khoá bảng để chụp cho đơn giản · không đối soát sau khi hoàn tất.",
"Đích khớp nguồn tuyệt đối tại ranh giới bất biến, và bản bỏ bước đan xen được chứng minh tạo ghi đè ngược kèm số bản ghi sai."),

(338,"The event envelope - before, after, op and source metadata","TH","Lesson 337",
"Cấu trúc một sự kiện thay đổi, và mỗi trường tồn tại để trả lời một câu hỏi vận hành. Trạng thái trước và trạng thái sau cho phép bên tiêu thụ biết cái gì đã đổi chứ chỉ biết giá trị mới. Mã thao tác phân biệt thêm, sửa, xoá và đọc từ bản chụp; phân biệt cái cuối là quan trọng vì sự kiện từ bản chụp không có trạng thái trước. Siêu dữ liệu nguồn gồm tên bảng, vị trí trong nhật ký, định danh giao dịch và dấu thời gian ở nguồn; **vị trí trong nhật ký là thứ tạo nên thứ tự xác định cho mỗi khoá**, và nó là cơ sở để đích khử trùng và chọn bản thắng. Khoá của sự kiện lấy từ khoá chính, và nó quyết định phân vùng theo lesson 322 nên mọi thay đổi của một hàng đi cùng phân vùng và giữ đúng thứ tự. Sự kiện bia mộ cho thao tác xoá theo lesson 324. Đích áp dụng bằng ghi đè theo khoá cộng so phiên bản.",
"Cài đích áp dụng sự kiện đúng cho cả bốn mã thao tác, dùng vị trí nhật ký để chọn bản thắng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là trạng thái đích khớp nguồn sau một chuỗi thao tác hỗn hợp. Kiểm bằng đối soát sau 10.000 thao tác; đạt khi đích khớp nguồn tuyệt đối và sự kiện tới sai thứ tự không làm sai trạng thái.",
"Thu sự kiện cho một bảng và kiểm từng trường của phong bì. Cài đích áp dụng bằng ghi đè theo khoá với so phiên bản theo vị trí nhật ký. Chạy 10.000 thao tác hỗn hợp gồm thêm, sửa, xoá. Cố ý đảo thứ tự một số sự kiện khi giao và chứng minh so phiên bản giữ trạng thái đúng. Đối soát cuối cùng.",
"Chỉ dùng trạng thái sau nên không biết cái gì đã đổi · áp dụng theo thứ tự tới thay vì theo vị trí nhật ký · xử lý sự kiện từ bản chụp như một lần sửa · bỏ qua sự kiện bia mộ.",
"Đích khớp nguồn tuyệt đối sau 10.000 thao tác, và sự kiện bị đảo thứ tự không làm sai trạng thái nhờ so phiên bản."),

(339,"Ordering scope and the multi-table transaction limit","TH","Lesson 338",
"Bài phát biểu chính xác bảo đảm về thứ tự, vì đây là chỗ kỳ vọng thường vượt thực tế. Thứ tự được giữ cho mỗi khoá, vì mọi thay đổi của một hàng vào cùng phân vùng. Thứ tự giữa hai bảng khác nhau thì không, vì chúng thường ở hai chủ đề hoặc hai phân vùng khác nhau. **Hệ quả: một giao dịch nguồn chạm hai bảng sẽ tới đích thành hai sự kiện độc lập, và đích có thể thấy nửa giao dịch trong một khoảng thời gian**; nếu hạ nguồn có ràng buộc tham chiếu giữa hai bảng thì nó sẽ thấy trạng thái không nhất quán tạm thời. Ba cách xử lý và đánh đổi: chấp nhận trạng thái trung gian và nói rõ với bên tiêu thụ; gom theo định danh giao dịch rồi áp dụng cả cụm; hoặc đưa hai bảng về một chủ đề với khoá chung. Định danh giao dịch có trong phong bì nên gom được, nhưng ranh giới kết thúc giao dịch cần một tín hiệu riêng.",
"Tái hiện ca đích thấy nửa giao dịch và chọn một cách xử lý kèm điều kiện áp dụng.",
"Tầng *phân tích*. Objective đòi nhận ra một giới hạn thường bị bỏ qua khi thiết kế. Kiểm bằng ca tái hiện cộng bài chọn; đạt khi ca nửa giao dịch được quan sát và định lượng khoảng thời gian, và cách xử lý chọn kèm hai điều kiện.",
"Tạo một giao dịch nguồn chạm hai bảng có quan hệ tham chiếu. Ở đích, chạy một truy vấn liên tục kiểm ràng buộc tham chiếu và ghi lại mọi lần nó bị vi phạm cùng độ dài khoảng thời gian. Cài cách gom theo định danh giao dịch và đo lại. So độ trễ của hai cách. Viết một câu cho bên tiêu thụ nói rõ bảo đảm thứ tự mà họ nhận được.",
"Giả định thứ tự toàn cục giữa các bảng · để hạ nguồn cưỡng chế ràng buộc tham chiếu mà không nói trước · gom theo giao dịch mà không có tín hiệu kết thúc · bỏ qua độ trễ tăng thêm khi gom.",
"Ca nửa giao dịch được quan sát kèm độ dài khoảng thời gian, và cách xử lý chọn kèm hai điều kiện áp dụng."),

(340,"Position, offset and checkpoint - three different things","TH","Lesson 339",
"Ba con số hay bị gọi chung là tiến độ, và trộn chúng làm không chẩn đoán được. Vị trí trong nhật ký nguồn là tiến độ của trình kết nối trên nguồn, và nó điều khiển việc nguồn giải phóng nhật ký theo lesson 336. Vị trí trên nhật ký phân tán là tiến độ của bản ghi đã được ghi sang đường truyền. Điểm kiểm tra ở đích là tiến độ của việc áp dụng vào kho cuối. Ba con số tiến theo ba nhịp và khoảng cách giữa chúng là ba loại độ trễ khác nhau, mỗi loại có nguyên nhân riêng và cách xử lý riêng. **Thứ tự lưu trạng thái phải theo đúng quy tắc ở lesson 240**: chỉ tiến một con số sau khi dữ liệu tương ứng đã bền vững ở bước sau. Ca hỏng bắt buộc tái hiện: trình kết nối chết sau khi đã phát sự kiện nhưng trước khi lưu vị trí, dẫn tới phát lại và trùng lặp ở đích; lời giải là đích luỹ đẳng chứ cố tránh phát lại.",
"Đo riêng ba loại độ trễ và tái hiện ca phát lại sau khi chết, chứng minh đích luỹ đẳng xử lý đúng.",
"Tầng *phân tích*. Objective đòi tách ba tiến độ thường bị gộp. Kiểm bằng ba số đo cộng thí nghiệm giết; đạt khi ba loại độ trễ được đo riêng và đích vẫn khớp nguồn sau 50 lần giết ngẫu nhiên.",
"Dựng đường đầy đủ từ nguồn qua nhật ký phân tán tới đích. Đo riêng ba loại độ trễ dưới tải và vẽ ba đường. Giết trình kết nối 50 lần ở các thời điểm ngẫu nhiên, trong đó có lần sau khi phát và trước khi lưu vị trí. Đếm số sự kiện trùng ở đích. Bật đích luỹ đẳng và đối soát lại.",
"Gọi chung ba con số là độ trễ · lưu vị trí trình kết nối trước khi sự kiện bền vững ở đường truyền · cố tránh phát lại thay vì làm đích luỹ đẳng · theo dõi một loại độ trễ rồi kết luận cho cả tuyến.",
"Ba loại độ trễ được đo riêng, và đích khớp nguồn sau 50 lần giết nhờ luỹ đẳng."),

(341,"Deletes, truncates, primary key updates and tombstones","TH","Lesson 340",
"Bốn thao tác phá vỡ giả định thông thường của bên tiêu thụ, và cả bốn phải xử lý tường minh. Xoá tạo sự kiện có trạng thái trước và không có trạng thái sau, kèm bia mộ để chủ đề nén dọn được; đích phải xoá thật hoặc đánh dấu tuỳ hợp đồng, và **bỏ qua xoá làm đích phình dần và mọi phép đếm sai**. Cắt bảng ở nhiều hệ không sinh sự kiện mức hàng, nên đích không biết bảng đã rỗng; cần xử lý riêng hoặc cấm thao tác này ở nguồn. Cập nhật khoá chính là ca khó nhất: nguồn coi là một lần sửa, nhưng ở đích khoá cũ và khoá mới là hai hàng, nên nếu không xử lý thì hàng cũ ở lại thành bản mồ côi và số lượng bị đếm đôi; lời giải là phát cả sự kiện xoá khoá cũ lẫn sự kiện thêm khoá mới. Xoá theo tầng ở nguồn sinh hàng loạt sự kiện và có thể gây dồn ứ.",
"Xử lý đúng cả bốn thao tác và chứng minh đích không còn bản mồ côi cũng không đếm đôi.",
"Tầng *áp dụng*. Objective có bốn ca biên với tiêu chí nghiệm thu bằng đối soát. Kiểm bằng bốn thao tác tiêm; đạt khi đích khớp nguồn về tập khoá và số lượng sau cả bốn, và ca cắt bảng được xử lý tường minh.",
"Thực hiện bốn thao tác trên nguồn: xoá, cắt bảng, cập nhật khoá chính, và xoá theo tầng nhiều nghìn hàng. Sau mỗi thao tác, đối soát tập khoá và số lượng giữa nguồn và đích. Với cập nhật khoá chính, chứng minh không còn hàng mồ côi. Với cắt bảng, chỉ ra hệ có sinh sự kiện không và xử lý tường minh. Đo dồn ứ khi xoá theo tầng.",
"Bỏ qua sự kiện xoá · coi cập nhật khoá chính là một lần sửa thường · giả định cắt bảng sinh sự kiện mức hàng · không đo dồn ứ khi có thao tác hàng loạt.",
"Đích khớp nguồn về tập khoá và số lượng sau cả bốn thao tác, không còn hàng mồ côi, và ca cắt bảng có xử lý tường minh."),

(342,"Schema change, schema history and quarantine","TH","Lesson 341",
"Lược đồ nguồn đổi trong lúc dòng đang chạy, và trình kết nối phải xử lý được vì nó không kiểm soát nguồn. Lịch sử lược đồ được lưu riêng để giải mã đúng sự kiện cũ: một sự kiện phát ra ba tháng trước phải được diễn giải bằng lược đồ của thời điểm đó chứ lược đồ hiện tại, nên **đọc lại dữ liệu cũ cần lịch sử lược đồ còn nguyên**; mất lịch sử lược đồ là mất khả năng đọc lại. Ba loại thay đổi và phản ứng, theo phân loại ở lesson 241: thêm cột thì bên tiêu thụ cũ vẫn chạy; đổi kiểu thu hẹp là phá vỡ; đổi tên là phá vỡ với bên đọc theo tên. Thứ tự triển khai giữa bên sản xuất và bên tiêu thụ lấy từ mức tương thích ở lesson 331. Sự kiện không giải mã được đi vào vùng cách ly kèm nguyên nhân và vị trí, để phát lại sau khi sửa chứ bỏ.",
"Xử lý ba loại thay đổi lược đồ trong lúc dòng đang chạy và đọc lại được dữ liệu cũ sau đó.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là đọc lại dữ liệu cũ vẫn đúng sau khi lược đồ đã đổi. Kiểm bằng phép đọc lại; đạt khi dữ liệu trước thay đổi được giải mã đúng, không sự kiện nào bị bỏ im lặng, và sự kiện cách ly phát lại được.",
"Chạy dòng liên tục rồi thực hiện ba thay đổi lược đồ ở nguồn. Với mỗi cái, ghi lại phản ứng của trình kết nối và của bên tiêu thụ. Sau khi đổi xong, đọc lại toàn bộ chủ đề từ đầu và xác nhận dữ liệu cũ giải mã đúng nhờ lịch sử lược đồ. Tạo một sự kiện không giải mã được, xác nhận nó vào vùng cách ly, sửa rồi phát lại.",
"Xoá lịch sử lược đồ để dọn dẹp · để sự kiện không giải mã được bị bỏ qua · đổi lược đồ nguồn mà không báo bên tiêu thụ · triển khai sai thứ tự so với mức tương thích.",
"Dữ liệu trước thay đổi giải mã đúng khi đọc lại, không sự kiện nào bị bỏ im lặng, và sự kiện cách ly được phát lại thành công."),

(343,"Slot retention, lag and the source disk risk","TH","Lesson 342",
"Bài vận hành quan trọng nhất của module, vì đây là chỗ một lỗi ở hệ phụ làm sập hệ chính. Chuỗi nhân quả: bên tiêu thụ dừng hoặc chậm, trình kết nối không tiến vị trí đã xác nhận, nguồn không giải phóng nhật ký, đĩa nguồn đầy dần, rồi cơ sở dữ liệu sản xuất ngừng nhận ghi. Ba chỉ số phải theo dõi và đặt ngưỡng: độ trễ của khe tính bằng dung lượng, tốc độ tăng, và dung lượng đĩa còn lại quy ra thời gian. **Cảnh báo phải đặt theo thời gian còn lại chứ theo phần trăm đĩa**, vì phần trăm không nói được còn bao lâu để xử lý. Quy trình khi cảnh báo nổ, theo thứ tự: tìm nguyên nhân bên tiêu thụ dừng, khôi phục nó, chỉ khi hết cách mới cân nhắc bỏ khe. Bỏ khe là thao tác phá huỷ: nó giải phóng đĩa ngay nhưng **mất toàn bộ thay đổi chưa đọc, nên bắt buộc phải chụp lại**, và chụp lại phải vào không gian cách ly chứ đè lên trạng thái đang phục vụ.",
"Dựng cảnh báo theo thời gian còn lại và chạy đúng quy trình xử lý khi khe phình, không dùng thao tác phá huỷ.",
"Tầng *đánh giá*. Objective đo năng lực vận hành dưới một rủi ro có thể làm sập hệ chính. Kiểm bằng tình huống tái hiện; đạt khi cảnh báo nổ trước ngưỡng thời gian thoả thuận và quy trình phục hồi không cần bỏ khe.",
"Dựng ba chỉ số và đặt cảnh báo theo thời gian còn lại. Dừng bên tiêu thụ và để khe phình; xác nhận cảnh báo nổ đúng lúc. Chạy quy trình phục hồi theo thứ tự và đo thời gian tới khi nhật ký được giải phóng. Ở môi trường cách ly, thực hiện một lần bỏ khe rồi chụp lại vào không gian riêng, đối soát trước khi hoán đổi.",
"Đặt cảnh báo theo phần trăm đĩa · bỏ khe để tắt cảnh báo · chụp lại đè lên trạng thái đang phục vụ · không đo thời gian còn lại nên không biết còn bao lâu để xử lý.",
"Cảnh báo nổ trước ngưỡng thời gian thoả thuận, phục hồi hoàn tất không cần bỏ khe, và lần chụp lại ở môi trường cách ly có đối soát trước khi hoán đổi."),

(344,"CDC project - reconcile after repeated crashes","DA","Lesson 343",
"Bài dự án khép module. Dựng đường đầy đủ từ một cơ sở dữ liệu quan hệ qua nhật ký phân tán tới một đích phân tích, chạy được cả khởi tạo, dòng liên tục, và chụp lại. Nộp gồm: sơ đồ bốn vị trí tiến độ theo lesson 340 với số đo độ trễ thật cho từng chặng; bằng chứng bản chụp ban đầu nhất quán theo lesson 337; xử lý đủ bốn thao tác ở lesson 341; lịch sử lược đồ cùng vùng cách ly; ba chỉ số cùng cảnh báo theo lesson 343; và sổ tay vận hành. Nghiệm thu bằng đối soát sau khi giết lặp lại: chạy tải ghi liên tục trên nguồn, giết trình kết nối, máy chủ nhật ký và tiến trình ghi đích ở các thời điểm ngẫu nhiên ít nhất 30 lần, rồi đối soát tập khoá và giá trị giữa nguồn và đích tại một ranh giới bất biến. **Mọi việc chạy xong không phải bằng chứng; đối soát mới là.**",
"Nộp đường bắt thay đổi hoàn chỉnh, đối soát khớp nguồn sau ít nhất 30 lần giết ngẫu nhiên.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module. Kiểm bằng đối soát sau giết lặp lại; đạt khi đích khớp nguồn tuyệt đối về tập khoá và giá trị, và bốn vị trí tiến độ đều có số đo độ trễ.",
"Dựng đường đầy đủ. Chạy tải ghi liên tục gồm thêm, sửa, xoá và một lần cập nhật khoá chính. Giết ba thành phần ngẫu nhiên ít nhất 30 lần. Dừng ghi và đối soát. Thực hiện một lần chụp lại vào không gian cách ly rồi hoán đổi. Nộp sổ tay đủ năm mục bắt buộc.",
"Coi trình kết nối báo chạy là bằng chứng đầy đủ · chụp lại đè lên đích đang phục vụ · bỏ ca cập nhật khoá chính · đối soát bằng cách đếm tổng mà không so tập khoá.",
"Đích khớp nguồn tuyệt đối về tập khoá và giá trị sau ≥ 30 lần giết, bốn vị trí tiến độ có số đo độ trễ, và lần chụp lại có đối soát trước khi hoán đổi."),
]

M18 = ("Spark, Flink and Distributed Compute Engines", 345, 360, """| | |
|---|---|
| **Objective cấp module** | Ánh xạ mã nguồn thành kế hoạch logic, toán tử vật lý, giai đoạn và tác vụ; điều chỉnh bắt đầu từ số đo chứ từ việc đổi cấu hình |
| **Tiền đề** | M3 · M4 · M5 · M12 · M13 · M15 · M16 |
| **Exit criterion** | Giải thích được song song lồng nhau và tránh được cấp phát quá mức giữa lõi của tiến trình thực thi, mức đồng thời của tác vụ, luồng của thư viện gốc và số nút; chọn giữa **bốn lớp engine** gồm hai engine phân tán và hai engine một máy, theo khối lượng công việc, quy mô, độ trễ, nhu cầu giữ trạng thái và chi phí vận hành |
| **Kỹ năng SFIA** | `SYSP` mức 5 · `PROG` mức 4 |
| **Chế độ hỏng** | Đổi cấu hình bộ nhớ tiến trình thực thi một cách ngẫu nhiên, kéo toàn bộ dữ liệu về tiến trình điều khiển, và tuyên bố dòng chảy đúng một lần mà bỏ qua đích |""",
"""Module áp toàn bộ phần song song ở M4 vào một engine thật. Ba tầng đặt ra ở lesson 48 và lesson 56 gặp lại đầy đủ: **cụm tính toán là nhiều lệnh nhiều dữ liệu phân tán, một mảnh toán tử chạy theo khuôn mẫu một chương trình nhiều dữ liệu trên nhiều phân vùng, và bên trong mỗi tác vụ có đường xử lý theo lô cùng làn véctơ.**

Kỷ luật điều chỉnh lấy từ M4 và giữ nguyên ở đây: sửa dữ liệu, bố cục và thuật toán trước khi chạm tới cấu hình bộ nhớ.

Một engine học sâu là đủ; engine dòng chảy còn lại ở mức hiểu kiến trúc và khác biệt, trừ khi công việc yêu cầu.""")

L18 = [
(345,"Cluster roles and the execution hierarchy","LT","Module 18: M16",
"Bài mở module bằng từ vựng thực thi, vì năm từ dưới đây bị dùng lẫn thường xuyên. Tiến trình điều khiển giữ kế hoạch, lập lịch và gom kết quả; tiến trình thực thi chạy tác vụ và giữ dữ liệu trong bộ nhớ; bộ quản lý cụm cấp tài nguyên. Bậc thang thực thi có bốn mức lồng nhau: một ứng dụng gồm nhiều công việc, một công việc gồm nhiều giai đoạn, một giai đoạn gồm nhiều tác vụ, và **một tác vụ xử lý đúng một phân vùng**. Từ đó suy ra quan hệ nền tảng: số tác vụ trong một giai đoạn bằng số phân vùng, nên số phân vùng là nút điều chỉnh mức song song chứ số lõi. Tiến trình điều khiển là điểm nghẽn tiềm tàng và là điểm hỏng: kéo dữ liệu lớn về nó làm tràn bộ nhớ, và kế hoạch quá lớn cùng quá nhiều siêu dữ liệu cũng làm nó chậm. Ánh xạ sang ba tầng song song ở lesson 48 được làm rõ ở lesson 352.",
"Ánh xạ năm từ vựng thực thi vào một ứng dụng thật và đếm đúng số tác vụ của từng giai đoạn.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng. Kiểm bằng bài đọc giao diện theo dõi; đạt khi đếm đúng số giai đoạn và số tác vụ cho ba công việc và giải thích được nguồn gốc của số tác vụ.",
"Chạy ba công việc có hình dạng khác nhau. Với mỗi cái, mở giao diện theo dõi và ghi số công việc, giai đoạn và tác vụ. Giải thích số tác vụ của mỗi giai đoạn đến từ đâu. Thay đổi số phân vùng đầu vào và xác nhận số tác vụ đổi theo. Kéo một tập dữ liệu lớn về tiến trình điều khiển và quan sát hậu quả.",
"Nghĩ số tác vụ do số lõi quyết định · kéo dữ liệu lớn về tiến trình điều khiển · nhầm công việc với giai đoạn · bỏ qua tiến trình điều khiển khi tính năng lực.",
"Đếm đúng số giai đoạn và tác vụ cho ba công việc, và giải thích được số tác vụ đến từ số phân vùng."),

(346,"From code to logical plan to physical operators","TH","Lesson 345",
"Bài truy đường biên dịch, nối thẳng với nội dung engine truy vấn ở lesson 126 và lesson 130. Bốn bước: mã dựng kế hoạch logic chưa phân giải; bộ phân tích phân giải tên và kiểu theo danh mục; bộ tối ưu áp luật viết lại cùng thông tin chi phí; bộ lập kế hoạch chọn toán tử vật lý. Đọc kế hoạch là kỹ năng chính của module: phần quét cho biết có cắt tỉa và có đẩy điều kiện xuống không theo lesson 206 và 210; phần kết cho biết chiến lược được chọn; phần trao đổi cho biết ranh giới giai đoạn; phần gộp và sắp xếp cho biết chi phí bộ nhớ. **Kế hoạch đã tối ưu khác kế hoạch vật lý, và chỉ kế hoạch vật lý mới nói được công việc sẽ chạy ra sao.** Hai giới hạn của bộ tối ưu phải biết: nó dựa vào thống kê nên thống kê cũ cho kế hoạch tồi, và nó không nhìn thấy bên trong hàm do người dùng viết.",
"Đọc kế hoạch vật lý của ba truy vấn và dự đoán đúng số giai đoạn trước khi chạy.",
"Tầng *phân tích*. Objective đòi dự đoán từ kế hoạch rồi kiểm bằng thực tế. Kiểm bằng ba truy vấn; đạt khi dự đoán đúng số giai đoạn ở ít nhất hai và chỉ ra đúng vị trí mọi bước trao đổi dữ liệu.",
"Với ba truy vấn có hình dạng khác nhau, xuất cả kế hoạch logic, kế hoạch đã tối ưu và kế hoạch vật lý. Dự đoán số giai đoạn từ số bước trao đổi trước khi chạy, rồi đối chiếu. Làm thống kê lạc hậu và quan sát kế hoạch đổi thế nào. Chèn một hàm do người dùng viết và chỉ ra bộ tối ưu mất khả năng gì.",
"Đọc kế hoạch logic rồi kết luận về cách chạy · bỏ qua bước trao đổi khi đếm giai đoạn · chạy với thống kê lạc hậu · chèn hàm tự viết vào chỗ cần đẩy điều kiện xuống.",
"Dự đoán đúng số giai đoạn ở ≥ 2/3 truy vấn, và mọi bước trao đổi dữ liệu được chỉ đúng vị trí trong kế hoạch."),

(347,"Narrow and wide dependencies, and why exchange creates a stage","TH","Lesson 346",
"Bài giải thích ranh giới giai đoạn bằng cơ chế chứ bằng quy ước. Phụ thuộc hẹp: mỗi phân vùng đầu ra chỉ cần một phân vùng đầu vào, nên phép biến đổi chạy tại chỗ và nhiều phép nối tiếp nhau gộp vào một tác vụ. Phụ thuộc rộng: một phân vùng đầu ra cần dữ liệu từ nhiều phân vùng đầu vào, nên phải xáo trộn dữ liệu qua mạng; **bước trao đổi là ranh giới giai đoạn vì giai đoạn sau không bắt đầu được cho tới khi giai đoạn trước ghi xong toàn bộ dữ liệu xáo trộn**, tức nó là một rào đồng bộ. Từ đó suy ra ba hệ quả thực hành: giảm số bước xáo trộn là đòn bẩy tối ưu lớn nhất; một tác vụ chậm trong giai đoạn trước giữ chân cả giai đoạn sau; và dòng dõi cho phép tính lại một phân vùng mất mà không chạy lại toàn bộ. Điểm kiểm tra khác dòng dõi: dòng dõi tính lại, điểm kiểm tra cắt chuỗi tính lại.",
"Phân loại phép biến đổi theo hai loại phụ thuộc và giảm được số bước xáo trộn của một công việc thật.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là số bước xáo trộn giảm mà kết quả không đổi. Kiểm bằng cặp số đo; đạt khi số bước trao đổi giảm ít nhất một, thời gian giảm có số đo, và kết quả đối soát khớp bản gốc.",
"Phân loại mười phép biến đổi vào hai loại. Lấy một công việc có bốn bước xáo trộn; viết lại để giảm ít nhất một bước, chẳng hạn bằng cách gộp phép gộp hoặc đổi thứ tự. Đo thời gian và lượng dữ liệu xáo trộn trước sau. Đối soát kết quả. Giết một tiến trình thực thi và quan sát việc tính lại theo dòng dõi; thêm điểm kiểm tra rồi đo lại.",
"Coi ranh giới giai đoạn là quy ước · thêm phép sắp xếp không cần thiết · đặt điểm kiểm tra khắp nơi · sửa mà không đối soát kết quả.",
"Số bước trao đổi giảm ≥ 1 với thời gian giảm có số đo, và kết quả đối soát khớp bản gốc tuyệt đối."),

(348,"Join strategies and the threshold that is not magic","TH","Lesson 347",
"Ba chiến lược kết trong engine phân tán, tương ứng ba thuật toán ở lesson 127 nhưng thêm chiều mạng. Kết phát tán băm gửi bảng nhỏ tới mọi tiến trình thực thi rồi kết cục bộ, nên không cần xáo trộn bảng lớn; điều kiện là bảng nhỏ vừa bộ nhớ, và **ngưỡng phát tán dựa trên ước lượng kích thước nên thống kê sai làm tràn bộ nhớ** theo đúng ca ở lesson 212. Kết băm sau xáo trộn băm cả hai bảng theo khoá kết. Kết trộn sau sắp xếp sắp cả hai rồi trộn, ổn định với dữ liệu lớn và tốn chi phí sắp xếp. Thực thi thích ứng có thể đổi chiến lược khi thấy kích thước thật tại thời gian chạy, nhưng nó chỉ sửa được sau khi đã có thống kê thật của giai đoạn trước, nên **nó không cứu được mọi trường hợp**. Ép chiến lược bằng gợi ý là công cụ chẩn đoán, không phải giải pháp lâu dài.",
"Ép cả ba chiến lược trên cùng phép kết, đo chi phí từng cái, và tái hiện ca phát tán gây tràn bộ nhớ.",
"Tầng *phân tích*. Objective đòi nối lựa chọn chiến lược với số đo và với một ca hỏng. Kiểm bằng ba chiến lược đo song song; đạt khi ba chiến lược có số đo thời gian cùng lượng xáo trộn và ca tràn bộ nhớ do ước lượng sai được tái hiện.",
"Với một phép kết giữa bảng lớn và bảng vừa, ép lần lượt ba chiến lược và xác nhận trong kế hoạch. Đo thời gian, lượng dữ liệu xáo trộn và bộ nhớ đỉnh. Làm thống kê sai để engine chọn phát tán cho một bảng quá lớn và ghi lại lỗi tràn bộ nhớ. Bật thực thi thích ứng và chỉ ra nó sửa được ca nào, không sửa được ca nào.",
"Tin ngưỡng phát tán là con số an toàn · ép gợi ý rồi để đó thay vì sửa thống kê · bỏ qua lượng dữ liệu xáo trộn khi so · cho rằng thực thi thích ứng chữa được mọi kế hoạch tồi.",
"Ba chiến lược có số đo thời gian và lượng xáo trộn, và ca tràn bộ nhớ do ước lượng sai được tái hiện cùng giải thích."),

(349,"Shuffle - read, write, sort, spill and serialization","TH","Lesson 348",
"Bước xáo trộn là thao tác đắt nhất, nên nó có một bài riêng để mổ xẻ chi phí. Bốn thành phần chi phí phải tách: ghi dữ liệu xáo trộn ra đĩa cục bộ, truyền qua mạng, đọc lại, và chi phí tuần tự hoá cùng giải tuần tự hoá. **Xáo trộn đi qua ba bậc chậm nhất của thứ bậc bộ nhớ cùng lúc** theo lesson 58, nên nó thường chiếm phần lớn thời gian. Tràn đĩa xảy ra khi bộ nhớ làm việc không đủ cho phép sắp xếp hoặc phép gộp; nó là cơ chế sống sót chứ lỗi, nhưng làm chậm nhiều lần và phải đọc được trong số đo. Chi phí tuần tự hoá là phần hay bị bỏ qua và thường lớn hơn phép tính, nhất là với hàm do người dùng viết bằng ngôn ngữ cần chuyển đổi dữ liệu qua ranh giới. Số phân vùng sau xáo trộn quá nhỏ gây tràn, quá lớn gây nhiều tác vụ vụn và tăng chi phí lập lịch.",
"Tách bốn thành phần chi phí của một bước xáo trộn và giảm tổng thời gian có số đo mà kết quả không đổi.",
"Tầng *phân tích*. Objective đòi phân giải một số tổng thành bốn phần để biết sửa chỗ nào. Kiểm bằng phép đo phân tách; đạt khi bốn thành phần đều có số, và thành phần lớn nhất được giảm với tổng thời gian giảm theo.",
"Chạy một công việc có bước xáo trộn lớn dưới bộ nhớ hạn chế. Đo riêng bốn thành phần chi phí cùng mức tràn đĩa và thời gian thu dọn rác. Thử bốn mức số phân vùng sau xáo trộn và vẽ đường thời gian. Giảm chi phí tuần tự hoá bằng cách thay hàm tự viết bằng biểu thức có sẵn và đo lại. Đối soát kết quả.",
"Tăng bộ nhớ tiến trình thực thi trước khi biết thành phần nào đắt · coi tràn đĩa là lỗi cấu hình · bỏ qua chi phí tuần tự hoá · chọn số phân vùng sau xáo trộn theo mặc định.",
"Bốn thành phần chi phí đều có số đo, và thành phần lớn nhất giảm kéo tổng thời gian giảm theo với kết quả không đổi."),

(350,"Memory, caching and garbage collection","TH","Lesson 349",
"Bộ nhớ của tiến trình thực thi chia thành phần cho thực thi và phần cho lưu trữ, và hai phần cạnh tranh nhau. Lưu tạm một tập dữ liệu chỉ có lợi khi nó được đọc lại nhiều lần; **lưu tạm một tập dùng đúng một lần vừa không giúp vừa chiếm chỗ của phần thực thi**, làm tăng tràn đĩa. Các mức lưu tạm khác nhau về nơi giữ và về việc có tuần tự hoá không, nên chúng đánh đổi giữa bộ nhớ và chi phí giải tuần tự hoá. Thu dọn rác trở thành vấn đề khi giữ quá nhiều đối tượng sống: bộ thu dọn chạy liên tục và ăn thời gian bộ xử lý mà không làm việc hữu ích; biểu diễn dữ liệu ngoài vùng quản lý bộ nhớ giảm áp lực này. Ba dấu hiệu phân biệt thiếu bộ nhớ thật với dùng bộ nhớ sai cách. Giải phóng bộ nhớ lưu tạm khi không cần nữa là việc phải làm tường minh.",
"Quyết định lưu tạm dựa trên số lần đọc lại và chứng minh bằng số đo rằng lưu tạm sai làm chậm hơn.",
"Tầng *đánh giá*. Objective chống lại phản xạ lưu tạm mọi thứ. Kiểm bằng ba tình huống đo song song; đạt khi quyết định đúng ở cả ba và ca lưu tạm sai được định lượng mức chậm thêm.",
"Cho ba tình huống với số lần đọc lại khác nhau là một, ba và mười. Chạy có và không có lưu tạm ở từng tình huống; đo thời gian, mức tràn đĩa và thời gian thu dọn rác. Thử ba mức lưu tạm khác nhau cho tình huống đọc lại nhiều. Tạo một ca giữ quá nhiều đối tượng sống và quan sát thu dọn rác; giảm bằng biểu diễn ngoài vùng quản lý.",
"Lưu tạm mọi tập dữ liệu trung gian · lưu tạm tập dùng một lần · không giải phóng bộ nhớ lưu tạm · tăng bộ nhớ khi nguyên nhân là thu dọn rác.",
"Quyết định lưu tạm đúng ở cả ba tình huống, và ca lưu tạm sai được định lượng mức chậm thêm."),

(351,"Skew, stragglers and the salt-or-broadcast decision","TH","Lesson 350",
"Lệch tải là nguyên nhân số một khiến một công việc chạy lâu bất thường mà mọi cấu hình trông đều hợp lý. Triệu chứng đặc trưng: trong một giai đoạn, phần lớn tác vụ xong nhanh còn một hoặc vài tác vụ chạy lâu gấp nhiều lần; phân bố thời gian tác vụ là số đo chẩn đoán chính, và giá trị trung bình che mất hiện tượng này nên phải nhìn phân vị. Nguyên nhân: một khoá chiếm phần lớn số dòng, nên tác vụ nhận khoá đó làm nhiều việc hơn hẳn. Ba cách xử lý và điều kiện dùng: thêm phần ngẫu nhiên vào khoá rồi gộp hai bước, chuyển sang kết phát tán nếu một bên đủ nhỏ, hoặc tách riêng các khoá nóng và xử lý theo đường khác. **Mọi cách xử lý lệch tải đều đổi hình dạng phép tính, nên bắt buộc đối soát kết quả.** Phân biệt lệch tải với tác vụ chậm do máy yếu hoặc do thu dọn rác.",
"Chẩn đoán lệch tải từ phân bố thời gian tác vụ và sửa bằng một trong ba cách, có đối soát kết quả.",
"Tầng *phân tích*. Objective đòi phân biệt lệch tải với hai nguyên nhân giống triệu chứng. Kiểm bằng ba tình huống; đạt khi chẩn đoán đúng cả ba và bản sửa lệch tải cho kết quả khớp bản gốc với thời gian giảm có số đo.",
"Tạo lệch tải bằng một khoá chiếm phần lớn số dòng. Chạy và ghi phân bố thời gian tác vụ; chỉ ra trung bình che hiện tượng thế nào. Thử cả ba cách xử lý, đo thời gian và đối soát kết quả với bản gốc. Tạo thêm hai tình huống có triệu chứng giống nhưng nguyên nhân là máy yếu và thu dọn rác; phân biệt bằng số đo.",
"Đánh giá bằng thời gian tác vụ trung bình · thêm phần ngẫu nhiên vào khoá mà không đối soát · tăng số phân vùng để chữa lệch tải · nhầm tác vụ chậm do máy yếu với lệch tải.",
"Chẩn đoán đúng cả ba tình huống bằng số đo, và bản sửa lệch tải khớp kết quả gốc với thời gian giảm có số đo."),

(352,"Distributed MIMD and SPMD in a compute engine","LT","Lesson 351",
"Bài đặt engine vào đúng khung phân loại ở lesson 48 và nối với lesson 56 cùng lesson 211. Mỗi lõi của mỗi tiến trình thực thi có dòng lệnh và trạng thái riêng, nên cụm là nhiều lệnh nhiều dữ liệu bộ nhớ phân tán. Bộ lập lịch gửi cùng một mã toán tử cho nhiều phân vùng, nên đây là khuôn mẫu một chương trình nhiều dữ liệu. Hệ quả quan trọng và hay bị hiểu sai: **tác vụ song song dữ liệu không chạy đồng bộ từng bước**; thời gian của chúng khác nhau do lệch tải, vị trí dữ liệu, thu dọn rác, vào ra, thử lại và phần cứng không đồng nhất, và chênh lệch đó là bình thường. Bước trao đổi dữ liệu là ranh giới truyền thông và đồng bộ; rào cùng phép gộp cuối làm lộ phần tuần tự và làm lộ tác vụ chậm. Bên trong một tác vụ, bộ giải mã tệp cột và toán tử truy vấn có thể dùng đường xử lý theo lô và làn véctơ, tức tầng thứ ba theo lesson 208.",
"Truy được ba tầng song song trên một công việc thật và gán đúng mỗi mức tăng quan sát được về một tầng.",
"Tầng *hiểu*. Bài lý thuyết nối M4 với engine thật, chuẩn bị cho hai bài đo. Kiểm bằng bài truy tầng; đạt khi ba tầng được chỉ ra bằng bằng chứng quan sát được và ba mức tăng được gán đúng tầng.",
"Trên một công việc thật, chỉ ra bằng chứng của từng tầng: số tiến trình thực thi và lõi cho tầng nhiều lệnh nhiều dữ liệu, cùng một mã toán tử chạy trên nhiều phân vùng cho khuôn mẫu một chương trình nhiều dữ liệu, và đường xử lý theo lô trong kế hoạch cho tầng làn véctơ. Ghi phân bố thời gian tác vụ và giải thích vì sao chênh lệch là bình thường. Gán ba mức tăng quan sát được về đúng tầng.",
"Gộp ba tầng thành một lời giải thích · coi chênh lệch thời gian giữa các tác vụ là lỗi · nói engine nhanh vì dùng lệnh véctơ mà không tách các tầng · nhầm khuôn mẫu một chương trình nhiều dữ liệu với kiến trúc phần cứng.",
"Ba tầng được chỉ ra bằng bằng chứng quan sát được, và ba mức tăng được gán đúng tầng kèm lý do."),

(353,"Nested parallelism and oversubscription","TH","Lesson 352",
"Bài chỉ ra một chế độ hỏng mà chỉ hiểu song song lồng nhau mới nhận ra. Bốn nguồn song song cùng tồn tại: số nút trong cụm, số lõi cấp cho mỗi tiến trình thực thi, số tác vụ chạy đồng thời trong một tiến trình, và **luồng do thư viện gốc tự tạo bên trong một tác vụ**, chẳng hạn thư viện đại số tuyến tính hoặc thư viện xử lý cột. Nguồn thứ tư là nguồn ẩn: nó không xuất hiện trong bất kỳ cấu hình nào của engine, nhưng nó nhân lên với ba nguồn kia. Cấp phát quá mức xảy ra khi tổng số luồng vượt số lõi thật: hậu quả là tranh chấp bộ nhớ đệm, bão hoà băng thông bộ nhớ và chuyển ngữ cảnh liên tục, nên **thêm song song làm chậm hơn**, đúng hiện tượng ở lesson 55. Cách phát hiện: so tổng số luồng quan sát được với số lõi, và đo băng thông bộ nhớ. Cách chặn: đặt giới hạn luồng cho thư viện gốc một cách tường minh.",
"Phát hiện cấp phát quá mức bằng số đo và chặn nó, chứng minh thông lượng tăng trở lại.",
"Tầng *phân tích*. Objective nhắm vào một nguồn song song không xuất hiện trong cấu hình engine. Kiểm bằng cặp số đo; đạt khi tổng số luồng và số lõi được đo, và sau khi đặt giới hạn thì thông lượng tăng có số đo.",
"Chạy một công việc có dùng thư viện gốc đa luồng. Đếm tổng số luồng thật trên một máy và so với số lõi. Đo băng thông bộ nhớ và tỉ lệ chuyển ngữ cảnh. Đặt giới hạn luồng cho thư viện gốc và chạy lại; đo thông lượng cùng thời gian phân vị 95 của tác vụ. Lập bảng bốn nguồn song song với giá trị hiện tại của từng nguồn.",
"Tăng số lõi mỗi tiến trình mà không biết thư viện gốc đang tạo bao nhiêu luồng · chỉ đếm song song ở tầng engine · kết luận thiếu tài nguyên khi nguyên nhân là tranh chấp · không đặt giới hạn luồng tường minh.",
"Tổng số luồng và số lõi được đo, và sau khi đặt giới hạn thì thông lượng tăng với thời gian phân vị 95 của tác vụ giảm."),

(354,"Strong scaling lab - where scale-out turns negative","TH","Lesson 353",
"Bài thí nghiệm khép phần song song: cố định khối lượng công việc và tăng tài nguyên, rồi tìm điểm mà thêm tài nguyên bắt đầu phản tác dụng. Chạy với 1, 2, 4 và nhiều hơn số lõi hoặc tiến trình thực thi; tính tăng tốc và hiệu suất song song ở từng mức theo lesson 56, và **báo cáo cả hai chứ chỉ tăng tốc**. Tách thời gian thành bốn phần: chờ lập lịch, tính, xáo trộn cùng truyền thông, và tuần tự hoá; bốn phần này tiến hoá khác nhau khi tăng quy mô, và phần nào tăng theo là phần chỉ ra trần. Năm nguyên nhân làm tăng quy mô phản tác dụng: phần tuần tự ở tiến trình điều khiển, chi phí xáo trộn tăng theo số phân vùng, lệch tải, cấp phát quá mức theo lesson 353, và nút cổ chai ở hệ bên ngoài như nguồn dữ liệu. Kết luận phải là một khuyến nghị về số tài nguyên kèm lý do, chứ một đồ thị.",
"Vẽ đường hiệu suất song song tới ít nhất tám mức và quy trần về đúng một trong năm nguyên nhân.",
"Tầng *đánh giá*. Objective đòi giải thích đường cong chứ chỉ vẽ nó. Kiểm bằng thí nghiệm tăng quy mô; đạt khi bốn thành phần thời gian được tách ở mọi mức, điểm phản tác dụng được xác định, và trần quy về một nguyên nhân có bằng chứng.",
"Cố định tập dữ liệu và chạy với ít nhất bốn mức tài nguyên tăng dần. Ở mỗi mức, tính tăng tốc và hiệu suất song song, và tách bốn thành phần thời gian. Xác định mức mà thêm tài nguyên không còn giúp hoặc làm chậm hơn. Quy trần về một trong năm nguyên nhân bằng bằng chứng. Viết khuyến nghị về số tài nguyên kèm ngưỡng chi phí.",
"Báo cáo tăng tốc mà không báo hiệu suất song song · thêm tài nguyên khi trần là nguồn dữ liệu bên ngoài · không tách thời gian nên không biết phần nào tăng · kết luận bằng đồ thị mà không có khuyến nghị.",
"Đường hiệu suất song song có số đo ở ≥ 4 mức, bốn thành phần thời gian tách được ở mọi mức, và trần quy về một nguyên nhân có bằng chứng."),

(355,"Tuning project - the decision tree on three unknown jobs","DA","Lesson 354",
"Bài dự án về điều chỉnh hiệu năng, chạy theo một cây quyết định có thứ tự cố định để chống việc đổi cấu hình ngẫu nhiên. Thứ tự bắt buộc: kiểm tính đúng, lược đồ và số phân vùng trước; đọc kế hoạch theo trình tự quét rồi cắt tỉa rồi chiến lược kết rồi trao đổi rồi gộp và sắp xếp rồi ghi ra; thu số đo gồm số dòng và byte vào ra, phân bố thời gian tác vụ, lượng xáo trộn, mức tràn đĩa, thời gian thu dọn rác, bộ nhớ đỉnh và thời gian chờ lập lịch; chẩn đoán phân biệt lệch tải với thiếu song song với quá nhiều tác vụ vụn; rồi **sửa dữ liệu, bố cục và thuật toán trước khi chạm tới cấu hình bộ nhớ**. Nhận ba công việc chưa từng thấy, mỗi cái có một nguyên nhân khác nhau. Với mỗi công việc, đề xuất đúng một thay đổi có kiểm soát, đo trước sau, và đối soát kết quả.",
"Chẩn đoán ba công việc lạ theo cây quyết định và cải thiện từng cái bằng đúng một thay đổi có kiểm soát.",
"Tầng *sáng tạo*. Bài tổng hợp phần hiệu năng thành một quy trình chẩn đoán có kỷ luật. Kiểm bằng ba công việc; đạt khi chẩn đoán đúng nguyên nhân ở ít nhất hai, mỗi cải thiện chỉ dùng một thay đổi, và kết quả đối soát không đổi.",
"Nhận ba công việc chậm với ba nguyên nhân khác nhau. Với mỗi cái, chạy đủ cây quyết định và ghi số đo ở từng bước. Nêu giả thuyết trước khi sửa. Áp đúng một thay đổi, đo lại và đối soát kết quả. Nộp báo cáo hiệu năng theo chuẩn ở lesson 59, bắt đầu từ số đo chứ từ cấu hình.",
"Đổi nhiều cấu hình cùng lúc · tăng bộ nhớ tiến trình thực thi trước khi đọc kế hoạch · sửa mà không đối soát kết quả · viết báo cáo bắt đầu bằng việc đã đổi gì thay vì đã đo gì.",
"Chẩn đoán đúng nguyên nhân ở ≥ 2/3 công việc, mỗi cải thiện dùng đúng một thay đổi có số đo trước sau, và kết quả đối soát không đổi."),

(356,"Structured streaming - micro-batch, offsets, checkpoint and state","TH","Lesson 355",
"Bài chuyển sang xử lý dòng trên cùng engine, với mô hình xử lý theo lô nhỏ. Mỗi lần kích hoạt, engine đọc một khoảng vị trí từ nguồn, xử lý, ghi ra đích, rồi lưu tiến độ; nên nó là một chuỗi công việc theo lô liên tiếp chứ một dòng chảy từng bản ghi. Điểm kiểm tra giữ ba thứ: vị trí nguồn, trạng thái của các phép toán có trạng thái, và siêu dữ liệu của lần ghi; **mất điểm kiểm tra là mất khả năng tiếp tục đúng chỗ**, và nó không dựng lại được từ đích. Kho trạng thái giữ dữ liệu cho phép gộp theo cửa sổ và phép kết dòng; trạng thái phình vô hạn nếu không có cơ chế hết hạn, và đây là chế độ hỏng vận hành phổ biến nhất. Ba chế độ ghi ra và điều kiện dùng. Đổi lược đồ trạng thái giữa hai lần triển khai là thao tác không tương thích ngược ở nhiều trường hợp và phải có kế hoạch.",
"Vận hành một công việc dòng có trạng thái, khôi phục từ điểm kiểm tra, và chặn được trạng thái phình vô hạn.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là tiếp tục đúng chỗ và trạng thái có trần. Kiểm bằng phép thử giết và đo trạng thái; đạt khi khôi phục không mất và không trùng ngoài giới hạn đã nêu, và kích thước trạng thái ổn định sau khi đặt hết hạn.",
"Dựng công việc dòng có phép gộp theo cửa sổ. Chạy vài giờ và đo kích thước trạng thái theo thời gian; chứng minh nó phình khi chưa có hết hạn. Đặt cơ chế hết hạn và đo lại. Giết công việc và khôi phục từ điểm kiểm tra; đối soát kết quả. Xoá điểm kiểm tra và chỉ ra hậu quả. Thử đổi lược đồ trạng thái và ghi lại phản ứng.",
"Coi mô hình theo lô nhỏ là dòng chảy từng bản ghi · để trạng thái không có cơ chế hết hạn · xoá điểm kiểm tra để khởi động lại sạch · đổi lược đồ trạng thái mà không có kế hoạch.",
"Khôi phục từ điểm kiểm tra không mất và không trùng ngoài giới hạn đã nêu, và kích thước trạng thái ổn định sau khi đặt hết hạn."),

(357,"Event time, watermark and late data","TH","Lesson 356",
"Bài áp ba trục thời gian ở lesson 251 vào xử lý dòng, nơi chúng trở thành cơ chế chạy được. Thời gian sự kiện là lúc việc xảy ra; xử lý theo thời gian sự kiện cho kết quả đúng và ổn định khi chạy lại, còn xử lý theo thời gian tới thì kết quả đổi mỗi lần chạy lại. Mốc nước là ước lượng của engine về thời điểm mà mọi sự kiện trước đó coi như đã tới; nó điều khiển thời điểm đóng cửa sổ và giải phóng trạng thái. Đánh đổi trung tâm phải đo: **mốc nước rộng cho kết quả đầy đủ hơn nhưng trễ hơn và giữ trạng thái lâu hơn**, mốc nước hẹp cho kết quả sớm nhưng bỏ nhiều sự kiện muộn. Độ trễ cho phép quyết định cửa sổ đã đóng còn nhận cập nhật không. Sự kiện tới sau ngưỡng phải có chính sách rõ: bỏ có ghi nhận, đưa vào luồng riêng, hoặc hiệu chỉnh về sau; **bỏ im lặng là chế độ hỏng**.",
"Đo đánh đổi giữa độ trễ và tính đầy đủ theo ba mức mốc nước và áp chính sách rõ cho sự kiện quá muộn.",
"Tầng *đánh giá*. Objective đòi chọn tham số từ số đo chứ từ giá trị mặc định. Kiểm bằng ba mức mốc nước; đạt khi mỗi mức có cặp số độ trễ với tỉ lệ sự kiện bị bỏ, và sự kiện quá muộn không bị bỏ im lặng.",
"Sinh dòng sự kiện có phân bố độ trễ thực tế gồm một phần đuôi rất muộn. Chạy với ba mức mốc nước; với mỗi mức, đo độ trễ tới khi có kết quả, tỉ lệ sự kiện bị bỏ, và kích thước trạng thái. Chọn một mức và nêu lý do. Cài chính sách cho sự kiện quá muộn và chứng minh chúng được đếm và ghi nhận chứ bỏ.",
"Xử lý theo thời gian tới rồi chạy lại ra kết quả khác · đặt mốc nước theo giá trị mặc định · bỏ sự kiện muộn im lặng · bỏ qua ảnh hưởng của mốc nước lên kích thước trạng thái.",
"Ba mức mốc nước có cặp số độ trễ với tỉ lệ bỏ cùng kích thước trạng thái, và sự kiện quá muộn được đếm và ghi nhận."),

(358,"Choosing among four engine classes - distributed, embedded and in-process","TH","Lesson 357",
"Bài mở rộng phạm vi chọn engine ra bốn lớp, vì hai engine phân tán không phải lựa chọn duy nhất và thường không phải lựa chọn đúng. Engine dòng chảy thứ hai học tới mức hiểu kiến trúc và khác biệt, đi sâu chỉ khi công việc yêu cầu. Khác biệt nền tảng: nó xử lý từng bản ghi thay vì theo lô nhỏ, nên độ trễ thấp hơn đáng kể, đổi lại mô hình vận hành phức tạp hơn. Đồ thị toán tử, khe tác vụ và mức song song; nhóm khoá quyết định trạng thái được chia thế nào và quyết định mức song song đổi được tới đâu. Trạng thái theo khoá và trạng thái theo toán tử. Điểm kiểm tra dùng rào chắn chèn vào dòng: khi rào chắn đi qua mọi toán tử thì một ảnh chụp nhất quán được tạo mà không cần dừng dòng; chế độ căn chỉnh và không căn chỉnh khác nhau ở độ trễ dưới áp lực ngược. **Điểm lưu khác điểm kiểm tra ở mục đích: điểm kiểm tra do hệ tạo để phục hồi tự động, điểm lưu do người tạo để nâng cấp và di trú.** Áp lực ngược lan ngược về nguồn và làm điểm kiểm tra chậm hoặc hết giờ. Lớp thứ ba và thứ tư là engine chạy trên một máy, véctơ hoá theo lesson 208: một thư viện khung dữ liệu và một engine phân tích nhúng. **Với dữ liệu vừa bộ nhớ hoặc vừa đĩa của một máy, chúng thường nhanh hơn engine phân tán** vì không có chi phí xáo trộn, chi phí tuần tự hoá và chi phí lập lịch; ngưỡng chuyển sang phân tán phải đo chứ đoán. Mô hình lập trình theo đồ thị tính toán có nhiều bộ chạy chỉ cần biết là có. Quy tắc chọn: **engine đơn giản nhất còn đáp ứng được dữ liệu và độ trễ là engine đúng.**",
"So bốn lớp engine theo năm tiêu chí và chọn đúng cho ba bối cảnh, phân biệt điểm kiểm tra với điểm lưu.",
"Tầng *đánh giá*. Objective chống lại việc mặc định chọn engine phân tán. Kiểm bằng bảng bốn lớp nhân năm tiêu chí cộng một phép đo; đạt khi ba bối cảnh chọn đúng, ít nhất một bối cảnh chọn engine một máy, và ngưỡng chuyển sang phân tán có số đo.",
"So bốn lớp engine theo độ trễ, quy mô dữ liệu, mô hình trạng thái, chi phí vận hành và hệ sinh thái. Chạy một công việc đếm theo cửa sổ trên engine dòng chảy, giết một tiến trình quản lý tác vụ và khôi phục từ điểm kiểm tra; tạo một điểm lưu, đổi mức song song rồi khôi phục từ điểm lưu. Chạy **cùng một phép tổng hợp trên cả engine phân tán lẫn hai engine một máy** với ba kích thước dữ liệu tăng dần; tìm kích thước mà engine phân tán bắt đầu thắng. Cho ba bối cảnh khác nhau về quy mô và độ trễ, chọn engine cho từng cái.",
"Chọn engine theo độ phổ biến · **dùng engine phân tán cho dữ liệu vừa một máy** · nhầm điểm lưu với điểm kiểm tra · học sâu cả hai engine phân tán cùng lúc · bỏ qua chi phí vận hành khi so.",
"Bảng bốn lớp nhân năm tiêu chí có luận điểm kèm quan sát từ lab, ngưỡng chuyển sang engine phân tán có số đo từ ba kích thước dữ liệu, ba bối cảnh chọn đúng với ít nhất một chọn engine một máy, và khôi phục từ cả điểm kiểm tra lẫn điểm lưu thành công."),

(359,"End-to-end guarantee - source replay, state restore and sink","TH","Lesson 358",
"Bài phát biểu chính xác bảo đảm đầu cuối của một đường dòng chảy, và nó là bài chống lại tuyên bố mơ hồ. Bảo đảm đầu cuối là tích của ba điều kiện chứ một tính năng bật được: nguồn phải phát lại được từ một vị trí; trạng thái phải khôi phục được nhất quán với vị trí đó; và đích phải luỹ đẳng hoặc có giao dịch. **Thiếu một trong ba thì không có bảo đảm, dù engine có cờ nào bật đi nữa**; và đích là mắt xích hay bị bỏ quên nhất. Ba loại đích và cách đạt: đích có giao dịch thì chốt cùng tiến độ; đích luỹ đẳng theo khoá thì ghi đè an toàn; đích chỉ thêm mới thì không đạt được và phải chấp nhận trùng. Ghi ra hệ ngoài như gửi thư hoặc gọi dịch vụ là tác dụng phụ không hoàn tác được, nên nó luôn là ít nhất một lần. Phát biểu bảo đảm phải nêu nguồn, đích và giả định lỗi, theo lesson 326.",
"Phát biểu bảo đảm đầu cuối cho ba cấu hình và chứng minh bằng thí nghiệm giết có đối soát.",
"Tầng *đánh giá*. Objective đòi phát biểu có điều kiện thay vì tuyên bố. Kiểm bằng ba cấu hình đích; đạt khi phát biểu khớp kết quả đo ở cả ba và cấu hình đích chỉ thêm mới được nêu rõ không đạt được đúng một lần.",
"Dựng cùng một đường dòng chảy với ba loại đích. Với mỗi cái, phát biểu bảo đảm đầu cuối trước khi thử. Giết tiến trình 50 lần ở các ranh giới khác nhau; đếm bản ghi mất và trùng ở đích rồi đối chiếu với phát biểu. Thêm một bước gọi dịch vụ ngoài và chỉ ra vì sao nó luôn là ít nhất một lần.",
"Tuyên bố đúng một lần vì engine hỗ trợ · bỏ qua đích khi phát biểu bảo đảm · dùng đích chỉ thêm mới rồi mong không trùng · không nêu giả định lỗi.",
"Phát biểu khớp kết quả đo ở cả ba cấu hình sau 50 lần giết, và cấu hình đích chỉ thêm mới được nêu rõ giới hạn."),

(360,"Gate 8 - defend a delivery semantic and recover a stateful job","KT","Lesson 359",
"Cổng của Phase 8. Bài kiểm bốn module: nền tảng hệ phân tán ở M15, nhật ký phân tán ở M16, bắt thay đổi ở M17, và engine tính toán ở M18. Không có nội dung mới.",
"Phát biểu và bảo vệ một bảo đảm giao nhận có nêu ranh giới, phục hồi một công việc có trạng thái, và giải thích song song lồng nhau bằng số đo.",
"Tầng *đánh giá*. Cổng đo năng lực lập luận về bảo đảm và năng lực vận hành dưới hỏng, nên hình thức là thực hành tại chỗ cộng bảo vệ.",
"Buổi 180 phút: 135 phút làm bài độc lập, 45 phút chữa bài. Bài chấm sáu phần: A (20đ) cho một lịch sử thao tác, xác định mô hình nhất quán bị vi phạm kèm chuỗi chứng minh · B (20đ) phát biểu bảo đảm giao nhận đầu cuối của một đường cho trước, nêu nguồn, đích và giả định lỗi, rồi tính số bản trùng và lượng mất tối đa · C (15đ) tái hiện và sửa một ca người dẫn cũ quay lại bằng thẻ chặn · D (20đ) một công việc dòng có trạng thái bị giết; khôi phục từ điểm kiểm tra và đối soát · E (15đ) truy ba tầng song song trên một công việc và quy một mức tăng về đúng tầng · F (10đ) chẩn đoán một công việc chậm và đề xuất đúng một thay đổi có kiểm soát.",
"Coi hết giờ là bên kia đã hỏng · nói đúng một lần mà không nêu ranh giới · đặt lại vị trí tiêu thụ về cuối để phục hồi · đổi cấu hình bộ nhớ trước khi đọc kế hoạch.",
"Đạt ≥ 70/100, phần B và D đều ≥ 60%. Tuyên bố đúng một lần không nêu nguồn, đích và giả định lỗi thì phần B bằng không; phục hồi bằng cách đặt lại vị trí về cuối thì phần D bằng không."),
]
