# -*- coding: utf-8 -*-
"""ADE Phase 5: M11 Data modeling + M11B Semantic layer + M11C Analytical data product."""

M11 = ("Data Modeling - Operational, Analytical and Domain", 149, 164, """| | |
|---|---|
| **Objective cấp module** | Chọn hạt, khoá, cách lưu lịch sử và phương pháp mô hình hoá dựa trên khối lượng công việc, yêu cầu quản trị và khả năng tiến hoá |
| **Tiền đề** | M9 · M10 |
| **Exit criterion** | Mọi bảng sự kiện phát biểu hạt bằng một câu không mơ hồ; phép kết không đổi hạt ngoài ý muốn; chọn phương pháp theo chi phí thay đổi, kiểm toán, truy vấn và đội |
| **Kỹ năng SFIA** | `DATM` mức 4 · `DTAN` mức 4 |
| **Chế độ hỏng** | Vẽ lược đồ sao theo mẫu có sẵn mà không phát biểu hạt, rồi phép kết nhân dòng và mọi chỉ số bị thổi phồng mà không ai phát hiện |""",
"""Module này là bản lề của cả chương trình gộp: mọi thứ phía trước phục vụ nó, và M11B cùng M11C xây thẳng trên nó.

Khái niệm **hạt** đặt ở lesson 120 nay trở thành công cụ thiết kế chứ chỉ là kỷ luật viết truy vấn. Quy tắc giữ nguyên: một dòng đại diện cho cái gì, phát biểu bằng một câu, và phát biểu trước khi nghĩ tới cột.

Bốn phương pháp được dạy để **chọn**, không để áp dụng cả bốn: chuẩn hoá cho hệ giao dịch, mô hình chiều cho phân tích, Data Vault ở mức nhận ra, và bảng rộng cho tốc độ tiêu thụ.""")

L11 = [
(149,"From requirement to model - the seven-step protocol","LT","Module 11: M10",
"Bài mở module bằng một quy trình có thứ tự cố định, vì bỏ bước hoặc đảo bước là nguồn của phần lớn mô hình sai. Bảy bước: gọi tên quy trình nghiệp vụ và sự kiện, **phát biểu hạt trước khi nghĩ tới cột**, xác định danh tính tự nhiên và nhu cầu khoá thay thế, định nghĩa độ đo cùng chiều và ngữ nghĩa thời gian, mô hình hoá hiệu chỉnh cùng dữ liệu tới muộn cùng xoá, ánh xạ mẫu truy cập và khối lượng ghi đọc, rồi mới chọn phương pháp. Bước cuối nằm cuối là chủ ý: chọn phương pháp trước rồi ép bài toán vào nó là cách làm ra lược đồ sao cho một bài toán không phải phân tích. Ba câu hỏi phải trả lời được trước khi rời bước hai, vì hạt sai thì sáu bước sau đều sai theo. Nối với lesson 89: từ vựng miền là đầu vào của bước một.",
"Chạy đủ bảy bước trên một mô tả nghiệp vụ và dừng lại được ở bước hai với một phát biểu hạt không mơ hồ.",
"Tầng *áp dụng*. Bài mở module, áp một quy trình có sẵn vào tình huống mới. Kiểm bằng rà soát chéo phát biểu hạt; đạt khi hai người đọc cùng một phát biểu hiểu giống nhau ở cả ba mô tả nghiệp vụ.",
"Cho ba mô tả nghiệp vụ. Với mỗi cái, chạy đủ bảy bước và nộp kết quả từng bước. Đổi bài: người khác đọc phát biểu hạt của bạn và viết lại bằng lời của họ; nếu hai bản khác nghĩa thì phát biểu còn mơ hồ và phải sửa.",
"Nghĩ tới cột trước khi chốt hạt · chọn lược đồ sao rồi mới đọc yêu cầu · bỏ bước mô hình hoá hiệu chỉnh và dữ liệu tới muộn · viết hạt bằng một cụm danh từ thay vì một câu.",
"Ba phát biểu hạt đều được người đọc thứ hai diễn đạt lại đúng nghĩa, và cả bảy bước có kết quả ghi ra."),

(150,"Declaring the grain before the columns","TH","Lesson 149",
"Bài dành riêng cho bước hai vì nó là bước quyết định. Hạt là câu trả lời cho một dòng trong bảng này đại diện cho cái gì, và câu đó phải chặt tới mức không hai người hiểu khác nhau. Ba mức chặt và khác biệt hậu quả: một dòng là một đơn hàng, một dòng là một dòng hàng trong đơn, một dòng là một lần thay đổi trạng thái của dòng hàng; ba mức cho ba bảng khác nhau và trộn chúng là gốc của mọi lỗi nhân dòng. Kiểm chứng hạt bằng thực nghiệm chứ bằng niềm tin: đếm dòng theo tập khoá được tuyên bố là duy nhất, và nếu có nhóm nào nhiều hơn một dòng thì hạt đã phát biểu sai. Hạt và khoá liên quan nhưng khác nhau: khoá là cách nhận dạng một dòng, hạt là ý nghĩa của một dòng. Phép kết đổi hạt là hiện tượng đã gặp ở lesson 119, nay có tên gọi và có cách chặn.",
"Phát biểu hạt cho năm bảng và kiểm chứng từng phát biểu bằng phép đếm trên dữ liệu thật.",
"Tầng *áp dụng*. Objective có phép kiểm chứng khách quan bằng truy vấn, chứ dựa vào cảm nhận. Kiểm bằng phép đếm trùng; đạt khi cả năm phát biểu được dữ liệu xác nhận hoặc bị bác bỏ và sửa lại đúng.",
"Cho năm bảng có dữ liệu thật, không kèm tài liệu. Với mỗi bảng, suy ra hạt từ dữ liệu, viết phát biểu, rồi kiểm bằng cách đếm dòng theo tập khoá tuyên bố. Với bảng nào phát biểu sai, sửa lại và kiểm lần nữa. Ghi lại bảng nào có hạt khác với tên bảng gợi ý.",
"Tin tên bảng nói đúng hạt · phát biểu hạt rồi không kiểm bằng dữ liệu · nhầm hạt với khoá chính · chấp nhận phát biểu có từ mơ hồ như thông tin hay dữ liệu.",
"Cả năm phát biểu được kiểm bằng phép đếm, và mọi phát biểu sai đều được phát hiện rồi sửa đúng."),

(151,"Conceptual, logical and physical models","LT","Lesson 150",
"Ba tầng mô hình phục vụ ba người đọc khác nhau, và trộn chúng làm cả ba không dùng được. Mô hình khái niệm nói về khái niệm nghiệp vụ và quan hệ giữa chúng, không có kiểu dữ liệu, dùng để thống nhất với người nghiệp vụ. Mô hình logic có thuộc tính, khoá và ràng buộc, chưa gắn với hệ cụ thể. Mô hình vật lý có kiểu dữ liệu, chỉ mục, phân vùng và quyết định lưu trữ, gắn chặt với engine. Từ đó suy ra một quy tắc thực dụng: đổi engine chỉ nên ảnh hưởng tầng vật lý; nếu phải sửa cả tầng logic thì mô hình đã lẫn tầng. Chuẩn hoá theo lesson 117 là quyết định ở tầng logic, còn phi chuẩn hoá thường là quyết định ở tầng vật lý cho một đường đọc cụ thể. Ba sai lầm khi vẽ sơ đồ quan hệ cho người nghiệp vụ xem.",
"Tách một mô hình lẫn tầng thành ba tầng và chỉ ra quyết định nào thuộc tầng nào.",
"Tầng *hiểu*. Bài lý thuyết đặt khung cho phần còn lại của module. Kiểm bằng bài phân tầng 15 quyết định; đạt khi phân đúng ít nhất 12 và giải thích được ba quyết định biên.",
"Cho một tài liệu thiết kế lẫn cả ba tầng. Tách thành ba mô hình riêng. Cho 15 quyết định thiết kế cụ thể và phân mỗi cái vào một tầng. Với ba quyết định nằm ở ranh giới, viết một câu giải thích vì sao đặt ở tầng đó.",
"Đưa kiểu dữ liệu vào mô hình khái niệm · đưa quyết định chỉ mục vào mô hình logic · vẽ một sơ đồ duy nhất rồi dùng cho cả ba người đọc.",
"Phân đúng ≥ 12/15 quyết định vào tầng, và ba quyết định biên có giải thích hợp lý."),

(152,"Keys - natural, surrogate and identity over time","TH","Lesson 151",
"Khoá tự nhiên đến từ nghiệp vụ, khoá thay thế do hệ sinh ra, và chọn sai gây hậu quả kéo dài. Ba lý do kho phân tích cần khoá thay thế: khoá tự nhiên có thể đổi, có thể trùng giữa các nguồn, và có thể rất dài nên tốn khi kết. Nhưng khoá thay thế không thay thế khoá tự nhiên mà đi kèm: **khoá nghiệp vụ vẫn phải lưu và vẫn phải có ràng buộc duy nhất**, vì đối soát với nguồn dựa trên nó chứ trên số do ta tự sinh. Phạm vi duy nhất theo thời gian là chỗ tinh vi: một mã khách duy nhất tại một thời điểm nhưng có thể được cấp lại sau khi khách cũ đóng tài khoản, nên duy nhất theo thời gian khác duy nhất tuyệt đối. Khoá băm và đánh đổi: tiện vì tính được ở nhiều nơi, rủi ro khi thành phần băm có giá trị thiếu vì kết quả không xác định. Danh tính tách và gộp: khi hai bản ghi hoá ra là một người, hoặc một bản ghi hoá ra là hai.",
"Thiết kế bộ khoá cho một bảng chiều có danh tính đổi theo thời gian và xử lý được một lần gộp danh tính.",
"Tầng *áp dụng*. Objective là một thiết kế có ca biên cụ thể kiểm được. Kiểm bằng ba ca biên; đạt khi cả ba được xử lý đúng và đối soát theo khoá nghiệp vụ vẫn khớp sau khi gộp.",
"Thiết kế khoá cho bảng chiều khách hàng. Xử lý ba ca: mã khách đổi, mã khách được cấp lại cho người khác, và hai bản ghi được xác định là cùng một người. Với mỗi ca, chứng minh dữ liệu lịch sử vẫn truy được và đối soát theo khoá nghiệp vụ vẫn khớp.",
"Bỏ khoá nghiệp vụ vì đã có khoá thay thế · băm từ cột có thể thiếu giá trị · giả định mã nghiệp vụ không bao giờ được cấp lại · xử lý gộp danh tính bằng cách xoá một bản ghi.",
"Ba ca biên được xử lý đúng, dữ liệu lịch sử vẫn truy được, và đối soát theo khoá nghiệp vụ khớp sau khi gộp."),

(153,"Dimensional modelling - facts, dimensions and the bus matrix","LT","Lesson 152",
"Mô hình chiều tối ưu cho việc đọc và cho việc người không chuyên hiểu được, nên nó là dạng chính của tầng phục vụ. Bảng sự kiện chứa khoá ngoại và độ đo, không chứa thuộc tính mô tả; bảng chiều rộng, phi chuẩn hoá, giàu thuộc tính, và **cố ý lặp dữ liệu** vì lặp ở chiều rẻ hơn nhiều so với phải kết thêm bảng. Đây là chỗ mâu thuẫn có chủ đích với chuẩn hoá ở lesson 117, và lý do là hai hệ tối ưu cho hai việc khác nhau. Ma trận xe buýt: bảng liệt kê quy trình nghiệp vụ theo hàng và chiều theo cột, đánh dấu chiều nào dùng ở quy trình nào; nó là công cụ lập kế hoạch cho cả kho chứ chỉ cho một mart. Chiều dùng chung là khái niệm quan trọng nhất của ma trận: cùng một bảng chiều dùng ở nhiều bảng sự kiện thì hai mart so sánh được với nhau; thiếu nó thì mỗi phòng một con số.",
"Dựng ma trận xe buýt cho một miền nghiệp vụ và chỉ ra chiều nào phải dùng chung.",
"Tầng *hiểu*. Bài lý thuyết đặt khung cho bốn bài thực hành sau. Kiểm bằng ma trận cộng bài lập luận; đạt khi ma trận phủ đủ quy trình và chỉ đúng ít nhất ba chiều phải dùng chung kèm hậu quả nếu không.",
"Từ mô tả một doanh nghiệp bán lẻ, liệt kê sáu quy trình nghiệp vụ và các chiều. Dựng ma trận xe buýt. Chỉ ra chiều nào dùng ở nhiều quy trình và phải dùng chung. Với một chiều, mô tả cụ thể chuyện gì xảy ra nếu hai mart tự dựng bản riêng.",
"Đưa thuộc tính mô tả vào bảng sự kiện · chuẩn hoá bảng chiều vì thấy lặp dữ liệu · dựng mart rời nhau không có chiều dùng chung · vẽ ma trận mà không xác định quy trình nghiệp vụ trước.",
"Ma trận phủ đủ sáu quy trình, chỉ đúng ≥ 3 chiều phải dùng chung, và mô tả được hậu quả cụ thể khi không dùng chung."),

(154,"Fact types - transaction, periodic and accumulating snapshot","TH","Lesson 153",
"Ba loại bảng sự kiện trả lời ba loại câu hỏi, và chọn sai loại là không trả lời được câu hỏi chứ chỉ chậm. Bảng giao dịch: một dòng một sự kiện xảy ra, hạt mịn nhất, trả lời câu hỏi chuyện gì đã xảy ra. Bảng ảnh chụp định kỳ: một dòng một thực thể tại một kỳ, dùng cho số dư và tồn kho tức những đại lượng không cộng được theo thời gian. Bảng ảnh chụp tích luỹ: một dòng một quy trình có nhiều mốc, mỗi mốc một cột thời gian, và dòng được cập nhật khi quy trình tiến triển; dùng cho vòng đời đơn hàng và để tính thời gian giữa các mốc. Loại thứ ba là loại khác biệt nhất vì nó **cập nhật dòng đã tồn tại** thay vì chỉ thêm, nên kéo theo yêu cầu về ghi bất biến và về chạy bù. Bảng sự kiện không độ đo cho việc đếm sự kiện hoặc ghi nhận quan hệ.",
"Chọn đúng loại bảng sự kiện cho bốn câu hỏi nghiệp vụ và dựng được một bảng ảnh chụp tích luỹ có chạy bù.",
"Tầng *áp dụng*. Objective là chọn theo câu hỏi rồi cài đặt loại khó nhất. Kiểm bằng bốn câu hỏi cộng bài dựng; đạt khi chọn đúng cả bốn và bảng tích luỹ chạy bù cho kết quả khớp tuyệt đối.",
"Cho bốn câu hỏi nghiệp vụ. Chọn loại bảng sự kiện cho từng câu kèm lý do. Dựng bảng ảnh chụp tích luỹ cho vòng đời đơn hàng với năm mốc. Chạy bù 30 ngày và đối soát với bản chạy tuần tự. Tính thời gian trung bình giữa hai mốc bất kỳ.",
"Dùng bảng giao dịch cho câu hỏi về số dư · dựng bảng tích luỹ mà không bất biến khi chạy lại · trộn hai loại vào một bảng · quên rằng số dư không cộng được theo thời gian.",
"Chọn đúng cả bốn câu hỏi, và bảng tích luỹ chạy bù 30 ngày đối soát khớp tuyệt đối."),

(155,"Additivity - additive, semi-additive and non-additive measures","TH","Lesson 154",
"Phân loại quyết định độ đo được phép cộng theo chiều nào, và bỏ qua nó là nguồn của những con số sai mà trông hợp lý. Cộng được hoàn toàn: doanh thu cộng được theo mọi chiều gồm cả thời gian. Cộng được một phần: số dư và tồn kho cộng được theo chiều khác nhưng **không cộng được theo thời gian**, vì cộng số dư của mười hai tháng không ra số dư năm; cách xử lý đúng là lấy giá trị cuối kỳ hoặc trung bình. Không cộng được: tỉ lệ và phần trăm, vì trung bình của các tỉ lệ khác tỉ lệ của các tổng. Quy tắc vàng cho loại thứ ba và là quy tắc được dùng lại ở M11B: **lưu tử số và mẫu số riêng, tính tỉ lệ ở bước cuối**; lưu sẵn tỉ lệ rồi cộng lại là lỗi sai số liệu âm thầm phổ biến nhất trong kho dữ liệu. Đếm giá trị phân biệt cũng không cộng được, và đây là chỗ nhiều công cụ làm sai âm thầm.",
"Phân loại độ đo theo ba nhóm và chứng minh bằng số rằng cộng sai nhóm cho ra kết quả sai.",
"Tầng *phân tích*. Objective đòi nhận ra một lỗi không báo lỗi, nên phải chứng minh bằng đối chứng số. Kiểm bằng ba phép cộng sai; đạt khi định lượng được mức sai ở cả ba và đề xuất cách lưu đúng.",
"Cho mười độ đo, phân vào ba nhóm. Với ba độ đo không cộng được hoặc cộng được một phần, tính theo cách sai và cách đúng rồi so số. Thiết kế lại cách lưu cho một tỉ lệ theo quy tắc tử số mẫu số riêng và chứng minh nó gộp đúng ở mọi mức.",
"Cộng số dư theo thời gian · lưu sẵn tỉ lệ trong bảng sự kiện · trung bình các tỉ lệ · giả định đếm giá trị phân biệt cộng được.",
"Mười độ đo phân đúng nhóm, ba phép cộng sai được định lượng mức sai, và bản lưu tử số mẫu số gộp đúng ở mọi mức."),

(156,"Dimension patterns - role-playing, junk, degenerate and bridge","TH","Lesson 155",
"Bốn mẫu bảng chiều giải bốn vấn đề cụ thể, học để nhận ra chứ để nhồi vào mọi thiết kế. Chiều vai trò: cùng một bảng chiều dùng ở nhiều vai trong một bảng sự kiện, ví dụ ngày đặt và ngày giao cùng trỏ bảng lịch; cách hiện thực là tạo khung nhìn đặt tên theo vai để truy vấn đọc được. Chiều rác: gom nhiều cờ và mã nhỏ lẻ vào một bảng thay vì để mỗi cái một chiều, tránh bảng sự kiện có hai mươi khoá ngoại. Chiều suy biến: khoá nghiệp vụ như mã hoá đơn nằm thẳng trong bảng sự kiện vì nó không có thuộc tính nào khác. Bảng cầu cho quan hệ nhiều nhiều và cho phân cấp có độ sâu thay đổi; **đây là mẫu nguy hiểm nhất vì nó nhân dòng theo thiết kế**, nên mọi phép gộp qua bảng cầu phải có hệ số phân bổ, nếu không thì đếm trùng.",
"Nhận ra bốn mẫu trong một lược đồ cho trước và xử lý đúng phép gộp qua bảng cầu để không đếm trùng.",
"Tầng *áp dụng*. Objective gồm một ca dễ sai âm thầm là bảng cầu. Kiểm bằng bài nhận dạng cộng phép đối soát; đạt khi nhận đúng ít nhất ba mẫu và tổng qua bảng cầu khớp tổng thật.",
"Cho một lược đồ có cả bốn mẫu. Nhận dạng từng cái. Viết truy vấn gộp qua bảng cầu theo hai cách: không có hệ số phân bổ và có hệ số; so hai kết quả với tổng thật. Tạo khung nhìn chiều vai trò cho ngày đặt và ngày giao.",
"Gộp qua bảng cầu mà không phân bổ · tạo một chiều riêng cho mỗi cờ nhị phân · tách mã hoá đơn thành một chiều không có thuộc tính · dùng cùng tên cột cho hai vai của một chiều.",
"Nhận đúng ≥ 3/4 mẫu, và tổng gộp qua bảng cầu có hệ số phân bổ khớp tổng thật."),

(157,"Slowly changing dimensions, type 0 to type 6","TH","Lesson 156",
"Thuộc tính chiều đổi theo thời gian, và cách xử lý quyết định báo cáo lịch sử đúng hay sai. Bài toán cụ thể: khách chuyển từ vùng bắc sang vùng nam; nếu ghi đè thì **toàn bộ doanh thu lịch sử của khách đó nhảy sang vùng mới** và báo cáo năm ngoái đổi số dù không ai sửa dữ liệu bán hàng. Các loại và hậu quả báo cáo của từng loại: loại không giữ nguyên giá trị đầu, loại một ghi đè nên mất lịch sử, loại hai thêm dòng mới nên giữ đủ lịch sử và là loại dùng nhiều nhất, loại ba giữ một giá trị trước, loại sáu kết hợp. Cài đặt loại hai: khoá thay thế, hai cột hiệu lực, cờ bản ghi hiện hành, và quy trình tải gồm phát hiện thay đổi, đóng dòng cũ, mở dòng mới. Hai phép kiểm bắt buộc: không có khoảng hiệu lực chồng nhau, và mỗi khoá nghiệp vụ có đúng một dòng hiện hành.",
"Cài đặt chiều biến đổi chậm loại hai đạt hai bất biến, và định lượng sai lệch báo cáo nếu dùng loại một.",
"Tầng *áp dụng*. Objective là một cài đặt có hai bất biến kiểm được bằng truy vấn. Kiểm bằng hai phép kiểm bất biến cộng đối chứng; đạt khi cả hai bất biến giữ được qua 1000 lần cập nhật và sai lệch của loại một được định lượng.",
"Cài chiều khách hàng loại hai. Chạy 1000 lần cập nhật thuộc tính, gồm cả cập nhật tới muộn và cập nhật hiệu chỉnh. Chạy hai phép kiểm bất biến. Dựng cùng báo cáo doanh thu theo vùng trên bản loại một và bản loại hai, so hai kết quả cho kỳ lịch sử.",
"Ghi đè thuộc tính rồi mất lịch sử · để khoảng hiệu lực chồng nhau · có hai dòng cùng đánh dấu hiện hành · quên xử lý cập nhật tới muộn nên chèn sai thứ tự.",
"Hai bất biến giữ được qua 1000 lần cập nhật, và chênh lệch báo cáo giữa loại một và loại hai được định lượng."),

(158,"Valid time, system time, corrections and restatement","TH","Lesson 157",
"Hai trục thời gian trả lời hai câu hỏi khác nhau và trộn chúng làm không trả lời được câu nào. Thời gian hiệu lực là khoảng mà sự thật đúng trong thế giới; thời gian hệ thống là khoảng mà hệ của ta tin điều đó. Ví dụ phân biệt: khách đổi địa chỉ từ ngày mùng một nhưng hệ chỉ biết vào ngày mười; hai trục cho hai câu trả lời khác nhau cho câu hỏi ngày năm khách ở đâu. Từ đó suy ra hai loại câu hỏi mà một hệ trưởng thành phải trả lời được: tình trạng thật tại một thời điểm, và **báo cáo đã in ra hôm đó dựa trên dữ liệu nào**; câu thứ hai là yêu cầu kiểm toán và chỉ trả lời được nếu có trục thời gian hệ thống. Hiệu chỉnh và trình bày lại: khi dữ liệu cũ sai và được sửa, báo cáo đã công bố đổi theo hay giữ nguyên là quyết định nghiệp vụ chứ kỹ thuật, và phải thoả thuận trước.",
"Trả lời được cả hai loại câu hỏi thời gian trên cùng một tập dữ liệu và nêu chính sách hiệu chỉnh.",
"Tầng *đánh giá*. Objective đòi phân biệt hai trục và nhận ra đây là quyết định có bên liên quan. Kiểm bằng bốn câu hỏi hai loại; đạt khi trả lời đúng ít nhất ba và chính sách hiệu chỉnh nêu rõ ai quyết.",
"Dựng bảng có cả hai trục thời gian. Tạo một chuỗi sự kiện gồm một lần biết muộn và một lần hiệu chỉnh dữ liệu sai. Trả lời bốn câu hỏi: hai câu về tình trạng thật và hai câu về báo cáo đã công bố. Viết chính sách hiệu chỉnh nêu rõ số đã công bố có đổi không và ai quyết.",
"Chỉ lưu một trục thời gian · sửa dữ liệu cũ mà không ghi lại đã sửa · đổi số đã công bố mà không báo bên dùng · coi chính sách hiệu chỉnh là quyết định kỹ thuật.",
"Trả lời đúng ≥ 3/4 câu hỏi hai loại, và chính sách hiệu chỉnh nêu rõ hành vi cùng người quyết."),

(159,"Star, snowflake and the one-big-table trade-off","TH","Lesson 158",
"Ba cách bố trí tầng phục vụ, so bằng bốn tiêu chí chứ bằng sở thích. Lược đồ sao: bảng chiều phi chuẩn hoá, ít phép kết, dễ hiểu với người dùng cuối, tốn dung lượng do lặp. Bông tuyết: chiều được chuẩn hoá thành nhiều bảng, tiết kiệm dung lượng, thêm phép kết và khó hiểu hơn; hiếm khi đáng ở kho hiện đại vì dung lượng rẻ còn phép kết thì không. Bảng rộng gộp tất cả vào một bảng: nhanh nhất cho người tiêu thụ và không thể kết sai, đổi lại lặp dữ liệu nhiều, khó quản trị khi một định nghĩa đổi, và mất tính linh hoạt khi cần chiều mới. Bốn tiêu chí so: tốc độ truy vấn, dung lượng, chi phí thay đổi định nghĩa, và mức dễ hiểu với người dùng. Khi nào bảng rộng là lựa chọn đúng: đường tiêu thụ cố định, số người dùng lớn, và có tầng ngữ nghĩa ở trên giữ định nghĩa, tức chính bối cảnh của M11B.",
"So ba bố trí trên cùng dữ liệu theo bốn tiêu chí và chọn một kèm điều kiện làm lựa chọn đó sai.",
"Tầng *đánh giá*. Objective đòi so đa tiêu chí có số đo chứ theo quy tắc chung. Kiểm bằng bảng ba bố trí nhân bốn tiêu chí; đạt khi hai tiêu chí đầu có số đo thật và lựa chọn có hai điều kiện đảo ngược.",
"Dựng cùng dữ liệu ở cả ba bố trí. Chạy bộ năm truy vấn chuẩn và đo thời gian cùng dung lượng. Ước lượng chi phí thay đổi bằng cách đếm số chỗ phải sửa khi đổi một định nghĩa. Khảo sát mức dễ hiểu bằng cách nhờ một người chưa biết lược đồ viết một truy vấn và tính giờ.",
"Chọn bông tuyết để tiết kiệm dung lượng mà không đo phép kết thêm · dựng bảng rộng mà không có tầng giữ định nghĩa · so ba bố trí chỉ bằng tốc độ.",
"Bảng ba bố trí nhân bốn tiêu chí có số ở hai tiêu chí đầu, và lựa chọn kèm hai điều kiện đảo ngược cụ thể."),

(160,"Data Vault at a level sufficient to recognise it","LT","Lesson 159",
"Phương pháp thứ ba, dạy ở mức nhận ra và đánh giá chứ mức triển khai, vì phần lớn đội không cần nó. Ba thành phần: trung tâm giữ khoá nghiệp vụ, liên kết giữ quan hệ giữa các trung tâm, vệ tinh giữ thuộc tính có lịch sử. Bất biến khi tải và lý do thiết kế: mọi thứ chỉ thêm chứ sửa, nên tải song song được và giữ đủ dấu vết kiểm toán. Điểm mạnh thật: chịu được nguồn đổi lược đồ thường xuyên và yêu cầu kiểm toán chặt, vì không bao giờ mất dữ liệu gốc. Điểm yếu thật và lý do ít dùng: số bảng nhân lên nhiều lần, truy vấn phải kết rất nhiều, nên **luôn cần một tầng phục vụ dạng chiều ở trên** và đội phải nuôi hai tầng. Hai câu hỏi quyết định có nên dùng. Ba dấu hiệu một dự án đang dùng nó vì nghe chuyên nghiệp chứ vì ràng buộc thật.",
"Nhận ra cấu trúc này trong một lược đồ và đánh giá nó có phù hợp một bối cảnh cho trước không.",
"Tầng *đánh giá*. Objective là năng lực đánh giá chứ triển khai, đúng phạm vi bản nguồn đặt ra. Kiểm bằng ba bối cảnh; đạt khi quyết định đúng cả ba và nêu đúng chi phí kéo theo ở bối cảnh chọn dùng.",
"Cho một lược đồ đã dựng theo phương pháp này; nhận dạng ba thành phần và viết một truy vấn lấy thông tin khách hàng hiện hành, đếm số phép kết cần. Cho ba bối cảnh khác nhau về tần suất đổi lược đồ nguồn, yêu cầu kiểm toán và quy mô đội; quyết định có dùng không.",
"Chọn vì nghe chuyên nghiệp · dùng mà không dựng tầng phục vụ ở trên · nghĩ nó thay thế mô hình chiều · bỏ qua chi phí nuôi hai tầng.",
"Nhận đúng ba thành phần kèm số phép kết đo được, và quyết định đúng cả ba bối cảnh kèm chi phí kéo theo."),

(161,"Domain modelling, bounded context and the canonical-model trap","LT","Lesson 160",
"Góc nhìn thứ tư, đến từ thiết kế phần mềm và quan trọng khi dữ liệu đến từ nhiều đội. Ngữ cảnh giới hạn: cùng một từ có nghĩa khác nhau ở hai đội, và ép chúng dùng chung một định nghĩa thường thất bại; ví dụ khách hàng với đội bán hàng là người ký hợp đồng, với đội hỗ trợ là người gọi lên. Cái bẫy mô hình chuẩn chung: cố xây một mô hình duy nhất đúng cho cả công ty; nó tốn nhiều năm, không bao giờ xong, và chặn mọi đội. Cách đúng theo bản nguồn: **tích hợp ở mức hợp đồng chứ ở mức mô hình chung**, tức mỗi miền giữ mô hình riêng và công bố một hợp đồng ổn định ra ngoài. Sở hữu dữ liệu đi theo miền: đội sinh ra dữ liệu chịu trách nhiệm về nó. Quan hệ với M14D: từ điển thuật ngữ ghi lại việc một từ có nhiều nghĩa theo ngữ cảnh thay vì ép một nghĩa.",
"Nhận ra hai ngữ cảnh giới hạn xung đột nhau trong một mô tả và đề xuất cách tích hợp bằng hợp đồng.",
"Tầng *phân tích*. Objective đòi nhận ra xung đột ngữ nghĩa trước khi nó thành xung đột kỹ thuật. Kiểm bằng bài phân tích; đạt khi chỉ ra đúng ít nhất hai từ mang hai nghĩa và đề xuất hợp đồng thay vì mô hình chung.",
"Cho mô tả ba đội cùng dùng ba từ chung nhưng nghĩa khác nhau. Chỉ ra xung đột. Với mỗi từ, viết định nghĩa theo từng ngữ cảnh và một hợp đồng để hai bên trao đổi. Viết hai câu giải thích vì sao ép một định nghĩa chung sẽ thất bại ở đây.",
"Ép một định nghĩa chung cho cả công ty · đổi tên để né xung đột mà không giải quyết nghĩa · coi xung đột ngữ nghĩa là vấn đề kỹ thuật · bỏ qua ai sở hữu dữ liệu.",
"Chỉ đúng ≥ 2 từ mang hai nghĩa, và đề xuất tích hợp bằng hợp đồng kèm định nghĩa theo từng ngữ cảnh."),

(162,"Late arriving data, early arriving facts and the unknown member","TH","Lesson 161",
"Ba ca biên mà mọi mô hình thật đều gặp và mọi mô hình sách giáo khoa đều bỏ qua. Sự kiện tới trước chiều: một đơn hàng tham chiếu khách hàng chưa có trong bảng chiều; ba cách xử lý và hậu quả từng cách, trong đó cách sai phổ biến là bỏ dòng sự kiện đi và làm tổng thiếu mà không ai biết. Thành viên chưa biết: một dòng chiều đặc biệt để sự kiện luôn kết được, kèm ba biến thể mang ba nghĩa khác nhau là chưa biết, không áp dụng, và lỗi; gộp ba nghĩa là mất thông tin theo đúng bài học ở lesson 114. Chiều tới muộn: thuộc tính đúng chỉ biết sau khi sự kiện đã tải, nên phải sửa lại liên kết lịch sử; đây là chỗ khó nhất và liên quan trực tiếp tới loại hai ở lesson 157. Nguyên tắc chung: **không bao giờ bỏ dòng trong im lặng**, quy tắc sẽ được cưỡng chế ở M14C.",
"Xử lý đúng ba ca biên và chứng minh tổng không thiếu dòng nào so với nguồn.",
"Tầng *áp dụng*. Objective là ba ca biên có tiêu chí nghiệm thu bằng đối soát. Kiểm bằng đối soát tổng; đạt khi không dòng nào bị bỏ và ba nghĩa của thành viên chưa biết phân biệt được.",
"Tạo dữ liệu có cả ba ca biên. Xử lý từng ca. Đối soát tổng số dòng và tổng tiền với nguồn để chứng minh không mất dòng. Truy vấn phân biệt được ba nghĩa của thành viên chưa biết. Với ca chiều tới muộn, sửa lại liên kết lịch sử và đối soát báo cáo trước sau.",
"Bỏ dòng sự kiện không kết được · dùng một thành viên chưa biết cho cả ba nghĩa · để sự kiện tham chiếu khoá không tồn tại · sửa chiều tới muộn mà không sửa liên kết lịch sử.",
"Đối soát tổng khớp tuyệt đối với nguồn, ba nghĩa phân biệt được bằng truy vấn, và liên kết lịch sử sau khi sửa cho báo cáo đúng."),

(163,"Modelling for handover - what the consumer needs","TH","Lesson 162",
"Mô hình tốt về kỹ thuật vẫn vô dụng nếu người dùng không hiểu, nên bài này nhìn từ phía người tiêu thụ và là cầu nối sang M11C. Sáu thứ người tiêu thụ cần cùng với bảng: phát biểu hạt, định nghĩa từng độ đo gồm công thức và bộ lọc, ý nghĩa từng thuộc tính chiều, độ tươi và lịch làm mới, truy vấn mẫu cho ba câu hỏi thường gặp, và **hạn chế diễn giải** tức những kết luận mà dữ liệu này không cho phép rút ra. Phần cuối là phần hiếm ai viết và là phần chặn được nhiều kết luận sai nhất. Quy ước đặt tên nhất quán quan trọng hơn quy ước hoàn hảo, theo tinh thần đã nêu ở M7. Ba dấu hiệu mô hình chưa sẵn sàng bàn giao. Phép thử bàn giao ở đây là bản thu nhỏ của phép thử sẽ làm ở M11C: một người khác trả lời được ba câu hỏi nghiệp vụ chỉ bằng bảng và tài liệu.",
"Nộp bộ tài liệu sáu phần cho một mô hình và chứng minh người khác trả lời được ba câu hỏi mà không hỏi.",
"Tầng *đánh giá*. Objective đo chất lượng bàn giao bằng kết quả của người nhận. Kiểm bằng phép thử bàn giao; đạt khi người nhận trả lời đúng ít nhất hai trong ba câu hỏi mà không phải hỏi lại.",
"Viết bộ tài liệu sáu phần cho mô hình đã dựng. Đưa cho một học viên chưa xem mô hình cùng ba câu hỏi nghiệp vụ. Họ viết truy vấn và trả lời. Ghi lại mọi câu họ phải hỏi và mọi chỗ họ hiểu sai, rồi sửa tài liệu.",
"Bỏ phần hạn chế diễn giải · viết tài liệu cho người đã biết mô hình · đặt tên cột theo tên cột nguồn · không kèm truy vấn mẫu.",
"Người nhận trả lời đúng ≥ 2/3 câu hỏi mà không phải hỏi lại, và bộ tài liệu có đủ sáu phần gồm hạn chế diễn giải."),

(164,"Modelling project - four models, one decision matrix","DA","Lesson 163",
"Bài dự án khép module. Trên cùng một miền nghiệp vụ, dựng bốn mô hình: chuẩn hoá cho hệ giao dịch, mô hình chiều cho phân tích, phác thảo Data Vault, và một bảng rộng. Với mỗi mô hình, nộp phát biểu hạt cho mọi bảng sự kiện và một truy vấn trả lời cùng một câu hỏi nghiệp vụ. Sau đó lập ma trận quyết định bốn phương án nhân bốn tiêu chí ở lesson 159, mỗi ô có số đo hoặc ước lượng có căn cứ chứ tính từ. Kết luận: chọn một phương án cho một bối cảnh cho trước và **nêu ba điều kiện làm lựa chọn đó sai**. Yêu cầu bắt buộc: mô hình chiều phải cài loại hai theo lesson 157, xử lý đủ ba ca biên ở lesson 162, và kèm bộ tài liệu sáu phần theo lesson 163.",
"Nộp bốn mô hình có phát biểu hạt đầy đủ, một ma trận quyết định có số, và một khuyến nghị kèm điều kiện đảo ngược.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một quyết định thiết kế có bằng chứng. Kiểm bằng rà soát chéo cộng đối soát; đạt khi mọi bảng sự kiện có hạt kiểm được và ma trận không có ô nào chỉ có tính từ.",
"Dựng bốn mô hình trên cùng miền. Kiểm hạt bằng phép đếm theo lesson 150. Chạy cùng một truy vấn nghiệp vụ trên cả bốn và đối soát bốn kết quả phải khớp. Lập ma trận bốn nhân bốn. Viết khuyến nghị kèm ba điều kiện đảo ngược.",
"Bỏ phát biểu hạt ở một mô hình · để bốn mô hình cho bốn kết quả khác nhau mà không giải thích · điền ma trận bằng tính từ · khuyến nghị không có điều kiện đảo ngược.",
"Bốn mô hình cho cùng kết quả trên truy vấn đối chứng, mọi bảng sự kiện có hạt kiểm được, và ma trận không có ô nào thiếu số."),
]

M11B = ("Semantic Layer and Metrics Engineering", 165, 184, """| | |
|---|---|
| **Objective cấp module** | Thiết kế hợp đồng chỉ số không mơ hồ, dựng đồ thị ngữ nghĩa an toàn trước nhân dòng, và quản trị vòng đời chỉ số |
| **Tiền đề** | M11 |
| **Exit criterion** | 15 chỉ số thuộc ≥ 5 loại, mỗi cái có hợp đồng sáu phần, chủ sở hữu và phép kiểm; ≥ 3 mô hình ngữ nghĩa với chứng minh không nhân dòng cho truy vấn nhiều bước kết; bộ đối chứng phủ sáu ca; phục vụ hai bên tiêu thụ có bảo mật và cách ly đệm; một lần di trú phá vỡ hoàn tất với chạy song song và đối soát |
| **Kỹ năng SFIA** | `DATM` mức 5 · `DTAN` mức 4 |
| **Chế độ hỏng** | Cài công cụ tầng ngữ nghĩa rồi khai báo chỉ số theo bảng hiện có, không có hợp đồng và không đối soát, nên tầng mới trở thành một nguồn số sai mới có thẩm quyền |""",
"""**Đây là module đầu tiên thuộc phần bù Analytics Engineer.** Bản Data Engineer cũ không có nội dung này, và nó là một trong bốn lý do của việc gộp.

Thứ tự bắt buộc lấy từ hợp đồng nguồn: **nền ngữ nghĩa trước công cụ**. Ba bài đầu không mở công cụ nào, vì khai báo chỉ số bằng công cụ khi chưa có hợp đồng là cách nhân bản sự mơ hồ với tốc độ cao hơn.

Quy tắc hạt ở lesson 120 và quy tắc tử số mẫu số riêng ở lesson 155 được dùng lại liên tục trong module này.""")

L11B = [
(165,"The layers that must be distinguished","LT","Module 11B: M11",
"Bài mở module bằng việc tách năm thứ hay bị gọi lẫn, vì gọi lẫn thì không bàn được thiết kế. Bảng vật lý là nơi dữ liệu nằm. Mô hình mart là cách bảng được tổ chức cho một miền, nội dung của M11. Mô hình ngữ nghĩa là khai báo thực thể, chiều và độ đo cùng cách chúng nối nhau, không chứa dữ liệu. Chỉ số là một phép tính có tên, có hợp đồng, dựng trên mô hình ngữ nghĩa. Công cụ tiêu thụ là nơi người dùng đặt câu hỏi. Điểm quan trọng nhất và là lý do tầng ngữ nghĩa tồn tại: **định nghĩa chỉ số phải nằm ở một chỗ duy nhất, không nằm rải trong công cụ BI và trong từng truy vấn**; nằm rải thì mỗi chỗ một số. Ba triệu chứng của việc định nghĩa nằm rải, đã gặp dưới dạng khác trong tình huống bốn báo cáo bốn con số. Ranh giới với M11C: module này lo định nghĩa đúng, module sau lo người dùng dùng được.",
"Phân loại năm tầng cho một kiến trúc cho trước và chỉ ra định nghĩa chỉ số đang nằm ở đâu.",
"Tầng *hiểu*. Bài mở module, đặt từ vựng; chưa mở công cụ. Kiểm bằng bài phân tích ba kiến trúc; đạt khi phân đúng năm tầng ở ít nhất hai và chỉ ra đúng chỗ định nghĩa đang nằm rải.",
"Cho ba kiến trúc thật về mặt cấu trúc. Với mỗi cái, phân loại thành phần vào năm tầng và chỉ ra định nghĩa chỉ số đang nằm ở đâu. Với kiến trúc có định nghĩa nằm rải, đếm số chỗ cùng một chỉ số được định nghĩa và liệt kê ba triệu chứng quan sát được.",
"Gọi mọi thứ là tầng ngữ nghĩa · coi bảng mart là mô hình ngữ nghĩa · để công cụ BI giữ định nghĩa chỉ số · nghĩ cài công cụ là đã có tầng ngữ nghĩa.",
"Phân đúng năm tầng ở ≥ 2/3 kiến trúc, và đếm được số chỗ trùng định nghĩa ở kiến trúc có vấn đề."),

(166,"From a business question to a metric contract","TH","Lesson 165",
"Bài trung tâm của module. Hợp đồng chỉ số gồm sáu phần bắt buộc, và thiếu bất kỳ phần nào là chỉ số còn mơ hồ: **tập hợp** tức tính trên những bản ghi nào và loại trừ những gì; **hạt** theo lesson 120; **thời gian** tức dùng mốc thời gian nào và thuộc kỳ nào; **bộ lọc** tức điều kiện nằm trong định nghĩa chứ do người dùng chọn; **phép gộp** tức cộng, đếm, trung bình hay tỉ lệ; và **chủ sở hữu** tức ai quyết khi cần đổi. Ví dụ đối chiếu: câu hỏi doanh thu tháng trước là bao nhiêu có thể cho tám con số đều hợp lệ tuỳ sáu phần trên được chốt thế nào, và liệt kê đủ tám là bài tập của lab. Cách phỏng vấn người nghiệp vụ để chốt sáu phần, theo tinh thần bốn câu hỏi làm rõ ở lesson 1. Phép thử của một hợp đồng tốt: hai người đọc cùng viết ra cùng một truy vấn.",
"Viết hợp đồng sáu phần cho một chỉ số và chứng minh hai người đọc độc lập cho ra cùng một con số.",
"Tầng *áp dụng*. Objective có phép kiểm chứng khách quan bằng hai bản cài độc lập. Kiểm bằng phép thử hai người; đạt khi ba chỉ số đều cho hai con số khớp tuyệt đối giữa hai người cài độc lập.",
"Nhận ba câu hỏi nghiệp vụ mơ hồ. Với câu thứ nhất, liệt kê tám cách hiểu đều hợp lệ và con số tương ứng. Viết hợp đồng sáu phần cho cả ba. Đưa hợp đồng cho một học viên khác; hai người cài độc lập và so ba cặp con số.",
"Bỏ phần tập hợp nên không rõ loại trừ gì · không nêu mốc thời gian dùng để quy kỳ · để bộ lọc trong định nghĩa lẫn với bộ lọc người dùng chọn · không có chủ sở hữu.",
"Ba cặp con số từ hai người cài độc lập đều khớp tuyệt đối, và tám cách hiểu của câu đầu được liệt kê đủ."),

(167,"The semantic graph - entities, dimensions, measures, metrics","LT","Lesson 166",
"Mô hình ngữ nghĩa là một đồ thị chứ một danh sách khai báo, và nhìn nó như đồ thị giải thích mọi ràng buộc về sau. Bốn loại nút: thực thể là thứ có danh tính và là điểm nối, chiều là thuộc tính để cắt lát, độ đo là cột số có thể gộp, chỉ số là phép tính có hợp đồng dựng trên độ đo. Cạnh là quan hệ kết giữa các thực thể kèm bản số. Từ đồ thị suy ra ba câu hỏi mà tầng ngữ nghĩa phải trả lời được bằng máy: chỉ số này cắt được theo chiều nào, hai chỉ số này đặt cạnh nhau được không, và đường kết nào được dùng khi có nhiều đường. Câu cuối là nguồn của mọi phép kết mơ hồ ở lesson 171. Khác biệt với lược đồ vật lý: một thực thể ngữ nghĩa có thể ánh xạ tới nhiều bảng, và một bảng có thể chứa nhiều thực thể; nên đồ thị ngữ nghĩa không phải bản sao của sơ đồ bảng.",
"Vẽ đồ thị ngữ nghĩa cho một miền và chỉ ra chỗ có nhiều hơn một đường kết giữa hai thực thể.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho ba bài về tính đúng của phép kết. Kiểm bằng bài vẽ cộng nhận dạng; đạt khi đồ thị đủ bốn loại nút và chỉ ra đúng ít nhất một cặp thực thể có nhiều đường kết.",
"Từ lược đồ mart đã dựng ở M11, vẽ đồ thị ngữ nghĩa với bốn loại nút và cạnh có bản số. Chỉ ra mọi cặp thực thể có nhiều hơn một đường kết. Với mỗi cặp đó, viết hai câu hỏi nghiệp vụ mà hai đường cho hai câu trả lời khác nhau.",
"Chép sơ đồ bảng thành đồ thị ngữ nghĩa · nhầm độ đo với chỉ số · bỏ bản số trên cạnh · giả định luôn chỉ có một đường kết.",
"Đồ thị đủ bốn loại nút và cạnh có bản số, và chỉ ra được ít nhất một cặp có nhiều đường kèm hai câu hỏi cho hai kết quả."),

(168,"Metric types - simple, ratio, derived and cumulative","TH","Lesson 167",
"Bốn loại chỉ số, mỗi loại có ràng buộc gộp riêng, và xử lý sai loại là nguồn số sai phổ biến nhất ở tầng này. Chỉ số đơn giản là một phép gộp trên một độ đo. Chỉ số tỉ lệ có tử và mẫu, và ràng buộc bắt buộc theo lesson 155: **lưu tử và mẫu riêng, chia ở bước cuối**, vì gộp các tỉ lệ đã tính sẵn cho kết quả sai ở mọi mức trừ mức đã tính. Chỉ số phái sinh dựng từ chỉ số khác bằng phép toán, và phải kế thừa ràng buộc gộp của thành phần. Chỉ số tích luỹ cộng dồn theo một cửa sổ thời gian, nên phụ thuộc vào ngữ nghĩa thời gian ở lesson 170 và vào bảng lịch đầy đủ theo lesson 124. Với mỗi loại, một phép kiểm đặc trưng để phát hiện cài sai. Bảng phân loại mười chỉ số thật của một doanh nghiệp là bài tập nhận dạng.",
"Phân loại chỉ số vào bốn nhóm và chứng minh bằng số rằng cài tỉ lệ sai cho kết quả sai ở mức gộp cao hơn.",
"Tầng *phân tích*. Objective đòi nhận ra lỗi không báo lỗi, nên bắt buộc chứng minh bằng đối chứng. Kiểm bằng bài phân loại cộng đối chứng số; đạt khi phân đúng ít nhất tám trong mười và định lượng được sai lệch của cách cài sai.",
"Phân loại mười chỉ số thật vào bốn nhóm. Cài một chỉ số tỉ lệ theo hai cách: lưu sẵn tỉ lệ, và lưu tử mẫu riêng. Gộp lên ba mức khác nhau và so hai bộ kết quả với bản tính tay. Cài một chỉ số tích luỹ và kiểm ở kỳ không có dữ liệu.",
"Lưu sẵn tỉ lệ trong bảng · chỉ số phái sinh không kế thừa ràng buộc gộp · chỉ số tích luỹ không dựng trên bảng lịch đầy đủ · kiểm chỉ ở mức đã tính sẵn.",
"Phân đúng ≥ 8/10 chỉ số, và sai lệch của cách lưu sẵn tỉ lệ được định lượng ở cả ba mức gộp."),

(169,"Additivity and aggregation in the semantic layer","TH","Lesson 168",
"Bài áp phân loại cộng được ở lesson 155 vào tầng ngữ nghĩa, nơi nó trở thành một khai báo mà máy cưỡng chế được. Mỗi độ đo khai báo phép gộp mặc định và những chiều nó cộng được; tầng ngữ nghĩa dựa vào đó để **từ chối một truy vấn cộng sai** thay vì im lặng trả về số sai, và đây là giá trị lớn nhất của việc có tầng này. Ba nhóm theo lesson 155 nay thành ba kiểu khai báo. Độ đo bán cộng: khai báo phép gộp khác nhau theo chiều, ví dụ cộng theo sản phẩm nhưng lấy giá trị cuối kỳ theo thời gian. Đếm giá trị phân biệt: không cộng được và cũng không cộng dồn được, nên tầng ngữ nghĩa phải tính lại ở mọi mức thay vì gộp từ mức thấp; đây là lý do chỉ số loại này tốn hơn nhiều. Bảng tổng hợp tính sẵn và điều kiện dùng được: chỉ dùng cho độ đo cộng được hoàn toàn.",
"Khai báo phép gộp cho mười độ đo sao cho tầng ngữ nghĩa từ chối được các truy vấn cộng sai.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng phép thử phủ định. Kiểm bằng năm truy vấn cộng sai; đạt khi cả năm bị từ chối hoặc trả về đúng, và không truy vấn hợp lệ nào bị chặn nhầm.",
"Khai báo mười độ đo gồm cả cộng được, bán cộng và không cộng được. Viết năm truy vấn cố ý cộng sai và chứng minh tầng ngữ nghĩa từ chối hoặc xử lý đúng. Viết năm truy vấn hợp lệ và chứng minh không cái nào bị chặn nhầm. Đo chi phí của một chỉ số đếm giá trị phân biệt ở ba mức.",
"Khai báo phép gộp mặc định là cộng cho mọi độ đo · dùng bảng tổng hợp tính sẵn cho chỉ số không cộng được · chặn quá tay nên truy vấn hợp lệ cũng bị từ chối.",
"Năm truy vấn cộng sai đều bị chặn hoặc xử lý đúng, năm truy vấn hợp lệ đều chạy, và có số đo chi phí của chỉ số đếm phân biệt."),

(170,"Time semantics - grain, offsets and period comparison","TH","Lesson 169",
"Thời gian là chiều phức tạp nhất và là nguồn tranh cãi nhiều nhất giữa các phòng ban. Bốn quyết định phải chốt trong hợp đồng: dùng mốc thời gian nào khi một bản ghi có nhiều mốc như ngày đặt, ngày giao, ngày ghi nhận doanh thu; hạt thời gian mặc định; múi giờ quy chiếu, vì một giao dịch lúc nửa đêm thuộc ngày nào phụ thuộc múi giờ; và định nghĩa kỳ tài chính nếu khác kỳ dương lịch. So kỳ trước và cùng kỳ năm trước: ba cách dịch chuyển kỳ và chúng cho kết quả khác nhau ở tháng có số ngày khác nhau và ở năm nhuận. **Vấn đề kỳ thiếu** theo lesson 124 nay là ràng buộc bắt buộc của tầng ngữ nghĩa: mọi chỉ số theo thời gian phải dựng trên bảng lịch đầy đủ, nếu không thì kỳ không có dữ liệu biến mất và phép so kỳ lấy nhầm kỳ. Cửa sổ trượt và kỳ tới hiện tại.",
"Chốt bốn quyết định thời gian cho một bộ chỉ số và chứng minh phép so kỳ đúng ở tháng thiếu dữ liệu và ở năm nhuận.",
"Tầng *áp dụng*. Objective có hai ca biên cụ thể mà bản làm ẩu luôn sai. Kiểm bằng đối soát ở ca biên; đạt khi kết quả khớp bản tính tay ở cả tháng thiếu dữ liệu lẫn ngày 29 tháng 2.",
"Với một bộ ba chỉ số, chốt bốn quyết định thời gian và ghi vào hợp đồng. Dựng bảng lịch đầy đủ có kỳ tài chính. Tính so kỳ trước và cùng kỳ năm trước bằng ba cách dịch chuyển, trên dữ liệu cố ý thiếu ba tháng và bắc qua năm nhuận. Đối soát với bản tính tay.",
"Không chốt mốc thời gian dùng để quy kỳ · bỏ qua múi giờ · không dựng bảng lịch nên kỳ rỗng biến mất · dùng một cách dịch kỳ cho mọi chỉ số mà không hỏi nghiệp vụ.",
"Kết quả khớp bản tính tay ở cả tháng thiếu dữ liệu lẫn năm nhuận, và bốn quyết định thời gian có trong hợp đồng."),

(171,"Ambiguous joins and the chasm trap","TH","Lesson 170",
"Hai chế độ hỏng đặc trưng của tầng ngữ nghĩa, và cả hai đều cho số sai mà không báo lỗi. Phép kết mơ hồ: khi có nhiều hơn một đường nối hai thực thể theo lesson 167, công cụ phải chọn một đường và chọn khác nhau thì số khác nhau; cách chặn là khai báo tường minh đường kết hợp lệ chứ để công cụ đoán. Bẫy vực: hai bảng sự kiện cùng nối vào một chiều chung nhưng không nối trực tiếp với nhau; kết cả ba trong một truy vấn làm **hai bảng sự kiện nhân dòng lẫn nhau qua chiều chung**, và tổng của cả hai đều bị thổi phồng. Ví dụ kinh điển: đơn hàng và phiếu hỗ trợ cùng nối vào khách hàng. Ba cách giải: gộp riêng từng bảng rồi mới nối kết quả, dùng truy vấn con tương quan, hoặc tách thành hai truy vấn. Bẫy hố: quan hệ một nhiều theo chiều ngược làm mất dòng thay vì nhân dòng.",
"Tái hiện bẫy vực bằng số và chặn nó bằng một trong ba cách, chứng minh tổng trở lại đúng.",
"Tầng *phân tích*. Objective đòi nhận ra một lỗi im lặng rồi sửa bằng cơ chế đúng. Kiểm bằng đối chứng với tổng thật; đạt khi định lượng được mức thổi phồng và bản sửa khớp tổng thật.",
"Dựng hai bảng sự kiện cùng nối vào chiều khách hàng. Viết truy vấn kết cả ba và so tổng của từng bảng với tổng thật; định lượng mức thổi phồng. Sửa bằng cả ba cách và so ba kết quả. Tạo một cặp thực thể có hai đường kết và chứng minh hai đường cho hai con số.",
"Kết hai bảng sự kiện qua một chiều chung · để công cụ tự chọn đường kết · phát hiện bằng cách nhìn số rồi thấy hợp lý · dùng phép chọn phân biệt để chữa nhân dòng.",
"Mức thổi phồng được định lượng, cả ba cách sửa đều cho tổng khớp tổng thật, và hai đường kết cho hai con số khác nhau được chỉ ra."),

(172,"Fanout - proving a metric is not double counted","TH","Lesson 171",
"Bài đặt ra một nghĩa vụ chứng minh chứ chỉ một lời khuyên cẩn thận. Nhân dòng xảy ra bất cứ khi nào phép kết đổi hạt theo lesson 150, và hậu quả là mọi phép cộng sau đó bị thổi phồng. Ba nguồn nhân dòng ở tầng ngữ nghĩa: kết với bảng có bản số nhiều, kết qua bảng cầu theo lesson 156, và bẫy vực ở lesson 171. Quy trình chứng minh không đếm trùng gồm bốn bước và đây là quy trình bắt buộc cho mọi chỉ số trước khi được chứng nhận: phát biểu hạt của mỗi bảng tham gia; đếm dòng trước và sau mỗi phép kết; đối soát tổng với một truy vấn viết tay trên bảng gốc; và kiểm ở ít nhất ba mức gộp khác nhau chứ chỉ mức chi tiết nhất. **Một chỉ số chưa qua bốn bước này thì chưa được đưa vào danh mục**, và quy tắc đó được cưỡng chế ở lesson 182.",
"Chạy đủ bốn bước chứng minh cho ba chỉ số và phát hiện được chỉ số nào đang đếm trùng.",
"Tầng *áp dụng*. Objective là một quy trình kiểm chứng bắt buộc có kết quả nhị phân. Kiểm bằng ba chỉ số trong đó ít nhất một đang đếm trùng; đạt khi phát hiện đúng và hai chỉ số còn lại được chứng minh sạch ở cả ba mức gộp.",
"Nhận ba chỉ số đã khai báo sẵn, trong đó một cái đếm trùng. Chạy đủ bốn bước cho từng cái. Với chỉ số có vấn đề, định lượng mức thổi phồng và sửa. Nộp bảng đối soát ba mức gộp cho cả ba.",
"Chỉ đối soát ở mức chi tiết nhất · tin công cụ đã xử lý nhân dòng · bỏ bước đếm dòng trước và sau kết · đối soát với chính truy vấn do công cụ sinh ra thay vì truy vấn viết tay.",
"Phát hiện đúng chỉ số đếm trùng và định lượng mức thổi phồng, và hai chỉ số còn lại khớp truy vấn viết tay ở cả ba mức gộp."),

(173,"The compatibility matrix - which dimension goes with which metric","TH","Lesson 172",
"Không phải chỉ số nào cũng cắt được theo chiều nào, và để người dùng tự phát hiện điều đó bằng cách nhận số vô nghĩa là thiết kế tồi. Ma trận tương thích liệt kê chỉ số theo hàng và chiều theo cột, mỗi ô ghi hợp lệ, không hợp lệ, hoặc hợp lệ có điều kiện. Ba nguồn không tương thích: chiều không nối được tới bảng sự kiện của chỉ số; chiều nối được nhưng ở hạt thô hơn nên cắt lát làm mất nghĩa; và độ đo không cộng được theo chiều đó theo lesson 169. Ví dụ cụ thể: cắt số dư cuối kỳ theo chiều sản phẩm có nghĩa, cắt theo thời gian rồi cộng thì không. Tầng ngữ nghĩa nên **cưỡng chế ma trận bằng máy**: truy vấn ở ô không hợp lệ bị từ chối kèm thông báo giải thích, thay vì trả về số. Ma trận cũng là tài liệu cho người dùng, và nó là đầu vào của phần khả năng tìm thấy ở M11C.",
"Dựng ma trận tương thích cho bộ chỉ số và cưỡng chế được nó bằng máy với thông báo giải thích.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu hai chiều: chặn đúng cái sai và không chặn nhầm cái đúng. Kiểm bằng mười truy vấn; đạt khi mọi ô không hợp lệ bị chặn có giải thích và không ô hợp lệ nào bị chặn nhầm.",
"Dựng ma trận cho tám chỉ số nhân sáu chiều, mỗi ô ghi một trong ba trạng thái kèm lý do cho ô không hợp lệ. Cưỡng chế bằng công cụ. Chạy mười truy vấn gồm năm hợp lệ và năm không, kiểm phản ứng từng cái. Xuất ma trận thành tài liệu cho người dùng.",
"Để người dùng tự phát hiện chiều không dùng được · chặn mà không giải thích lý do · đánh dấu hợp lệ cho mọi ô để tránh phiền · không xuất ma trận thành tài liệu.",
"Năm truy vấn không hợp lệ bị chặn kèm giải thích, năm truy vấn hợp lệ chạy được, và ma trận xuất ra dạng tài liệu đọc được."),

(174,"Semantic models in MetricFlow","TH","Lesson 173",
"Bài đầu tiên mở công cụ, sau khi chín bài trước đã dựng nền. Mô hình ngữ nghĩa khai báo ba phần: thực thể với loại khoá chính hoặc khoá ngoại, chiều với loại phân loại hoặc thời gian, và độ đo với phép gộp. Chiều thời gian chính là khai báo quyết định hạt thời gian mặc định theo lesson 170. Ánh xạ từ mô hình ngữ nghĩa xuống bảng vật lý, và vì sao một mô hình ngữ nghĩa có thể trỏ tới một bảng hoặc một truy vấn. Quan hệ với tầng biến đổi ở M14: mô hình ngữ nghĩa đặt trên mart chứ trên bảng thô, nên chất lượng mart quyết định chất lượng tầng ngữ nghĩa. Ba lỗi khai báo hay gặp và thông báo lỗi tương ứng. Nguyên tắc giữ trong suốt module: **mọi khai báo phải truy được về một dòng trong hợp đồng chỉ số ở lesson 166**, chứ suy ra từ cột có sẵn trong bảng.",
"Khai báo mô hình ngữ nghĩa cho ba bảng mart sao cho mọi khai báo truy được về hợp đồng.",
"Tầng *áp dụng*. Objective là chuyển một thiết kế đã có sang khai báo công cụ, có tiêu chí truy ngược. Kiểm bằng rà soát truy ngược; đạt khi mọi độ đo và chiều dẫn được về một dòng trong hợp đồng và ba mô hình biên dịch sạch.",
"Khai báo mô hình ngữ nghĩa cho ba bảng mart đã dựng ở M11. Với mỗi độ đo và chiều, ghi rõ nó đến từ phần nào của hợp đồng. Biên dịch và sửa tới sạch. Cố ý khai báo sai loại thực thể và ghi lại thông báo lỗi.",
"Khai báo theo cột có sẵn trong bảng · đặt mô hình ngữ nghĩa trên bảng thô · bỏ khai báo chiều thời gian chính · khai báo phép gộp mặc định là cộng cho mọi độ đo.",
"Ba mô hình biên dịch sạch, và mọi độ đo cùng chiều dẫn được về một dòng cụ thể trong hợp đồng."),

(175,"Defining metrics and reading the generated SQL","TH","Lesson 174",
"Khai báo bốn loại chỉ số ở lesson 168 bằng công cụ, và bước quan trọng hơn là đọc câu lệnh SQL mà nó sinh ra. Lý do đọc: **công cụ sinh SQL không phải hộp đen được phép tin**, và cách duy nhất biết định nghĩa có đúng là đọc câu lệnh rồi đối chiếu với hợp đồng. Bốn thứ cần soi trong SQL sinh ra: phạm vi tập hợp có khớp phần tập hợp của hợp đồng không, bộ lọc trong định nghĩa có được áp không, đường kết nào được chọn theo lesson 171, và phép gộp có đúng loại theo lesson 169. Chỉ số tỉ lệ sinh ra SQL đặc trưng với tử và mẫu tính riêng rồi chia, và thấy đúng dạng đó là bằng chứng công cụ đang làm đúng. Chỉ số tích luỹ sinh ra phép kết với bảng lịch. Cách đọc kế hoạch thực thi của SQL sinh ra, dùng kỹ năng ở lesson 130.",
"Khai báo bốn loại chỉ số và chứng minh bằng SQL sinh ra rằng mỗi cái khớp hợp đồng ở cả bốn điểm soi.",
"Tầng *phân tích*. Objective đòi kiểm chứng đầu ra của công cụ thay vì tin nó. Kiểm bằng bài đọc SQL có danh mục bốn điểm; đạt khi cả bốn chỉ số qua đủ bốn điểm soi và phát hiện được một khai báo sai cài sẵn.",
"Khai báo bốn chỉ số theo bốn loại. Với mỗi cái, xuất SQL sinh ra và soi đủ bốn điểm, đối chiếu với hợp đồng. Giảng viên sửa một khai báo cho sai lệch hợp đồng; tìm ra nó chỉ bằng cách đọc SQL. Đọc kế hoạch thực thi của chỉ số tốn nhất.",
"Tin SQL sinh ra là đúng vì công cụ nổi tiếng · chỉ kiểm bằng cách so con số · bỏ qua đường kết được chọn · không bao giờ đọc kế hoạch của SQL sinh ra.",
"Bốn chỉ số qua đủ bốn điểm soi, và khai báo sai cài sẵn được tìm ra chỉ bằng đọc SQL."),

(176,"Query compilation internals","TH","Lesson 175",
"Hiểu công cụ biên dịch một câu hỏi thành SQL ra sao là điều kiện để chẩn đoán khi nó cho số lạ hoặc chạy chậm. Các bước: phân giải chỉ số và chiều được yêu cầu, xác định tập mô hình ngữ nghĩa cần tới, tìm đường kết giữa chúng, dựng truy vấn theo từng nguồn rồi nối, và áp phép gộp cuối. Bước tìm đường kết là bước quyết định và là nơi phát sinh phép kết mơ hồ ở lesson 171. Cơ chế tránh nhân dòng của công cụ: gộp riêng từng nguồn về hạt chung trước khi nối, và đây chính là cách giải thứ nhất ở lesson 171 được tự động hoá. Giới hạn phải biết: công cụ chỉ đúng khi khai báo đúng, nên **nó không cứu được một mô hình ngữ nghĩa sai**. Ba trường hợp công cụ sinh SQL kém hiệu quả và cách can thiệp, gồm cả việc dựng bảng tổng hợp tính sẵn.",
"Giải thích một kết quả lạ bằng cách truy các bước biên dịch, và can thiệp được vào một truy vấn sinh ra kém hiệu quả.",
"Tầng *phân tích*. Objective là chẩn đoán xuyên tầng từ câu hỏi tới SQL. Kiểm bằng ba tình huống; đạt khi truy đúng bước gây ra ở ít nhất hai và cải thiện được truy vấn chậm có số đo.",
"Giảng viên đưa ba tình huống: một kết quả lạ do đường kết, một do phép gộp, và một truy vấn chậm. Với mỗi cái, truy các bước biên dịch để tìm bước gây ra. Với truy vấn chậm, dựng bảng tổng hợp tính sẵn hoặc chỉnh khai báo, đo thời gian trước sau.",
"Đổ lỗi cho công cụ khi nguyên nhân là khai báo · sửa bằng cách viết SQL tay ngoài tầng ngữ nghĩa · dựng bảng tổng hợp cho chỉ số không cộng được · không đo trước sau.",
"Truy đúng bước gây ra ở ≥ 2/3 tình huống, và truy vấn chậm cải thiện có số đo mà kết quả không đổi."),

(177,"Testing a semantic layer - definition and static tests","TH","Lesson 176",
"Tháp kiểm thử cho tầng ngữ nghĩa có ba tầng, bài này lo tầng thứ nhất. Kiểm tra định nghĩa chạy nhanh và không cần dữ liệu: mọi chỉ số có đủ sáu phần hợp đồng, mọi độ đo khai báo phép gộp, mọi chiều thuộc ít nhất một thực thể, không có chỉ số mồ côi không ai dùng, và mọi khai báo có chủ sở hữu. Kiểm tra tĩnh về cấu trúc đồ thị: không có chu trình, không có thực thể cô lập, và mọi cặp thực thể dùng chung trong một chỉ số có đúng một đường kết được khai báo. Những kiểm tra này chạy trong tích hợp liên tục theo lesson 96 và chặn hợp nhất, nên một chỉ số thiếu hợp đồng không vào được nhánh chính. **Giá trị thật của tầng kiểm tra này là nó rẻ và chạy ở mọi lần nộp mã**, nên bắt lỗi trước khi ai đó nhìn thấy số sai.",
"Dựng bộ kiểm tra định nghĩa và cấu trúc chạy trong tích hợp liên tục, chặn được năm loại vi phạm.",
"Tầng *áp dụng*. Objective là một cửa chặn tự động có tiêu chí nghiệm thu bằng phép thử tiêm. Kiểm bằng năm vi phạm tiêm; đạt khi cả năm bị chặn và không khai báo hợp lệ nào bị chặn nhầm.",
"Viết bộ kiểm tra cho năm quy tắc định nghĩa và ba quy tắc cấu trúc đồ thị. Đưa vào quy trình tích hợp liên tục có cửa chặn hợp nhất. Nộp năm yêu cầu hợp nhất vi phạm năm quy tắc khác nhau và xác nhận cả năm bị chặn ở đúng quy tắc.",
"Chỉ kiểm bằng cách chạy truy vấn · không chặn hợp nhất nên kiểm tra chỉ để tham khảo · viết kiểm tra cần dữ liệu nên chạy chậm và bị tắt · bỏ quy tắc bắt buộc có chủ sở hữu.",
"Năm vi phạm đều bị chặn ở đúng quy tắc, và không khai báo hợp lệ nào bị chặn nhầm."),

(178,"Correctness tests and reconciliation against hand-written SQL","TH","Lesson 177",
"Tầng thứ hai của tháp kiểm thử, và là tầng quyết định tầng ngữ nghĩa có đáng tin không. Bốn loại kiểm tra tính đúng. Đối soát với SQL viết tay: với mỗi chỉ số được chứng nhận, có một truy vấn viết tay độc lập trên bảng gốc và hai kết quả phải khớp ở ít nhất ba mức gộp, theo lesson 172; **truy vấn đối soát phải do người khác viết từ hợp đồng chứ chép từ SQL sinh ra**, nếu không thì nó chỉ lặp lại cùng một sai lầm. Kiểm bất biến: tổng con bằng tổng cha, tỉ lệ nằm trong khoảng hợp lệ, và chỉ số không âm khi không được phép âm. Kiểm ca biên: hợp đồng nguồn đòi bộ đối chứng phủ **sáu ca bắt buộc** chứ ba, vì mỗi ca làm sai một chỉ số theo một cách khác nhau: giá trị rỗng, bản ghi trùng, giao dịch hoàn tiền tức giá trị âm, dữ liệu tới muộn, thay đổi ở chiều biến đổi chậm, và ranh giới kỳ tài chính. Bộ đối chứng là tài sản cố định của module: nó không đổi giữa các lần chạy, nên mọi hồi quy đều quy được về thay đổi của mã chứ của dữ liệu. Kiểm hồi quy: khi định nghĩa đổi, so kết quả trước và sau trên cùng dữ liệu để biết chính xác cái gì đổi.",
"Dựng bộ đối soát độc lập cho năm chỉ số và chứng minh khớp ở ba mức gộp cùng đủ sáu ca đối chứng bắt buộc.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu khắt khe là khớp tuyệt đối với nguồn độc lập. Kiểm bằng đối soát ba mức nhân sáu ca đối chứng; đạt khi năm chỉ số khớp ở mọi ô trong 18 ô và bộ kiểm chạy tự động.",
"Với năm chỉ số đã chứng nhận, nhờ một học viên khác viết truy vấn đối soát chỉ từ hợp đồng. Dựng bộ đối chứng cố định phủ đủ sáu ca: giá trị rỗng, trùng, hoàn tiền, tới muộn, chiều biến đổi chậm, và ranh giới kỳ tài chính. So kết quả ở ba mức gộp nhân sáu ca. Đưa bộ đối soát vào quy trình chạy hằng ngày. Đổi một định nghĩa và chạy kiểm hồi quy để liệt kê chính xác cái gì đổi.",
"Viết truy vấn đối soát bằng cách chép SQL sinh ra · chỉ đối soát ở một mức gộp · bộ đối chứng thiếu ca hoàn tiền hoặc ca chiều biến đổi chậm · đổi bộ đối chứng giữa hai lần chạy nên không quy được hồi quy · không có kiểm hồi quy nên đổi định nghĩa mà không biết ảnh hưởng.",
"Năm chỉ số khớp ở cả 18 ô ba mức nhân sáu ca đối chứng, và kiểm hồi quy liệt kê đúng phần thay đổi khi đổi định nghĩa."),

(179,"Serving, caching and performance","TH","Lesson 178",
"Tầng ngữ nghĩa đứng trên đường truy vấn nên nó là một thành phần có hiệu năng, chứ chỉ một tệp khai báo. Ba đường phục vụ: truy vấn từ công cụ BI, từ SQL, và từ mã qua giao diện lập trình. Bảng tổng hợp tính sẵn là kỹ thuật tăng tốc chính: tính trước ở một hạt thô hơn rồi dùng lại; điều kiện dùng được là độ đo cộng được hoàn toàn theo lesson 169, và chọn hạt tính sẵn là đánh đổi giữa tốc độ với dung lượng cùng độ tươi. Bộ đệm kết quả và ba chiến lược làm mới, cùng vấn đề dữ liệu cũ. **Khoá đệm phải mang ngữ cảnh bảo mật và phiên bản ngữ nghĩa**: thiếu phần đầu thì một người thấy kết quả dựng từ dữ liệu ngoài quyền của họ, thiếu phần sau thì một định nghĩa đã đổi vẫn trả kết quả cũ; cả hai là điều kiện tự động không đạt của module. Phục vụ cho hai loại bên tiêu thụ cùng lúc là yêu cầu bắt buộc chứ tuỳ chọn, vì chỉ khi có hai bên mới lộ ra chỗ định nghĩa bị diễn giải khác nhau. Đồng thời và giới hạn: nhiều người cùng chạy truy vấn nặng làm kho quá tải, nên cần giới hạn tốc độ và hàng đợi theo lesson 87. Bốn chỉ số phải theo dõi: thời gian phản hồi phân vị 95, tỉ lệ trúng đệm, số truy vấn đồng thời, và chi phí trên mỗi truy vấn.",
"Phục vụ hai loại bên tiêu thụ đạt ngưỡng thời gian phản hồi, với khoá đệm mang ngữ cảnh bảo mật và phiên bản ngữ nghĩa.",
"Tầng *đánh giá*. Objective đòi tối ưu dưới hai ràng buộc đối nghịch là tốc độ và độ tươi. Kiểm bằng cặp số đo cộng phép thử cách ly đệm; đạt khi thời gian phân vị 95 dưới ngưỡng, độ tươi trong cam kết, và hai người dùng khác quyền không bao giờ nhận cùng một mục đệm.",
"Chạy bộ 20 truy vấn chuẩn và đo bốn chỉ số ở trạng thái chưa tối ưu. Dựng bảng tổng hợp tính sẵn cho các chỉ số cộng được. Bật đệm với chiến lược làm mới phù hợp. Đo lại. Phục vụ cùng bộ chỉ số cho hai bên tiêu thụ khác loại, ví dụ một công cụ báo cáo và một ứng dụng gọi qua giao diện lập trình, rồi đối soát hai bên cho cùng con số. Chạy phép thử cách ly đệm: hai người dùng khác quyền hỏi cùng câu, chứng minh không ai nhận mục đệm của người kia. Đổi một định nghĩa và chứng minh đệm cũ bị vô hiệu nhờ phiên bản ngữ nghĩa trong khoá.",
"Dựng bảng tổng hợp cho chỉ số không cộng được · đặt thời gian sống của đệm dài hơn cam kết độ tươi · tối ưu mà đổi kết quả · **đặt khoá đệm bỏ ngữ cảnh bảo mật hoặc bỏ phiên bản ngữ nghĩa** · chỉ phục vụ một bên tiêu thụ rồi coi là đã kiểm · không đo chi phí trên mỗi truy vấn.",
"Thời gian phân vị 95 dưới ngưỡng, độ tươi trong cam kết, hai bên tiêu thụ cho cùng con số, và phép thử cách ly đệm không có lần nào hai người khác quyền dùng chung một mục."),

(180,"Access control at the semantic layer","TH","Lesson 179",
"Đặt kiểm soát truy cập ở tầng ngữ nghĩa có lợi thế lớn: một chỗ cưỡng chế cho mọi công cụ tiêu thụ, thay vì cấu hình lại ở từng công cụ BI. Ba mức kiểm soát: theo chỉ số tức ai được xem chỉ số nào, theo dòng tức mỗi người chỉ thấy dữ liệu thuộc phạm vi của mình, và theo cột tức che các trường nhạy cảm. Bảo mật mức dòng cài bằng cách gắn thuộc tính người dùng vào điều kiện lọc được áp tự động; ba cách lấy thuộc tính người dùng và đánh đổi. Cạm bẫy rò rỉ qua phép gộp: người không được xem dòng chi tiết nhưng được xem tổng có thể suy ra dòng chi tiết khi nhóm chỉ có một phần tử; cách chặn là đặt ngưỡng số phần tử tối thiểu cho mỗi nhóm. **Phép thử phủ định bắt buộc**: với mỗi chính sách, một phép kiểm chứng minh người không có quyền nhận được từ chối chứ nhận số đã lọc âm thầm.",
"Cài ba mức kiểm soát và chứng minh bằng phép thử phủ định rằng không rò rỉ, kể cả qua phép gộp.",
"Tầng *áp dụng*. Objective là một cơ chế bảo mật kiểm được bằng phép thử phủ định gồm cả đường rò gián tiếp. Kiểm bằng sáu phép thử; đạt khi cả sáu bị chặn đúng và đường rò qua phép gộp được chặn bằng ngưỡng nhóm.",
"Cài kiểm soát theo chỉ số, theo dòng và theo cột. Viết sáu phép thử phủ định gồm một phép thử suy ra dòng chi tiết từ nhóm một phần tử. Đặt ngưỡng số phần tử tối thiểu và chứng minh đường rò bị chặn. Kiểm rằng cùng chính sách có hiệu lực ở cả ba đường phục vụ.",
"Cấu hình quyền ở từng công cụ BI thay vì ở tầng ngữ nghĩa · bỏ qua đường rò qua phép gộp · trả về số đã lọc âm thầm thay vì từ chối · không kiểm chính sách ở mọi đường phục vụ.",
"Sáu phép thử phủ định đều bị chặn đúng, đường rò qua nhóm một phần tử bị chặn, và chính sách có hiệu lực ở cả ba đường phục vụ."),

(181,"Architecture alternatives - headless, BI-native or curated marts","LT","Lesson 180",
"Ba kiến trúc cho cùng một mục tiêu, và chọn theo ràng buộc tổ chức chứ theo công nghệ. Tầng ngữ nghĩa độc lập: định nghĩa nằm ngoài mọi công cụ tiêu thụ, nên nhiều công cụ dùng chung một định nghĩa; đổi lại thêm một thành phần phải vận hành và không phải công cụ BI nào cũng tích hợp tốt. Tầng ngữ nghĩa trong công cụ BI: tiện, không thêm thành phần, nhưng định nghĩa bị khoá trong một công cụ nên đổi công cụ là làm lại từ đầu, và người dùng SQL không hưởng được. Mart đã chuẩn bị sẵn: không có tầng ngữ nghĩa, thay vào đó là bảng rộng theo lesson 159 với định nghĩa đã tính sẵn; đơn giản nhất và đủ cho nhiều đội, đổi lại thiếu linh hoạt và số tổ hợp bảng phình theo nhu cầu. Sáu chiều để chọn và ba tình huống mà mart chuẩn bị sẵn là lựa chọn đúng dù nghe kém hiện đại.",
"Chọn kiến trúc cho ba bối cảnh tổ chức và nêu điều kiện làm lựa chọn đó sai.",
"Tầng *đánh giá*. Objective đòi chọn theo ràng buộc tổ chức, và chống việc mặc định chọn phương án phức tạp nhất. Kiểm bằng ba bối cảnh trong đó ít nhất một nên chọn mart chuẩn bị sẵn; đạt khi chọn đúng cả ba kèm điều kiện đảo ngược.",
"Cho ba bối cảnh khác nhau về số công cụ tiêu thụ, quy mô đội, và mức trưởng thành. Chấm ba kiến trúc trên sáu chiều cho từng bối cảnh, mỗi ô dẫn một quan sát từ lab của chính mình ở các bài trước. Chọn một và nêu hai điều kiện làm nó sai.",
"Chọn tầng ngữ nghĩa độc lập cho đội hai người · giữ định nghĩa trong công cụ BI rồi khoá mình vào nó · chấm bằng tính từ · bỏ qua phương án mart chuẩn bị sẵn vì nghe đơn giản.",
"Chọn đúng cả ba bối cảnh, mỗi ô trong bảng chấm dẫn một quan sát từ lab, và mỗi lựa chọn có hai điều kiện đảo ngược."),

(182,"Metric lifecycle - propose, certify, version, deprecate","TH","Lesson 181",
"Chỉ số có vòng đời, và không quản vòng đời thì danh mục phình tới mức không ai tin được cái nào. Năm trạng thái và điều kiện chuyển: đề xuất, đang rà soát, đã chứng nhận, đã khai tử, và đã gỡ. Điều kiện để được chứng nhận là danh mục kiểm lấy từ các bài trước: hợp đồng sáu phần đủ, qua bốn bước chứng minh không đếm trùng ở lesson 172, có bộ đối soát độc lập ở lesson 178, có ma trận tương thích ở lesson 173, và có chủ sở hữu. Phân loại thay đổi thành ba mức và quy trình tương ứng: thay đổi không ảnh hưởng số, thay đổi làm số đổi, và thay đổi phá vỡ tương thích; **mức hai là mức nguy hiểm nhất vì nó im lặng**, nên bắt buộc phải thông báo và phải chạy kiểm hồi quy. Với mức ba, thông báo là chưa đủ: hợp đồng nguồn đòi **chạy song song hai phiên bản, đối soát chênh lệch giữa chúng, lấy chấp thuận của bên tiêu thụ, rồi mới gỡ bản cũ**, và toàn bộ được ghi thành một bản ghi khai tử. Lý do chạy song song: chênh lệch giữa hai phiên bản là con số duy nhất cho bên tiêu thụ biết báo cáo của họ sẽ đổi bao nhiêu; không có nó thì họ chỉ nhận được một lời hứa. **Sửa đè công thức tại chỗ mà không có phiên bản mới là điều kiện tự động không đạt**, vì nó làm mọi số lịch sử đổi nghĩa mà không ai truy được. Khai tử có cửa sổ chuyển tiếp và cảnh báo cho người đang dùng. **Quy trình khai tử là quy trình hay bị bỏ quên nhất** và là lý do danh mục phình mãi.",
"Vận hành vòng đời năm trạng thái, và thực hiện một lần đổi công thức phá vỡ theo quy trình chạy song song cộng đối soát cộng bản ghi khai tử.",
"Tầng *áp dụng*. Objective là một quy trình quản trị có tiêu chí nghiệm thu bằng việc chặn đúng và khai tử sạch. Kiểm bằng ba chỉ số đi qua vòng đời cộng một lần di trú phá vỡ; đạt khi chỉ số thiếu điều kiện bị chặn chứng nhận, lần di trú có số chênh lệch đo được giữa hai phiên bản, và chỉ số khai tử không còn người dùng khi gỡ.",
"Dựng vòng đời năm trạng thái với cửa chặn tự động cho danh mục chứng nhận. Đưa ba chỉ số qua vòng đời, trong đó một cái thiếu bộ đối soát và phải bị chặn. Thực hiện một lần đổi định nghĩa mức hai với thông báo và kiểm hồi quy. Thực hiện một lần đổi công thức mức ba theo đủ quy trình: tạo phiên bản thứ hai, chạy song song cả hai trên cùng dữ liệu ít nhất một chu kỳ, đối soát và báo cho bên tiêu thụ chênh lệch bằng số, lấy chấp thuận, rồi gỡ bản cũ và nộp bản ghi khai tử. Khai tử một chỉ số với cửa sổ chuyển tiếp và xác nhận không còn ai dùng trước khi gỡ.",
"Chứng nhận chỉ số chưa có bộ đối soát · **sửa đè công thức tại chỗ thay vì tạo phiên bản mới** · gỡ bản cũ trước khi có chấp thuận của bên tiêu thụ · đổi định nghĩa làm số đổi mà không thông báo · gỡ chỉ số khi còn người dùng · không có quy trình khai tử nên danh mục chỉ phình.",
"Chỉ số thiếu điều kiện bị chặn chứng nhận, đổi công thức mức ba có chạy song song kèm số chênh lệch và chấp thuận của bên tiêu thụ, bản ghi khai tử đầy đủ, và chỉ số khai tử không còn người dùng khi gỡ."),

(183,"Ownership, change classification and the failure matrix","TH","Lesson 182",
"Bài chốt phần quản trị. Mô hình sở hữu ba vai và ranh giới: chủ sở hữu nghiệp vụ quyết định nghĩa, chủ sở hữu kỹ thuật chịu trách nhiệm cài đặt và vận hành, người quản trị danh mục giữ quy trình. Thiếu vai thứ nhất là nguyên nhân phổ biến nhất khiến định nghĩa không ai dám chốt. Ma trận chế độ hỏng của tầng ngữ nghĩa, mỗi dòng gồm hiện tượng, nguyên nhân gốc, cách phát hiện, và cách chặn; sáu chế độ hỏng chính đã gặp rải rác nay gom thành một bảng dùng được khi trực: đếm trùng, phép kết mơ hồ, gộp sai loại độ đo, ngữ nghĩa thời gian lệch, rò rỉ qua phép gộp, **đệm bỏ ngữ cảnh bảo mật hoặc bỏ phiên bản ngữ nghĩa** theo lesson 179, và **công thức bị sửa đè tại chỗ nên số lịch sử đổi nghĩa** theo lesson 182. Hai chế độ hỏng cuối nguy hiểm hơn phần còn lại vì chúng không sinh ra con số lạ: kết quả vẫn nằm trong khoảng hợp lý, chỉ là thuộc về người khác hoặc thuộc về một định nghĩa khác. **Với mỗi chế độ hỏng phải có một phép kiểm tự động phát hiện được**, nếu không thì nó sẽ tái diễn. Phân tích sau sự cố cho một lần số sai đã công bố ra ngoài.",
"Lập ma trận chế độ hỏng có phép kiểm tự động cho từng dòng, và gán được ba vai sở hữu cho bộ chỉ số.",
"Tầng *đánh giá*. Objective đòi tổng hợp các lỗi đã gặp thành một hệ phòng vệ. Kiểm bằng phép thử tiêm bảy lỗi; đạt khi ít nhất sáu bị phép kiểm tự động phát hiện và ba vai được gán rõ.",
"Lập ma trận bảy chế độ hỏng với đủ bốn cột. Với mỗi dòng, viết một phép kiểm tự động. Giảng viên tiêm bảy lỗi tương ứng, trong đó có một mục đệm dùng lại xuyên người dùng và một công thức bị sửa đè, rồi đếm bao nhiêu cái bị phát hiện. Gán ba vai cho bộ chỉ số đã dựng. Viết phân tích sau sự cố cho một lần số sai công bố ra ngoài.",
"Gán chủ sở hữu nghiệp vụ cho một nhóm thay vì một người · viết cách chặn mà không có phép kiểm tự động · bỏ chế độ hỏng rò rỉ qua phép gộp · bỏ hai chế độ hỏng về đệm và về sửa đè công thức vì chúng không sinh số lạ · phân tích sau sự cố quy về lỗi cá nhân.",
"≥ 6/7 lỗi tiêm bị phép kiểm tự động phát hiện, ba vai được gán rõ, và phân tích sau sự cố không đổ lỗi cá nhân."),

(184,"Capstone - a governed revenue semantic product","DA","Lesson 183",
"Bài dự án khép module, lấy đúng yêu cầu capstone của hợp đồng nguồn. Dựng một sản phẩm ngữ nghĩa cho miền doanh thu. Sản phẩm nộp gồm chín hạng mục, lấy đúng ngưỡng của hợp đồng nguồn: hợp đồng sáu phần cho **ít nhất 15 chỉ số thuộc ít nhất năm loại**, mỗi chỉ số có chủ sở hữu và có phép kiểm; **ít nhất ba mô hình ngữ nghĩa**, và một truy vấn đi qua nhiều bước kết kèm chứng minh bản số cùng chứng minh không nhân dòng; ma trận tương thích chỉ số nhân chiều; bộ kiểm ba tầng gồm định nghĩa, tính đúng và tích hợp; bộ đối chứng cố định phủ đủ sáu ca ở lesson 178; SQL sinh ra cùng kế hoạch thực thi được soi cho một ma trận truy vấn đại diện; **phục vụ hai loại bên tiêu thụ** có bảo mật theo dòng cùng theo khách hàng và có phép thử cách ly đệm theo lesson 179; một lần **di trú phá vỡ hoàn chỉnh** gồm chạy song song, đối soát, chấp thuận của bên tiêu thụ và bản ghi khai tử theo lesson 182; và tài liệu vòng đời gồm trạng thái từng chỉ số cùng ba vai sở hữu. Sáu điều kiện tự động không đạt, lấy đủ từ phần *Critical failures* của nguồn: chỉ số thiếu tập hợp, thời gian, hạt hoặc chủ sở hữu; đồ thị kết cho phép đếm trùng im lặng; lấy sự đồng thuận trên bảng điều khiển làm bằng chứng đúng duy nhất; **sửa đè công thức tại chỗ khi thay đổi phá vỡ, không có di trú**; **đệm bỏ ngữ cảnh bảo mật hoặc bỏ phiên bản ngữ nghĩa**; và công cụ biên dịch xanh nhưng không có đối soát độc lập.",
"Nộp sản phẩm ngữ nghĩa đủ chín hạng mục với 15 chỉ số thuộc năm loại, không vi phạm sáu điều kiện tự động không đạt.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một sản phẩm có quản trị. Kiểm bằng rà soát chín hạng mục cộng đối soát độc lập; đạt khi cả 15 chỉ số khớp đối soát ở ba mức gộp nhân sáu ca đối chứng và không vi phạm điều kiện nào.",
"Dựng sản phẩm theo chín hạng mục. Nhờ một học viên khác viết bộ đối soát chỉ từ hợp đồng. So ở ba mức gộp nhân sáu ca đối chứng. Chạy phép thử phủ định cho chính sách truy cập và phép thử cách ly đệm. Thực hiện trọn một lần di trú phá vỡ và nộp bản ghi khai tử. Người chấm đổi một hạt, một mốc thời gian hoặc một quy tắc nghiệp vụ; thiết kế phải xác định đúng phạm vi ảnh hưởng và đúng đường di trú. Trình bày 15 phút và trả lời chất vấn về một chỉ số bất kỳ: chỉ số đó tính trên tập nào, ở hạt nào, và vì sao không đếm trùng.",
"Khai báo chỉ số theo cột có sẵn thay vì theo hợp đồng · tự viết bộ đối soát của chính mình · nộp đủ số lượng chỉ số nhưng dồn vào hai ba loại · bỏ phần di trú phá vỡ vì tốn một chu kỳ chạy song song · bỏ chính sách truy cập vì thấy môi trường thử không cần.",
"Chín hạng mục đầy đủ với ≥ 15 chỉ số thuộc ≥ 5 loại và ≥ 3 mô hình ngữ nghĩa, mọi chỉ số khớp đối soát độc lập ở ba mức gộp nhân sáu ca đối chứng, di trú phá vỡ hoàn tất có bản ghi khai tử, và không vi phạm sáu điều kiện tự động không đạt."),
]

M11C = ("Analytical Data Product and Self-Service", 185, 202, """| | |
|---|---|
| **Objective cấp module** | Biến một yêu cầu mơ hồ thành quyết định, câu hỏi, cây chỉ số và tiêu chí nghiệm thu; rồi dựng một sản phẩm dữ liệu có chủ, có hợp đồng, có tài liệu và có bằng chứng người dùng dùng được |
| **Tiền đề** | M11B |
| **Exit criterion** | Chứng minh tự phục vụ bằng phép thử khả dụng theo tác vụ, không bằng số dashboard đã tạo; mọi chỉ số truy được về một quyết định nghiệp vụ |
| **Kỹ năng SFIA** | `DATM` mức 5 · `DTAN` mức 4 |
| **Chế độ hỏng** | Trở thành người viết dbt giỏi mà không hiểu người tiêu thụ, quyết định và vòng đời sản phẩm, nên dựng ra mart đúng kỹ thuật mà không ai dùng |""",
"""**Module thứ hai thuộc phần bù Analytics Engineer**, và là module ngăn việc người học thành người viết mã biến đổi thuần tuý.

Ranh giới lấy từ hợp đồng nguồn: đây không phải curriculum Business Analyst. Trọng tâm là **truy được từ chỉ số ngược về quyết định**, và chứng minh người khác dùng được sản phẩm của mình.

Nguyên tắc chấm nghiêm nhất: số dashboard đã tạo, số bảng đã dựng và số người có quyền truy cập đều **không** phải bằng chứng tự phục vụ.""")

L11C = [
(185,"Decision-first discovery","LT","Module 11C: M11B",
"Bài mở module bằng cách đảo ngược thứ tự quen thuộc: bắt đầu từ quyết định chứ từ dữ liệu có sẵn. Bốn câu hỏi phải trả lời trước khi dựng bất cứ thứ gì: quyết định nào sẽ được đưa ra, ai đưa ra, theo nhịp nào, và hành động thay đổi ra sao tuỳ kết quả. Câu cuối là câu lọc mạnh nhất: nếu mọi kết quả đều dẫn tới cùng một hành động thì phân tích đó không cần làm. Phân biệt ba loại yêu cầu và cách xử lý khác nhau: yêu cầu có quyết định rõ, yêu cầu tò mò không gắn hành động, và yêu cầu thực ra là một yêu cầu vận hành chứ phân tích. Nối với lesson 1: phát biểu bài toán sáu phần áp vào đây với phần phi mục tiêu đặc biệt quan trọng. Ba câu hỏi để phát hiện yêu cầu là dashboard theo thói quen chứ theo nhu cầu quyết định thật.",
"Chuyển một yêu cầu mơ hồ thành phát biểu quyết định đủ bốn phần và nhận ra yêu cầu không dẫn tới hành động nào.",
"Tầng *áp dụng*. Bài mở module, áp một khung phỏng vấn vào tình huống mới. Kiểm bằng năm yêu cầu trong đó ít nhất một không dẫn tới hành động; đạt khi bốn phần đầy đủ ở ít nhất bốn yêu cầu và nhận ra đúng yêu cầu nên từ chối.",
"Nhận năm yêu cầu viết theo cách người nghiệp vụ thật hay nhắn. Phỏng vấn giảng viên đóng vai người yêu cầu để chốt bốn phần cho từng cái. Nhận ra yêu cầu nào không dẫn tới hành động khác nhau và viết cách từ chối hoặc chuyển hướng nó.",
"Nhận mọi yêu cầu rồi dựng dashboard · bỏ câu hỏi hành động thay đổi ra sao · nhầm yêu cầu vận hành với yêu cầu phân tích · phỏng vấn bằng câu hỏi đóng.",
"Bốn phần đầy đủ ở ≥ 4/5 yêu cầu, và nhận ra đúng yêu cầu không dẫn tới hành động kèm cách xử lý."),

(186,"Question decomposition and the metric tree","TH","Lesson 185",
"Một quyết định phân rã thành câu hỏi, câu hỏi phân rã thành chỉ số, và chỉ số phân rã thành thành phần điều khiển được. Cây chỉ số là công cụ trung tâm: chỉ số đầu ra ở gốc, các thành phần nhân hoặc cộng ở dưới, cho tới khi tới các lá mà một đội cụ thể tác động được. Phép thử của một cây tốt: **mọi lá có người sở hữu và có đòn bẩy tác động được**, nếu không thì cây chỉ là phép chia số học không dẫn tới hành động. Ví dụ phân rã doanh thu thành số khách nhân tần suất nhân giá trị đơn nhân biên lợi nhuận, rồi mỗi thành phần lại phân rã tiếp. Phân biệt chỉ số dẫn dắt với chỉ số kết quả và vì sao dashboard chỉ có chỉ số kết quả thì luôn tới muộn. Mỗi chỉ số trong cây phải trỏ tới một hợp đồng sáu phần ở lesson 166 chứ chỉ một cái tên.",
"Dựng cây chỉ số từ một quyết định sao cho mọi lá có chủ và có đòn bẩy, và mọi nút trỏ tới một hợp đồng.",
"Tầng *áp dụng*. Objective có phép thử khách quan ở mọi lá. Kiểm bằng rà soát cây; đạt khi mọi lá có chủ và đòn bẩy, và mọi nút dẫn được tới một hợp đồng chỉ số.",
"Từ một quyết định đã chốt ở lesson 185, dựng cây chỉ số ba tầng. Với mỗi lá, ghi đội sở hữu và đòn bẩy cụ thể họ tác động được. Với mỗi nút, trỏ tới hợp đồng tương ứng. Đánh dấu chỉ số nào là dẫn dắt và chỉ số nào là kết quả.",
"Phân rã tới mức không ai tác động được · để lá không có chủ · dựng cây chỉ toàn chỉ số kết quả · đặt tên chỉ số mà không có hợp đồng.",
"Mọi lá có chủ và đòn bẩy cụ thể, mọi nút dẫn tới một hợp đồng, và chỉ số dẫn dắt được đánh dấu tách khỏi chỉ số kết quả."),

(187,"Requirements traceability","TH","Lesson 186",
"Khả năng truy ngược là thứ phân biệt một sản phẩm dữ liệu với một đống bảng. Chuỗi truy ngược đầy đủ có năm mắt: quyết định, câu hỏi, chỉ số, mô hình, và bảng nguồn. Từ bất kỳ mắt nào phải đi được cả hai chiều: từ một cột trong bảng nguồn trả lời được nó phục vụ quyết định nào, và từ một quyết định liệt kê được mọi thứ nó phụ thuộc. Công dụng thực tế và đo được: khi một nguồn đổi lược đồ thì biết ngay quyết định nào bị ảnh hưởng để báo đúng người; và khi cần cắt chi phí thì biết bảng nào không phục vụ quyết định nào để bỏ. Cách ghi lại chuỗi truy ngược: ma trận truy ngược trong kho mã chứ trong tài liệu rời, để nó được rà soát cùng mã. Quan hệ với lineage kỹ thuật ở M14D: lineage nối bảng với bảng, còn truy ngược nối bảng với quyết định, và cần cả hai.",
"Dựng ma trận truy ngược năm mắt và trả lời được cả hai chiều cho ba truy vấn kiểm tra.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng việc trả lời câu hỏi hai chiều. Kiểm bằng ba câu hỏi truy ngược; đạt khi trả lời đúng cả ba chỉ bằng ma trận và tìm được ít nhất một bảng không phục vụ quyết định nào.",
"Dựng ma trận truy ngược năm mắt cho sản phẩm đang làm, lưu trong kho mã. Trả lời ba câu hỏi: nguồn này đổi thì quyết định nào ảnh hưởng, quyết định này phụ thuộc những bảng nào, và bảng nào không phục vụ quyết định nào. Đề xuất bỏ những bảng ở câu cuối.",
"Lưu ma trận truy ngược trong tài liệu rời nên nó lạc hậu ngay · chỉ truy được một chiều · nhầm lineage kỹ thuật với truy ngược tới quyết định · bỏ mắt câu hỏi nên nhảy thẳng từ quyết định sang chỉ số.",
"Trả lời đúng cả ba câu hỏi chỉ bằng ma trận, và tìm được ít nhất một bảng không phục vụ quyết định nào."),

(188,"Product anatomy - what makes a dataset a product","LT","Lesson 187",
"Bài phân biệt sáu thứ hay bị gọi chung là sản phẩm dữ liệu: tập dữ liệu, mart, dashboard, mô hình ngữ nghĩa, giao diện chỉ số, và sản phẩm dữ liệu. Tám thuộc tính làm một tập dữ liệu thành sản phẩm: có chủ sở hữu tên cụ thể, có người tiêu thụ xác định, có giao diện ổn định, có hợp đồng, có cam kết mức dịch vụ, có tài liệu, có chính sách truy cập, và có kế hoạch khai tử. Thiếu thuộc tính cuối là dấu hiệu rõ nhất của một thứ chưa phải sản phẩm: **không ai nghĩ tới việc nó sẽ chết thì nó sẽ sống mãi mà không ai dùng**. So sánh với sản phẩm phần mềm: điểm giống là vòng đời và hợp đồng, điểm khác là người tiêu thụ thường không biết mình cần gì cho tới khi thấy số. Ba mức trưởng thành và cách nhận ra đội đang ở mức nào.",
"Chấm một tập dữ liệu theo tám thuộc tính và chỉ ra nó ở mức trưởng thành nào.",
"Tầng *hiểu*. Bài lý thuyết đặt tiêu chuẩn cho phần còn lại của module. Kiểm bằng bài chấm ba tập dữ liệu; đạt khi chấm đúng ít nhất hai theo tám thuộc tính và chỉ đúng thuộc tính thiếu quan trọng nhất.",
"Chấm ba tập dữ liệu thật trong dự án theo tám thuộc tính, mỗi thuộc tính có hoặc không kèm bằng chứng. Với tập yếu nhất, chỉ ra thuộc tính thiếu nào gây hậu quả lớn nhất và vì sao. Phân loại sáu khái niệm ở phần đầu bài bằng ví dụ từ dự án của mình.",
"Gọi mọi bảng là sản phẩm dữ liệu · gán chủ sở hữu là một phòng ban thay vì một người · bỏ kế hoạch khai tử · nhầm dashboard với sản phẩm dữ liệu.",
"Chấm đúng ≥ 2/3 tập dữ liệu theo tám thuộc tính kèm bằng chứng, và sáu khái niệm được phân loại bằng ví dụ thật."),

(189,"Interface design for an analytical product","TH","Lesson 188",
"Giao diện của một sản phẩm dữ liệu là thứ người tiêu thụ dựa vào, nên nó là phần phải ổn định nhất. Bốn dạng giao diện và điều kiện dùng: bảng trong kho, khung nhìn, giao diện chỉ số qua tầng ngữ nghĩa ở M11B, và tệp xuất ra. Nguyên tắc thiết kế: **lộ ra ít nhất có thể**, vì mọi cột lộ ra đều thành hợp đồng mà ai đó sẽ dựa vào, theo đúng nguyên tắc che giấu thông tin ở lesson 90. Ba quyết định phải chốt: hạt của giao diện, tập cột công khai so với cột nội bộ, và quy ước đặt tên. Quy ước đặt tên nhất quán quan trọng hơn quy ước đẹp; đặt tên theo từ vựng nghiệp vụ ở lesson 89 chứ theo tên cột nguồn. Ba cách người tiêu thụ sẽ dùng sai giao diện nếu không thiết kế trước, và cách chặn từng cái bằng thiết kế chứ bằng tài liệu.",
"Thiết kế giao diện cho một sản phẩm với tập cột công khai tối thiểu và chứng minh nó đủ cho ba câu hỏi nghiệp vụ.",
"Tầng *áp dụng*. Objective có hai ràng buộc đối nghịch là tối thiểu và đủ dùng. Kiểm bằng ba câu hỏi nghiệp vụ; đạt khi cả ba trả lời được bằng tập cột công khai và không cột nội bộ nào bị lộ.",
"Thiết kế giao diện cho sản phẩm đang làm: chốt hạt, chia cột công khai và nội bộ, đặt tên theo từ vựng nghiệp vụ. Kiểm bằng ba câu hỏi nghiệp vụ. Nhờ một học viên dùng thử và ghi lại mọi lần họ phải hỏi cột này nghĩa là gì.",
"Lộ toàn bộ cột cho tiện · đặt tên cột theo tên ở hệ nguồn · đổi hạt của giao diện sau khi có người dùng · dựa vào tài liệu để chặn cách dùng sai thay vì thiết kế.",
"Ba câu hỏi nghiệp vụ trả lời được bằng tập cột công khai, không cột nội bộ nào lộ ra, và người dùng thử không phải hỏi nghĩa cột."),

(190,"Contract compatibility for consumers","TH","Lesson 189",
"Hợp đồng của sản phẩm dữ liệu gồm những gì và đổi nó thế nào cho an toàn. Năm phần: lược đồ, ngữ nghĩa từng trường, cam kết chất lượng, cam kết độ tươi, và quy trình thay đổi. Ba mức thay đổi theo đúng phân loại ở lesson 94 và 182: tương thích, làm đổi số, và phá vỡ. Quy tắc: **thêm cột thì an toàn, đổi nghĩa một cột mà giữ nguyên tên là mức nguy hiểm nhất vì không có gì báo hiệu**. Quy trình đổi hai giai đoạn cho thay đổi phá vỡ, theo lesson 97: thêm cái mới, chạy song song, thông báo, cho cửa sổ chuyển, rồi mới bỏ cái cũ. Cửa sổ chuyển đủ dài là bao lâu và ai quyết. Phát hiện ai đang dùng cái sắp bỏ: đây là chỗ nhật ký truy vấn và lineage ở M14D trả cổ tức, vì không biết ai dùng thì không dám bỏ gì cả.",
"Thực hiện một thay đổi phá vỡ theo quy trình hai giai đoạn mà không làm bên tiêu thụ nào lỗi.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng việc bên tiêu thụ không lỗi lần nào. Kiểm bằng thí nghiệm đổi có tải; đạt khi không bên tiêu thụ nào lỗi và danh sách người dùng cái cũ được xác định trước khi bỏ.",
"Viết hợp đồng năm phần cho sản phẩm. Thực hiện ba thay đổi ở ba mức. Với thay đổi phá vỡ, xác định ai đang dùng bằng nhật ký truy vấn, chạy quy trình hai giai đoạn với cửa sổ chuyển, và chứng minh không bên nào lỗi. Thực hiện một thay đổi mức hai và chứng minh có thông báo.",
"Đổi nghĩa một cột mà giữ nguyên tên · bỏ cột cũ ngay sau khi thêm cột mới · không biết ai đang dùng · cửa sổ chuyển do kỹ thuật tự đặt.",
"Không bên tiêu thụ nào lỗi qua toàn bộ quá trình, danh sách người dùng được xác định trước khi bỏ, và thay đổi mức hai có thông báo."),

(191,"The documentation hierarchy","TH","Lesson 190",
"Tài liệu cho sản phẩm dữ liệu có bốn tầng phục vụ bốn nhu cầu khác nhau, và viết gộp làm cả bốn không dùng được. Tầng khám phá trả lời sản phẩm này là gì và có phải thứ tôi cần không, đọc trong 30 giây. Tầng bắt đầu trả lời làm sao dùng ngay, gồm ba truy vấn mẫu chạy được. Tầng tham chiếu mô tả từng trường, từng chỉ số, hạt, và độ tươi. Tầng ngữ cảnh giải thích quyết định thiết kế và **hạn chế diễn giải** tức kết luận nào dữ liệu này không cho phép rút ra, phần đã nêu ở lesson 163 và là phần chặn nhiều kết luận sai nhất. Nguyên tắc chung: tài liệu nằm cạnh mã và được rà soát cùng mã, chứ trong một trang wiki rời sẽ lạc hậu sau ba tháng. Ba thứ không nên có trong tài liệu vì chúng chắc chắn lạc hậu.",
"Viết bộ tài liệu bốn tầng và chứng minh người lạ tìm được sản phẩm rồi dùng được trong giới hạn thời gian.",
"Tầng *áp dụng*. Objective đo bằng thời gian và kết quả của người đọc, chứ bằng độ dài tài liệu. Kiểm bằng phép thử tính giờ; đạt khi người lạ quyết định được sản phẩm có phù hợp trong 30 giây và chạy được truy vấn đầu trong 10 phút.",
"Viết bộ tài liệu bốn tầng cho sản phẩm. Nhờ một học viên chưa biết sản phẩm: tính giờ xem họ mất bao lâu để quyết định sản phẩm có phù hợp nhu cầu không, và bao lâu để chạy được truy vấn đầu tiên. Ghi lại mọi chỗ họ phải hỏi.",
"Viết một trang dài cho mọi nhu cầu · bỏ hạn chế diễn giải · để tài liệu trong wiki rời khỏi mã · đưa ảnh chụp màn hình vào tài liệu tham chiếu.",
"Người lạ quyết định được trong 30 giây và chạy được truy vấn đầu trong 10 phút, và bốn tầng tài liệu đều có nội dung."),

(192,"Search, discovery and the findability test","TH","Lesson 191",
"Sản phẩm tốt mà không ai tìm thấy thì bằng không tồn tại, và khả năng tìm thấy là thứ đo được chứ giả định. Bốn yếu tố quyết định: tên đặt theo từ người dùng tìm chứ theo từ kỹ thuật, mô tả một dòng chứa từ khoá họ dùng, nhãn phân loại theo miền nghiệp vụ, và chỉ dấu mức độ tin cậy như đã chứng nhận hay còn thử nghiệm. Phép thử khả năng tìm thấy: cho năm người dùng thật một nhu cầu và tính tỉ lệ họ tìm ra đúng sản phẩm trong ba phút mà không hỏi ai; **tỉ lệ đó là chỉ số, không phải số sản phẩm đã đăng ký trong danh mục**. Ba lý do khiến người dùng dựng bản sao riêng thay vì dùng sản phẩm có sẵn, và cả ba đều là lỗi của khả năng tìm thấy chứ của người dùng. Quan hệ với danh mục dữ liệu ở M14D: danh mục là công cụ, còn khả năng tìm thấy là kết quả.",
"Đo tỉ lệ tìm thấy bằng phép thử với người dùng thật và cải thiện được tỉ lệ đó sau một vòng sửa.",
"Tầng *đánh giá*. Objective đo bằng hành vi người dùng chứ bằng cấu hình công cụ. Kiểm bằng phép thử hai vòng; đạt khi có số đo cả hai vòng và vòng sau cao hơn vòng trước.",
"Chạy phép thử khả năng tìm thấy với năm người, mỗi người một nhu cầu, tính giờ ba phút. Ghi tỉ lệ tìm ra và mọi từ khoá họ đã thử mà không ra kết quả. Sửa tên, mô tả và nhãn theo danh sách đó. Chạy lại với năm người khác và so hai tỉ lệ.",
"Đo bằng số sản phẩm đã đăng ký · đặt tên theo tên bảng kỹ thuật · bỏ chỉ dấu mức tin cậy · kết luận người dùng lười tìm thay vì sửa khả năng tìm thấy.",
"Có tỉ lệ tìm thấy ở cả hai vòng với vòng sau cao hơn, và danh sách từ khoá thất bại được dùng để sửa."),

(193,"Documentation tests","TH","Lesson 192",
"Tài liệu sai còn nguy hiểm hơn không có tài liệu, vì người đọc tin nó. Bốn loại kiểm tự động giữ tài liệu khớp thực tế: mọi cột công khai có mô tả, mọi truy vấn mẫu trong tài liệu chạy được và trả về dòng, mọi chỉ số nhắc trong tài liệu tồn tại trong tầng ngữ nghĩa, và cam kết độ tươi trong tài liệu khớp lịch làm mới thật. Loại thứ hai là loại có giá trị cao nhất và hay bị bỏ: truy vấn mẫu hỏng là thứ người mới gặp đầu tiên và mất niềm tin ngay. Những kiểm tra này chạy trong tích hợp liên tục và chặn hợp nhất theo lesson 96, nên tài liệu không thể lạc hậu quá một lần nộp mã. **Nguyên tắc: tài liệu là mã, nên nó được kiểm như mã.** Ba thứ không kiểm tự động được và cần rà soát người, gồm cả phần hạn chế diễn giải.",
"Dựng bốn loại kiểm tài liệu chạy tự động và chặn được tài liệu lạc hậu ở mức nộp mã.",
"Tầng *áp dụng*. Objective là một cửa chặn tự động có tiêu chí nghiệm thu bằng phép thử tiêm. Kiểm bằng bốn vi phạm tiêm; đạt khi cả bốn bị chặn ở đúng loại kiểm.",
"Viết bốn loại kiểm tài liệu và đưa vào quy trình có cửa chặn. Tiêm bốn vi phạm: thêm cột công khai không mô tả, làm hỏng một truy vấn mẫu, nhắc một chỉ số đã khai tử, và đổi lịch làm mới mà không sửa tài liệu. Xác nhận cả bốn bị chặn. Liệt kê ba thứ phải rà soát bằng người.",
"Chỉ kiểm sự tồn tại của tài liệu chứ không kiểm nội dung · không chạy truy vấn mẫu · để tài liệu ngoài quy trình kiểm · tin rằng kiểm tự động thay được rà soát người.",
"Bốn vi phạm đều bị chặn ở đúng loại kiểm, và ba thứ cần rà soát người được liệt kê rõ."),

(194,"Self-service UX and the enablement boundary","LT","Lesson 193",
"Tự phục vụ là mục tiêu hay được tuyên bố và hiếm khi đạt, vì nó thường bị hiểu thành cấp quyền truy cập cho nhiều người hơn. Bốn điều kiện thật của tự phục vụ: người dùng tìm được sản phẩm theo lesson 192, hiểu được nghĩa mà không hỏi, dùng được mà không viết SQL phức tạp, và tin được số. Thiếu điều kiện nào thì họ quay lại hỏi đội dữ liệu, và khi đó tự phục vụ chỉ tồn tại trên giấy. Ranh giới hỗ trợ: đội dữ liệu chịu trách nhiệm tới đâu và người dùng tự lo từ đâu; ranh giới mơ hồ làm đội dữ liệu thành bộ phận trả lời câu hỏi lặt vặt. Ba mức tự phục vụ theo độ khó câu hỏi, và việc **không phải câu hỏi nào cũng nên tự phục vụ**: câu hỏi cần suy luận nhân quả thì vẫn cần người phân tích, và nói rõ điều đó là trung thực chứ thất bại.",
"Chấm mức tự phục vụ hiện tại theo bốn điều kiện và xác định ranh giới hỗ trợ cho một đội cho trước.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho phép thử khả dụng ở lesson 195. Kiểm bằng bài chấm cộng bài phân loại; đạt khi chấm bốn điều kiện có bằng chứng và phân đúng ít nhất bảy trong mười câu hỏi theo ba mức.",
"Chấm sản phẩm hiện tại theo bốn điều kiện, mỗi điều kiện kèm bằng chứng chứ cảm nhận. Phân mười câu hỏi nghiệp vụ thật vào ba mức tự phục vụ. Viết ranh giới hỗ trợ một trang nêu rõ đội dữ liệu lo gì và người dùng lo gì.",
"Đo tự phục vụ bằng số người có quyền truy cập · hứa mọi câu hỏi đều tự phục vụ được · không có ranh giới hỗ trợ nên đội thành bộ phận hỏi đáp · chấm bằng cảm nhận.",
"Bốn điều kiện được chấm có bằng chứng, phân đúng ≥ 7/10 câu hỏi vào ba mức, và ranh giới hỗ trợ nêu rõ hai phía."),

(195,"Task-based usability testing","TH","Lesson 194",
"Bài đặt ra phương pháp đo duy nhất được chấp nhận trong module này. Phép thử khả dụng theo tác vụ: đưa người dùng thật một tác vụ nghiệp vụ, không hướng dẫn, tính giờ và ghi lại mọi chỗ họ vấp; **không hỏi họ thấy có dễ dùng không**, vì câu trả lời đó không dự đoán được hành vi. Bốn số đo: tỉ lệ hoàn thành, thời gian tới kết quả đúng, số lần phải hỏi người khác, và số lần ra kết quả sai mà họ tin là đúng; số đo thứ tư là số đo quan trọng nhất và hay bị bỏ, vì kết quả sai mà tự tin nguy hiểm hơn không ra kết quả. Cỡ mẫu đủ dùng: năm người phát hiện phần lớn vấn đề nghiêm trọng. Quy trình: chuẩn bị tác vụ, chạy, tổng hợp theo mức nghiêm trọng, sửa, rồi chạy lại vòng hai với người khác.",
"Chạy được hai vòng thử khả dụng và chứng minh bốn số đo cải thiện ở vòng hai.",
"Tầng *đánh giá*. Objective đo bằng hành vi người dùng thật, và đây là tiêu chí nghiệm thu chính của cả module. Kiểm bằng hai vòng thử; đạt khi có đủ bốn số đo ở cả hai vòng và ít nhất ba số cải thiện.",
"Chuẩn bị ba tác vụ nghiệp vụ. Chạy vòng một với năm người, ghi đủ bốn số đo và mọi chỗ vấp. Xếp vấn đề theo mức nghiêm trọng, sửa những cái nghiêm trọng nhất. Chạy vòng hai với năm người khác. So bốn số đo và giải thích chỗ không cải thiện.",
"Hỏi cảm nhận thay vì giao tác vụ · hướng dẫn trong lúc thử · bỏ số đo kết quả sai mà tự tin · chỉ chạy một vòng nên không biết sửa có tác dụng không.",
"Bốn số đo đủ ở cả hai vòng, ≥ 3 số cải thiện, và chỗ không cải thiện có giải thích."),

(196,"Serving, access and security for consumers","TH","Lesson 195",
"Đưa sản phẩm tới người dùng an toàn và đủ nhanh. Ba đường phục vụ và người dùng tương ứng: công cụ BI cho người không viết mã, SQL trực tiếp cho người phân tích, và giao diện lập trình cho hệ khác. Chính sách truy cập kế thừa từ tầng ngữ nghĩa ở lesson 180, nhưng phải kiểm lại ở từng đường vì cấu hình có thể lệch. Ba yêu cầu phi chức năng phải đo: thời gian phản hồi ở phân vị 95, số người dùng đồng thời chịu được, và hành vi khi quá tải, theo lesson 179 và 87. Phân loại dữ liệu và che dữ liệu nhạy cảm cho môi trường không phải sản xuất. Ba lỗi hay gặp khi mở quyền: cấp theo cá nhân thay vì theo vai nên không quản được, cấp quyền tạm rồi quên thu hồi, và sao chép dữ liệu ra ngoài phạm vi kiểm soát. Nhật ký truy cập là đầu vào cho đo mức dùng ở lesson 197.",
"Mở ba đường phục vụ với chính sách nhất quán và đạt ba yêu cầu phi chức năng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu gồm cả bảo mật lẫn hiệu năng. Kiểm bằng phép thử phủ định ở cả ba đường cộng phép thử tải; đạt khi chính sách nhất quán ở ba đường và ba yêu cầu phi chức năng đạt.",
"Mở ba đường phục vụ. Chạy cùng bộ phép thử phủ định ở cả ba và chứng minh kết quả giống nhau. Chạy tải tới ngưỡng người dùng đồng thời mục tiêu và đo ba yêu cầu phi chức năng. Dựng quy trình che dữ liệu cho môi trường thử và kiểm không còn trường định danh.",
"Cấu hình quyền khác nhau ở ba đường · cấp quyền theo cá nhân · chép dữ liệu sản xuất sang môi trường thử chưa che · không đo hành vi khi quá tải.",
"Phép thử phủ định cho kết quả giống nhau ở cả ba đường, ba yêu cầu phi chức năng đạt, và dữ liệu môi trường thử đã che."),

(197,"Adoption metrics that are not vanity","TH","Lesson 196",
"Đo mức dùng sai cách dẫn tới tối ưu sai thứ, nên bài này tách chỉ số hợp lệ khỏi chỉ số phù phiếm. Ba chỉ số phù phiếm và lý do vô nghĩa: số bảng đã dựng đo khối lượng chứ giá trị; số dashboard đã tạo thường tương quan nghịch với chất lượng; số người có quyền truy cập không nói gì về việc họ có dùng không. Bốn chỉ số hợp lệ: số người dùng hoạt động theo tần suất tự nhiên của quyết định, tỉ lệ câu hỏi được trả lời mà không cần đội dữ liệu can thiệp, số quyết định có dẫn chứng từ sản phẩm, và tỉ lệ người dùng quay lại sau lần đầu. Chỉ số thứ hai là chỉ số trung tâm vì nó đo đúng định nghĩa tự phục vụ ở lesson 194. Đo niềm tin: tỉ lệ người dùng tự kiểm chứng lại số bằng nguồn khác là chỉ số nghịch đảo của niềm tin. Ba cách đo làm hỏng hành vi nếu đội bị chấm theo chúng.",
"Chọn bộ chỉ số mức dùng hợp lệ cho một sản phẩm và giải thích vì sao ba chỉ số phù phiếm bị loại.",
"Tầng *đánh giá*. Objective đòi phán đoán về chất lượng của chính phép đo, chứ chỉ đo. Kiểm bằng bài chọn cộng dựng đo; đạt khi loại đúng ba chỉ số phù phiếm và bốn chỉ số hợp lệ đều đo được từ dữ liệu có sẵn.",
"Từ nhật ký truy cập, dựng bốn chỉ số hợp lệ cho sản phẩm. Tính cả ba chỉ số phù phiếm và chỉ ra cụ thể chúng dẫn tới kết luận sai thế nào trên dữ liệu thật của mình. Đo tỉ lệ người dùng tự kiểm chứng lại số. Viết một câu cho mỗi chỉ số nêu hành vi xấu nào sẽ xuất hiện nếu đội bị chấm theo nó.",
"Báo cáo số dashboard như thành tích · đo người dùng hoạt động theo tần suất không khớp nhịp quyết định · bỏ chỉ số niềm tin · chọn chỉ số dễ đo thay vì chỉ số đúng.",
"Bốn chỉ số hợp lệ đo được từ dữ liệu thật, ba chỉ số phù phiếm được chỉ ra dẫn tới kết luận sai thế nào, và mỗi chỉ số có cảnh báo hành vi xấu."),

(198,"Cost to serve","TH","Lesson 197",
"Một sản phẩm dữ liệu có chi phí và không đo thì không biết nó có đáng giữ không. Bốn thành phần chi phí: tính toán để dựng, lưu trữ, tính toán để phục vụ truy vấn, và thời gian người để vận hành cùng hỗ trợ. Thành phần thứ tư thường lớn nhất và hầu như không bao giờ được tính. Chi phí trên mỗi đơn vị giá trị: chia chi phí cho số quyết định được phục vụ hoặc số người dùng hoạt động, và con số đó là thứ so sánh được giữa các sản phẩm. Ba sản phẩm nên cân nhắc khai tử: chi phí cao mà ít người dùng, trùng lặp với sản phẩm khác, và không truy được về quyết định nào theo lesson 187. Quyết định khai tử là quyết định có bên liên quan nên cần quy trình ở lesson 200. Cảnh báo về tối ưu chi phí quá đà: cắt độ tươi để giảm chi phí làm sản phẩm mất giá trị cho quyết định cần dữ liệu mới.",
"Tính chi phí bốn thành phần cho ba sản phẩm và đề xuất khai tử có căn cứ cho ít nhất một cái.",
"Tầng *đánh giá*. Objective đòi nối chi phí với giá trị, chứ chỉ cắt chi phí. Kiểm bằng bảng chi phí ba sản phẩm; đạt khi cả bốn thành phần có số hoặc ước lượng có căn cứ và đề xuất khai tử dẫn được từ bảng.",
"Tính bốn thành phần chi phí cho ba sản phẩm, gồm cả ước lượng thời gian người từ nhật ký hỗ trợ. Tính chi phí trên mỗi đơn vị giá trị. Xếp hạng. Đề xuất khai tử một sản phẩm kèm lập luận và kèm phương án cho người đang dùng nó.",
"Bỏ qua thời gian người · so tổng chi phí giữa các sản phẩm khác quy mô · cắt độ tươi để giảm chi phí mà không hỏi quyết định · đề xuất khai tử mà không có phương án cho người dùng.",
"Bốn thành phần có số hoặc ước lượng có căn cứ cho cả ba sản phẩm, và đề xuất khai tử dẫn được từ bảng kèm phương án thay thế."),

(199,"Reverse ETL and the shadow operational system","LT","Lesson 198",
"Đẩy dữ liệu từ kho phân tích ngược về hệ vận hành là nhu cầu có thật, và cũng là chỗ dễ tạo ra một hệ vận hành ngầm nguy hiểm. Bốn ràng buộc phải tôn trọng khi làm: ranh giới trách nhiệm tức kho phân tích không được trở thành nguồn sự thật cho nghiệp vụ; tính bất biến khi đẩy lại theo lesson 105; quyền riêng tư vì dữ liệu tổng hợp đẩy ngược có thể chứa thông tin không được phép dùng cho mục đích vận hành; và vòng phản hồi tức dữ liệu đẩy về hệ vận hành rồi lại được nạp lên kho tạo vòng lặp làm hỏng phân tích. Vấn đề thứ tư tinh vi nhất và khó phát hiện nhất. Ba dấu hiệu một hệ vận hành ngầm đang hình thành: nghiệp vụ phụ thuộc kho phân tích để chạy quy trình hằng ngày, kho phân tích có cam kết mức dịch vụ của hệ vận hành mà không có năng lực vận hành tương ứng, và không ai biết dữ liệu gốc nằm ở đâu.",
"Nhận ra một hệ vận hành ngầm đang hình thành và nêu bốn ràng buộc phải tôn trọng khi đẩy ngược.",
"Tầng *phân tích*. Objective là nhận ra một rủi ro kiến trúc trước khi nó cố định. Kiểm bằng ba kiến trúc; đạt khi nhận ra đúng ít nhất hai trường hợp có rủi ro và chỉ ra ràng buộc bị vi phạm.",
"Cho ba kiến trúc có đẩy dữ liệu ngược. Với mỗi cái, kiểm bốn ràng buộc và chỉ ra cái nào bị vi phạm. Với kiến trúc có vòng phản hồi, vẽ đường đi của dữ liệu và chỉ ra chỗ vòng lặp hình thành. Đề xuất cách chặn cho từng vi phạm.",
"Coi đẩy ngược là một pipeline bình thường · để kho phân tích thành nguồn sự thật cho nghiệp vụ · không chặn vòng phản hồi · hứa cam kết mức dịch vụ của hệ vận hành trên hạ tầng phân tích.",
"Nhận đúng ≥ 2/3 trường hợp có rủi ro kèm ràng buộc bị vi phạm, và vẽ đúng chỗ vòng phản hồi hình thành."),

(200,"Lifecycle and the operating model","TH","Lesson 199",
"Bài chốt phần quản trị của module. Vòng đời sản phẩm dữ liệu sáu giai đoạn: đề xuất, dựng, chứng nhận, vận hành, khai tử, và gỡ. Điều kiện chuyển giai đoạn lấy từ các bài trước: được chứng nhận khi có đủ tám thuộc tính ở lesson 188, hợp đồng ở lesson 190, tài liệu bốn tầng ở lesson 191, và qua phép thử khả dụng ở lesson 195. Mô hình vận hành: ai trực khi sản phẩm hỏng, cam kết thời gian phản hồi theo mức nghiêm trọng, và kênh nhận phản hồi từ người dùng. Vòng phản hồi vận hành là thứ phân biệt sản phẩm sống với sản phẩm bị bỏ: thu thập câu hỏi người dùng hỏi, phân loại, và dùng chúng làm đầu vào cho việc sửa tài liệu và sửa thiết kế. **Câu hỏi lặp lại nhiều lần là lỗi thiết kế chứ nhu cầu đào tạo**, và đó là cách đọc đúng dữ liệu hỗ trợ.",
"Vận hành vòng đời sáu giai đoạn với cửa chứng nhận và vòng phản hồi đọc được từ dữ liệu hỗ trợ.",
"Tầng *áp dụng*. Objective là một quy trình có cửa chặn và một vòng cải tiến đo được. Kiểm bằng ba sản phẩm đi qua vòng đời; đạt khi sản phẩm thiếu điều kiện bị chặn chứng nhận và câu hỏi lặp lại được chuyển thành thay đổi thiết kế.",
"Dựng vòng đời sáu giai đoạn với danh mục chứng nhận. Đưa ba sản phẩm qua, trong đó một cái thiếu phép thử khả dụng và phải bị chặn. Thu thập câu hỏi người dùng trong hai tuần, phân loại, và chỉ ra ba câu hỏi lặp lại; chuyển chúng thành thay đổi thiết kế chứ tài liệu đào tạo.",
"Chứng nhận sản phẩm chưa qua phép thử khả dụng · trả lời câu hỏi lặp lại bằng cách mở lớp hướng dẫn · không có kênh phản hồi · gỡ sản phẩm khi còn người dùng.",
"Sản phẩm thiếu điều kiện bị chặn chứng nhận, và ba câu hỏi lặp lại được chuyển thành thay đổi thiết kế cụ thể."),

(201,"Capstone - a governed customer health data product","DA","Lesson 200",
"Bài dự án khép module, lấy đúng yêu cầu capstone của hợp đồng nguồn. Dựng một sản phẩm dữ liệu về sức khoẻ khách hàng. Sản phẩm nộp gồm tám hạng mục: phát biểu quyết định bốn phần và cây chỉ số có chủ ở mọi lá; ma trận truy ngược năm mắt; hợp đồng năm phần; giao diện có tập cột công khai tối thiểu; bộ tài liệu bốn tầng có hạn chế diễn giải; chính sách truy cập ba đường có phép thử phủ định; kết quả hai vòng thử khả dụng với bốn số đo; và bảng chi phí bốn thành phần cùng kế hoạch khai tử. Bốn điều kiện tự động không đạt lấy từ phần *Critical failures* của nguồn: có chỉ số không truy được về quyết định, chưa chạy phép thử khả dụng, thiếu hạn chế diễn giải, hoặc dùng chỉ số phù phiếm làm bằng chứng mức dùng.",
"Nộp sản phẩm đủ tám hạng mục, không vi phạm bốn điều kiện tự động không đạt.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một sản phẩm có người dùng thật. Kiểm bằng rà soát tám hạng mục cộng kết quả thử khả dụng; đạt khi hai vòng thử có bốn số đo và vòng hai cải thiện ở ít nhất ba số.",
"Dựng sản phẩm theo tám hạng mục. Chạy hai vòng thử khả dụng với người dùng thật. Trình bày 15 phút và trả lời chất vấn: chỉ số này phục vụ quyết định nào, ai sở hữu lá nào trong cây, và bằng chứng nào cho thấy người khác dùng được.",
"Dựng sản phẩm rồi mới tìm quyết định cho nó · dùng số người có quyền truy cập làm bằng chứng · bỏ phép thử khả dụng vì tốn thời gian · viết hạn chế diễn giải chung chung.",
"Tám hạng mục đầy đủ, hai vòng thử khả dụng có bốn số đo với vòng hai cải thiện ≥ 3 số, và không vi phạm bốn điều kiện tự động không đạt."),

(202,"Gate 5 - defend a metric definition and prove self-service","KT","Lesson 201",
"Cổng của Phase 5, và là cổng đầu tiên kiểm phần năng lực Analytics Engineer. Bài kiểm ba module: mô hình hoá ở M11, ngữ nghĩa và chỉ số ở M11B, và sản phẩm cùng tự phục vụ ở M11C. Không có nội dung mới.",
"Bảo vệ một định nghĩa chỉ số trước chất vấn, chứng minh nó không đếm trùng, và trình ra bằng chứng người khác dùng được sản phẩm.",
"Tầng *đánh giá*. Cổng đo năng lực thiết kế và bảo vệ dưới chất vấn, nên hình thức là bảo vệ trực tiếp có đối soát tại chỗ.",
"Buổi 120 phút: 75 phút làm bài độc lập, 45 phút chữa bài. Bài chấm sáu phần: A (20đ) phát biểu hạt cho mọi bảng và chứng minh bằng phép đếm · B (25đ) hợp đồng sáu phần cho ba chỉ số, và đối soát với truy vấn do hội đồng viết từ hợp đồng, khớp ở ba mức gộp · C (20đ) chứng minh không đếm trùng bằng bốn bước, gồm một chỉ số có bẫy vực cài sẵn · D (15đ) ma trận tương thích chỉ số nhân chiều, cưỡng chế được bằng máy · E (15đ) bằng chứng thử khả dụng theo tác vụ với bốn số đo · F (5đ) truy ngược một chỉ số bất kỳ về quyết định nghiệp vụ.",
"Dùng số dashboard làm bằng chứng tự phục vụ · đối soát bằng truy vấn do chính mình viết · bỏ phần truy ngược vì hết giờ · khai báo chỉ số theo cột có sẵn.",
"Đạt ≥ 70/100, phần B và C đều ≥ 60%. Chỉ số nào không khớp đối soát của hội đồng thì phần B của chỉ số đó bằng không; bằng chứng tự phục vụ bằng chỉ số phù phiếm thì phần E bằng không."),
]
