# -*- coding: utf-8 -*-
"""ADE Phase 6: M12 OLAP internals + M13 File, serialization and table formats."""

M12 = ("OLAP Internals and Analytical Engines", 203, 216, """| | |
|---|---|
| **Objective cấp module** | Giải thích vì sao hệ cột, xử lý theo lô véctơ và kiến trúc phân tán nhanh, rồi chọn engine theo khối lượng công việc, vận hành và chi phí |
| **Tiền đề** | M4 · M9 · M10 · M11 |
| **Exit criterion** | Đọc được kế hoạch có quét, cắt tỉa, trao đổi dữ liệu, kết và tràn đĩa; truy được ba tầng song song lồng nhau gồm tác vụ MIMD, toán tử xử lý theo lô và làn véctơ; mọi khuyến nghị engine gắn với bằng chứng đo được chứ danh sách tính năng |
| **Kỹ năng SFIA** | `DBAD` mức 4 · `SYSP` mức 4 |
| **Chế độ hỏng** | Chọn engine bằng danh sách tính năng của nhà cung cấp, và so tốc độ giữa một lần chạy có đệm nóng với một lần chạy đệm lạnh |""",
"""Module này trả lời câu hỏi vì sao một truy vấn quét mười tỉ dòng xong trong vài giây, và nó trả lời bằng bốn cơ chế độc lập chứ bằng một lời giải thích chung.

Bốn cơ chế: bố cục theo cột giảm lượng byte phải đọc, mã hoá và nén giảm tiếp, thống kê theo khối cho phép bỏ qua phần lớn dữ liệu mà không đọc, và xử lý theo lô véctơ giảm chi phí trên mỗi dòng. **Tách riêng bốn phần đóng góp là yêu cầu bắt buộc của module**, vì gộp chúng lại thì không tối ưu được cái nào.

Mô hình chi phí bộ nhớ ở lesson 45 và bố cục theo hàng hay theo cột ở lesson 47 nay được áp vào quy mô kho dữ liệu.""")

L12 = [
(203,"OLTP against OLAP - the workload is the difference","LT","Module 12: M11",
"Hai hệ khác nhau ở khối lượng công việc chứ ở công nghệ, và hiểu đúng khác biệt đó giải thích mọi quyết định thiết kế còn lại. Năm chiều so sánh: một truy vấn chạm bao nhiêu dòng, bao nhiêu cột, tỉ lệ đọc trên ghi, yêu cầu độ trễ, và số người dùng đồng thời. Hệ giao dịch đọc ít dòng nhiều cột với độ trễ mili giây và đồng thời cao; hệ phân tích quét rất nhiều dòng ít cột với độ trễ giây và đồng thời thấp hơn nhiều. Từ năm chiều đó suy ra vì sao hệ phân tích chọn bố cục cột, chọn nén mạnh, và chấp nhận cập nhật từng dòng đắt. Hệ lai và giới hạn thật của nó. Ba dấu hiệu một khối lượng công việc bị đặt nhầm hệ, và chi phí của việc chạy báo cáo phân tích thẳng trên cơ sở dữ liệu giao dịch, vấn đề đã gặp ở M10.",
"Phân loại khối lượng công việc theo năm chiều và suy ra hệ phù hợp kèm lý do cơ chế.",
"Tầng *hiểu*. Bài mở module, đặt khung giải thích cho mười bài sau. Kiểm bằng bài phân loại sáu khối lượng công việc; đạt khi phân đúng ít nhất năm và lý do dẫn được về năm chiều chứ về tên sản phẩm.",
"Cho sáu mô tả khối lượng công việc, trong đó hai cái nằm ở ranh giới. Chấm từng cái theo năm chiều và suy ra hệ phù hợp. Với hai ca ranh giới, nêu hai điều kiện đẩy nó về mỗi phía. Đo một truy vấn phân tích chạy trên cơ sở dữ liệu giao dịch và trên hệ cột, ghi lại chênh lệch.",
"Phân loại theo tên sản phẩm thay vì theo khối lượng công việc · giả định hệ phân tích luôn nhanh hơn · bỏ qua chiều đồng thời · chạy báo cáo nặng trên bản sao đọc rồi tưởng đã tách tải.",
"Phân đúng ≥ 5/6 khối lượng công việc, lý do dẫn về năm chiều, và có số đo chênh lệch giữa hai hệ."),

(204,"Row and column layout","TH","Lesson 203",
"Bài đưa bố cục dữ liệu ở lesson 47 lên quy mô tệp và đo từng phần đóng góp. Bố cục theo hàng đặt mọi cột của một dòng cạnh nhau, nên đọc một dòng đủ cột thì rẻ; bố cục theo cột đặt mọi giá trị của một cột cạnh nhau, nên đọc ba cột trong bảng trăm cột chỉ chạm phần dữ liệu của ba cột đó. Tỉ lệ byte đọc **không bằng đúng tỉ lệ số cột**, vì mỗi cột có kích thước khác nhau, có mã hoá khác nhau, và tệp còn phần siêu dữ liệu đọc trong mọi trường hợp; lab bài này đo tỉ lệ thật rồi giải thích vì sao nó lệch khỏi tỉ lệ số cột. **Đây là phần đóng góp thứ nhất và phải đo riêng**, trước khi bật nén hay cắt tỉa. Hệ quả kéo theo: cập nhật một dòng trong hệ cột phải chạm mọi tệp cột, nên đắt hơn nhiều lần; đó là lý do hệ phân tích ưa thêm mới rồi hợp nhất hơn sửa tại chỗ, nối với cây hợp nhất có cấu trúc nhật ký ở lesson 135. Lợi ích phụ của bố cục cột và là lý do nén hiệu quả hơn: giá trị cùng cột cùng kiểu và thường giống nhau. Chọn cột dư thừa làm mất lợi ích và đây là lỗi hay gặp nhất.",
"Đo riêng phần đóng góp của bố cục cột trên cùng dữ liệu, tách khỏi nén và cắt tỉa.",
"Tầng *áp dụng*. Objective đòi cô lập một biến, nên thiết kế đo phải tắt các cơ chế còn lại. Kiểm bằng phép đo có đối chứng; đạt khi lượng byte đọc được giải thích bằng tỉ lệ số cột chọn và sai số dưới mức thoả thuận.",
"Ghi cùng một bảng trăm cột ở hai bố cục, tắt nén ở cả hai. Chạy bốn truy vấn chọn lần lượt 1, 3, 10 và 100 cột. Đo lượng byte đọc và thời gian. Vẽ quan hệ giữa số cột chọn và lượng byte đọc, kiểm nó tuyến tính ở bố cục cột và phẳng ở bố cục hàng. Đo chi phí cập nhật một dòng ở cả hai.",
"Bật nén khi đo bố cục nên không tách được phần đóng góp · chọn toàn bộ cột rồi kết luận hệ cột không nhanh hơn · đo thời gian mà không đo byte đọc · so hai bố cục ở hai bộ dữ liệu khác nhau.",
"Quan hệ số cột chọn với byte đọc tuyến tính ở bố cục cột và phẳng ở bố cục hàng, và có số đo chi phí cập nhật một dòng."),

(205,"Encoding and compression","TH","Lesson 204",
"Phần đóng góp thứ hai, và nó phụ thuộc vào dữ liệu chứ vào thuật toán được chọn. Bốn cách mã hoá và điều kiện mỗi cách thắng: mã hoá từ điển thắng khi số giá trị phân biệt thấp; mã hoá độ dài chạy thắng khi giá trị lặp liên tiếp, nên **nó phụ thuộc thứ tự sắp xếp** và đây là liên hệ trực tiếp tới lesson 209; đóng gói bit thắng khi miền giá trị hẹp; mã hoá sai phân thắng với dãy tăng dần như dấu thời gian. Nén khối đặt trên mã hoá và đánh đổi giữa tỉ lệ nén với thời gian giải nén, nên nén mạnh nhất thường không phải lựa chọn nhanh nhất vì nút cổ chai chuyển từ đĩa sang bộ xử lý. Bitmap giá trị rỗng và cách nó tách rỗng khỏi giá trị. Lợi ích thứ hai của từ điển: engine tính trực tiếp trên mã từ điển mà không giải nén, nội dung của lesson 207.",
"Chọn cách mã hoá theo đặc trưng dữ liệu và chứng minh lựa chọn bằng cặp số kích thước với thời gian giải nén.",
"Tầng *áp dụng*. Objective là một quyết định có hai ràng buộc đối nghịch. Kiểm bằng ma trận cách mã hoá nhân đặc trưng dữ liệu; đạt khi mỗi ô có cặp số và lựa chọn cho mỗi cột dẫn được từ ma trận.",
"Tạo bốn cột có bốn đặc trưng khác nhau. Ghi mỗi cột bằng cả bốn cách mã hoá cộng ba mức nén khối. Đo kích thước và thời gian giải nén. Lập ma trận. Sắp lại bảng theo một cột và đo lại độ dài chạy để chứng minh nó phụ thuộc thứ tự. Chọn cấu hình cho từng cột và chứng minh tổng thời gian truy vấn giảm.",
"Bật nén mạnh nhất cho mọi cột · dùng từ điển cho cột gần như duy nhất · đo kích thước mà không đo thời gian giải nén · quên rằng độ dài chạy phụ thuộc thứ tự sắp xếp.",
"Ma trận có cặp số ở mọi ô, hiệu ứng thứ tự sắp xếp lên độ dài chạy được chứng minh, và cấu hình chọn làm giảm tổng thời gian truy vấn."),

(206,"Zone maps, statistics and pruning","TH","Lesson 205",
"Phần đóng góp thứ ba và thường là phần lớn nhất: không đọc còn rẻ hơn mọi cách đọc nhanh. Mỗi khối dữ liệu mang thống kê gồm giá trị nhỏ nhất, lớn nhất, số dòng và số giá trị rỗng; engine so điều kiện lọc với thống kê để bỏ qua cả khối mà không mở. Hiệu quả phụ thuộc hoàn toàn vào tương quan giữa cột lọc với thứ tự lưu: nếu dữ liệu sắp theo dấu thời gian thì lọc theo dấu thời gian cắt được gần hết, còn lọc theo một cột rải đều thì mỗi khối đều chứa cả miền giá trị nên không cắt được gì. **Cắt tỉa không xảy ra là chế độ hỏng im lặng phổ biến nhất**, và ba nguyên nhân là bọc cột trong hàm, lệch kiểu dữ liệu, và điều kiện không so trực tiếp; đây chính là tính bám chỉ mục ở lesson 131 dưới một dạng khác. Rủi ro cắt nhầm khi thống kê sai hoặc quy tắc so sánh chuỗi khác nhau giữa bên ghi và bên đọc.",
"Đo tỉ lệ khối bị cắt tỉa cho từng truy vấn và sửa được ba trường hợp cắt tỉa không xảy ra.",
"Tầng *phân tích*. Objective đòi nhận ra một cơ chế không hoạt động mà truy vấn vẫn trả đúng kết quả. Kiểm bằng số khối đọc trong kế hoạch; đạt khi ba trường hợp hỏng được sửa và tỉ lệ cắt tỉa tăng có số đo ở cả ba.",
"Ghi bảng có thống kê theo khối. Chạy sáu truy vấn và đọc số khối bị cắt từ kế hoạch. Ba truy vấn cố ý làm cắt tỉa thất bại theo ba nguyên nhân; sửa từng cái và đo lại. Ghi cùng dữ liệu theo hai thứ tự sắp xếp khác nhau và so tỉ lệ cắt tỉa cho cùng bộ truy vấn.",
"Tin cắt tỉa đang xảy ra vì truy vấn nhanh · bọc cột lọc trong hàm · so cột kiểu chuỗi với giá trị kiểu số · đánh giá cắt tỉa mà không đọc số khối trong kế hoạch.",
"Ba trường hợp cắt tỉa thất bại được sửa với tỉ lệ cắt tỉa tăng có số đo, và hiệu ứng thứ tự sắp xếp lên cắt tỉa được định lượng."),

(207,"Vectorized execution and late materialization","LT","Lesson 206",
"Phần đóng góp thứ tư, nằm ở tầng thực thi chứ tầng lưu trữ. Mô hình xử lý từng dòng trả một dòng mỗi lần gọi, nên chi phí gọi hàm và rẽ nhánh đè lên chi phí tính thật. Mô hình theo lô véctơ xử lý một nghìn giá trị mỗi lần gọi, nên chi phí trên mỗi dòng giảm mạnh và vòng lặp chặt tận dụng được dòng đệm cùng lệnh một chỉ thị nhiều dữ liệu theo lesson 46. Véctơ chọn lọc: thay vì sao chép dòng sau khi lọc, engine giữ một mảng chỉ số để tránh chép dữ liệu. Vật chất hoá muộn: chỉ đọc cột cần cho điều kiện lọc trước, lọc xong mới đọc các cột còn lại của những dòng sống sót; với bộ lọc chọn ít dòng thì lượng byte đọc giảm thêm nhiều lần. Thực thi trên mã từ điển: so sánh trên mã nguyên thay vì trên chuỗi, và giải nén đặt càng muộn càng tốt. Sinh mã tại thời điểm chạy ở mức nhận biết.",
"Giải thích bốn cơ chế thực thi và suy ra điều kiện mỗi cơ chế mất tác dụng.",
"Tầng *hiểu*. Bài lý thuyết khép phần cơ chế, chuẩn bị cho phần phân tán. Kiểm bằng bài lập luận bốn tình huống; đạt khi chỉ đúng cơ chế mất tác dụng ở ít nhất ba và lý do dẫn về cơ chế chứ về cấu hình.",
"Cho bốn tình huống: bộ lọc chọn gần hết số dòng, cột có kiểu phức hợp, hàm do người dùng viết chen giữa, và bảng rất hẹp. Với mỗi cái, chỉ ra cơ chế nào mất tác dụng và vì sao. Đo một truy vấn có hàm do người dùng viết so với bản viết bằng biểu thức có sẵn.",
"Nghĩ xử lý theo lô là một cấu hình bật được · giả định vật chất hoá muộn luôn thắng · chen hàm tự viết vào vòng lặp nóng · bỏ qua chi phí chuyển đổi kiểu giữa các tầng.",
"Chỉ đúng cơ chế mất tác dụng ở ≥ 3/4 tình huống, và có số đo cho ảnh hưởng của hàm do người dùng viết."),

(208,"Vectorized execution is not SIMD","TH","Lesson 207",
"Bài sửa một nhầm lẫn làm sai mọi lập luận hiệu năng về sau. Thực thi theo lô véctơ là một quyết định ở tầng engine: xử lý một lô giá trị mỗi lần gọi thay vì một dòng, nên chi phí gọi hàm và rẽ nhánh trên mỗi dòng giảm; lợi ích này có ngay cả khi không lệnh véctơ nào của bộ xử lý được dùng. Một lệnh nhiều dữ liệu là một cơ chế của phần cứng theo lesson 48. **Thực thi theo lô tạo điều kiện cho lệnh véctơ chứ đồng nghĩa với nó**, và trong nhiều engine phần lớn mức tăng đến từ việc giảm chi phí trên mỗi dòng chứ từ làn véctơ. Bốn thứ ở tầng engine quyết định làn véctơ có được dùng hiệu quả không: kích thước lô, mặt nạ chọn lọc và mặt nạ giá trị rỗng, phần đuôi, và biểu thức lọc nhiều rẽ nhánh. Ranh giới vật chất hoá và đường thu thập rải rác làm mất lợi ích, đúng như lesson 49.",
"Tách phần đóng góp của xử lý theo lô khỏi phần đóng góp của lệnh véctơ trên cùng một phép toán.",
"Tầng *phân tích*. Objective đòi tách hai cơ chế thường bị gộp thành một lời giải thích. Kiểm bằng ba cấu hình đo song song; đạt khi hai phần đóng góp được tách bằng số và mức tăng thấp ở lô nhỏ được giải thích.",
"Chạy cùng một phép tổng hợp ở ba cấu hình: xử lý từng dòng, xử lý theo lô nhưng tắt lệnh véctơ, và xử lý theo lô có lệnh véctơ. Đo thời gian cùng số chu kỳ trên mỗi dòng ở từng cấu hình. Lặp lại với bốn kích thước lô và với một biểu thức lọc nhiều rẽ nhánh. Giải thích vì sao lô nhỏ làm mức tăng sụt.",
"Nói hệ cột nhanh vì dùng lệnh véctơ mà không tách hai cơ chế · đo ở một kích thước lô duy nhất · bỏ qua mặt nạ giá trị rỗng khi giải thích · kết luận từ thời gian tổng mà không có số chu kỳ trên mỗi dòng.",
"Hai phần đóng góp được tách bằng số ở cả bốn kích thước lô, và mức sụt ở lô nhỏ được giải thích bằng cơ chế."),

(209,"Partitioning, clustering and sort order","TH","Lesson 208",
"Ba cách bố trí dữ liệu quyết định cắt tỉa ở lesson 206 có hiệu quả hay không, và cả ba đều là quyết định có chi phí. Phân vùng chia dữ liệu theo giá trị một cột thành các nhóm tách biệt; nó cắt tỉa mạnh nhất nhưng **phân vùng theo cột có số giá trị phân biệt cao tạo ra hàng triệu tệp nhỏ**, và khi đó chi phí siêu dữ liệu cùng chi phí mở tệp vượt xa lợi ích, đây là lỗi nghiêm trọng nhất của module. Quy tắc thực dụng: chọn cột phân vùng sao cho mỗi phân vùng đủ lớn, và số phân vùng nằm trong khoảng quản được. Gom cụm và sắp xếp bố trí dữ liệu trong phân vùng, cho cắt tỉa mịn hơn mà không nhân số tệp. Sắp theo nhiều cột và vì sao thứ tự cột quan trọng, giống hệt lập luận về chỉ mục tổ hợp ở lesson 129. Hình phạt tệp nhỏ và cách đo nó tách khỏi chi phí quét.",
"Chọn cách bố trí cho ba khối lượng công việc và chứng minh bằng số cả lợi ích cắt tỉa lẫn hình phạt tệp nhỏ.",
"Tầng *đánh giá*. Objective đòi cân hai hiệu ứng ngược chiều, và chống lại quy tắc phân vùng theo cột hay lọc. Kiểm bằng ba phương án đo song song; đạt khi cả lợi ích lẫn hình phạt đều có số và lựa chọn dẫn được từ hai số đó.",
"Ghi cùng dữ liệu theo ba phương án: phân vùng theo cột ít giá trị, phân vùng theo cột nhiều giá trị, và phân vùng thô cộng sắp xếp trong phân vùng. Đo số tệp, kích thước tệp trung bình, thời gian liệt kê siêu dữ liệu, và thời gian bộ năm truy vấn. Chỉ ra phương án hai tạo bao nhiêu tệp và chi phí thêm bao nhiêu.",
"Phân vùng theo cột chỉ vì hay lọc theo nó · không đo số tệp sinh ra · sắp theo nhiều cột mà không cân nhắc thứ tự · bỏ qua thời gian liệt kê siêu dữ liệu khi đo.",
"Ba phương án có đủ bốn số đo, hình phạt tệp nhỏ được định lượng, và lựa chọn dẫn được từ cặp lợi ích với chi phí."),

(210,"MPP - coordinator, fragments and exchange","LT","Lesson 209",
"Từ một máy sang nhiều máy, và bài này giải thích một truy vấn được chia ra sao. Bộ điều phối phân tích câu lệnh, lập kế hoạch, rồi cắt kế hoạch thành các mảnh; mỗi mảnh chạy song song trên nhiều nút; giữa hai mảnh là một bước trao đổi dữ liệu qua mạng. **Bước trao đổi dữ liệu là chỗ tốn nhất**, vì nó là chỗ duy nhất dữ liệu đi qua mạng, nên đọc kế hoạch phân tán là tìm các bước trao đổi trước tiên. Ba cách phân bố dữ liệu giữa các nút và hệ quả: theo băm của một cột cho phép kết cục bộ nếu hai bảng cùng băm theo cột kết, theo khoảng, và ngẫu nhiên. Kết cục bộ là mục tiêu và nó chỉ đạt được khi thiết kế bố cục dữ liệu khớp với cách kết. Vì sao thêm nút không tự động làm nhanh hơn: nếu nút cổ chai là bước trao đổi hoặc là một nút lệch tải thì thêm nút làm tệ hơn.",
"Đọc kế hoạch phân tán, chỉ ra các bước trao đổi dữ liệu, và suy ra thêm nút có giúp không.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho bài thực hành về lệch tải. Kiểm bằng bài đọc ba kế hoạch; đạt khi chỉ đúng bước trao đổi ở cả ba và dự đoán đúng hiệu ứng thêm nút ở ít nhất hai.",
"Cho ba kế hoạch phân tán của cùng một truy vấn ở ba cách bố trí dữ liệu. Với mỗi cái, chỉ ra mảnh, bước trao đổi và lượng dữ liệu qua mạng. Dự đoán hiệu ứng khi gấp đôi số nút, rồi chạy thật và so với dự đoán.",
"Cho rằng thêm nút luôn làm nhanh hơn · bỏ qua lượng dữ liệu qua mạng khi đọc kế hoạch · nhầm song song trong một nút với phân tán giữa các nút · thiết kế bố cục mà không xem cách kết.",
"Chỉ đúng bước trao đổi ở cả ba kế hoạch, và dự đoán hiệu ứng thêm nút khớp thực tế ở ≥ 2/3."),

(211,"MPP as distributed MIMD and SPMD - the strong-scaling lab","TH","Lesson 210",
"Bài đặt kiến trúc phân tán của engine phân tích vào đúng khung phân loại đã học ở lesson 48. Một cụm xử lý là bộ nhớ phân tán nhiều lệnh nhiều dữ liệu: mỗi nút có dòng lệnh, thời điểm và chế độ hỏng độc lập. Kế hoạch vật lý thường theo khuôn mẫu một chương trình nhiều dữ liệu: cùng một mảnh toán tử chạy trên nhiều phân vùng, nhưng mỗi bản chạy độc lập nên chênh lệch thời gian giữa chúng là chuyện bình thường chứ bất thường. Từ đó dựng được **hệ phân cấp ba tầng phải truy được**: tiến trình hoặc tác vụ ở tầng nhiều lệnh nhiều dữ liệu, toán tử xử lý theo lô ở tầng engine, và làn véctơ ở tầng phần cứng; mức tăng quan sát được phải quy được về đúng tầng. Rào đồng bộ và bước trao đổi dữ liệu là điểm mà một nút chậm kéo cả truy vấn theo. Thí nghiệm tăng quy mô cố định khối lượng và tăng số nút, rồi tìm trần.",
"Truy được hệ phân cấp ba tầng trên một truy vấn thật và tìm trần khi tăng số nút bằng số đo.",
"Tầng *phân tích*. Objective đòi quy mức tăng về đúng tầng thay vì gộp. Kiểm bằng thí nghiệm tăng quy mô; đạt khi hiệu suất song song được đo ở ít nhất bốn mức và trần được quy về một trong bốn nguyên nhân bằng bằng chứng.",
"Chạy cùng một truy vấn với 1, 2, 4 và 8 nút; tính tăng tốc và hiệu suất song song ở mỗi mức. Tách thời gian tính, thời gian trao đổi dữ liệu và thời gian chờ rào đồng bộ. Tìm mức mà thêm nút không còn giúp và quy trần về phần tuần tự, lệch tải, truyền thông hay nút cổ chai bên ngoài. Với một tác vụ, truy tiếp xuống tầng lô và tầng làn theo lesson 208.",
"Báo cáo tăng tốc mà không báo hiệu suất song song · thêm nút khi trần là nguồn dữ liệu bên ngoài · coi chênh lệch thời gian giữa các tác vụ là lỗi · gộp ba tầng song song thành một lời giải thích.",
"Hiệu suất song song có số đo ở ≥ 4 mức nút, trần được quy về một nguyên nhân có bằng chứng, và hệ phân cấp ba tầng truy được trên một tác vụ."),

(212,"Broadcast, repartition, skew and spill","TH","Lesson 211",
"Bốn hiện tượng quyết định một truy vấn phân tán chạy được hay không. Kết phát tán gửi bảng nhỏ tới mọi nút rồi kết cục bộ; nhanh khi bảng nhỏ thật, và **tràn bộ nhớ khi engine ước lượng sai kích thước bảng nhỏ**, một hệ quả trực tiếp của sai số ước lượng lực lượng ở lesson 128. Kết phân bố lại băm cả hai bảng theo cột kết rồi kết từng phần; tốn mạng nhưng chịu được bảng lớn. Lệch tải xảy ra khi một giá trị khoá chiếm phần lớn số dòng, nên một nút nhận gần hết việc còn các nút khác chờ; triệu chứng là một tác vụ chạy lâu gấp nhiều lần phần còn lại. Ba cách xử lý lệch tải và đánh đổi của từng cách. Tràn đĩa khi bộ nhớ làm việc không đủ, và nhận ra tràn đĩa trong kế hoạch là kỹ năng chẩn đoán chính; tràn đĩa không phải lỗi mà là cơ chế sống sót, nhưng nó làm chậm nhiều lần.",
"Tái hiện cả bốn hiện tượng và chẩn đoán được từng cái từ kế hoạch cùng số đo.",
"Tầng *phân tích*. Objective đòi nối triệu chứng với nguyên nhân trong hệ phân tán. Kiểm bằng bốn tình huống tái hiện; đạt khi chẩn đoán đúng cả bốn từ bằng chứng và sửa được ít nhất ba với số đo trước sau.",
"Ép kết phát tán trên một bảng đủ lớn để tràn bộ nhớ. Ép kết phân bố lại và đo lượng dữ liệu qua mạng. Làm lệch một khoá tới mức chiếm phần lớn số dòng và quan sát tác vụ chạy lâu. Giảm bộ nhớ làm việc để gây tràn đĩa. Với mỗi hiện tượng, chỉ ra bằng chứng trong kế hoạch và số đo, rồi sửa.",
"Ép kết phát tán mà không kiểm kích thước thật · kết luận truy vấn chậm mà không tách lệch tải khỏi tràn đĩa · tăng bộ nhớ để che lệch tải · sửa mà không đo lại.",
"Bốn hiện tượng được tái hiện và chẩn đoán đúng từ bằng chứng, và ≥ 3 được sửa với số đo trước sau."),

(213,"Shared-nothing against separated storage and compute","LT","Lesson 212",
"Hai kiến trúc và hệ quả vận hành khác nhau hoàn toàn. Kiến trúc không chia sẻ gắn dữ liệu với nút, nên đọc cục bộ nhanh nhưng thay đổi quy mô đòi phân bố lại dữ liệu, tức một thao tác nặng và có rủi ro. Kiến trúc tách lưu trữ khỏi tính toán đặt dữ liệu trên kho đối tượng và cho cụm tính toán co giãn độc lập; đổi lại mọi lần đọc đi qua mạng nên đệm trở thành thành phần quyết định hiệu năng. Ba hệ quả của việc tách: nhiều cụm tính toán đọc cùng dữ liệu nên cô lập được các khối lượng công việc; dừng cụm khi không dùng nên chi phí theo mức dùng; và đệm lạnh làm lần chạy đầu chậm hơn nhiều lần, điều làm mọi phép so tốc độ thành vô nghĩa nếu không kiểm soát trạng thái đệm. **So sánh đệm nóng với đệm lạnh là lỗi đo lường nghiêm trọng nhất của module.** Siêu dữ liệu và danh mục là thành phần dùng chung, nên nó cũng là điểm nghẽn và điểm hỏng.",
"Chỉ ra hệ quả vận hành của mỗi kiến trúc và thiết kế được một phép đo công bằng về trạng thái đệm.",
"Tầng *hiểu*. Bài lý thuyết chuẩn bị cho phần chi phí và phần chọn engine. Kiểm bằng bài thiết kế phép đo; đạt khi phép đo kiểm soát được trạng thái đệm và chênh lệch nóng lạnh được định lượng.",
"Chạy cùng bộ truy vấn ở đệm lạnh và đệm nóng, đo chênh lệch. Thiết kế một quy trình đo công bằng nêu rõ trạng thái đệm được đặt thế nào trước mỗi lần chạy. Cho hai tình huống thay đổi quy mô và suy ra thao tác cần làm ở mỗi kiến trúc.",
"So một lần chạy nóng với một lần chạy lạnh · quên rằng siêu dữ liệu là thành phần dùng chung có thể nghẽn · giả định tách lưu trữ và tính toán luôn rẻ hơn · thay đổi quy mô cụm không chia sẻ mà không tính thời gian phân bố lại.",
"Chênh lệch đệm nóng và đệm lạnh được định lượng, và quy trình đo nêu rõ cách đặt trạng thái đệm trước mỗi lần chạy."),

(214,"Workload management, concurrency and cache","TH","Lesson 213",
"Một truy vấn chạy nhanh khi chạy một mình không nói gì về hành vi khi hai mươi người cùng chạy. Ba cơ chế quản lý: hàng đợi, đơn vị tính toán được cấp, và cô lập giữa các nhóm khối lượng công việc. Khi nhu cầu vượt năng lực thì hệ có hai hành vi khác nhau và phải chọn trước: xếp hàng làm độ trễ tăng, hoặc chia nhỏ tài nguyên làm mọi truy vấn chậm đều. Tách thời gian chờ khỏi thời gian chạy là kỹ năng chẩn đoán chính, vì hai nguyên nhân đó cần hai cách sửa hoàn toàn khác nhau và nhầm chúng dẫn tới mở rộng sai chỗ. Đệm kết quả và đệm dữ liệu là hai thứ khác nhau; đệm kết quả chỉ trúng khi truy vấn giống hệt, nên tỉ lệ trúng cao bất thường thường là dấu hiệu đang đo sai. Tự tạm dừng cụm và đánh đổi giữa chi phí với độ trễ lần chạy đầu. Bốn số phải theo dõi theo lesson 110 và 179.",
"Tách được thời gian chờ khỏi thời gian chạy dưới tải và chọn đúng cách sửa cho hai tình huống.",
"Tầng *phân tích*. Objective đòi phân giải một triệu chứng gộp thành hai nguyên nhân cần hai cách sửa khác nhau. Kiểm bằng hai tình huống; đạt khi tách đúng hai thành phần thời gian ở cả hai và cách sửa chọn đúng.",
"Chạy tải tăng dần tới khi hàng đợi hình thành. Đo và tách thời gian chờ khỏi thời gian chạy ở từng mức tải. Tạo hai tình huống: một cái nghẽn vì hàng đợi, một cái nghẽn vì truy vấn nặng. Chọn cách sửa cho từng cái và chứng minh cách sửa của tình huống này không giúp gì cho tình huống kia.",
"Đo thời gian tổng mà không tách chờ · mở rộng cụm để chữa một truy vấn viết kém · để đệm kết quả làm sai phép đo · không cô lập nhóm khối lượng công việc nên báo cáo nặng chặn truy vấn tương tác.",
"Hai thành phần thời gian tách được ở mọi mức tải, và cách sửa của mỗi tình huống được chứng minh không áp dụng cho tình huống kia."),

(215,"The cost model of an analytical engine","TH","Lesson 214",
"Chi phí là một ràng buộc thiết kế chứ một con số nhìn cuối tháng. Năm thành phần: lượng byte quét, thời gian tính toán, đơn vị tính toán được cấp nhân thời gian chạy, lưu trữ, và truyền dữ liệu ra ngoài. Các engine tính tiền theo mô hình khác nhau, nên **cùng một khối lượng công việc có thứ hạng chi phí đảo ngược giữa hai engine**, và đó là lý do không so được bằng đơn giá. Cách so đúng: dựng một khối lượng công việc đại diện rồi tính tổng chi phí sở hữu cho từng engine, gồm cả thời gian người vận hành. Ba đòn bẩy giảm chi phí theo thứ tự hiệu quả: giảm byte quét bằng cắt tỉa và chọn cột, giảm thời gian tính bằng viết lại truy vấn, rồi mới tới chỉnh kích thước cụm. Chi phí truyền ra ngoài hay bị quên và là nguồn hoá đơn bất ngờ. Đặt hạn mức và cảnh báo trước khi chạy khối lượng công việc mới.",
"Tính chi phí cho một khối lượng công việc trên hai mô hình tính tiền và chỉ ra thứ hạng có thể đảo ngược.",
"Tầng *áp dụng*. Objective đòi tính chi phí theo mô hình chứ tra bảng giá. Kiểm bằng bài tính hai mô hình; đạt khi tính đúng cả năm thành phần và chỉ ra được điều kiện làm thứ hạng đảo ngược.",
"Dựng một khối lượng công việc gồm ba loại truy vấn với tần suất khác nhau. Tính năm thành phần chi phí theo hai mô hình tính tiền. Tìm điểm mà thứ hạng đảo ngược khi đổi tần suất hoặc lượng dữ liệu. Áp ba đòn bẩy giảm chi phí theo thứ tự và đo mức giảm của từng đòn bẩy.",
"So engine bằng đơn giá · bỏ thành phần truyền dữ liệu ra ngoài · bỏ thời gian người vận hành khỏi tổng chi phí · tăng kích thước cụm trước khi sửa truy vấn.",
"Năm thành phần được tính cho cả hai mô hình, điểm đảo ngược thứ hạng được chỉ ra, và ba đòn bẩy có mức giảm riêng."),

(216,"Engine selection - five archetypes, one ADR","DA","Lesson 215",
"Bài dự án khép module. Năm nguyên mẫu engine và điều kiện thắng của từng cái: kho dữ liệu đám mây được quản lý thắng khi cần quản trị cùng khả năng co giãn với chi phí là mô hình tính tiền và mức phụ thuộc nhà cung cấp; kho theo kiểu hồ dữ liệu thắng khi dùng chung với học máy và dòng dữ liệu với chi phí là độ phức tạp nền tảng; hệ phân tích thời gian thực thắng khi cần tổng hợp độ trễ thấp trên luồng nạp lớn với chi phí là hạn chế về cập nhật, phép kết và vận hành; truy vấn liên kết nhiều nguồn thắng khi cần hỏi xuyên nguồn với chi phí là khả năng đẩy điều kiện xuống nguồn; engine nhúng thắng cho phân tích cục bộ với chi phí là đồng thời và quy mô. Nộp một bản ghi quyết định kiến trúc cho ba khối lượng công việc, mỗi ô dẫn một số đo từ lab của chính mình.",
"Nộp bản ghi quyết định chọn engine cho ba khối lượng công việc, mỗi luận điểm gắn một số đo của chính mình.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một quyết định có bằng chứng. Kiểm bằng rà soát bản ghi quyết định; đạt khi không luận điểm nào chỉ có tính từ và mỗi khối lượng công việc có ngưỡng chi phí kèm hai điều kiện đảo ngược.",
"Dựng cùng khối lượng công việc trên ít nhất hai engine thuộc hai nguyên mẫu. Đo byte quét, thời gian, hành vi dưới đồng thời, và chi phí, với trạng thái đệm được kiểm soát theo lesson 213. So năm nguyên mẫu trên bốn tiêu chí cho ba khối lượng công việc. Viết bản ghi quyết định kèm ngưỡng chi phí và điều kiện đảo ngược.",
"Chọn bằng danh sách tính năng của nhà cung cấp · so một lần chạy nóng với một lần chạy lạnh · bỏ chi phí vận hành khỏi so sánh · khuyến nghị không có điều kiện đảo ngược.",
"Mọi luận điểm gắn một số đo của chính mình, trạng thái đệm được kiểm soát trong mọi phép so, và mỗi khối lượng công việc có ngưỡng chi phí cùng hai điều kiện đảo ngược."),
]

M13 = ("File, Serialization and Open Table Formats", 217, 230, """| | |
|---|---|
| **Objective cấp module** | Chọn cách biểu diễn dữ liệu và giao thức chốt giao dịch, rồi vận hành tiến hoá lược đồ, tiến hoá phân vùng, gộp tệp và quay lại trạng thái cũ một cách an toàn |
| **Tiền đề** | M4 · M10 · M12 |
| **Exit criterion** | Nói được chính xác đơn vị nào được đọc và đơn vị nào bị cắt tỉa cho từng định dạng; mô tả được giao thức chốt nguyên tử và cách phát hiện xung đột mà không dùng chữ ACID thay cho lời giải thích |
| **Kỹ năng SFIA** | `DBAD` mức 4 · `DATM` mức 4 |
| **Chế độ hỏng** | Xoá tệp dữ liệu bằng tay, chạy dọn tệp mồ côi mà không kiểm thời hạn giữ và tham chiếu, hoặc tuyên bố đạt đúng một lần chỉ vì bảng chốt giao dịch nguyên tử |""",
"""Module tách ba khái niệm hay bị gọi lẫn: **định dạng tệp** quy định byte trên đĩa, **định dạng bảng** quy định tệp nào thuộc bảng tại thời điểm nào, và **danh mục** quy định tên bảng trỏ tới siêu dữ liệu nào.

Tách được ba khái niệm này là điều kiện để hiểu vì sao kho đối tượng không có thao tác đổi tên thư mục nguyên tử lại sinh ra cả một lớp phần mềm mới.

Chuẩn tương thích lấy từ M7 và M8 nay áp vào lược đồ dữ liệu, với một khác biệt: bên đọc và bên ghi ở đây thường là hai hệ khác nhau, chạy hai phiên bản thư viện khác nhau, và không ai điều phối được thời điểm chúng nâng cấp.""")

L13 = [
(217,"CSV and JSON - the ambiguity you inherit","TH","Module 13: M12",
"Hai định dạng phổ biến nhất và cũng mơ hồ nhất, nên bài này liệt kê chính xác những gì chúng không quy định. Với định dạng phân tách bằng dấu: ký tự phân tách, cách trích dẫn, cách thoát, bảng mã ký tự, cách biểu diễn giá trị rỗng, và kiểu dữ liệu đều không có trong tệp; bên đọc phải đoán, và hai bên đoán khác nhau là nguồn của lỗi âm thầm. Khả năng chia tệp để đọc song song bị phá khi có ký tự xuống dòng nằm trong giá trị được trích dẫn. Với định dạng đối tượng lồng nhau: tự mô tả nên không cần lược đồ ngoài, đổi lại tốn dung lượng và tốn thời gian phân tích; **số lớn mất độ chính xác và dấu thời gian không có ngữ nghĩa múi giờ** là hai chỗ hỏng hay gặp. Dạng mỗi dòng một đối tượng chia tệp được nên dùng được cho đường dẫn dữ liệu lớn. Khi nào hai định dạng này vẫn là lựa chọn đúng: trao đổi với bên ngoài và dữ liệu thô khi nạp.",
"Liệt kê những gì hai định dạng không quy định và tái hiện ba lỗi do khác giả định giữa bên ghi và bên đọc.",
"Tầng *áp dụng*. Bài mở module, kiểm bằng phép thử vòng tròn. Kiểm bằng ba lỗi tái hiện; đạt khi cả ba được tái hiện, chẩn đoán đúng, và chặn bằng một khai báo tường minh.",
"Ghi cùng dữ liệu ra hai định dạng. Tái hiện ba lỗi: giá trị rỗng bị đọc thành chuỗi rỗng, số lớn mất độ chính xác, và dấu thời gian lệch múi giờ. Với mỗi lỗi, chỉ ra giả định nào khác nhau giữa hai bên và khai báo tường minh chặn nó. Tạo một tệp có xuống dòng trong giá trị trích dẫn và chứng minh không chia được.",
"Giả định bên đọc hiểu giá trị rỗng giống bên ghi · để số định danh dài đi qua định dạng đối tượng lồng nhau · tin tệp phân tách bằng dấu luôn chia được · suy kiểu dữ liệu từ một mẫu nhỏ đầu tệp.",
"Ba lỗi được tái hiện và chặn bằng khai báo tường minh, và tệp không chia được được chứng minh."),

(218,"Avro and schema resolution","TH","Lesson 217",
"Định dạng theo hàng có lược đồ đi kèm, và cơ chế đáng học nhất của nó là phép phân giải lược đồ. Lược đồ của bên ghi được lưu cùng dữ liệu; bên đọc có lược đồ riêng; thư viện đối chiếu hai lược đồ và quyết định đọc được hay không. Quy tắc đối chiếu theo tên trường, nên **đổi tên một trường là thay đổi phá vỡ dù kiểu dữ liệu không đổi**, và bí danh là cơ chế duy nhất cứu được. Giá trị mặc định cho phép bên đọc mới đọc dữ liệu cũ thiếu trường. Cấu trúc theo khối cho phép chia tệp để đọc song song. Vì sao định dạng theo hàng vẫn dùng ở tầng nạp dù tầng phân tích dùng định dạng cột: bên ghi thêm từng bản ghi, và tiến hoá lược đồ đơn giản hơn. Phân biệt giải mã được về cú pháp với tương thích về ngữ nghĩa: đọc không lỗi không có nghĩa là hiểu đúng.",
"Cài phép phân giải lược đồ cho bốn loại thay đổi và phân biệt giải mã được với hiểu đúng.",
"Tầng *áp dụng*. Objective đòi phân biệt hai mức tương thích mà một mức không có thông báo lỗi. Kiểm bằng bốn thay đổi; đạt khi dự đoán đúng kết quả cả bốn và chỉ ra được ca giải mã sạch nhưng sai nghĩa.",
"Định nghĩa lược đồ có đủ giá trị rỗng, mặc định, dấu thời gian và số thập phân. Thực hiện bốn thay đổi: thêm trường có mặc định, bỏ trường, đổi tên trường, và đổi kiểu. Với mỗi cái, dự đoán kết quả rồi kiểm. Tạo một thay đổi giải mã sạch nhưng đổi nghĩa và chỉ ra vì sao không có lỗi nào được báo.",
"Đổi tên trường mà không đặt bí danh · thêm trường bắt buộc không có mặc định · coi giải mã không lỗi là tương thích · kiểm tương thích chỉ theo một chiều.",
"Dự đoán đúng kết quả cả bốn thay đổi, và ca giải mã sạch nhưng sai nghĩa được chỉ ra kèm giải thích."),

(219,"Protobuf - field numbers and wire compatibility","TH","Lesson 218",
"Định dạng thứ hai, khác ở chỗ danh tính trường là một con số chứ một cái tên. Trên đường truyền chỉ có số hiệu trường và kiểu mã hoá, nên **đổi tên trường là an toàn còn dùng lại một số hiệu đã bỏ là thảm hoạ**, đúng ngược với định dạng ở bài trước. Quy tắc tương thích suy ra trực tiếp từ đó: thêm trường mới với số hiệu mới thì an toàn; bỏ trường thì phải giữ số hiệu đó ở trạng thái đã đặt chỗ để không ai dùng lại; đổi kiểu chỉ an toàn trong một số cặp kiểu tương thích trên đường truyền. Trường không nhận ra được giữ nguyên hay bị bỏ tuỳ phiên bản thư viện, và điều đó quyết định một bên trung gian có làm mất dữ liệu không. Vì sao định dạng này là lựa chọn cho hợp đồng sự kiện và cho giao thức gọi hàm từ xa ở lesson 101. So sánh với bài trước theo bốn tiêu chí.",
"Xây ma trận tương thích cho bốn thay đổi và chứng minh hậu quả của việc dùng lại số hiệu trường.",
"Tầng *áp dụng*. Objective có một ca hỏng đặc trưng cần tái hiện bằng dữ liệu thật. Kiểm bằng bốn thay đổi cộng ca dùng lại số hiệu; đạt khi dự đoán đúng cả bốn và ca dùng lại số hiệu cho thấy dữ liệu bị diễn giải sai.",
"Định nghĩa hợp đồng sự kiện. Thực hiện bốn thay đổi gồm đổi tên, thêm trường, bỏ trường có đặt chỗ, và bỏ trường không đặt chỗ rồi dùng lại số hiệu. Mã hoá bằng phiên bản cũ và giải mã bằng phiên bản mới cùng chiều ngược lại. Chỉ ra ca dùng lại số hiệu cho giá trị bị diễn giải sai mà không báo lỗi.",
"Dùng lại số hiệu trường đã bỏ · giả định đổi tên là thay đổi phá vỡ như ở định dạng trước · bỏ qua hành vi của bên trung gian với trường không nhận ra · chỉ kiểm một chiều tương thích.",
"Dự đoán đúng cả bốn thay đổi, và ca dùng lại số hiệu cho thấy giá trị bị diễn giải sai mà không có lỗi."),

(220,"The compatibility matrix - writer old, reader new","TH","Lesson 219",
"Bài gom hai bài trước thành một quy trình kiểm bắt buộc. Ma trận tương thích có bốn ô: bên ghi cũ với bên đọc cũ, bên ghi cũ với bên đọc mới, bên ghi mới với bên đọc cũ, và bên ghi mới với bên đọc mới. Ba mức tương thích và ý nghĩa vận hành: tương thích ngược cho phép nâng cấp bên đọc trước, tương thích xuôi cho phép nâng cấp bên ghi trước, và tương thích đầy đủ cho phép nâng cấp theo thứ tự bất kỳ. **Mức tương thích quyết định thứ tự triển khai**, nên chọn mức là quyết định vận hành chứ quyết định kỹ thuật thuần tuý. Bản ghi vàng: một tập bản ghi mẫu được giữ cố định, mã hoá bằng mọi phiên bản và giải mã bằng mọi phiên bản, chạy trong tích hợp liên tục theo lesson 96. Sổ đăng ký lược đồ cưỡng chế quy tắc tương thích tại thời điểm đăng ký, nên một thay đổi phá vỡ bị chặn trước khi tới môi trường chạy.",
"Dựng ma trận bốn ô chạy tự động trên bản ghi vàng và chặn được một thay đổi phá vỡ trước khi hợp nhất.",
"Tầng *áp dụng*. Objective là một cửa chặn tự động có tiêu chí nghiệm thu bằng phép thử tiêm. Kiểm bằng ba thay đổi phá vỡ tiêm; đạt khi cả ba bị chặn và mỗi ô của ma trận có kết quả rõ.",
"Dựng bộ bản ghi vàng cho một hợp đồng. Viết bộ kiểm chạy đủ bốn ô ma trận trên ba phiên bản lược đồ. Đưa vào tích hợp liên tục có cửa chặn. Tiêm ba thay đổi phá vỡ khác loại và xác nhận cả ba bị chặn kèm thông báo chỉ rõ ô nào hỏng. Chọn mức tương thích cho hợp đồng và nêu thứ tự triển khai kéo theo.",
"Chỉ kiểm ô bên ghi mới với bên đọc mới · không có bản ghi vàng nên mỗi lần kiểm một bộ dữ liệu khác · chọn mức tương thích mà không suy ra thứ tự triển khai · để sổ đăng ký ở chế độ không cưỡng chế.",
"Ba thay đổi phá vỡ đều bị chặn kèm thông báo chỉ đúng ô hỏng, và mức tương thích chọn kèm thứ tự triển khai."),

(221,"Parquet internals - row group, column chunk, page","TH","Lesson 220",
"Định dạng cột chính của hệ sinh thái phân tích, và hiểu cấu trúc của nó là điều kiện để giải thích mọi hành vi hiệu năng ở M12. Bốn mức lồng nhau: tệp chứa nhiều nhóm hàng, mỗi nhóm hàng chứa một khối cột cho mỗi cột, mỗi khối cột chứa nhiều trang, và chân tệp chứa siêu dữ liệu cùng thống kê. **Đơn vị cắt tỉa là nhóm hàng, đơn vị đọc là trang**, và trả lời được hai câu đó cho mỗi định dạng là tiêu chí ra module. Kích thước nhóm hàng là đánh đổi trung tâm: nhóm lớn cho nén tốt và ít siêu dữ liệu nhưng cắt tỉa thô và tốn bộ nhớ khi đọc; nhóm nhỏ cho cắt tỉa mịn nhưng sinh nhiều siêu dữ liệu. Chân tệp nằm ở cuối nên bên đọc phải đọc cuối tệp trước, điều có hệ quả trên kho đối tượng. Mức lặp và mức định nghĩa cho cấu trúc lồng nhau ở mức nhận biết.",
"Đọc siêu dữ liệu thật của một tệp và giải thích đơn vị nào được cắt tỉa, đơn vị nào được đọc.",
"Tầng *phân tích*. Objective đòi nối cấu trúc tệp với số đo hiệu năng. Kiểm bằng ba kích thước nhóm hàng đo song song; đạt khi ba đánh đổi đều có số và lựa chọn dẫn được từ số đó.",
"Ghi cùng dữ liệu với ba kích thước nhóm hàng. Đọc siêu dữ liệu chân tệp của cả ba và ghi lại số nhóm hàng, kích thước khối cột và thống kê. Chạy bộ truy vấn và đo byte đọc, số nhóm hàng bị cắt, bộ nhớ đỉnh. Chọn kích thước cho khối lượng công việc và dẫn từ ba số đo.",
"Nhầm đơn vị cắt tỉa với đơn vị đọc · đặt kích thước nhóm hàng theo giá trị mặc định mà không đo · sinh nhóm hàng rất nhỏ rồi ngạc nhiên vì siêu dữ liệu phình · không bao giờ đọc chân tệp thật.",
"Siêu dữ liệu chân tệp của ba phương án được đọc và ghi lại, và lựa chọn kích thước nhóm hàng dẫn được từ ba số đo."),

(222,"Encoding choice, statistics and pushdown","TH","Lesson 221",
"Bài nối cấu trúc tệp ở bài trước với hai cơ chế đã học ở M12, lần này ở phía bên ghi. Chọn cách mã hoá cho từng cột theo số giá trị phân biệt và phân bố, theo đúng ma trận ở lesson 205, nhưng nay quyết định nằm trong tham số ghi tệp. Thống kê tối thiểu lớn nhất và số giá trị rỗng ghi ở mức nhóm hàng và mức trang; chỉ mục trang cho cắt tỉa mịn hơn. Đẩy điều kiện lọc xuống tầng đọc và đẩy danh sách cột xuống tầng đọc là hai cơ chế khác nhau và phải kiểm riêng: một cái giảm số nhóm hàng đọc, cái kia giảm số cột đọc. Ba điều kiện làm đẩy điều kiện xuống thất bại, giống ba nguyên nhân ở lesson 206. Cột có phân bố rải đều làm thống kê vô dụng, nên sắp xếp trước khi ghi là bước quyết định, và đó là cùng một lập luận đã dùng ở lesson 209.",
"Cấu hình bên ghi để đạt cả hai cơ chế đẩy xuống và chứng minh bằng số byte đọc tách theo từng cơ chế.",
"Tầng *áp dụng*. Objective đòi tách hai cơ chế thường bị gộp. Kiểm bằng bốn cấu hình đo song song; đạt khi phần đóng góp của mỗi cơ chế được tách riêng và tổng khớp phép đo đầy đủ.",
"Ghi bảng với bốn cấu hình: không sắp xếp, sắp theo cột lọc, có chỉ mục trang, và cả hai. Chạy truy vấn chọn ít cột kèm điều kiện lọc hẹp. Với mỗi cấu hình, đo byte đọc khi chỉ bật đẩy cột, khi chỉ bật đẩy điều kiện, và khi bật cả hai. Chứng minh phần đóng góp cộng lại xấp xỉ phép đo đầy đủ.",
"Gộp hai cơ chế đẩy xuống thành một số đo · sắp xếp theo cột không dùng để lọc · tin thống kê tồn tại là cắt tỉa hoạt động · ghi cột phân bố rải đều rồi mong cắt tỉa.",
"Phần đóng góp của hai cơ chế được tách riêng ở cả bốn cấu hình, và tổng khớp phép đo đầy đủ trong sai số thoả thuận."),

(223,"Nested schemas, timestamps and decimal interoperability","TH","Lesson 222",
"Ba chỗ mà hai hệ đọc cùng một tệp lại cho hai kết quả, và cả ba đều không báo lỗi. Cấu trúc lồng nhau: mảng và bản ghi con được biểu diễn bằng mức lặp và mức định nghĩa, và tiến hoá một trường bên trong cấu trúc lồng nhau có quy tắc khác với trường ở mức trên. Dấu thời gian: độ phân giải mili giây hay micro giây, có gắn múi giờ hay không, và hai hệ có thể hiểu cùng một cột theo hai cách; **đây là nguồn lệch số liệu theo ngày phổ biến nhất khi nhiều engine cùng đọc một bảng**. Số thập phân: độ chính xác và phần thập phân được biểu diễn khác nhau giữa các hệ, nên tiền tệ đi qua nhiều hệ có thể bị làm tròn khác nhau. Nguyên tắc chung: với mỗi kiểu dữ liệu nhạy cảm, một phép thử vòng tròn qua mọi engine sẽ đọc bảng, chạy tự động chứ làm một lần rồi tin.",
"Chạy phép thử vòng tròn ba kiểu dữ liệu nhạy cảm qua nhiều engine và phát hiện ít nhất một chỗ lệch.",
"Tầng *phân tích*. Objective đòi phát hiện một lệch không báo lỗi giữa hai hệ. Kiểm bằng phép thử vòng tròn; đạt khi phát hiện ít nhất một chỗ lệch, chẩn đoán đúng nguyên nhân, và chặn bằng một ràng buộc ở bên ghi.",
"Ghi một bảng có cấu trúc lồng nhau, dấu thời gian ở hai độ phân giải, và cột tiền tệ dạng số thập phân. Đọc bằng ít nhất hai engine và so từng giá trị chứ so tổng. Chỉ ra chỗ lệch, chẩn đoán, và chặn bằng cách cố định biểu diễn ở bên ghi. Đưa phép thử vòng tròn vào chạy tự động.",
"So bằng tổng nên lệch làm tròn bị che · để độ phân giải dấu thời gian do giá trị mặc định quyết · dùng số dấu chấm động cho tiền tệ · kiểm vòng tròn một lần rồi coi như xong.",
"Ít nhất một chỗ lệch được phát hiện và chẩn đoán đúng, và phép thử vòng tròn chạy tự động."),

(224,"Object store limits and why a table format exists","LT","Lesson 223",
"Bài giải thích vì sao có cả một lớp phần mềm nằm giữa tệp và bảng. Kho đối tượng không phải hệ thống tệp: không có thao tác đổi tên thư mục nguyên tử, danh sách đối tượng có thể không phản ánh ngay trạng thái mới, và đối tượng là bất biến nên sửa nghĩa là ghi đối tượng mới. Hệ quả trực tiếp và là lý do tồn tại của định dạng bảng: cách làm cũ dùng một thư mục làm một phân vùng rồi ghi đè bằng đổi tên thư mục không còn nguyên tử, nên bên đọc có thể thấy trạng thái nửa vời. Ba khái niệm phải tách rõ: định dạng tệp quy định byte, định dạng bảng quy định tệp nào thuộc bảng tại thời điểm nào, và danh mục quy định tên bảng trỏ tới siêu dữ liệu nào. **Nói ACID mà không mô tả được cơ chế là dấu hiệu chưa hiểu**, và ranh giới đúng là nguyên tử cùng cô lập ở mức một bảng chứ xuyên bảng.",
"Tách ba khái niệm và mô tả chính xác vấn đề mà định dạng bảng giải, không dùng chữ ACID thay lời giải thích.",
"Tầng *hiểu*. Bài lý thuyết bản lề, chuyển từ định dạng tệp sang định dạng bảng. Kiểm bằng bài lập luận; đạt khi tách đúng ba khái niệm và mô tả được ranh giới bảo đảm mà không dùng từ viết tắt thay cơ chế.",
"Tái hiện vấn đề trên kho đối tượng: ghi một tập tệp mới rồi dừng giữa chừng, và chứng minh bên đọc thấy trạng thái nửa vời khi dùng cách theo thư mục. Phân loại mười thành phần vào ba khái niệm. Viết một đoạn mô tả chính xác bảo đảm mà định dạng bảng cho và không cho.",
"Coi kho đối tượng như hệ thống tệp · dùng chữ ACID thay cho mô tả cơ chế · nhầm định dạng bảng với engine lưu trữ · giả định bảo đảm có hiệu lực xuyên nhiều bảng.",
"Mười thành phần phân đúng ba khái niệm, trạng thái nửa vời được tái hiện, và mô tả bảo đảm không dùng từ viết tắt thay cơ chế."),

(225,"The metadata tree - snapshot, manifest list, manifest","TH","Lesson 224",
"Cấu trúc siêu dữ liệu của định dạng bảng mở, học bằng cách đọc tệp thật chứ đọc sơ đồ. Bốn tầng: tệp siêu dữ liệu của bảng giữ lược đồ, quy tắc phân vùng và danh sách ảnh chụp; mỗi ảnh chụp trỏ tới một danh sách kê khai; mỗi kê khai liệt kê các tệp dữ liệu kèm thống kê và giá trị phân vùng; tệp dữ liệu là bất biến. Vì sao cấu trúc này cho phép lập kế hoạch nhanh: engine đọc kê khai để loại bỏ tệp mà không chạm tệp dữ liệu, tức cắt tỉa xảy ra ở tầng siêu dữ liệu trước khi tới tầng tệp. Danh mục giữ một con trỏ tới tệp siêu dữ liệu hiện hành, và **con trỏ đó là thứ duy nhất phải đổi nguyên tử**. Đi ngược cây từ một dòng dữ liệu về tới ảnh chụp là bài tập cốt lõi. Siêu dữ liệu phình khi có quá nhiều ảnh chụp hoặc quá nhiều tệp nhỏ.",
"Đọc chuỗi siêu dữ liệu thật của một bảng và giải thích một dòng dữ liệu thuộc ảnh chụp nào.",
"Tầng *phân tích*. Objective đòi đọc cấu trúc thật thay vì mô tả nó. Kiểm bằng bài truy ngược; đạt khi truy đúng đường từ dòng dữ liệu về ảnh chụp và giải thích đúng nơi cắt tỉa siêu dữ liệu xảy ra.",
"Dựng một bảng và ghi ba lần. Mở tệp siêu dữ liệu, danh sách kê khai và kê khai của từng ảnh chụp, ghi lại nội dung. Chọn một dòng dữ liệu và truy ngược về tệp dữ liệu, kê khai, ảnh chụp. Chạy truy vấn có lọc theo phân vùng và chỉ ra bao nhiêu tệp bị loại ở tầng kê khai trước khi mở tệp nào.",
"Học cấu trúc qua sơ đồ mà không mở tệp thật · nhầm ảnh chụp với phiên bản lược đồ · bỏ qua vai trò của danh mục · không đo số tệp bị loại ở tầng siêu dữ liệu.",
"Truy đúng đường từ một dòng dữ liệu về ảnh chụp qua đủ bốn tầng, và số tệp bị loại ở tầng kê khai được đo."),

(226,"The commit protocol and atomic visibility","TH","Lesson 225",
"Giao thức chốt giao dịch gồm năm bước, và hiểu năm bước này là hiểu toàn bộ bảo đảm của định dạng bảng. Bên ghi tạo các tệp dữ liệu bất biến; bên ghi tạo kê khai và tệp siêu dữ liệu mới trỏ tới các tệp đó cùng ảnh chụp cơ sở; danh mục đổi con trỏ bằng một thao tác so sánh rồi đặt, và **đây là bước duy nhất công bố thay đổi**; phát hiện xung đột quyết định thử lại hay báo lỗi; bảo trì ghi lại dữ liệu và siêu dữ liệu, hết hạn ảnh chụp cũ và xoá tệp mồ côi an toàn. Hệ quả quan trọng nhất và là điều phải chứng minh bằng thực nghiệm: nếu bên ghi chết trước bước ba thì các tệp đã ghi tồn tại trên kho đối tượng nhưng **không thuộc bảng**, nên bên đọc không bao giờ thấy chúng. Bên đọc ghim một ảnh chụp cho toàn bộ truy vấn nên nó thấy một trạng thái nhất quán. Du hành thời gian là hệ quả miễn phí của việc giữ các ảnh chụp cũ.",
"Chứng minh bằng thực nghiệm rằng tệp chưa chốt không hiện ra với bên đọc, và lập được kế hoạch dọn chúng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu bằng một thí nghiệm hỏng có chủ ý. Kiểm bằng thí nghiệm dừng giữa chừng; đạt khi bên đọc không thấy dòng nào của lần ghi hỏng và tệp mồ côi được xác định đúng.",
"Ghi một lô dữ liệu và dừng tiến trình sau bước hai nhưng trước bước ba. Đếm tệp trên kho đối tượng và đếm dòng bảng thấy được; chứng minh hai số không khớp và bảng vẫn đúng. Xác định đúng tập tệp mồ côi bằng cách đối chiếu với kê khai. Chạy du hành thời gian về ảnh chụp trước đó và đối soát.",
"Xoá tệp lạ trên kho đối tượng bằng tay · cho rằng tệp đã ghi là đã thuộc bảng · dọn tệp mồ côi ngay mà không chờ hết thời hạn giữ · nhầm du hành thời gian với sao lưu.",
"Bên đọc không thấy dòng nào của lần ghi hỏng, tập tệp mồ côi được xác định đúng bằng đối chiếu kê khai, và du hành thời gian đối soát khớp."),

(227,"Optimistic concurrency and conflict detection","TH","Lesson 226",
"Nhiều bên ghi cùng một bảng và cơ chế giải quyết là lạc quan chứ khoá, giống nguyên tắc đã gặp ở lesson 104. Mỗi bên ghi đọc ảnh chụp cơ sở, làm việc, rồi thử đổi con trỏ với điều kiện ảnh chụp cơ sở chưa đổi; nếu đã đổi thì thao tác so sánh rồi đặt thất bại và bên ghi phải quyết định thử lại hay báo lỗi. Ba loại xung đột và cách xử lý khác nhau: hai bên cùng thêm dữ liệu vào phân vùng khác nhau thường thử lại được; hai bên cùng sửa cùng tập tệp thì phải báo lỗi vì thử lại có thể mất thay đổi; và một bên chạy bảo trì trong khi bên kia ghi. **Thử lại vô điều kiện là lỗi nghiêm trọng** vì nó có thể làm mất thay đổi của bên kia. Chi phí khi tranh chấp cao: mọi bên ghi làm việc rồi hỏng ở bước cuối, nên thông lượng sụp; cách giảm là giảm số bên ghi hoặc tách phạm vi ghi.",
"Tái hiện ba loại xung đột và chọn đúng hành vi thử lại hay báo lỗi cho từng loại.",
"Tầng *phân tích*. Objective đòi phân biệt ca thử lại an toàn với ca thử lại làm mất dữ liệu. Kiểm bằng ba xung đột tái hiện; đạt khi cả ba được chẩn đoán đúng và không ca nào thử lại làm mất thay đổi.",
"Chạy hai bên ghi song song vào cùng bảng ở ba kịch bản. Với mỗi kịch bản, ghi lại thao tác nào thất bại và vì sao. Cài chính sách thử lại phân biệt ba loại. Chứng minh bằng đối soát rằng không thay đổi nào bị mất. Tăng số bên ghi và đo thông lượng sụp ở mức nào.",
"Thử lại mọi xung đột · không đối soát sau khi thử lại · chạy bảo trì trong giờ ghi cao điểm · tăng bên ghi để tăng thông lượng khi tranh chấp đã cao.",
"Ba loại xung đột được chẩn đoán đúng, đối soát chứng minh không mất thay đổi nào, và ngưỡng sụp thông lượng được đo."),

(228,"Hidden partitioning, partition evolution and schema field IDs","TH","Lesson 227",
"Hai tính năng giải hai vấn đề vận hành mà cách làm theo thư mục không giải được. Phân vùng ẩn: người dùng lọc theo cột gốc, còn định dạng bảng tự suy ra giá trị phân vùng từ một phép biến đổi khai báo sẵn; nhờ vậy **không còn lỗi quên thêm điều kiện lọc theo cột phân vùng**, một lỗi tốn kém và im lặng trong cách làm cũ. Tiến hoá phân vùng: đổi quy tắc phân vùng cho dữ liệu mới mà không phải ghi lại dữ liệu cũ, vì mỗi tệp mang theo giá trị phân vùng của nó; đây là lý do siêu dữ liệu phải lưu phép biến đổi chứ chỉ lưu giá trị. Danh tính trường bằng số hiệu chứ bằng tên, cùng nguyên lý với lesson 219: nhờ đó đổi tên cột là thao tác an toàn, còn bên đọc dựa theo tên thì hỏng. Tiến hoá lược đồ gồm thêm, bỏ, đổi tên và mở rộng kiểu, mỗi loại có quy tắc riêng.",
"Thực hiện tiến hoá phân vùng và tiến hoá lược đồ trên bảng có dữ liệu cũ, chứng minh truy vấn cũ vẫn đúng.",
"Tầng *áp dụng*. Objective có tiêu chí nghiệm thu là dữ liệu cũ và mới cùng đọc đúng sau khi đổi quy tắc. Kiểm bằng đối soát bắc qua ranh giới tiến hoá; đạt khi truy vấn phủ cả hai vùng cho kết quả khớp bản tính tay.",
"Dựng bảng phân vùng ẩn theo tháng, nạp dữ liệu. Đổi quy tắc phân vùng sang theo ngày và nạp tiếp, không ghi lại dữ liệu cũ. Chạy truy vấn phủ cả hai vùng và đối soát với bản tính tay. Đổi tên một cột và chứng minh truy vấn cũ theo tên mới vẫn đọc đúng dữ liệu cũ. Kiểm cắt tỉa còn hoạt động ở cả hai vùng.",
"Ghi lại toàn bộ dữ liệu cũ khi đổi quy tắc phân vùng · dùng bên đọc dựa theo tên cột · đổi quy tắc phân vùng mà không kiểm cắt tỉa ở vùng cũ · bỏ đối soát bắc qua ranh giới.",
"Truy vấn phủ cả hai vùng khớp bản tính tay, đổi tên cột không làm hỏng dữ liệu cũ, và cắt tỉa còn hoạt động ở cả hai vùng."),

(229,"Maintenance project - deletes, compaction and safe cleanup","DA","Lesson 228",
"Bài dự án khép module, và là phần vận hành mà bỏ qua thì bảng tự hỏng theo thời gian. Hai mô hình xoá: xoá theo vị trí ghi lại dòng nào trong tệp nào bị xoá, xoá theo giá trị ghi điều kiện; mỗi mô hình có chi phí đọc khác nhau, và tệp xoá tích luỹ làm mọi truy vấn chậm dần cho tới khi được hợp nhất. Gộp tệp giải quyết cả tệp nhỏ lẫn tệp xoá tích luỹ, và nó phải chạy được song song với bên ghi theo lesson 227. Ba thao tác bảo trì có thứ tự bắt buộc và điều kiện an toàn: gộp tệp, hết hạn ảnh chụp cũ, rồi dọn tệp mồ côi. **Dọn tệp mồ côi là thao tác nguy hiểm nhất**: nó xoá tệp không được kê khai nào tham chiếu, nên nếu thời hạn giữ ngắn hơn thời gian một lần ghi đang chạy thì nó xoá mất tệp sống. Điều kiện an toàn bắt buộc: thời hạn giữ lớn hơn lần ghi dài nhất, và không bao giờ xoá tệp bằng tay.",
"Vận hành đủ ba thao tác bảo trì an toàn trên bảng đang có bên ghi, không mất dòng nào và quay lại được trạng thái cũ.",
"Tầng *sáng tạo*. Bài tổng hợp toàn module thành một quy trình vận hành có tiêu chí an toàn kiểm được. Kiểm bằng đối soát trước sau cộng phép thử quay lại; đạt khi số dòng khớp tuyệt đối qua mọi thao tác và quay lại được ảnh chụp trước bảo trì.",
"Tạo hàng nghìn tệp nhỏ và một lượng tệp xoá đáng kể; đo thời gian quét và kích thước siêu dữ liệu. Chạy gộp tệp trong khi một bên ghi vẫn đang thêm dữ liệu; đo lại và đối soát số dòng. Hết hạn ảnh chụp với thời hạn giữ có căn cứ. Chạy dọn tệp mồ côi và chứng minh thời hạn giữ lớn hơn lần ghi dài nhất. Quay lại một ảnh chụp trước đó và đối soát.",
"Xoá tệp dữ liệu bằng tay · dọn tệp mồ côi với thời hạn giữ mặc định mà không đo lần ghi dài nhất · hết hạn ảnh chụp còn cần cho quay lại · gộp tệp mà không đối soát số dòng.",
"Số dòng khớp tuyệt đối qua cả ba thao tác, thời hạn giữ được chứng minh lớn hơn lần ghi dài nhất, và quay lại ảnh chụp trước bảo trì thành công."),

(230,"Gate 6 - explain a metadata chain and survive a concurrent write","KT","Lesson 229",
"Cổng của Phase 6. Bài kiểm hai module: cơ chế engine phân tích ở M12 và định dạng tệp cùng định dạng bảng ở M13. Không có nội dung mới.",
"Giải thích một chuỗi siêu dữ liệu thật, chứng minh tính hiển thị nguyên tử dưới ghi đồng thời, và chọn engine bằng số đo của chính mình.",
"Tầng *đánh giá*. Cổng đo năng lực giải thích cơ chế và vận hành an toàn, nên hình thức là thực hành tại chỗ cộng bảo vệ.",
"Buổi 150 phút: 105 phút làm bài độc lập, 45 phút chữa bài. Bài chấm sáu phần: A (20đ) tách bốn phần đóng góp làm hệ cột nhanh, mỗi phần một số đo riêng · B (15đ) chẩn đoán một truy vấn phân tán chậm, phân biệt lệch tải với tràn đĩa với hàng đợi · C (20đ) đọc chuỗi siêu dữ liệu thật và truy một dòng dữ liệu về ảnh chụp · D (20đ) chạy hai bên ghi đồng thời, chỉ ra thao tác nào thất bại và vì sao, chứng minh không mất thay đổi · E (15đ) ma trận tương thích bốn ô cho một thay đổi lược đồ · F (10đ) khuyến nghị engine cho một khối lượng công việc, mọi luận điểm gắn số đo.",
"Dùng chữ ACID thay cho mô tả giao thức chốt · so tốc độ giữa lần chạy nóng và lần chạy lạnh · thử lại mọi xung đột ghi · chọn engine bằng danh sách tính năng.",
"Đạt ≥ 70/100, phần C và D đều ≥ 60%. Xoá tệp dữ liệu bằng tay trong phần D thì phần đó bằng không; khuyến nghị engine không có số đo thì phần F bằng không."),
]
